### ISSUE TITLE
Sitreps do not generate for first turn

### ISSUE THREAD

**Issue by dbenage-cx** [freeorion/freeorion#1004]
### Environment
- **FreeOrion Version**: 0.4.6+
- **Operating System**: Linux
- **Graphic card used**: N/A
- **Fetched as**
  - Compiled from source
### Description

Sitreps for the first turn no longer display on game load or after clicking next turn.
Commenting out universe/Universe.cpp:2315-2320, introduced in 39bb074, displays these sitreps.
### Expected Result

Display of sitreps for Turn 1, at a minimum this would include the `Random Game Hints` sitrep.
### Steps to reproduce
- Start new game
- Sitreps for `initial turn` are displayed, `Back`, `Next,` and `Last` are greyed out.
- Click `Turn 1` for next turn.
- Sitreps for `Turn 2` are displayed
- Clicking `Back` displays sitreps for `Initial turn`

**Comment by willmotil** [comment]
He made these changes to test if they would fix a bug preventing if = conditions [ ... ]effects = [  ... SetMeter from executing ... ] Prior to this change, Setmeter code doesn't work at all preventing direct conditional jumps in if or ifelse and else subsequent effects[ ... SetStructure wont work  ... ]. 

 I was just about to try to compile fo for the first time and try the changes but im finding im getting tons of compile errors.

The primary script code is here http://www.freeorion.org/forum/viewtopic.php?f=15&t=10238 if you would like more details.

Sorry im the guy with the post xlightwavex

**Comment by geoffthemedio** [comment]
Should be fixed: https://github.com/freeorion/freeorion/commit/c345b3b469a01b1b11d060d846398eef18ba83ae

**Comment by dbenage-cx** [comment]
TY @geoffthemedio
