### ISSUE TITLE
Update AI to take into account Ancient Guardians

### ISSUE THREAD

**Issue by MatGB** [freeorion/freeorion#1012]
### Description

As of #1009 Ancient Guardians are a species that self destruct on conquest, the AI doesn't know how they work and in testing will deploy large fleets of troops to capture them without a backup warship to keep shields down. They have the tag "DESTROYED_ON_CONQUEST" as per @Morlic-fo's request.

**Comment by MatGB** [comment]
Not this issue but relevant: testing these highlighted how the AI doesn't seem to know how planetary shields block conquest, something we were already aware of but it's a lot more apparent with this.

**Comment by Vezzra** [comment]
@freeorion/ai-team, if possible that should be addressed for 0.4.7. Do you think you can do this, or should I set it to only "optional for 0.4.7"?

**Comment by Morlic-fo** [comment]
#1305 only adresses the self-destruction on conquest which is the only thing "special" about ancient guardians.

The shield issue is not specific to this species, Refer to #1013 instead.

**Comment by MatGB** [comment]
I do regularly see an AI world in the same system as guardians with huge piles of troop drops in orbit, 100+ troop drops will mess up an AI production substantially, if that at the very least could be reduced then the rest shouldn't be release blocking.

**Comment by Morlic-fo** [comment]
That is a more general issue that is unrelated to this particular species. It just is showcased because of the actual number but the problem lies deeper, thus
> Refer to #1013 instead.
