### ISSUE TITLE
AI Invasion problems

### ISSUE THREAD

**Issue by Morlic-fo** [freeorion/freeorion#1013]
### Description

There are currently issues with the AI invasions.
- The AI has problems invading planets with shields. Just send a military ship already, stupid!
- The AI generally leaves native planets unconquered for way too long. This indicates the priorities are off and need an overhaul

**Comment by LGM-Doyle** [comment]
ovarwa, commented on the AI invastion/ship deployment in http://freeorion.org/forum/viewtopic.php?f=28&t=10307&start=0 and I transcribed the relevant section.
- When the AI considers something a high priority, it will wisely congregate ships there. Yay! But then it sends out ships in onesy twosies to their deaths at lower priority targets, because it knows it needs to do _something_ but has no idea either going big or not going at all.
- The AI seems to know not to send an inferior force to a sector that already has a greatly superior enemy force. But it has no sense of history, and makes no use of its ability to see my detection range: If I leave the sector empty, it will repeatedly send a ship or two there, and I can move a fleet to the sector to wipe it out.
- When I have a large fleet besieging an enemy system with heavy industry, it builds things like scouts and outposts rather than ships with weapons that can abrade my force. If I plunk a colony down on an unoccupied planet of that system, it also builds lots of troop ships, which are also immediately destroyed without inflicting any damage.

**Comment by MatGB** [comment]
Re the planets with shields problem: it also seems to think that fighters reduce shields and stations fighter-only ships in orbit around high tech natives.

**Comment by Morlic-fo** [comment]
https://github.com/freeorion/freeorion/issues/1012#issuecomment-279231433
>I do regularly see an AI world in the same system as guardians with huge piles of troop drops in orbit, 100+ troop drops will mess up an AI production substantially, if that at the very least could be reduced then the rest shouldn't be release blocking.

**Comment by Vezzra** [comment]
Ok, all that sounds rather serious... @freeorion/ai-team, do you want to tackle this for 0.4.7, or should I leave it only as "optional for 0.4.7" (that is, fine if it can get done in time, but should not block the release)?

**Comment by Morlic-fo** [comment]
#1309 aims to resolve the issues regarding shields, fighters and the "ancient guardian problem". 

Testing and feedback appreciated.

**Comment by Dilvish-fo** [comment]
I think that #1309  has some significant issues, and unless I am misreading something there I don't think it would address the troop base issue at all.  I'll follow up with Morlic for more discussion on that.  Whether covered by 1309 or not, I do think we can get something in soon for the troop bases.

**Comment by Dilvish-fo** [comment]
Besides the troop bases for guardians planets, I think the biggest issue is that the 'securing' type military missions for invasion target planets will often fully release a turn or two too soon; they are intended to attack in force and then leave a smaller force behind to hold the place until the invasion completes, but it seems that smaller force is often thinking its job is done before it really is.

**Comment by Morlic-fo** [comment]
#1444 attempts to fix an invasion-related bug: The AI would sometimes allocate exactly as many troops as there are defenders. By requesting some more troops than there are defenders, the AI should always allocate enough troops.

However, as discussed in the comment there, additional checks during ongoing invasion missions are needed that would find and adress ongoing invasion missions with insufficient troops.

**Comment by Vezzra** [comment]
@freeorion/ai-team, have all the issues listed here been resolved, and can we close this, or do we need to keep it open?

**Comment by Dilvish-fo** [comment]
Hmm, I think that a higher priority for invading natives has not yet been explicitly addressed, but the changes of #1341 might very well have indirectly caused an improvement in that area.  I'll pay more attention to that for a while now and then decide about closing this.

**Comment by Vezzra** [comment]
Ok, thanks!

**Comment by Dilvish-fo** [comment]
Ah, I actually have been thinking that I am not really yet content with the priority the AI gives to invading undefended natives.  But I hadn't yet got to tinkering further with that.  Like many things for the AI, it could be just something that we continue to try to improve, we don't necessarily need an open issue for it, I suppose.  @Morlic-fo could you comment with your thinking?

**Comment by Morlic-fo** [comment]
The original issue was opened in the context of the state of invasion in 0.4.6+ where the AI would really struggle to get any invasions going at all, thus a non-focussed issue covering a multitude of problems made sense. In particular note the issue is labeled with bug. Since then, there were massive improvements to the AI invasion logic.

While there is of course plenty of room for improvement (as there is in all areas of the AI), I don't think it is worth keeping this issue open but would rather see a new one opened if you think the remaining point warrants it.

* This issue is labeled bug, the remaining point is not a bug / serious misbehavior
* The original intent of this issue has sufficiently been adressed about a year ago
* A single vague (yet specific compared to original scope of the issue) point remains
* The comments and linked PRs/commits are unrelated to the remaining point
