### ISSUE TITLE
loading older save leads to segfault

### ISSUE THREAD

**Issue by Voker57** [freeorion/freeorion#1025]
Save: http://dump.bitcheese.net/files/vyganeb/l_q_v.mps

**Comment by Vezzra** [comment]
Just to clarify: by "older save" you mean a save game from a previous version?

**Comment by geoffthemedio** [comment]
How are you loading the file? When I try to load it in the multiplayer lobby, it's not listed in the save files dialog, and the server log has

```
2016-10-07 10:26:58.303159 [error] Server : SaveGamePreviewUtils.cpp:92 : LoadSaveGamePreviewData: Failed to read preview of C:\Users\Geoff\AppData\Roaming\FreeOrion\save\.\l_q_v.mps because: unrecognized XML syntax
```

**Comment by Voker57** [comment]
@Vezzra yes.
@geoffthemedio the same old way, hosting a mp game then loading. maybe you need to enable compressed saves?

**Comment by geoffthemedio** [comment]
Enabling compressed saves doesn't affect loading; just saving.

What version are you trying to load with?

**Comment by Voker57** [comment]
v0.4.3-4969-gacc1a55

**Comment by geoffthemedio** [comment]
Is that what you're using to load it, or what was used to save it?

If the loading, that's 3 versions and 3 years out of date. If you have an issue in a recent build, particularly v0.4.6, then we might do something about it.

**Comment by Voker57** [comment]
Uh, it's recent git, here's commit acc1a55

**Comment by Voker57** [comment]
That's the loading version, saving one is several weeks earlier, can determine more specifically if needed

**Comment by geoffthemedio** [comment]
You wrote "v0.4.3", which is not "recent git".

**Comment by Voker57** [comment]
yeah, not sure why git describe shows me 0.4.3

**Comment by geoffthemedio** [comment]
Can you post the sever and client log files from immediately after opening the multiplayer file dialog and then selecting the old file, then trying to start the game with it?

**Comment by Voker57** [comment]
http://dump.bitcheese.net/files/wytemos/freeoriond.log
http://dump.bitcheese.net/files/zehuzeg/freeorion.log

**Comment by Voker57** [comment]
backtrace: http://dump.bitcheese.net/files/vuvinid/bt.txt

**Comment by Voker57** [comment]
I actually loaded different save to test, but it exhibits the same problem http://dump.bitcheese.net/files/gynutew/n_v_q_l.mps

**Comment by Vezzra** [comment]
Hm, first of all, loading a savegame of a previous version isn't guaranteed to work. The game being in alpha stage, we don't try to maintain savegame compatibility with older versions. Can you load the savegame with a build of the exact same FO version it has been created with?

The other thing is, I've peeked into the two savegames you linked to, and both of them look weird - I can see text parts which say "this is an XML save", but the header clearly isn't plain text, lot of non-text data in between the text parts. So both savegames are maybe corrupted.

**Comment by Vezzra** [comment]
I suggest to close this as "wontfix", as we currently don't intend to maintain savegame compatibility with savegames created by older versions. As nice as it would be to have that, I don't expect it before we enter the beta stage (meaning, in the far, far future). It just requires too  much effort to do this.

If the savegames @Voker57 linked to can't be loaded by builds of the exact same version of FO they have been created with, please create a new, separate issue.

Comments, objections?

**Comment by geoffthemedio** [comment]
This issue isn't about breaking savegame compatibility; it's about the game segfaulting when given a save that it should just refuse to load, or have an error when it tries to load and finds the save format is different.

That said, it appears to be breaking somewhere deep in the boost serialization code, and that may not be something we can fix.

**Comment by Vezzra** [comment]
Ok, makes sense.

**Comment by Vezzra** [comment]
What's the status on this? Any hope that we might be able to do anything about it? The fact that those saves might be corrupted anyway and that the error happens deep in boost serialization code suggests that this is probably a wontfix, so I lean toward closing it.

Or do you guys want to keep this open?

**Comment by geoffthemedio** [comment]
Renaming or making a new issue for avoiding crashes when loading old or broken saves might make sense...

**Comment by Vezzra** [comment]
Sounds reasonable.
