### ISSUE TITLE
Unable to invade

### ISSUE THREAD

**Issue by MatGB** [freeorion/freeorion#1027]
### Environment

- **FreeOrion Version**:  0.4.6,
- **Operating System**: w10 x64
- **Graphic card used**: ??
- **Fetched as** 
  - Binary release
### Description

Report on forums of inability to invade for no obvious reason
[FreeOrion • View topic - troops](http://www.freeorion.org/forum/viewtopic.php?f=28&t=10278&view=unread#unread)
### Expected Result

All planets in linked picture should be invadeable.
### Steps to reproduce

Am asking for savegame to be uploaded here

**Comment by yorev** [comment]
that the turn before, just run the new turn (i have tryed several times) and you will have the same result

for info i use 7-zip  i have rename it to .zip, if not i will not be able to upload

[chato382.zip](https://github.com/freeorion/freeorion/files/515566/chato382.zip)

**Comment by MatGB** [comment]
Ah, I don't have a 7-zip app on my system and installing it on Linux/Kubuntu isn't an easy hoop to jump through, hopefully someone that can unzip that can have a look, or if you could zip it into an actual zip or a rar file?

**Comment by yorev** [comment]
i have installed winzip and created this new file, i hope it will work for you

[chato382.zip](https://github.com/freeorion/freeorion/files/515651/chato382.zip)

**Comment by adrianbroher** [comment]
> Ah, I don't have a 7-zip app on my system and installing it on Linux/Kubuntu isn't an easy hoop to jump through

`$ sudo apt-get install p7zip`

`$ 7za x [the file.7z]`

**Comment by geoffthemedio** [comment]
7-zip can save as standard .zip files...

**Comment by MatGB** [comment]
Someday, I will get used to the difference between Discover and apt-get and remember the latter gets me more stuff. Thx. Got it all unzipped, will check it out in a bit.

**Comment by Vezzra** [comment]
Ooookay, that's weird... @yorev, some questions:
1. When you manually select some of your troop ships in the fleet window, do the "Invade" buttons appear? Or does manually selecting troop ships have no effect at all?
2. In the forum thread you mentioned: "i have the same issu on all systems attacked" - so you can't invade _any_ populated enemy planets anymore, correct? As this game is in a _very_ late state, this issue must have turned up at some point, when exactly? After you loaded the game?
3. This save game you continued here, did you start that with 0.4.6, or is this a save game of a previous version of FO?

**Comment by yorev** [comment]
1)-i have not tryed to select manually one by one each troop, just saw i could only invade the gas giant and run the invade button
i had selected the 10 troops fleet as you can see in orion forum, the picture
will try and tell you

2) in this turn i attack 5 systems and any had the invade button nor the one with the outpost on a gas giant and this happen on the 0.4.6 version

3) no i started the game with the test 23-08 version but i had a trouble, it was not possible after the turn 382 to save game (manually or auto sav) 
i run the turn to 383 to see if i could save and it was not possible but there were no problem to invade planets
that had happened only with the 0.4.6 
in 0.4.6 i was not able (manually or auto) to save file as well
i checked the forum i see i could in option select to save in binary and that had worked so i run to the turn 383 and find this bug about troops

my aplogize if i'm not very clear english is not my native language

**Comment by Vezzra** [comment]
> 1)-i have not tryed to select manually one by one each troop, just saw i could only invade the gas giant and run the invade button
> i had selected the 10 troops fleet as you can see in orion forum, the picture
> will try and tell you

Selecting the fleets does not help, you need to manually select some of the actual troop _ships_ in the lower half of the fleet window. Try doing that and report back if that makes the "Invade" buttons appear.

Savegames of older versions are not guaranteed to work when loaded with a newer version, we currently don't try to maintain savegame compatibility. So when you try to do that, you can get all kind of unpredictable results - from working perfectly fine to weird bugs popping up when playing to crashes.

One thing you can try is to load the 382 turn save with the old 23-08 version, turn binary saves on there and see if you can continue (and save) your game with that version. If you can and the bug does not turn up with the 23-08 version, it's definitely a savegame incompatibility that can't be fixed.

**Comment by yorev** [comment]
"Selecting the fleets does not help, you need to manually select some of the actual troop ships in the lower half of the fleet window. Try doing that and report back if that makes the "Invade" buttons appear."

no the button doesn't appear

tommorrow i will uninstall 0.4.6 and reinstall the 23-08

**Comment by yorev** [comment]
i have reinstalled 23-08 version
i can invade
i can save in binary(auto and manually)

**Comment by MatGB** [comment]
OK, so it's a savegame compatibility issue between versions, that's fine.  As Vezzra says, we don't ensure compatibility between versions, we essentially can't while developing at this stage (maybe later in the process but not yet).

What I do is always complete a game before recompiling, any from previous versions are done for, but you can always go back to that version if you want to load up.

So closing this, thanks for highlighting it, it may have been an actual bug, as it is it's something to be aware of when we do want to try to keep compatabilty.
