### ISSUE TITLE
Better Next / Previous System Ordering

### ISSUE THREAD

**Issue by geoffthemedio** [freeorion/freeorion#1028]
Currently when cycling through systems using the left and right arrows at the top of the system sidepanel, the ordering of systems is essentially random, jumping around the galaxy. It would be easier to use if the systems were ordered spatially, perhaps using something like a space-filling curve eg:

https://en.wikipedia.org/wiki/Peano_curve

**Comment by Vezzra** [comment]
A slightly different approach has been suggested on the forum, posting a link to that here in case we want to consider that once someone gets around to addressing this issue:

http://www.freeorion.org/forum/viewtopic.php?f=6&t=10279

**Comment by TheSilentOne1** [comment]
I'll have a go at this if noone else volunteers.

**Comment by geoffthemedio** [comment]
I alreadly did it...

**Comment by geoffthemedio** [comment]
https://github.com/freeorion/freeorion/commit/a9cabda49354260aa7cca434862e7364bde4e610
