### ISSUE TITLE
Ancient Guardians need gating to not take over a native homeworld

### ISSUE THREAD

**Issue by MatGB** [freeorion/freeorion#1057]
### Description

Playing a new game and noticed an italicised world populated by Guardians, this isn't good, natives shouldn't be displaced by them so there should always be a sentry or maintenance ship placed instead on a world with natives and a special.

**Comment by Vezzra** [comment]
Either that, or create a new special which greatly enhances the native planets defences (something like "Native supporting Ancient Guardians"), and add that special instead of the Ancient Guardians if a planet has a native pop. The idea being that the Ancient Guardians of this planet exist in harmony with the native population, granting them protection.

**Comment by Vezzra** [comment]
BTW, I'd consider that a bug rather than a tweak?

**Comment by MatGB** [comment]
Possibly, it's not the first time we've had specials overriding a native population and this is one of those that you only notice if you're paying attention to map indicators. 

And yeah, I like the special idea, what say you @Deepsloth , your idea originally.

**Comment by Deepsloth** [comment]
That's a good idea.
We could use Moderate Tech Natives, which only boosts defense, but doesn't have any upsides (in contrast to High Tech Natives).
I would also be ok with something new.

**Comment by Vezzra** [comment]
If the Moderate Tech Natives special grants defence boni roughly comparable to the defence stats of the Ancient Guardians, that's an option. On the other hand, a new special could add more flavor....

**Comment by MatGB** [comment]
Moderate Tech gives a fairly strong Defence bonus not just a shield bonus and thus would be an actual threat to very early game ships whereas the current guardians are cool because you can park your starting frigate on one safely to start the process of grabbing something.

I'd rather have something new that enhances shields and troops but not defences (because if the shield bonus is very high as it is then the defence bonus is lethal over time even if it's very low)

**Comment by Vezzra** [comment]
But can't that issue easily be circumvented by just setting the agression to "Hide" for all fleets you want to park at/pass through such a system? I never experienced Moderate or High Tech Natives as a roadblock like the guardian monsters...

(That said, I too prefer a new special, but more for flavor reasons.)

**Comment by MatGB** [comment]
In theory, yes if you a) notice, b) remember (my memory is incredibly flaky) and c) don't have something else to deal with there, if there's another monster on aggressive (eg a wandering Kraken or a Maintenance Ship you can get engaged even if you weren't planning to and were on hide.

Plus, the Guardians are/were tested/balanced to allow for low spec early ships to simply sit there and slowly wear them down, having a ship/small fleet randomly die because you didn't remember/notice the natives when you were moving to intercept a Kraken with your very early fleet is, for me, time to reload an autosave generally. It's not a fun way of losing stuff.

So yeah, I'd rather a new special for balance reasons **and** flavour reasons ;-)

**Comment by Deepsloth** [comment]
I tried to think up a fitting flavor, but have a question first:

Should the new special be persistent (i.e. stick around and give boni when conquered)?

It's eays to come up with a special that gives a troop bonus (like Native Domesticated Warbeasts), but something that increases shields is not so easy...

**Comment by Vezzra** [comment]
IMO it should behave exactly as the Ancient Guardians - once conquered, the special should be removed.

**Comment by Deepsloth** [comment]
Suggestion:

Precursor Protection

Increases Shields by + 500 and Troops by + 50. This special will be destroyed when conquered.

This planet is protected by an ancient defense system, constructed by the Curators to preserve the native life forms. The species on the planet was able to develop freely without the dangers of meteorites, space monsters or alien invaders.

**Comment by Vezzra** [comment]
Sounds good. 👍

**Comment by MatGB** [comment]
@Deepsloth do you fancy scripting that up? Discovering #1146 puts this up the priorities for me but it's still distinctly non-urgent, I'd rather get it done by next release though.

**Comment by l29ah** [comment]
dumb fix like
```
--- a/default/scripting/specials/specials.macros
+++ b/default/scripting/specials/specials.macros
@@ -21,6 +21,7 @@ CHANCE_OF_GUARD_1
                     Building name = "BLD_EXPERIMENTOR_OUTPOST"
                     And [ Planet HasSpecial name = "HIGH_TECH_NATIVES_SPECIAL" ]
                 ]
+                Population high = 0.0001
             ]
             effects = [
                 If condition = Random probability = 0.6
```
doesn't work for some reason :/

**Comment by dbenage-cx** [comment]
Try:

```
--- a/default/scripting/specials/specials.macros
+++ b/default/scripting/specials/specials.macros
@@ -26,8 +26,12 @@ CHANCE_OF_GUARD_1
                 If condition = Random probability = 0.6
                     effects = CreateShip designname = OneOf("SM_GUARD_0", "SM_GUARD_1")
                 else = [
-                    SetSpecies name = "SP_ANCIENT_GUARDIANS"
-                    SetPopulation value = Target.TargetPopulation
+                    If condition = (Target.TargetPopulation < 0.001)
+                        effects = [
+                            SetSpecies name = "SP_ANCIENT_GUARDIANS"
+                            SetPopulation value = Target.TargetPopulation
+                        ]
+                    else = CreateShip designname = OneOf("SM_GUARD_0", "SM_GUARD_1")
                 ]
             ]
 '''

**Comment by l29ah** [comment]
Doesn't seem to work. I see an italicized system with the guardians.

**Comment by geoffthemedio** [comment]
Other suggestion was a bit overcomplicated. Hopefully resolved now, though.

**Comment by l29ah** [comment]
Nope, this way they don't get spawned at all.

**Comment by geoffthemedio** [comment]
How did you test that? It doesn't make sense with the scripted condition, and is not consistent with my tests, in which they still spawned.

**Comment by l29ah** [comment]
git pull, make, ./freeorion, single player game, super testers.

**Comment by l29ah** [comment]
Okay, at the second generated world i see one guardian-occupied planet in 150 systems.

**Comment by geoffthemedio** [comment]
Works for me. There are going to be fewer of them now, especially if there are natives around taking away otherwise allowed locations with specials.
![guardians](https://cloud.githubusercontent.com/assets/11386908/21754938/7b0e662e-d60a-11e6-9b4e-69df907368af.png)
