### ISSUE TITLE
Crash on opening combat log

### ISSUE THREAD

**Issue by MatGB** [freeorion/freeorion#1073]
### Environment
- **FreeOrion Version**: Fighters branch rebased with master
- **Operating System**: Kubuntu
- **Graphic card used**: AMD A78
- **Fetched as** 
  - Compiled from source
### Description

Reading turn sitrep, clicked combat report, game crashed.
### Steps to reproduce

Unsure as yet, not replicated on reload, didn't happen earlier in game. Logs attached.
[freeorion.zip](https://github.com/freeorion/freeorion/files/552073/freeorion.zip)

**Comment by MatGB** [comment]
OK, this might be a Fighters branch specific, while the game didn't crash this time it did get horrendously laggy while I tried to read the report, and the report itself is messed up in really bad ways (large number of fighters launched by both sides).

Savegame attached, for compatibility, Fighters branch rebased to
[FreeOrion_Mat_Gotham_0179_20161026_030211.sav.zip](https://github.com/freeorion/freeorion/files/552205/FreeOrion_Mat_Gotham_0179_20161026_030211.sav.zip)
 Master as at 4f3619b

**Comment by MatGB** [comment]
@LGM-Doyle , you're the most recent person to have done major work on the combat log, can you give this a look, think it's a Fighter compatibility issue with your stuff.

**Comment by LGM-Doyle** [comment]
Yes I will look at this.

Could you provide a more detailed list of the problems with the combat report?  An itemized list will mean that I have at least looked at every item on the list, even if I am unable to improve the situation.

**Comment by MatGB** [comment]
OK, screenshot attached, I expanded a set of results, as you can see the fighters are listed twice, independently of the collapsing per ship results and within it, plus there's a lot of "unknown" in there.

Loading the report at all takes significant time, even on relatively small fights, if either/both sides is using fighters (and as I'm deliberately testing fighters I am).

The scrolling down to read further results is very laggy, it's not all pregenerated, and if you get to the bottom you sometimes need to resize the report window to get the scrollbar to let you go down further.

For **really** large fights, the end of it either doesn't generate properly or sometimes at all, and you get some weird artifacts displaying instead of actually rendered font: loading such a fight has now caused at least three identical-in-style crashes for me.

The inability to get to the bottom is a real problem with Fighters, the only way the UI tells you what a ship currently has on board is to look at the combat report to see what it recovered, and you need to withdraw to replenish in longer fights, as a short term fix having recovered fighters display at the top might be an idea, but ideally we need a UI element in the fleetwnd (not related to this but, well, it just occured.

I'm still testing/playing, if I come up with any problems I've forgotten I'll update.

**Comment by MatGB** [comment]
New crash, logs and savefile attached
[FreeOrion_Mat_Battlestar_0132_20161027_023307.sav.zip](https://github.com/freeorion/freeorion/files/554794/FreeOrion_Mat_Battlestar_0132_20161027_023307.sav.zip)
[combat-report-crash-2.zip](https://github.com/freeorion/freeorion/files/554796/combat-report-crash-2.zip)
On reload, crash doesn't occur, appears to be a problem on ongoing games when memory leak has built up

**Comment by geoffthemedio** [comment]
To see what fighters a ship has, can you do a debug data dump on the ship from the objects list? Results should appear in the chat, and the various part meters should be shown.

**Comment by MatGB** [comment]
OK, rebased and recompiled with #1076 , substantial improvements in rendering time but glitches in display as attached
![combat-log-fighters-2](https://cloud.githubusercontent.com/assets/11533206/19791388/5fe4bf46-9cb8-11e6-9b90-254c9711a089.png)
![combat-log-fighters-3](https://cloud.githubusercontent.com/assets/11533206/19791389/62d24db8-9cb8-11e6-9d3b-8a20b7be8150.png)

Large side margin, plus boxes giving space for the drop down before the dropdown is called, these shrink to a sensible size when you click.

**Comment by MatGB** [comment]
@geoffthemedio , yes, this can be done and appears to give correct results but will need to wait until a big fight to confirm. It's not an ideal workaround and we need a better way to display it or discover it.

**Comment by LGM-Doyle** [comment]
@MatGB thanks for the quick feedback.  

I only tested this quickly (and obviously incompletely).  I had hoped the speed improvement would make things more testable for you.

I have seen all of the problems that you describe except for the crashing.  I'm hoping that the crashing will stop happening if we can get the layout to be shorter than a refresh interval.

**Comment by MatGB** [comment]
Oh, the speed improvement and distinct lack of crashing has helped significantly, and the rendering issue is merely placement instead of illegibility, so it's a substantial improvement—of course, not having crashed yet isn't the same as stopping it but it's looking better.

**Comment by Vezzra** [comment]
#1076 has been merged, which should take care of the actual intent of this issue. So I suggest to close it as "resolved" and open separate issues for the other, remaining glitches - @MatGB, @LGM-Doyle?

**Comment by LGM-Doyle** [comment]
I am happy either way, one PR, one PR with a list of items to be ticked off, or multiple PRs.

I was unable to duplicate the crashes.  It was not clear to me, from @MatGB's log files what caused the crash. I do not know what caused the crashes.

However, since the `DeferredLayout` approach is much faster, 10 times for my test case, the crash might be fixed in passing, or much less likely.

**Comment by Vezzra** [comment]
Hm, in that case I'd like to get a confirmation from @MatGB that the crash has been fixed...

**Comment by MatGB** [comment]
As far as I can tell, crash fixed, but of course can't prove a negative, all I can say is that testing a few turns through on the old savegame and loading multiple large combat reports hasn't either caused crashes or weird lag problems.

There are a few rendering/display errors and the Fighters are listed as 'unknown' in a few places, but it's better, it definitely isn't a merge blocking problem that the crashing/unreadable reports was.
