### ISSUE TITLE
Fighters: carrier fleets need a "split empty carriers" option

### ISSUE THREAD

**Issue by MatGB** [freeorion/freeorion#1077]
### Environment

Fighters Branch
### Description

Fighters as a mechanic increases combat length and reduces the likelihood combat will be over in a single turn. During an ongoing combat individual ships in a fleet may run out of fighters and need to withdraw for resupply. Having an easy method of splitting those ships from a fleet and withdrawing them would be very useful.
### Expected Result

When right clicking a fleet, alongside 'split damaged ships' and 'split unfuelled ships' an option for 'split empty carriers' should exist, this should split off all ships with a max fighter capacity above zero but a current capacity at zero from the fleet.

**Comment by geoffthemedio** [comment]
https://github.com/freeorion/freeorion/commit/eac69acfe6f7df1f67ccebd6671b40e11cef3ffe may resolve this.

**Comment by Vezzra** [comment]
Hm, @MatGB requested an option to split *empty* carriers from the fleet, so this isn't exactly what he asked for... @MatGB, is the right-click option @geoffthemedio implemented in eac69acfe6f7df1f67ccebd6671b40e11cef3ffe good enough for you, so that we can close this, or do you think the "split empty carriers" as you requested it is needed?

I have only one test game with fighters so far, so I can't tell myself...

**Comment by MatGB** [comment]
I don't know yet, my current game is on compile 81e02f5 (ie, the commit just before), and from experience of broken saves I don't recompile during games unless I'm testing a bugfix for that game, I'm still testing fighters &c for balance while attempting the update of the premades and don't want to lose a big game nor a forced reset (compiling takes me ~30 minutes normally, which is time I'd rather not waste).

I suspect it'll do the job and is at least consistent with damage, going through a separated fleet of "not full" to put selected partially full back into the line fleet will be a similar routine to the current pick only slightly damaged setup. Will test when this game is finished (likely today).

**Comment by geoffthemedio** [comment]
Do you really care more about 1 vs 0 than full vs full - 1 for fighters? Implemented command seems more useful ti me...

**Comment by MatGB** [comment]
I don't know, and it would be circumstantial, but frequently, especially in the early game, total capacity of a carrier is 2, 1 remaining means can fight, 0 remaining means can't. Even in late game a stealthed carrier with one fighter can stay in place and cause disruption whereas we'll need to fix it so a stealthed carrier with no fighters or guns doesn't/can't initiate combat (because that's abusive).

I suspect the fix you've put in is enough, but haven't tested yet, and having both empty and not full would probably add too much to an already cluttered menu (especially as I have an idea for *another* split ;-) )

**Comment by Vezzra** [comment]
Ok, @MatGB, can you give us a heads up/close the issue once you've tested this and are sufficiently satisfied (or not)? Just so this issue isn't left hanging...

**Comment by MatGB** [comment]
No problem: I got a game started yesterday using this, Dilvish's AI tweaks and the fractional production but I only got about 50 turns in, not enough to judge yet.

**Comment by MatGB** [comment]
OK, have played enough, I think it's enough as is, splitting off the partially empty allows you to choose which if any to then rejoin the original fleet.

**Comment by Vezzra** [comment]
Resolved by eac69acfe6f7df1f67ccebd6671b40e11cef3ffe
