### ISSUE TITLE
Scripting Bug - Auto history analyser should research iff culture library exists

### ISSUE THREAD

**Issue by agrrr3** [freeorion/freeorion#1081]
### Environment
- **FreeOrion Version**: master head from this morning
### Description

Building BLD_AUTO_HISTORY_ANALYSER can only be built if BLD_CULTURE_ARCHIVES is there, but for producing research output it is not necessary. Probably one can build the analyser, then kill the population of and still get the benefit.
### Expected Result

Same as for the BLD_CULTURE_ARCHIVES, the BLD_AUTO_HISTORY_ANALYSER should not help researdch if the original species gets wiped out. 
### Implementation idea

Either auto-destroy history analyser or reduce research output to zero if BLD_CULTURE_ARCHIVES is not there.
Probably a sitrep message should be given to the user, so one knows why the building is not there anymore/does not produce research output.

**Comment by Vezzra** [comment]
Sounds reasonable. The fluff explanation specifically states that the History Analyzer works with the data provided by the Cultural Archives, so it makes absolutely no sense if the HA provides its bonus once the CA is destroyed.

Personally I'd prefer to destroy the HA together with the CA, less confusing for the player IMO.

**Comment by Vezzra** [comment]
I thought this one has been addressed, but can't really remember anymore... anyone? @MatGB? @agrrr3?

**Comment by MatGB** [comment]
I don't recall seeing anyone do any work on it: on the other hand an automated computer analysis doesn't need population?

Ensuring the prereq building is there to work should go in, not sure I care about depopulation but consistency probably says it ought to stop working. I don't think either destruction or sitrep is necessary, if the population is gone you get a sitrep for that and meters go to zero anyway.

**Comment by Vezzra** [comment]
> I don't recall seeing anyone do any work on it: on the other hand an automated computer analysis doesn't need population?

That isn't really the point, if the Cultural Archives building is a prereq for the History Analyzer, and the CA only works with the original pop, then the HA also only should work with the original pop. That's a matter of consistency IMO.

If I understand correctly, if you recolonize with a different species, the HA currently would work again, won't it?

So the HA should get destroyed together with the CA. Or we need to decouple these buildings and come up with other fluff explanations. But whatever approach gets chosen, it needs to be a consistent one.

Once that's assured, we can close this as resolved.

**Comment by MatGB** [comment]
Fairly sure archives work if you repopulate, I've done it enough with Trith recently.

**Comment by Vezzra** [comment]
Well, as long as the History Analyzer works the same way as the Cultural Archives in that regard, I guess we're good.

The only thing that actually needs fixing then is that the HA only works if the CA is present and pop>0, right?

**Comment by dbenage-cx** [comment]
Some confusion here between Cultural Archives and Cultural Library, only the later has a `Destroy` effect.

Minimum population was covered with commit 3ff6566
