### ISSUE TITLE
cannot save game in multiplayer: Invalid UTF-8

### ISSUE THREAD

**Issue by Voker57** [freeorion/freeorion#1089]
Message saying "Invalid UTF-8" pops up when I try to save multiplayer game.

**Comment by geoffthemedio** [comment]
What version? What OS? What is your username in that OS?

**Comment by Voker57** [comment]
Version: 54f121a8ef171f0c3d3
OS: linux debian unstable
Username: Voker57

bug does not always reproduce, not sure what triggered it

**Comment by adrianbroher** [comment]
What save file name did you use?  What is the locale does your system use?

**Comment by Voker57** [comment]
I didn't even get the option to choose save file name, message pops up immediately on pressing save game button. Locale is en_US.UTF-8

**Comment by geoffthemedio** [comment]
Can you post freeorion.log and freeoriond.log from immediately after this occurs?

**Comment by geoffthemedio** [comment]
Note @LGM-Doyle I'm getting similar-looking errors in freeorion.log when clicking the load game button in the multiplayer lobby, which often doesn't appear to work (although sometimes does...)

Relevant bit of the stack from when an invalid_utf8 exception gets thrown:

```
    utf8::next<std::_String_const_iterator<std::_String_val<std::_Simple_types<char> > > >(std::_String_const_iterator<std::_String_val<std::_Simple_types<char> > > & it={...}, std::_String_const_iterator<std::_String_val<std::_Simple_types<char> > > end={...}) Line 153  C++
    GG::Font::DetermineLines(const std::basic_string<char,std::char_traits<char>,std::allocator<char> > & text={...}, GG::Flags<GG::TextFormat> & format={...}, GG::X box_width={...}, const std::vector<boost::shared_ptr<GG::Font::TextElement>,std::allocator<boost::shared_ptr<GG::Font::TextElement> > > & text_elements={...}) Line 1796  C++
>   SaveFileDialog::Init() Line 659 C++
    SaveFileDialog::SaveFileDialog(bool load=true) Line 606 C++
    HumanClientApp::SelectLoadFile() Line 1113  C++
```

And some reported local variables in Font::DetermineLines:

```
+       text    "SERVERSERVERSERVER"    const std::basic_string<char,std::char_traits<char>,std::allocator<char> > &
+       format  {m_flags=18 }   GG::Flags<GG::TextFormat> &
+       box_width   {m_value=590 }  GG::X
+       text_elements   { size=1 }  const std::vector<boost::shared_ptr<GG::Font::TextElement>,std::allocator<boost::shared_ptr<GG::Font::TextElement> > > &
+       pending_formatting_tags { size=0 }  std::vector<boost::shared_ptr<GG::Font::TextElement>,std::allocator<boost::shared_ptr<GG::Font::TextElement> > >
+       render_state    {use_italics=0 use_shadow=0 draw_underline=0 ...}   GG::Font::RenderState
+       it  "¸`\fsers\\Geoff\\"    std::_String_const_iterator<std::_String_val<std::_Simple_types<char> > >
```

**Comment by Voker57** [comment]
I'll try to do it next time i catch this bug.

**Comment by LGM-Doyle** [comment]
@geoffthemedio, thanks for the stack trace.  I was unable to duplicate the bug, but it was obvious when I followed the stack to the relevant location.
