### ISSUE TITLE
Can't build/compile

### ISSUE THREAD

**Issue by MatGB** [freeorion/freeorion#1106]
### Environment

* **FreeOrion Version**: 7f979fb
* **Operating System**: Kubunto 16.04
* **Fetched as**
  * Compiled from source

### Description
Have done a hard reset to remote HEAD to ensure it's not a problem with my Git repo, get following message:
`
CMakeFiles/freeorioncommon.dir/build.make:86: recipe for target 'CMakeFiles/freeorioncommon.dir/combat/CombatEvents.cpp.o' failed
make[2]: *** [CMakeFiles/freeorioncommon.dir/combat/CombatEvents.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:99: recipe for target 'CMakeFiles/freeorioncommon.dir/all' failed
make[1]: *** [CMakeFiles/freeorioncommon.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
`
Full build log attached
### Expected Result
Game should compile

[make-log.txt](https://github.com/freeorion/freeorion/files/589555/make-log.txt)

**Comment by LGM-Doyle** [comment]
Please try PR #1108 to see if it fixes the problem.
