### ISSUE TITLE
AI errors when no planets left

### ISSUE THREAD

**Issue by MatGB** [freeorion/freeorion#1116]
### Environment

* **FreeOrion Version**: 93847d8 (plus rebased Fighters branch)
* **Operating System**: Linux
  * Compiled from source

### Description
Yellow has lost all its planets and has three warships left, every turn I get this error:
'AI_4: AI_Error: AI script error in "calculate_priorities": "'float' object has no attribute 'get'"
AI_4: AI_Error: AI script error in "assign_military_fleets_to_systems": "'float' object has no attribute 'get'"'

I am playing with compiled-from-master binaries and a rebased Fighters branch but that shouldn't make a difference, the AI was effectively defeated by a different AI and the remaining ships are outside my zone of influence.
[AI_4-no-planet-error.log.zip](https://github.com/freeorion/freeorion/files/600622/AI_4-no-planet-error.log.zip)
[FreeOrion_Mat_AI-4-no-planets.sav.zip](https://github.com/freeorion/freeorion/files/600623/FreeOrion_Mat_AI-4-no-planets.sav.zip)

**Comment by Morlic-fo** [comment]
Fix pushed to Fighters branch.
