### ISSUE TITLE
Adaptive Automation sets Industry to 5, vs increases by 5

### ISSUE THREAD

**Issue by jasonosgood** [freeorion/freeorion#1120]
From what I can tell so far, researching Adaptive Automation sets the Industry on all owned planets/colonies to just 5. Versus increasing Industry by 5, as stated in the Pedia.

Running Version 0.4.6 (build 2016-09-16.49f9123) on a late 2013 Retina MacBook Pro running macOS 10.11.2. Fetched as binaries.

I'll update ticket with screenshots, logs, etc as able.

**Comment by MatGB** [comment]
> I'll update ticket with screenshots, logs, etc as able.

Please do, because that's a very weird edge case bug that I've never seen: are you sure it's affecting worlds set to Industry focus? It's virtually always the only industry output non Industry set worlds get unless they're a homeworld.

**Comment by dbenage-cx** [comment]
Planets might possibly have a negative TargetPopulation.  One such case is an outpost with the tidal lock special:

![adaptive_automation_tidal_lock](https://cloud.githubusercontent.com/assets/17205519/20635534/ddb65228-b323-11e6-90a2-3b0b7aea9019.png)

@jasonosgood Is this the same issue?  I do not notice any issue with other planets.

**Comment by Vezzra** [comment]
I think we should wait for a few more weeks, maybe until end of January. If @jasonosgood hasn't replied by then, I suggest to close this as invalid.

**Comment by jasonosgood** [comment]
Thank you for followup, patience. User error. Please close.
