### ISSUE TITLE
map doesn't update fleets after turn until zoom level is changed

### ISSUE THREAD

**Issue by krator44** [freeorion/freeorion#1131]
### Environment

* **FreeOrion Version**: 0.4.6+ HEAD [build 2016-11-23.b56dfe7c0]
* **Operating System**: gentoo linux
* **Graphic card used**: intel HD graphics 520 (rev 07)
* **Fetched as** 
  * Compiled from source 

### Description

the main view keeps old fleet positions after a new turn. the fleet description (if you click on the fleet) is updated but the fleet UI element on the main view is still at its old coordinates. this goes away once the map is zoomed in or out one level and is updated to the new coordinates. workaround: zoom map after new turn to get the ships updated. this never happened in 0.4.5.

### Expected Result

fleet coordinates on the main map are updated after new turn (without having to zoom in or out).

### Steps to reproduce

construct some fleets. order them to move to a different star. click "next turn". check to see that the fleets have moved. do it again. this happens at a minimum once every 20 turns (that is not always but rather frequently).

if the fleets that were supposed to move stayed stationary click the mouse wheel once while looking at the fleets. note that the fleet coordinates have now been updated.

**Comment by krator44** [comment]
some additional info
this bug happens when you click next turn while looking at the research screen.
construct a fleet. order the fleet to move. open research screen. hit next turn. close research screen. the fleet is still at its previous coordinates. click mousewheel once to zoom the map. the fleet is now at the new coordinates.

**Comment by Vezzra** [comment]
Can confirm the issue on OSX when following the steps with the research screen. Haven't been able to reproduce it any other way though.

**Comment by Vezzra** [comment]
Same on Windows: can reproduce following the steps with the research screen, but not any other way.

**Comment by geoffthemedio** [comment]
MapWnd::RefreshFleetButtons calls RequirePreRender which sets the flag to prerender, rather than actually refreshing the fleet buttons. Then in MapWnd::PreRender, GG::Wnd::PreRender is called, which de-sets the flag to prerender, but then immediately after if the research or design Wnds are open, it early aborts. This means the following call to DeferredRefreshFleetButtons never happens until a subsequent RequirePreRender call, presumably after zooming.

**Comment by LGM-Doyle** [comment]
This is fixed in master by https://github.com/freeorion/freeorion/commit/771d3308b7b806de149c87a55292dc53213e5a9c
