### ISSUE TITLE
Sidepanel Won't Drag to Left Side of Screen

### ISSUE THREAD

**Issue by geoffthemedio** [freeorion/freeorion#1135]
Open the sidepanel, drag it (not on the system name, which doesn't respond to drags, but on the star picture space below) left. It won't go all the way to the left edge of the map screen.
![sidepanel drag left](https://cloud.githubusercontent.com/assets/11386908/20646711/0e2fe514-b481-11e6-86ea-f9f2fabf556d.png)

**Comment by MatGB** [comment]
Huh, never even tried to do that.

Just tested: for me, it leaves just enough of a space for the planets to display if there are any, which is probably how we'd normally want it?

**Comment by geoffthemedio** [comment]
Hmm... could be the intention / reason. I recall the actual and apparent sizes of that window weren't as expected.

**Comment by Vezzra** [comment]
Can confirm Mats observations. If you select a Deep Space system, drag the side panel as far left as possible, then select a system which contains planets, the planet panels use up the extra space to the left.

So, I'd say works as intended. Suggest to close as invalid (unless you want the current behaviour to be changed).

**Comment by LGM-Doyle** [comment]
The `PlanetPanel` inside the `SidePanel` reserves the space for the planet graphic even if it is not visible.  That behavior is not due to recent changes.
