### ISSUE TITLE
Sidepanel System Droplist Should Show Selected System In Dropped List When Opened

### ISSUE THREAD

**Issue by geoffthemedio** [freeorion/freeorion#1136]
When opening the system droplist, it defaults to the top of the list. It should instead show the selected system in the centre of the displayed range of system names.
![sidepanel system drop](https://cloud.githubusercontent.com/assets/11386908/20646750/f6ea9b46-b481-11e6-891b-9832c6f5f1b1.png)

**Comment by LGM-Doyle** [comment]
This is already fixed in PR #1133.

**Comment by LGM-Doyle** [comment]
Correction.  This is now fixed in PR #1133.  I had fixed it in a previous version, but didn't double check.

**Comment by geoffthemedio** [comment]
Can it show the selected item in the middle instead of the bottom?

**Comment by Vezzra** [comment]
Has everything (including @geoffthemedio's last request directly above) been addressed? Can we close this?

**Comment by LGM-Doyle** [comment]
This is fixed including @geoffthemedio request to show the selected system in the center of the list.

**Comment by Vezzra** [comment]
Perfect, thanks 😃
