### ISSUE TITLE
Mousewheel On System List Should Loop Around To End of List and Go in Other Direction

### ISSUE THREAD

**Issue by geoffthemedio** [freeorion/freeorion#1137]
When the mouse pointer is over the system name on the system sidepanel, one can scroll the mousewheel to change the selected system. However:

-Mousewheel down moves up the list, ie. to names earlier in the list instead of later. This is particularly odd when mousewheeling while the list is open, as moving the cursor to the top (selected) item or down onto the list itself will cause the mousewheel to switch directions.

-If at the first system in the list, mousewheel down does nothing. It should loop around to the end of the list.

**Comment by Vezzra** [comment]
Confirmed on OSX.

**Comment by LGM-Doyle** [comment]
I fixed the agreement between the mousewheel scroll direction in the anchor and when the list is open, in PR #XX

I did not make the mousewheel scrolling wrap around.
* that is how I prefer it
* this particular list is an alphabetically sorted list.  It has a beginning and an end, so wrapping seems odd.
* stopping at the beginning and end of the list agrees with the keyboard behavior of HOME and END.

I could, of course, change it to wrap, or add an option and wrap things like the focus drop downs, but not ordered lists.

**Comment by Vezzra** [comment]
@geoffthemedio, do you still want mousewheeling to loop around, and keep that issue open, or can you agree with @LGM-Doyle's assessment, and are ok with how things are now? In which case we can close this...?

**Comment by geoffthemedio** [comment]
It feels to me like it should loop around for systems, but probably it shouldn't for many other cases of similar / derived controls, and I can accept that it doesn't / others think it shouldn't. Not a major issue in any case.

**Comment by Vezzra** [comment]
Ok then, fixed by #1142.
