### ISSUE TITLE
Multiedit Coloured Text Glitches

### ISSUE THREAD

**Issue by geoffthemedio** [freeorion/freeorion#114]
In MultiEdit windows where text can be selected, including the Pedia and Messages windows, when click-dragging to select text, occasionally colour tags aren't closed properly, leading to glitchy colouring of text that should not be specially coloured.

![multiedit_text_select_colours](https://cloud.githubusercontent.com/assets/11386908/8024571/04317b82-0d06-11e5-8010-a627be5af21c.png)

**Comment by Vezzra** [comment]
That not only happens when you click-drag to select text, you just need to scroll through the text. Apparently, sometimes when lines are auto-wrapped the glitch with the color tags happens too.

**Comment by Dilvish-fo** [comment]
Bah, I just double checked Vezzra's extra circumstances above and discovered the fix for the first problem did not fix it for the second.  It's probably a related problem, though, so I am hopeful finishing this off will be quick (fixing the first part took waaaay too many hours to figure out!)

**Comment by Dilvish-fo** [comment]
Ok, that does it, whew!
