### ISSUE TITLE
Allow editing and deletion of saved ship designs within app

### ISSUE THREAD

**Issue by MatGB** [freeorion/freeorion#1145]
### Description
The saved designs feature is a godsend that is very useful, when I switch to a new machine or do an OS reinstall it always throws me when they're not there.

However, sometimes I mess a design up, and sometimes we introduce new features (eg: Fighters) or parts (eg: Flak Cannon) that require a rethink of designs. And then there are the inevitable typos.

It would be *really* helpful if the client allowed for editing of saved designs directly within it in a user friendly way.

**Comment by LGM-Doyle** [comment]
I added this comment to #884, when I meant to comment here.

@MatGB do the newly merged `DesignWnd`changes to saved ship designs satisfy this feature request enough to close it and start opening bug issues and/or new feature requests based on the current state of the game?

**Comment by MatGB** [comment]
Yup, this one is now resolved to my satisfaction, many thanks: it's been a particular godsend given I'm working on the engine parts fix at the moment and that means switching between radically different designs for testing, etc.
