### ISSUE TITLE
Homeworld Supply growth bonus can be granted by non original species

### ISSUE THREAD

**Issue by MatGB** [freeorion/freeorion#1146]
Related to, but separate from #1057 

### Description
If a depopulated homeworld is recolonised with a different species that species can be set to Growth focus and all non-homeworld planets in supply of the new species get the homeworld supply growth bonus.

This is more apparent now with the Ancient Guardians as they are likely to replace the population of a native world with a growth special, but would always have been the case and needs fixing independently (I discovered this in my current test game as I've captured a guardian world with Ki Spice and colonised it with Sslith, all my other Sslith worlds are getting both the Ki Spice and Homeworld bonus: this would also apply if you concentration camp or evacuate a planet.
```
HAS_GROWTH_FOCUS
'''        Focus
            name = "FOCUS_GROWTH"
            description = "FOCUS_GROWTH_DESC"
            location = Or [
                AND [
                    Homeworld
                    Not HasTag name = "SELF_SUSTAINING"
                ]
                HasSpecial name = "POSITRONIUM_SPECIAL"
                HasSpecial name = "SUPERCONDUCTOR_SPECIAL"
                HasSpecial name = "MONOPOLE_SPECIAL"
                HasSpecial name = "SPICE_SPECIAL"
                HasSpecial name = "FRUIT_SPECIAL"
                HasSpecial name = "PROBIOTIC_SPECIAL"
                HasSpecial name = "ELERIUM_SPECIAL"
                HasSpecial name = "CRYSTALS_SPECIAL"
                HasSpecial name = "MINERALS_SPECIAL"
            ]
            graphic = "icons/focus/growth.png"
'''
```

### Expected Result
Homeworld supply should only be granted for species of the original homeworld regardless of how depopulation occurs.

This could be achieved by rewriting the scripts or have the Homeworld tag removed if the population is destroyed, not sure if this is optimal as removal could be done by hostile action and repopulation with original species is then viable, but it's one way to do it.

**Comment by geoffthemedio** [comment]
The Homeworld condition takes a name = parameter to specify the species, which is used in the homeworld growth scope but not the activation... perhaps it should be used in both, to restrict which homeworlds can generate the effect to only homeworlds of the species on a planet?

https://github.com/freeorion/freeorion/blob/master/default/scripting/species/common/population.macros#L108
