### ISSUE TITLE
Regression: build candidates list rewinds after adding an item to the build queue

### ISSUE THREAD

**Issue by l29ah** [freeorion/freeorion#1147]
This makes it painful to add multiple tasks of one ship.

**Comment by MatGB** [comment]
Was going to start an issue on this having mentioned it as an aside elsewhere, but yes.

When you add something to the production queue and/or if you change the order size or repeat number, the producible items list jumps, so you can't always see the same thing, especially annoying if, for example, you want several different outpost ships to be given rally points to different places.

In addition, if deleting an item from a long production list, it now jumps to the middle of the list, which makes cleaning up after capturing AI worlds building unnecessary things (eg if they've already lost a capital and are rebuilding high priority buildings) even more frustrating.

**Comment by l29ah** [comment]
7ace2fe8b5362e698f84634eef9b235de6d00e11 is the first bad commit

**Comment by LGM-Doyle** [comment]
@l29ah thanks for the bug report.  

I think that #1150 addresses the issue.  Your comments are welcome.

**Comment by Vezzra** [comment]
Bump. @l29ah, @MatGB, has the issue been solved for you? Can we close this?

**Comment by l29ah** [comment]
Yes.
