### ISSUE TITLE
improve visibility of sensor ghosts

### ISSUE THREAD

**Issue by TheSilentOne1** [freeorion/freeorion#1148]
Bug reports like this one ( https://github.com/freeorion/freeorion/issues/1130 ) bring it to attention that it can sometimes be difficult to recognize the scanlines over a ghost fleet. An easy fix would be to change the scanline color. The following screenshot shows the change of a single line of scanlines.frag, adding some green:
const vec4      half_gray = vec4(0.0, 0.8, 0.0, 0.5);   // darkened pixels

![invisible_fleets](https://cloud.githubusercontent.com/assets/12985960/20671558/118d06c6-b57e-11e6-8db9-67cde4672e12.jpg)

It is obvious that the color of the scanlines over nebulae, systems etc. would better not be changed. So I'd propose to just change the color for ghost fleets, which would require a modification of the shader so it takes a color as an argument (replacing the half-gray variable).
Other ideas are certainly welcome!

**Comment by geoffthemedio** [comment]
How does that colour look interacting with the various other empire coloured detection range circles?

**Comment by LGM-Doyle** [comment]
How about de-saturating the ghost's color, so that they look white, pale and ghostly.  

It would conflict with the new `White Kraken`.

**Comment by TheSilentOne1** [comment]
I'm working some more on this, will report next week (probably).

**Comment by TheSilentOne1** [comment]
Adressed with #1155.
