### ISSUE TITLE
Packaging license question

### ISSUE THREAD

**Issue by subpop** [freeorion/freeorion#1157]
I'm packaging freeorion for Fedora, and I'm having some trouble getting the licenses squared away. As I understand the licensing structure is roughly:

* Game assets are licensed under `CC-BY-SA`
* Game code is licensed under `GPLv2`
* Bundled libgigi is licensed under `LGPLv2`

Fedora's packaging policies try to include the license files provided with the upstream source whenever possible. The COPYING files distributed in the 0.4.6 release tarball make this a challenge. `default/COPYING` includes the GPLv2 and the CC-BY-SA license contents. `GG/COPYING` includes just the LGPLv2 license. Would it be possible to separate them into individual files? Something like:

```
src-tarball/default/COPYING          // CC-BY-SA
src-tarball/COPYING                  // GPLv2
src-tarball/GG/COPYING               // LGPLv2
```

This would make distribution packaging easier to manage.

**Comment by geoffthemedio** [comment]
That is "roughly" accurate, but incomplete, as noted in the copying file,
````
Game content scripts are also licensed under the GNU General Public License, Version 2
````

**Comment by subpop** [comment]
Oh I see. Hence the dual licensing in default/COPYING. That's not a problem then. I'm able to handle that in the packaging steps.
