### ISSUE TITLE
Objects window loses column headers during game

### ISSUE THREAD

**Issue by MatGB** [freeorion/freeorion#1161]
### Environment
* **FreeOrion Version**: 1f1cddf
* **Operating System**: Linux/Kubuntu
  * Compiled from source

### Description
Thus far I've been unable to work out what is triggering this and have now recompiled a clean copy of master to find it's still happening.

On initial use in any game loaded, Objects works fine, and sometimes can be used several times without issue, but at some point, always after it has been used at least once since most recent load, the column heading line disappears (pictured), making refining a search and/or changing the sort order impossible.

### Expected Result
Column headings should display correctly, be clickable/changeable and allow for sorting, etc.

### Steps to reproduce
Uncertain as yet, this has happened in my three most recent games but this is the first game where I've run a clean recompile.

Saving, exiting and reloading brings the column headings back, but they go again next time I use the menu after I've cycled a turn.

I think: play a game through, use Objects for something, close Objects, cycle a turn then try to use Objects again, will try to confirm.
![screenshot_20161209_153933](https://cloud.githubusercontent.com/assets/11533206/21054469/cfe7bbde-be25-11e6-8853-385c862dcfb3.png)
[Objects-columns-missing.zip](https://github.com/freeorion/freeorion/files/642551/Objects-columns-missing.zip)

**Comment by LGM-Doyle** [comment]
@MatGB  thanks for reporting this bug.

When you have a reproducer could you try #1162, which I think fixes the problem.

**Comment by MatGB** [comment]
Geoff merged in before I could recompile having confirmed the problem, it was simply "have used Objects and then cycled a turn", it appears now fixed.
