### ISSUE TITLE
AI ShipDesign.py starting guess can cause divide by zero.

### ISSUE THREAD

**Issue by LGM-Doyle** [freeorion/freeorion#1170]
### Environment
* **FreeOrion Version**: master https://github.com/freeorion/freeorion/commit/284bbb1279a4ca0d3708788eb7b3909a2f424857
  * Compiled from source

### Description
In the creation of the starting guess for the AI ship design code the following lines causes a divide by zero error.
Line https://github.com/freeorion/freeorion/blob/master/default/python/AI/ShipDesignAI.py#L1695

````                
                p3 = a*(ca-cw)
                n = max((p1+p2)/p3, (p1-p2)/p3)
````
where `ca` and `cw` are cost of armor and weapons respectively, can result in divide by zero in the python code.

I'd don't have a log, but it generates the expected python divide by zero error, that I noticed while debugging something else.

I'm not familiar with this code, so I'll simply report it with no fix.

### Expected Result
`_starting_guess` should deal with the local min/max without a divide by zero.

**Comment by Morlic-fo** [comment]
Should be fixed. Thanks for the report.
