### ISSUE TITLE
Colony detection range should change (downgrade) immediately on conquest.

### ISSUE THREAD

**Issue by LGM-Doyle** [freeorion/freeorion#1174]
### Description
If your empire has a lower detection range than an opposing empire and you conquer one of their colonies, your newly conquered colony still has the detection range of the opposing empire long enough to reveal the map area that is outside of your detection range, but inside of the opposing empire's detection range.

### Expected Result
Your new colony's detection range should change to your empire's detection range, before exposing more map.

### Steps to reproduce
* Play game and let other empire get ahead of yours in detection range.
* Conquer one of their planets.
* Briefly see map area that is in other empire's detection range from the conquered colony.
* Detection range snaps back to your empire's correct detection range.

**Comment by geoffthemedio** [comment]
https://github.com/freeorion/freeorion/commit/40356093cf6b019b4069853e177fcfb90dbf8b82 resets detection, along with various other meters, when conquering. should resolve this.
