### ISSUE TITLE
Sidepanel stat icons flickers during turn updates

### ISSUE THREAD

**Issue by Vezzra** [freeorion/freeorion#1177]
### Environment

* **FreeOrion Version**: ~~eaf735e20cf50767a2ade2060543ca68d4d8affc~~ 853af0ea037ff01e0a63645984cebf0228f81a5a
* **Fetched as**
  * Weekly development build

### Description

~~When executing a turn, the stealth stat icon in the sidepanel does seem to flicker (go black) briefly (perhaps a frame), in the case where all the sub-panels are collapsed.~~

When executing a turn, any stat icon in the sidepanel that is too close to the arrow icons to the right does seem to flicker (go black) briefly (perhaps a frame). Once you resize the sidepanel so that there is a sufficient gap between the stat icon(s) and the arrow icon(s), the flickering is gone.
### Expected Result

Well, no flickering of course. 😃

**Comment by LGM-Doyle** [comment]
I can't see the flicker anymore.  I compared eaf735e and master and the flicker seems gone.

**Comment by Vezzra** [comment]
Nope, still there, however, I now discovered the real issue: it's not so much the stealth icon per se, it's any icon that is too close to the arrow icons to the right. Once you resize the sidepanel so that there is a sufficient gap between the stat icon(s) and the arrow icon(s), the flichering is gone. If a stat icon is too close to the arrow icon to the right of it, it flickers.

Edited title and OP accordingly.

**Comment by Vezzra** [comment]
So maybe you don't notice it because your sidepanel is sized so wide the gap between the stealth icon and the arrow icon is wide enough?

**Comment by LGM-Doyle** [comment]
@Vezzra thanks for triaging this issue.

**Comment by Vezzra** [comment]
Fixed by #1448.
