### ISSUE TITLE
Scrollbar missing on focus dropdown

### ISSUE THREAD

**Issue by MatGB** [freeorion/freeorion#1183]
### Environment

* **FreeOrion Version**: b7f04f3
* **Operating System**: Linux
  * Compiled from source

### Description
If a planet has multiple focus options (eg through a Transformer) and is focused on an option at the bottom of a list, on opening the sidepanel with the need to scroll *up* (ie to Industry), there is no scrollbar. Selecting Research, closing the sidepanel then reopening will then display industry. If set to Industry the scrollbar appears correctly to allow a scroll down.

The scrollbar, as far as I can tell, is only missing if, on opening the sidepanel, the selected focus is low enough on the list to normally trigger a need to scroll upwards.
![screenshot_20161220_150757](https://cloud.githubusercontent.com/assets/11533206/21355642/b8f13d52-c6c6-11e6-807a-45dbef630b3b.png)

**Comment by MatGB** [comment]
OK, this has now gone, so closing.

**Comment by Vezzra** [comment]
So, basically, the issue disappeared for no obvious reason...?

**Comment by MatGB** [comment]
And it's back with master compiled at d9352da, if you do scroll up and click select the display doesn't change as it should but the top focus is selected, it updates to show this when the UI updates the sidepanel registering the change.

As the preferred focus is almost always Industry it's a valid workaround but it's not good. As it appears to be intermittent and isn't always happening in the current game I'm not sure how to test further.

**Comment by Dilvish-fo** [comment]
I think the issue is not so much that a scrollbar is missing, but that the first item is getting omitted.  Note in the screenshot above that there is a blank spot at the bottom of the list.  Also, this is very easy to replicate for me, without needing any advanced techs like stargate -- for a planet with the typical set of initial focii, set the focus to Defense (the last one) and then advance a turn, and then go to change it back:

![humancolonymissingproductionfocuschoice](https://cloud.githubusercontent.com/assets/10995939/22799118/70ad1d66-eeb9-11e6-8719-e329afee725b.png)

**Comment by Vezzra** [comment]
> I think the issue is not so much that a scrollbar is missing, but that the first item is getting omitted.

You mean, a focus setting that should be there (industry?) is missing? *That* would actually be a very serious bug.

The blank line however has been around since forever I think...

**Comment by LGM-Doyle** [comment]
Thank you @Dilvish-fo for the straightforward replicator.

**Comment by geoffthemedio** [comment]
![droplist](https://cloud.githubusercontent.com/assets/11386908/22952489/96420552-f30d-11e6-9482-35c5e4486e5b.png)

bit of extra space at the bottom, which can be notably visible if the last item in the list is selection highlighted

**Comment by Vezzra** [comment]
@MatGB, #1307 fixed this, so we can close this as resolved, right?

**Comment by Vezzra** [comment]
Um, @MatGB? Can we close this...?

**Comment by MatGB** [comment]
Oh, yes, had missed your question earlier, appears fixed and haven't seen it for a bit now.
