### ISSUE TITLE
Freeorion crashes on closing fleet window

### ISSUE THREAD

**Issue by Voker57** [freeorion/freeorion#1191]
How to reproduce: click on any fleet icon, quickly press escape to close it. Version: 78182d468c75e8b70de414

Backtrace: http://dump.bitcheese.net/files/gigoxim/bt.txt

**Comment by adrianbroher** [comment]
> I'm guessing this relates to your recent loop replacements?

Probably.

**Comment by adrianbroher** [comment]
Couldn't reproduce the issue locally but after reviewing the change I found the bug that should cause the issue reported.

**Comment by Vezzra** [comment]
@Voker57, please confirm if the fix works for you.

**Comment by Voker57** [comment]
The fix works.

**Comment by Vezzra** [comment]
Thanks!
