### ISSUE TITLE
Sitrep list lacks a srollbar when the last item doesn't fit the window

### ISSUE THREAD

**Issue by l29ah** [freeorion/freeorion#1199]
![screenshot](https://dump.bitcheese.net/files/lonirun/screenshot-no-scrollbar.png)

**Comment by l29ah** [comment]
Also it seems related: sometimes when i scroll the list "page-wise" by clicking on the scrollbar, it skips one sitrep.

**Comment by Vezzra** [comment]
Fixed by #1356.
