### ISSUE TITLE
Blank screen on game start

### ISSUE THREAD

**Issue by MatGB** [freeorion/freeorion#1231]
### Environment

* **FreeOrion Version**: both e28e7c9 and d9352da
* **Operating System**: Linux
* **Graphic card used**: Gigabyte GA-F2A78M-HD2 (integrated)
  * Compiled from source

### Description
Black screen on game start, regardless of whether game is loaded from save, started using default quickstart or from the settings I've entered.

Game runs but once into client display where the mapwnd should be all I've got is black. 

Initially tried with current Head then did a hard reset to two commits previous, same result each time. Logs give no indication of problem and indicate game thinks it's running correctly. Am not technically proficient enough to do further investigation, if someone wants me to check by compiling before a specific commit am able to do so but I'd just be guessing as to how far back I need to go, I was able to compile and run master as at 2017-01-15

**Comment by geoffthemedio** [comment]
provide those logs, please... and make sure to delete them before generating them, to be sure they're new.

**Comment by MatGB** [comment]
Um, yeah *shameface*, rebooting the machine for other reasons has got everything working properly, I have zero clue what was wrong, possibly an FO process from earlier hadn't closed properly, but it does now run properly—I suspected it might be a hanging process when the other folder I compile into that was working fine earlier also had the same problem.
