### ISSUE TITLE
GetUniverseObject usage in conjunction with dynamic_pointer_cast

### ISSUE THREAD

**Issue by adrianbroher** [freeorion/freeorion#1243]
There are multiple places in the code where a generic `UniverseObject` is fetched from the `ObjectMap` and always casted to the specific subtype (including the additional error handling code).  The IApp interface provides direct accessors for those subtypes.

Executing `grep -rn dynamic_pointer_cast * | grep -v '\<if\>'` should list possible candidates for replacement.

* UI/Sidepanel.cpp:2390

**Comment by geoffthemedio** [comment]
https://github.com/freeorion/freeorion/blob/master/UI/SidePanel.cpp#L2391

**Comment by adrianbroher** [comment]
@geoffthemedio 

I don't quite get what you want to express with the link you posted?

**Comment by geoffthemedio** [comment]
Now that I fixed it, it points to the line you referenced. Makes seeing what you're referring to easier.

**Comment by adrianbroher** [comment]
Ah yes, linking the line to the github interface is a neat idea. I will update the recent issues accordingly.

**Comment by Vezzra** [comment]
@adrianbroher, has #1288 fixed this issue completely (so we can close as resolved), or only partially?

**Comment by Mitten-O** [comment]
I attempted to refactor every instance were the pointer was immediately cast to the more specific type. In many cases despite the code being aware of the type on a variable name and logic level, the object is never cast into it. It is less clear whether the refactoring make sense in those cases.

**Comment by adrianbroher** [comment]
@Mitten-O yes, you're right.  The instances don't need the subtype, but maybe the implicit validation that an ID refers to a specific subtype could be useful here.  Does anybody else have an option on this?

**Comment by geoffthemedio** [comment]
The remaining cases don't use dynamic_pointer_cast, if I understand correctly, so is there still a problem?

**Comment by adrianbroher** [comment]
Seems like a was unfocused when writing that comment.
