### ISSUE TITLE
Replace boost::lexical_cast<std::string> with std::to_string for fundamental types

### ISSUE THREAD

**Issue by adrianbroher** [freeorion/freeorion#1244]
Within the whole codebase we use `std::lexical_cast<std::string>` to convert fundamental types to an std::string.  Replacing those instances with a call to `std::to_string` would make the code much more readable.

However keep in mind that `std::to_string` only works for fundamental numeric types, not for custom enumerations.

Executing `grep -rn 'boost::lexical_cast<std::string>' *` should list a good list of candidates.

**Comment by Vezzra** [comment]
@adrianbroher, @dbenage-cx, with #1303 merged, can this issue be considered resolved and closed?

**Comment by adrianbroher** [comment]
After reviewing latest master I consider this task realized.  There are still some places missing but those involve custom types and also there is no std::string to numeral, but those cases were never in the scope of the original issue.
