### ISSUE TITLE
No Starting Ship

### ISSUE THREAD

**Issue by geoffthemedio** [freeorion/freeorion#1257]
When starting a game, I have no ships.

I don't see relevant errors in the server log.

**Comment by adrianbroher** [comment]
e66256bb doesn't have this problem.  Currently building 98e72a6a.

**Comment by adrianbroher** [comment]
98e72a6 works for me too.

Seems like I can't reproduce this on Linux.

**Comment by geoffthemedio** [comment]
seems to have magically fixed itself, maybe after rebuilding...
