### ISSUE TITLE
progress bar not working (when planet is disconnected from supply?)

### ISSUE THREAD

**Issue by TheSilentOne1** [freeorion/freeorion#1259]
![progress bar bug](https://cloud.githubusercontent.com/assets/12985960/22479243/4ef4d11e-e7ed-11e6-8814-d6cdf9c40f8c.jpg)
The progress bar on the sidepanel doesn't seem to work as intended, probably if the planet is out of supply range. Can provide a save if necessary. Current build.

**Comment by dbenage-cx** [comment]
Could you clarify how this issue is different from #1201?

**Comment by TheSilentOne1** [comment]
Sorry I had forgotten this had been reported / thought this had been fixed. Closing.
