### ISSUE TITLE
Missing Word in Stringtable

### ISSUE THREAD

**Issue by geoffthemedio** [freeorion/freeorion#1260]
https://github.com/freeorion/freeorion/blob/master/default/stringtables/en.txt#L10822

"...Note the needs to have been in system for a turn..."

I'm not sure what needs to have been there, though.

**Comment by MatGB** [comment]
Ow, that's one of mine, and it got proofread. Ship, the word ship is missing. Will fix.

**Comment by MatGB** [comment]
Actually, it was beacon, either type needs to have been there a turn. Thanks.
