### ISSUE TITLE
Build fails via freeorion-git package for archlinux in aur repository

### ISSUE THREAD

**Issue by hakova** [freeorion/freeorion#1267]
The build failed with the following error message. Please advise:

In file included from /usr/include/boost/phoenix/object/detail/cpp03/preprocessed/construct.hpp:12:0,
from /usr/include/boost/phoenix/object/detail/cpp03/construct.hpp:6,
from /usr/include/boost/phoenix/object/construct.hpp:76,
from /usr/include/boost/phoenix/object.hpp:12,
from /usr/include/boost/phoenix/phoenix.hpp:15,
from /usr/include/boost/phoenix.hpp:11,
from /usr/include/boost/spirit/include/phoenix.hpp:11,
from /tmp/yaourt-tmp-mancar/aur-freeorion-git/src/freeorion.git/parse/ConditionParserImpl.h:6,
from /tmp/yaourt-tmp-mancar/aur-freeorion-git/src/freeorion.git/parse/ValueRefParserImpl.h:3,
from /tmp/yaourt-tmp-mancar/aur-freeorion-git/src/freeorion.git/parse/DoubleComplexValueRefParser.cpp:1:
/usr/include/boost/phoenix/object/detail/cpp03/preprocessed/construct_10.hpp: In instantiation of ‘const typename boost::phoenix::expression::construct<boost::phoenix::detail::target<T>, A0>::type boost::phoenix::construct(const A0&) [with T = std::__cxx11::basic_string<char>; A0 = char [21]; typename boost::phoenix::expression::construct<boost::phoenix::detail::target<T>, A0>::type = boost::phoenix::actor<boost::proto::exprns_::basic_expr<boost::phoenix::tag::construct, boost::proto::argsns_::list2<boost::proto::exprns_::basic_expr<boost::proto::tagns_::tag::terminal, boost::proto::argsns_::term<boost::phoenix::detail::target<std::__cxx11::basic_string<char> > >, 0l>, boost::proto::exprns_::basic_expr<boost::proto::tagns_::tag::terminal, boost::proto::argsns_::term<char*>, 0l> >, 2l> >]’:
/tmp/yaourt-tmp-mancar/aur-freeorion-git/src/freeorion.git/parse/DoubleComplexValueRefParser.cpp:58:96: required from here
/usr/include/boost/phoenix/object/detail/cpp03/preprocessed/construct_10.hpp:23:25: error: invalid conversion from ‘const char*’ to ‘param_type {aka char*}’ [-fpermissive]
expression::
~~~~~~~~~~~~
construct<detail::target<T>, A0>::
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make(detail::target<T>(), a0);
~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/boost/phoenix/core/argument.hpp:14:0,
from /usr/include/boost/phoenix/core.hpp:15,
from /usr/include/boost/spirit/include/phoenix_core.hpp:11,
from /usr/include/boost/spirit/home/support/terminal.hpp:17,
from /usr/include/boost/spirit/home/support/common_terminals.hpp:15,
from /usr/include/boost/spirit/home/lex/lexer/terminals.hpp:13,
from /usr/include/boost/spirit/home/lex/lexer.hpp:13,
from /usr/include/boost/spirit/home/lex.hpp:13,
from /usr/include/boost/spirit/home/lex/lexer_lexertl.hpp:15,
from /usr/include/boost/spirit/include/lex_lexertl.hpp:16,
from /tmp/yaourt-tmp-mancar/aur-freeorion-git/src/freeorion.git/parse/Lexer.h:6,
from /tmp/yaourt-tmp-mancar/aur-freeorion-git/src/freeorion.git/parse/ValueRefParser.h:4,
from /tmp/yaourt-tmp-mancar/aur-freeorion-git/src/freeorion.git/parse/ValueRefParserImpl.h:1,
from /tmp/yaourt-tmp-mancar/aur-freeorion-git/src/freeorion.git/parse/DoubleComplexValueRefParser.cpp:1:
/usr/include/boost/phoenix/core/expression.hpp:63:21: note: initializing argument 2 of ‘static boost::phoenix::expr_ext<Actor, Tag, A>::type boost::phoenix::expr_ext<Actor, Tag, A>::make(typename boost::call_traits<A>::param_type ...) [with Actor = boost::phoenix::actor; Tag = boost::phoenix::tag::construct; A = {boost::phoenix::detail::target<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, char*}; boost::phoenix::expr_ext<Actor, Tag, A>::type = boost::phoenix::actor<boost::proto::exprns_::basic_expr<boost::phoenix::tag::construct, boost::proto::argsns_::list2<boost::proto::exprns_::basic_expr<boost::proto::tagns_::tag::terminal, boost::proto::argsns_::term<boost::phoenix::detail::target<std::__cxx11::basic_string<char> > >, 0l>, boost::proto::exprns_::basic_expr<boost::proto::tagns_::tag::terminal, boost::proto::argsns_::term<char*>, 0l> >, 2l> >]’
static type make(typename call_traits<A>::param_type... a)
^~~~
In file included from /usr/include/boost/phoenix/object/detail/cpp03/preprocessed/construct.hpp:12:0,
from /usr/include/boost/phoenix/object/detail/cpp03/construct.hpp:6,
from /usr/include/boost/phoenix/object/construct.hpp:76,
from /usr/include/boost/phoenix/object.hpp:12,
from /usr/include/boost/phoenix/phoenix.hpp:15,
from /usr/include/boost/phoenix.hpp:11,
from /usr/include/boost/spirit/include/phoenix.hpp:11,
from /tmp/yaourt-tmp-mancar/aur-freeorion-git/src/freeorion.git/parse/ConditionParserImpl.h:6,
from /tmp/yaourt-tmp-mancar/aur-freeorion-git/src/freeorion.git/parse/ValueRefParserImpl.h:3,
from /tmp/yaourt-tmp-mancar/aur-freeorion-git/src/freeorion.git/parse/DoubleComplexValueRefParser.cpp:1:
/usr/include/boost/phoenix/object/detail/cpp03/preprocessed/construct_10.hpp: In instantiation of ‘const typename boost::phoenix::expression::construct<boost::phoenix::detail::target<T>, A0>::type boost::phoenix::construct(const A0&) [with T = std::__cxx11::basic_string<char>; A0 = char [22]; typename boost::phoenix::expression::construct<boost::phoenix::detail::target<T>, A0>::type = boost::phoenix::actor<boost::proto::exprns_::basic_expr<boost::phoenix::tag::construct, boost::proto::argsns_::list2<boost::proto::exprns_::basic_expr<boost::proto::tagns_::tag::terminal, boost::proto::argsns_::term<boost::phoenix::detail::target<std::__cxx11::basic_string<char> > >, 0l>, boost::proto::exprns_::basic_expr<boost::proto::tagns_::tag::terminal, boost::proto::argsns_::term<char*>, 0l> >, 2l> >]’:
/tmp/yaourt-tmp-mancar/aur-freeorion-git/src/freeorion.git/parse/DoubleComplexValueRefParser.cpp:67:98: required from here
/usr/include/boost/phoenix/object/detail/cpp03/preprocessed/construct_10.hpp:23:25: error: invalid conversion from ‘const char*’ to ‘param_type {aka char*}’ [-fpermissive]
expression::
~~~~~~~~~~~~
construct<detail::target<T>, A0>::
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make(detail::target<T>(), a0);
~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/boost/phoenix/core/argument.hpp:14:0,
from /usr/include/boost/phoenix/core.hpp:15,
from /usr/include/boost/spirit/include/phoenix_core.hpp:11,
from /usr/include/boost/spirit/home/support/terminal.hpp:17,
from /usr/include/boost/spirit/home/support/common_terminals.hpp:15,
from /usr/include/boost/spirit/home/lex/lexer/terminals.hpp:13,
from /usr/include/boost/spirit/home/lex/lexer.hpp:13,
from /usr/include/boost/spirit/home/lex.hpp:13,
from /usr/include/boost/spirit/home/lex/lexer_lexertl.hpp:15,
from /usr/include/boost/spirit/include/lex_lexertl.hpp:16,
from /tmp/yaourt-tmp-mancar/aur-freeorion-git/src/freeorion.git/parse/Lexer.h:6,
from /tmp/yaourt-tmp-mancar/aur-freeorion-git/src/freeorion.git/parse/ValueRefParser.h:4,
from /tmp/yaourt-tmp-mancar/aur-freeorion-git/src/freeorion.git/parse/ValueRefParserImpl.h:1,
from /tmp/yaourt-tmp-mancar/aur-freeorion-git/src/freeorion.git/parse/DoubleComplexValueRefParser.cpp:1:
/usr/include/boost/phoenix/core/expression.hpp:63:21: note: initializing argument 2 of ‘static boost::phoenix::expr_ext<Actor, Tag, A>::type boost::phoenix::expr_ext<Actor, Tag, A>::make(typename boost::call_traits<A>::param_type ...) [with Actor = boost::phoenix::actor; Tag = boost::phoenix::tag::construct; A = {boost::phoenix::detail::target<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, char*}; boost::phoenix::expr_ext<Actor, Tag, A>::type = boost::phoenix::actor<boost::proto::exprns_::basic_expr<boost::phoenix::tag::construct, boost::proto::argsns_::list2<boost::proto::exprns_::basic_expr<boost::proto::tagns_::tag::terminal, boost::proto::argsns_::term<boost::phoenix::detail::target<std::__cxx11::basic_string<char> > >, 0l>, boost::proto::exprns_::basic_expr<boost::proto::tagns_::tag::terminal, boost::proto::argsns_::term<char*>, 0l> >, 2l> >]’
static type make(typename call_traits<A>::param_type... a)
^~~~
make[2]: *** [parse/CMakeFiles/freeorionparse.dir/build.make:351: parse/CMakeFiles/freeorionparse.dir/DoubleComplexValueRefParser.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:285: parse/CMakeFiles/freeorionparse.dir/all] Error 2
make: *** [Makefile:150: all] Error 2
==> ERROR: A failure occurred in build().
Aborting...
==> ERROR: Makepkg was unable to build freeorion-git.

**Comment by dbenage-cx** [comment]
@hakova boost 1.63? Please try with `-DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION`

([related comment](https://github.com/freeorion/freeorion/pull/1202#discussion_r95624549) which I should have opened an issue for)

**Comment by hakova** [comment]
@dbenage-cx Yes, boost version is 1.63.0-1. I don't have a coding background but I guessed that I should paste the option you provided in PKGBUILD in the line that reads
`cmake -DCMAKE_INSTALL_PREFIX=/usr ../freeorion-git`
Build still failed with the following error:

...
==> Starting build()...
Parse error in command line argument: -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION
Should be: VAR:type=value
CMake Error: No cmake script provided.
CMake Error: Problem processing arguments. Aborting.

==> ERROR: A failure occurred in build().
    Aborting...
==> ERROR: Makepkg was unable to build freeorion-git.

**Comment by dbenage-cx** [comment]
Possibly:
 `cmake -DCMAKE_CXX_FLAGS=-DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION -DCMAKE_INSTALL_PREFIX=/usr ../freeorion-git`
, though I'm not well versed in setting such flags.

Regardless, I see this flag as a workaround for something that can be trivially fixed.

**Comment by Vezzra** [comment]
@hakova, can you test PR #1271 and confirm if that fixes the issue for you?

**Comment by hakova** [comment]
@dbenage-cx  I tried following your recommendation and it almost worked; however there was a last minute error as follows:

`(1/1) checking keys in keyring                                                                                                                                             [##########################################################################################################] 100%
(1/1) checking package integrity                                                                                                                                           [##########################################################################################################] 100%
(1/1) loading package files                                                                                                                                                [##########################################################################################################] 100%
(1/1) checking for file conflicts                                                                                                                                          [##########################################################################################################] 100%
error: failed to commit transaction (conflicting files)
freeorion-git: /usr/lib64 exists in filesystem
Errors occurred, no packages were upgraded.
==> WARNING: Your packages are saved in /tmp/yaourt-tmp-mancar
`

@Vezzra I am not sure how to test PR #1271 but see my reply to @dbenage-cx above.

Thanks for the prompt responses!

**Comment by dbenage-cx** [comment]
@hakova Should be fixed in master without the need for a flag/define addition.

From the message displayed, it sounds like your local changes are preventing an update?  But I am not familiar with the setup arch uses to be of much use here.

**Comment by adrianbroher** [comment]
> failed to commit transaction (conflicting files) freeorion-git: /usr/lib64 exists in filesystem Errors occurred

That's out of scope for our project.  Ask the packager to fix the package ownership for the /usr/lib64 directory.

**Comment by Vezzra** [comment]
@hakova, as #1271 has already been merged, just try to build master. Regarding the other error you're getting now: what @adrianbroher said, he is our resident expert on these things.
