### ISSUE TITLE
Sitrep Ignore / Block Options Empty or Disabled

### ISSUE THREAD

**Issue by geoffthemedio** [freeorion/freeorion#1270]
Start a game, right click on a sitrep. It should have options to block or ignore, but they are always greyed out and cannot be used.
![sitrep](https://cloud.githubusercontent.com/assets/11386908/22570437/8cf67c06-e99b-11e6-8991-6fa774b2f478.png)

**Comment by dbenage-cx** [comment]
f618d1b

**Comment by Vezzra** [comment]
@adrianbroher, f618d1bbf8d32631dbb9e8de5160f7ad4981ff30 is one of yours...

**Comment by adrianbroher** [comment]
Seems like I confused the initialized values for the different constructors.
