### ISSUE TITLE
Unable to queue more than one building on same planet

### ISSUE THREAD

**Issue by MatGB** [freeorion/freeorion#1279]
### Environment

* **FreeOrion Version**: 5ecb1cb
* **Operating System**: Linux
  * Compiled from source

### Description
I'm unable to build some buildings on the same planet at the same time. First noticed with Scanning Facility (see screenshot), couldn't work it out, then when the colony building completed I could queue a scanning facility but when adding it to the queue the shipyard disappeared.

I think that the ENQUEUE_BUILD_ONE_PER_PLANET macro is messing up, perhaps something is wrong with the CurrentContent check?

### Expected Result
Buildings that aren't scripted to be exclusive builds should be buildable concurrently, especially important if the Colony buildings are blocking other developments.

![screenshot_20170204_232340](https://cloud.githubusercontent.com/assets/11533206/22622522/4a1e3686-eb34-11e6-8db0-09f9c6654185.png)

**Comment by MatGB** [comment]
Commenting out [the enqueued condition](https://github.com/freeorion/freeorion/blob/master/default/scripting/common/enqueue.macros#L4) makes it possible to build more than one thing, including multiples of the same thing, before and after this change a completed building ceased blocking things correctly, it may therefore be a problem with Enqueued rather than CurrentContent.

**Comment by Vezzra** [comment]
Hm, that has been working flawlessly for ages, so here too it would be good if someone could track down which commit introduced the issue...

**Comment by MatGB** [comment]
Aye, all I can say for sure is that it came in after 210004e because that was my previous compile (I alternate builds these days).

**Comment by dbenage-cx** [comment]
2790cb4 not certain why, but will try a couple alternatives for boost 1.63 compatibility

**Comment by Vezzra** [comment]
2790cb4f3fda2a482f664475413eeb28ff6d3c48 introduced the issue? That indeed sounds very strange... why would these changes trigger such an issue...?

**Comment by dbenage-cx** [comment]
There should be a building name before `buildings on the production queue` in the posted tooltip.
Possibly from namespace, giving it some testing.

**Comment by geoffthemedio** [comment]
For some reason, it's initializing the `Enqueued` condition with a `ValueRef::Constant<std::string>` which has an empty string as the value it's trying to match. It should be initialized with "CurrentContent".

**Comment by geoffthemedio** [comment]
semi-random guess: add explicit before declariation of the ValueRef::Constant<T> constructor?

**Comment by dbenage-cx** [comment]
Having success with: https://github.com/dbenage-cx/freeorion/tree/fix_1279-variable_scope

**Comment by geoffthemedio** [comment]
maybe also try declaring the static?

**Comment by geoffthemedio** [comment]
this is perhaps a case where automated testing of parsing results would have helped?

**Comment by dbenage-cx** [comment]
Yes, though I've never been successful in even manually running these (probably doing it wrong to start with).
