### ISSUE TITLE
Mines can't destroy ships

### ISSUE THREAD

**Issue by Voker57** [freeorion/freeorion#1283]
Version: 387a65d513bf379ae

Save: http://dump.bitcheese.net/files/gukaseh/undying.mps

Voker57 empire. At the end of turn, ship at Rheims 3 will die and resurrect.

**Comment by dbenage-cx** [comment]
Going to summarize the conditions until it a similar situation can be reconstructed and verified.

The save game is `v0.4.6+ teamsmac [build 2017-02-05.7605a7f]`, this does not seem to load correct from master (game does not fully start).
Using that branch, I can start a game with just selecting a player for the empire NBL.

The ship in question is a compressed energy hull + active radar with kobuntura pilots (45 stealth, 1.0 structure remaining), owned by the empire NBL.
The system contains an unowned(and unpopulated) planet with a fortress and a sentry monster (40 detection). Suspect the only points of concern here are an unowned and unpopulated planet with a fortress, and an empire owned ship with similar stealth.

A sitrep is issued each turn stating the ship is destroyed from mines, however the ship remains (with the same ID).

**Comment by MatGB** [comment]
This might be a problem specific to the Fortress, I've just had my newly conquered outpost destroy an AI ship in orbit and it's definitely gone.
