### ISSUE TITLE
Multiplayer game can start when players have same color

### ISSUE THREAD

**Issue by l29ah** [freeorion/freeorion#1284]

**Comment by geoffthemedio** [comment]
Related to: https://github.com/freeorion/freeorion/pull/1187

**Comment by afwbkbc** [comment]
Not an issue. Sometimes in i.e. 3x3 game it's convenient for team to have same color. Host can always ask player to change color before starting game. Please don't fix.

**Comment by l29ah** [comment]
On Tue, Feb 07, 2017 at 02:07:32AM -0800, afwbkbc wrote:
> Not an issue. Sometimes in i.e. 3x3 game it's convenient for team to have same color. Host can always ask player to change color before starting game. Please don't fix.

Even in this case at least changing a color must reset the readiness flag for everyone.

-- 
()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments

**Comment by geoffthemedio** [comment]
Since players cannot presently control eachothers' planets / ships, having them all be the same colour would be problematic at best. A team can use similar colours to avoid confusion about allegiances, with the opponents set to contrasting colours in a multiplayer game.

**Comment by afwbkbc** [comment]
"Even in this case at least changing a color must reset the readiness flag for everyone." - why? color is solely player's personal choise and shouldn't bother others.

**Comment by geoffthemedio** [comment]
because you're in a multiplayer game, and someone changing the settings, including empire colour, may change someone else's mind about whether they like the current setup

**Comment by o01eg** [comment]
The color is what other players see so it bothers. Even in the games with team support players have a different color.

**Comment by MatGB** [comment]
Different people have different ability to perceive differentiation in colour, and it's important to be able to tell the difference between your systems/fleets and those of others quickly.

What might be to you two strongly different colours might be to another very similar shades, differing monitors/settings, etc may exacerbate this. If you set your colour to be very close to mine, I'm going to want to change mine or ask you to change yours, I simply couldn't play with someone else using a very close to mine shade.

**Comment by afwbkbc** [comment]
"differing monitors/settings, etc may exacerbate this" - ok, so what if some player is blind or using monitor that is monochrome or is turned off? Maybe cover these cases too, then?
Typical person can easily distinguish #AAAAAA from #AAAAAF , so there is no problem, unless some player intentionally picks same color to deceive. But then host just won't start the game until he behaves.

"may change someone else's mind about whether they like the current setup" - i seriously doubt somebody may suddenly dislike game just because somebody chose color he doesn't like. If such obstacle happens, a psychiatrist may be one good solution.
Let's not discuss impossible scenarios and invent artificial problems here.

"

**Comment by afwbkbc** [comment]
My point is that it should be up to host to decide if players can have same colors or not. There is no reason to enforce it it code - this will just limit freedom without any benefits. So let's just close this issue.

**Comment by LGM-Doyle** [comment]
Why not leave it up to each individual HumanClient?  

The color does not matter to the game mechanics or the AIs.  Each player may have different perception of and requirements for the color.  Players don't need to be using a common color scheme. 

Start from the colors that the host accepts.  After that if one player wants to have all of their teammates one color, then they can without inconveniencing any other player.

**Comment by geoffthemedio** [comment]
Alternate team colouring vs. enemy vs. self colouring, overriding the empires' selected colours, is something I'd implement as an option during the game, not affected or affecting galaxy and player setup.

**Comment by dbenage-cx** [comment]
> Why not leave it up to each individual HumanClient?

I agree with this but sounds like it may require some significant changes.  There are a number of other changes I'd like to see which would alter player setup data as well which includes a remodel of the lobby window.  I'll make a proposal on forum, probably with a post 0.4.7 target.

**Comment by l29ah** [comment]
On Tue, Feb 07, 2017 at 03:49:42AM -0800, afwbkbc wrote:
> "Even in this case at least changing a color must reset the readiness flag for everyone." - why? color is solely player's personal choise and shouldn't bother others.

Because being unable to tell friends and enemies apart IS bothering everyone.

-- 
()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments
