### ISSUE TITLE
Boost 1.63 compatibility

### ISSUE THREAD

**Issue by subpop** [freeorion/freeorion#1289]
### Environment

* **FreeOrion Version**: 0.4.6
* **Operating System**: Linux
* **Graphic card used**: Intel
* **Fetched as**: Compiled from source

### Description
Fedora rawhide recently updated to Boost 1.63. The rawhide build service reported 0.4.6 failed to build from source ([full build log](https://kojipkgs.fedoraproject.org/work/tasks/9893/17639893/build.log)). I looked at the build long and it *might* be a compatibility issue with Boost 1.63.

```
[...snippet...]
In file included from /usr/include/boost/archive/detail/interface_iarchive.hpp:22:0,
                 from /usr/include/boost/archive/detail/common_iarchive.hpp:23,
                 from /usr/include/boost/archive/basic_binary_iarchive.hpp:30,
                 from /usr/include/boost/archive/binary_iarchive_impl.hpp:21,
                 from /usr/include/boost/archive/binary_iarchive.hpp:20,
                 from /builddir/build/BUILD/src-tarball/util/Serialize.h:4,
                 from /builddir/build/BUILD/src-tarball/util/SerializeUniverse.cpp:1:
/usr/include/boost/archive/detail/iserializer.hpp: In instantiation of 'static void boost::archive::detail::heap_allocation<T>::doesnt_have_new_operator::invoke_delete(T*) [with T = Ship]':
/usr/include/boost/archive/detail/iserializer.hpp:265:33:   required from 'static void boost::archive::detail::heap_allocation<T>::invoke_delete(T*) [with T = Ship]'
/usr/include/boost/archive/detail/iserializer.hpp:273:26:   required from 'boost::archive::detail::heap_allocation<T>::~heap_allocation() [with T = Ship]'
/usr/include/boost/archive/detail/iserializer.hpp:294:36:   required from 'void* boost::archive::detail::pointer_iserializer<Archive, T>::heap_allocation() const [with Archive = boost::archive::binary_iarchive; T = Ship]'
/builddir/build/BUILD/src-tarball/util/SerializeUniverse.cpp:351:133:   required from here
/usr/include/boost/archive/detail/iserializer.hpp:246:17: error: 'virtual Ship::~Ship()' is protected within this context
                 delete t;
                 ^~~~~~
[...snippet...]
```

The full build record is [here](https://apps.fedoraproject.org/koschei/build/2561545). I'm not 100% sure this is a boost issue. I'm happy to provide more info and/or testing within the Fedora build infrastructure.

**Comment by dbenage-cx** [comment]
Looks related to #1245 ([relevant workaround commit](https://github.com/freeorion/freeorion/commit/e09032b0ca3ee5e6fe16b3d23355237f5dc534b6))

I'm successful in testing on Fedora 25 + boost 1.63 from source, a couple of other commits you may need specific to this boost version: 802b9f3 2790cb4

**Comment by subpop** [comment]
Hm. This isn't affecting a Fedora release and #1245 hasn't been accepted. I'll keep an eye on it.

**Comment by geoffthemedio** [comment]
> #1245 hasn't been accepted.

What do you mean?

https://github.com/freeorion/freeorion/blob/master/universe/Ship.h#L130

`~Ship()` is public in master.

**Comment by adrianbroher** [comment]
> This isn't affecting a Fedora release and #1245 hasn't been accepted.

We don't have any 'accepted' issue status.

**Comment by l29ah** [comment]
freeorion is developing quite rapidly, consider using the master branch.
