### ISSUE TITLE
serious FPS problems

### ISSUE THREAD

**Issue by afwbkbc** [freeorion/freeorion#1291]
For some reason FPS in freeorion is LOWER than in Fallout 4 1920x1080 ULTRA settings.

My configuration: AMD FX-9590 / 32GB 2400Mhz DDR3 / ASUS STRIX Geforce GTX 1070 O8E OC
In freeorion I only get 130-170 FPS (the absolute maximum was 184FPS).
This is ridiculous.
Are there some sleep() calls or relaxed timers that contribute to this? My hardware is hardly bottleneck here.
I have 144hz monitor and it's really uncomfortable when FPS drops below 144. And for perfect smoothness/responsiveness FPS must be > 288.
Also most stereoscopic 3d techniques (i.e. Dolby 3D, actually anything with exception of active shutter glasses) require FPS of ( 2 x monitor refresh rate ) to look smooth, and twice as much for perfect smoothness/responsiveness.
So, please fix FPS for high-end systems that can clearly handle it.
Also there is "Max FPS" setting which can't be disabled and is limited to ridiculously low 240. Please add option to disable FPS limiter or at least don't limit it to 240.

**Comment by afwbkbc** [comment]
Note that there already are 200hz monitors, which, when coupled with stereo 3d glasses, will require 800+ FPS from application for comfortable play.

**Comment by geoffthemedio** [comment]
I suppose FreeOrion is not the game for you.

**Comment by afwbkbc** [comment]
What? I like freeorion, I just want it smoother.

**Comment by geoffthemedio** [comment]
If you think "only" 184 FPS is ridiculous for a turn based strategy game where you spend minutes at a time looking at a nearly-static screen of text and unanimated images, your standards for smoothness are unrealistic for the level of effort we are likely to put into optimizing rendering.

**Comment by adrianbroher** [comment]
> This is ridiculous.

FreeOrion doesn't aim to be a benchmarking tool, still carries a good amount of technical debt and isn't a A³ title.

> What? I like freeorion, I just want it smoother.

Changes like that are not about flipping a switch or changing a compile flag and suddenly the application becomes XXX% faster.  To achieve your request probably some bigger internal redesign and programming is required and I assume nobody in the team is willing to work on this if the numbers are far beyond of what we consider 'good enough', especially if there are more pressing issues at hand.

**Comment by Vezzra** [comment]
> I have 144hz monitor and it's really uncomfortable when FPS drops below 144.

Inhowfar? I can't imagine how anything above 60 FPS would be even discernible by the human eye...? Or is the problem here that the monitor displays a blurry/flickering image if the FPS drops below its frequency? In that case, can't you switch your monitor to a lower frequency when playing FO?

> And for perfect smoothness/responsiveness FPS must be > 288.

For that to even notice you need to have the reflexes of Data, the cyborg from Star Trek... 😉

**Comment by geoffthemedio** [comment]
Data was an android, not a cyborg, except perhaps for a part of the First Contact movie when the borg grafted some skin onto him.

**Comment by l29ah** [comment]
Well, i have 10-15fps in endgame even w/o zooming out.

**Comment by Vezzra** [comment]
> Data was an android, not a cyborg

Argh, right of course. That's what I meant, just somehow ended up using the wrong word. Blame it on my still sickness-impaired mind. 😉

**Comment by Vezzra** [comment]
> Well, i have 10-15fps in endgame even w/o zooming out.

*That* actually is a serious FPS problem, and something we're constantly working on anyway.

Which why it's so bizarre if someone complains about having *only* 130 FPS... I guess you'd be *thrilled* if you had that...
