### ISSUE TITLE
Implement distributed execution of server code

### ISSUE THREAD

**Issue by afwbkbc** [freeorion/freeorion#1293]
If I understand correctly, server now handles entire processing of universe and stuff. It means scalability is near-zero - the larger is universe / number of players - the greater is overhead on host machine. If it has weak CPU, game will lag.
Solution: split universe to "regions", every of which is assigned to one client to process. In the end clients synchronise their processed regions with host and he may somehow validate validity of received data.
Benefits:
1) SCALABILITY! it will be possible to easily host 5000-system universe with 100 players and everything be lightning-fast. Even 100000 systems with 1000 players will be easy. So freeorion can easily be turned into MMO4X-something.
2) RESILIENCE! Even if host is disconnected, his region is just split and assigned to other players, one of which will become new host. Even if 5 of 6 players disconnect, universe will stay intact because one player still hosts it.
3

**Comment by adrianbroher** [comment]
@afwbkbc Is today the day of unreasonable requests?

@geoffthemedio Did you intent to set the milestone to 'void'? That's for invalid requests only.

**Comment by adrianbroher** [comment]
> what is unreasonable here? Performance benefits are pretty clear, no?

The request to change the application design. The cost-benefit ratio is pretty clear, no?  This won't happen.

**Comment by geoffthemedio** [comment]
I thought it meant something like "probably never".

**Comment by adrianbroher** [comment]
@geoffthemedio 

> I thought it meant something like "probably never".

It does, but then there should be a corresponding status assigned too.

**Comment by Vezzra** [comment]
@afwbkbc, what you suggest isn't possible the way FO, especially the effects engine, is designed. As basically everything can affect everything, splitting the map into segments as you suggest and process this segments in parallel can't work.

For that we'd basically had to redesign and rewrite the game. I hope you can see how that's not possible, and any attempt at this will probably just kill the entire project.

Believe me, if it where that easy, we would have done that a long time ago.
