### ISSUE TITLE
Add pep8 check for travis builds.

### ISSUE THREAD

**Issue by Cjkjvfnby** [freeorion/freeorion#1296]
This should be easy to implement (according to first code example on https://gist.github.com/MichaelCurrie/802ce28c993ff2dd632c)

There are possible number of errors to fix. (I will fix them soon)
```
PS F:\projects\freeorion> pep8 --statistic -qq ./ --max-line-length=120
4       E114 indentation is not a multiple of four (comment)
8       E122 continuation line missing indentation or outdented
1       E125 continuation line with same indent as next logical line
5       E127 continuation line over-indented for visual indent
4       E128 continuation line under-indented for visual indent
7       E129 visually indented line with same indent as next logical line
32      E201 whitespace after '('
1       E202 whitespace before ')'
1       E221 multiple spaces before operator
8       E225 missing whitespace around operator
8       E231 missing whitespace after ','
1       E265 block comment should start with '# '
3       E266 too many leading '#' for block comment
1       E271 multiple spaces after keyword
21      E302 expected 2 blank lines, found 1
1       E303 too many blank lines (3)
34      E402 module level import not at top of file
544     E501 line too long (144 > 120 characters)
1       E711 comparison to None should be 'if cond is None:'
3       E713 test for membership should be 'not in'
1       E721 do not compare types, use 'isinstance()'
5       E731 do not assign a lambda expression, use a def
3       W291 trailing whitespace
24      W293 blank line contains whitespace
7       W391 blank line at end of file
36      W503 line break before binary operator
```

**Comment by adrianbroher** [comment]
It's not a bad idea and should be doable.  I would need to update the docker image to include the pep8 tool so this may take a bit of time.  However I do have some questions:

* Do you plan to fix the listed issues before we introduce the pep8 tool to the CI build?
* I would use a separate Travis-CI job for this to balance out the build.  Should this build be allowed to fail or not? If you don't know what I am talking about: https://travis-ci.org/freeorion/freeorion we currently have 3 jobs on Travis:
  * Compile FO on Linux with GCC (must not fail)
  * Compile FO on MacOSX with Xcode Clang (must not fail)
  * Generate and upload C++ code documentation with Doxygen (can fail)
* Should this 'check' only complain about PEP-8 compliance fail if they were introduced between the last and this build or should it display all compliance fail, including old ones?

**Comment by Cjkjvfnby** [comment]
- I expect that start of the docker and checkout project will take more time than testing, so may be add it too some compile builds?
- I plan to fix most of the issues, only possible conflicts with other branch stops me. 
- We can start from recommended (may fail)
-  We can check only diff with base branch ```New option --diff to check only modified code. The unified diff is read from STDIN. Example: hg diff | pep8 --diff (Issue #39)```

**Comment by Cjkjvfnby** [comment]
I almost fixed all warnings, but need to wait for windows build to run code.   Is it possible to download compiled build from travis (put them to dropbox)?

**Comment by adrianbroher** [comment]
> Is it possible to download compiled build from travis (put them to dropbox)?

We use AppVeyor to build the Windows exectuable.  Yes, it is possible to store build artifacts but it isn't configured yet.

**Comment by Cjkjvfnby** [comment]
Is it possible to setup Travis runs based on file changes?  I got c++ build started on my pure python PR.

PS. I did not find special Travis discussion on forum, do we have one?

**Comment by adrianbroher** [comment]
> Is it possible to setup Travis runs based on file changes? I got c++ build started on my pure python PR.

In Travis it would be possible to look up the changed files via something `git diff --names-only ${TRAVIS_COMMIT_RANGE}`, compare the changes against a `.gitignore`-like blacklist and exit the build early.  I haven't implemented that and for now I don't see a point for changing that.  AppVeyor provides a builtin blacklist similar to the described capabilities.

> I did not find special Travis discussion on forum, do we have one?

There is none yet.  I will open one.

**Comment by Cjkjvfnby** [comment]
pep8 check via flake8 are working on Travis.
