### ISSUE TITLE
Invalid config settings for colors

### ISSUE THREAD

**Issue by dbenage-cx** [freeorion/freeorion#1298]
OS: Linux - GCC 6.3.1
Compiled from: ee31bf3

On creation of a new config.xml file, all of the color values are either empty or contain invalid characters  (file now contains non-UTF8 chars)

```
    <ctrl-border-color>(|,|,|,)</ctrl-border-color>
    <ctrl-color>(,,,)</ctrl-color>
    <default-link-color>(P,,,)</default-link-color>
```

@geoffthemedio d4f7e34 related? (not verified)

**Comment by adrianbroher** [comment]
> d4f7e34 related? (not verified)

Probably yes. GG::Color holds `unsigned char`s, StreamableColor holds `int`s.  The std::ostream prints chars as the character instead of the numeric value. I'm currently testing a fix for this.
