### ISSUE TITLE
Add Postfix to Disambiguate Player Names in Multiplayer

### ISSUE THREAD

**Issue by geoffthemedio** [freeorion/freeorion#1306]
If to players join a multiplayer game, and they have the same name, the latest joiner's name should be adjusted to disambiguate them.

Also, if a player joins with the same name as another, or with a name that matches another player's empire name, the default empire name for the new player should be modified to avoid giving two players duplicate empire names.

**Comment by o01eg** [comment]
Should the server just reject player who join with someone name? If sometimes authorization will be implemented the changing player name as a login name will lead to misunderstanding.

**Comment by o01eg** [comment]
I suppose this PR solve it: https://github.com/freeorion/freeorion/pull/1314

**Comment by geoffthemedio** [comment]
I would much rather have it change the name, if only for the use case of running two clients on the same computer and connecting to the same MP game. The player name will by default be the same, and part of the reason I posted this issue was that it was annoying to have to change the empire name of one of them in the MP lobby to be able to start the game. If I can't even connect without remembering to first change the second joiner's player name, that's even more annoying.
