### ISSUE TITLE
Min/Max ValueRefs Only Consider Two Elements

### ISSUE THREAD

**Issue by geoffthemedio** [freeorion/freeorion#1308]
The parsers for some ValueRef::Operation allow arbitrary numbers of operands in a min(...,...,...) operation, but the actual `ValueRef::Operation<double>::EvalImpl` and possibly some others only consider the first two operands.

https://github.com/freeorion/freeorion/blob/master/parse/ValueRefParserImpl.h#L194
https://github.com/freeorion/freeorion/blob/master/universe/ValueRef.cpp#L2575

**Comment by adrianbroher** [comment]
@geoffthemedio are you working on this?  If not I would like to take it.

**Comment by geoffthemedio** [comment]
no, I am not
