### ISSUE TITLE
Backspace deletes 2 symbols per press down.

### ISSUE THREAD

**Issue by o01eg** [freeorion/freeorion#1315]
### Environment

* **FreeOrion Version**:
* **Operating System**: Gentoo Linux AMD64
* **Graphic card used**: NVIDIA GeForce 750 Ti
* **Fetched as** 
  * Compiled from source

### Description
When I edit text and press BackSpace key two symbols are deleted.

### Expected Result
Delete one symbol on press BackSpace.

### Steps to reproduce
* Choose any GG::Edit widget.
* Enter some text.
* Press BackSpace key.

**Comment by geoffthemedio** [comment]
Don't see the issue on Windows in the pedia or player name edit boxes.

**Comment by o01eg** [comment]
I could suppose there is a difference in SDL input subsystem.

**Comment by Vezzra** [comment]
Can't reproduce neither on OSX nor my Linux system. Looks like that's a bug specific to your distro.

Can anyone reproduce this on their system?

**Comment by MatGB** [comment]
Working fine on my Kubuntu 16.04 as well.

**Comment by adrianbroher** [comment]
@o01eg What `symbol` do you refer to?  Please state an exact unicode code point.

**Comment by o01eg** [comment]
@adrianbroher I mean latin symbol.

It caused by `XMODIFIERS="@im=ibus"`. I get two SDL_KEYDOWN event when it enabled. Looks like libsdl2 bug.
