### ISSUE TITLE
Cancel button in multiplayer lobby window doesn't disconnect from server.

### ISSUE THREAD

**Issue by o01eg** [freeorion/freeorion#1316]
### Environment

* **FreeOrion Version**:
* **Operating System**: Gentoo Linux AMD64
* **Graphic card used**: NVIDIA GeForce 750 Ti
* **Fetched as** 
  * Compiled from source

### Description
When the player press Cancel in multiplayer lobby he left in the players list until he close client. Also it blocks "Multiplayer" button.

### Expected Result
Disconnect from the server when the player leaves multiplayer lobby window.

### Steps to reproduce
* Start game as a host.
* Start another client.
* Join it to the server.
* Press Cancel.

**Comment by adrianbroher** [comment]
I tested various connect/disconnect combinations and the non-host client now properly disconnects and reconnects.
