### ISSUE TITLE
Cpp API tag filter requires doxygen v1.8.12

### ISSUE THREAD

**Issue by dbenage-cx** [freeorion/freeorion#1319]
Travis is currently running doxygen v1.8.11 and not correctly parsing the arguments in `FILTER_PATTERNS` (doc/DoxyFile.in).

This was apparently fixed for doxygen v1.8.12 https://bugzilla.gnome.org/show_bug.cgi?id=504305

Locally running version 1.8.13, I do not have any errors for:
 `sh: 1: /usr/bin/python2.7 /src/doc/tag_filter.py: not found`

(milestone purposefully absent, does not affect build or typical user)

**Comment by adrianbroher** [comment]
Ubuntu 16.04 only has doxygen 1.8.11 in repositories.  I need to check if there is an updated package in some PPA available or if I need to build it myself.  That's a lot of effort for some issue, even if it renders the online tag documentation useless.

> Locally running version 1.8.13, I do not have any errors for:
> sh: 1: /usr/bin/python2.7 /src/doc/tag_filter.py: not found

Is this another local error or how is this related to this issue?

**Comment by dbenage-cx** [comment]
This is the immediate error caused by `FILTER_PATTERNS` not being resolved correctly.
It repeats at few times in the Travis build log.

I am certain there are other alternatives to achieving this documentation if updating is problematic.

**Comment by adrianbroher** [comment]
So far I haven't found any premade backport or ppa containing doxygen 1.8.12 or later for ubuntu 16.04.  Seems like I need to create a custom backport for this if we need this feature.

**Comment by adrianbroher** [comment]
@dbenage-cx 

> I am certain there are other alternatives to achieving this documentation if updating is problematic.

Is there anything specific you had in mind for this?

**Comment by dbenage-cx** [comment]
First thought is to use a `.dox.in` source and parse tags via script (prior to executing doxygen).
Will mull it over today and may start looking into it tonight.

**Comment by adrianbroher** [comment]
That's actually a decent idea.  The current solution creates a lot of [empty namespaces][1] and [empty file references][2] from the parsed python files.  So collecting the documentation beforehand and generating a .dox file would be ideal.

[1]: http://freeorion.github.io/cppapi/master/namespaceAIstate.html
[2]: http://freeorion.github.io/cppapi/master/starnames_8py.html

**Comment by Vezzra** [comment]
@adrianbroher:

Why "status:follow up"?

Why assigning this to a milestone? This issue isn't really release related/relevant...
