### ISSUE TITLE
Implement dynamic galaxy

### ISSUE THREAD

**Issue by afwbkbc** [freeorion/freeorion#1322]
Stars should move relative to each other, same as in real life. Lanes should appear and disappear (ships already on lane will reach their destination but new ones can't be sent aftet that) based on how far stars are from each other and whether there's something between them blocking passage. Some stars will move slowly, some so faster than ship's speed over lane. But trajectories must obey laws of physics and be predictable to players. Also in some rare cases stars can collide with each other, destroying everything on them and then either merge into larger star or dissipate as large cloud of gas in all direction, new stars can be formed from it later. Also cool objects like quasars would be cool - a quasar can be implemented as huge star that emit ray of plasma in direction its turned on (it may rotate), which will damage or destroy stars in its path. There's definetely needs to be a quasar in center of galaxy. Or maybe a super-massive black hole that destroys in everything that comes to it by lanes or stars that happen to fly too near.

**Comment by l29ah** [comment]
You should provide us a pull request.

**Comment by Vezzra** [comment]
Similar ideas have already been suggested, and maybe something like this (probably in a less extreme form) might be considered at some point. Although I don't expect that to be in the near future (lot of other, more important things to deal with before).

Anyway, such concepts require a lot of design discussion first, and therefore a github issue isn't really the proper means to present an idea like that. Please head over to [our forums](http://freeorion.org/forum/) and open a thread in the [Other Game Design subforum](http://freeorion.org/forum/viewforum.php?f=6) to discuss your idea there.

Closing this as invalid.
