### ISSUE TITLE
Implement titanic creatures

### ISSUE THREAD

**Issue by afwbkbc** [freeorion/freeorion#1323]
Basically a creature so big that gravity shaped it into geoid. Some kind of living planet. Feeds on energy from stars, but can also feed from other planets and asteroids, gradually reducing their size and then eliminating. Once enough energy is accumulated, can travel to other stars to eat. When no energy is available (i.e. some shitty star without planets) - it's "sleeping", but players may send stuff to it (i.e. planets) intentionally to feed and wake. Upon feeding, creature will grow larger, gaining more HP, attack power and speed of movement (maybe not) and speed of feeding, but will need more energy so may go into sleep more often. Generally it will become more agressive because of increasing hunger. When two of such creatures meet, larger one typically tries to feed from smaller one, while smaller will try to fly away if it has enough energy. Occasionally such creatures may reproduce by leaving some shards of itself, so small that are out of their interest or ability to notice. These shards can slowly grow on energy of nearby star, in time gaining spherical form and ability to move and going to search for food to other stars. Creatures are immune to normal weapons but may be damaged by some planet bombardment tools. They will try to fight back, but have very low chance to hit. But if they do hit, ship is destroyed instantly. Planetary bombardment is effective only against younger creatures (larger ones will regenerate hp too fast), so specific branch will exist in tech tree to invent really powerful countermeasures. Unless killed, creature will grow indefinetely, in the end becoming a living black hole that is imposdible to kill with anything. It will also gain ability to devour stars. The only salvation will be to run away and take stars along.

**Comment by geoffthemedio** [comment]
This sort of rather vague suggestion is more suitable in the other game design forum.

http://www.freeorion.org/forum/viewforum.php?f=6

**Comment by Vezzra** [comment]
@afwbkbc, you've repeatedly opened issues for ideas/suggestions like this in the past. Each time we've patiently explained to you that our github issue tracker isn't meant to be used for this and asked you to head over to our forums to present and discuss your ideas and thoughts there.

You never did that, and also never made any reply to our suggestions. May I ask why you ignore the feedback we have been giving you, and continue to open issues like the ones we closed already?

If you want to be taken seriously, you really need to change the way you communicate with us.
