### ISSUE TITLE
PlanetPanel Doesn't Resize When Expanded BuildingPanel Resizes

### ISSUE THREAD

**Issue by geoffthemedio** [freeorion/freeorion#1326]
Start game, open production screen. Enqueue multiple super tester takeovers. The buidlings panel fills up but doesn't seem to resize to show the extras. Collapse and re-expand it. remove some of the takeovers until the last row is empty. The buildings panel does resize, but the containing planet panel seems not to. Collapse and re-expand the buildings panel again, and the planet panel shrinks to fit.

![planet_panels](https://cloud.githubusercontent.com/assets/11386908/23040562/12e0bc54-f492-11e6-9a8e-591249779d96.png)

**Comment by geoffthemedio** [comment]
possibly related to @LGM-Doyle prerender / layout changes?

**Comment by LGM-Doyle** [comment]
This is fixed by https://github.com/freeorion/freeorion/commit/82156880ee0ed3f52ace1855cbbed4e6eb13e004.

**Comment by Vezzra** [comment]
@geoffthemedio, @LGM-Doyle: so can we close this issue as resolved?

**Comment by LGM-Doyle** [comment]
It works for me, but I did not report the bug.
