### ISSUE TITLE
Credits Overlay Doesn't Resize With Game Window

### ISSUE THREAD

**Issue by geoffthemedio** [freeorion/freeorion#1345]
Start game, click credits, resize window (larger). Note that the credits overlay doesn't resize with the game window, and that clicking outside the shadowed credits area produces no response. It should resize.
![credits](https://cloud.githubusercontent.com/assets/11386908/23106152/600edcdc-f6e9-11e6-8dad-3d883456ebaa.png)

**Comment by Vezzra** [comment]
Fixed by #1399.
