### ISSUE TITLE
FPS block is too similar to Turn block

### ISSUE THREAD

**Issue by afwbkbc** [freeorion/freeorion#1348]
Right now FPS block has same font, color and size as "Turn". If Show FPS is turned off and turn is 178-something ( or 45-something for low-end systems ) player can accidentally click on "Turn" thinking it's FPS button (that will show more info on click).
Please make them visually different.

**Comment by geoffthemedio** [comment]
Do you have suggestions as to how to make them more distinct?

**Comment by afwbkbc** [comment]
@geoffthemedio display FPS in bright lime color over space area to the right, it's common to FPS monitoring tools

**Comment by Dilvish-fo** [comment]
@afwbkbc could you maybe post a screenshot of how these currently look on your system?  On mine they already seem very distinct-- the turn button has an outline around it and is separated from the FPS block by the manual/automatic turn advancement button.  And the font size seems a bit different also.  Or perhaps there has already been an adjustment made that is simply not noted here?

**Comment by Dilvish-fo** [comment]
I'm inclined to close this as either invalid or works-for-me

**Comment by Vezzra** [comment]
I also don't understand what the FPS *button* is supposed to be. On OSX, I don't get a *button*, just a text, which can't be clicked anyway.

Closing this as invalid sounds reasonable.
