### ISSUE TITLE
No way to turn off music while in game lobby

### ISSUE THREAD

**Issue by afwbkbc** [freeorion/freeorion#1349]
Sometimes I have to connect and wait for others. Sometimes it can take a while. Often I want to do something else (i.e. watch porn) and freeorion music is always playing in background because I can't access menu without leaving game lobby screen. I'm scared to leave this screen because it may crash freeorion for other players and they won't want to play with me anymore.
There must be a way to access main menu from game lobby.

**Comment by adrianbroher** [comment]
I can reproduce this.  Maybe we should suspend the sound system as soon as the game looses focus and resume it when the game gains focus.

**Comment by afwbkbc** [comment]
@adrianbroher please don't, or it won't be possible to watch porn while waiting for others to end turn anymore.

**Comment by afwbkbc** [comment]
But disabling music (not sounds) will do.

**Comment by geoffthemedio** [comment]
just turn off game music before going into the lobby if you don't like it

**Comment by adrianbroher** [comment]
@geoffthemedio Please curb the troll.

https://help.github.com/articles/blocking-a-user-from-your-organization/

**Comment by Vezzra** [comment]
Still, the idea to turn off the music when the app looses focus and to resume when it gains the focus isn't completely unreasonable.

But of course that is very low priority. And given the issues @afwbkbc seems to have with our music, they probably should just turn it off, case closed.
