### ISSUE TITLE
Music is too slow and boring

### ISSUE THREAD

**Issue by afwbkbc** [freeorion/freeorion#1359]
Music is so slow and sedating that you have to turn it off ASAP to avoid falling into sleep while playing. I once actually fell asleep while waiting in game lobby because I couldn't turn music off and was too lazy to remove headphones.
Add some better music plz. I.e. NASA Voyager Space sounds will be much better theme for freeorion. Or maybe some dynamically generated tune like in Sid Meier's Alpha Centauri. Or some zerg theme from scbw. Long turns are already sedating enough without this tranquilizing music addition.

**Comment by Vezzra** [comment]
Honestly, music in particular is so much a matter of personal taste, that I don't see much sense in a request like this. E.g. for me even that serene piece is too distracting, so I turn off music by default. So whatever we set as default, there will be a lot of people who won't like it.

Anyway, you can change the file used for background music to anything you want in the "Audio" tab og the options dialog. Or turn off music. Whatever floats you boat...

**Comment by afwbkbc** [comment]
Still, default must be selected to be consistent with game's atmosphere. Why not NASA Voyager Space Sounds?

**Comment by Vezzra** [comment]
Because that's just *your* personal preference. Others might prefer the current piece. Still others might prefer neither, but something else... it's pointless to try to select a piece that is considered "consistent with the games atmosphere" by everyone, because everyone has their own ideas about that.

**Comment by geoffthemedio** [comment]
If you don't like the music, turn it off or submit something available under the CC-BY-SA to add to or replace it.
