### ISSUE TITLE
FO sounds continues playing even when game lost focus

### ISSUE THREAD

**Issue by adrianbroher** [freeorion/freeorion#1361]
### Environment
* **FreeOrion Version**: master
* **Operating System**: any
* **Graphic card used**: -
* **Fetched as**
  * Compiled from source

### Description
The current implementation of the sound system continues playing the background music, even when the game application lost its focus.  

### Expected Result
When selecting another application FreeOrion should suspend its audio output until it regains the application focus.

### Steps to reproduce
* Start FreeOrion in windowed mode.
* Focus OS Desktop or another Application
* FreeOrion continues playing background music, despite not being in focus.

**Comment by Voker57** [comment]
This should be disableable. New turn sounds are extremely useful, for instance, and I would like to hear them when freeorion is not focused.

**Comment by TheSilentOne1** [comment]
The new turn sound is not disabled when the application loses focus, just the music.
