### ISSUE TITLE
Load File Dialog Lacks Scrollbars Before Being Resized

### ISSUE THREAD

**Issue by geoffthemedio** [freeorion/freeorion#1365]
Start game, navigate to a directory with 10 or so save files. If the file select dialog is sufficiently small, it will lack a scrollbar, even though not all the files fit in the visible area.
![load_scrollbar](https://cloud.githubusercontent.com/assets/11386908/23331116/4ddc76bc-fb5f-11e6-8170-90cb64929a6f.png)

**Comment by LGM-Doyle** [comment]
@geoffthemedio I was unable to duplicate this.

I tried with my own config file and the default config.
I tried with 4, 5, 6, and 8 save games files.
I tried in the regular `save` folder and a different `save-other`folder.

**Comment by geoffthemedio** [comment]
Doesn't happen for me now either. Perhaps was fixed by https://github.com/freeorion/freeorion/pull/1356/files
