### ISSUE TITLE
Same game settings, different player starting locations depending on platform

### ISSUE THREAD

**Issue by Vezzra** [freeorion/freeorion#1369]
### Environment

* **FreeOrion Version**: 4644c927ccf8a02f36e59326832d7cfc31e31595
* **Operating System**: Windows, OSX, Linux
* **Fetched as**
  * Compiled from source

### Description

When starting a default quickstart game, assignment of home systems to empires differs depending on platform. I've tested this on all three platforms: Windows (XP), OSX (10.10) and Linux (Kubuntu 16.04). For some strange reason I can't insert them here, so I opened a thread on the forum where I posted the screenshots:

http://www.freeorion.org/forum/viewtopic.php?f=28&t=10434

### Expected Result

The map as generated by the universe generation scripts should be identical across all platforms when using identical game settings.

### Steps to reproduce

Just start a default quickstart game on different platforms and compare the results.

**Comment by Vezzra** [comment]
There are probably other differences too, but the different starting positions are of course the most obvious. Apparently there are also slight deviations in the placement of natives, compare e.g. the Caps (in the center north) and Lilac (in the southwest) systems.

It would be good if others could compare my screenshots to what they get when they start a default quickstart game on their systems.

**Comment by adrianbroher** [comment]
Is this a new behaviour or did you want to document this as an issue?

**Comment by Vezzra** [comment]
New behaviour. (Although, to be precise, it has already been present for a few weeks, but I constantly forgot to open an issue for it.)

We had the problem before, that universe generation did not generate the same maps across all platforms given the same game settings. We fixed it, but apparently it's (partly) back.

IIRC not all functions provided by the `random` module of the Python standard library deliver platform independent results. So I guess that's the culprit here. Most likely got introduced by the improved home system selection implementation we merged recently.

We really need to do something about these RNG issues. Probably no way around providing our own implementation of a suitable PRNG algorithm.

**Comment by geoffthemedio** [comment]
Aren't there already lines in the logs that output a series of pseudo-random numbers to test whether the results are the same on all platforms? I thought these results were found to be consistent? Point being, is this really an issue with the PRNG, and not other non-PRNG timing-related inconsistencies, such as the order in which AI players join and are assigned player IDs and empire IDs?

**Comment by Vezzra** [comment]
> Aren't there already lines in the logs that output a series of pseudo-random numbers to test whether the results are the same on all platforms? I thought these results were found to be consistent?

Yes, for the functions of the `random` module we checked that way. But I *think* I've stumbled on a function in that module that did *not* yield platform independent result, and replaced the piece of code which used that function with an implementation that used one of the those other functions. But it's a very vague memory.

And I've not been able to reproduce this. Ran a couple of tests with the functions provided by the `random` module on all platforms, and all yielded platform independent results.

> Point being, is this really an issue with the PRNG, and not other non-PRNG timing-related inconsistencies, such as the order in which AI players join and are assigned player IDs and empire IDs?

That should only change which of the AI processes gets assigned to which player/empire, but the empire themselves should still get the same starting positions. Even if the AI process to player/empire assignment would change which AI empire gets which starting position, the human player in a default quickstart game is *always* player 1. Therefore, the human player should end up with the same home system across all platforms, even if that weren't true for the AI players. But that is not the case, starting a default quickstart game will give the human player a different starting position on each platform.

That leaves only the PRNG as the cause for these differences, I don't know what else could possibly produce different results on different platforms... I'm completely clueless what's going on here.

**Comment by geoffthemedio** [comment]
It seems unlikely that it's a PRNG issue if the only thing that's changing, or at least the first thing that's different, is which player gets which empire, which shouldn't even be PRNG-related result.

Are you sure that player ID (should equal empire ID for a new SP game) determines which starting location an empire/player will get? There are numerous places where C++ code iterates though the connected players in the order of the shared pointers to the connections, not by player ID. I'm not sure where players/empires are assigned start locations, though.

**Comment by dbenage-cx** [comment]
> where players/empires are assigned start locations

In [UniverseGenerator.cpp:916](https://github.com/freeorion/freeorion/blob/master/universe/UniverseGenerator.cpp#L916) (roughly via [default/python/empires.py:475](https://github.com/freeorion/freeorion/blob/master/default/python/universe_generation/empires.py#L475))
Different sorting of homeworlds container compared to empires?


[freeoriond_default_quickstart.log.txt](https://github.com/freeorion/freeorion/files/817353/freeoriond_default_quickstart.log.txt)

**Comment by Vezzra** [comment]
> It seems unlikely that it's a PRNG issue if the only thing that's changing, or at least the first thing that's different, is which player gets which empire, which shouldn't even be PRNG-related result.

Which *player* gets which *empire* isn't the issue. The problem is which *player/empire* gets which *home system*. That assignment has always produced platform independent results (after we fixed the issues with the RNG that is), and stopped working (for whatever reason).

> Are you sure that player ID (should equal empire ID for a new SP game) determines which starting location an empire/player will get?

I don't know about player ID, the relevant factor here is the order of the player setup data list which gets passed into the `create_universe` function (if that list is ordered by player ID, then player ID determines which home system an empire/player will get).

> I'm not sure where players/empires are assigned start locations, though.

[`universe_generator.py`, line 111-115](https://github.com/freeorion/freeorion/blob/647678b26f341e2797644fb65c45dfc76e880d42/default/python/universe_generation/universe_generator.py#L111):
```
    # set up empires for each player
    seed_rng(seed_pool.pop())
    for empire, psd, home_system in zip(psd_map.keys(), psd_map.values(), home_systems):
        if not setup_empire(empire, psd.empire_name, home_system, psd.starting_species, psd.player_name):
            report_error("Python create_universe: couldn't set up empire for player %s" % psd.player_name)
```
In line 113 (the `for` statement), the entries in the `psd_map` dict (which is the passed in player setup data list) are correlated to the entries in the `home_systems` list. Which basically means, one of these lists obviously is sorted differently depending on platform, otherwise we wouldn't get platform dependent assignments of home systems to players/empires.

As platform independent results of this assignment has worked before, I assume the order of the player setup data list is platform independent. Unless there have been changes to the part of the code that compiles this list?

That only leaves the home systems list, the compilation of which has undergone a major revision recently. A quick glance at the relevant code seems to indicate that the home systems list gets ordered by a "merit" value assigned to each system, before it finally gets randomly shuffled.

Which actually *should* produce a platform independent end result, as `random.shuffle` produces system independent randomized results, and the sorting happening prior should be platform independent anyway (otherwise something would be seriously wrong).

No idea what's going on here... 😕

**Comment by Dilvish-fo** [comment]
> As platform independent results of this assignment has worked before, I assume the order of the player setup data list is platform independent.

I don't think so.  PythonServer::CreateUniverse moves the player setup data from a c++ map into a boost::python::dict, which I believe uses an actual python dict as its base object, and the ordering of python dictionary keys is platform dependent (and commonly noted as something to not be relied upon).  

Since the homeworlds are already shuffled in what should be a platform independent way, I think we should simply sort the player data before assigning the homeworlds, perhaps simply making line 113 be

```for (empire, psd), home_system in zip(sorted(psd_map.items()), home_systems):```

could someone set up to compare across platforms give that change a try?

**Comment by Vezzra** [comment]
> I don't think so. PythonServer::CreateUniverse moves the player setup data from a c++ map into a boost::python::dict, which I believe uses an actual python dict as its base object, and the ordering of python dictionary keys is platform dependent (and commonly noted as something to not be relied upon).

Actually that's what I have been wondering too, but:

* Why has home system assignment worked before with platform independent results? The way player setup data is passed into `create_universe` hasn't changed since forever.
* Inspecting the logs clearly reveals that while AI player to empire assignment varies, the order of empires is platform independent, and the human player in a default quickstart game is always first in that dict.

Anyway, after some digging I found the culprit: it's the `SystemsWithinJumps` function in `ServerWrapper.cpp` which gets exposed to Python as `systems_within_jumps`. The order of the list of systems this function returns is not platform independent.

This causes deviations when the home system placement algorithm tries to add additional planets to the near vicinity of home systems which don't meet the relevant limits. The logs show that very clearly. From that point on the sequences of random numbers the RNG produces are of course no longer in sync across platforms, which cause the call to `random.shuffle` to randomize the order of the home systems list to produce different results - BANG.

@LGM-Doyle, you've migrated the `systems_within_jumps` function into the C++ backend, any idea why the order of the list this function compiles deviates across platforms? I've looked at the code, but can't see anything immediately obvious...

**Comment by Dilvish-fo** [comment]
@Vezzra Hmm, I also don't see why systems_within_jumps would itself be giving platform dependent results; in your testing of it did you make sure the input list to it was consistent?  

Something related to it that appears to me to cause platform dependency is that the HomeSystemFinder class, in its find_home_systems_for_min_jump_distance, uses a python set local_pool, and then makes random selections from that.  Like python dicts, the ordering of a python set is arbitrary and platform dependent, and so I think this introduces some platform dependence.  I think a solution for that would be to change line 160 of empires.py from

```member = random.choice(list(local_pool))```

to

```member = random.choice(sorted(local_pool))```

Perhaps see if that fixes things (along with the previous change I suggested, which I think is also necessary)...

**Comment by Vezzra** [comment]
> in your testing of it did you make sure the input list to it was consistent?

The input list only consists of the home system of which the "near vicinity" is going to be checked, so there can't be any inconsistencies here.

> Something related to it that appears to me to cause platform dependency is that the HomeSystemFinder class, in its find_home_systems_for_min_jump_distance, uses a python set local_pool, and then makes random selections from that.

That has been one of my guesses too, however, in that case the compiled home system list would already be different *before* it gets shuffled, but it isn't. That has been the baffling thing: Everything appeared to proceed the same independent of platform. The list of home systems right before it gets shuffled is exactly the same, same systems, same order. After the shuffle the order of the list is different on different platforms.

Nevertheless, to be sure of course I dumped the `local_pool` set to the log, and verified that it indeed is identical across different platforms.

Naturally I never suspected `systems_within_jumps`, which is why it took me quite long to narrow down the exact location where things go wrong. I finally noticed that the `for` loop starting at `empires.py` line 407, which adds a star and a planet to those home systems which didn't have one still produced the same results on all platforms, but the `for` loop after that (starting at line 430) which adds planets to the "near vicinity" of home systems where needed didn't. The results were different on different platforms.

Which meant that something there must cause this. Only then I checked the list returned by `systems_within_jumps` and lo and behold, the culprit has been busted.

To make sure I checked and sorted the list returned by that function before using it, which indeed solved the issues: the second `for` loop once again produced system independent results, so did shuffling the home system list. And running a default quickstart game gave me the same starting positions across different platforms.

So just sorting that list would fix this issue, but of course a solution that makes sure `systems_within_jumps` returns platform independent results is preferable, so I want to wait for @LGM-Doyle's input before proceeding.

That said, the suggestions you made above on sorting to player setup data dict and the `local_pool` set make sense. Although it seems that they actually *do* seem to have the same order independent of platform, we probably shouldn't rely on that.

However, I guess there are far more similar cases in the universe generation scripts (where we iterate over dicts or sets and use the RNG to do something in these loops), which should also be fixed in a similar manner.

Well, looks like @geoffthemedio has been right after all - this hasn't been an issue with the PRNG...

**Comment by LGM-Doyle** [comment]
@Vezzra, excellent bit of sleuthing.

The problem is that the `libstdc++` (`gcc`) and `libstdc++` (clang)` `unordered_set` have different ordering. It is to be expected when something has unordered in its name.  

I will work on a solution tomorrow.

Sorting the returned list as @Dilvish-fo suggested works and may be the best solution.  Now that the problem is known, we also know that the solution will not mysteriously break in future.  

The fast method I have for providing read-only access for python to `unorderd_set` and `unordered_map` preserves the unorderedness from which those data structures derive their speedy access properties.
