### ISSUE TITLE
[Play-testing] It's very too long to add multiple entries into build list

### ISSUE THREAD

**Issue by Chklang** [freeorion/freeorion#1372]
Hi

I like freeorion, but there is one thing that it's very horrible : If you have a big production (like 6K +), you will produce many fleets by turns. And if you wants to complete the list you must double-click, double-click, double-click, double-click, [...] with 1-2secs of pause between each because it's too long. I think that if you add an entry into builds options (right click, into https://github.com/freeorion/freeorion/blob/31ac8e722b6e5fd1de37c6430d9d0d338c6d4a7a/UI/BuildDesignatorWnd.cpp#L928 ) to show a popup "Add x sheeps into list" that would be very very [...] wonderfull!

A fan of the master of orion serie (but french so please to excuse my english :/ ) :)

**Comment by geoffthemedio** [comment]
Are you aware of the multiple and repeat production options? There are droplists on ship production queue items that let you pick how many times to repeat a production item, or how many of something to produce simultaneously, with a single box on the queue.

**Comment by Chklang** [comment]
Ho O_o

Thank you!!! I didn't know this feature!! So sorry for this ticket, and thanks for your reply :)

Freeorion is really impressive!!
