### ISSUE TITLE
Typo in bootstrap.command makes MacOSX SDK unusable

### ISSUE THREAD

**Issue by memem359** [freeorion/freeorion#1376]
I was running the bootstrap.command for the MacOSX SDK.

Part of the way through the script, it does this:
`echo Unzipping dependencies...`
`tar -xyf dep.tar.bz2 -C Xcode`

There is no "y" option for tar.
It fails to run, the script erases the dep.tar.bz2 file, and I was unable to compile the program in XCode because most of the software headers were missing (since the Xcode/dep folder was never made). It wasn't obvious that there was a fatal error from the bootstrap.

Wherever this script is being made, please fix the typo for the "tar" command.

**Comment by adrianbroher** [comment]
Invalid due to wrong repository. I will take care of it anyway.

**Comment by Vezzra** [comment]
@adrianbroher, to be sure I just ran a test, looks like the "y" option can be removed safely.

Any reason why you left the issue open after tagging it as invalid? Or just forgot to close it?

**Comment by memem359** [comment]
My system was using "GNU tar", which like the Linux version, does not have a "y" option and crashes to a halt if it sees it. When I reverted to the normal bsdTar, I was seeing the same thing that Vezzra expected.
