### ISSUE TITLE
System Name Misplaced

### ISSUE THREAD

**Issue by geoffthemedio** [freeorion/freeorion#1382]
I've only observed this after loading an MP game, and not SP. When the game loads, the map is shown without the sidepanel open. Clicking on a system... possibly only ones without populated planets in them, will open the sidepanel with the system name misplaced at the top right. Viewing another system or closing and reopening the sidepanel fixes it.

![deep_space_shifted](https://cloud.githubusercontent.com/assets/11386908/23591855/a08df982-01f7-11e7-9f4a-890011093121.png)

**Comment by dbenage-cx** [comment]
Can reproduce in SP:
*  Resize SidePanel
*  Close SidePanel
*  Resize Client
*  Select any system (populated or not)

**Comment by Vezzra** [comment]
On OSX I can reproduce this just by launching FO, starting a default quickstart game, and without doing anything else before directly go to the production screen.

If I select another system and then go to the production screen, the system names stays where it should. After that I can't reproduce the issue by going to the production screen regardless which system is selected, until I quit the program and restart it.
