### ISSUE TITLE
Add Tooltip for Focus Selection Dropdown

### ISSUE THREAD

**Issue by Morlic-fo** [freeorion/freeorion#1404]
### Environment
* **FreeOrion Version**: build 2017-03-14.853af0e
* **Operating System**: Windows 7
* **Graphic card used**: Nvidia GT520M
* **Fetched as** Weekly test build

### Description
When hovering over the (collapsed) dropdown to select a planetary focus in the sidepanel, a tooltip for the focus is displayed.
It would be nice to have the tooltip shown for each entry when the dropdown is expanded.

See screenshot for reference.

![dropdowntooltip](https://cloud.githubusercontent.com/assets/11706951/23972582/ac628164-09d2-11e7-8b92-e7338e4a4dac.png)

**Comment by LGM-Doyle** [comment]
Implemented by #1466
