### ISSUE TITLE
The --auto-quit option pauses but doesn't exit the application.

### ISSUE THREAD

**Issue by LGM-Doyle** [freeorion/freeorion#1405]
This issue arose in the review of PR [#1375 Improve app termination correctness.](https://github.com/freeorion/freeorion/pull/1375#issuecomment-286592239)

### Environment

* **FreeOrion Version**: master and [PR #1375 ](https://github.com/freeorion/freeorion/pull/1375/commits/f4447598c7983b98ec58a876c28129c1fe3e0c98)
* **Operating System**: Ubuntu

### Expected Result
The expected behavior of auto quit is to run some number of turns and then exit the application.  For example:
`./freeorion --auto-advance-n-turns 10 --auto-quit --load ~/.local/share/freeorion/save/test.sav`

should load `text.sav`, run 10 turns and then exit.

### Description of Problem
The buggy behavior as described in more detail [here](https://github.com/freeorion/freeorion/pull/1375#issuecomment-286922496), is that the application runs and then pauses, but does not exit.

**Comment by LGM-Doyle** [comment]
I forgot to mention that this works for me.  I do not have a non-working example of this issue to fix.

This command line ````./freeorion --auto-advance-n-turns 10 --auto-quit --quickstart```` also works correctly for me.

**Comment by geoffthemedio** [comment]
I get a save game in progress popup after 10 turns. Clicking to exit dismisses it, but doesn't exit. Clicking the top-right gives me the popup again. Clicking to exit again actually exits.

[logs.zip](https://github.com/freeorion/freeorion/files/1195190/logs.zip)

**Comment by LGM-Doyle** [comment]
Thanks for the logs.  I'll look into it.
