### ISSUE TITLE
ComplexVariable<T>::Description() Looks Weird

### ISSUE THREAD

**Issue by geoffthemedio** [freeorion/freeorion#1418]
https://github.com/freeorion/freeorion/blob/master/universe/ValueRef.h#L1317

This whole function looks weird / incomplete / broken. I could probably be implemented much better than whatever it's doing now.

**Comment by Dilvish-fo** [comment]
Hmm, looks like I was responsible for it, I think my focus was on getting the description for JumpsBetween working, and the rest was some work-in-progress that slipped in with it.  If you don't already have something in mind for the cleanup I should probably take responsibility for cleaning up my own mess.

**Comment by geoffthemedio** [comment]
I think this is resolved...

Edit: Looking again, the function hasn't changed in several years, so probably not...

**Comment by adrianbroher** [comment]
@geoffthemedio if you're talking about https://github.com/freeorion/freeorion/blob/master/universe/ValueRefs.h#L1288-L1300

I don't immediatetly see what is wrong with that function. Could you please clarify?

**Comment by geoffthemedio** [comment]
It appears to have been completely rewritten since this bug was submitted, eg. compared with https://github.com/freeorion/freeorion/blob/8860996bee32030d669c5e2b8a32a85b062620c9/universe/ValueRef.h#L1310-L1337
