### ISSUE TITLE
Human Client Access Violation Upon Fatal Error From Server

### ISSUE THREAD

**Issue by geoffthemedio** [freeorion/freeorion#1422]
Was playing around with the save format, and made a save that the UI accepts, but which fails to load properly on the server. When the client receives an error message from the server about the fatal error, there is an access violation in the client, at least in Windows. The problem happens around here:

https://github.com/freeorion/freeorion/blob/master/client/human/HumanClientFSM.cpp#L550

The comment immediately above this code suggests the possible cause of the problem.

I'm not sure how the code within `Client().ResetToIntro();`, which itself posts some events and does some transitions to kill the sever and similar things, will interact with the explicit transition here, but at least the explicit transition probably needs to happen before the message box.

**Comment by geoffthemedio** [comment]
Reordering things to:
````
    auto retval = discard_event();
    if (fatal) {
        retval = transit<IntroMenu>();
        Client().ResetToIntro();
        ClientUI::MessageBox(UserString(problem), true);
    } else {
        ClientUI::MessageBox(UserString(problem), false);
    }
    return retval;
````
Seems to stop the crash / access violation, but I am left with some in-game windows over top of the intro screen...

![leftovers](https://cloud.githubusercontent.com/assets/11386908/24083987/09e7dcb4-0ce2-11e7-8b34-05d61815ba0c.png)

**Comment by geoffthemedio** [comment]
Attempted fix: https://github.com/freeorion/freeorion/commit/60e92bb1aa83e3eda3b8ffab8a5a1ad425f81cdc

not sure it's correct / completely fixed, though.

**Comment by LGM-Doyle** [comment]
I think a better fix is to remove line 552,  `return transit<IntroMenu>();`.  Line 548 already discards the event, which is the null transition, and creates the correct `retval`.  Then `ResetToIntro()` transits away to the `StartQuittingGame`.

line 969 `return transit<IntroMenu>();` is correct as is, since a) `ResetClientData()` does not affect the FSM and b) there is no blocking modal element so it would not matter in any case.

**Comment by geoffthemedio** [comment]
Revised fix: https://github.com/freeorion/freeorion/commit/a0f73eaa6268736649bb38983498f5859bcd8e37

**Comment by Vezzra** [comment]
On OSX I have the same issue now: when returning to the intro screen the "Messages" and "Empires" windows are left open, exactly as shown in the screenshot above. Tested with 60b8488aa44d68d706161a2d10b8b39ecdf817c0.
