### ISSUE TITLE
Provide in-game explanation for info in Homeworlds pedia article

### ISSUE THREAD

**Issue by dbenage-cx** [freeorion/freeorion#1430]
**EDIT** Per discussion below: Provide some in-game explanation for the information contained in the homeworld pedia article.

### ~Description~

~The pedia article listing Homeworlds displays more information than the empire should actually know.~

~On first turn, with no view of any other populated planets:~
![screenshot_20170322_023804](https://cloud.githubusercontent.com/assets/17205519/24186934/aa0d0b98-0ea8-11e7-9faf-4e4a95c5ce09.png)

### ~Expected Result~
~Any species should list as unknown for location and count of homeworlds, until the empire has some competing info.~

**Comment by geoffthemedio** [comment]
Presently the empire can / does actually know that species have homeworld(s), but not anything about those homeworlds other than their object ID. The pedia reflects this.

**Comment by o01eg** [comment]
I suppose the server should not send that data to client.

**Comment by geoffthemedio** [comment]
That's a game mechanics change, and would require some complicated rules / logic about when a player gets that information. For this and a variety of other things, the players just get to know information if even if they "shouldn't". Assume it's from rumours?

**Comment by dbenage-cx** [comment]
> Assume it's from rumours?

Fair enough, migrate this issue to "provide fluff explanation" or close as invalid?

**Comment by MatGB** [comment]
Either is fine: we do need to continue to improve justifications in game as well as explanations. Worth noting 2 points: all the info in this Pedia entry is also in each Species entry, putting it in one place simply made it more accessible. Also, if it's decided to remove it/turn it off for most players I'd want the ability to see it all anyway for test purposes, if I want to see what a new Native concept does within a test-for-balance game, I need to know that species is there *without* doing the Super Tester route, I most recently used it for this on the Lembala Lem, they were a pain to test even when I knew they were out there, somewhere.

But I like the rumours plan, there are traders, trade posts, etc in all the best space opera.
