### ISSUE TITLE
Save Dialog Columns Option Broken?

### ISSUE THREAD

**Issue by geoffthemedio** [freeorion/freeorion#1435]
On Windows, after starting the program and opening the load file dialog, closing it, quitting the game, and repeating that a few times, I get a series of errors in the log file similar to:
````2017-03-24 14:30:29.996242 [error] Client : SaveFileDialog.cpp:595 : SaveFileListBox::FilterColumns: Column not found: ,````

and an odd-looking related entry in config.xml:
````<columns>time,,,,,,,,turn,,,,,,,,player,,,,,,,,empire,,,,,,,,file</columns>````

**Comment by Vezzra** [comment]
Should this really be considered release blocking...?

**Comment by dbenage-cx** [comment]
Did not notice this had an open issue, should be fixed in 7bf38a3

**Comment by memem359** [comment]
I made a note in dbenage-cx's other open issue, but I can confirm that it fixed the extra commas in my config.xml. (No more error messages when loading saved games, and any previous config.xml file is cleaned up after the game is started/quitted.)

**Comment by dbenage-cx** [comment]
@memem359 TY for confirming.  If you still wish to make further improvements to these functions, I am sure a PR is more than welcome (realize it will probably be held until after release).
