### ISSUE TITLE
Lobby unresponsive after two AIs assigned to same faction

### ISSUE THREAD

**Issue by Voker57** [freeorion/freeorion#1437]
Version: teamsmac-10.3 based on 60b8488aa44d68d7061

Reproduce: load a game with  multiple fractions, assign two AIs to same one. Can't click any menus now, hearing constant dropdown choice sound.

**Comment by dbenage-cx** [comment]
@Voker57 Might be relevant: Did this issue occur well before I joined lobby, or around the same time?

**Comment by o01eg** [comment]
@dbenage-cx It doesn't happen in vanilla version but only with https://github.com/freeorion/freeorion/pull/1392 so it is for `post v0.4.7` milestone.

**Comment by o01eg** [comment]
Looks like host and server infinitely send LobbyUpdate message to each other.

**Comment by o01eg** [comment]
@Voker57 > assign two AIs to same one
I get rejection when trying to assign same empire on two AIs. I reproduced it when add AI but only once.

**Comment by Vezzra** [comment]
> It doesn't happen in vanilla version but only with #1392 so it is for post v0.4.7 milestone.

Which indicates that this *might* be an issue introduced by that PR, so I agree,  this should be assigned to "post 0.4.7".

EDIT: Ah, @dbenage-cx already made the reassignment, thanks!

**Comment by Vezzra** [comment]
@Voker57, does this issue still happen with recent test builds?

**Comment by Voker57** [comment]
@Vezzra appears to be fine now, ai switches back to non-taken/null faction

**Comment by Vezzra** [comment]
Good, thanks!
