### ISSUE TITLE
Closing Window on Intro Screen Gives Save is in Progress Warning.

### ISSUE THREAD

**Issue by geoffthemedio** [freeorion/freeorion#1440]
Start program, click X at top right (in Windows). Get popup about save in progress. Repeatedly pressing the X does nothing.

Interestingly, dragging the popup notification reveals a second hidden behind it.
![in_progress](https://cloud.githubusercontent.com/assets/11386908/24330603/4151cf8a-1222-11e7-8b83-f3e8a649f0ea.png)

**Comment by Vezzra** [comment]
I can reproduce the exact same behaviour on my Linux system (Kubuntu 16.04), but not on OSX.

**Comment by dbenage-cx** [comment]
Can not reproduce, possibly just not initialized?
```
diff --git a/client/human/HumanClientApp.cpp b/client/human/HumanClientApp.cpp
index 913af6d..1ba9af1 100644
--- a/client/human/HumanClientApp.cpp
+++ b/client/human/HumanClientApp.cpp
@@ -194,7 +194,8 @@ HumanClientApp::HumanClientApp(int width, int height, bool calculate_fps, const
     m_game_started(false),
     m_connected(false),
     m_auto_turns(0),
-    m_have_window_focus(true)
+    m_have_window_focus(true),
+    m_save_game_in_progress(false)
 {
 #ifdef ENABLE_CRASH_BACKTRACE
     signal(SIGSEGV, SigHandler);
```

**Comment by geoffthemedio** [comment]
`m_save_game_in_progress(false)` appears to fix it

**Comment by LGM-Doyle** [comment]
@dbenage-cx thanks for the save.
