### ISSUE TITLE
Compile changelog for 0.4.7

### ISSUE THREAD

**Issue by Vezzra** [freeorion/freeorion#1441]

**Comment by geoffthemedio** [comment]
Sub issue: What are key changes in this release? Suggestions and comments are requested.

**Comment by geoffthemedio** [comment]
https://github.com/freeorion/freeorion/commit/5329c7a468699178d34aa8add5a049a88a330e0d

**Comment by LGM-Doyle** [comment]
@geoffthemedio thanks once again for doing the big task of compiling the change log.
