### ISSUE TITLE
Add user documentation on blockaded system effects.

### ISSUE THREAD

**Issue by dbenage-cx** [freeorion/freeorion#1454]
An article (or addition to existing articles) describing effects on supply and limits to ship movement when a system is blockaded would be helpful.

Issue #1237 has some discussion and links to previous discussions on the topic.

**Comment by geoffthemedio** [comment]
Has this been resolved?

https://github.com/freeorion/freeorion/blob/master/default/scripting/encyclopedia/game_concepts/SYSTEM_BLOCKADE.focs.txt
https://github.com/freeorion/freeorion/blob/master/default/stringtables/en.txt#L4802

**Comment by MatGB** [comment]
Yes, probably could do with a copyedit but so could most of the Pedia, ergo resolved by 1f7d9fe and 8d7f9df
