### ISSUE TITLE
problems with "A save game is in progress." popups

### ISSUE THREAD

**Issue by Dilvish-fo** [freeorion/freeorion#1465]
Earlier this eve, I apparently tried quitting too soon after saving the game, and got the "A save game is in progress popup."  Just waiting a bit for it didn't seem to clear it up, even after a couple minutes (only a small fraction of which should have been needed to finish the save) the popup was still there, and I wound up clicking the button to just exit without save.  (And the game indeed had not been saved).

Now, if I (1) open the setup window for a new single player game, but then just cancel out of it, or (2) open up the game and just try to quit it without doing anything (via the window bar X button), I still get the "A save game is in progress popup."  (slightly different versions of it for those two cases).  Starting up the game and then immediately closing it via the Main Menu exit button works fine though, with no popup.   I can't seem to do anything to fully clear this state so that I no longer get these popups -- if I start a  new game or load a game and then save it and give it a few seconds, then I can quit or exit that game without the popup.  But if I then restart FO and check either of the above two cases, they still are wrongly triggering the "A save game is in progress." popups.

I am on Ubuntu Linux, my FO version is d3ff2ad

**Comment by dbenage-cx** [comment]
@Dilvish-fo Do you have any lingering freeorion processes? e.g. `ps aux | grep -i freeorion`
Try clean build for recent(ish) commit?

Related: #1440

**Comment by Dilvish-fo** [comment]
> Try clean build

Yes, sorry, turns out I had gotten confused as to what master branch commit my executable corresponded to because I had forgotten to rebuild after having merged in some commits, but then poorly assumed my git records actually corresponded to my executable.  I'll be more careful about that in the future.  The problem is gone with the current build.

**Comment by Vezzra** [comment]
Um, if this is a "duplicate" (of #1440 I assume?), then it's not "resolved". It's just closed as a "duplicate".
