### ISSUE TITLE
Engine parts need balancing

### ISSUE THREAD

**Issue by MatGB** [freeorion/freeorion#1480]
Follow up to #1400 
### Description
Warships with large numbers of internal slots can be overpowering simply because of the speed they can achieve. This makes larger number of internal slots significantly more powerful per extra slot.

I propose we increase the speed boost per engine part as well as the cost, but make them non stacking so a design can only benefit from one part not all of them.

When this is done, the temporary changes in #1477 should be reverted and the reversion should be tested alongside the stacking group parts.

**Comment by afwbkbc** [comment]
No. This will make game more linear and boring.
Instead we need to invent more fun stuff to be placed into internal slots.
Also remove all limits for other parts and slots, i.e. let multiple Spinal Antimatter cannons be placed if ship has multiple core slots (no worries - this ship will cost much more that way so it will still be somewhat balanced).
The last thing we need to do is artificially limit creativity and make game more linear.
Let fast ships be. Their drawback will be in not using these slots for something more useful.
Also it would be common sense if fuel consumption depended on ship's speed (or at least amount and type of mounted engines). So ship with 10 engines would lose all its fuel in 1 or 2 turns, unless engines are accompanies with fuel tanks.

**Comment by Morlic-fo** [comment]
Wasn't this resolved by #1621 ?

**Comment by Vezzra** [comment]
Looks like it was, anyone any objections to closing this as resolved (and correcting the milestone accordingly)?

**Comment by Vezzra** [comment]
Fixed by #1621.
