### ISSUE TITLE
stealthed monster-carriers can result in buggy-looking combat reports

### ISSUE THREAD

**Issue by Dilvish-fo** [freeorion/freeorion#1483]
Presumably the following is from a stealthed medium krill moving into a system with one of my colonies. 
 The summary of forces is just my planet and zero neutral forces; nevertheless the zero neutral forces manage to launch fighters (which then do nothing)
![buggy_combat_report](https://cloud.githubusercontent.com/assets/10995939/24925304/a9620ed2-1eac-11e7-8076-a8ca39a4757b.png)

I am pretty sure that we had decided a long while back that armed monsters should not be stealthed, and I think that should apply to monster-carriers also.  So I would propose that we make that change (which I think is a correction really) and cherry pick it for 0.4.7

I also have a recollection that we recently discussed having fighter-launch cause enemies present to gain visibility the same as if they had been attacked by direct fire weapons, but I can't seem to locate that discussion now.  My recollection is that we talked about making it be some-chance-of-losing stealth and punted it for some later stealth re-work.  I would be pretty inclined myself to have the interim position be that launching fighters grants visibility just like a direct attack.

Also just a note about my labels here: I am categorizing the more specific issue as a bug regarding content scripting for armed monsters, and the suggestion about combat visibility in general as a game mechanic tweak.

**Comment by Vezzra** [comment]
> I also have a recollection that we recently discussed having fighter-launch cause enemies present to gain visibility the same as if they had been attacked by direct fire weapons, but I can't seem to locate that discussion now.

http://www.freeorion.org/forum/viewtopic.php?p=88085#p88085

I'd consider stealthy carriers being overpowered as a "known issue" for 0.4.7, and postpone a more thorough fix until after the release. I expect a major part of 0.4.8 being fixes and adjustments for the new fighter/carrier mechanic anyway.

The combat report does look a bit weird, but then, considering you were fighting an enemy that didn't break stealth, it's also somehow fitting. I mean, you don't know where the fighters came from, only that they have been there. So no estimates on the numbers of the mysterious thing(s) you couldn't see...

> I am pretty sure that we had decided a long while back that armed monsters should not be stealthed

We did? Can't remember right now... but that's probably my faulty memory. Anyway, we can't really prevent that, as monsters could get increased stealth e.g. from ion storms.

**Comment by Dilvish-fo** [comment]
> We did? Can't remember right now.

Well, I did manage to find a much older discussion that starts with [the same unsupported assertion from me of a recollected agreement](http://www.freeorion.org/forum/viewtopic.php?p=70101#p70101) :laughing: but we seem to have pretty much accepted the idea during the course of that discussion.  The exception made then was for snails, being immobile at known risk spots.  There was also some discussion of leaving in stealth for some very low damage monsters, although I think that wound up going by the wayside until fighters were added.

> Anyway, we can't really prevent that, as monsters could get increased stealth e.g. from ion storms.

Like the risk of snails being in asteroid belts, the presence of an ion storm gives visible warning that there might be a hidden enemy nearby (and I think it's been my experience that they will also generally block the monsters from attacking me, though perhaps I am mis-remembering that).  So I think the possibility of an ion storm temporarily masking an armed enemy of any type doesn't matter much regarding the issue of armed monsters having high base stealth.

Is there some reason that anyone really *wants* the medium and large krill to be stealthed?

**Comment by MatGB** [comment]
> Is there some reason that anyone really wants the medium and large krill to be stealthed?

Yes. I think it adds flavour to the game, they're incredibly low threat things that'd struggle to take out most scouts (deliberately) and they can't affect planets (deliberately) or blockade as they always move.

I/we want to redo the stealth/detection techs and numbers, and splitting up distance seen from detection strength is sort of in that plan, having a minor threat at stealth 15 is an encouragement for players to actually research stuff that humanity has had since the 1940s ;-)

I agreed that snowflakes should be destealthed because they're an actual real threat including bombardment weapons, but krill are annoying at best and they should be gated to be unable to form larger swarms until certain turns.

Re carriers: we've tested them extensively this pass and the ability to stealth them was in the original spec, we deliberately toned down a few of the stealth hulls just before making the release branch because those specific hulls could be a problem, the AI has upped the priority of detection techs and while they're powerful in some respects they're also very much glass cannons and a human player can overwhelm them relatively easily. I'm happy with the toning down we've done, I'm *very* happy that you can have stealth carriers, it helps make stealth a viable/interesting approach and I definitely don't think it needs adjusting further right now.

We're going to do a lot of stuff that involves stealth next cycle, with the stealthed supply stuff and imperial stockpile both contributing to stealth-as-a-strategy by design, and redoing the numbers for everything, adding refinements and improving the funness of hiding has to be part of that. 

Stealth carriers are glass cannons and can't take planets at all, I'm happy with them as is at the moment.

**Comment by Vezzra** [comment]
> we seem to have pretty much accepted the idea during the course of that discussion

I took a quick look at that old discussion (oh boy, I can barely remember it, I'm really getting old...), and the conclusion still seems reasonable. Higher stealth stats only for either immobile, or unarmed, or, at most, very weakly armed roaming monsters. No stealth for the more dangerous roaming monsters.

> So I think the possibility of an ion storm temporarily masking an armed enemy of any type doesn't matter much regarding the issue of armed monsters having high base stealth.

Agreed.

> Is there some reason that anyone really wants the medium and large krill to be stealthed?

No strong preference, but what @MatGB said sounds reasonable. Although IIRC at least the large krill swarms weren't that harmless, but maybe they got nerfed at some point? I have to admit, I almost never play with space monsters, so I don't know their stats.

But if even the large krill swarm is barely a threar even to very early game hulls, then I don't see a problem with them being a bit stealthy.

Regarding stealthy carriers, I'd say lets see how they play out with 0.4.7. Having that in a stable release will ensure it gets tested more thoroughly, and we can hope for more feedback. 😃

**Comment by Dilvish-fo** [comment]
>  they're incredibly low threat things that'd struggle to take out most scouts (deliberately)

I think that is quite an exaggeration.  Yesterday I had a fleet of 3 ships (starter frigate plus two scouts) run into a medium krill, and I lost both scouts and did practically nothing to the Krill, again with a combat report that would make little sense to anyone not very familiar with the game (the report now shows the monster ship name, but at the original time of the battle I didn't have Radar and so it just reported as fighters launched from Unkown):
![fleet_movement_trouble_b2](https://cloud.githubusercontent.com/assets/10995939/24972254/a664e768-1f6f-11e7-97ff-b43d60095cf2.png)

An even worse case, which would probably extremely vexing and confusing for someone not so familiar with FO, was when I was trying to tackle a high tech native planet with defenses, and it turned out there was a stealthed medium Krill that arrived on the same turn, so the Krill fighters soaked up most of my attacks and also did some damage, while the planet finished my ships off.   What had looked like it should be a guaranteed victory instead resulted in my fleet simply flashing to oblivion, with the combat report requiring a fair bit of extra knowledge to decipher.

The combat report summary only identified the neutral forces as having a single member, the planet, with the enemy fighters magically appearing from "Unknown", and there wasn't even a ghost fleet or scanlined enemy fleet showing on the MapWnd.  I think it would take a fair bit of experience for a player to even be able to realize that the issue stemmed from a stealthed monster fleet.

**Medium Krill can appear after turn 30** and I think that's too early to be effectively requiring a 100 RP tech especially if that requirement won't be at all clear to FO newcomers. 

If you are going to be doing a stealth rework soonish, then I would urge that we let stealthed medium+ Krill wait to be considered for then, and that we unstealth them for 0.4.7.

**Comment by Dilvish-fo** [comment]
Let me mention also, that I think that Dyson Forests and Floaters are a better way to urge newcomers towards Radar -- the Dyson Forest description should not just mention a 'seed', but actually have a link to the Floater and mention that the Floaters may be hard to detect, and then the Floater description should mention and link to what tech would be necessary for them to be visible (currently Radar).  Perhaps I'll try to squeeze in a quick PR for this Dyson Forest / Floater Pedia change regardless of what we do about Krill.

**Comment by Vezzra** [comment]
Hm... I have to admit, to me this thing looks like a border case (is that the correct word in English?). The medium krill swarm is not really dangerous, I mean, it can deal a max of 12 damage in a battle, which isn't *that* much. 

*However*, with those "krill fighters" now the space monster itself remains stealthed (and thus invulnerable to empires which can't detect them), while still being able to attack. It's a stealthed carrier (which is basically a *very* powerful thing), and as such definitely more than just an annoyance.

I don't think this to be a big issue, but still lean more towards Dilvish assessment in this case. The medium krill swarm is just this tiny bit too powerful for something that can appear at turn 30. So de-stealthing the krills (setting stealth of the medium and larger krill swarms to 5) as a stop-gap solution for 0.4.7 sounds reasonable to me.

I suggest to apply this stop-gap fix only to the release branch though. It's really just a fix for the release, no need to apply that to master.

@MatGB, are you ok with that? Then I'd apply that fix to the release branch before I produce RC1.

**Comment by MatGB** [comment]
Release only is fine, don't like it but can't win then all, right?

**Comment by Vezzra** [comment]
😉

**Comment by LGM-Doyle** [comment]
I have three suggestions for changes to the combat log to improve the clarity in these situations.

- If there are no initially detected enemies, then perhaps before `Round 1` there should be a line like:
````Terran Imperium attacked by hidden enemies````

- Perhaps `Unknown` could be changed to `Hidden ship` so that it reads
````Hidden ship launches 4 Fighter````

- The visibility of old combat reports should be persistent, so that when you scroll back through the combat reports ships that were hidden on turn 5 are still hidden on turn 200.  

Does anyone else have any other suggestions?

**Comment by Dilvish-fo** [comment]
@LGM-Doyle I think your first suggestion is great and sounds easy.  The second one sounds good also, but is probably not as simple.  

The last one would require some really significant changes I think, easily affecting other kinds of SitReps as well, and I think is just not really needed especially after suggestion 1.

**Comment by agrrr3** [comment]
Now carriers which launch fighters are decloaking, so this issue should be gone.
