### ISSUE TITLE
Add experience points and skills for ships

### ISSUE THREAD

**Issue by afwbkbc** [freeorion/freeorion#1484]
Ship should get XP when it destroys enemy ship in combat. XP points amount is larger if destroyed ship was stronger, or smaller is destroyed ship was weaker.
XP is accumulated until ship is destroyed.
Once ship gets enough XP, it gets to new level. Levels can be numeric (starting from 1) or name-based (i.e. Green, Skilled, Veteran, Commando, Elite, Godlike, ...).
Every new level adds additional skill or modifier to ship, chosen randomly. Higher levels have more powerful skills available. Skills got at lower levels remain and stack with skills got at higher levels later.
Examples:

Green : default skill level for newly built ships, no additional skills

Skilled : ship gets one of (randomly):
- Evasive I : +5% chance to dodge incoming attack
- Lethal I : damage of all weapons ( and fighters ) increased by 10%
- Hardy I : max structure of ship increased by 10%, current structure is also increased by 10% ( so 10/20 HP damaged ship will become 11/22 HP)

Veteran : one of (randomly):
- Evasive II : +15% chance to dodge incoming attack (up to 20% if stacked with Evasive I)
- Lethal II : damage of all weapons increased by 20% ( up to 30% total if stacked with Lethal I ), flak cannons get 2 additional shots ( up to 5 )
- Hardy II : max and current structure of ship increased by additional 20% ( up to 30% total )
- Survival I : every turn ship regenerates additional 10% of max structure
- Twitchy I : +15% chance to retaliate on every incoming attack (independently of main attack), can occur multiple times per round
- Accuracy I : enemy Dodge chance is decreased by 15%
- Tactical : normal weapons ignore fighters and irrelevant ships and aim for carriers and other dangerous targets (preferrably high-damage low-structure ships) as first priority, flak cannons always prioritize fighters

Commando : one or two of (randomly):
- Evasive III : +30% to dodge incoming attack ( up to 50% if stacked with Evasive I and Evasive II )
- Lethal III : damage of all weapons increased by 35% ( up to 65% total ), flak cannons get additional 3 shots ( up to 8 ), every successful attack damages two other random enemy ships by 10% of original damage
- Hardy III : max and current structure of ship increased by 35% ( up to 65% total )
- Survival II : every turn ship regenerates additional 25% ( up to 35% total ) of max structure
- Twitchy II : +25% ( up to 40% total ) chance to retaliate on every incoming attack, can occur multiple times per round
- Accuracy II : enemy Dodge chance is decreased by additional 25% ( up to 40% decrease )
- Critical I : every successful attack has 10% chance to deal 200% of damage
- Scrapper I : every successful attack regenerates ship's structure by 10% of damage dealt
- Barriage I : when damage dealt is higher than target ship's structure, 50% of remaining amount of damage is dealt to one other random enemy ship
- DIsruptive I : every round of combat disables 1 random skill of 1 random enemy ship
- Escape I : when ship is presumed to be destroyed in combat, it's removed from remaining combat but has 15% chance to survive with 1 structure at same location ( and can run away from enemy fleet on next turn if combat was lost )
- Leadership I : upon start of combat 2 friendly ships get 1 random skill of this ship ( only lasts during combat )

Elite : two or three of (randomly):
- Evasive IV : +50% to dodge incoming attack ( up to 100% chance if stacked with all Evasive levels, but final Dodge chance capped at 80% (higher values just make ship more resilient to Accuracy of attacking ship) )
- Lethal IV : damage of all weapons increased by 50% ( up to +115% total ), flak cannons get additional 5 shots ( up to 13 ), every successful attack damages two random ships for additional 15% of original damge ( up to +25% ), damages three more ships for 10% of original damage
- Hardy IV : max and current structure of ship increased by 50% ( up to +115% total )
- Survival III : every turn ship regenerates additional 30% ( up to 65% total ) of max structure, every round ship regenerates 10% of total structure
- Twitchy III : +35% ( up to 75% total ) chance to retaliate on every incoming attack, can occur multiple times per round, every retaliation has 25% chance to do another retaliation to random enemy ship
- Accuracy III : enemy Dodge chance is decreased by additional 40% ( up to 80% decrease )
- Critical II : every successful attack has additional 15% chance ( up to 25% ) to deal 300% of damage ( up to 500% if stacked with Critical I )
- Scrapper II : every successful attack regenerates ship's structure by additional 25% ( up to 35% ) of damage dealt
- Barriage II : when damage dealt is higher than target ship's structure, 50% of remaining amount of damage is dealt to two other random enemy ships ( up to three ships if stacked with Barriage I )
- DIsruptive II : every round of combat disables 1 random skill ( up to 2 ) of 2 ( up to 3 ) random enemy ships
- Escape II : when ship is presumed to be destroyed in combat, it's removed from remaining combat but has 25% chance ( up to 40% chance ) to survive with 1 structure at same location ( and can run away from enemy fleet on next turn if combat was lost )
- Leadership II : upon start of combat 5 friendly ships ( up to 7 ) get 2 random skills ( up to 3 if stacked with Leadership I ) of this ship ( only lasts during combat )
- Fear I : every round 1 or 2 random enemy ships don't attack or launch fighters
- Rush I : gets additional attack with all weapons every round
- Mirror I : reflects 35% of received damage to random enemy ship (so takes 35% less damage itself)
- Illusion : permanently gets a disguise on galaxy map (enemy empires see this ship as different design), disguise is taken randomly from all designs built by player, hides all skills and experience (is seen as "Green")

Godlike : three of (randomly):
- Evasive V : +75% to dodge incoming attack ( up to 175% chance if stacked with all Evasive levels, but final Dodge chance capped at 95% (higher values just make ship more resilient to Accuracy of attacking ship) )
- Lethal V : damage of all weapons increased by 85% ( up to +200% total ), flak cannons get additional 7 shots ( up to 20 ), every successful attack damages two random ships for additional 25% of original damge ( up to +50% ), damages three more ships for additional 15% of original damage ( up +25% ), damages all other enemy ships for 10% of original damage
- Hardy V : max and current structure of ship increased by 85% ( up to +200% total )
- Survival IV : every turn ship regenerates additional 35% ( up to 100% total ) of max structure, every round ship regenerates additional 20% ( up to 30% ) of total structure
- Twitchy IV : +75% ( up to 125% total, if more than 100% - retaliates one more time ) chance to retaliate on every incoming attack, can occur multiple times per round, every retaliation has additional 35% chance ( up to 60% ) to do another retaliation to two random enemy ships ( up to three )
- Accuracy IV : enemy Dodge chance is decreased by additional 70% ( up to 150% decrease with all Accuracy levels, ship with all Evasive levels will still have 25% chance to Dodge in this case )
- Critical III : every successful attack has additional 20% chance ( up to 45% ) to deal additional 500% of damage ( up to 1000% if stacked with Critical I and Critical II )
- Scrapper III : every successful attack regenerates ship's structure by additional 65% ( up to 100% ) of damage dealt
- Barriage III : when damage dealt is higher than target ship's structure, 50% of remaining amount of damage is dealt to three other random enemy ships ( up to five ships if stacked with Barriage I and Barriage II)
- DIsruptive III : every round of combat disables additional 2 random skills ( up to 4 ) of additional 4 ( up to 7 ) random enemy ships
- Escape III : when ship is presumed to be destroyed in combat, it's removed from remaining combat but has 40% chance ( up to 80% chance ) to survive with 1 structure at same location ( and can run away from enemy fleet on next turn if combat was lost )
- Leadership III : upon start of combat 8 friendly ships ( up to 15 ) get 5 random skills ( up to 8 if stacked with Leadership I and Leadership II ) of this ship ( only lasts during combat )
- Fear II : every round 3-5 ( 4-7 if stacked with Fear I ) random enemy ships don't attack or launch fighters
- Rush II : gets 2 additional attacks ( up to 3 if stacked with Rush I ) with all weapons every round
- Mirror II : reflects additional 45% ( 80% if stacked with Mirror I ) of received damage to random enemy ship (so takes 45% or 80% less damage itself)
- Revival : after every fights recovers 50-100% (randomly) of lost ships with 1 structure on same node
- Overpower : during combat all friendly ships get good pilots +2, all enemy ships get bad pilots +2 (if enemy fleet has ship with Overpower too - this is prevented and both fleets get Normal Pilots on all ships)
- To The End : after presumed destroyed in combat, still attacks every turn until end of combat (and can't be targeted). If Escape skill took place, this behavior is prevented ( ship won't attack during combat but will survive after it).
- Fortress : all received damage is reduced to 90%, invulnerable to fighters
- Invulnerabiity : blocks all damage first 3 rounds of combat
- Gray Goo Armor : every turn current and max structure is increased by 20 ( capped at 50000 )

This will provide an interesting game mechanic by allowing to build unique fleets, and will also smooth out disbalances between different hulls (now when a player starts building fractals - older energy hulls typically die like flyes to them, same with solar hulls and titanic hulls). Now newly built Solar Hull ships will be Green and it will be possible (though still challenging) to take them over with older fleet which is more experienced.
Godlike level skills may seem a bit unbalanced but it will be really really hard to get ship to this level of experience. Also, combos like all 5 Evasive skills are very rare, so their power is balanced by rarity.
Also, for this mechanic to work, ship upgrades must be implemented. So that you can bring older design ship to shipyard and issue 'upgrade' order which will take several turns and industry points but will turn it into stronger design ship. Skills will remain but ship will be moved back a few levels (losing some XP), but can reachieve these levels later.

**Comment by o01eg** [comment]
Too much micromanagement. Do not want.

**Comment by afwbkbc** [comment]
Micromanagement where? Everything happens automatically, you just may need to move one ship to another fleet to make it more effective (but this happens already, a single doomstack is rarely enough).
Where do you see additional micromanagement?
