### ISSUE TITLE
double clicking a production queue item causes an incomplete UI update

### ISSUE THREAD

**Issue by Dilvish-fo** [freeorion/freeorion#1486]
most specifically, the MapWnd active system indicator and the color highlighting of queue item locations will not update even though the BuildDesignator system has changed.   This was [raised on our forums](http://www.freeorion.org/forum/viewtopic.php?f=28&t=10510) by Oberlus: 
> When you have the production queue open and you click on a system in the map, the production entries corresponding to the planets of that system get the planet's name highlighted (plus you hear that soft sound for selecting sth and you see the planets of that system in the right panel). I love that feature, makes things easier.
If you single-click on an entry of the production queue the map focus on the corresponding system but the selected system/fleet does not change. Again lovable.
If you double-click on a production entry the map focus change, the planets of that system show up at your right and you have effectively selected that planet from that panel (you even hear that sound for changing selected object in the map). However (here comes the possible minor bug), the system doesn't show as selected (there is no white ring around it, it keeps circling on the previously selected object in the map) and the planets names in the production queue aren't highlighted. Then, if you try to select the system in the map (or the planet in the right panel, that is already selected) to get that helpful highlight you get nothing, you (double-)click on the planet to no avail. I realised that the planet is actually selected but the GUI is not showing the change. So when you click on the planet, as it is already selected, it does nothing. If you select another system and then back the one you want, you get the corresponding production entries highlighted as desired. The workaround is to not use the double-click on the queue list, just single-click (to locate the system in the map) and then select the system in the map.
Also, it seems I can't get screenshots from within the game (fullscreen), I just get a black box to paste. I'm on Windows 7 (I thought I was Windows 10, I'm so noob with M$ systems...).

I have confirmed this on Linux, and also found that this can lead to the MapWnd showing the system selection indicator circle active on two different systems simultaneously.   I think the problem stems from ProductionWnd::QueueItemDoubleClickedSlot() calling BuildDesignatorWnd::CenterOnBuild(), which among other things calls BuildDesignatorWnd::SelectSystem() which calls SidePanel::SetSystem() to select the system and which also selects the planet;  this all is a subset of what happens when clicking on a MapWnd system with the production window open.  The latter triggers MapWnd::SelectSystem(), which changes the system icon selection as well as triggering some other updating.

I will explore having BuildDesignatorWnd::CenterOnBuild() call to MapWnd::SelectSystem() rather than skipping over steps directly to BuildDesignatorWnd::SelectSystem().

**Comment by MatGB** [comment]
Gah, you hit submit as I was typing the same issue up, I'll close mine.

**Comment by wheals** [comment]
Oops, that was my implementation that did it wrong I think, but glad to see that it got eventually fixed :)
