### ISSUE TITLE
AI prematurely ending system-secure missions

### ISSUE THREAD

**Issue by Dilvish-fo** [freeorion/freeorion#1494]
I just discovered that the AI is commonly prematurely ending its system-secure missions, such as when it wants to secure a system in order to invade a planet (and in many other cases as well), I have observed it only having fleet orders to move to the end system, but not having any other fleet orders, so that when it issues the final move order it is thinking all its orders are finished and it is clearing itself.

I suspect that this is an unintended side effect from recent changes that allowed the AI to pass through systems without always stopping, it turns out that [some of the fleet order creation code](https://github.com/freeorion/freeorion/blob/master/default/python/AI/AIFleetMission.py#L518-L527) was apparently dependent on the practice of always stopping at each system, and it appears that the normal final OrderMilitary() was no longer being generated, which in turn was allowing for premature termination of the secure mission as soon as the final move order was issued.

I am working on a fix and hope to submit a PR promptly.

As this is a fairly significant impediment for the AI, I am setting the Milestone as 0.4.7, not optional; requiring an RC2.

**Comment by Vezzra** [comment]
Yep, that definitely needs to be fixed for the release. Which means we're going to have a RC2.

**Comment by Vezzra** [comment]
Doh, tagging an issue for cherry picking is kind of dumb, silly me. Sorry... 😉
