### ISSUE TITLE
Inner system circle doesn't show white if co-owned with natives

### ISSUE THREAD

**Issue by MatGB** [freeorion/freeorion#1498]
### Environment

* **FreeOrion Version**: 3efa627 RC1
* **Operating System**: Linux
  * Compiled from source

### Description
After outposting one planet in a system where the other planet is inhabited by natives, the entire inner circle shows my colour with no white (see picture)

NB: the white showing is the 'system selected' cursor, if the system is deselected it goes and the entire inner is purple but you can't then get the planet in one pic.

### Expected Result
If there are inhabited/outposted planets in a system, the inner circle should show all present colours.
![screenshot_20170416_223554](https://cloud.githubusercontent.com/assets/11533206/25074542/70a85c3e-22f5-11e7-9114-59ee6cdc4e5b.png)

(marking as optional as it's a new feature, if easily fixable it should be)

**Comment by TheSilentOne1** [comment]
Will fix this, possibly on next monday.

**Comment by TheSilentOne1** [comment]
Thanks for the feedback. Fixed.
