### ISSUE TITLE
Allied vision does not reveal ship type

### ISSUE THREAD

**Issue by Voker57** [freeorion/freeorion#1499]
They show up as "Ship" with unknown stats, as seen on that screenshot: 

![unseen ships](http://dump.bitcheese.net/files/pumucir/ship.png)

Save (load with Voker57 empire, look at system in screenshot): http://dump.bitcheese.net/files/lihusyz/hidden.mps

version: teamsmac-11.1, based on e45dedee03a215e5a7be8f

**Comment by Dilvish-fo** [comment]
poking around with your save file, I see that the direct ship info actually all comes over fine, but the ship design does not (only the design ID).  I'm submitting a PR that fixes this.
