### ISSUE TITLE
[Bug] Freeorion causes BSOD on Windows 10 when another game is running in background

### ISSUE THREAD

**Issue by afwbkbc** [freeorion/freeorion#1501]
OS: Windows 10 Pro v.1511 En-us x64 July2016 Pre-Activated-=TEAM OS=
Hardware: Asus Crosshair V Formula-z / AMD FX-9590 / ASUS STRIX GTX1070 O8E OC / Corsair Vengeance Pro 2400Mhz 32GB DDR3

Steps to reproduce:
1) Launch freeorion
2) Launch some other game (i.e. Dark Souls 3) in Stereo 3D mode (Nvidia 3d Vision 2)
3) Keep stereo 3D game minimized while freeorion maximized
4) Maximize stereo 3D game via Alt-Tab

Result:
Sometimes it results in BSOD with message like IRQL_NOT_LESS_OR_EQUAL or something. Sometimes (rarely) some other error message takes place.

Other tested cases:
- dark souls 3 (stereo 3d) minimizing/maximizing infinetely - no bsod
- dark souls 3 (stereo 3d) in background, UT4 in foreground, alt-tabbing between them - no bsod
- fallout 4 (stereo 3d) in background, freeorion in foreground, alt-tabbing - sometimes bsod
- dark souls 3 ( no stereo 3d ) in background, freeorion in foreground, alt-tabbing - no bsod

So, it looks like BSOD happens only when stereo 3d is on **and freeorion is running**.
This issue is serious because I want to play dark souls 3 while others are making their turns in freeorion. So it's potentially game ruining bug. Please fix.

**Comment by geoffthemedio** [comment]
Some obscure driver conflict isn't something we can fix. If you can afford the fancy 3D hardware, you can probably afford a spare laptop to run FreeOrion on separately.
