### ISSUE TITLE
Opening the Research window should refresh the list of (available) Techs

### ISSUE THREAD

**Issue by memem359** [freeorion/freeorion#1505]
This is not about the Queue, but about the list of available Techs in the larger window.

When I'm using the Research window, I normally use List view, Completed "off", and Availble/Locked/Partially Unlocked as "on". If I close this window (to go back to the main galaxy view) and come back to it several turns later, the list of Techs is the same as I left it.

That means that any Techs that were completed during that time are still on that list, despite the option of not seeing competed techs.

I need to hit a button (like "All" twice, or Completed on/off) to get the information to refresh.
This is minor, but still annoying.

I'd suggest that getting to this window (hitting the Research menu button from the galaxy view) should automatically refresh the list, instead of just bringing up the previous state.

**Comment by Dilvish-fo** [comment]
as noted above, I just put an imperfect fix as a branch on my fork; this simple change has the minor drawback that changing a planet focus would now cause the the current vertical scroll status of the tech list to be lost, and I'm not feeling in the mood to chase down that aspect just now, is why I haven't put the PR here.

**Comment by dbenage-cx** [comment]
@Dilvish-fo I should not have self-assigned this without first asking if you were still looking into the issue.
Please change assignment if you have some pending changes in mind.  If not, I'd like to propose [this branch](https://github.com/freeorion/freeorion/compare/master...dbenage-cx:fix-1505_research-list-update) which partially addresses the scroll issue.

**Comment by Dilvish-fo** [comment]
No worries, I happily cede the task to you :smiley:
