### ISSUE TITLE
successful AIs crippled by eventual switch to hyperfocus on research

### ISSUE THREAD

**Issue by Dilvish-fo** [freeorion/freeorion#1511]
Successful AIs wind up crippling themselves by switching to research hyperfocus.

I had been kind of noticing this happening to the leading AIs in my recent games, but it hadn't really sunk in what was happening until I actually got around to examining one of the respective logs.  

Here is an example from the game that finally prompted me to examine what was happening.  The lead AI was cranking along quite happily, at turn 131 it had 343 PP (target 427) and 162 RP (target 172).  Then on turn 132 it decided to just switch all its non-defense planets over to research (even though it did not actually *want* more research), making its target PP plummet to 118.  And this wasn't just a coincidental momentary thing from it happening to dither all its planets at once, it was keeping this up constantly at least up through turn 145 when I decided I needed to get it sorted out (and I separately confirmed it was not the dither code prompting this).  So far I have not figured out the exact trigger.  Just that in a single turn it went from saying "My desired RP/PP ratio is 0.43 and I will settle on focii that give me a reasonable target ratio of 0.35", to saying "My desired RP/PP ratio is 0.43 but I will choose focii that give me an ***insane*** target ratio of 2.52"

```
Planet Focus Assignments to achieve target RP/PP ratio of 0.43 from current target ratio of 0.40 ( 172.0 / 427.1 )
Max Industry assignments would result in target RP/PP ratio of 0.15 ( 76.5 / 505.9 )
Max Research assignments would result in target RP/PP ratio of 2.50 ( 292.3 / 116.8 )
-----------------------------------
Final Ratio Target (turn  131) RP/PP : 0.35 ( 157.2 / 454.5 ) after 2 Focus changes
Current Output (turn  131) RP/PP : 0.47 ( 161.7 / 343.2 )
```

```
Planet Focus Assignments to achieve target RP/PP ratio of 0.43 from current target ratio of 0.35 ( 160.3 / 463.4 )
Max Industry assignments would result in target RP/PP ratio of 0.15 ( 77.6 / 516.3 )
Max Research assignments would result in target RP/PP ratio of 2.54 ( 299.4 / 117.8 )
-----------------------------------
Final Ratio Target (turn  132) RP/PP : 2.52 ( 297.2 / 117.8 ) after 16 Focus changes
Current Output (turn  132) RP/PP : 0.45 ( 162.1 / 357.3 )
```

This does only seem to be happening once the AIs reach a certain level of accomplishment, which they have been much better at lately, and which could be why we hadn't noticed this before.   At that stage, though, this seems to me to be a rather severe impediment for the AIs, yet I am quite hopeful of solving it, so I am designating this as mandatory to resolve for 0.4.7, but of course that's open for discussion.  I have several hours available to focus on it right now, so hopefully will get a fix up in time for it to be reviewed/tested/accepted within the time available under @Vezzra 's current RC2 schedule.

@Morlic-fo @dbenage-cx @LGM-Doyle I am hoping one or more of you will have some time to also look at this, at least once I get it fixed or maybe even before.  There also appears to have been some bugginess in the logging for focus assessments, so I will probably go ahead and put up a Work-in_Progress PR that just has corrections for the logging while I keep working on the main problem.

**Comment by Vezzra** [comment]
> so hopefully will get a fix up in time for it to be reviewed/tested/accepted within the time available under @Vezzra 's current RC2 schedule.

@Dilvish-fo, you know, you don't need to put yourself under too much pressure, you can always ask for an extension of the deadline. I'm not *that* harsh of a taskmaster, now am I...? 😉 😃

**Comment by LGM-Doyle** [comment]
I can confirm that is a typo fix.
