### ISSUE TITLE
FTBFS - Boost 1.64.0 -  serialization::make_array

### ISSUE THREAD

**Issue by dbenage-cx** [freeorion/freeorion#1513]
With boost 1.64.0, make_array was removed(?) from boost::serialization.
numeric::ublas was not updated for this change, thus freeorion will fail to compile (only first error shown):
```console
CMakeFiles/freeorioncommon.dir/build.make:110: recipe for target 'CMakeFiles/freeorioncommon.dir/combat/CombatLogManager.cpp.o' failed
In file included from /opt/projects/boost/1_64_0/include/boost/numeric/ublas/vector.hpp:21:0,
                 from /opt/projects/boost/1_64_0/include/boost/numeric/ublas/matrix.hpp:18,
                 from /opt/projects/boost/1_64_0/include/boost/numeric/ublas/symmetric.hpp:16,
                 from /opt/projects/freeorion/combat/../universe/Universe.h:11,
                 from /opt/projects/freeorion/combat/CombatSystem.h:4,
                 from /opt/projects/freeorion/combat/CombatLogManager.h:4,
                 from /opt/projects/freeorion/combat/CombatLogManager.cpp:1:
/opt/projects/boost/1_64_0/include/boost/numeric/ublas/storage.hpp: In member function ‘void boost::numeric::ublas::unbounded_array<T, ALLOC>::serialize(Archive&, unsigned int)’:
/opt/projects/boost/1_64_0/include/boost/numeric/ublas/storage.hpp:299:18: error: ‘make_array’ is not a member of ‘boost::serialization’
             ar & serialization::make_array(data_, s);
                  ^~~~~~~~~~~~~
```

Boost ticket [#12978](https://svn.boost.org/trac/boost/ticket/12978)
There is a (still pending) upstream PR: [boostorg/ublas #46](https://github.com/boostorg/ublas/pull/46), inclusion of which would allow build to complete.

I have not yet found the commit in boost::serialization that made this change, so posting as issue in case someone comes across it before.

A potential workaround:
```diff
diff --git a/universe/Universe.h b/universe/Universe.h
index d98d8d6..9ada5c3 100644
--- a/universe/Universe.h
+++ b/universe/Universe.h
@@ -8,6 +8,9 @@
 
 #include <boost/signals2/signal.hpp>
 #include <boost/unordered_map.hpp>
+#if BOOST_VERSION >= 106400
+    #include <boost/serialization/array_wrapper.hpp>
+#endif
 #include <boost/numeric/ublas/symmetric.hpp>
 #include <boost/serialization/access.hpp>
 #include <boost/thread/shared_mutex.hpp>
```

**Comment by Vezzra** [comment]
If I understand correctly, this breaks building FO on all Linux distros which ship boost 1.64. A FO release that can't be built on a substantial part of Linux distros because of issues with the current boost version is something we should try to avoid. I mean, this is exactly one of those things we consider making bugfix releases for in the future.

*Therefore I consider this issue critical for 0.4.7 and assign this to the v0.4.7 milestone.* @dbenage-cx, if the fix/workaround you suggested above works, it should go in before I produce RC2 (which I'm going to postpone if necessary).

Any objections?

**Comment by geoffthemedio** [comment]
sounds reasonable, especially if the fix is a single boost version-dependent include.
