### ISSUE TITLE
AI needlessly builds half-strength troopers

### ISSUE THREAD

**Issue by Dilvish-fo** [freeorion/freeorion#1517]
As noted in [a thread on our forums](http://www.freeorion.org/forum/viewtopic.php?p=88400#p88400), the AI has been observed building troopers from half-strength species.  I had initially just chalked that up to limited AI species availability, but I have now observed the AI build exobot troopers with robotic hull when it also had Ugmors available with shipyard/dockyard and its whole empire was in the same resource group.

I think this deserves being fixed for RC2, but I'll need a bit more time, hopefully no more than half a day to a day.

**Comment by Vezzra** [comment]
> I think this deserves being fixed for RC2, but I'll need a bit more time, hopefully no more than half a day to a day.

I've extended the deadline for RC2 until Monday evening (UTC), so you've got the entire weekend. Take all the time you need, and if the weekend isn't sufficient, we'll extend the deadline again. 😃
