### ISSUE TITLE
Log output of ClientNetworking::GetMessage is not utf-8

### ISSUE THREAD

**Issue by dbenage-cx** [freeorion/freeorion#1536]
Not typically a concern, as such message requires `TRACE_EXECUTION`.

Message output to logs is non-utf8(not deserialized?):
`[debug] Client : ClientNetworking.cpp:442 : ClientNetworking::GetMessage() : received message Message: GAME_START -1(server/unknown) --> 1 "`...(line continues but fails to paste)

ref a63dc71

**Comment by LGM-Doyle** [comment]
@dbenage-cx that message text is the raw message.  It may not even be text and `ClientNetworking`/`Message` has no way to determine what it is.  That is why it is at the trace level.  It is only useful to someone debugging the network code.
