### ISSUE TITLE
Research and Production Queue UI inconsistent

### ISSUE THREAD

**Issue by Morlic-fo** [freeorion/freeorion#1537]
Version: RC2 / 2017-04-24.60d06dc

Production Queue entries are removed by ctrl+left-click while Research Queue entries are removed by double-left-click; ctrl+left-click does not do anything.

It seems that the behaviour should be consistent between these two.

**Comment by MatGB** [comment]
Been meaning to open a similar issue: we need to standardise the UI across different windows, it used to be that double click removed items everywhere but as that was incredibly laggy in some windows they got changed.

Now ctrl+click does it in some, right click/delte or remove does it in some and double click still does it in, IIRC, research.

Needs to be the same across all screens, including the design window.

**Comment by dbenage-cx** [comment]
@MatGB Anything specific that is different on design window?  I only noticed the ship design layout using double click for part removal (only other option is to drag the part away or drag a different part on top of it).

SitReps also use double click to "completely ignore", but only on the icon portion.

I am favouring deletion on Control+LeftClick for easier use on trackpads/touchscreens and preventing accidental double clicks from being troublesome (partially complete queue item).

**Comment by MatGB** [comment]
I'll check through, I think it was that research was different and I knew that ctrl+click had been added to design relatively recently.

If we're consistent I'm happy, if we're consistent based around what we do in production I'm even happier because I like that and agree with you on ctrl click being best.

**Comment by dbenage-cx** [comment]
Any remaining inconsistencies?

**Comment by Morlic-fo** [comment]
Seems consistent now. At the very least, the original point has been adressed.
