### ISSUE TITLE
intel_do_flush_locked failed: Input/output error

### ISSUE THREAD

**Issue by tex** [freeorion/freeorion#1554]
First, thank you for perfect game. This is really great successor of Master of Orion 2 which I loved.

Crashes with:

[milan@nixos ~]$ ./result/bin/freeorion                                                                                                                                                                                         ~
intel_do_flush_locked failed: Input/output error

### Environment

* **FreeOrion Version**: FreeOrionCH v0.4.7 
* **Operating System**: NixOs (Linux)
* **Graphic card used**: Integrated Graphics Chipset: Intel(R) HD Graphics 3000
* **Fetched as**   * Compiled from source

### Description
It is constantly crashing. Interesting thing is that since turn ~50 or so, it is very chocked. I do not hit next turn, but it is still freezing every 30 or so seconds. It freeze for 10 - 30 seconds - no mouse, no UI updating, nothing. It then resumes and works OK work following 30 or so seconds until it freeze again.

### Expected Result
Not crashing. Not freezing.

### Steps to reproduce
Play game. Single player, UI threads 1, AI threads 1. Play at least 200 turns.

**Comment by geoffthemedio** [comment]
Googling your error message, 'intel_do_flush_locked failed' suggests it is a kernel issue. If so, it's probably not something we can fix.

**Comment by tex** [comment]
Seems correct.

I did updated my configuration.nix with

services.xserver = {
      videoDriver = "intel";

      deviceSection = ''
	#Identifier "Intel Graphics"
	Option "AccelMethod" "uxa"
	Option "Backlight" "intel_backlight"
	BusID "PCI:0:2:0"
      '';
};

and that did the trick. No more crashes, no locking up / long freezing.

Thanks!
