### ISSUE TITLE
Objects Window: X doesn't close 

### ISSUE THREAD

**Issue by MatGB** [freeorion/freeorion#1555]
### Environment

* **FreeOrion Version**: 72992d2
* **Operating System**: Linux
  * Compiled from source

### Description
Objects window isn't closing if I click the X in the corner of the window, it opens and closes normally using the top right menu toggle.

This isn't affecting Sitrep or Pedia.

### Expected Result
Objects should close if the X is clicked as well as from the menu.

**Comment by geoffthemedio** [comment]
My guess was that it was related to recent reworking of signal connections, but I don't see anything relevant in https://github.com/freeorion/freeorion/commit/8e106cfe595197ae2425a407560330f56a0065e2
