### ISSUE TITLE
dropdown mousewheel scroll anomalies/bugs

### ISSUE THREAD

**Issue by Dilvish-fo** [freeorion/freeorion#1573]
### Environment
* **Operating System**: Ubuntu Linux
* **Fetched as** 
  * Compiled from source

### Description
There are two aspects to this, the first is nuisance behavior, the second is a bug
a) *Unintended dropdown scrolling of planetary focus and of production queue repeat/blocksize* -- Neither of these require clicking on the dropdown element to activate mousewheel scrolling, and so it can easily happen by accident when in the process of mousewheel-scrolling the larger listboxes (SidePanel, and ProductionQueue) which contain the panels on which these dropdowns appear.  This causes actual changes/problems for the planetary focii, though as noted below it may only cause a display glitch for the ProductionQueue.
b) *mismatch between display and actual setting for mousewheel-scrolled ProductionQueue dropdowns*
If using only mousewheel scroll to change a productionqueue item panel repeat or blocksize dropdown (without afterwards left-clicking on the dropdown), the numeric label on the dropdown will change, but it appears that the status of the item does not actually change -- the reported PP this turn and until completion will not change, and upon advancing to the next turn the dropdowns for that item will have reverted to their previous values.

### Expected Result
UI elements should not be excessively easy to accidentally change, and their display status should match their actual status.

### Proposed fixes
*  for accidental scrolling-- enable mousewheel scrolling of dropdowns only while either (i) they have been left-clicked to open up their dropdown listing, or (ii) the shift key is being held down
* for production panel display mismatch -- if the display label is changed via mousewheel scroll, ensure that the actual setting is changed also

**Comment by geoffthemedio** [comment]
These are two almost unrelated issues.

The production batch size and repetitions one is longstanding, and I'm slightly surprised there isn't already a bug about it.

**Comment by Dilvish-fo** [comment]
I'll agree the two aspects are distinct, but they are also related-- if the resolution for the first issue were to only enable the dropdown mousewheel scroll upon left-clicking the dropdown, then the second issue would already be fixed by that.

**Comment by LGM-Doyle** [comment]
@Dilvish-fo I added a [PR](https://github.com/freeorion/freeorion/pull/1577) that restricts the mouse wheel scrolling of all `DropDownLists` as you suggested.

**Comment by Dilvish-fo** [comment]
As suggested in LGM-Doyle's PR, [here is a reminder note](https://github.com/freeorion/freeorion/pull/1577#pullrequestreview-40414015) about a possible generalization to that PR that might be done if the ProductionWnd blocksize and repeat dropdowns were fixed to record changes even if no clicks were involved.

**Comment by geoffthemedio** [comment]
Has there been any progress on this?

**Comment by Dilvish-fo** [comment]
I'll accept [LGM-Doyle's assessment that this has been sufficiently resolved](https://github.com/freeorion/freeorion/pull/1577#issuecomment-318746530).
