### ISSUE TITLE
increasing blocksize of partially completed ships destroys all current progress

### ISSUE THREAD

**Issue by Dilvish-fo** [freeorion/freeorion#1574]
### Environment
* **Operating System**: Ubuntu Linux
* **Fetched as** 
  * Compiled from source

### Description
increasing the blocksize of a partially completed ship-type build item will cause all current progress to be lost (unless the change is undone before advancing to the next turn).

### Expected Result
Doubling the blocksize (or increasing by some other factor N) should not cause all current progress to be lost, but instead should cause the current percentage completion to simply drop to 1/2 (or 1/N) of what it was before the change.

**Comment by geoffthemedio** [comment]
Working as intended I think... If you want to produce 2 ships, and it takes minimum 4 turns to produce any given ship, you can't take a half-produced ship and turn it instantly into two quarter-produced ships. Regardless, it's probably a forum discussion, not a bug.

**Comment by Dilvish-fo** [comment]
The current penalty greatly exceeds the minimum penalty necessary to accomplish the goal you state, so it does still seem like a bug to me.  I've opened [a forum thread to discuss it.](http://www.freeorion.org/forum/viewtopic.php?f=6&t=10563)

**Comment by Vezzra** [comment]
> Regardless, it's probably a forum discussion, not a bug.

[As I already stated in the forum thread](http://www.freeorion.org/forum/viewtopic.php?p=88889#p88889), I disagree. While not a bug in the technical sense (an error in the code), it's definitely a design flaw, which, for the purpose of classification here, should be considered a bug.

Meaning, the current implementation has to be fixed, in whatever way.
