### ISSUE TITLE
Wrong panel position in planet view, two monitors

### ISSUE THREAD

**Issue by xunto** [freeorion/freeorion#1592]
### Environment
* **FreeOrion Version**: 0.4.7
* **Operating System**: Archlinux
* **Graphic card used**:  NVIDIA Corporation GK106 [GeForce GTX 660] (rev a1)

* **Fetched as**
  * Binary release

### Description
http://imgur.com/jRV5xpe

Looks like gui is drawn wrong. I think that this image is self-explanatory. I have two monitors, so maybe this is the cause of problem.

### Expected Result
http://imgur.com/vRGOwRL

The same way as in galaxy view.

### Steps to reproduce
Just open planet view.

**Comment by xunto** [comment]
Oups. Sorry. I didn't found a way to move it before. Sorry.

**Comment by xunto** [comment]
Oups. Sorry. I didn't found a way to move it before. Sorry.

**Comment by MatGB** [comment]
That's alright. For what it's worth, the not-very-well documented Persistent Config (in the wiki and soon in the in game Pedia) will allow you to store window and panel positions between games and after upgrading between releases.
