### ISSUE TITLE
Split/Duplicate production gives incorrect batch sizes

### ISSUE THREAD

**Issue by MatGB** [freeorion/freeorion#1610]
### Environment
* **FreeOrion Version**: 8b96e3a
* **Operating System**: Linux
  * Compiled from source

### Description
When using either the split or duplicate commands introduced for production in 051a839 the batch size isn't honoured, so an order of 10 troop ships becomes an order of 1 troop ship.

### Expected Result
Batch sizes should be honoured if you split or duplicate a production item.

**Comment by geoffthemedio** [comment]
Hopefully fixed by https://github.com/freeorion/freeorion/commit/8962f2365250f9337f3a5d6e1c8d3df825584841

**Comment by Vezzra** [comment]
From my brief testing of the last test builds it looks like the fix works as intended.
