### ISSUE TITLE
If-effects (Effect::Conditional) does not report effects

### ISSUE THREAD

**Issue by agrrr3** [freeorion/freeorion#1613]
### Environment
* **FreeOrion Version**: 4.7.x (checked on a master like to weeks ago)
* **Fetched as** 
  * Compiled from source

### Description
When using the If-effects in FOCS to e.g. conditionally add troops like in this commit: 
[this commit](https://github.com/agrrr3/freeorion/commit/b354389b1925020acfaa9ed62b2a07d09a28c773), the effect applies but is not explained (see attached screenshot, there should be a +100 troops modifier)

<img width="216" alt="test-if-effects-accountinglabel--plus-100-troops-not-shown" src="https://user-images.githubusercontent.com/3252041/27474460-9be6cf1a-5802-11e7-9ee4-d48f1a6ed07d.png">

### Expected Result
The effect result applies and the reason is reported on the details mouseover using the correct accountinglabel.

### Steps to reproduce
* Use this [scripting branch test-if-effects-accountinglabel](https://github.com/agrrr3/freeorion/tree/test-if-effects-accountinglabel) with your freeorion. 
* Start a game, advance a turn.
* See the troops on a planet (should be at least 50) and explanations

**Comment by geoffthemedio** [comment]
Seemingly fixed in https://github.com/freeorion/freeorion/commit/3048071a75fb3eb04f888265dfc0045c853e6185
