### ISSUE TITLE
Research screen List view / Tree view UI parity

### ISSUE THREAD

**Issue by rriegs** [freeorion/freeorion#1628]
Various UI features present in the Research screen's Tree view are absent from its List view.  In particular:

- [x] Completed, unlocked, locked, and queued techs each have different visual indicators in Tree view: bright, normal, and dim backgrounds and an outline, respectively.  No such visual differentiation is present in List view.  It would make sense to color row backgrounds similarly, and queued status could be indicated by a heavier white row border.

- [x] Ctrl-double-clicking techs in Tree view adds them to the top of the queue, but behaves the same as just double-clicking in List view (adding to the bottom).  Ctrl-double-clicking should add to the top in List view as well.

- [x] Right-clicking techs behaves very mildly differently in either view: specifically, in Tree view, right-clicking a queued tech still pops up a context menu with "Pedia Lookup...", while in List view, right-clicking such a tech has no effect.
  - [ ] In my opinion, both views should also offer "Move to Queue Top" above "Pedia Lookup..." for queued techs.
  - [x] In addition, both views should offer both "Add to Queue" and "Add to Top of Queue" for unqueued, uncompleted techs.

- [x] Hovering over techs in Tree view pops up a tooltip with additional information about the tech, while hovering over techs in List view has no effect.  Hovering should reveal the same tooltip in either view.
  - [x] The tooltip also needs some kind of delineator between the tech's category and its purpose.  At present, content runs together; for example, Robotic Production has "Production Improves Industry".  It should instead look something like "Production - Improves Industry".

**Comment by MatGB** [comment]
When we last did a revamp of the tech window UI I completely forgot to even test it on the list view, I never ever use it, so mea culpa from me for saying work done. The backend code is completely beyond me but standardised interface across all windows ought to be a design goal if/when possible.

**Comment by dbenage-cx** [comment]
> both views should also offer "Move to Queue Top" ... for queued techs.

This portion is a feature I am not certain is needed, as adjustment of order is provided more thoroughly in the queue (comments or thumbs down welcome).  Though if added, might also add "Move to Queue Bottom" and "Remove from Queue".

**Comment by MatGB** [comment]
It's not needed because it appears to already be there?

I just went and checked a bunch of things and right click/{add/move}-to-top are there in all views?

**Comment by dbenage-cx** [comment]
Maybe I am misreading that entry to mean the tech context menu in the list/tree(the main portion of the screen), instead of the queue. @rriegs Can you clarify which menu you refer to?

**Comment by MatGB** [comment]
First bullet is research queue, second is main screen list/tree, both have the context menu now (not sure when added)
![spectacle j16195](https://user-images.githubusercontent.com/11533206/29739213-2e9b89ae-8a30-11e7-8eb7-849b42386ad4.png)

**Comment by dbenage-cx** [comment]
Ok, going to mark this as resolved in that case.

If the request is for the list/tree menu (Plasma Cannon 4 in MatGB's screenshot), can be opened as separate feature request or forum discussion.
