### ISSUE TITLE
Space Station+trade

### ISSUE THREAD

**Issue by robinteus** [freeorion/freeorion#1638]
can you add a space station
without having to own planet/system
with hangar's to add fighters+/bombers
trade equipment to let certain space stations be trade centers
trade ships that do auto trading with those that you have a trade agreement with
👍

**Comment by geoffthemedio** [comment]
This is too vague to be a relevant tracker issue. I suggest opening a thread on the forums to discuss specifics.

**Comment by Vezzra** [comment]
What @geoffthemedio said. When it comes to feature requests, please use the issue tracker only for very specific/concise issues. If you want to suggest/propose more general/broad ideas for game mechanics like you did here, do that in the ["Other Game Design"](http://freeorion.org/forum/viewforum.php?f=6&sid=4aacb6e243f4621ce5cb3d6b74294cfa) board on our [forum](http://freeorion.org/forum/index.php). That is where all the design discussions take place.

**Comment by Vezzra** [comment]
Closing as invalid.
