### ISSUE TITLE
Dynamic linker lazy symbol binding fails on OSX

### ISSUE THREAD

**Issue by Vezzra** [freeorion/freeorion#1649]
### Environment

* **FreeOrion Version**: 9eafbf85772acc854dfac61f5920f46dea667ed8
* **Operating System**: Mac OSX
* **Fetched as**
  * Compiled from source

### Description

When trying to run build 9eafbf85772acc854dfac61f5920f46dea667ed8, FO crashes immediately upon program launch with these error messages dumped to the shell:
```
dyld: lazy symbol binding failed: Symbol not found: __ZN11IDAllocatorC1EiRKNSt3__16vectorIiNS0_9allocatorIiEEEEiii
  Referenced from: /Users/user/SoftwareProjekte/FO/src/Xcode/build/Test/FreeOrion.app/Contents/MacOS/./../SharedSupport/freeorioncommon.dylib
  Expected in: flat namespace

dyld: Symbol not found: __ZN11IDAllocatorC1EiRKNSt3__16vectorIiNS0_9allocatorIiEEEEiii
  Referenced from: /Users/user/SoftwareProjekte/FO/src/Xcode/build/Test/FreeOrion.app/Contents/MacOS/./../SharedSupport/freeorioncommon.dylib
  Expected in: flat namespace

Trace/BPT trap: 5
```
I cleaned and rebuilt from scratch.

I'll try to narrow down the commit which introduced the issue via bisecting within the next few days.

**Comment by memem359** [comment]
The IDAllocator (.h and .cpp) files were created/added on July 25th.
The last update to the xcodeproj file was on the 21st.

Suggest "adding" those files to the Xcode project, including them in the Common target, and see if that resolves the situation.

**Comment by Vezzra** [comment]
Doh, totally missed that! 😳 

Thanks for the pointers, fixed.
