### ISSUE TITLE
insufficient exception logging in AI scripts

### ISSUE THREAD

**Issue by Dilvish-fo** [freeorion/freeorion#1659]
While sorting out some compatibility between an experimental branch and the commits from PR #669, it became apparent that for some time now there has been some trouble with exception logging in the AI scripts.  [Morlic's observation](https://github.com/freeorion/freeorion/pull/669#issuecomment-320733587) is that the main (perhaps only) trouble is from exceptions that arise during the AI initialization.

I am performing a git bisect to locate the commit that leads to the inadequate logs, and will report here when finished with that.  My test process is to add a faulty import
``` import nothing```
after the last of the import statements in FreeOrion.py, then start a single player game with a single AI, then immediately quit (some versions gave a warning that the AI had crashed, some older versions did not), and then check the error reporting in AI_1.log.  (and then discard the changes and do the next git bisect).

### Expected Result
the AI logfile should include some traceback info like the following
```
2017-08-07 23:40:43.950909 [debug] AI : LoggingWrapper.cpp:23 : Python stdout and stderr redirected
2017-08-07 23:40:44.007204 [error] AI : : : Traceback (most recent call last):
2017-08-07 23:40:44.007237 [error] AI : : :   File "/home/FO/programs/fo_recov/default/python/AI/FreeOrionAI.py", line 36, in <module>
2017-08-07 23:40:44.007256 [error] AI : : :     import nothing
2017-08-07 23:40:44.007268 [error] AI : : : ImportError: No module named nothing
2017-08-07 23:40:44.007283 [error] AI : AIClientApp.cpp:178 : AIClientApp failed due to error in python AI code for AI_1.  Exiting Soon. id = -1
```

### Faulty Result
the AI is crashing from the exception but not providing a traceback or other indication of the source of the error; the logfile just unhelpfully lists
```
20:28:12.965815 [debug] python : configure_logging.py:185 - Python stdout and stderr are redirected to ai process.
20:28:12.966006 [info] root : configure_logging.py:197 - The python logger is initialized with a log level of %s
20:28:13.005596 [error] ai : AIClientApp.cpp:188 : AIClientApp failed due to error in python AI code for AI_1.  Exiting Soon. id = -1
```

### Environment
by my own observation, in Ubuntu Linux, and from reporting by Cjkjvfnby and Morlic, apparently also in Windows

**Comment by Dilvish-fo** [comment]
@LGM-Doyle OK well I believe I have located the problem to 5e72ae5029a9c77cab0b1e3ce17ba5d4daa1584d which is from PR #1529 

I am slightly short of 100% certainty on that mostly because of some trouble compiling some of the middle commits from the PR, the removal of TraceLogger in commit 4c6f7250c7d902fc3efad198f73a85df297edc03 appears to have been incomplete and I was getting compile errors from that point until the point where TraceLogger was reinstated.  To get around those  compile errors I wound up adding back a declaration for TraceLogger that was really just an alias for the DebugLogger.  For commit 4c6f7250c7d902fc3efad198f73a85df297edc03 this took the form
```
#define TraceLogger(name)\
    FO_LOGGER(name, debug)
```

and the AI logfile was still generated with the desired traceback info.

For the next commit, 5e72ae5029a9c77cab0b1e3ce17ba5d4daa1584d about custom LegLevel types, the alias had to change a little, to 
```
#define TraceLogger(name)\
    FO_LOGGER(name, LogLevel::debug)
```
and this is the point at which the AI logfile no longer included a traceback or similar info for the crash.  I tried poking around with a couple changes to see if I could clear up the issue, but no luck.

**Comment by LGM-Doyle** [comment]
@Dilvish-fo thanks for making an issue, chasing down the commit causing the problem and trying to fix it. 

I'll try and sort out how that broke some platforms, but not all.

**Comment by Vezzra** [comment]
@LGM-Doyle, @Dilvish-fo, did #1665 sufficiently address this issue? Can we close this as resolved?

**Comment by Morlic-fo** [comment]
Can confirm the issue is fixed on Windows.

**Comment by Dilvish-fo** [comment]
Yes, I guess I'll go ahead and close this.  There is still a similar logging problem lingering, but I have opened another Issue more specifically focused on it.
