### ISSUE TITLE
Wiki Needs New Screenshots

### ISSUE THREAD

**Issue by geoffthemedio** [freeorion/freeorion#1668]
As noted here,

https://github.com/freeorion/freeorion/pull/1657#issuecomment-321843438 

the wiki screenshots page

http://www.freeorion.org/index.php/Screenshots

is a few versions / years out of date. Some new screenshots to add to that would be useful.

**Comment by dbenage-cx** [comment]
Started discussion with some samples: http://freeorion.org/forum/viewtopic.php?f=4&t=10676

**Comment by adrianbroher** [comment]
Was covered by #2826, so this can be closed?
