### ISSUE TITLE
New python logging has horrible performance

### ISSUE THREAD

**Issue by Morlic-fo** [freeorion/freeorion#1715]
### Environment
* **FreeOrion Version**:  Test build 2017-08-24.4e12b03
* **Operating System**: Win7, 64-bit
* **Python Version**: FreeOrion-distributed

### Description
FreeOrion has become extremely slow for me. Starting a new game takes ages and the AI takes a long time to finish their turns. As it turns out, this is caused by the new python logging framework introduced by @LGM-Doyle in https://github.com/freeorion/freeorion/pull/669.

I wrote a simple test scenario for profiling: 1000 print statements and another 1000 arbitrary list extension to make sure it is not the python interpreter itself hanging.

### Result
 It takes a whole 7 seconds on my system to finish 
the 1000 print statements. Only 274ms are spent doing the actual write() call. The rest of time is spent inspecting the stack: [profiling_log.txt](https://github.com/freeorion/freeorion/files/1271262/profiling_log.txt)

### Expected Result
The overhead of the logger needs to be significantly reduced to ensure acceptable performance.

### Steps to reproduce

1. Pull https://github.com/Morlic-fo/freeorion/commit/9a98c6b6a956e7dcf24eeafa3c7e7aa2f0d48b1a
2. Start a game of FreeOrion with a single AI
3. Wait for the game to crash
4. Check end of logfile for profiling results

**Comment by Morlic-fo** [comment]
Posted a PR that offers a ~60x speedup for me. Feedback from other OS required.

Not sure how to label this.

**Comment by Dilvish-fo** [comment]
Hmm, well, my results do share with yours the aspect that inspection took up about 20 times as long as the actual writing, though my totals are much less, a bit under a second on an Ubuntu Linux desktop machine that I built 2-3 years ago (i7-4770K CPU @ 3.50GHz, typical hard drives, no SSD).  Did you check after rebooting to clear any rogue processes and then letting the boot-up settle down for any straggling startup processes?  (those seems to take quite a while on my windows laptop.) 

I'll post my before and after results in the comments to your PR since they seem more meaningful there.

**Comment by MatGB** [comment]
I've been meaning to ask what was with the slowness at various points, I'm finding it really slow to start a new game and to load a game, but once it's going I don't notice problems (then, my turns tend to take ages as I'm ducking in and out constantly).

**Comment by Morlic-fo** [comment]
Clean reboot and not running anything in the meantime still comes out at 4 seconds for the simple test case above. Given the age of my laptop, our difference in absolute numbers are not too surprising. The issue seems to be worse for windows anyway:

Rougly 30% of time for me is spent on the system-specific check for file existence (```nt.stat```). The ```nt.stat``` call was replaced in the ```os.path.isdir()``` call for performance reasons some time 2011 (https://hg.python.org/cpython/rev/f1509fc75435) but it still exists in ```os.path.exists()``` which is what ```inspect``` uses for file-checking.
