### ISSUE TITLE
Update AI for fuel part auto upgrade

### ISSUE THREAD

**Issue by MatGB** [freeorion/freeorion#1747]
Re #1709  
> when merging this PR, please open a short issue regarding the lack of AI support and link to this PR so it will not be forgotten.

**Comment by Vezzra** [comment]
@MatGB, that's actually a tweak, not a refactoring. 😉

@Morlic-fo, I think setting this to "v0.4.8" is ok for now. Once we start preparing for the release, I'll have to go over all the open issues/PRs anyway and separate them into "required for 0.4.8" and "optional for 0.4.8" anyway. Until then, "v0.4.8" is good enough for all of them, those that will *have* to go in and those that only *might*.

**Comment by Morlic-fo** [comment]
> I think setting this to "v0.4.8" is ok for now.

Your call. Either way, it is really low priority.
