### ISSUE TITLE
Player is not informed about peace/alliance proposals

### ISSUE THREAD

**Issue by Morlic-fo** [freeorion/freeorion#1749]
When testing #1748, I noticed that the human player is seemingly not informed about peace/alliance proposals from (at least) the AI. Accepting the proposal via the empire window works fine, it just is not indicated anywhere that there was such a proposal.

Best would probably be to both generate a SitRep unforming about the Proposal and to add a visual indicator in the empire window, e.g. by a special icon for the proposing empire.

**Comment by Dilvish-fo** [comment]
In addition to the two indicators you propose, it seems to me that it should also cause some notice about it to be printed in the message window also, since that is the focal point for inter-player communications.

**Comment by o01eg** [comment]
What if make the diplomacy part of `OrderSet` instead messages?

**Comment by geoffthemedio** [comment]
It would probably be better for a variety of reasons if diplomatic messages were orders.

However, there is a problem with this, which is that players will want to be able to send, immediately receive, and immediately respond to diplomatic messages. If the diplo changes are executed as an order, then "offer peace" will be sent by player A on turn 1, player B would receive the message on turn 2 and could order "accept peace", and then player A will receive the reply on turn 3. This is annoying for players who can instantly chat with eachother, and leads to problems where a combat or other negative / competitive empire interaction could occur between turns 1 and 2 even though both players would prefer to be at peace, or player 1 doesn't know if player 2 will accept or not while issuing orders on turn 2.

That said, it might be better to just accept that problem, to avoid issues where a player can declare war on a turn after another player has ended their turn, and the complications that could create...

**Comment by o01eg** [comment]
They can both send "offer peace" to each other on turn 1 and have a peace on turn 2.

**Comment by geoffthemedio** [comment]
If it's just peace for peace, and is between humans. But if there's an AI controlling one or both empires, then there would need to be some extra communication to let each know that the other player will also be sending peace orders at the same time, so that they can match it. And if peace treaties can have other stuff attached to it, like receiving planets or techs or influence, as part of the deal, then a player can't just "offer peace" but needs to make a complete diplomatic proposal, and the other needs to see it to decide if it's acceptable.

**Comment by agrrr3** [comment]
How about adding a unilateral ceasefire order which can be used not to
attack the future partner?


Offering a complete peace package could always involve declaring unilateral
ceasefire until the other party declines or starts negotiating (a
counterproposal which also implies a ceasefire from the other party) or the
peace offer is retracted.

2018-02-19 11:54 GMT+01:00 Geoff <notifications@github.com>:

**Comment by geoffthemedio** [comment]
This is getting in-depth enough that you should probably post to the forums to discuss further.

**Comment by Vezzra** [comment]
> This is getting in-depth enough that you should probably post to the forums to discuss further.

Just wanted to second that. How to handle diplomatic messages is an important design decision which needs to be discussed on the forum.

**Comment by o01eg** [comment]
Was it implemented in https://github.com/freeorion/freeorion/pull/2457 ?

**Comment by Morlic-fo** [comment]
Looks like it. If it is playtested and works as intended, this can be closed as resolved.
