### ISSUE TITLE
Freeorion Crashes on Start

### ISSUE THREAD

**Issue by SadaleNet** [freeorion/freeorion#1779]
### Environment

* Freeorion 0.4.7.1
* Arch Linux
* Using the package from [AUR](https://aur.archlinux.org/packages/freeorion)
* Same bug occur with version [r13546.19febb8f0-1](https://aur.archlinux.org/packages/freeorion-git/)

### Description
When Freeorion is executed, it crashed with the following debug message

```
process 1676: arguments to dbus_type_is_basic() were incorrect, assertion "dbus_type_is_valid (typecode) || typecode == DBUS_TYPE_INVALID" failed in file dbus-signature.c line 322.
This is normally a bug in some application using the D-Bus library.
D-Bus not built with -rdynamic so unable to print a backtrace
Aborted (core dumped) 
```

After some quick googling, it seems that Steam also [got hit by a similar bug in the recent](https://steamcommunity.com/app/462770/discussions/2/1471967615877566184/).

### Expected Result
It shouldn't crash when it's run

### Steps to reproduce
Install the package from AUR and execute `freeorion` in terminal. It crashes.

This crash is reproduced by another user. Please refer to the [comment made by wookietreiber](https://aur.archlinux.org/packages/freeorion/).

**Comment by dbenage-cx** [comment]
Assuming you have SDL v2.0.6, as that is the latest shown on AUR packages? https://bugzilla.libsdl.org/show_bug.cgi?id=3854

**Comment by SadaleNet** [comment]
You're right. I'm using the package sdl2 of verion 2.0.6-1 from the official Arch repo.

Downgraded sdl2 to 2.0.5-4 and it works. So it isn't your bug. Closing.
