### ISSUE TITLE
Mismatch between the description and actual operation of  Empire::UnrestrictedLaneTravel()

### ISSUE THREAD

**Issue by Dilvish-fo** [freeorion/freeorion#1780]
The comments/descriptions for ```Empire::UnrestrictedLaneTravel()``` and the underlying ```m_available_system_exit_lanes``` are written up with their primary (only current) use case pattern in mind, but their implementation wound up being somewhat more specific and relied on the manner in which ```UnrestrictedLaneTravel()``` is currently always paired (either directly or indirectly) with ```Empire::SupplyUnobstructedSystems()```.  This leaves the comment/description for ```m_available_system_exit_lanes``` being perhaps a bit misleading, and the comments/description for  ```Empire::UnrestrictedLaneTravel()``` being yet more misleading.    

The point of deviation is that ```m_available_system_exit_lanes``` in fact only tracks lanes that are actually being preserved against blockade (by the presence of an empire fleet, as handled by ```Empire::UpdateSupplyUnobstructedSystems()```), ```m_available_system_exit_lanes``` does not necessarily include all the various lanes which are available simply because they are not blockaded.   The discrepancy became apparent to me as I was debugging some new AI pathfinding behavior that was at first trying to use ```UnrestrictedLaneTravel()``` without ```Empire::SupplyUnobstructedSystems()```.

There are two main approaches to rectifying this-- change the comments or change the behavior (and in the latter case there can be some notable variance in what behavior is changed).  Concurrent with this submission I am proposing two alternative PRs for discussion, one clarifying comments/descriptions and the other mostly changing behavior.  I thought the individual PRs could be focused on the best way to do their particular approach, and this Issue could be place to discuss the choice between the two.   I propose that in either case we leave the derivation of ```m_available_system_exit_lanes``` be as it is now, and simply clarify the description for it.   

Then in the first PR #1781, we simply also make similar corrections to the description for ```UnrestrictedLaneTravel()```.  This PR is my strong preference because it retains some more granularity of information that the AI could use in its pathfinding code without having to redetermine the info from ```m_available_system_exit_lanes``` (which is possible but seems to me it would clutter and bog down the AI code).  To make things even more clear, perhaps we should also consider changing the names to be ```m_preserved_system_exit_lanes``` and ```PreservedLaneTravel()```

The alternate PR, #1782  conforms the operation of ```UnrestrictedLaneTravel()``` to the current description by directly incorporating some information from ```Empire::SupplyUnobstructedSystems()```.  This would in some ways keep the ideas a little simpler, and could probably allow removing some current calls to ```Empire::SupplyUnobstructedSystems()```, but even moreso it would complicate some code for the AI.

**Comment by dbenage-cx** [comment]
Since there has been no other feedback yet: Changing the comments/variable names (1781) seems preferable strictly from a testing perspective.

**Comment by geoffthemedio** [comment]
@Dilvish-fo I think you can go whichever way you want with this... or do you prefer to wait longer?
