### ISSUE TITLE
OptionsDB::Commit() destroys options in config.xml if they have not yet been Add()ed to the OptionsDB.

### ISSUE THREAD

**Issue by mel-odious** [freeorion/freeorion#179]
I've been working on having CUIWnds remember their state between executions via the OptionsDB (see [my fork](https://github.com/mel-odious/freeorion/tree/remember-window-positions-c2)) and had a go at having windows Add() their options when they are constructed instead of at the beginning of execution (inside AddOptions()) in order to allow the default sizes to be specified at runtime (as they are now) and to avoid needing to specify the config option name again in an AddOptions() function.

The problem I'm having is that if several windows save their state to the DB, on the next execution if Commit() is called before all of them have been constructed & had their state restored that information is lost, because unregistered options in config.xml are ignored ([OptionsDB.cpp@400](https://github.com/freeorion/freeorion/blob/master/util/OptionsDB.cpp#L400)).

Of course, one way would be to make sure everything restores its state from the DB before any calls to Commit() but that has a couple of issues:
- Adding an option at runtime currently requires another read from config.xml in order to actually set the values from the file (which is fairly awkward at the moment, see mainConfigOptionsSetup() in chmain.cpp)
- It reduces flexibility - we have windows that aren't constructed as soon as FreeOrion starts (OptionsWnd, SaveFileDialog and other modal CUIWnds come to mind) and those windows would have anything they add to the DB on construction destroyed on the next execution anyway.

I have the idea of saving unrecognised options, with just their value string (not the parsed value, because we don't know its type yet).  When a new option is added, we can look up the list of unrecognised options to see if one matches and parse it then.  This would even mean that dynamically-added options would automatically have their config.xml values parsed without requiring another read.

For implementing that, I was thinking of adding a std::map<std::string, std::string> member to OptionsDB to store the un-parsed value strings which can be checked when an option is Add()ed.  Trying to Get() these options would still raise an exception, of course.  Thoughts?

**Comment by mel-odious** [comment]
Or it could be done by adding unrecognised options as std::string options with a flag that marks them as unrecognised (so Get(), Add() etc. can still behave like they don't really exist) which would simplify writing them all back to XML in alphabetical order.

**Comment by geoffthemedio** [comment]
As suggested, Options set by SetFromXMLRecursive (and perhaps SetFromCommandLine) that don't find an existing already-Added option in the DB could add a string-valued Option to the map. 

When Adding an option in code, it checks for an existing option by the same name already, and throws an exception if a duplicate is found.

Instead, it could set the value of the new Option to whatever is already set in the existing Option by taking the result of the existing Option's GetValueString() function, and attempting to lexical_cast that to whatever the newly-Added Option's type is.

No need for an extra flag, I think.

If the lexical_cast fails, then use the default value of the newly-Added Option.

**Comment by mel-odious** [comment]
That approach wouldn't allow functions such as Get(), Validate() or OptionExists() to tell the difference between options that have been registered with Add() (and therefore have the proper type info, validators, descriptions, defaults etc.) and ones that were merely found in the config or command line with no context.  I just threw up a PR with the "save as a string Option with a flag" approach [over here](https://github.com/freeorion/freeorion/pull/186) if you'd like to inspect it.  Haven't done anything with SetFromCommandLine there but it would make sense for that to behave similarly to SetFromXMLRecursive.

**Comment by geoffthemedio** [comment]
Seems reasonable
