### ISSUE TITLE
AI supply_val calculation for invasion score seems wrong

### ISSUE THREAD

**Issue by Morlic-fo** [freeorion/freeorion#1793]
Relevant piece of code:
```
    if p_sys_id in ColonisationAI.annexable_system_ids:  # TODO: extend to rings
        supply_val = 100
    elif p_sys_id in ColonisationAI.annexable_ring1:
        supply_val = 200
    elif p_sys_id in ColonisationAI.annexable_ring2:
        supply_val = 300
    elif p_sys_id in ColonisationAI.annexable_ring3:
        supply_val = 400
```
 https://github.com/freeorion/freeorion/blob/master/default/python/AI/InvasionAI.py#L437

What seems wrong to me is:
1) ```ColonisationAI.annexable_system_ids``` contains those planets that are hypothetically, in the very best scenario (best specials, tiny planet etc) able to connect to supply.
2) The supply_val gets greater the further we are from supply (but to which we can not possibly connect to).
3) The ```ColonisationAI.evaluate_planet``` already considers the supply (or is this supposed to compensate for a supply penalty there? If so, this needs to be corrected accordingly)

@Dilvish-fo : Thoughts on what is happening and what is supposed to happen?

**Comment by Dilvish-fo** [comment]
> The supply_val gets greater the further we are from supply (but to which we can not possibly connect to).

My vague recollection is that the idea was to promote expanding the suppliable area, but this code does indeed seem incomplete/broken at this point.
