### ISSUE TITLE
No tooltip breakdown on sidepanel

### ISSUE THREAD

**Issue by MatGB** [freeorion/freeorion#1800]
### Environment

* **FreeOrion Version**: ec6ad1e
* **Operating System**: Linux
  * Compiled from source

NB, I hard reset my master branch and did a fresh compile with which I'm playing.

### Description
![spectacle j30167](https://user-images.githubusercontent.com/11533206/31317245-6f14366c-ac35-11e7-84d2-766fb14c9631.png)
No breakdown of where the numbers are coming from on any planet stats in the sidepanel stats display.

### Expected Result
Breakdown of what effects bonuses and maluses are coming from should display.

### Steps to reproduce
Compile game, start, hover mouse over homeplanet stats.

NB: this problem definitely wasn't there in f5e26bc, and appeared by 96e15f7

**Comment by dbenage-cx** [comment]
f5e26bc...96e15f7 Not seeing much, do you have Effect accounting tabulation off?
(Options->Other, need to hit next turn after changing)

**Comment by MatGB** [comment]
Apparently yes I did, and I cannot recall ever touching that, although it is immediately above the new create persistent config so must have selected it in error.  So that's what that does, had no idea, thanks.

**Comment by Vezzra** [comment]
@MatGB, you can leave the labels categorizing this issue, the "invalid" label already tells that the original assessment was mistaken, no need to remove the "classification" tags.
