### ISSUE TITLE
pycompile returns error for freeOrionAIInterface.py

### ISSUE THREAD

**Issue by o01eg** [freeorion/freeorion#1804]
### Environment
* **FreeOrion Version**: d68433e
* **Operating System**: Ubuntu Server 16.04 LTS
* **Graphic card used**: -
* **Fetched as** 
  * Compiled from source

### Description
`pycompile` couldn't process `freeOrionAIInterface.py` file and returns error:
```
  File "/usr/share/games/freeorion/default/python/interface_mock/result/freeOrionAIInterface.py", line 3373
    None = None  # ruleType(1, "None")
SyntaxError: cannot assign to None
```

### Expected Result
Successfull installation.

### Steps to reproduce
* Enter to `default` directory.
* Execute `python2.7 -m compileall .`
* Issue occurs.

**Comment by o01eg** [comment]
Add test for same issues https://github.com/freeorion/freeorion/pull/1805

**Comment by Morlic-fo** [comment]
Fixed by
https://github.com/freeorion/freeorion/commit/98625c0743266d7fcf9cb70bcb23cef0e2822fa8
https://github.com/freeorion/freeorion/commit/3a0dcf40afe43fbd45d2140c6619c1fcf870f1c9
