### ISSUE TITLE
Screen goes black when joining a multiplayer game not in the 'multiplayer setup' screen

### ISSUE THREAD

**Issue by wrivas** [freeorion/freeorion#1809]
In reference to this thread : 
http://www.freeorion.org/forum/viewtopic.php?f=25&t=10733

### Environment
as described in the thread, linux, 2 systerms, nvidia and ati

### Description

when I try to join a game, all i got is a black screen.
I start the game, click multiplayer, join localhost, then the freeorion window is completely black.
it doesnt change, disk is not used, cpu is not used. it stays as is until i kill it, or until i kill the server.
(the hosting freeorion is fine and plays ok)

in the forum thread, it was suggested to have the server stay at 
the 'multiplayer setup' time until the other player has joined. it worked.

It was very very frustrating and I spent a few hours on it. other multiplayer games have more friendly experience.

### Expected Result
it should at least print "waiting server to be in 'Multiplayer Setup' screen
it should not freeze to black death.

### Steps to reproduce
try to connect to a multiplayer game when the "server" is already in game or before the multiplayer setup window.

**Comment by Vezzra** [comment]
> It was very very frustrating and I spent a few hours on it. other multiplayer games have more friendly experience.

I understand, but keep in mind that this is an open source project carried on by a few volunteers in their free time, and still in alpha. There are plenty of things that work less than optimal, or are unfinished, and only so much time we all have to deal with all what needs to be done...

**Comment by geoffthemedio** [comment]
Additionally, if it's something that has an easy workaround, it's less likely to be prioritized for fixing.

**Comment by o01eg** [comment]
Fixed in https://github.com/freeorion/freeorion/pull/1660 with commit https://github.com/freeorion/freeorion/pull/1660/commits/5fcdda86677d79d2246902af75697610787a99d2

**Comment by wrivas** [comment]
On 2017.10.12 10:03:48 EDT, Vezzra wrote:
> > It was very very frustrating and I spent a few hours on it. other multiplayer games have more friendly experience.
> 
> I understand, but keep in mind that this is an open source project carried on by a few volunteers in their free time, and still in alpha. There are plenty of things that work less than optimal, or are unfinished, and only so much time we all have to deal with all what needs to be done...


fair, just put minimal effort on it. just display a message that says cant connect to multiplayer unless 
server is in the 'multiplayer setup' window


thanks !

**Comment by wrivas** [comment]
On 2017.10.12 11:56:25 EDT, O01eg wrote:
> Fixed in https://github.com/freeorion/freeorion/pull/1660 with commit https://github.com/freeorion/freeorion/pull/1660/commits/5fcdda86677d79d2246902af75697610787a99d2
> 


nice great job thanks !

**Comment by Vezzra** [comment]
Meaning, this has already been fixed in master since weeks. Closing as resolved.
