### ISSUE TITLE
Help Output Entry Garbled / Badly Laid Out

### ISSUE THREAD

**Issue by geoffthemedio** [freeorion/freeorion#1814]
Running `freeorion -h` gives me help output, including a bit:
````
--GameSetup.specials-frequency
     The proportion of planets and systems containing Special Features.

Some
     Special Features are protected by Guardians left by Precursor speciesÔÇöonly
     setting Monster Frequency to None will prevent these appearing if the game
     contains specials.
 | Default: GALAXY_SETUP_MEDIUM
````

It would preferably not have the `ÔÇö` and not have the odd newline after `Some`.

**Comment by dbenage-cx** [comment]
Layout was reworked in #1929, this issue remains for the characters rendered in place of `-` (which I assume has different behavior across various terminals).

**Comment by geoffthemedio** [comment]
switching the character to `-` in that stringtable entry seems to resolve the issue.

https://github.com/freeorion/freeorion/commit/ffa679a22f52a7a8ed502e10cbc53bb520e3f894
