### ISSUE TITLE
Splitting ships for each design causing the entire fleet to disappear

### ISSUE THREAD

**Issue by cpeosphoros** [freeorion/freeorion#1865]
### Environment
```
$ inxi -GSx
System:    Host: chronos-18 Kernel: 4.4.0-98-generic x86_64 (64 bit gcc: 5.4.0)
           Desktop: Cinnamon 3.2.7 (Gtk 3.18.9) Distro: Linux Mint 18.1 Serena
Graphics:  Card: NVIDIA GM200 [GeForce GTX 980 Ti] bus-ID: 01:00.0
           Display Server: X.Org 1.18.4 drivers: nvidia (unloaded: fbdev,vesa,nouveau)
           Resolution: 1920x1080@60.00hz, 1680x1050@59.88hz
           GLX Renderer: GeForce GTX 980 Ti/PCIe/SSE2 GLX Version: 4.5.0 NVIDIA 384.98 Direct Rendering: Yes
```
* **FreeOrion Version**:  80e7841 
* **Fetched as**
  * Compiled from source

### Description
At turn 253, splitting ships for design causes the fleet to disappear.

It affects any fleet, no matter if it has or has not different design ships.

This is the save game (without XML compression)
[disappearing ships.sav.zip](https://github.com/freeorion/freeorion/files/1484672/disappearing.ships.sav.zip)
.

### Expected Result
Ships should not disappear...

### Steps to reproduce
* Load the game.
* Try to split any fleet.
* Issue occurs.

**Comment by wheals** [comment]
Might be worth checking if this still happens after applying the fix in #1863

**Comment by dbenage-cx** [comment]
@wheals I tried with your PR and with b6940d0 with no change.

The save file states a build from 80e7841, curious if the game is a continuation from an earlier build?

Loading the save generates a number of error logs of form:
[error] client : ObjectMap.cpp:108 : ObjectMap::FindObjects couldn't find object with id 169352713

When splitting the fleet, none of the passed ships ids are found, thus no fleets are created.

Moreover, clicking next turn for me ends up segfaulting the server, stemming from IDAllocator.cpp:312 (during deallocation? posting screenshot as the info may be easier to parse)
![fo_debug_181117_01](https://user-images.githubusercontent.com/17205519/32986903-e0745454-cca1-11e7-8964-b3aeabfd4154.png)

**Comment by cpeosphoros** [comment]
@dbenage-cx You are right, this is a build from 80e7841. Not a continuation. I always start fresh games after compiling.

**Comment by Vezzra** [comment]
That sounds quite serious (although the issue might occur only rarely), so flagging this as mandatory for the release for now.

**Comment by geoffthemedio** [comment]
I'm unable to load this save, even after attempting some code changes to work around some of the issues. My guess is that it's an issue with transition to the ID allocator. It doesn't seem to have recurred since (since noone has reported it) and isn't easily reproducible.

If it reoccurs, please repost.
