### ISSUE TITLE
Adjust AI for new Imperial Stockpile mechanic

### ISSUE THREAD

**Issue by Vezzra** [freeorion/freeorion#1879]
The AI needs some (at least) basic adjustment to be able to handle the new Imperial Stockpile mechanic before the 0.4.8 release. I've created this issue and assigned it to the "0.4.8 (mandatory)" milestone so this shows up on the list of things which need to be done before we can get 0.4.8 out.

**Comment by Morlic-fo** [comment]
#1883 does introduce some basic adjustment.

Obviously, more work can and probably will be done at some point in the future but the "release blocking" part should be covered.
