### ISSUE TITLE
AI builds outpost base at system when all planets are full.

### ISSUE THREAD

**Issue by alleryn** [freeorion/freeorion#1886]
### Environment

* **FreeOrion Version**: cbf1e48 (Nov. 26)
* **Operating System**: Windows 10 Home
* **Fetched as** 
  * Compiled from source

### Description

The AI built an outpost base at a star system where that AI owns all the planets.
![foaioutpostbase](https://user-images.githubusercontent.com/30762579/33294978-b3c1512a-d398-11e7-8459-e46fc63bd7e9.jpg)
That AI's log fille:
[AI_10.log](https://github.com/freeorion/freeorion/files/1507996/AI_10.log)
Other log files:
[AI_1.log](https://github.com/freeorion/freeorion/files/1507979/AI_1.log)
[AI_2.log](https://github.com/freeorion/freeorion/files/1507983/AI_2.log)
[AI_3.log](https://github.com/freeorion/freeorion/files/1507982/AI_3.log)
[AI_5.log](https://github.com/freeorion/freeorion/files/1507985/AI_5.log)
[AI_4.log](https://github.com/freeorion/freeorion/files/1507981/AI_4.log)
[AI_9.log](https://github.com/freeorion/freeorion/files/1507984/AI_9.log)
[freeorion.log](https://github.com/freeorion/freeorion/files/1508009/freeorion.log)
[freeoriond.log](https://github.com/freeorion/freeorion/files/1508010/freeoriond.log)

### Expected Result

AI does not build unusable Outpost Bases.

**Comment by Morlic-fo** [comment]
Do you still have the (starting) savegame so I can reproduce the issue or could you alternatively confirm if #1887 fixes the behaviour?

**Comment by alleryn** [comment]
I do still have the savegame from the start of the game, but i'm not sure how to upload it (the simple drag and drop gives me a "We don't support that file type.")

In terms of applying the fix and attempting to reproduce it myself, would that just be a matter of keeping an eye on the system in question to see if it re-occurs, or do i need to try to exactly reproduce my actions from the previous game?

**Comment by Morlic-fo** [comment]
You do not need to reproduce your actions.

It would be sufficient to just pass 10 turns and post a new log file of the relevant AI.

**Comment by alleryn** [comment]
Ok, thanks, i think i can do that.  (i am just learning git so i may do something stupid and fetch the wrong repository or something but it should be ok).

**Comment by alleryn** [comment]
Done.  Judging by the colony names, it looks like this is the relevant file, but that would mean the AI's renumbered themselves, so i'm not 100% sure this is the file you're looking for.
[AI_4.log](https://github.com/freeorion/freeorion/files/1508219/AI_4.log)

**Comment by alleryn** [comment]
Oh i should also have mentioned, this is a game that i started as a multiplayer game, saved as .mps at the start of the game, renamed via Windows to .sav, and then immediately reloaded.

I've done that a number of times before and haven't noticed it changing anything, but i was probably remiss in leaving that out.

**Comment by Morlic-fo** [comment]
Thanks for your test. Unfortunately, the issue has not been completely resolved yet. I will look into it some more in the coming days.

**Comment by alleryn** [comment]
Sorry to hear that.  Let me know if i can do any testing for you.  Good luck.

**Comment by dbenage-cx** [comment]
> the simple drag and drop gives me a "We don't support that file type."

For future reference, you can compress (zip) the save file

**Comment by alleryn** [comment]
> For future reference, you can compress (zip) the save file

Understood. Information appreciated.

**Comment by alleryn** [comment]
> so i may do something stupid and

forget to build before i test.

Unfortunately, the AI log file looks pretty similar to the last one, at least to my eye, even after building.
[AI_4.log](https://github.com/freeorion/freeorion/files/1509807/AI_4.log)
Here's the save file in case it's useful
[HumanProdResTurn1.zip](https://github.com/freeorion/freeorion/files/1509809/HumanProdResTurn1.zip)

**Comment by Morlic-fo** [comment]
Thanks for the savegame. It helped me to track down the issue.

In a nutshell, the AI colonized a planet (Lithia Beta II) with the starting colony ship but at the same time still had it flagged for orbital outposting. When the outpost base was complete, it was correctly reassigned to the remaining possible target Lithia Beta I. However, that reassignment did not happen before another outpost base was enqueued for Lithia Beta I (thinking the 1st base would still be targeting Lithia Beta II). That 2nd excessively enqueued base was never deleted from the queue.

With the updated #1887 the AI should handle situations like this correctly.

> forget to build before i test.

As long as only python scripts are edited, there is no need to recompile.

**Comment by Morlic-fo** [comment]
Should be resolved by the combination of 217d3aa, 2a1f0c7 and #1998
