### ISSUE TITLE
FTBFS: clang/boost after pull #1838

### ISSUE THREAD

**Issue by ghost** [freeorion/freeorion#1890]
Debian Linux
clang version 3.9.1-9 (tags/RELEASE_391/rc2)
boost 1.62.0.1

clang fails while building parse/ConditionParser.cpp.

[build_log.txt](https://github.com/freeorion/freeorion/files/1516606/build_log.txt)

I haven't been able to fix this one, but it appears to be a problem with a forward declared template being instantiated before it is defined.  gcc doesn't complain, so I'm guessing that it is doing lazy template processing, while clang is not.

**Comment by LGM-Doyle** [comment]
@spikethehobbitmage could you try #1911, to see if it works or at least has a different error message?

Do you know why in the log file the command line has a `-std=c++14` option at the beginning?

I've checked the gcc stdlib change log from 6.3 onward and I don't see anything significant changes. 

Could you try adding ````#include "../universe/ValueRef.h"```` to the very beginning of "ConditionParser.cpp" **before** the current first line ````#include "ConditionParserImpl.h"```` ?

**Comment by ghost** [comment]
#1911 produces an identical error message
The -std=c++14 was an attempt to get it to build when -std=c++11 wasn't working.  Changing it back to -std=c++11 makes no difference.
The include makes no difference, either.
At this point, I suspect gcc is doing lazy template initialization and clang isn't, which then trips a boost bug with forward templates.

Sorry for taking so long to reply.
