### ISSUE TITLE
No messages if Chat Timestamp is activated

### ISSUE THREAD

**Issue by Ouaz** [freeorion/freeorion#1907]
### Environment

* **FreeOrion Version**: v0.4.7+ [build 2017-12-04.25bd9a9]
* **Operating System**: Windows 7
* **Graphic card used**: Radeon HD 7670
* **Fetched as** 
  * Weekly development build

### Description

Possibly related to #1813 

If "Show chat timestamp" is activated in the game options:

· no AI messages are displayed in the Messages panel, e.g. AI greetings at Turn 1, or AI reply to peace proposal.
· typing something in the Messages text box then pressing Enter to send it, does not work.

![timestamp_on](https://user-images.githubusercontent.com/11946570/33774710-78af96bc-dc3c-11e7-9cd0-a378887fcc96.gif)

If "Show chat timestamp" is unticked, Messages panel works fine.

![timestamp_off](https://user-images.githubusercontent.com/11946570/33774715-80e27a5c-dc3c-11e7-8511-cfa9728702da.gif)

**Comment by o01eg** [comment]
I wonder if it is a locale problem with windows. Is there something in client logs?

**Comment by Ouaz** [comment]
Here's the full log if required:
[freeorion.log](https://github.com/freeorion/freeorion/files/1543330/freeorion.log)

**Comment by geoffthemedio** [comment]
I'm unable to replicate the problem. English or French stringtables work fine. I get AI chat with timestamps.

What happens if you type a chat message?

Can you attach an AI log file?

**Comment by Vezzra** [comment]
@geoffthemedio:

"component:game mechanic"? Isn't that more of an UI issue?

And do you consider this really as release blocking? I mean, it's an annoying issue, of course, but it can easily be circumvented by simply turning chat timestamps off.

Just want to check back with you before I change anything, assuming you had your reasons for categorizing the issue like this...

**Comment by geoffthemedio** [comment]
Chat messages not working is a broken game mechanic... It seems like they're not being sent, not that they aren't being displayed properly, which would be a UI issue.

Either it needs to be fixed or timestamps need to be default off and probably labelled as potentially broken...

**Comment by Vezzra** [comment]
Ok, that makes sense.

**Comment by o01eg** [comment]
Server has nothing to do with showing timestamp option. It always sends timestamp of chat message.

**Comment by geoffthemedio** [comment]
I thought it might have some interactìon in the AI scripts.

**Comment by Ouaz** [comment]
> What happens if you type a chat message?

Nothing. I type a message then send it by pressing Enter, but nothing is displayed in the messages panel.

> Can you attach an AI log file?

[AI_1_timestamp_on.log](https://github.com/freeorion/freeorion/files/1545788/AI_1_timestamp_on.log)
[AI_1_timestamp_off.log](https://github.com/freeorion/freeorion/files/1545789/AI_1_timestamp_off.log)

**Comment by geoffthemedio** [comment]
Can you turn all the human client log levels to trace and then (with timestamps on) type and send a chat message, and then post the log file?

**Comment by Ouaz** [comment]
> Can you turn all the human client log levels to trace and then (with timestamps on) type and send a chat message, and then post the log file?

[freeorion_trace_timestamp_on.log](https://github.com/freeorion/freeorion/files/1545895/freeorion_trace_timestamp_on.log) (I hope I turned to trace all the log you need ^^)

I typed and sent "test for Geoff".

```
18:55:33.242622 [trace] FSM : HumanClientFSM.cpp:971 : (HumanClientFSM) PlayingTurn.PlayerStatus
18:55:49.263539 [trace] network : ClientNetworking.cpp:435 : ClientNetworking::SendMessage() : sending message Message: PLAYER_CHAT "<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE boost_serialization>
<boost_serialization signature="serialization::archive" version="13">
<receiver>-1</receiver>
<data>test for Geoff</data>
</boost_serialization>
```

And (one of many):

```
18:55:32.958606 [trace] FSM : HumanClientFSM.cpp:639 : (HumanClientFSM) PlayingGame.DiplomaticStatusUpdate
18:55:32.990608 [trace] network : ClientNetworking.cpp:442 : ClientNetworking::GetMessage() : received message Message: PLAYER_CHAT "<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE boost_serialization>
<boost_serialization signature="serialization::archive" version="13">
<sender>2</sender>
<timestamp class_id="0" tracking_level="0" version="0">
	<ptime_date class_id="1" tracking_level="0" version="0">
		<date>20171210</date>
	</ptime_date>
	<ptime_time_duration class_id="2" tracking_level="0" version="0">
		<is_special>0</is_special>
		<time_duration_hours>17</time_duration_hours>
		<time_duration_minutes>55</time_duration_minutes>
		<time_duration_seconds>32</time_duration_seconds>
		<time_duration_fractional_seconds>0</time_duration_fractional_seconds>
	</ptime_time_duration>
</timestamp>
<data>Entirety (Beginner Mode): [[AI_FIRST_TURN_GREETING_MSG102]]</data>
</boost_serialization>
```


But nothing is displayed in the messages panel.

**Comment by geoffthemedio** [comment]
Hmm. Looks like some additional logging within the chat message display functions may be needed to isolate this.

...

Try with the next test build, or latest master (after https://github.com/freeorion/freeorion/commit/786298ccae70e663f29c8f5d229153d3e29a9721 )if you can compile. Just starting a game, turning on trace logging in the client general, and then sending a chat message with timestamps on should be enough. (Don't need to have trace logging on before that).

**Comment by Ouaz** [comment]
v0.4.7+ [build 2017-12-11.05ee54a]

[freeorion_timestamp_on_trace2.log](https://github.com/freeorion/freeorion/files/1552570/freeorion_timestamp_on_trace2.log) (client general and FSM turned to trace)

Still "test for Geoff":

```
17:57:48.548473 [trace] FSM : HumanClientFSM.cpp:603 : (HumanClientFSM) PlayingGame.PlayerChat: <?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE boost_serialization>
<boost_serialization signature="serialization::archive" version="13">
<sender>1</sender>
<timestamp class_id="0" tracking_level="0" version="0">
	<ptime_date class_id="1" tracking_level="0" version="0">
		<date>20171212</date>
	</ptime_date>
	<ptime_time_duration class_id="2" tracking_level="0" version="0">
		<is_special>0</is_special>
		<time_duration_hours>16</time_duration_hours>
		<time_duration_minutes>57</time_duration_minutes>
		<time_duration_seconds>48</time_duration_seconds>
		<time_duration_fractional_seconds>0</time_duration_fractional_seconds>
	</ptime_time_duration>
</timestamp>
<data>test for Geoff</data>
</boost_serialization>


17:57:48.548473 [trace] client : ClientUI.cpp:753 : ClientUI::FormatTimestamp(2017-Dec-12 16:57:48)
17:57:48.549473 [trace] client : ClientUI.cpp:766 : ClientUI::FormatTimestamp date formatted: [12 déc. 17:57:48] 
17:57:48.549473 [trace] client : ClientUI.cpp:753 : ClientUI::FormatTimestamp(2017-Dec-12 16:57:48)
17:57:48.550473 [trace] client : ClientUI.cpp:766 : ClientUI::FormatTimestamp date formatted: [12 déc. 17:57:48] 
17:57:48.549473 [trace] client : ChatWnd.cpp:406 : HandlePlayerChatMessage sender: Ouaz  sender empire id: 1  sender colour rgba tag: <rgba 17 147 255 255>  filtered message: test for Geoff  timestamp text: [12 déc. 17:57:48]   wrapped text: <rgba 17 147 255 255>[12 déc. 17:57:48] Ouaz: test for Geoff</rgba>
```


I set the game to english but it seems the date is still formatted in french form:

`ClientUI.cpp:766 : ClientUI::FormatTimestamp date formatted: [12 déc. 17:57:48] `

Maybe the bug comes from my system language being french?

---------

OK, I changed my system language to English (United Kingdom), and surprise!

With Timestamp on, everything is displayed correctly in the Messages panel:

![game_eng_locale_eng](https://user-images.githubusercontent.com/11946570/33898362-7761d91c-df68-11e7-99af-423d637c0074.gif)
```
18:14:16.698498 [trace] client : ClientUI.cpp:753 : ClientUI::FormatTimestamp(2017-Dec-12 17:14:16)
18:14:16.699498 [trace] client : ClientUI.cpp:766 : ClientUI::FormatTimestamp date formatted: [12 Dec 18:14:16] 
18:14:16.699498 [trace] client : ClientUI.cpp:753 : ClientUI::FormatTimestamp(2017-Dec-12 17:14:16)
18:14:16.700498 [trace] client : ClientUI.cpp:766 : ClientUI::FormatTimestamp date formatted: [12 Dec 18:14:16] 
18:14:16.699498 [trace] client : ChatWnd.cpp:406 : HandlePlayerChatMessage sender: Ouaz  sender empire id: 1  sender colour rgba tag: <rgba 17 147 255 255>  filtered message: test for geoff  timestamp text: [12 Dec 18:14:16]   wrapped text: <rgba 17 147 255 255>[12 Dec 18:14:16] Ouaz: test for geoff</rgba>
```
If I set the game to french, and the system language to english, everything works fine too:

![game_fr_locale_eng](https://user-images.githubusercontent.com/11946570/33898594-3c0015ae-df69-11e7-8472-349c58a2b76a.gif)

So, the bug occurs when the system language is set to french.

**Comment by geoffthemedio** [comment]
My guess is that when the system language is set to french, the standard library's date formatting based on the system locale uses non utf-8 characters for accented letters, which lead to the combined / wrapped message text being il-formed and thus not displayed / displayable by the text formatting code that assumes it gets utf8 input.

**Comment by o01eg** [comment]
Timestamp formats using default locale. Looks like it should get locale based on stringtables.

**Comment by dbenage-cx** [comment]
@o01eg Not sure how that would look, seems many language/region pairings would not be valid.

**Comment by geoffthemedio** [comment]
I've added some additional trace log output of timestamp generation / locale being used, and a test to not include the timestamp if it's not valid UTF-8 text. Additional testing would be helpful.

**Comment by Ouaz** [comment]
(build 2017-12-18.8ab050f)

Timestamp on, system locale FR, FO language EN

[freeorion.log](https://github.com/freeorion/freeorion/files/1576788/freeorion.log)

The messages are correctly displayed in the panel, but the timestamp are not included, due to the unvalid UTF-8 text:
```

<!DOCTYPE boost_serialization>
<boost_serialization signature="serialization::archive" version="13">
<sender>1</sender>
<timestamp class_id="0" tracking_level="0" version="0">
	<ptime_date class_id="1" tracking_level="0" version="0">
		<date>20171220</date>
	</ptime_date>
	<ptime_time_duration class_id="2" tracking_level="0" version="0">
		<is_special>0</is_special>
		<time_duration_hours>19</time_duration_hours>
		<time_duration_minutes>22</time_duration_minutes>
		<time_duration_seconds>38</time_duration_seconds>
		<time_duration_fractional_seconds>0</time_duration_fractional_seconds>
	</ptime_time_duration>
</timestamp>
<data>test for geoff</data>
</boost_serialization>


20:22:38.463329 [trace] client : ClientUI.cpp:750 : ClientUI::FormatTimestamp(2017-Dec-20 19:22:38)
20:22:38.464329 [trace] client : ClientUI.cpp:757 : ClientUI::FormatTimestamp locale: *
20:22:38.464329 [trace] client : ClientUI.cpp:765 : ClientUI::FormatTimestamp date formatted: [20 déc. 20:22:38] 
20:22:38.464329 [trace] client : ClientUI.cpp:766 : ClientUI::FormatTimestamp date valid utf8?: no
20:22:38.464329 [trace] client : ClientUI.cpp:750 : ClientUI::FormatTimestamp(2017-Dec-20 19:22:38)
20:22:38.464329 [trace] client : ClientUI.cpp:757 : ClientUI::FormatTimestamp locale: *
20:22:38.464329 [trace] client : ClientUI.cpp:765 : ClientUI::FormatTimestamp date formatted: [20 déc. 20:22:38] 
20:22:38.465329 [trace] client : ClientUI.cpp:766 : ClientUI::FormatTimestamp date valid utf8?: no
20:22:38.464329 [trace] client : ChatWnd.cpp:411 : HandlePlayerChatMessage sender: Ouaz  sender empire id: 1  sender colour rgba tag: <rgba 17 147 255 255>  filtered message: test for geoff  timestamp text: [20 déc. 20:22:38]   wrapped text: <rgba 17 147 255 255>Ouaz: test for geoff</rgba>
```

**Comment by geoffthemedio** [comment]
a marginal improvement, I suppose?

**Comment by Ouaz** [comment]
> a marginal improvement, I suppose?

For my part, I have no use of the chat timestamp (implemented mainly for multiplayer, I suppose?). But as the options is activated by default in the options, it produced the bug.

This temporary fix allows to let the timestamp activated by default for those playing with EN system locale, and to correctly display the chat messages for french players (and all players with accented letters in their locale language).

So, it's better than nothing. ^^

**Comment by Vezzra** [comment]
@geoffthemedio, @Ouaz, while the issue certainly hasn't been actually fixed, do you at least consider it sufficiently, well, alleviated, so we can reassign this to optional instead of keeping it mandatory?

**Comment by Ouaz** [comment]
> so we can reassign this to optional instead of keeping it mandatory?

Sure, I do not see any objection.

**Comment by Ouaz** [comment]
**v0.4.7+ [build 2018-01-29.13902ea]** 

![timestamp_fr_ok](https://user-images.githubusercontent.com/11946570/35746312-af244996-0846-11e8-83ac-20e37ea47bce.PNG)

The timestamp is correctly displayed, although the February month has an accented letter in French (février) and the OS locale is set to french.

```
18:19:18.046030 [trace] client : ClientUI.cpp:753 : ClientUI::FormatTimestamp(2018-Feb-02 17:19:17)
18:19:18.047030 [info] client : i18n.cpp:116 : Global locale: fr_FR.UTF-8
18:19:18.073031 [trace] client : i18n.cpp:132 : Requested (default) locale returning fr_FR.UTF-8
18:19:18.073031 [trace] client : ClientUI.cpp:759 : ClientUI::FormatTimestamp locale: *
18:19:18.073031 [trace] client : ClientUI.cpp:766 : ClientUI::FormatTimestamp date formatted: [02 févr. 18:19:17]  Valid utf8?: yes
[...]
18:19:28.532630 [trace] client : ClientUI.cpp:753 : ClientUI::FormatTimestamp(2018-Feb-02 17:19:28)
18:19:28.532630 [trace] client : ClientUI.cpp:759 : ClientUI::FormatTimestamp locale: *
18:19:28.532630 [trace] client : ClientUI.cpp:766 : ClientUI::FormatTimestamp date formatted: [02 févr. 18:19:28]  Valid utf8?: yes
18:19:28.532630 [trace] client : ChatWnd.cpp:411 : HandlePlayerChatMessage sender: Ouaz  sender empire id: 1  sender colour rgba tag: <rgba 17 147 255 255>  filtered message: test for geoff  timestamp text: [02 févr. 18:19:28]   wrapped text: <rgba 17 147 255 255>[02 févr. 18:19:28] Ouaz: test for geoff</rgba>
```

I notice there is two new lines:

```
18:19:18.047030 [info] client : i18n.cpp:116 : Global locale: fr_FR.UTF-8
18:19:18.073031 [trace] client : i18n.cpp:132 : Requested (default) locale returning fr_FR.UTF-8
```

It seems #1918 by dbenage-cx works as intended. IMO, this issue can be marked as resolved.
