### ISSUE TITLE
Remove IDAllocator legacy save conversion code at the v0.4.8 transistion.

### ISSUE THREAD

**Issue by LGM-Doyle** [freeorion/freeorion#1909]
`IDAllocator` includes code to convert legacy saved games.  It allows incorrectly configured orders to be processed by the server with only a warning, assuming that they are from a legacy save.  This code should be removed at the v0.4.8 transition which will be a hard save game compatibility break.

This change will prevent loading development saved games prior to July 2017 after the change.  It is unlikely that saved games that old would load in any case.

Location requiring a change are:
https://github.com/freeorion/freeorion/blob/master/universe/IDAllocator.h#L35
https://github.com/freeorion/freeorion/blob/master/universe/Universe.cpp#L398
https://github.com/freeorion/freeorion/blob/master/universe/Universe.cpp#L426
https://github.com/freeorion/freeorion/blob/master/universe/Universe.cpp#L438
https://github.com/freeorion/freeorion/blob/master/universe/Universe.cpp#L454

**Comment by Vezzra** [comment]
I wouldn't worry too much about breaking savegame compatibility.

We can't really maintain that anyway, and accumulating savegame compatibility ensuring code for which it's only a matter of time before becomes pointless will only result in a lot of pointless code laying around.

So, IMO, go ahead and good riddance to that code. 😉

**Comment by Vezzra** [comment]
As we are (slowly) trying to wrap up things for 0.4.8, can someone take care of this? I really want to cut down the list of mandatory things for the release. @LGM-Doyle? Or anyone else...
