### ISSUE TITLE
Flatpak for FreeOrion on Linux

### ISSUE THREAD

**Issue by Siosm** [freeorion/freeorion#1914]
I created a [Flatpak](https://flatpak.org/) for FreeOrion. You can try it on Linux with the following commands:
```
$ wget https://siosm.fr/flatpaks/key.gpg
$ flatpak --user remote-add --gpg-import key.gpg org.freeorion.FreeOrion https://siosm.fr/flatpaks/org.freeorion.FreeOrion
$ flatpak --user install org.freeorion.FreeOrion org.freeorion.FreeOrion
```

This version is temporarily hosted on my personal server but if I/you/we submit it for inclusion into [FlatHub](https://flathub.org/), it would be hosted there with [all the other apps](https://flathub.org/apps.html).

The Flatpak related sources are temporarily hosted here: https://github.com/Siosm/org.freeorion.FreeOrion.

(Related issue: #1236)

**Comment by Vezzra** [comment]
@Siosm, [what I said](https://github.com/freeorion/freeorion/issues/1236#issuecomment-275917165) in the comment section of #1236 also applies here.

As nice as it would to have it, I/we don't have the resources/manpower to maintain AppImage, Flatpak, Snap or whatever packages. However, if you (or someone else) volunteer to take over that task, that would certainly be very welcome.

A submission to a platform like FlatHub would require someone dedicated to maintain a FreeOrion flatpak package and handle all the FlatHub stuff. If you're willing to do that, feel free to go ahead... 😃

**Comment by Siosm** [comment]
OK. I'll try to push it to FlatHub if I find the time. Thanks.

**Comment by Siosm** [comment]
Now available at https://flathub.org/apps/details/org.freeorion.FreeOrion. Closing.
