### ISSUE TITLE
Homeworld population bonus appears as Unknown

### ISSUE THREAD

**Issue by alleryn** [freeorion/freeorion#1920]
Forum thread: http://www.freeorion.org/forum/viewtopic.php?f=25&t=10819&p=91005#p91005

### Environment
* **FreeOrion Version**: 110ba9f - 33c6468
* **Operating System**: Windows 10 Home
* **Fetched as**
  * Compiled from source

### Description
Starting in 110ba9f (Make Universe:: ResetUniverse() and Clear() into single function.), hovering over the population on a planet now displays the "Homeworld" bonus as "Unknown" and the bonus disappears entirely upon loading a saved game.  Was working in the previous commit b1ab67a.

Logs, save, and screenshot available in forum thread (link at top of this post).

### Expected Result
Hovering should list the HOMEWORLD_BONUS_POPULATION as "Homeworld" and not as "Unkown".  The bonus should remain present after loading a saved game.

### Steps to reproduce
* Start a single player game.
* Hover over the human player's homeworld's population.
* Note that the last entry is "Unknown +<(2*Planetsize)>" (e.g. "Unknown +8.00 for a large homeworld")
* Save, or allow the game to autosave by advancing to the next turn.
* Load the save.
* Advance a turn.
* Hover over the human player's homeworld's population.
* Note that the homeworld population bonus has disappeared.

**Comment by dbenage-cx** [comment]
@alleryn TY for finding the related commit!

Confirmed on linux with recent master (may require next turn after load)

**Comment by alleryn** [comment]
> may require next turn after load

Oops, thanks i skipped a step.  Edited that in above.

**Comment by Vezzra** [comment]
@LGM-Doyle, that's one of your changes. I know you'll be gone tomorrow already, so you most likely won't have time to look into or even fix this before you go. But if there is any chance you could at least give it a quick glance and some pointers as to what might be the cause, that could help someone else working on it in the meantime...

**Comment by alleryn** [comment]
Fixed in ba69006
