### ISSUE TITLE
max fps setting not saved in config file

### ISSUE THREAD

**Issue by Ouaz** [freeorion/freeorion#1924]
### Environment

* **FreeOrion Version**: v0.4.7+ [build 2017-12-18.8ab050f] MSVC 2015
* **Operating System**: Windows 7
* **Graphic card used**: Intel HD 3000
* **Fetched as** 
  * Weekly development build

### Description

Max FPS setting not saved between game sessions (even if enabled; on by default). Revert to 60 each time the game is launched:

```
<video>
    <fps>
      <max>60
        <enabled>1</enabled>
      </max>
      <shown>1</shown>
      <unfocused>15
        <enabled>1</enabled>
      </unfocused>
    </fps>
```

`limit-fps` has been replaced by `video.fps.max.enabled` in the config file ([commit here](https://github.com/freeorion/freeorion/commit/7146fd69b847d92892c294e9b5411b197ec069a9#diff-a5796f8dbcd77fd2fdc025498f029467)) but has disappeared from the game options (checkbox), although modified in the same commit.

![limit_fps_absent](https://user-images.githubusercontent.com/11946570/34227445-6512044c-e5cd-11e7-9d58-fa2c8585d84a.png)

### Expected Result

If enabled, Max FPS should be saved between game sessions. "Limit FPS" (or Enable FPS Limit) should be back to game options as a checkbox.

### Steps to reproduce

Launch FO, go to Options, set Max FPS to 30, apply, start a game (optional), quit.
Re-launch FO, go to Options, Max FPS setting has been reverted to 60.

Same behaviour by modifying manually the config file prior to launch FO.

**Comment by dbenage-cx** [comment]
@Ouaz Thank you for report, looks like OptionsDB may be confused by the nested `enabled` flag when fetching value of `max`.

As a temporary workaround either pass as command line option (`--video.fps.max 30`) or add to persistent_config.xml without specifying `enabled`:
```
<video>
    <fps>
      <max>30</max>
    </fps>
</video>
```

The UI control for this option was commented out in 0e87e37. One argument for retaining removal for now might be assisting display of the `Apply` button, at least until that button is addressed in some manner.

Option descriptions are also used for `--help` output, so `OPTIONS_DB_LIMIT_FPS` is still utilized even if not shown in UI. That is not to say the descriptions could not be improved.
