### ISSUE TITLE
Failed to colonize planets within a system

### ISSUE THREAD

**Issue by EnLightning** [freeorion/freeorion#1937]
### Environment

* **FreeOrion Version**:
v0.4.7+[build 2018-01-02.8092012] MSVC 2015
* **Operating System**:
Windows 7 Pro
* **Graphic card used**: 
NVIDIA GeForce 940MX
* **Fetched as**
  * Weekly development build

### Description
Try to place some outpost bases on uncolonized planets within a system, but failed.

### Expected Result
The planets shall be colonized.

### Steps to reproduce
* First step.
Load [172.zip](https://github.com/freeorion/freeorion/files/1617267/172.zip), select system "Situla beta".
* Second step.
"Place Outpost" on the 4 uncolonized planets.
* Third step.
Go next turn, the 4 planets are not colonized.
* Fourth step.
Repeat step 2 and 3, the planets still can not be colonized.

**Comment by geoffthemedio** [comment]
Do you have current visibility of the planets? If not there should be scanlines over the planet image and if you mouse over the scanlinea it ahould ahow a tooltip indicating when you last could detect it.

**Comment by EnLightning** [comment]
Yes, I have the visibility, no scanline at all. You can try my save file in case I missed something.

**Comment by dbenage-cx** [comment]
Can reproduce on Situla beta, even with newly designed outpost ships.

Moving an armed ship to system initiates combat (with no opponent, and not prior to moving armed there).  Checking logs, opponent fleet 41240 is reported in system, fleet with that ID is not actually there:
```
OBJ_FLEET 41240:   at: Grue α owner: Possession created on turn: 149 specials:   Meters: METER_STEALTH: Cur: 2000 Init: 2000   agressive cur system: 2799 moving to: -1 prev system: -1 next system: -1 arrival lane: 2799 ships: 30562
```

Moving ships to Grue alpha and destroying that fleet allows colonization of Situla beta.

(EDIT: Note, need to use build from 8092012 for save game, later builds are not compatible)

**Comment by dbenage-cx** [comment]
Potentially related to #1794

**Comment by Vezzra** [comment]
@EnLightning, @dbenage-cx, #1794 has been closed as resolved, is this issue here fixed now too? Can we close it, or are further fixes necessary?

**Comment by EnLightning** [comment]
@Vezzra Seems fixed with in the latest build.

**Comment by Vezzra** [comment]
Thanks for reporting back (here and in #1938).
