### ISSUE TITLE
Invisible foreign fleet at a player's fully owned system

### ISSUE THREAD

**Issue by EnLightning** [freeorion/freeorion#1938]
### Environment
* **FreeOrion Version**:
v0.4.7+[build 2018-01-02.8092012] MSVC 2015
* **Operating System**:
Windows 7 Pro
* **Graphic card used**: 
NVIDIA GeForce 940MX
* **Fetched as**
  * Weekly development build

### Description
In this game, all of AI Pact's systems were conquered by the player, and all roaming fleets were destroyed, yet this AI was not defeated. Pedia indicated there's a foreign fleet at a system full taken by the player, but the fleet remains invisible and prevent the player to defeat the AI.

### Expected Result
There shall not be undetectable ghost ships.

### Steps to reproduce
* First step.
Load [193.zip](https://github.com/freeorion/freeorion/files/1617377/193.zip)

* Second step.
Open Empires dialog, right click on AI "Pact", select "Pedia Lookup Pact"

* Third step
At the end of the Pedia of Pact, it's indicated: "Owned Fleets: Foreign fleet at Beaivi alpha".

* Fourth step.
This system was once owned by Pact, but fully taken by player, checked the system, no visible fleet.
![ghost ships](https://user-images.githubusercontent.com/86997/34754015-3785a9e8-f5b3-11e7-98b3-8af408519d36.png)

**Comment by dbenage-cx** [comment]
Potentially related to #1794

**Comment by Vezzra** [comment]
@EnLightning, @dbenage-cx, #1794 has been closed as resolved, is this issue here fixed too? Can we close it, or are further fixes needed?

**Comment by EnLightning** [comment]
@Vezzra Tried latest build, seems fixed. Please close it.
