### ISSUE TITLE
Debug build assert - MeterToResource(METER_STOCKPILE)

### ISSUE THREAD

**Issue by dbenage-cx** [freeorion/freeorion#1942]
### Environment
* **FreeOrion Version**: 0.4.7+ a3882b07

### Description
Running game from debug build aborts with message:
`freeorion: freeorion/universe/Enums.cpp:48: ResourceType MeterToResource(MeterType): Assertion '0' failed.`

This stems from a call to MeterToResource(METER_STOCKPILE) at [UI/SidePanel.cpp:3315](https://github.com/freeorion/freeorion/blob/master/UI/SidePanel.cpp#L3315).  Not certain if a RE_STOCKPILE is appropriate, some special casing for the tooltip, or a different tooltip.

Running the game in Release mode may not have the intended system resource tooltip.

**Comment by geoffthemedio** [comment]
I added `RE_STOCKPILE`. Also not sure if it was appropriate, but it seemed the easiest solution for now. Could probably just get rid of the resource types entirely, actually...

https://github.com/freeorion/freeorion/commit/529f1daa4dc2482ec29a929dfd399787b549c6f5
