### ISSUE TITLE
Segfault when giving fleet move order

### ISSUE THREAD

**Issue by dbenage-cx** [freeorion/freeorion#1951]
### Environment
* **FreeOrion Version**: 0.4.7+ e01e822
* **Operating System**: Fedora 26

### Description
Ordering fleets to move causes segfault within first few orders given.

git bisect points to [this change](https://github.com/freeorion/freeorion/commit/e01e822b9f23a0183cd30eea916fe360dff18389#diff-3f45e80ad24499b79318a462ed3cf4e0R1571) for m_fleet_connection (from boost::bind to lambda).

[gdb.log](https://github.com/freeorion/freeorion/files/1648641/gdb.log)

While a simple working fix is to revert that one line, I'm opening issue as this seemed to indicate some other potential problems with this change set not yet realized (wrt GG::Control/Wnd).

### Steps to reproduce
* Start new game
* Order starting fleets to move to another system, selecting either by clicking on map fleet icon or using hotkey.
* Segfault between second and forth fleet ordered to move.

**Comment by adrianbroher** [comment]
Reproducible for me.

**Comment by adrianbroher** [comment]
No easy fix here, reverting until I have a better solution.

**Comment by adrianbroher** [comment]
Reverted with:
* 2327397348641155cb1e6b4ce835118d6dc610b6
* 9e4f3ce0bbaa00a5bce0a5ddbda0226adf905626
