### ISSUE TITLE
Experimentor Pedia: "ERROR: ULTIMATE_STOCKPILE_STOCKPILE_DESC"

### ISSUE THREAD

**Issue by EnLightning** [freeorion/freeorion#1964]
### Environment
* **FreeOrion Version**:
v0.4.7+[build 2018-01-29.13902ea] MSVC 2015
* **Operating System**:
Windows 7 Pro
* **Graphic card used**: 
NVIDIA GeForce 940MX
* **Fetched as**
  * Weekly development build

### Description
The string ULTIMATE_STOCKPILE_STOCKPILE_DESC is missed in Experimentor's Pedia

![experimentor_stockpile_desc](https://user-images.githubusercontent.com/86997/35704601-073082f6-07db-11e8-8cdb-46438ac680df.png)

### Expected Result
Shall not show this error msg

**Comment by Ouaz** [comment]
Fixed with ad1374b
