### ISSUE TITLE
auto-advance-n-turns is broken

### ISSUE THREAD

**Issue by agrrr3** [freeorion/freeorion#1974]
### Environment
* **FreeOrion Version**: current master
* **Operating System**: debian stretch, according to dilvish also on windows
* **Fetched as** 
  * Compiled from source

### Description
Auto-advance  doesnt really work for me, freeorion starts, but the turns are not advanced
> ./freeorion --setup.player.name ophiuchus --quickstart --auto-advance-n-turns 10

### Steps to reproduce
start freeorion with the parameter
> ./freeorion --quickstart --auto-advance-n-turns 10

**Comment by dbenage-cx** [comment]
Fixed by c0924fb
