### ISSUE TITLE
error parsing rich text tags

### ISSUE THREAD

**Issue by Dilvish-fo** [freeorion/freeorion#2005]
For a week or two I have sometimes been getting malformed pedia pages from some techs, and for a while for most species.  I wasn't playing with a totally plain vanilla build though so held off on reporting an issue.  Now, though, I am sure this must be an issue in the master branch.  I do not seem to be getting the errors for species' pages any more though.  But below is what I get on the pedia page for Planetary Barrier Shield I.

```
Error parsing rich text tags: expected end tag:CurrentTurn got: "

<tech LRN_FORC..."
```
and here is that for Planetary Barrier Shield II:

```
Error parsing rich text tags: expected end tag:CurrentTurn got: "

<tech DEF_PLAN..."
```
The title bar for these pages is fine, it's just the page body that is bad.

**Comment by dbenage-cx** [comment]
Looks like this requires the "auto-generated effects description" option enabled to reproduce (`resource.effects.description.shown`).

**Comment by Dilvish-fo** [comment]
Great!  Thanks for figuring that out so quickly.
