### ISSUE TITLE
over-greedy fleetbutton

### ISSUE THREAD

**Issue by Dilvish-fo** [freeorion/freeorion#2025]
[reported on the forums by UrshMost here](http://www.freeorion.org/forum/viewtopic.php?f=28&t=10896&p=91804#p91804) 

He is experiencing fleetbuttons being over-greedy and including fleets whose path tracer shows them clearly located at substantially different positions along the starlane, as shown in these pics:

![image](https://user-images.githubusercontent.com/10995939/36825893-bb0770da-1cbe-11e8-9673-d1044bbd1205.png)

![image](https://user-images.githubusercontent.com/10995939/36825900-c9643d8e-1cbe-11e8-9b63-a2fb3c9c2ed2.png)

Here is a savegame that goes with the second image.: 
[ship_icon_issue.zip](https://github.com/freeorion/freeorion/files/1769712/ship_icon_issue.zip)
I forgot to ask him the version he is running, but I can replicate on recent master e97989efa32dfc0afb1acfd44980c7f573c33f6e.  I tried out this savefile, it is from the turn before the issue appears.  The fleets that wind up grouped are heading in opposite directions and are no where near close enough on the starlane that they actually should share the same fleetbutton.  The shared fleetbutton is at the correct location for one of the fleets, and at least several fleetbutton diameters away from where the second fleet is actually located.

I'm a bit on the fence about whether this is serious enough to say mandatory for 0.4.8, so I'm putting as optional for now (and think it likely it will get fixed before the distinction matters).

**Comment by Vezzra** [comment]
Escalated this to mandatory for the release, as it's a quite glaring UI issue I don't think we want in 0.4.8.

**Comment by Dilvish-fo** [comment]
I'll go ahead and mention here a related issue that I'm hoping we can also clear up-- that the mid-starlane fleetbuttons will aggregate fleets heading in opposite directions.  I see three possible solutions.  

One (my initial preference) might be to have the fleets heading in opposite directions be selectable by cycling via multiple clicks on the fleetbutton, akin to how I understand it to work now for when there are multiple empires represented at the fleetbutton location.

Another might be to make two different fleetbuttons in such cases, slightly separated enough for separate clicking.  Or a third (well, I am feeling pretty yech about this idea but I'll mention it) could maybe perhaps to do some direction-based grouping of the fleets in the fleetwindow.

**Comment by geoffthemedio** [comment]
This problem is partly related to sorting the start/end points of fleets moving on a lane when determining the return value of `IsMovingOnStarlane`. The return value is used here:
https://github.com/freeorion/freeorion/blob/master/UI/MapWnd.cpp#L5028
to sort fleets when determining which to group together and create a single button for. Fleets moving in opposite directions on a lane are grouped into a single button, and fleets moving on a lane are grouped without considering their position in space (other than that they are on the same lane). The grouped fleets are all put into a single `FleetButton`.

Just avoiding the sorting of start/endpoint ids when storing the clusters of fleets results in separate buttons in each direction, but clicking one of them does nothing. I'd expect it to also still group together all fleets on a lane moving in the same direction.

Sorting by fleet position before creating the buttons produces multiple buttons on the lane, but clicking any opens a FleetWnd for just one of the buttons (I think... possibly this also happened with the per-direction sorting in the previous paragraph).

**Comment by geoffthemedio** [comment]
Made some adjustments in https://github.com/freeorion/freeorion/commit/b21325cc8e46ef89402f4300e1e900e8b3d7f288 that seem to help.

**Comment by Dilvish-fo** [comment]
Hmm, well I guess that commit does help at least some aspects of the current fleetbutton/FleetWnd troubles, but it also seems to add at least a couple (and then leaves some in place), so I think we are in agreement that more work is needed.  

The first new problem that I have seen in my limited testing so far is that if I have multiple fleetbuttons on the same starlane, and click one of them, both fleets will be shown in the FleetWnd and it will select both the fleet and the fleetbutton for the first fleet listed, even if I had clicked the other fleetbutton.

The other new problem I saw is that if I have several fleets at rest in a system, and then give one travel orders, all of the fleets are still listed in the same FleetWnd (and it stays that way if I close the wnd and then try to just select the stationary fleet).  Being able to click on the stationary button and have only the stationary fleets listed is a pretty important organizational characteristic.

I'll see if I can find time for poking around with some changes also, after I take care of some AI work.

**Comment by geoffthemedio** [comment]
Try clicking the moving fleet button repeatedly. It should cycle through the fleets in the window. I thought I'd posted a comment asking about this, but I don't see it now. (Edit: was here: https://github.com/freeorion/freeorion/issues/2075 /Edit)

The question was whether it should cycle through all fleets in the window, or just those represented by a button, when a button is clicked. I'm inclined to just cycle through those in a button when that button is clicked. Edit: https://github.com/freeorion/freeorion/commit/7364d18de0171d9a2e96fa12f47d0ad04dff03a7 /Edit

It's always shown all the fleets in a system, regardless of whether they are stationary or fixed... I don't consider that a bug, unless I don't understand what you're describing.

**Comment by Dilvish-fo** [comment]
> I'm inclined to just cycle through those in a button when that button is clicked.  Edit: 7364d18 /Edit

Thanks, and I agree about your preference for the cycling (which I guess puts it back to how things used to be, at least for stationary vs moving).  I haven't had a chance to test that yet, but it sounds like a good fix.

> It's always shown all the fleets in a system, regardless of whether they are stationary or fixed... I don't consider that a bug, unless I don't understand what you're describing.

Right, I guess it was really just the cycling behavior that was off, and I then somewhat misinterpreted/misremembered the conflict with my past usage pattern.

**Comment by geoffthemedio** [comment]
Fixed, I think...

@Dilvish-fo ?

**Comment by Dilvish-fo** [comment]
Moved to #2094 

~~The primary original problem does seem fixed; I just encountered a closely related problem though, in which fleets share the same fleetwnd even though their fleet buttons are no where near overlapping.~~

~~In the screenshot below, on the first turn I had sent three of the starting fleets to a neighboring system one turn away, and sent one of the scouts to a system two jumps away.  At turn 2, all 4 fleets are still shown together in the fleet window even though the one scout fleet is fairly distant from the other fleets.~~

![wrongly_grouped_fleets](https://user-images.githubusercontent.com/10995939/39793271-99a04e46-52f9-11e8-9fc6-00912fb50ea4.png)

**Comment by Dilvish-fo** [comment]
Upon clicking either of the fleetbuttons, the fleetwnd does reset to only show the fleet(s) for the clicked fleetbutton, so that's good.  My recollection though is that in the past, if their travel separated them then the fleetwnd would automatically update so they no longer appeared there together (and I also seem to recall seeing code comments indicating that was intended to still be the case).

**Comment by Dilvish-fo** [comment]
OK, done.

**Comment by Vezzra** [comment]
Thx!
