### ISSUE TITLE
Focus changes taking an extra turn to get benefit

### ISSUE THREAD

**Issue by Dilvish-fo** [freeorion/freeorion#2027]
But the focus change malus kicks in right away.  

It used to be that if you changed focus on a planet you'd immediately see the appropriate change to expected next turn meter values, and on the next turn you'd get the expected benefit of the new focus.  There now seems to be an extra turn delay in getting the benefit.

The first couple turns my planet had been on Industry, on turn 3 the industry meter was maxed to 14.7 and the research meter was at its min of 5.  I changed focus to research and to turn 4, and was surprised to notice my research still being at 5, although the industry had dropped by one point.  Continuing to advance turns did result in research rising to 6 on turn 5, 7 on turn 6, etc.

I reloaded turn 4, and changed the focus back to industry for the below screenshot.  Notice that it still predicts industry to lose a point next turn even though it properly shows the target industry being above the current level.

![image](https://user-images.githubusercontent.com/10995939/36930859-2daf2b5e-1e5f-11e8-89dd-c9c6a12a4cdf.png)

Advancing to turn 5, we see that the industry really did drop to 12.7 even though the target meter is higher.  The research meter however remained at its min of 5, as would normally be expected.

![image](https://user-images.githubusercontent.com/10995939/36931005-246d997e-1e62-11e8-94b8-ad18cc7fae1b.png)

Please excuse that the version this was done on is not quite fully clean master, but recompiling is taking me a very long time these days; this version is based on recent master d84474be6a98db42eadb87cca1690b9983053a84 plus PR 2023 and a handful of other commits which should not be affecting the meters; I am pretty confident the problem does indeed lie with master.  If someone with clean master available could test and confirm that it would be appreciated.

Attached is my save file, I am pretty sure it should still be compatible with master.
[focus_change.zip](https://github.com/freeorion/freeorion/files/1777139/focus_change.zip)

**Comment by geoffthemedio** [comment]
My guess is that after recent parser changes, it's ignoring / throwing away cases where an expression in the script is wrapped in `Value(...)` to indicate that it should return the current rather than the immediate value. eg here:

https://github.com/freeorion/freeorion/blob/master/parse/ValueRefParser.h#L171

**Comment by geoffthemedio** [comment]
Fixed? https://github.com/freeorion/freeorion/commit/c335a908b1bacee5aaef3960fe732f8da0fe562f

**Comment by Dilvish-fo** [comment]
Yes, thanks.
