### ISSUE TITLE
delays in supply connection

### ISSUE THREAD

**Issue by Dilvish-fo** [freeorion/freeorion#2028]
I outposted a medium planet that was one jump out of supply.  In the past, my recollection is that it would have been supply connected on the turn the outpost was established (outposts with a positive supply target would have their supply meter at 1 on their first turn).  Now, it is getting delayed until a full _two_ turns after that.  On the first turn the supply meter has a value of zero, and on the second turn the supply meter has gone up to 1 but the planet is still not supply connected (shown below).  It is not until the next turn after that until the planet actually gets supply connected.

![image](https://user-images.githubusercontent.com/10995939/36941947-4a592512-1f1c-11e8-923a-23031885e6ae.png)

**Comment by geoffthemedio** [comment]
Probably the same or related issue as https://github.com/freeorion/freeorion/issues/2027

**Comment by Dilvish-fo** [comment]
Also fixed along with 2027.

**Comment by Dilvish-fo** [comment]
Turns out the situation was a little more strange/complex. When I tested this and closed above, I must have just tested on an existing problem savegame I had.  But I am seeing now that the problem can still arise in a game, but then is apparently repaired upon reload.  That would tend to suggest a client-side problem, though it's still not coming to mind how that could really come to be.  

Note the first screenshot below, on the turn Woz Alpha was outposted (and I enqueued at the top of my build queue a exobot colony for it), the game is treating it as not supply connected (both for map starlane display and for deciding whether its build item gets any PP), even the debug data dump shows that its supply meter is init 1 current 1 (and so it should be connected).

Upon reloading the savegame, though, the problem is resolved, as shown in the second screenshot below.  The problem is repeatable, however, by loading the game from the turn right before the outposting gets executed.
![faulty_supply_connection](https://user-images.githubusercontent.com/10995939/37675820-80d76c9c-2c33-11e8-9de5-ea5d1f05825e.png)
![supply_connection_repaired_upon_reload](https://user-images.githubusercontent.com/10995939/37675835-8899b2b4-2c33-11e8-8313-089bf04ae1b1.png)

[__supply_connection_problem_Woz_alpha_next_turn.zip](https://github.com/freeorion/freeorion/files/1830699/__supply_connection_problem_Woz_alpha_next_turn.zip)

**Comment by geoffthemedio** [comment]
maybe there just needs to be an extra supply update on the server?

**Comment by geoffthemedio** [comment]
Maybe fixed by https://github.com/freeorion/freeorion/commit/2146fa338890ab73e42c5e1d2f89b62d352d7946

**Comment by Dilvish-fo** [comment]
That does seem to have helped, but not quite fully fixed the problem.  The screenshot below is from the same turn that a planet was outposted.  Before the commit you link above, the newly outposted planet would not have any supply lines extending from it at all, so this is progress.  But it really should have the thicker "core" supply lines connecting it to the rest of the core network, and the production queue should show the just-enqueued human colony building as getting assigned PP.  I'll try to get some more time in on debugging this one also.
![supply_linkage_incomplete](https://user-images.githubusercontent.com/10995939/39536679-2da97864-4dec-11e8-8e6d-3730ca3049c0.png)
