### ISSUE TITLE
Missing sensor ghost after combat

### ISSUE THREAD

**Issue by Oberlus** [freeorion/freeorion#2033]
### Environment
* **FreeOrion Version**: compiled from master (several versions between 2018-02-28 and 2018-03-06).
* **Operating System**: Ubuntu 16.04
* **Graphic card used**: GeForce GTX 860M
* **Fetched as** 
  * Compiled from source

### Description
A ship (scout) arrives to a unexplored system, combat ensues, the scout is killed, in the combat report you can see it was a Frigate Ms (standard initial ship) who killed the scout, but there is no sensor ghost in the system after the combat.

### Expected Result
There should be a sensor ghost for the enemy Frigate Ms ship.
 
### Steps to reproduce
* First step: load saved game "FreeOrion_Human_Player_Terran_0021_2018-Mar-02 19:17:59.107408.sav"
* Second step: do next turn.
* Issue occurs: scout Wezen arrives to system Ankh, combat ensues and no sensor ghost appears after combat.

[miss_ghost_sensor_after_combat_at_end_turn_21.zip](https://github.com/freeorion/freeorion/files/1784130/miss_ghost_sensor_after_combat_at_end_turn_21.zip)

**Comment by Dilvish-fo** [comment]
I'm marking this as optional for 0.4.8, but it is something I am looking at and very much do hope to get resolved.
