### ISSUE TITLE
BT_STOCKPILE needs encyclopedia entry

### ISSUE THREAD

**Issue by agrrr3** [freeorion/freeorion#2040]
UI/BuildDesignatorWnd.cpp uses EncyclopediaDetailPanel:SetText, but it should have a proper article, not a SetText call that probably will cause problems with other pedia functions.

 m_build_selector->DisplayStockpileProjectSignal.connect(boost::bind(static_cast<void (EncyclopediaDetailPanel::*)(const std::string&, bool)>(&EncyclopediaDetailPanel::SetText), m_enc_detail_panel, "PROJECT_BT_STOCKPILE_DESC", true));

**Comment by geoffthemedio** [comment]
Resolved by https://github.com/freeorion/freeorion/commit/871efafe2b1b8cbfb20b73cd9bbdd285d747fcdd
