### ISSUE TITLE
Buggy client-side prediction of supply meter on a enemy outpost

### ISSUE THREAD

**Issue by Oberlus** [freeorion/freeorion#2064]
### Environment
* **FreeOrion Version**: build 2018-04-02.02f4a84
* **Operating System**: Ubuntu 16.04
* **Fetched as**
  * Compiled from source

### Description
Supply meter of enemy outposted planet does not make a correct prediction of next turn value. It fails to recognise the small planet supply bonus (shows Unknown instead). This undesired effect is solved if the homeworld of the enemy empire is scouted.

### Expected Result
Supply meter should show a correct +2 Predicted Next Turn value.

Dilvish wrote: "the "Unknown +1.00" comes from the small planet supply adjustment (which in turn is specified in SHP_GAL_EXPLO.focs.txt). It's strange that the client can know the source of the Orbital Construction bonus but not know the SHP_GAL_EXPLO bonus-- it's not like the client does not know it's a small planet. And then if I either (i) research sensors and park a scout near their Capital, or (ii) build a supertesters takeover at your Capital to get the detection boost, then all of a sudden my client realizes that this extra +1 is from the SHP_GAL_EXPLO small planet adjustment. It should not normally take visibility of the enemy Capital in order for the client to properly process their techs (as it did not for their Orbital Construction tech)."

Further discussion in this thread of the forum: http://www.freeorion.org/forum/viewtopic.php?f=28&t=10930

### Steps to reproduce
* Load attached save game and check supply meter of enemy planet Rin alpha IV.

![sly_nice_supply_68](https://user-images.githubusercontent.com/28650914/38380204-5312d3fa-3903-11e8-9077-c7af13a02cea.png)

[FreeOrion_Sicofonte_Fundaci_0068_2018-Apr-05 16:58:48.740447.sav.zip](https://github.com/freeorion/freeorion/files/1880959/FreeOrion_Sicofonte_Fundaci_0068_2018-Apr-05.16.58.48.740447.sav.zip)

**Comment by Dilvish-fo** [comment]
At this point I suspect this is an 'internal' bug related to the preparation of the universe update sent to the client, but it also seems possible this is simply a UI bug, so I've flagged both of those for now.

**Comment by Dilvish-fo** [comment]
The problem stemmed from insufficient client visibility of the Source object, which in turn had been cited in unneeded explicit activation clauses (so the human client was unable to determine that the tech should really apply). 
```
Remove superfluous activation clauses from SHP_GAL_EXPLO

 - besides being unneeded, they were interfering with the UI properly showing
   accounting info if the client empire did not have sufficient visibility of '
   the unnecessarily cited Source object
```

In the past we've been a bit laissez-faire about superfluous activation clauses, but this highlights the need to be on guard against them.  There are probably numerous other similar cases that shoud be cleaned up.  A quick search reveals that there are 73 instances of inherently-superfluous  ``` activation = Source```.  (Right, @geoffthemedio I am not forgetting something about any possible need for such a clause, correct?)  

It looks to me like all the remaining instances of ```activation = Planet``` are within the species scripts, where they would be appropriate.  But within techs (in particular defense techs) I see several instances of things like
```
activation = Unowned
```
and
```
activation = Not Unowned
```
@geoffthemedio  please correct me if I'm missing something, but it appears to me that the former would essentially void out the application of a tech, and that the latter would be superfluous.  I suspect that all such instances really intended for those restrictions to apply to the scope, but they'll need individual examination.
