### ISSUE TITLE
BAD_ENVIRONMENT_LABEL is not set

### ISSUE THREAD

**Issue by Oberlus** [freeorion/freeorion#2065]
### Environment
* **FreeOrion Version**: build 2018-04-02.02f4a84
* **Fetched as** 
  * Compiled from source

### Description
BAD_ENVIRONMENT_LABEL, used by the Sly, is not set. When you check the population of a Sly planet you see "ERROR: BAD_ENVIRONMENT_LABEL: -15".

### Expected Result
It should show a more pleasant description of that trait.

### Steps to reproduce
Check the population meter of any Sly planet on any game.

**Comment by dbenage-cx** [comment]
Fixed in bddfa21
