### ISSUE TITLE
Improper change of selected Fleet in FleetWnd upon course change

### ISSUE THREAD

**Issue by Dilvish-fo** [freeorion/freeorion#2075]
When the fleetbutton and FleetWnd represent multiple moving fleets, it will sometimes (more than rarely, perhaps even often) happen that changing the course for one of the fleets will cause that fleet to be deselected and a different fleet to instead be selected.  This can be lead to significant confusion/hassle when trying to change the destination for several fleets in the same FleetWnd.

It's my tentative observation that the wrongly-newly-selected fleet seems to always be the first fleet listed in the FleetWnd (which suggests that this might possibly be arising from the FleetWnd being reset or regenerated).

I also have a suspicion ( it is true for the case in front of me right now, and seems familiar for past instances) that this arises just for the situation where disparately located fleets have been aggregated in the FleetWnd/FleetButton.  So it is possible that this might be related to and resolved along with #2025, and certainly I think that issue should be addressed first.  But that issue has already had one ancillary issue tacked onto it, and I'm concerned that tacking on a third sub-issue there might make it too easy to get overlooked/lost during testing, so: a new Issue.

**Comment by geoffthemedio** [comment]
Test case. Click the colony fleet icon to cycle between having the colony fleet and the nearby battle fleet selected. Ordering the colony ship to move somewhere else similarly causes the battle fleet to be selected.

[clustered_fleets_test.zip](https://github.com/freeorion/freeorion/files/1958578/clustered_fleets_test.zip)

**Comment by geoffthemedio** [comment]
Should clicking a fleet button cycle through the fleets of nearby buttons, or just those within the clicked button? The other buttons' fleets can / could still be selected within the FleetWnd in either case.

**Comment by geoffthemedio** [comment]
I think this is fixed. Not sure why, but doesn't happen in my latest build https://github.com/freeorion/freeorion/commit/28768568ab559552ae88c71045467895ddeca277

@Dilvish-fo ?

**Comment by Dilvish-fo** [comment]
I haven't seen this occurring any more, and it seems to make sense that the recent changes would have fixed it.
