### ISSUE TITLE
Sitreps full of errors or not shown

### ISSUE THREAD

**Issue by Dilvish-fo** [freeorion/freeorion#2087]
(depending on whether you have the UI setting enabled for showing sitreps with errors).

Occurs on current clean master, appears likely to stem from bb3033a800

**Comment by geoffthemedio** [comment]
Avoiding issues like this is why I suggested making a release branch some time earlier. We should be fixing up the last few known major bugs now, in prep for a long delayed release, rather than doing intrnal code refactoring that will often introduce new ones...

**Comment by Vezzra** [comment]
*Sigh*, I know. However, even if we *had* created the release branch weeks ago, we still wouldn't be any closer to the release, considering issues/PRs like #1794 and #2009 still sitting there and apparently not much progress is being made. As well as the still ongoing work on final touches for the IS.

I'm going to post a reply in the [0.4.8 roadmap thread](http://freeorion.org/forum/viewtopic.php?f=4&t=10751) on the forum to discuss how to proceed with the release.

**Comment by adrianbroher** [comment]
> (depending on whether you have the UI setting enabled for showing sitreps with errors).

Why is this setting even a thing?

**Comment by geoffthemedio** [comment]
> Why is this setting even a thing?

Because players shouldn't see "ERROR", but devs should be able to.

**Comment by Dilvish-fo** [comment]
> Why is this setting even a thing?

To give a bit of background--  my recollection is that Ancient Ruins and the Experimentor Outpost (perhaps amongst others) had a tendency to generate a fair number of sitreps that would have errors if the player had not yet discovered the respective location.   This UI option was apparently chosen as a way to avoid that error spam.  

I think that I reformulated the Ancient Ruins sitreps to avoid that, and a similar restructuring could probably be done for the Experimentors, and perhaps the UI option should be done away with (or normally set to default to showing errors, and only be switch to suppress them for release builds akin to what we have done for the SuperTesters).

**Comment by adrianbroher** [comment]
> To give a bit of background-- my recollection is that Ancient Ruins and the Experimentor Outpost (perhaps amongst others) had a tendency to generate a fair number of sitreps that would have errors if the player had not yet discovered the respective location.

So in other words: the server in general sends sitreps to clients, that cannot know about the event or all linked entities due to their limited viewport on the universe?  That's what is actually bugging me. The client should never receive those sitreps in the first place unless old sitreps should be revealed retroactively which seems strange too.

**Comment by geoffthemedio** [comment]
Sitreps are generated with scripted effects and can thus refer to arbitrary object ids.

**Comment by adrianbroher** [comment]
And the server is not able to resolve those, despite being the authoritative source of truth for the game state?
