### ISSUE TITLE
ShipPartsOwned class filter broken

### ISSUE THREAD

**Issue by Voker57** [freeorion/freeorion#2089]
* **FreeOrion Version**: ae02c26b15018c63b1d59977e838ae5d626ac43f
* **Operating System**: Debian sid
* **Graphic card used**: ASUS Nvidia GTX1080
* **Fetched as** 
  * Compiled from source

### Description
This upkeep macro fails:

```
FLEET_UPKEEP_MULTIPLICATOR
'''(ShipPartsOwned empire = Source.Owner class = ShortRange)'''
```

With approximately this error:
```
/opt/freeorion/share/freeorion/default/scripting/ship_hulls/SH_BASIC_MEDIUM.focs.txt:13:72: Parse error.  Expected ) here:
```

### Expected Result
macro works

### Steps to reproduce
replace FLEET_UPKEEP_MULTIPLICATOR in default/scripting/common/upkeep.macros with above, launch freeoriond

**Comment by geoffthemedio** [comment]
Found some workarounds after extended trial-and-error. Seems to work after https://github.com/freeorion/freeorion/commit/120ab059420fbbb625d437dc3d0cd8a9a205937f though potentially not as good handling of specific cases of unexpected extra parameters in scripts.

**Comment by Voker57** [comment]
Yes, my case works now
