### ISSUE TITLE
subclassed dropdown lists broken

### ISSUE THREAD

**Issue by Dilvish-fo** [freeorion/freeorion#2097]
I first noticed that the ProductionQueue blocksize/repeat quantity selectors were broken.  They'll appear to change values, but other than their label the production queue does not respond to the change, and upon advancing the turn the numbers revert, confirming that the attempted change was ineffective.

This was caused by 26d5b0fa924aabf8be3d26e6c21e56bb7b70c9a4, which made droplists respond to left-mouse press instead of click, but didn't make the corresponding change to the subclasses, such as  ```QuantitySelector : public CUIDropDownList``` in ProductionWnd.cpp.

The fix for the ProductionQueue (and probably the others as well) appears fairly straightforward, although the QuantitySelectors had been overriding both ```DropDownList::LClick```  and ```DropDownList::LButtonDown```; it seems to me that the former  QuantitySelector::LButtonDown code can just be jettisoned and essentially replaced with the former LClick code.  I have a basic fix for the ProductionQueue ready that does that, and most/all of the small bit of jettisoned code seems to be a useless remnant from some older code anyways, but it's been long enough since I've done anything with that that I'll put it up as a PR for some review/testing rather than just commit it directly.

Searching for other overrides via Git Bash, I found 
```
$ grep "public CUIDropDownList" */*.cpp */*/*.cpp
UI/MultiplayerLobbyWnd.cpp:    class TypeSelector : public CUIDropDownList {
UI/ProductionWnd.cpp:    class QuantitySelector : public CUIDropDownList {
UI/SidePanel.cpp:class SidePanel::SystemNameDropDownList : public CUIDropDownList {
```
And I confirmed that the SidePanel SystemNameDropDownList no longer seems to be working right (it won't show the dropdown list, although it will allow mousescrolling).  I haven't checked what the TypeSelector was yet and whether or not it was affected.  I don't have much more time available just now but will try to come back to it before Monday if no one else gets around to it.

**Comment by Dilvish-fo** [comment]
Hmm, I went ahead and took a peek at the SidePanel::SystemNameDropDownList and it hadn't even been overriding DropDownList::LClick, so it's not immediately apparent to me why it would have a problem now.  Did I miss some other recent change to the behavior of SidePanel::SystemNameDropDownList?  It's pretty strong in my memory that it used to be that you could left click it and it would drop down the list of all System names to select from.

**Comment by geoffthemedio** [comment]
I don't see any problems with the system name drop list... works as expected as far as I can tell.

Multiplayer lobby type selector seems to work fine as well.

**Comment by adrianbroher** [comment]
FYI:  The search result may be incomplete.  Try

```
grep -r --include=\*.cpp "public CUIDropDownList" .
```

instead for searching recursive (`-r`), only including files with cpp suffix (`--include`).  Adding `-E` as parameter and `\s+` is useful too as you may not know if people reliable use a single space between tokens.

**Comment by Dilvish-fo** [comment]
> The search result may be incomplete. Try

@adrianbroher  Thanks for the useful tips.

> I don't see any problems with the system name drop list... works as expected as far as I can tell.

@geoffthemedio just to be clear about "works as expected", does that mean that (i) leftmousedown on the system name triggers display of the dropdown list of system names to appear for you, (ii) you recall some other change that had blocked/stopped that dropdown list, or (iii) you do not recall the system name ever being clickable to trigger the dropdownlist being displayed?

**Comment by geoffthemedio** [comment]
The list drops and I can pick a system from the list and thereby switch to the new system.

**Comment by Dilvish-fo** [comment]
OK, that's what I would expect also, but it's not what I'm getting on my Win10 machine.  I'll do some more experimenting later today.

**Comment by geoffthemedio** [comment]
Now works for  you...?

**Comment by Dilvish-fo** [comment]
Before closing I confirmed that the systemname dropdown list works fine for me on my Linux machine.  Since it is also working fine for you on Win10, it seems there is something odd going on with my Win10 laptop.  I'll investigate further, but if I can't resolve the problem then I think it should be a new Issue anyways since it is seeming to be different than (and possibly predating) this issue.  Compiling on my Win10 laptop goes really slow (I wish there was a good ccache equivalent for Visual Studio), and I'm pretty busy for the next few days, so it will probably be a while.  Perhaps I should go ahead and open an Issue for this more specific case and assign it to myself just to keep it from getting lost in the shuffle.
