### ISSUE TITLE
Default Pedia Article is Empty Incomplete Ship Design

### ISSUE THREAD

**Issue by geoffthemedio** [freeorion/freeorion#2101]
Quickstart from command line. When at map, immediately open the pedia. The article shown is an empty "Incomplete Ship Design" article. It should be the index.

**Comment by Vezzra** [comment]
Confirmed on OSX for current master (c6196f996ae5080c8a1cba1634da386cd8d9fd0d).

**Comment by geoffthemedio** [comment]
Fixed? https://github.com/freeorion/freeorion/commit/b8dbb75e3d7779496a5216223e335187e7606881

**Comment by Dilvish-fo** [comment]
Yes, fixed.
