### ISSUE TITLE
freeorion cleans the environment variables for freeoriond

### ISSUE THREAD

**Issue by l29ah** [freeorion/freeorion#2106]
### Environment

* **FreeOrion Version**: https://github.com/Voker57/freeorion/tree/teamsmac-14.6.2
* **Operating System**: Gentoo Linux
* **Fetched as** 
  * Compiled from source

### Description
I run `LD_LIBRARY_PATH=. ./freeorion`, and when i try to host a game, freeoriond complains about the missing library that's in fact in '.':
```
"/home/l29ah/projects/freeorion-teamsmac/freeoriond": error while loading shared libraries: libfreeorioncommon.so: cannot open shared object file: No such file or directory
```

### Expected Result
`freeorion` passing `LD_LIBRARY_PATH` to `freeoriond` and `freeoriond` working happily from the build dir.

### Steps to reproduce
Build freeorion and try running it from the build directory.

**Comment by Dilvish-fo** [comment]
> Build freeorion and try running it from the build directory.

I do that all the time on Linux, no problem.  

Please describe the relevant portion of your folder structure more clearly, and why you wind up with a need to pass LD_LIBRARY_PATH at all.  (From your own description, it's not clear to me that you need it, or that what you are passing would be correct.)

**Comment by l29ah** [comment]
What relevant portion? I `cmake . && make`, then
```
‰ ./freeorion
./freeorion: error while loading shared libraries: libfreeorioncommon.so: cannot open shared object file: No such file or directory
```
```
‰ ls -1
AI
appveyor.yml
BUILD.md
ChangeLog.md
check
client
cmake
CMakeCache.txt
CMakeDoxyfile.in
CMakeDoxygenDefaults.cmake
CMakeFiles
cmake_install.cmake
CMakeLists.txt
combat
CONTRIBUTING.md
CPackConfig.cmake
CPackSourceConfig.cmake
default
doc
Empire
freeorion
freeorionca
freeoriond
freeorion.desktop
FreeOrion.ico
GG
Installer
libfreeorioncommon.so
libfreeorionparse.so
libGiGiSDL.so
libGiGi.so
Makefile
msvc2015
network
parse
python
README.md
server
test
UI
universe
util
Xcode
```

It used to work w/o LD_LIBRARY_PATH, but recently i `git clean -df`, and it started misbehaving.

**Comment by Dilvish-fo** [comment]
It looks like you are building directly within the main source tree.  Marcel (adrian_broher) very strongly recommends using a separate build directory, as described in [our build instructions](https://github.com/freeorion/freeorion/blob/master/BUILD.md).  Could you try that approach?  You would then execute freeorion from within that build directory.

**Comment by l29ah** [comment]
Yeah, after building it in build/ subdir i no longer have to provide any environment, thank you.
