### ISSUE TITLE
Pedia entry for Stockpile Tranfer Units producible item broken

### ISSUE THREAD

**Issue by Vezzra** [freeorion/freeorion#2110]
### Environment

* **FreeOrion Version**: c6196f996ae5080c8a1cba1634da386cd8d9fd0d
* **Operating System**: OSX
* **Fetched as** 
  * Compiled from source

### Description

The Pedia entry for the Stockpile Tranfer Units producible item is broken:

![pediaentryforstockpiletranferunits](https://user-images.githubusercontent.com/10279417/40240927-025e1220-5aba-11e8-822f-cd1856cd570b.png)

**Comment by geoffthemedio** [comment]
Fixed? https://github.com/freeorion/freeorion/commit/871efafe2b1b8cbfb20b73cd9bbdd285d747fcdd

**Comment by Vezzra** [comment]
Yes.

**Comment by Vezzra** [comment]
Has been a duplicate of #2040 anyway, sorry, missed that when I created this issue.
