### ISSUE TITLE
Focus change penalty can drop a meter below target value

### ISSUE THREAD

**Issue by Dilvish-fo** [freeorion/freeorion#2112]
It used to be (before meter growth moved to effects) that the focus change penalty would only apply if a meter was above its current target value, so, for example, if you had a planet on Research Focus long enough to stabilize,  then changed to Protection Focus, the Research meter would drop by up to two points if the new target was at least 2 points below the previous target,  but the Industry meter would in that case not drop because it was already at its target value, which did not change from the focus change.

Currently, that's not the case-- switching From Research to Protection will drop the Industry meter by one point even if that puts it below its target value.

I expect this will be fairly straightforward to fix, and will work on it shortly.

**Comment by Dilvish-fo** [comment]
> Why shouldn't it cause a drop in all cases? The points is to make it costly to switch focus.

If it accidentally dropped it 3 points, you could say, 'why not drop it 3 points?.  The dropping below target was an apparently accidental change introduced with the February switch to Effect driven meter growth.  This PR fixes that accidental change.  The actual script of the penalty didn't change, but the changes in meter operation did change the result of the script.  Before posting this issue and the PR I went back and built a version just prior to the switch to confirm.   It's easy to test this with the starting planet just a couple turns into the game.

I don't think the additional penalty is necessary or even helpful.  It seems very wrong to me that it would cause the meter value to drop below target.  Of course my thinking may be partly colored by just being used to how it had worked for so long before February.  Some of the particularly annoying times this now occurs (and what really brought it to my attention) are when you conquer a new planet, and it has some odd focus like growth or defense, if you don't notice and change it immediately, but instead notice it a turn or two later, fixing the focus currently causes one of the meters to get set back a point even though they are all still climbing up to their min targets.  It didn't used to do this if they were all below their min targets.

I will emphasize, the PR is simply reverting the behavior to that which had been standard for a long time, and which was changed in February, apparently accidentally and unnoticed at the time.

**Comment by geoffthemedio** [comment]
> It seems very wrong to me that it would cause the meter value to drop below target.

It seems very wrong to me that it wouldn't. Consistent focus change = penalty means it's always a bad idea to dither focus settings. If it sometimes isn't penalized, then a particularly attentive player might find cases where doing the micromanagement for benefit is worthwhile.

But sure, if you prefer to restore the old behaviour, go ahead...

**Comment by Dilvish-fo** [comment]
> Consistent focus change = penalty means it's always a bad idea to dither focus settings

I don't see this fix as really having anything to do with dithering.  This reversion does *not affect at all* the penalties faced by someone trying to squeak a few points from intelligent research/industry dithering (at least not in any situation where I could actually see anyone bothering to try it under either penalty behavior).

The old treatment (and as restored by the linked PR) could let you ditrher without research/industry penalty between two non-research-non-industry focii like going back and forth between Growth and Defense, or Defense and logistics, or whatnot, and if for some unusual reason (which I cannot recall having encountered in a game if we don't count making a decision and then changing one's mind the next turn) someone wanted to dither between those two focii, I don't see any reason that we need to  penalize such.

Thinking hard, I suppose this could also let you dither a planet back and forth between Growth and your choice of either Industry or Research without any special penalty beyond giving up the growth focus for the dithering turns (and in situations where the growth focus makes any sense at all, I find it unlikely that tradeoff would look worthwhile).  If you really think that's something we need to guard against by making a penalty that also applies to lots of other situations then please present that argument in a design discussion on the forum.
