### ISSUE TITLE
CombatReports not displaying in loaded game

### ISSUE THREAD

**Issue by Dilvish-fo** [freeorion/freeorion#2116]
Steps: load a savegame having at least one combat report in the sitreps (or play a game to that point), display that combat report,  then (whether from within the current game or after resigning, but without totally exiting from FreeOrion) load  a savegame also having at least one combat report (can be the same file), in this second game the CombatReports will not display (clicking the link appears to do nothing).

I am finding slightly different behavior between Win10 and Linux in this regards. in that for Win10 it seems that the bug appears even if the CombatReport in the fist game is not displayed, it is sufficient that there simply be a combat report in the Sitreps, whereas on Linux I am only seeing the bug if a combat report in the first game has actually been displayed.

**Comment by geoffthemedio** [comment]
Fixed? https://github.com/freeorion/freeorion/commit/07769949e71d723312fcddbf189d93d6bad7fc2d

**Comment by Dilvish-fo** [comment]
Yes, thanks.
