### ISSUE TITLE
Move all multiplayer related game rules to a separate category

### ISSUE THREAD

**Issue by o01eg** [freeorion/freeorion#2148]
### Environment
* **FreeOrion Version**: pre 0.4.8
* **Fetched as** 
  * Binary release
  * Weekly development build
  * Compiled from source

### Description
Currently all game rules applied in multiplayer game are scattered in different game rules categories.

### Expected Result
Move these game rules to one category which won't show in singleplayer mode.

**Comment by Dilvish-fo** [comment]
> which won't show in singleplayer mode.

While I can understand the motivation, I don't know that that part is necessarily ideal.   If someone opens up the options to review them when they have a single player game going, they won't necessarily think that it might be hiding options from them.  I would advocate that you just let the multiplayer option tab be visible/available at all times, like all the other options.
