### ISSUE TITLE
Scylior OP, add some bad traits

### ISSUE THREAD

**Issue by Oberlus** [freeorion/freeorion#2162]
### Description
Scylor have great research (200%) and good population (125%), no more traits, which makes them rather OP compared to other playable species.
Also, they start on a medium (instead of large) planet (this is undocumented, should be fixed), but that is not enough to balance them.

I suggest adding them these bad traits:

- Bad supply.
- Bad detection.
- Bad stockpiling.

None of these are crippling, and all can be circumvented using their great research, so that they are just a bit of a slowdown for expansion.
I don't think these would really make Scylior balanced, just less OP.

Discussion thread: http://www.freeorion.org/forum/viewtopic.php?f=28&t=10985

**Comment by Vezzra** [comment]
Has there been done anything about this?

**Comment by Oberlus** [comment]
Not that I'm aware.
It is not gamebreaking, in several enough games Scylior do not fare well, so I would not give any priority to this issue.
[Edit: after reading the forum, I'd give this the priority:low tag]

I'm working only on the new tech tree until I get to something resembling an alpha version for forum discussion, but then I'll start doing small github things like the one of this issue to get into play. So if no one solves it first, this issue could be the meat of my first PR.

**Comment by agrrr3** [comment]
Was playtesting how BAD_FUEL and BAD_SUPPLY combine and made a PR #2568 which got already merged. So solved I guess?
