### ISSUE TITLE
Change GASEOUS_LABEL text

### ISSUE THREAD

**Issue by Oberlus** [freeorion/freeorion#2177]
Sly in their native environment has a special effect (-50% population, target population scaling priority) so that before-scaling effects produce values equivalent to a medium size planet instead of the default 6 size of the planet. This effect does no apply in the rest of planets (so once a Sly can colonise a hostile env. planet, it will have the same population numbers than any other AVERAGE_POPULATION species with same tech.
The point is the text for that effect on GGs is "Bad Environment", which is confusing for the native environment of a species.

Dilvish suggested "Crushing Gravity". I'm not convinced (I expect gasbags to require that gravity).
Another alternative could be "Gas Giant Environment".

I want to note that having habitable size 4 for GGs and removing the -50% population effect would yield roughly similar population values than current implementation (without any other change) and render unnecessary the GASEOUS_LABEL.

Discusion in http://www.freeorion.org/forum/viewtopic.php?f=28&t=10995

**Comment by Vezzra** [comment]
As this is essentially a confusing/misleading label/text, I think we can consider any patch which changes that close enough to a "fix" to allow it into the release (especially since such a fix is going to be of the very simple kind :wink:).

**Comment by Vezzra** [comment]
Fixed by #2181.
