### ISSUE TITLE
Research modifications from game rules do not get restored

### ISSUE THREAD

**Issue by agrrr3** [freeorion/freeorion#2180]
### Environment
* **FreeOrion Version**: last pre-RC2 0.4.8 build
* **Operating System**: windows
* **Fetched as** 
  * Binary release

### Description
If you load a game which modifies the research (or production) cost via game rules, the UI shows the modified consequences, but the cost calculation actually does not comply to the game rules anymore.

Also see [research problems with 0.4.8 (build 2018-06-14.3f22a75)](http://www.freeorion.org/forum/viewtopic.php?f=28&t=10990).

### Expected Result
The game rule still has effect after loading a game.

### Steps to reproduce
Start a game with e.g. fast research. Check that you need only 1 turn for every tech research. Save the game. Restart freeorion. Load the game.  Now the UI still claims that you need only 1RP for every technology, but research progress is at normal RP cost.

Note that i consider this bug severe, somebody trying to use game rules for research/production will get broken games

**Comment by geoffthemedio** [comment]
Is something similar going on with rules in the pedia? Using master, if I start a game and modify a bunch of rules, when I immediately open the pedia rules page, they are all shown with default values.

Edit: At least some also don't work, like the number of combat rounds, so it's not just a pedia display issue.

**Comment by agrrr3** [comment]
Diddling around a bit. The problem also shows if you just load your autosave file (no need to restart).

Also there is some (probably different) issue - if you play with cheap/fast tech and give up and start a new game without stopping fo, the flag for cheap/fast tech is set but it seems to be ignored (seen on debian build from release branch).

Also there is some (probably different) issue - if you play with cheap/fast tech and restart fo and start another game it doesnt remember your last setting. (seen on debian build from release branch).

We probably should fix the save game issue. And if this doesnt fix the other stuff open up some separate issues?

**Comment by agrrr3** [comment]
RULE_CHEAP_AND_FAST_TECH_RESEARCH is set and used in universe/Tech.cpp

RULE_TECH_COST_FACTOR gets defined in game_rules.focs.txt and used in default/scripting/common/base_prod.macros, so this is scripting-only.

There seems some debug support defined in custom_sitreps.txt

Also AI doesnt know shit about the real value of TECH_COST_MULTIPLIER so the estimates will be very wrong. Somebody add @Dilvish-fo AI flag please.

**Comment by agrrr3** [comment]
As expected, the rule gets serialized in XML:
        <m_game_rules class_id="3" tracking_level="0" version="0">
                        <first>RULE_CHEAP_AND_FAST_TECH_RESEARCH</first>
        </m_game_rules>

**Comment by Vezzra** [comment]
> Also AI doesnt know shit about the real value of TECH_COST_MULTIPLIER so the estimates will be very wrong. Somebody add @Dilvish-fo AI flag please.

@Dilvish-fo, is that really a problem, and if yes, how serious is it?

**Comment by Vezzra** [comment]
> Moved some class version macros into the header, which fixes that issue: e3e8108

@agrrr3, can you check if the fix @geoffthemedio committed solved the issue for you? (You'll have to build and test master, as the fix hasn't been cherry picked yet.)

**Comment by geoffthemedio** [comment]
It doesn't fix this issue (#2180). It just, for me, resolved the related issue that modified rules weren't showing up in the pedia list at all, nor were they affecting the game after universe generation.

**Comment by Vezzra** [comment]
Oh, I see... still, if those issues are in the release branch too, that commit needs to be cherry picked.

**Comment by Dilvish-fo** [comment]
> Also AI doesnt know shit about the real value of TECH_COST_MULTIPLIER so the estimates will be very wrong

Short answer: Perhaps I'm overlooking something, but I'm not particularly concerned.

While a higher TECH_COST_MULTIPLIER would probably, in general, merit the AI assigning a somewhat higher ratio for valuing research relative to industry, currently 
```
RESEARCH_WEIGHTING = 2.3
```
It couldn't be a simple linear relationship, and I wouldn't want to rush into an even mild increase for it without a fair bit of testing.

A higher (or lower) TECH_COST_MULTIPLIER would probably also make LRN_ARTIF_MINDS somewhat  _less_ valuable (or more valuable in the case of a lower multiplier) relative to other techs, but given as it is relatively cheap it will still be pretty important pretty early.  There are a few other similar type things that you could point to as having an at least somewhat different relative value, but I don't think that there would be a really clear adjustment to make.  At least, one doesn't come to mind for me just now.

If someone plays much with a significantly altered TECH_COST_MULTIPLIER and wants to comment on how that seems to affect the AI, I'd love to read about that feedback on the forums.  Or if you just have feedback on how you adjust your own gameplay for such changes, that would also be interesting reading.

**Comment by agrrr3** [comment]
Probably in coming test games (after fixing the bug) I will adjust the value to see what it does to my choices.

Is there an automated way to run lets 100 freeorion games for 100 turns and see the statistics of the empires? Do this for an multiplier of 1.0, 2.0 and 4.0 with different research weighting. Should show which species fare better and how much influence the weighting has.

**Comment by Dilvish-fo** [comment]
> Is there an automated way to run lets 100 freeorion games for 100 turns and see the statistics of the empires?

I've talked about such for a while, with an aim to doing a sort of evolutionary approach to AI fine tuning, but we haven't quite gotten around to it.  A basic python script to control such would be pretty straightforward, but I think that at the time I was most interested we started having trouble with the auto-advance-n-turns and/or auto-quit (mostly the latter I think).  Although they both seem to be working fine now I haven't gotten around to following up on it yet.

**Comment by o01eg** [comment]
> Is there an automated way to run lets 100 freeorion games for 100 turns and see the statistics of the empires? Do this for an multiplier of 1.0, 2.0 and 4.0 with different research weighting. Should show which species fare better and how much influence the weighting has.

You could try new `SmokeTestGame` or `SmokeTestHostless` but you need to hack them to change rules and gather statistics.

**Comment by geoffthemedio** [comment]
Maybe fixed?

**Comment by agrrr3** [comment]
Its not fixed (i think i tried on master)

**Comment by geoffthemedio** [comment]
Then I can't replicate the issue anymore. Started a game with the tech cost scaling set to 6. Played a few turns, putting a few turns' research into a tech. Saved. Loaded. Costs and per-turn changes remained consistent.

**Comment by Vezzra** [comment]
@agrrr3,

> Issue does still exist in release-v0.4.8 (c872658, fedora 28, kde)

Because the fix hasn't been cherry picked to the release branch yet. First I need a confirmation that the fix works. So, do I understand correctly, that ee9e4e45267c3f753e71f36f79f52326d1c2ab57 fixed the issue?

**Comment by agrrr3** [comment]
@Vezzra yes the commit fixes the issue (cherry-picking also fixes it in the release branch)

**Comment by Vezzra** [comment]
Fixed by ee9e4e45267c3f753e71f36f79f52326d1c2ab57.
