### ISSUE TITLE
Feature request: new species trait, fuel efficiency

### ISSUE THREAD

**Issue by Oberlus** [freeorion/freeorion#2187]
### Description
A new species trait that seems natural to FO:

Fixed bonus alternative 1:
Bad: -1 fuel.
Good: +1 fuel.
Great: +2 fuel.
Ultimate: +3 fuel.

Geoff wrote:
> This would effectively add a fuel tank part to ships crewed by those species. That isn't overly compelling... A multiplicative adjustment might be more interesting.

Multiplicative bonus alternative:
Bad: 75% fuel.
Good: 150% fuel.
Great: 200% fuel.
Ultimate: 300% fuel.

Agrrr3 (Ophiuchus) wrote:
> Note though that it would be pretty easy to get a 9 fuel scout ship (with 2 deuterium tanks) when having +50%. We could try with the multiplication first and change later if its not good.
> Two extra fuel always mean one extra supply-equivalent-roundtrip-reach.
> Actually what I would suggest though is:

**Fixed bonus alternative 2:
Bad: -1 fuel.
Good: +2 fuel.
Great: +4 fuel.
Ultimate: +6 fuel.**

[Forum discussion](http://www.freeorion.org/forum/viewtopic.php?f=6&t=10919).

**Comment by agrrr3** [comment]
In master actually some version of this is already implemented. Needed it to balance the Fulver.

https://github.com/freeorion/freeorion/blob/master/default/scripting/species/common/fuel.macros

The bonus is now bad-1 ; good +1 ; great +2 ; ultimate +3
Reasoning: the difference between average supply and great supply is +1  supply; so to match this distance fuel should be +2.

**Comment by Oberlus** [comment]
The feature requested was implemented. Closing.
