### ISSUE TITLE
Disable option that turns off the predefined designs (0.4.8 only, temporary workaround)

### ISSUE THREAD

**Issue by Vezzra** [freeorion/freeorion#2190]
As discussed in #2107, the option to turn off predefined ship designs is currently broken and, as a quick fix doesn't seem possible, should be disabled for 0.4.8.

**Comment by geoffthemedio** [comment]
Option is hidden by that commit. Consider cherry picking?

**Comment by geoffthemedio** [comment]
Feel free to revert and implement as you prefer...

Edit: Actually, just hiding that option isn't enough in any case, as there are popup menus to adjust the setting.

**Comment by geoffthemedio** [comment]
Better PR added, probably just for the release branch, although made against master.

**Comment by Vezzra** [comment]
> Consider cherry picking?

Done: a792292c753c8bd2ee6e6a8b475ac702ffe636fe
