### ISSUE TITLE
Pedia lookup of a ship produces errors

### ISSUE THREAD

**Issue by flaviojs** [freeorion/freeorion#2201]
### Environment
* **FreeOrion Version**: v0.4.8+ (master at ae39545)
* **Operating System**: Linux Mint 18 Sarah
* **Graphic card used**:Advanced Micro Devices, Inc. [AMD/ATI] RV710/M92 [Mobility Radeon HD 4530/4570/545v]
* **Fetched as**
  * Compiled from source

### Description
Doing a pedia lookup of a ship produces errors in the log file `freeorion.log`.
```
08:51:19.640508 [error] client : ValueRef.cpp:86 : FollowReference : Unable to get system for object
08:51:19.640925 [error] client : ValueRef.cpp:903 : Variable<int>::Eval unable to follow reference: LocalCandidate.System.LastTurnBattleHere :  | Local Candidate: Ship -2 (  )  |  System (-1):  |  LastTurnBattleHere  | 
08:51:19.641374 [error] client : ValueRef.cpp:905 : source: OBJ_PLANET 2248 ( Sole γ I )
```

### Expected Result
No errors.

### Steps to reproduce
1. right click on a ship in the map or production windows
2. choose the option to open the pedia page

**Comment by geoffthemedio** [comment]
Probably need to check that a ship is in a system before testing the last turn that system had a battle...

**Comment by Dilvish-fo** [comment]
> choose the option to open the pedia page

@flaviojs just to be clear, you are referring to the right-click option in the fleet window listing, to open the pedia page for the Ship Design corresponding to the selected ship, yes?

**Comment by flaviojs** [comment]
Right click on an existing ship or a ship in the production window. Let me add images to be clearer...

ship being produced:
![ship_being_produced](https://user-images.githubusercontent.com/1009600/43390482-3b0f9228-93e6-11e8-99de-e9e393d9e634.png)

ship that can be produced:
![ship_can_be_produced](https://user-images.githubusercontent.com/1009600/43390519-4d6e0e0e-93e6-11e8-9ef4-cbbf2830f100.png)

ship that exists:
![ship_that_exists](https://user-images.githubusercontent.com/1009600/43390590-7052506a-93e6-11e8-82cd-bd9bccd375e8.png)

**Comment by geoffthemedio** [comment]
I think that's looking up the design, using a temporary ship object, in all cases...?

**Comment by flaviojs** [comment]
The pedia page shows "[Game - Ship Design]" in all cases.
