### ISSUE TITLE
Belts with Asteroid Reformation Processor under blockage do not count as connected to it

### ISSUE THREAD

**Issue by Oberlus** [freeorion/freeorion#2215]
* **FreeOrion Version**: build 2018-07-13.9a03676 MSCV 2015 (0.4.8 RC2, binary release)
* **Operating System**: Windows 7

### Description
An asteroid belt colonised with exobots and equiped with Asteroid Processor (AP) and Asteroid Reformation Processor (ARP) was building scattered asteroid hulls. Once the system has got blockaded by an Enemy, the asteriod belt fails to meet the building requirements, which is wrong. Check attached image
![fo_cant_built_asteroid_hulls_on_belts](https://user-images.githubusercontent.com/28650914/42735791-7cb7b652-885a-11e8-86b2-c9e3227873a4.png)
I've checked that asteroid hulls with the AP requirement (and not ARP) are available to be built in that same asteroid belt, and that the ARP counts as present in the asteroid belt (can't build a second one because it does not meet the requirement "there is no ARP in the planet"). I don't see why the FOCS code could be failing here.

### Expected Result
The hull should be allowed in the asteroid belt under blockage, since it has all required buildings. More specifically, the building requirements should be acknowledge as met, which are not.

### Steps to reproduce
Load attached save game. Check system Adhil Gamma. Check the items being built in Adhil Gamma Asteroids. There is a batch of 1 "Swarm Carrier" about to be finished. It's due date is "never". If you check the unavailable ship designs you'll see the "Swarm Carrier" design there, the asteroid belt fails to meet the Asteroid Reformation Processor building requirement, while it is actually built in that asteroid belt.

[FreeOrion_Sicofonte_Shy_0238_20180715_131612.zip](https://github.com/freeorion/freeorion/files/2195881/FreeOrion_Sicofonte_Shy_0238_20180715_131612.zip)

**Comment by Dilvish-fo** [comment]
verified, and I think I see the problem, I am working on it.
