### ISSUE TITLE
Fleet movement orders broken in a couple ways

### ISSUE THREAD

**Issue by Dilvish-fo** [freeorion/freeorion#2222]
On master (currently at 4b5c70f2b1c0416f0591a0a636b9340b98fa5fdb) the ability to enter fleet movement orders is broken in a couple ways.
- [ ] 1) @adrianbroher   after 058e12a52f673843c93e10de26ed9e15465e093f can no longer append to the current path-- the fleet movement projection lines will display as if the new travel will be appended to the current path, but the actual movement path that the fleet winds up with is instead (a) in most cases the most direct route from its current location to the final destination or (b) after  83674122283ec4617d114e3c3cbd2cb8c9cee3f2 it seems in cases where the new final destination has never been Partially visible, the total amended travel path wound up rejected and the fleet remained where it was
- [ ] 2) After 83674122283ec4617d114e3c3cbd2cb8c9cee3f2, once a fleet has move orders, can no longer order it to stop at the first system in its movepath (including the situation where the fleet is currently in a system and was just ordered to leave it, it can no longer be ordered to instead stay).

**Comment by adrianbroher** [comment]
Please give proper instructions to reproduce the issues.

**Comment by Dilvish-fo** [comment]
I had thought I could assume a certain level of familiarity with our standard UI.  

On Windows and Linux we set a fleet path by left-clicking on a fleet to select it, and then right-clicking on a destination system to set the path.  We append to the current path of a selected fleet by shift-right-clicking on the new destination system.  I would guess that on MacOS it's an option-click or ctrl-click instead of right-click, but I'm not sure about that.

If there is something different that is not clear to you, please be more specific.

**Comment by adrianbroher** [comment]
> I had thought I could assume a certain level of familiarity with our standard UI.

No you can't. I may have some time to do some maintenance and refactoring, but taking time for actual playing the game are gone for years.

**Comment by Dilvish-fo** [comment]
If a person doesn't even strive to maintain enough familiarity with the operation of the program to know how to test changes to a section of code, then I don't see how it could be a responsible action to commit changes to that section directly to master instead of posting a PR and noting the lack of testing.

**Comment by adrianbroher** [comment]
You're right. I should stop bothering this project with subpar code.

Bye.

**Comment by Dilvish-fo** [comment]
@adrianbroher That wasn't a complaint about your coding skills -- I'll happily acknowledge that your coding knowledge and skills are exemplary and in at least many ways superior to mine, and that your coding output is likewise overall exemplary.  I expect there are lots of areas in the FO codebase where the combination of the strength of your assessment of the reliability of your changes together with your determination of whatever testing might be prudent, and your personal execution of that, make it fine for those changes to go directly to master.  And of course we all make mistakes from time to time, and so I refrained from commenting on my testing concerns in the initial descriptions for these last couple Issues.    There are many cases where prudence dictates to me that my own changes go through a PR.  I'd like to ask you to reassess your evaluative process for such decisions, and I'll hope that you and @geoffthemedio  discuss this some more once the forums are working again, but I'll refrain from further comment on it.

Let me also note that your coding contributions for this project, and your time in general, are greatly appreciated.

**Comment by geoffthemedio** [comment]
@Dilvish-fo 's comment was rather poorly phrased, but I think the suggestion that, if nontrivial changes aren't going to be tested by the coder, they should be put into a pull request before being committed to master is reasonable.

@adrianbroher I don't think anyone considers your code contributions "subpar", and I hope you'll reconsider leaving.
