### ISSUE TITLE
Forum doesn't work anymore.

### ISSUE THREAD

**Issue by adrianbroher** [freeorion/freeorion#2224]
The forum spews deprecation warnings on every thread view and it's impossible to post something.

On creating a thread:
```
[phpBB Debug] PHP Warning: in file [ROOT]/includes/message_parser.php on line 71: preg_replace(): The /e modifier is no longer supported, use preg_replace_callback instead
[phpBB Debug] PHP Warning: in file [ROOT]/includes/functions_content.php on line 678: preg_replace(): The /e modifier is no longer supported, use preg_replace_callback instead
```
Ob viewing a thread
```
[phpBB Debug] PHP Warning: in file [ROOT]/includes/bbcode.php on line 483: preg_replace(): The /e modifier is no longer supported, use preg_replace_callback instead
... left out dupes
[phpBB Debug] PHP Warning: in file [ROOT]/includes/bbcode.php on line 112: preg_replace(): The /e modifier is no longer supported, use preg_replace_callback instead
... left out dupes
[phpBB Debug] PHP Warning: in file [ROOT]/includes/functions.php on line 4752: Cannot modify header information - headers already sent by (output started at [ROOT]/includes/functions.php:3887)
[phpBB Debug] PHP Warning: in file [ROOT]/includes/functions.php on line 4754: Cannot modify header information - headers already sent by (output started at [ROOT]/includes/functions.php:3887)
[phpBB Debug] PHP Warning: in file [ROOT]/includes/functions.php on line 4755: Cannot modify header information - headers already sent by (output started at [ROOT]/includes/functions.php:3887)
[phpBB Debug] PHP Warning: in file [ROOT]/includes/functions.php on line 4756: Cannot modify header information - headers already sent by (output started at [ROOT]/includes/functions.php:3887)
```

Time for an upgrade I would guess.

**Comment by geoffthemedio** [comment]
I wasn't loading at all a few hours ago. I adjusting a setting in config.php based on googling the error mesasge. That got it to be viewable, but I didn't try posting a message.

Seemingly the host updated the PHP version which broke the somewhat (rather) out of data version of phpBB 3.0.x.

**Comment by geoffthemedio** [comment]
Attempting an upgrade now, so the forums are currently offline.

**Comment by geoffthemedio** [comment]
First attempt stopped part way through updating the database with various errors. Uploading unconverted stuff again...

**Comment by geoffthemedio** [comment]
Apparently phpBB 3.1 doesn't work with PHP 7+, which is now the version provided by the host, so I'm trying phpBB 3.2.1.

Edit: still no luck

**Comment by Oberlus** [comment]
> SQL ERROR [ mysqli ]
> 
> Table 'tzlaine_phpbb3.phpbb3_styles_template' doesn't exist [1146]

Have you tried the solution posted at the end of that thread? Quoting from there:

Go into a MySQL command line:
EXECUTE THE FOLLOWING CODE. BUT CHANGE 'YourDBname' to your actual database name.

`UPDATE YourDBname.phpbb_styles SET style_active = '1' WHERE style_id = '1';`

Then re-run your database upgrade process.

https://www.phpbb.com/community/viewtopic.php?f=556&t=2455291&sid=a739cd41762eb8e3964a9123d43bda79&start=15#p14962281

**Comment by geoffthemedio** [comment]
> Have you tried...

I don't know how to get into the mysqul command line
````
% mysql tzlaine_phpbb3
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)
````

**Comment by geoffthemedio** [comment]
Got some hints from Tyreth by email, so will try again later. He's currently too busy to do the forum upgrade / repair himself, unfortunately.

**Comment by Cjkjvfnby** [comment]
Do you done `db` backup before any upgrades?

**Comment by geoffthemedio** [comment]
Yes.

**Comment by Vezzra** [comment]
@geoffthemedio, since the forum is down, and consequently I can't PM you, how can/shall I contact your for private communications?

**Comment by geoffthemedio** [comment]
@Vezzra I sent you an email (to the address in your github profile) . Reply to that.

**Comment by Dilvish-fo** [comment]
Noting from another discussion:

>> If you just want to view the boards, you can at http://freeorion.org/forum321/

>Ah, thanks, that is at least a bit of help.  And it seems that the thread and post numbers are the same, so it works fine to take a forum thread/post address, like the discussion link towards the top here: ```http://www.freeorion.org/forum/viewtopic.php?f=2&t=10890``` and just swap in ```forum321``` in places of ```forum```
so to review the forum discussion for this PR, we can go to http://www.freeorion.org/forum321/viewtopic.php?f=2&t=10890

**Comment by Vezzra** [comment]
Just a small update: we're still working on getting the forums back up. I'm now also trying to assist @geoffthemedio and Tyreth, which is why there is no progress with the release right now (working on that forum problem is using up my entire FO time).

Everyone please be patient, hopefully we will be able to resume normal operation soon.

**Comment by Vezzra** [comment]
Another quick heads-up: we're making progress with solving the issues of the forum upgrade. Just so you guys know that the silence doesn't mean nothing is happening. A lot has happened, and hopefully we'll be back online soon!

**Comment by o01eg** [comment]
Looks like forum is up.

**Comment by Vezzra** [comment]
Yep, forums are back online. Still need to post a proper announcement in the news section on the wiki main page...
