### ISSUE TITLE
Feature request: drag&drop from producible (researchable) items to production (research) queue

### ISSUE THREAD

**Issue by Oberlus** [freeorion/freeorion#2247]
Sometimes a new item to be added to the production queue is to be put at some place between top and bottom of the production list, so you have to double-click it in the producible list and then drag&drop it to the right place in the production queue.

So it would save some user actions to be able to drag directly from the producible items and drop in the desired position in the production queue.

The same goes for researchable items from the research tree into the research queue.

**Comment by geoffthemedio** [comment]
Somewhat duplicates https://github.com/freeorion/freeorion/issues/784
