### ISSUE TITLE
Ship part exclusions not working for certain part ordering

### ISSUE THREAD

**Issue by Morlic-fo** [freeorion/freeorion#2260]
### Environment
Master as of 9439931

### Description
Consider a part A which excludes part B:
```
exclusions = ["B"]
```

When trying to add a new design, the "Add Finished Design" button is only grayed out if the excluded part B is in an earlier slot than the excluding part A.
This means you can actually add a design which has both part A and part B in it.

### Expected Result
Exclusions are respected regardless of part/slot order. You can not add a design with Part A and B in it if part A excludes part B.

### Steps to reproduce
1) Apply following diff:
```
diff --git a/default/scripting/ship_parts/Colony/CO_COL_OUTPOST.focs.txt b/default/scripting/ship_parts/Colony/CO_COL_OUTPOST.focs.txt
index a3affb1e8..bb16c6eca 100644
--- a/default/scripting/ship_parts/Colony/CO_COL_OUTPOST.focs.txt
+++ b/default/scripting/ship_parts/Colony/CO_COL_OUTPOST.focs.txt
@@ -1,6 +1,10 @@
 Part
     name = "CO_OUTPOST_POD"
     description = "CO_OUTPOST_POD_DESC"
+    exclusions = [
+        "CO_COLONY_POD" 
+        "CO_SUSPEND_ANIM_POD"
+    ]
     class = Colony
     capacity = 0
     mountableSlotTypes = Internal
```
2) Open the ship design screen
3) Select an empty Camouflage Asteroid Hull (or any other hull with at least 3 slots).
4) Add an outpost pod to one of the middle slots.
5) Add a colony pod to its left. You are unable to add the design as expected from the exclusions.
6) Move the colony pod to the right of the outpost pod. You are now able to save the design. This shouldn't happen.

**Comment by geoffthemedio** [comment]
Test with that pull request?
