### ISSUE TITLE
Obliterating an enemy AI prevents to finish turn

### ISSUE THREAD

**Issue by Oberlus** [freeorion/freeorion#2302]
* **FreeOrion Version**: 2018-10-07.feb528b
* **Operating System**: Windows 7
* **Graphic card used**: GTX 660
* **Fetched as**
  * Weekly development build

### Description
On the turn you completely eliminate an enemy AI empire, on hitting next turn game will stay waiting for that dead AI to finish before saving, so game won't continue. Clicking on resign exits without giving you time to click on the "exit without saving".
This happens consistently since at least a week before this weekly dev. build was published. The attached game is a second, different-settings game with latest week dev. build, but it also happened to me on Linux using compiled source from master around 10 days ago.

### Expected Result
Games doesn't wait on dead empires and continues.

### Steps to reproduce
Load attached game and click on next turn until issue happens (should be on turn 143, save is from turn 141 when combat on enemy (last) homeworld is going on).
[FreeOrion_Jugador_Humano_El_0141_20181016_174736.zip](https://github.com/freeorion/freeorion/files/2483923/FreeOrion_Jugador_Humano_El_0141_20181016_174736.zip)

**Comment by urshmost** [comment]
I just experienced this again in build 2018-10-27, in the situation where you invade a species' last planet, on the same turn that they build a last ship there.  
Example:
-turn 98: your fleet arrives at enemy capital planet and destroys their last fleet.
-turn 99: your troop fleet arrives and you click invade, and a last ship by the enemy is built.
-turn 100: the enemy's capital, their last planet, is captured, and then their last ship is destroyed.

The Messages window does not progress past "Waiting for Other Players" and the Empire window shows all players other than the one that you just defeated are finished their turns.  It also shows a 'Head on a Spike" icon for that empire that you just defeated.

This Situation Report shows, in sequence:

The Syndicate has been defeated!
The capital of the Syndicate empire has fallen.
On Royal Cor a I : there was a ground battle with Syndicate.
Royal Cor a I was captured by Terran Imperium.
At Cor a: there was combat with Syndicate
At Cor a: a Griffin was destroyed

Hope that helps!

**Comment by o01eg** [comment]
I suppose defeated empire shouldn't be processed after https://github.com/freeorion/freeorion/pull/2283

Do you have a server log?

**Comment by urshmost** [comment]
[hang on defeated empire.zip](https://github.com/freeorion/freeorion/files/2544176/hang.on.defeated.empire.zip)
freeorion.log and freeoriond.log attached in included zip file

**Comment by urshmost** [comment]
[AI_1.zip](https://github.com/freeorion/freeorion/files/2544195/AI_1.zip)

And here is the A! log file.
