### ISSUE TITLE
Unable to Recreate Deleted Ship Design

### ISSUE THREAD

**Issue by metablaster** [freeorion/freeorion#2322]
When a ship design is deleted the design still exist in "sll designs" tab in ship designer until end of game session.

If a player decides to recreate this design in same game session (same ship hull and same ship components) then the button "add finishied design" will read that this design is "a duplicate of existing design"

The issue can be easily reproduced by creating a new design, delete it and then try to create the very same design (hull and components) again (under same or different dame).

This has been discussed in following forum thread:
https://freeorion.org/forum/viewtopic.php?f=28&t=11119

**Comment by geoffthemedio** [comment]
Seemingly fixed by commits picked from https://github.com/freeorion/freeorion/pull/2387
