### ISSUE TITLE
Encyclopedia shouldn't automatically disclose private information about empire's research

### ISSUE THREAD

**Issue by o01eg** [freeorion/freeorion#2324]
### Environment

* **FreeOrion Version**: 0.4.8, master

### Description
Encyclopedia provides information about researched techs, available parts, hulls, buildings. Enemy could use this to match his strategy.

https://a.doko.moe/ymgjnn.png

### Expected Result
Enemies shouldn't known researched capabilities of empires.

### Steps to reproduce
* Start game.
* Make some turns enough to research several techs. 
* Open `Pedia` -> `[Game - Empires]` -> Any other empire.
* Issue occurs.

**Comment by geoffthemedio** [comment]
This is presently working as intended. There are no espionage mechanics implemented.

**Comment by Dilvish-fo** [comment]
To augment Geoff's answer a bit, it is expected that an espionage system would be implemented whereby access to some or all of that info would be gated (partly or entirely) by direct observation and/or espionage projects.

In the meantime, the consensus has been that there is no clearly good way to just not give that info-- simply not providing that info would mean that that all your meter reading tooltips for observed enemy ships and planets and whatnot would either be generally very wrong, or else full of the 'unknown' type meter corrections.

I suppose that for multiplayer games, for which we could reasonably assume the players are more experienced, having a multitude of 'unknown' type meter corrections in enemy meter observations could be an acceptable tradeoff for keeping such info more secret.

So, to put into place a somewhat more clear development plan in this area, we would (A) start with a GameRule to disable the enemy empire info entirely (and ensure that enemy meter observations are then properly presented with the actual value and 'unknown' contributions listed in the tooltips.  Empire Detection Strength could either still be shared, or else could be left unknown and would be difficult to even infer from observation.  (edit: probably the proto-EspionageManager should actually go in at this point, even though it would simply be gating info by the GameRule.)

Then (B) we could put into place a proto-EspionageManager, which would in this phase simply be tied into the visibility granting code, and grant knowledge of techs, parts, hulls and buildings when ships, planets & buildings dependent on such techs are actually observed.  Hopefully that wouldn't slow down the visibility determination process too much.  (Mere possession of something, particularly a building, wouldn't actually necessarily mean that the empire possesses the relevant tech; they could have captured it.  But we could rely on a fluff explanation that observation of the degree of skill with which the building/part/hull is being deployed allows the true knowlede or lack thereof of the relevant tech to be exposed.)

Then at some point (C) espionage projects could be added to provide a further path to enemy empire knowledge.

**Comment by o01eg** [comment]
I've looked into empire serialization code and it looks like even research and production queues are disclosed.
