### ISSUE TITLE
Building FreeOrion from source is very slow under VS 2017

### ISSUE THREAD

**Issue by OlafPettersson** [freeorion/freeorion#2340]
* **FreeOrion Version**: 0.4.8
* **Operating System**: Windows 10
* **Fetched as** 
  * Compiled from source

### Description
When Building FreeOrion from source under VS 2017, on my system it can take 20 to 25 minutes. Incremental builds with only small changes can also take > 5 min. This slows development enormously.

Are there any reasons why precompiled headers are not configured? On my system, after configuring precompiled headers - in VS this can be done without changing any source files - the build is much quicker.

I believe gcc also supports precompiled headers, though only with changes to the source files: https://gcc.gnu.org/onlinedocs/gcc/Precompiled-Headers.html.

**Comment by Vezzra** [comment]
@OlafPettersson, has this been sufficiently addressed by #2342? Can we close it as resolved?
