### ISSUE TITLE
Don't save orders before processing

### ISSUE THREAD

**Issue by o01eg** [freeorion/freeorion#2353]
### Environment
* **FreeOrion Version**: https://github.com/freeorion/freeorion/commit/4ee5f067f96a88caeb412a7c4a025a139003a71c
* **Operating System**: Gentoo Linux AMD64
* **Graphic card used**: GeForce GTX 750 Ti/PCIe/SSE2
* **Fetched as** 
  * Compiled from source

### Description
The server in state `WaitingForTurnEnd` accepts turn orders from client and then saves them into savegame before processing. It could lead to savegam contains incorrect orders like https://github.com/freeorion/freeorion/issues/2348
Shouldn't server save game before accept orders so incorrect ones wouldn't be included?

### Expected Result
The server doesn't store incorrect orders.

### Steps to reproduce
See https://github.com/freeorion/freeorion/issues/2348

**Comment by geoffthemedio** [comment]
The idea is that you can play part of a turn, save, quit, reload, and resume from the partly played turn.

**Comment by o01eg** [comment]
I'm not sure if it works because `WaitingForTurnEnd` requires to get all orders before save.

**Comment by geoffthemedio** [comment]
In what way doesn't it work?

**Comment by o01eg** [comment]
I missed there were substatuses in `WaitingForTurnEnd`.
