### ISSUE TITLE
Support Value(ValueRef::ComplexVariable) in FOCS

### ISSUE THREAD

**Issue by agrrr3** [freeorion/freeorion#2367]
One can use e.g. Value(Source.MaxSupply) to get the current meter value; without Value() you get the initial value.

In my understanding it is not possible to use Value(..) to retrieve the inital value of a complex valueRef, e.g. Value(ShipPartMeter part="SR_WEAPON_1_1" meter="MaxCapacity") - this should probably be supported for consistency.

**Comment by geoffthemedio** [comment]
Might / should work for part meters after https://github.com/freeorion/freeorion/commit/a3a0980b8b35146c456b6fb2c1c12e9f97a5c173


eg. `Value(ShipPartMeter part = "SR_WEAPON_1_1" meter = Damage object = Source.ID)`

**Comment by Vezzra** [comment]
@agrrr3, can you check if a3a0980b8b35146c456b6fb2c1c12e9f97a5c173 sufficiently addresses your feature request? Can we close this?

**Comment by geoffthemedio** [comment]
I'll assume yes...
