### ISSUE TITLE
snap package: license is `unset`

### ISSUE THREAD

**Issue by sumpfralle** [freeorion/freeorion#2369]
I cannot tell, who is the maintainer of [freeorion's snap package](https://snapcraft.io/freeorion), thus I decided to file the issue here. Please redirect me, if there is a more appropriate place.

Currently the snap package description (https://snapcraft.io/freeorion) describes the license of the game (and/or the packaging?) as `unset`.

**Comment by agrrr3** [comment]
I set it in the snapcraft to "CC-BY-SA-3.0 AND GPL-2.0" which is i think is the closest i can get to the real thing.

**Comment by sumpfralle** [comment]
Great - thank you for updating the description!

I think, this issue can be closed or do you see open details?

**Comment by agrrr3** [comment]
I see open details (different licenses for different parts of the
application), but I don't think there is a good solution given the options.
So the issue can be closed.
