### ISSUE TITLE
Missing ship_part icons in tech tree

### ISSUE THREAD

**Issue by Oberlus** [freeorion/freeorion#2371]
### Environment
* **FreeOrion Version**: 2019-02-03.23f627b
* **Operating System**: Windows 7
  * Weekly development build

### Description
I've just updated to latest test build, from one that was near two months old.
Many icons of ship_parts (and maybe others) are missing in the tech tree view. See attached image.
![missingicons_20190203-23f627b](https://user-images.githubusercontent.com/28650914/52240866-730d3780-28d2-11e9-8696-b096507363d9.png)

### Steps to reproduce
Start a game and check out the full research tree.

**Comment by geoffthemedio** [comment]
Works fine for me in master. Delete your config.xml and/or persistent_config.xml or check in the options/directories tab that the resources directory is pointing to the right place. Check also freeorion.log for errors about the image files not being found for hints.

**Comment by Oberlus** [comment]
I've deleted config.xml, there is no persistent_config.xml. Problem persists.
Resources directory is fine: D:/Installed Games/FreeOrion/default
I can't find any "not found" or "image" in freeorion.log. I attach freeorion.log after starting, checking ship_parts in the Pedia (icons are missing) and exiting.
[freeorion.log](https://github.com/freeorion/freeorion/files/2832038/freeorion.log)

The default/data/art/icon/ship_parts folder is full of healthy PNG images.
I don't know what's going on.

Edit: I've downloaded the previous test build: FreeOrion_2019-01-27.35c8071_Test_Win32_Setup.exe, and installed it over last one. The icons are shown fine.
Then I've reinstalled last version FreeOrion_2019-02-03.23f627b_Test_Win32_Setup.exe and the icons are missing again.
Then I've deleted that exe and downloaded again from sourceforge (just to be sure it's not corrupted from yesterday's download), reinstalled (23f627b over 23f627b) and the icons are still missing.

So definitively **there is a problem with FreeOrion_2019-02-03.23f627b_Test_Win32_Setup.exe**.

To be more specific:
Ship_part icons are not shown in Pedia, Design Window and Research Window.

**Comment by Vezzra** [comment]
Tomorrow (Monday) I should provide new test builds. @Oberlus, once they are out, can you test them and report back if the issue persists?

**Comment by Oberlus** [comment]
> Tomorrow (Monday) I should provide new test builds. @Oberlus, once they are out, can you test them and report back if the issue persists?

The issue persists. Exactly the same.

**Comment by Vezzra** [comment]
@Oberlus, #2383 got merged which supposedly fixed this issue. The fix will be included in next weeks test builds, please check again when they are out and report back if the issue has been solved or if it persists. In the latter case we need to reopen this issue.
