### ISSUE TITLE
Attack ValueRef always zero for ships

### ISSUE THREAD

**Issue by agrrr3** [freeorion/freeorion#2385]
While testing TopmostMatches i found that the Attack valueref did work for fighters but not for ships. As far as i can see it is zero for the ships (at least during combat).

And expected would be the total of all weapon damage.

**Comment by geoffthemedio** [comment]
I [added](https://github.com/freeorion/freeorion/commit/4f1c539cb30d56ad7a4541f8d050ae5d8e9ef8bb) a column to the object list, and it shows non-zero values for the default starting ship with weapons. Maybe something different happens in combat, though.

**Comment by agrrr3** [comment]
Yes, probably, i couldnt pinpoint that yet.
Also total weapon damage for fleets is off, it seems it does not take species modifiers into account.

**Comment by agrrr3** [comment]
I checked this again. And Attack is working for Ships in combatTargets conditions.

It might be that I was looking at the time at Target.Attack which does not work. Or that I was using a nested condition (but that should also have worked).
Using Source.Attack or LocalCandidate.Attack both work fine in combatTargets conditions.
