### ISSUE TITLE
Stop the game after having winners

### ISSUE THREAD

**Issue by o01eg** [freeorion/freeorion#2401]
### Environment
* **FreeOrion Version**: 0.4.8, master
* **Fetched as** 
  * Binary release
  * Weekly development build
  * Compiled from source

### Description
Currently the game continues after some players wins the game.

### Expected Result
Server notifies all player about winners and their victory reason.
Server shutdowns or went back to lobby depending on mode.

### Steps to reproduce
* Win the game.
* Make next turns.

**Comment by Vezzra** [comment]
It should at least remain an option to continue the game after victory conditions have been met.

**Comment by mmoderau** [comment]
So, a game rule then?

**Comment by TheSilentOne1** [comment]
How about a dialog à la Civ: "Just one more turn" / "Back to Main Menu"?

**Comment by Vezzra** [comment]
If that dialog has to be confirmed each turn, that would be quite annoying IMO. Game rule sounds fine to me.

**Comment by TheSilentOne1** [comment]
The dialog would ofc only appear once after a party has achieved victory. "Just one more turn..." is a joke about civ's addictive effect, it means "continue playing".

**Comment by Vezzra** [comment]
Oh, ok. Now I understand 😃

**Comment by mmoderau** [comment]
To elaborate, the "Just one more turn" option in Civ is a nod by developers to the One More Turn Syndrome.

Indeed, it only appears once, after the player achieves a victory condition.
