### ISSUE TITLE
Dark Red AI Colour Unreadable

### ISSUE THREAD

**Issue by Thinker55** [freeorion/freeorion#2411]
(see comments)

**Comment by Thinker55** [comment]
I am colorblind.  I can only barely make out the dark red color assigned to a race in the game system.  I find it hard to read messages and difficult to track things like fleet movements.  Can this be altered anywhere?  There does not seem to be a selector for it in options.  the color is too dark.  There will be others with this issue.

**Comment by Thinker55** [comment]
Sorry.  Build is 0.4.7.1, master branch as of 3/19/2019 (Build # reports as ???).  I compiled it today from the source, but the issue exists previous to this. OSS is OpenSuSE LEAP 15.  System is a VM, so video card is unk -- but it happens on my HP with the same OS and an ATI card. It exists in the latest Windows binary release, so it is general.The red is just too dull to read.

**Comment by Thinker55** [comment]
I went through forum threads and determined that this SHOULD be adjustable using the empire_colors.xml file in the /default directory.  However, it DOES NOT!  I have replaced the file with one from a thread, I have totally emptied the file of all color settings -- NOTHING changes the color set on this build!  Where else can it be getting colors?
I tried files from this forum thread:  https://www.freeorion.org/forum/viewtopic.php?f=25&t=8915&p=95040#p95040. 

I've attached a screenshot.  These are the only color set I get no matter what -- and the dark red or brown color is unreadable.
I have not seen any build issues, but I am getting a message that I believe indicates that even though I am in single player mode, the system is attempting multiplayer connections:

stephen@VMUtilLEAP:~> freeorion &
[1] 57141
stephen@VMUtilLEAP:~> Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock


![Screenshot from 2019-03-19 17-02-31](https://user-images.githubusercontent.com/45952457/54641599-f476ee80-4a68-11e9-9e58-e1d7bf802f1d.png)

**Comment by Thinker55** [comment]
I am beginning to suspect that the issue is that I compiled to /opt as root.  Was this a mistake?

**Comment by geoffthemedio** [comment]
The file works, so you're probably not editing the file it's loading.

If you previously had FreeOrion installed or built in another location, you might have a config.xml file in ~/.config/freeorion/

If so, delete that, or edit the resource directory in the in-game options.

FreeOrion has separate client and server programs. In a single player game, the client launches the server program and then communicates with it to send orders and get gamestate updates. This does not involve accessing the internet, unless you start a multiplayer game and connect to a remote server by specifying the IP address. For single player games, it only sends messages to localhost, your own machine.

**Comment by Thinker55** [comment]
This was my first install on this host, done as root in the /opt directory.  I have since recompiled out of my home directory -- and color changes work there.  I remember that on my first attempt, I compiled locally and copied everything to either /user/share or /opt -- and planet graphics failed to work, although everything was fine locally.  There must be some kind of environment issue.
