### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by ghost** [freeorion/freeorion#242]
With Slackware64 and ogre 1.8.1, freeorion 0.4.4 build normal after this [patch](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=783839;msg=19;filename=fix-FTBFS.patch;att=1).

But when run i get error message :

```
$ freeorion
Segmentation fault

$ cat ~/.freeorion/freeorion.log
2015-07-24 17:00:45,565 DEBUG Client : Logger initialized
2015-07-24 17:00:45,565 DEBUG Client : v0.4.4 [SVN ???] CMake
2015-07-24 17:00:45,694 DEBUG Client : OpenAL initialized. Version 1.1 ALSOFT 1.15.1Renderer OpenAL SoftVendor OpenAL Community
Extensions: AL_EXT_ALAW AL_EXT_DOUBLE AL_EXT_EXPONENT_DISTANCE AL_EXT_FLOAT32 AL_EXT_IMA4 AL_EXT_LINEAR_DISTANCE AL_EXT_MCFORMATS AL_EXT_MULAW AL_EXT_MULAW_MCFORMATS AL_EXT_OFFSET AL_EXT_source_distance_model AL_LOKI_quadriphonic AL_SOFT_buffer_samples AL_SOFT_buffer_sub_data AL_SOFTX_deferred_updates AL_SOFT_direct_channels AL_SOFT_loop_points AL_SOFT_source_latency
```

**Comment by geoffthemedio** [comment]
Release candidate builds for v0.4.5 are expected within the next week or two, and FreeOrion has since moved from Ogre to SDL. Whatever issue this is, it's unlikely to get any attention at this point. If you can reproduce similar problems in the latest git, then please reopen.

**Comment by ghost** [comment]
Now work with 0.4.5 pre-release test build (gaf01).
