### ISSUE TITLE
GG::Spin ignores disabled status

### ISSUE THREAD

**Issue by o01eg** [freeorion/freeorion#2425]
### Environment
* **FreeOrion Version**: master
* **Operating System**: Linux
* **Graphic card used**: NVIDIA
* **Fetched as** 
  * Compiled from source

### Description
If I disable some spins in UI they get gray but value changed if mouse wheel rotated.

### Expected Result
Disabled spins don't change their value.

### Steps to reproduce
* Call `Disable(true)` on spin.
* Rotate mouse wheel over it.

**Comment by geoffthemedio** [comment]
Should be fixed by https://github.com/freeorion/freeorion/commit/efb570bdc88b78e556f76f5100fea510fa526045
