### ISSUE TITLE
Storing cookie for server by IP address violates XML standart

### ISSUE THREAD

**Issue by o01eg** [freeorion/freeorion#2449]
### Environment

* **FreeOrion Version**: 0.4.8, master
* **Operating System**: Any
* **Graphic card used**:
* **Fetched as** 
  * Binary release
  * Weekly development build
  * Compiled from source

### Description
When cookies stored for server addresses by IP for example "147.135.99.147" it becomes 

```xml
    <server>
      <cookie>
        <147>
          <135>
            <99>
              <147>Some long UUID</147>
            </99>
          </135>
        </147>
      </cookie>
      <uri>localhost</uri>
    </server>
```

This breaks options parsing and violates XML standard: https://www.w3schools.com/xml/xml_elements.asp

> Element names must start with a letter or underscore

### Expected Result
Servers addressed by IP doesn't break options.

I suppose it should be some encoding applied to server address so it will become correct xml element.

### Steps to reproduce
* Login to server by IP.
* Open options.xml

**Comment by geoffthemedio** [comment]
Here: https://github.com/freeorion/freeorion/blob/master/client/human/HumanClientFSM.cpp#L347

it generates the name of an option from the IP address, rather than storing the server address as a value.

**Comment by o01eg** [comment]
@geoffthemedio  It was done to store cookies for different servers.

**Comment by geoffthemedio** [comment]
Sure, but presumably a more XML-compatible encoding scheme is possible... Like making the option name for `147.135.99.147` be `ipv4_147_135_99_147` or similar. Supporting ipv6 keys like `ipv6_2001_0db8_0000_0042_0000_8a2e_0370_7334` would also be good.
