### ISSUE TITLE
Linux clients crash on connecting to multiplayer slow-game server

### ISSUE THREAD

**Issue by Oberlus** [freeorion/freeorion#2475]
### Environment
* **FreeOrion Version**: Several recent builds, including snap and compiled from master. Attached logs are for 2019-06-11.470d071 compiled from master.
* **Operating System**: Ubuntu 16.04.

### Description
For some players, FreeOrion clients on Linux crash to desktop when joining the slow-game multiplayer server (freeorion-lt.dedyn.io). o01eg is playing the same game with no problems.
Check out this thread in the forum: https://www.freeorion.org/forum/viewtopic.php?f=2&t=11274&start=60#p95995

### Expected Result
No crash.

### Steps to reproduce
IFAIK, you need to be a player of an ongoing game to be able to join, and the password goes to your email, so you can't reproduce this unless you talk to o01eg to join a game, etc. And then cross fingers to be affected by the bug.

Attached freeorion.log with trace enabled for "client general", "server general" and "log", and the gdb stack traces for the many exceptions that arise, with comments to indicate player's inputs.

[freeorion.log.zip](https://github.com/freeorion/freeorion/files/3275571/freeorion.log.zip)
[freeorion_gdb_catch_throw_bt.txt](https://github.com/freeorion/freeorion/files/3275574/freeorion_gdb_catch_throw_bt.txt)

**Comment by o01eg** [comment]
Log shows failure happened in deserialization UI data.
It could be caused either boost serialization 1.58 - 1.65 incompatibility ( there is a good candidate `boost::optional` ).
At least if we want to maintain some compatibility I think it possible to reorder serialized fields, move UI data to the end, and allow to fail when deserializing UI data.

**Comment by Oberlus** [comment]
Not sure if this is relevant, just in case, there are these two warnings when compiling that mention "initialized after [-Wreorder]":

```
In file included from /home/lucas/Projects/FreeOrion/freeorion/network/ServerNetworking.cpp:1:0:
/home/lucas/Projects/FreeOrion/freeorion/network/ServerNetworking.h: In constructor ‘PlayerConnection::PlayerConnection(boost::asio::io_context&, MessageAndConnectionFn, MessageAndConnectionFn, ConnectionFn)’:
/home/lucas/Projects/FreeOrion/freeorion/network/ServerNetworking.h:333:37: warning: ‘PlayerConnection::m_disconnected_callback’ will be initialized after [-Wreorder]
     ConnectionFn                    m_disconnected_callback;
                                     ^
/home/lucas/Projects/FreeOrion/freeorion/network/ServerNetworking.h:329:37: warning:   ‘bool PlayerConnection::m_valid’ [-Wreorder]
     bool                            m_valid;
                                     ^
/home/lucas/Projects/FreeOrion/freeorion/network/ServerNetworking.cpp:55:1: warning:   when initialized here [-Wreorder]
 PlayerConnection::PlayerConnection(boost::asio::io_context& io_context,
 ^
[...]
In file included from /home/lucas/Projects/FreeOrion/freeorion/server/ServerApp.cpp:1:0:
/home/lucas/Projects/FreeOrion/freeorion/server/ServerApp.h: In constructor ‘ServerApp::ServerApp()’:
/home/lucas/Projects/FreeOrion/freeorion/server/ServerApp.h:321:47: warning: ‘ServerApp::m_chat_history’ will be initialized after [-Wreorder]
     boost::circular_buffer<ChatHistoryEntity> m_chat_history; ///< Stored last chat messages.
                                               ^
/home/lucas/Projects/FreeOrion/freeorion/server/ServerApp.h:317:29: warning:   ‘bool ServerApp::m_turn_expired’ [-Wreorder]
     bool                    m_turn_expired;         ///< true when turn exceeds its timeout
                             ^
/home/lucas/Projects/FreeOrion/freeorion/server/ServerApp.cpp:79:1: warning:   when initialized here [-Wreorder]
 ServerApp::ServerApp() :
 ^
```

**Comment by o01eg** [comment]
I've opened server so this issue and some other could be tested.

**Comment by o01eg** [comment]
Looks like deserialization of UI data could be broken on the server too:

```
2019-06-12 21:06:34.862501 [trace] network : ServerNetworking.cpp:301 : Server received message from player id: 1 of type Turn Orders and size 11505
2019-06-12 21:06:34.862748 [debug] server : Message.cpp:941 : deserializing orders
2019-06-12 21:06:34.862931 [debug] server : Message.cpp:943 : checking for ui data
2019-06-12 21:06:34.862955 [debug] server : Message.cpp:946 : deserializing UI data
2019-06-12 21:06:34.872078 [error] server : Message.cpp:957 : ExtractTurnOrdersMessageData(const Message& msg, ...) failed! Message probably long, so not outputting to log.
Error: std::bad_alloc
```

**Comment by o01eg** [comment]
Looks like it could break when restoring UI data
```
11:27:36.003601 {0x00000870} [trace] FSM : humanclientfsm.cpp:865 : Restoring UI data from save data...
11:27:36.084448 {0x00000870} [trace] FSM : humanclientfsm.cpp:830 : (HumanClientFSM) ~WaitingForGameStart
11:27:36.084448 {0x00000870} [trace] FSM : humanclientfsm.cpp:621 : (HumanClientFSM) ~PlayingGame
```

**Comment by Oberlus** [comment]
I've found others are having trouble using boost 1.65+ serialization:

https://github.com/boostorg/serialization/issues/104

E.g.:
https://github.com/dealii/dealii/issues/5262 (they solved the issue banning 1.65+)

**Comment by geoffthemedio** [comment]
FreeOrion doesn't use `boost::singleton` so I think that issue shouldn't apply.

**Comment by Oberlus** [comment]
I was able to connect to the slow-game server using my linux, compiled from master with PR 2480 just merged.
Server wasn't restarted or updated in any way, so whatever made my linux builds to crash on connection has been fixed or hidden by that PR.

**Comment by geoffthemedio** [comment]
The [server was updated](http://sourceforge.net/projects/freeorion/files/FreeOrion/Test/FreeOrion_2019-06-16.ecb7a95_MacOSX_10.9.dmg/download) to the latest test build (2019-06-16.ecb7a95), so that may also have been necessary.

**Comment by geoffthemedio** [comment]
If you could post freeorion.log from after connecting to a server, that would be useful.

**Comment by Oberlus** [comment]
> The [server was updated](http://sourceforge.net/projects/freeorion/files/FreeOrion/Test/FreeOrion_2019-06-16.ecb7a95_MacOSX_10.9.dmg/download) to the latest test build (2019-06-16.ecb7a95), so that may also have been necessary.

o01eg said I had not updated or restarted server.

Attached log of successful connection, right after getting to the game (not playing nor exiting):
[freeorion.log](https://github.com/freeorion/freeorion/files/3304508/freeorion.log)

When I couldn't connect, the error was always about bad allocation.

**Comment by o01eg** [comment]
> o01eg said I had not updated or restarted server.

I've updated server. Could you try again?

**Comment by Oberlus** [comment]
> I've updated server. Could you try again?

The log I posted above is from a connection this morning (it was turn 17).
I've connected again now with same results (i.e. OK).

Only weird thing I see is that the server name (freeorion-lt.dedyn.io) is deleted after each connection. With Windows (when it didn't fail), player and server names were remembered for next session, but now it only remembers player name.

**Comment by o01eg** [comment]
Looks like some option file issue.

**Comment by Oberlus** [comment]
Should I close this issue?

**Comment by o01eg** [comment]
@Oberlus No, looks like @TheSilentOne1 still has issue.

**Comment by o01eg** [comment]
Looks like #2480 didn't help. UI data still fails: https://freeorion.org/forum/viewtopic.php?p=96287#p96287

What about to merge #2479 ?

**Comment by Oberlus** [comment]
> Looks like #2480 didn't help. UI data still fails: https://freeorion.org/forum/viewtopic.php?p=96287#p96287

I think it did help, at least with my problem in this issue.
Actually, I had two problems, one with the Linux client (CTD on connect to server, from game turn 1), and one with the Windows one (CTD after some turns have been played). This last one I think is the same that @TheSilentOne1 is having too (he gets it earlier in the game, turn 16, for me it happens later).

Maybe second problem should have its own issue. BTW, there are no logs or stack traces in this thread that correspond to that problem (there are only in the forum thread, from The Silent One).

**Comment by o01eg** [comment]
https://freeorion.org/forum/viewtopic.php?p=96304#p96304
Looks like something here was break between boost version as well:

```cpp
std::unordered_map<std::string, int> obsolete_ship_parts
```

**Comment by o01eg** [comment]
My `obsolete_ship_parts`:
```xml
	<obsolete_ship_parts class_id="120" tracking_level="0" version="0">
		<count>0</count>
		<bucket_count>159871</bucket_count>
		<item_version>0</item_version>
	</obsolete_ship_parts>
```

TheSilentOne's obsolete_ship_parts:
```xml
	<obsolete_ship_parts class_id="115" tracking_level="0" version="0">
		<count>0</count>
		<bucket_count>68460391</bucket_count>
		<item_version>0</item_version>
	</obsolete_ship_parts>
```

Magnate's one:
```xml
	<obsolete_ship_parts class_id="114" tracking_level="0" version="0">
		<count>0</count>
		<bucket_count>608903</bucket_count>
		<item_version>0</item_version>
	</obsolete_ship_parts>
```

Oberlus's one:
```xml
	<obsolete_ship_parts class_id="119" tracking_level="0" version="0">
		<count>1</count>
		<bucket_count>1447153</bucket_count>
		<item_version>0</item_version>
		<item>
			<first>FT_HANGAR_1</first>
			<second>38</second>
		</item>
	</obsolete_ship_parts>
```

**Comment by geoffthemedio** [comment]
Not clear that a different `bucket_count` indicates an incompatibility in the serialization...

**Comment by o01eg** [comment]
Yes, look like it calls `std::unordered_map::rehash` with very big value and fails to allocate buckets. I'm checking it in savegames when bucket count became to grow.

**Comment by o01eg** [comment]
Looks like it steady grows each turn. Maybe if rehash it before serialization and after deserialization with lesser bucked count it will stop to grow.

**Comment by geoffthemedio** [comment]
or put it into a `std::map` before serializing... or just make it a `std::map`, and perhaps add a rule that nothing that will be serialized should be stored in anything from C++11 or later, which serialization apparently doesn't support very well.

**Comment by o01eg** [comment]
I'm not sure if it related to C++11. I think it grows somewhere else and then boost for some reason tries to reproduce internal structure.

**Comment by geoffthemedio** [comment]
My point is that the older structures / contains - pre C++11 - are probably more reliably serialized than the newer stuff, since they've been around longer and generally less "fancy".

**Comment by Oberlus** [comment]
I no longer have any problem.
Can/should I close this?

**Comment by o01eg** [comment]
Looks like it works now.
