### ISSUE TITLE
lost connection

### ISSUE THREAD

**Issue by yorev** [freeorion/freeorion#2489]
[see next comment]

**Comment by yorev** [comment]
win10 x64
8go memory
v0.4.8

i have this trouble often and most of the time all the save game give the same result so i have to abandon and begin a new game.
when i try to load a save game, that begin to show the map then it's crashing and i have the message "lost the connexion to the server"

as asked by oberlus in forum
https://www.freeorion.org/forum/viewtopic.php?f=25&t=11188

i give the logs with trace options
[freeorion.zip](https://github.com/freeorion/freeorion/files/3318054/freeorion.zip)
[logs3.zip](https://github.com/freeorion/freeorion/files/3318055/logs3.zip)

**Comment by geoffthemedio** [comment]
When you write "all the save game give the same result", do you mean all saves regardless of when they were made or the galaxy setup settings cause this crash when being loaded, or a particular game will eventually have this error when loading saves for it? Have you tried smaller games? The log files suggest that save has at least 500 systems and 20 AIs. Does this issue also happen with smaller galaxies and fewer AIs?

**Comment by yorev** [comment]
i mean all the autosave and manualy from 1 game in particular, give the same result, after turm 300 it's begining risky.

often but not every time, i had played some games where i didn't had troubles untill the end.

I never tryed small galaxies, so i can't say

**Comment by Vezzra** [comment]
@yorev, try switching to binary saves, that sometimes helps alleviating such issues. AFAIK, the problem is that with very large games saving/loading compressed XML can cause out of memory issues - @geoffthemedio?

**Comment by yorev** [comment]
Thanks Vezzra

but i do this without change, i also undo compressed xml
i had surveyed the memory while it was loading and the memory's use stay at max 50%

**Comment by geoffthemedio** [comment]
Can you post the save (compressed xml format) that produces the issue? I don't recall all the fixes and changes to saving and loading since 0.4.8 but having a test save would be helpful to diagnose it, to hopefully check if the issue should already be fixed.

**Comment by yorev** [comment]
i have begined new game
i had saved this old turn which was not bugging, but thr turn after 407 was buged
[scy406.zip](https://github.com/freeorion/freeorion/files/3425206/scy406.zip)

**Comment by geoffthemedio** [comment]
From the save, I think the issue is that the combat logs are too big to serialize, and it throws an exception when trying to do so, which isn't caught locally, so effectively crashes the server. I can relatively easily fix it so that won't crash, but it will instead just send no logs.

**Comment by yorev** [comment]
as far i remind, the bug appear even when there is no battle

**Comment by geoffthemedio** [comment]
Even if there is no battle on a particular turn, it still saves (and thus serializes) information about battles that occurred previously, so that you can go back in the stirep and review the battle results from previous turns. So, it can fail to allocate memory for the serializing even if it's re-serializing a battle from a previous turn.

**Comment by yorev** [comment]
no logs it's ennoying, may be it would be better to send only the last combat's logs and erase the previous.
by this way the game would not be bugged only 1 turn

**Comment by geoffthemedio** [comment]
I think I have a fix that lets the game continue without problems. The patch / pull request would need to be applied to v0.4.8 to load that save without issues.

**Comment by yorev** [comment]
where can i find this patch, please?

**Comment by geoffthemedio** [comment]
56155467aee328b3b5602bcaae5fc24b9e549c40 might be all that is needed

**Comment by yorev** [comment]
thanks, but how i use it under windows with v0.4.8 ?

**Comment by TheSilentOne1** [comment]
If you are not able to compile the source yourself, the easiest solution will probably be to grab the next weekly build (provided by Vezzra) from this thread: https://www.freeorion.org/forum/viewtopic.php?f=2&t=4208&start=525

**Comment by yorev** [comment]
thanks, i will wait next build;

but if somebody could pm me how to do to compile i will be very gratefull to learn

**Comment by TheSilentOne1** [comment]
To start: https://www.freeorion.org/index.php/Compile
For help: https://www.freeorion.org/forum/viewforum.php?f=24

**Comment by geoffthemedio** [comment]
Depending how much help you need, start with https://github.com/freeorion/freeorion/blob/master/BUILD.md

You can cherry pick that commit with git, or manually make those changes to the code and compile. Note that you want the v8 SDK for building v0.4.8.  MSVC 2015 is also recommended for compatibility.

Getting the next test build won't help with a v0.4.8 save file.

**Comment by yorev** [comment]
i have tryed last build 2019-08-27.e0efd35
and it's still impossible to load, still msg lost connection

[freeorion.log](https://github.com/freeorion/freeorion/files/3549615/freeorion.log)
[freeoriond.log](https://github.com/freeorion/freeorion/files/3549616/freeoriond.log)

**Comment by geoffthemedio** [comment]
Your server log says
`UpdateCombatLogs returning 3959 logs to player 1`
This indicates the relevant patch was not applied, as with the patch, it should not send more than 50 logs in a single message.

https://github.com/freeorion/freeorion/commit/56155467aee328b3b5602bcaae5fc24b9e549c40

The version string on line 13 of freeoriond.log also says it's 2018-08-23-26f16b0 v0.4.8

I'm surprised it can even start loading the file actually... As I wrote above I doubt that will work. You need to patch and build v0.4.8.
