### ISSUE TITLE
Provide a way for external application to get information about playing game

### ISSUE THREAD

**Issue by o01eg** [freeorion/freeorion#2497]
### Environment
* **FreeOrion Version**: any
* **Operating System**: any

### Description

I want to get information from the server about playing game current turn, time before turn advance, game UID and so on to show it on both my servers. Currently there no API for external application to interact with the server.

### Expected Result

The server provides API to get playing game status.

**Comment by geoffthemedio** [comment]
Any ideas about how to implement this? Just output to monitor the server, or polling and response messages? Network-like messages similar to the client-server communication? Server status file being written every time something changes?

**Comment by o01eg** [comment]
> Any ideas about how to implement this?

Just a vague ideas. Maybe something Boost.Beast and some compatible Json serialization, but Boost.Beast isn't available in the minimal supported boost version and Boost.Serialize doesn't support JSON at all.

> Just output to monitor the server, or polling and response messages?

I suppose some polling is better. It doesn't have to be often.

> Network-like messages similar to the client-server communication?

Maybe, but Boost.Serialize is unsuitable for interaction with non-C++ application.

> Server status file being written every time something changes?

No. I think it works poorly with turn remaining time.

**Comment by geoffthemedio** [comment]
Network messages don't need to use Boost serialization... Depending on the sort of data being requested, just returning the text strings, binary-encoded numbers, or numbers as text should cover most cases, except if lists or more complex data structures are needed.

**Comment by Oberlus** [comment]
> > Server status file being written every time something changes?
> 
> No. I think it works poorly with turn remaining time.

Even if what you save is the **date** and time for next turn?
(edited)

**Comment by o01eg** [comment]
Yes, it looks better. I'll try to use Boost.Property to get some JSON.

**Comment by geoffthemedio** [comment]
As mentioned here, https://github.com/freeorion/freeorion/pull/2427

External application messaging can be done by extending the UDP discovery server.

One can set up, for example, a Python script to send a UDP message to the IP and discovery port of a freeoriond process, with the server discovery inquiry message, and can get back the UDP reply message. 
 
In the Python interpreter:
````
>>> import socket
>>> UDP_IP = '127.0.0.1'
>>> UDP_PORT = 12345
>>> MESSAGE = 'Yo, can I play Free-O here, dog?'.encode('utf-8')
>>> s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
>>> s.sendto(MESSAGE, (UDP_IP, UDP_PORT))
32
>>> data, addr = s.recvfrom(1024, 0)
>>> print(data)
b'Word!Fiona'
````

In freeoriond log:
````
15:02:10.061132 {0x00003020} [debug] network : ServerNetworking.cpp:432 : Discovery server received from: 127.0.0.1:50434
message: Yo, can I play Free-O here, dog?
replied: Word!Fiona
````

The discovery server can be extended to supply an interface for other queries...

I'd be reluctant to do this with arbitrary JSON, however, as that could potentially introduce security vulnerabilities.

**Comment by geoffthemedio** [comment]
https://github.com/freeorion/freeorion/pull/2536 implements a way to get info from the server, but with limited info available. Additional info can be made available, but I'd need a list of what to provide...  Is there anything more than is mentioned in the issue description above?

**Comment by Vezzra** [comment]
@o01eg, @geoffthemedio, bump? What's the status of this? Is #2536 considered to be a sufficient implementation of the features requested? Can this issue be closed as resolved?

Or, as @geoffthemedio already asked, should more infos be provided, and should this stay open?

**Comment by geoffthemedio** [comment]
More info is certainly needed... so far just a framework for a few bits of mostly unnecessary info is in place... extra server-specific support for the sorts of info @o01eg wants are needed, but I don't know what specific info is important.

**Comment by o01eg** [comment]
@Vezzra, I suppose it could be closed. If I need more info within new interface I'll open a new issue.
