### ISSUE TITLE
Allied supply breaks supply network

### ISSUE THREAD

**Issue by o01eg** [freeorion/freeorion#2500]
### Environment
* **FreeOrion Version**: 993d1ba46
* **Operating System**: Gentoo Linux AMD64
* **Graphic card used**: NVIDIA GeForce GTX 750 Ti
* **Fetched as** 
  * Compiled from source

### Description

In configuration {Empire A's capital} - {Empire B's planets} - {Empire A's outpost} where A and B are allied it is impossible to start building for colony.

### Expected Result

Empire A can build colony on its output.

### Steps to reproduce
* Start multiplayer game with two players and small map.
* Make players allied.
* Place colony of second player between capital and outpost of the first player.
* Issue occurs.

**Comment by o01eg** [comment]
As I see in `Supply.{h,cpp}` only `SupplyManager::FleetSupplyableSystemIDs` checks for allies.

**Comment by geoffthemedio** [comment]
What `FleetSupplyableSystemIDs` does is irrelevant, I think. The the `ResourceSupplyConnected` condition, which is used for location and cost calcuations for colony buildings, uses its own determination of whether two objects are connected, based on resource supply groups within an empire, which I think ignores allied connections. I'll see about rewriting it to use something within `SupplyManager` that (via a parameter) does take into account allied connections.

**Comment by geoffthemedio** [comment]
hmm... looking at it more, I'm not sure why there's a problem. The networks should be merged for purposes of what stuff is supply connected...

**Comment by TheSilentOne1** [comment]
From when it occured in the multiplayer game, it seemed to me the issue was that actually there was no supply connection. My supply didn't extended to o01eg's outpost, so he couldn't build a colony (while I could when I had an outpost and he had supply in a different system). What I thought was strange is that my supply should have, but did not extend into his 0 supply outpost.

**Comment by o01eg** [comment]
Yes, I've just check save game and found out if I research Orbital Construction I can build colony here.
[FreeOrion_0017_20190709_055407.mps.zip](https://github.com/freeorion/freeorion/files/3437951/FreeOrion_0017_20190709_055407.mps.zip)
