### ISSUE TITLE
Don't use outdated translations from rarely maintained string tables

### ISSUE THREAD

**Issue by adrianbroher** [freeorion/freeorion#251]
Requesting cherry picking of commit 1d8946f3 to release-0.4.5 branch.

Most string tables are not maintained properly and may contain untranslated items (in english) which are not in sync with the latest english entry.  This can lead to outdated or wrong translations even if there is a more recent english entry available.  The mentioned commit removes such completely untranslated items.

**Comment by Vezzra** [comment]
Makes sense. Anyone any objections? Otherwise I'm going to do the cherry pick.

**Comment by MatGB** [comment]
Tidying up the stringtables is something that needs doing, so go ahead and do it, English and French are good, I have zero clue as tot he status of the others and some look horrifically outdated.  Better to not have one than to have one that's wrong, which is likely the case in some of them.

**Comment by Vezzra** [comment]
Done, 183fdf15f0ce5e751a789221131bd117c2cae6c5.
