### ISSUE TITLE
Fuel Efficiency Issues with Self Grav Hulls

### ISSUE THREAD

**Issue by urshmost** [freeorion/freeorion#2521]
### Environment
Build 2019-7-30 win32

### Description
The self grav hulls now has a fuel rating of 1.5, and fuel efficiency of 60% which gives them a max fuel value of 0.9. This somehow allows them to travel within your supply range, but as soon as they leave it they are stranded.

Sitting at .9 fuel, every self grav ship, on every turn, generates a message stating that they now have sufficient fuel to travel again, but because it appears to be capped at .9, they really don't.

### Expected Result
I would expect the message that a ship has enough fuel to travel to not be generated when the ship ultimately will not have sufficient fuel.
I would expect that any ship design should have at least a minimum fuel of 2 or 3, otherwise you are effectively forcing extra fuel tanks to always be necessary, and at that point what is the reason over just giving the design more fuel and taking away a slot?

**Comment by agrrr3** [comment]
The need for the supply network for less than one fuel is intended. The big hulls need their supply networks (or good fuel tech) to operate.

The message should definitley be fixed. 

Besides of this this is a UI and balancing issue. A part of the balancing was kept as fuel efficiency was applied to all ships' base fuel (so the big hulls only have a fourth of fuel before). 

Difference between taking away a slot while adding base fuel vs adding a fuel part is that fuel part bonus increases better fuel tech. I am undecided if it is possible to design ships with less than one max fuel are an issue or not.
Maybe all ships designs should be able to return to supply network. Maybe in many hulls this is a tradeoff between having an extra internal slot. And having good fuel pilots or energy metabolism tech also can kick the hull over the 1 fuel barrier without sacrificing the slot.

**Comment by geoffthemedio** [comment]
Could perhaps use `floor(...)` to round down rather than having fractional fuel values.

**Comment by agrrr3** [comment]
> Could perhaps use `floor(...)` to round down rather than having fractional fuel values.

That is great idea for 0.x max fuel  (floor it to zero max fuel) - for other fractionals i would like to get some feedback from playtesting first (see the discussion in [New Fuel Settings](https://www.freeorion.org/forum/viewtopic.php?f=28&t=11321&p=96805#p96805)

**Comment by agrrr3** [comment]
Oberlus brought one real change of concept up - before it was always possible to refuel and do a jump if you are out of supply. This is currently not possible anymore - you would have to extend your supply to reach the ship or research energy metabolism.

**Comment by geoffthemedio** [comment]
Did #2538 resolve this?

**Comment by Vezzra** [comment]
@urshmost, bump?

**Comment by Morlic-fo** [comment]
Not resolved. 

Scattered Asteroid Hull has 0.6 fuel
Titanic Hull has 0.9 fuel

**Comment by agrrr3** [comment]
> Not resolved.
> 
> Scattered Asteroid Hull has 0.6 fuel
> Titanic Hull has 0.9 fuel

Ye foul things how didst ye escape my grep?

**Comment by Vezzra** [comment]
I assume #2566 fixed this issue? @agrrr3?

**Comment by agrrr3** [comment]
As far as I know this is fixed. If something else comes up we can reopen.
