### ISSUE TITLE
Migration to Python 3?

### ISSUE THREAD

**Issue by subpop** [freeorion/freeorion#2522]
Fedora is planning on retiring Python 2. FreeOrion was flagged as a package that depends on Python 2.7. I know a portion of the project uses Python for AI and scripting. Are there plans to support or upgrade to Python 3?

**Comment by o01eg** [comment]
Yes, it's already planned: https://freeorion.org/forum/viewtopic.php?f=9&t=11181

**Comment by subpop** [comment]
Oh excellent. Thank you. I will follow the discussion on the forum.
