### ISSUE TITLE
Please tell players how price rise.

### ISSUE THREAD

**Issue by jinlan** [freeorion/freeorion#2523]
Does price rise because I have a lot of ships?
Does price rise because I have a lot of money?
Does price rise because I have a lot of stars?
......

Can I avoid price rise by build a few big ships instead of a lot of small ships?

**Comment by TheSilentOne1** [comment]
Currently the number of ships will increase production cost (it's in one of the .FOCS files). We have plans to switch the production cost to an influence upkeep.
It certainly wouldn't hurt to have some documentation of the current mechanism until it is changed.

**Comment by geoffthemedio** [comment]
There is an article in the in-game pedia, "Fleet Upkeep" that describes this mechanic. It can be searched for by name, or found by links from the index page by: *Game Concepts* -> Ship Management -> Fleet Upkeep
