### ISSUE TITLE
Game Crash on Win7

### ISSUE THREAD

**Issue by jinlan** [freeorion/freeorion#2524]
It happens after I pressed "end turn" button, so it probably happens in AI turn. 
No Seen error message.  Mouse icon becomes "busy" icon, when I "alt-tab" to desktop, there's an "app stopped" window, when I press "OK", game killed.
My version is :  2019-08-04
My [Log files and config.xml](https://github.com/jinlan/issue/blob/master/FreeOrion_CrashLog.7z)
My [save](https://github.com/jinlan/issue/blob/master/FreeOrion_CrashSave.7z)

---------------------------------------------------------------------------------------------
Loaded the save and ended turn again, no longer crash.

**Comment by jinlan** [comment]
Maybe it's my hardware problem. Should I close this issue?

**Comment by geoffthemedio** [comment]
I also don't get a crash when loading the save and pressing the turn button a few times.
