### ISSUE TITLE
Ship designed with Quantum Energy Hull doesn't appear in build list

### ISSUE THREAD

**Issue by jinlan** [freeorion/freeorion#2525]
Designed several ship with QE hull, but it doesn't appear in the build list. I can't build it.
That stars has Energy Compressor, can build energy fighter ( the small energy hull ).
I tried different stars different species, all can build small energy hull, but can not see QE hull ships.

-----------------------------------------------
My version : 2019-08-04

**Comment by TheSilentOne1** [comment]
On the production screen, click on "unavailable", look for your design in the porduction list, and look what condition is not met (red).

**Comment by jinlan** [comment]
Thank you, it can only be built in blue and black star. I think we can close this issue now.
