### ISSUE TITLE
AI has occupied my Gas Giant star

### ISSUE THREAD

**Issue by jinlan** [freeorion/freeorion#2533]
It's about 80 turns, I don't think he has the tech to see my 45 stealth stars.
In player list window, it indicates that he has 30 stealth detection.
I checked my star detail, it's 45 stealth.

My version is : 2019-08-12
My save : https://raw.githubusercontent.com/jinlan/issue/master/FreeOrion_Ego_Ego_stealth.7z

**Comment by Morlic-fo** [comment]
Unless something else happens on your system, the AI does not see you here. It was trying to invade the Ancient Guardian planet (Aurinko I, the desert one).

For whatever reason, it does not send sufficient troops for that task, though.

**Comment by Vezzra** [comment]
> For whatever reason, it does not send sufficient troops for that task, though.

That, however, is a different issue, right? As the original issue apparently isn't actually an issue, can this be closed?

**Comment by Morlic-fo** [comment]
> As the original issue apparently isn't actually an issue, can this be closed?

Yes.
