### ISSUE TITLE
GG::DropDownList incorrectly shows long lines

### ISSUE THREAD

**Issue by o01eg** [freeorion/freeorion#2545]
### Environment
* **FreeOrion Version**: 0.4.8, master
* **Operating System**: Gentoo Linux AMD64
* **Graphic card used**: NVIDIA GeForce
* **Fetched as** 
  * Compiled from source

### Description
In a drop list all items are trimmed by control width:

![fo1](https://user-images.githubusercontent.com/397177/64490076-38052500-d262-11e9-92be-21ff2b997e76.png)

If long item was chosen it shows without trim and overlaps with other controls:

![fo2](https://user-images.githubusercontent.com/397177/64490084-405d6000-d262-11e9-881d-34c44ee67bbc.png)

### Expected Result
Drop list width adjusted with its content. Chosen item in the control is trimmed by control width.

### Steps to reproduce
* Choose language with long words like a Russian.
* Chose new game in the main menu.
* Open "Test" page in the game rules.
* Click on "Test string" drop down list.

**Comment by geoffthemedio** [comment]
This is a controllable behaviour, not a bug...

The `Row` class can have `SetChildClippingMode(ClipToClient)` called to make it clip its contents, and droplist overrides like `CUIDropDownList` can have the same done to avoid rendering over the drop arrow.

I'll do this in master for `CUIDropDownList` and `UserStringRow`.

https://github.com/freeorion/freeorion/commit/5330d47616afe4fdecbe0aae363fb4b19b54174a
https://github.com/freeorion/freeorion/commit/85e726204f0505fe3693423bb2597887b3377c57

**Comment by o01eg** [comment]
@geoffthemedio  I suppose it should clip only selected text, not the drop list. It isn't shown when inactive.

**Comment by geoffthemedio** [comment]
The modal picker is handled separately...
