### ISSUE TITLE
Ask for confirmation to leave without sending orders in the multiplayer game

### ISSUE THREAD

**Issue by o01eg** [freeorion/freeorion#2551]
### Environment

* **FreeOrion Version**: master
* **Fetched as** 
  * Binary release
  * Weekly development build
  * Compiled from source

### Description
In the multiplayer game the player could forgot to send his orders before close client: https://www.freeorion.org/forum/viewtopic.php?p=97201#p97201
I suppose there should be some confirmation to ensure player want to disconnect from the game without set his empire to ready.

### Expected Result
In the multiplayer game show confirmation dialog to ask if the player want to leave the game if his empire is unready.

**Comment by geoffthemedio** [comment]
This is a would-be-nice but not a requirement for v0.4.9, I think.

**Comment by Vezzra** [comment]
Ok

**Comment by o01eg** [comment]
It looks like it was fixed in #2594
