### ISSUE TITLE
Allied supply: simple case

### ISSUE THREAD

**Issue by magnate** [freeorion/freeorion#2554]
* **FreeOrion Version**: f39038e
* **Operating System**: Windows
* **Graphic card used**: RadeOn 5750
* **Fetched as** 
  * Binary release
  * Weekly development build

### Description
When two planets in the same system belonging to different empires have equal supply, neither connects to adjacent supply. This is ok in the non-allied case, but not for allies.

### Expected Result
When the two empires are allied, they share supply so it should extend and connect to adjacent supply. Since they are allied, it doesn't really matter which empire actually gets the supply to that system (and it should reset to unconnected as soon as the alliance is dissolved).

### Steps to reproduce
1. Have a spare planet in your supply network, in a system where you have an outpost or colony on a larger planet
2. Let your ally place an outpost or colony on the spare planet
3. Wait until the supply on his planet equals the supply on your planet - the system will suddenly be cut off from your supply network, reconnecting if his supply then exceeds yours on the following turn.

**Comment by TheSilentOne1** [comment]
In our current game, this supply behaviour does have a significant impact on game-play.

**Comment by geoffthemedio** [comment]
I've implemented an intended but overlooked missing feature, which is to break supply ties by considering a few other factors, as of c7dabb70b64a45d80e7477629301f9ec8ff0707c. Now, supply ties should be broken by considering total supply in system, total max supply in system, and total empire supply, in cases where the in-system supply between two empires is the same. This should hopefully prevent most issues for allies in the same system... please report about whether it's working.

**Comment by geoffthemedio** [comment]
Also added a tie-breaker for the allied case. 4927f44dd586cccb8a88d33e230b23dee176afa3

**Comment by TheSilentOne1** [comment]
Thanks and good work!
