### ISSUE TITLE
Sitrep inaccurate when System Defence Mines 2 is researched

### ISSUE THREAD

**Issue by magnate** [freeorion/freeorion#2555]
### Environment

* **FreeOrion Version**: f39038e
* **Operating System**: Win 7
* **Graphic card used**: RadeOn 5750
* **Fetched as** 
  * Binary release
  * Weekly development build

### Description

My sitrep says "Mines caused 2 damage to the fleet ...."

They actually caused 6 damage, because he researched that tech this turn

Somehow the sitrep is using old tech data

Or maybe the bug is that they shouldn't cause 6 damage until next turn?

### Expected Result

Sitrep should say "Mines caused 6 damage ...."

Or the mines should only cause 2 damage ...

### Steps to reproduce

Have ships in orbit at enemy system on the turn he completes research on System Defence Mines 2.

**Comment by agrrr3** [comment]
This is a backend problem. Currently it is not possible to have the right
sitrep in the turn you finish research.

The solution I am working on delays the effect application one turn so
sitrep and effect are in sync.

See #2370

**Comment by agrrr3** [comment]
@magnate can you check if #2370 solves this? or please provide a save game the turn before the enemy completes the new mines technology

**Comment by magnate** [comment]
Yes o01eg has confirmed that we have saves from all turns so I will upload the right one here.

**Comment by agrrr3** [comment]
@magnate bump?

**Comment by magnate** [comment]
[FreeOrion_0076_20190916_175441.gz](https://github.com/freeorion/freeorion/files/3722126/FreeOrion_0076_20190916_175441.gz)

Ok, there is the save file from turn 76 - Oberlus (yellow, Eaxaw) researches System Defence Mines 2 on turn 77 so I think this is the file you want. I am blue (Abbadoni). 

Incidentally I have not zipped the file, just renamed it from .mps to .gz to bypass github's pointless and irritating refusal to accept it as is.

Hope this helps.

**Comment by agrrr3** [comment]
Tested with the mps - sitrep and mines damage are in sync (i think damage 6 starting in turn 78).
So can be closed.
