### ISSUE TITLE
Inconsistent behaviour for speed of new ships

### ISSUE THREAD

**Issue by magnate** [freeorion/freeorion#2557]
### Environment
* **FreeOrion Version**: latest weekly build
* **Operating System**: Win7 (and Win10)
* **Graphic card used**: unknown
* **Fetched as** 
  * Binary release
  * Weekly development build

### Description
New ships appear at their home system with a speed that includes the bonus from any interstellar lighthouse in the system, but not the bonus from interstellar logistics - this does not appear until the following turn. 

Note that I do not know whether the logistics speed bonus is actually used during movement that turn, but it is not shown on the ship details at the start of the turn. For that matter I don't know whether the lighthouse bonus is used either, but I assume so.

### Expected Result
Either both speed bonuses should be shown on the turn the ship is built (my preference), or both should not take effect until the following turn.

### Steps to reproduce
1. Research interstellar lighthouse
2. Build interstellar lighthouse at the shipyard
3. Research interstellar logistics
4. Build a new ship at the shipyard

**Comment by agrrr3** [comment]
Could not reproduce. Always get both the bonus on a newbuild ship. 
But actually the value without any of the bonus is shown in the ship/fleet view - if you look at the mouseover both effects are correctly applied.

**Comment by Oberlus** [comment]
> Could not reproduce. Always get both the bonus on a newbuild ship.

Strange.
I have never built lighthouses (I'm starting now), but I am used to the fact that newbuilt ships does not get the bonus of interstellar logistics until next turn (common scenario for me is robo hulls: the old ones show 95 speed int he fleet/ship, showing 75+20 for the correct reason when mouse hover; and the robo hulls built current turn show just 75 in both places, meter and emerging tooltip). This behaviour is consistent for as long as I can remember (0.4.7+).

I'd love the effect to be applied to newbuilt ships on the turn they are built. A bit less micromanagement.

**Comment by magnate** [comment]
Weirdly I am now seeing the same behaviour as agrrr3, namely that *neither* is added to the new ship's speed but both are shown on the tooltip. Hmmm, I swear I have never seen this before today!

**Comment by magnate** [comment]
Ok, I can now confirm that *neither* bonus is applied if the new ship moves on the turn it is built, so the current behaviour is correct albeit perhaps undesirable.

My apologies for the mistaken report - I was confusing the turn the ship is built with the turn the lighthouse is built - that's what gives the weird behaviour, presumably because the building of the lighthouse triggers the speed bonus on all ships including the newly built one.

**Comment by geoffthemedio** [comment]
So should this be closed and marked invalid?

**Comment by magnate** [comment]
> So should this be closed and marked invalid?

Depends whether you'd prefer I open a new issue for the turn the lighthouse is built, or recast this one. There is a bug, it's just not the one I thought it was!

**Comment by geoffthemedio** [comment]
New would perhaps be cleaner...
