### ISSUE TITLE
Fleet Upkeep Multiplier not calculating correctly.

### ISSUE THREAD

**Issue by alleryn** [freeorion/freeorion#2558]
### Environment
* **FreeOrion Version**:549e43d
* **Operating System**:Win 10 Home
* **Fetched as**
  * Compiled from source

### Description
The Fleet Upkeep Multiplier is giving an incorrect result.

### Expected Result
Correct result.

### Steps to reproduce
* Start a game Free Orion
* Check how many ships you have
* Calculate how much another ship should cost based on fleet upkeep

**Comment by alleryn** [comment]
There is a problem in the upkeep.macros file:

https://github.com/freeorion/freeorion/blob/4927f44dd586cccb8a88d33e230b23dee176afa3/default/scripting/common/upkeep.macros#L4-L11

is not returning the right result.  Specifically the attempt to break the rule up with `(1 - (GameRule name = "RULE_SHIP_PART_BASED_UPKEEP")) *` and `(GameRule name = "RULE_SHIP_PART_BASED_UPKEEP") *` doesn't seem to work.

I edited the upkeep.macros file into two separate versions and those seem to work for each case:
[upkeep.zip](https://github.com/freeorion/freeorion/files/3639503/upkeep.zip)

**Comment by Vezzra** [comment]
@alleryn:

> I edited the upkeep.macros file into two separate versions and those seem to work for each case

Can you open a proper PR for that patch?

**Comment by alleryn** [comment]
> @alleryn:
> 
> > I edited the upkeep.macros file into two separate versions and those seem to work for each case
> 
> Can you open a proper PR for that patch?

It isn't a proper patch.  I don't know how to make it work with just one upkeep.macros file.  It's one file that works for standard upkeep rules, and one file that works for parts-based upkeep rule.

**Comment by alleryn** [comment]
Just to clarify a little, the problem seems to be that 

`GameRule name = "RULE_SHIP_PART_BASED_UPKEEP"`

does not appear to be evaluating to 1/0 when the rule is enabled/disabled.  I don't know why, or if this is even expected behavior (though it is intuitive and presumably the intention of the formula as currently written).

**Comment by o01eg** [comment]
This rule was introduced in https://github.com/freeorion/freeorion/pull/2100 and I suppose @geoffthemedio fixed toggle issue with calculation https://github.com/freeorion/freeorion/commit/c33186dabd9cab3480460b669dffd59c1d09d65d
Is it back again?

**Comment by alleryn** [comment]
I'll check that version to see if it's working for me there, and if so try to bisect to see if i can find where the problem returned.

**Comment by alleryn** [comment]
I've been bisecting using weekly test builds.  Looks like the part based rule was absent in the 2018-8-13 build, and present in the 2018-9-23 build, when fleet upkeep was not working (at least for me).

(I don't have any indication fleet upkeep was ever working since the introduction of the part-based rule).

It's not clear to me that the semantic structure mentioned above:
`GameRule name = "RULE_SHIP_PART_BASED_UPKEEP"`
should necessarily be expected to work as one might expect. (I.e. for this "toggle" rule to behave like a boolean function and return true/false value that equate to 1/0.)

In trying to figure it out i'm lost in the parser.

So that's where i'm at with this.

**Comment by alleryn** [comment]
I have a fix now.

There was no problem with `GameRule name = "RULE_SHIP_PART_BASED_UPKEEP"`, as i had surmised.  That was evaluating correctly.

There was a missing pair of parentheses around
`ShipDesignsOwned empire = Source.Owner `

I should have a PR up shortly.

**Comment by alleryn** [comment]
Fixed in 0cfeb38b5cb4038f1a8bd41c82873b4003be94eb
