### ISSUE TITLE
Value() in scope condition is useless and misleading

### ISSUE THREAD

**Issue by agrrr3** [freeorion/freeorion#2576]
This issue was named 'Less-than operator for ValueRefs seems broken. Also Value() in scope condition.'
I found out the less-than operator is not broken and that the Value() does not return the current value is to be expected. 

So this issue is now what to do with Value() in scope.. conditions. 

The original text:
I found an unexpected issue with the latest commit which sets the max fuel to zero if the ship has 0.x fuel:
 The max fuel in the ship design window is always zero. 

I was thinking and concluded that I my effect was using the initial value but needed the current one.

So I tried to fix it by using 
`(Value(Source.MaxFuel) < 1)` instead of `MaxFuel high = 0.9999` in the condition.

I also tried `effects = If condition = (Value(Source.MaxFuel < 1)) effects = SetMaxFuel value = 0` instead of filtering in the scope condition.

But it seems Value(Source.MaxFuel) < 1 is always evaluating to true.

Trying further I found the following logically equivalent condition to be working:
`effects = If condition = Not (Value(Source.MaxFuel) >= 1.0) effects = SetMaxFuel value = 0`
as well as `effects = If condition = Not (Value(Source.MaxFuel) >= 1) effects = SetMaxFuel value = 0`

Using that in the scope condition did not work:
```
                //Not (Value(Source.MaxFuel) >= 1.0) // Always is true
                // Not (Value(Source.MaxFuel) >= 1) // Always is true
                // (Value(Source.MaxFuel) < 1) // Always is true
```

It seems the less-than operator is buggy!

And - I am not sure - usage of Value in the scope condition does not seem to work.
I guess it should (?)

**Comment by geoffthemedio** [comment]
Is this an issue with less than or with `Value( ... )` wrapping?

I suspect that using `Value( ... )` wrappers in scope and activation conditions for a Max meter will always return 0. Max and Target meters are reset to 0 before effects are evaluated, so at the time of evaluating scope and activation conditions, they will be 0. Even if using priorities to order the execution, the scope and activation conditions are all evaluated in a separate earlier step. So probably don't do that.

The result of using `Value( ... )` wrapping within an effect will depend on when it's evaluated, relative to other effects that modify the meter.

**Comment by agrrr3** [comment]
I had a look again at the C++ code and it is completely good and sane.
So i tried again with (Value(Source.MaxFuel) <1 ) in the If condition.... and it works.

Luckily I copy'n'pasted the non-working string here into the issue. 
I f** up the parenthesis in the original. Jeez

Gotta hurry, so will later check on the condition.
Will check on the condition later - the evaluation order explanation makes sense at least - should put that in the wiki.

**Comment by agrrr3** [comment]
Note a github strangeness occurred and code from openening a new PR is shown in #2577 now

When looking at the log of freeorion/master I recognized that the version which got merged contained and older commit which did not solve the problem. Probably i did force push from the wrong work space.
I will put up a new PR with the correct code.

**Comment by agrrr3** [comment]
Hi, I renamed the issue - the question left is what to do with Value() in scope and activation conditions.

First it should get documented in the wiki that you can use Value() in the effects to get the immediate/current value instead of the initial value.

Second, if i understand correctly that Value(XXX) in activation and scope conditions always returns the initial value. If i understood @geoffthemedio  right, all activation and scope conditions get evaluated before any effects are applied.

If that is so we should signal using Value() in those contexts as an error to the FOCS scripter. But I do not know what the right mechanism for that is. I can think of:
* allowing Value() expressions only in effects in the parser
* Writing a SitRep and a log entry if such a Value is applied outside of effects .  

both could be a pain to implement though.

**Comment by agrrr3** [comment]
I added some info about the Value() expression in the scripting details wiki page: that Value() can be used to get the current value for meters and shippart meters in valueRefs .

**Comment by geoffthemedio** [comment]
Title is wrong now... `Value()` always does return the current value of the meter.

But, the current value for max and target meters and unpaired metes is the reset value of 0 at the time scope conditions are evaluated. For paired meters, the current value (then) should be the same as the initial value, which is the value at the end of the previous turn or whatever the meter was default set to when an object was created.

Within effect executions, however, the current value of meters will depend on what effects have been executed at the time an effect executes.

**Comment by agrrr3** [comment]
That is nicely explained, that is how it works and could go in a documentation of gotchas.

But if writing Value(XXX) always has the same result as writing XXX that is highly misleading, there is no point in writing Value(XXX). So if one writes Value(XXX) one probably intends something different and just does not understand evaluation correctly.

I changed the title to better express this.

**Comment by geoffthemedio** [comment]
Or it's part of a macro that gets used in multiple places...

**Comment by agrrr3** [comment]
Thanks for the relabling that fits better. 
So does a macro make sense which has a Value() expression in it and is used in activation/scope conditions? I mean in real content. Basically i am arguing that even if the text in the macro may be the same, the meaning/intention would be different.

**Comment by geoffthemedio** [comment]
I don't have an example, but it's plausible it could be useful...

**Comment by agrrr3** [comment]
> I don't have an example, but it's plausible it could be useful...

I think it is possible that one would find a use for but for 99% of those situations one would find another comparable solution without this. So i think its possible but it is definitely not plausible to me that we would want such a use. 

This is your call of course, so i will close this until more people complain that they were hitting this which i consider very unlikely given the current number of FOCS contributors.

**Comment by Vezzra** [comment]
@agrrr3, closed as "resolved", or "invalid" (or something else)?

**Comment by agrrr3** [comment]
It's neither resolved nor invalid.
We need more data / insights from actual usage before we know if it is a
relevant issue. So 'speculative' or 'wedontcareyet' or 'insignificant' or
'maybevalid' or 'maybeinvalid' or 'notnow' or something similar

**Comment by Vezzra** [comment]
@agrrr3, these kind of "states" would be reflected by leaving the issue open, with no milestone assigned, and tagged as "low priority". So in this case I'd suggest to just reopen the issue (no milestone and low priority are already set).
