### ISSUE TITLE
Building unlock sitrep delays 1 turn

### ISSUE THREAD

**Issue by o01eg** [freeorion/freeorion#2578]
### Environment
* **FreeOrion Version**: e1bf2509b4012a6d38754381757fe39eb70c16fd
* **Operating System**: Windows 7 x64
* **Graphic card used**: AMD
* **Fetched as** 
  * Compiled from source

### Description
I've started to research The Physical Brain at 1st turn, and at 3rd turn I got sitrep about it was researched and successfully add Automated History Analyzer into production queue but sitrep about this building was unlocked I got at 4th turn.

Save game and logs:
[fo-send.zip](https://github.com/freeorion/freeorion/files/3665750/fo-send.zip)

### Expected Result
Player should get both the tech researched and the building unlocked sitrep at the same turn.

### Steps to reproduce
* Start a new game.
* Start to research The Physical Brain.
* Next turn until it was researched.

**Comment by geoffthemedio** [comment]
Hopefully fixed by https://github.com/freeorion/freeorion/commit/1c393c652b70a682ee7d26e9c99c6ac81f02b79a

**Comment by agrrr3** [comment]
@geoffthemedio Oh, i was working in parallel on this.
With your implementation the initial sitreps are off. See #2579
