### ISSUE TITLE
Starting warship fleet starts in "Hide" mode

### ISSUE THREAD

**Issue by alleryn** [freeorion/freeorion#2583]
### Environment
* **FreeOrion Version**:2681499 (Oct 1 2019 weekly test build)
* **Operating System**: Win 10 Home
* **Fetched as** 
  * Weekly development build

### Description
The starting Battle Fleet containing one Frigate Ms (SD_MARK_1) starts out in Hide mode instead of Control System ("aggressive") mode.

### Steps to reproduce
* Just start a new singleplayer game

**Comment by alleryn** [comment]
Working in 68097cd
Broken in next commit 614982b
Diff: https://github.com/freeorion/freeorion/compare/68097cd..614982b

Relevant code (i think):
https://github.com/freeorion/freeorion/blob/a06fe840db372d892142ecf0da54270e3271faf8/universe/Effect.cpp#L46-L61

In particular:
https://github.com/freeorion/freeorion/blob/a06fe840db372d892142ecf0da54270e3271faf8/universe/Effect.cpp#L58

And
https://github.com/freeorion/freeorion/blob/08d52df67381aa7cf599eb8e2bd801afa8f03d0a/universe/Fleet.cpp#L661-L664

Which depends on `Ship::IsArmed(`), which was changed in the relevant commit.

**Comment by geoffthemedio** [comment]
Hopefully resolved by https://github.com/freeorion/freeorion/commit/40f884b28ea6a7286391088913865c077f08cf63
