### ISSUE TITLE
Stealthy ships detected at start of combat

### ISSUE THREAD

**Issue by magnate** [freeorion/freeorion#2610]
### Environment
* **FreeOrion Version**: 4f372cb
* **Operating System**: client win7, server Debian buster
* **Graphic card used**: n/a
* **Fetched as** 
  * Compiled from source

### Description
My stealthy ships are being attacked on the first round of combat - I'm not seeing the "initially Foo empire cannot detect Bar, Baz" line in the combat log. 

### Expected Result
My ships have 35 stealth (symbiotic hulls with electromagnetic dampers). My enemy has 30 detection strength, and no lighthouses. There are no ion storms nearby. My expectation is that my ships will not be detected until the end of the first combat round, and therefore will not be targeted in the first round. 

### Steps to reproduce
Attached are the save files before and after such a combat. 
[FreeOrion_0097_20191026_033809.gz](https://github.com/freeorion/freeorion/files/3774709/FreeOrion_0097_20191026_033809.gz)
[FreeOrion_0098_20191026_084344.gz](https://github.com/freeorion/freeorion/files/3774710/FreeOrion_0098_20191026_084344.gz)

**Comment by magnate** [comment]
Btw those saves are not zipped, just rename them to .mps

**Comment by magnate** [comment]
Incidentally this is new, it was not happening in the fourth MP game a few weeks ago.

**Comment by magnate** [comment]
Ok I see from change logs that this appears to have been implemented quite recently - f39038e51 refers to being able to turn it off! I'm afraid I don't know where to find all the game rule syntax - is it on the wiki somewhere?

**Comment by geoffthemedio** [comment]
What do you mean by game rule syntax?

There should be a setting in the single player setup screen to adjust the rule. For a server there is no simple UI.

**Comment by magnate** [comment]
No I know that, there's a file called persistent_config.xml into which you can put all the game setup data, but I can't find a page that tells you the correct syntax for the switches. There's a finite list of config switches that can go in that file, and I'd really like to see them on a wiki page somewhere. I'll happily write it if it doesn't exist, if I can find the info!

**Comment by magnate** [comment]
Ok I found it in the single player UI, it's called "Aggressive Ships Combat Visible", I've never seen this before. How do I set it in a multiplayer game? I presume I need to set it in persisten_config.xml, yes?

**Comment by magnate** [comment]
Sorry, closing as an invalid ticket. I had no idea this was a new feature.

**Comment by geoffthemedio** [comment]
Setting rules in the multiplayer setup UI is a missing feature. Not sure how it would be done for a hostless server.

**Comment by o01eg** [comment]
@geoffthemedio For hostless server it could be done by administration with configuration https://github.com/freeorion/freeorion/pull/2424
