### ISSUE TITLE
Stealthy ships detected when not aggressive

### ISSUE THREAD

**Issue by magnate** [freeorion/freeorion#2614]
### Environment
* **FreeOrion Version**: 4f372cb
* **Operating System**: server: debian buster, client: win7
* **Graphic card used**: n/a
* **Fetched as** 
  * Binary release (client)
  * Weekly development build (client)
  * Compiled from source (server)

### Description
While working out why #2610 was not in fact a bug, I realised that there is a different bug. In this same game, where my cloaked attacking ships are hit on the first round of combat, they are hit even if not aggressive. This is definitely a bug - if they are set to hide, they should not be visible, if their stealth exceeds the enemy detection (which it does). 

### Expected Result
Hidden stealthy ships should not be visible and should not get shot at. 

### Steps to reproduce
1. Build a ship with higher stealth than the enemy
2. Set it to hide
3. Move it into a system with an aggressive enemy capital ship

**Comment by geoffthemedio** [comment]
Test save to reproduce would be helpful...

**Comment by geoffthemedio** [comment]
@magnate bump?

**Comment by magnate** [comment]
[FreeOrion_0106_20191026_194952.zip](https://github.com/freeorion/freeorion/files/3843467/FreeOrion_0106_20191026_194952.zip)

Here it is, sorry for the wait. It's not zipped, just rename it to mps. One of my "cloakeroo" ships is moving into a deep space system, hidden, and gets killed when this turn processes - it's not seen on the first combat round, so the game knows that it's not aggressive, but it still fights.

**Comment by geoffthemedio** [comment]
Haven't looked at the same, but is there a third empire with ships or planets in the system that could be starting a fight that your ship gets drawn into, after which it starts shooting and reveals itself?

**Comment by o01eg** [comment]
@magnate I've opened this save in https://github.com/freeorion/freeorion/commit/4f372cb7a79115e8dd28658fab542b3ca0d51974

If I left it as is I get combat next turn in deep space between Mirphak and Nexus:

![fo-combat](https://user-images.githubusercontent.com/397177/68874985-2123f880-0713-11ea-8064-72fa304aaccd.png)

Your ships won't detected first round.

If I set them to hide I don't get combat here.

Do you mean other deep space system?

**Comment by magnate** [comment]
No that is the right system, and there is no third empire. But if you are not getting combat when they hide that means they are aggressive, and that means the AGGRESSIVE_SHIPS_VISIBLE rule is not triggering - they should be detected first round if they are aggressive. So I think your config is not the same as mine. 

In my turn log, I only had one ship there - Salk and not Hedgehog, so I must have moved Hedgehog - and it was not detected, therefore it was not aggressive.

Though I confess I am confused about when and how rule changes take effect. At some point we turned off the AGGRESSIVE_SHIPS_VISIBLE rule so maybe we turned it off on or before turn 106. That gives me an idea for a new ticket. I'm not sure what to do about this one, maybe close it and I'll reopen it if I see it again?

**Comment by o01eg** [comment]
Rules I have after loading this savegame: 
![fo-rules](https://user-images.githubusercontent.com/397177/68883351-e8d7e680-0721-11ea-8106-92c520959ded.png)

**Comment by magnate** [comment]
Ok then I think I messed up here. When I opened this ticket I was convinced it had happened, but I've been through every turn log and this is the only one where I lost a cloaked ship, and it must have been set to aggressive, and I must have not noticed/realised it was after the rule change, so I opened this in error. Sorry folks.
