### ISSUE TITLE
Suggestion: allied repair

### ISSUE THREAD

**Issue by magnate** [freeorion/freeorion#2615]
### Environment
* **FreeOrion Version**: none
* **Operating System**: all
* **Graphic card used**: n/a

### Description
Allied drydocks should repair ships of allies as they do your own ships. 

### Expected Result
Ships resting for a turn in a system with an allied drydock get repaired exactly as if they rested in a home system.

(How do I tag this as a suggestion?)

**Comment by Vezzra** [comment]
> (How do I tag this as a suggestion?)

Depends on what you mean by that. If you want to request a certain feature, then do more or less what you've done here: open an issue with a description of the desired feature (putting "[feature request]" into the subject line is a good idea too).

If you merely want to open a discussion about an idea you have and want to hear what others think about it, then open a corresponding thread on our forum would be the way to go.

**Comment by magnate** [comment]
Thank you, that makes sense.

**Comment by Vezzra** [comment]
Ok, can anyone confirm that for sure? @magnate?

**Comment by magnate** [comment]
Sorry I haven't had a situation to test it yet, but I expect to in the current game!

**Comment by agrrr3** [comment]
Note that there is a rule which enables this (not sure about the current
game)

And in master, you or your ally need s a certain policy enabled

**Comment by Oberlus** [comment]
This is implemented and tested. Can be closed.

**Comment by Vezzra** [comment]
@Oberlus, had this already been already included into 0.4.10?

**Comment by o01eg** [comment]
It was fixed in 0.4.9 https://github.com/freeorion/freeorion/pull/2674

**Comment by Vezzra** [comment]
Ok, I see, that means we just forgot to close this issue back then. Alright, will try to set the milestone accordingly...
