### ISSUE TITLE
Server unconditionally listens on a UDPv6 port for discovery requests

### ISSUE THREAD

**Issue by Vezzra** [freeorion/freeorion#2626]
The following issue has been reported by @spikethehobbit on the forum:

### Environment

* **FreeOrion Version**: 6e933988d858e7ccf5832db72ac0afcd63bc1f9f
* **Fetched as**
  * Compiled from source

### Description

Since pull request #2536 was merged, the server unconditionally listens on a UDPv6 port for discovery requests. This causes two problems:

First, single player games should not be listening for server discovery since they should not be accepting LAN connections.

Second, requiring IPv6 breaks single player on IPv4-only machines because the server crashes on startup:

```
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >'
  what():  open: Address family not supported by protocol
Aborted
```
The problem commit is 6e933988d858e7ccf5832db72ac0afcd63bc1f9f.

Forum thread: https://www.freeorion.org/forum/viewtopic.php?f=9&t=11408

**Comment by geoffthemedio** [comment]
As asked on the linked thread:

> Why is this a problem? The point is to enable interprocess communication, to query the server, whether that's on the same system or otherwise.

Crashing on IPv4-only machines is an issue, though.
