### ISSUE TITLE
diplomatic message indicator not appearing (longturn server)

### ISSUE THREAD

**Issue by TheSilentOne1** [freeorion/freeorion#2633]
On the longturn server, send a peace or alliance proposal to a player your empire is at war with. The player receiving the offer should see the diplo status indicator in the empires window, but it doesn*t appear.

**Comment by TheSilentOne1** [comment]
@o01eg : could this be related to the issue with the "player online" indicators?

**Comment by o01eg** [comment]
@TheSilentOne1 Yes, it possible doesn't find "player online" if player disconnected or something.

**Comment by TheSilentOne1** [comment]
What I meant is, if I recall correctly, you recently fixed the player online indicators not updating, and I thought maybe this could be fixed in a similar fashion.

**Comment by o01eg** [comment]
@TheSilentOne1 Did you try to do it in the current fifth game? Diplomacy is disabled in this game:
```
Allowed diplomacy : RULE_DIPLOMACY_FORBIDDEN_FOR_ALL
```

**Comment by TheSilentOne1** [comment]
No, I already noticed it on the game(s) before. We can try on the next game again.

**Comment by o01eg** [comment]
Yes, I've tried vanilla game and empire window doesn't show incoming diplomacy request while adding "Accept" to the menu.
