### ISSUE TITLE
Ship hulls do not state fuel efficiency in Pedia

### ISSUE THREAD

**Issue by alleryn** [freeorion/freeorion#2637]
The information on each Pedia page for ship hulls (e.g. SH_BASIC_SMALL_DESC in stringtable) does not state the fuel efficiency of the hull.

**Comment by agrrr3** [comment]
Should be fixed by #2627 which is already merged, would be good if you can confirm :)

**Comment by alleryn** [comment]
> Should be fixed by #2627 which is already merged, would be good if you can confirm :)

Yep, confirmed!

Sorry about that.  Didn't realize my information was outdated.  Issue is resolved and may be closed.
