### ISSUE TITLE
AI _ratings should use cost squared (at least for war ships)

### ISSUE THREAD

**Issue by agrrr3** [freeorion/freeorion#2641]
@freeorion/ai-team  I am not sure about this, but reading the AI code I think that the ratings used to by the AI to decide if a ship design is better than another do use `1/adjusted_production_cost` instead of `1/adjusted_production_cost^2`.

E.g. from WarShipDesigner class `combat_rating * speed_factor * fuel_factor / self._adjusted_production_cost()` and combat rating is basically `my_total_attack * my_structure`

In the discussions about how to (link TBD) there was broad consensus that using linear cost is way wrong and squared cost is a better measure.

p.s.: @Vezzra  I am not sure that freeorion/ai-team works (gives a 404), but maybe I am just not allowed to see it. Also it looks different when Vezzra adds it.

**Comment by Morlic-fo** [comment]
It does. https://github.com/freeorion/freeorion/blob/master/default/python/AI/ShipDesignAI.py#L1641

**Comment by agrrr3** [comment]
Ah it was hiding in the middle of the inheritance hierarchy! Thanks!
