### ISSUE TITLE
Graph selection does not persist from turn to turn

### ISSUE THREAD

**Issue by toolforger** [freeorion/freeorion#2642]
### Environment
* **FreeOrion Version**: 0.4.8
* **Operating System**: Xubuntu 19.10
* **Graphic card used**: Nvidia
* **Fetched as**
  * Binary release

### Description

When I have the Graph window open, the selected graph will be replaced by the list of graphs from one turn to the next.

### Expected Result

The selected graph should stay, just as it stays for Pedia pages.

**Comment by geoffthemedio** [comment]
I don't observe this issue in the latest master or v0.4.8.

I quick start a game, click the graphs button, click the Rough Estimate of Total Military Strength link to open that graph, hit turn several times, and it stays showing that graph, updating from turn to turn.

**Comment by toolforger** [comment]
Feel free to close it then. I'll just reopen if I find the next release on my distro still has it.

**Comment by geoffthemedio** [comment]
I'd like some other reports indicating if anyone else has the issue, or a more detailed description of what steps lead to the issue for you... ie. does it always happen, including doing exactly what I described, or just after some other series of clicks?

**Comment by toolforger** [comment]
Steps:
- Status window is open (as is usual after a new turn)
- I do my usual fleet & production management commands
- I activate the "Graphs" window (top-right symbol group)
- I select "Rough Estimate of Total Military Strength"
- I start the next turn
... mmm, ok, it's still there
- I call up some Pedia entry -> Graph window now becomes the Pedia window
- I click on the Graphs window again
- Pedia winow now becomes the Graphs window again but shows the graph selection list.

So I have to clarify: the selected graph gets lost whenever the window is being reused.
There also was some strange issues with the Graphs symbol switching between colored and greyed state. I couldn't reproduce well enough (and maybe I was misobserving anyway, so there's that).

**Comment by geoffthemedio** [comment]
Clicking the graphs button always takes you to the graphs list, regardless of what's being shown in the pedia, including a graph... that's working as intended.

**Comment by toolforger** [comment]
Mmm... my point would be that it's more valuable to me to return to a graph that I found useful in the last turn, rather than the list of graphs (which is easy to recover via the "Up" button anyway).
YMMV, obviously :-)
