### ISSUE TITLE
Cannot build Self-Grav or Titanic hulls

### ISSUE THREAD

**Issue by magnate** [freeorion/freeorion#2645]
### Environment
* **FreeOrion Version**: 4f372cb (longturn server and client same version)
* **Operating System**: server - Debian Buster, client - Win7
* **Graphic card used**: n/a
* **Fetched as**
  * Binary release - client
  * Weekly development build - client
  * Compiled from source - server

### Description
Very weird one this. We've all researched gravity and titanic hulls, and players noz and rosiebint have built the geo-doodah facility. (So they can put them in their build queues, though I can't.) We can each design self-grav hulls and add them to our finished designs, but the following turn those designs have disappeared. If the design is put into a build queue, the queued build disappears too. We have all confirmed this with self-grav hulls. rosiebint has had the same happen with Titanic hulls, and noz has had it happen with Scattered Asteroid Hulls. 

Organic and energy hulls seem to work fine. The AI is running around with dozens of self-grav and titanic hulls (Sovereignty and Seigniory respectively). 

Oh and here's the real weirdness: noz can put a "stock" self-grav into a build queue, and it will build. This is the pre-made template design. But no design that he makes himself. 

### Expected Result
When you save a self-grav design in the Finished Designs list, it should persist and be there next turn. When you put one in a build queue, it should get built and not disappear. 

### Steps to reproduce
1. Load the save as noz, rosiebint or me. 

2. Open the ship designer.

3. Choose self-grav hull. 

4. Finish the design. 

5. Click "Add to finished designs". 

6. Click the Finished Designs tab to check that it's there. 

7. End the turn. 

8. Open the designer again and click the Finished Designs tab. It's not there. 

[FreeOrion_0169_20191111_230318.zip](https://github.com/freeorion/freeorion/files/3843511/FreeOrion_0169_20191111_230318.zip)

It's not zipped, just rename it to mps

**Comment by o01eg** [comment]
I cannot reproduce it with simple multiplayer. Self-grav hull is present in finished designs and in production queue.

**Comment by o01eg** [comment]
Which revision of the server do you use?

**Comment by magnate** [comment]
I built it at the commit where you merged 4f372cb into the longturn-no-pullreq branch, so it's as close to that version as the longturn server can be. 

It's good that you can't reproduce it with that savefile, it means it's a server issue. I will update and rebuild and see if it goes away. If so I'll come back and close this.

**Comment by Oberlus** [comment]
> I will update and rebuild and see if it goes away. If so I'll come back and close this.

Poke

**Comment by magnate** [comment]
It was a weird permissions problem on the linux server. For some reason those hulls were owned by root!
