### ISSUE TITLE
No rule to make target '../util/Version.cpp'

### ISSUE THREAD

**Issue by apoleon** [freeorion/freeorion#265]
Hello,

the new pre-release fails to build from source. I have downloaded the source tarball v0.4.5-test-g4090.tar.gz but the build fails at 24% with

make[3]: **\* No rule to make target '../util/Version.cpp', needed by 'CMakeFiles/freeorioncommon.dir/util/Version.cpp.o'.  Stop.

I also see:

fatal: Not a git repository (or any of the parent directories): .git
WARNING: git not installed
WARNING: Can't determine git commit, util/Version.cpp not updated!
Building v0.4.5 build ???

So apparently the build system expects a git tree. Just adding git to FreeOrion's build-dependencies doesn't work either.

**Comment by Vezzra** [comment]
[New pre-release test builds](https://github.com/freeorion/freeorion/releases/tag/v0.4.5-test-gaf01) are up, this time I've also [provided a source tarball](https://github.com/freeorion/freeorion/releases/download/v0.4.5-test-gaf01/FreeOrion_2015-08-03.af01c2f_Source.tar.gz) that includes a version.cpp with the correct build number. The make_versioncpp.py script will still produce errors/warnings, but shouldn't touch the provided version.cpp, so your build process shouldn't fail anymore.

Can you test if that works for you?

**Comment by apoleon** [comment]
Hello

The new source tarball works now, thanks. To make it perfect please remove the MacOS specific files which start with ._. There seems to be hundreds of them included and they are all useless for source tarballs.

https://lintian.debian.org/tags/macos-resource-fork-file-in-package.html

Please also consider to use a version string such as 0.4.5-pre20150807 or something like that. The problem with the current scheme is that later git hashes are not always greater than the hashes before, eg. af01c is smaller than gaf01. For releasing and distributing FreeOrion it is important that subsequent release numbers are always greater. You could also avoid distributing two source tarballs because I guess everyone wants to have the one with the fixed version.cpp.

**Comment by Vezzra** [comment]
> The new source tarball works now, thanks.

Good to hear :smile: 

> To make it perfect please remove the MacOS specific files which start with ._.

Oh, ok, oops... will try to keep that in mind, shouldn't be too hard to filter them out...

> Please also consider to use a version string such as 0.4.5-pre20150807 or something like that.

Um, the build number is already composed following a scheme like that. For the latest pre-release test builds it's `2015-08-03.af01c2f`, and that's also the build number included into the file name of the installer packages and the source tarball. The git hash is only an additional qualifier to ensure a unique build number in case two builds have the same date in the date part, and to make it easier for us devs to quickly associate a build number with the corresponding git commit.

So what exactly does not work for you concerning the version string?

**Comment by apoleon** [comment]
Am 07.08.2015 um 17:52 schrieb Vezzra:
[...]

> ```
> Please also consider to use a version string such as
> 0.4.5-pre20150807 or something like that.
> ```
> 
> Um, the build number is already composed following a scheme like that.
> For the latest pre-release test builds it's |2015-08-03.af01c2f|, and
> that's also the build number included into the file name of the
> installer packages and the source tarball. The git hash is only an
> additional qualifier to ensure a unique build number in case two builds
> have the same date in the date part, and to make it easier for us devs
> to quickly associate a build number with the corresponding git commit.

Ok, but this one is missing the main version number 0.4.5. It would be
easier to recognize if the build number was

```
0.4.5-2015-08-03.af01c2f
```

I assume major releases just use the major version number without date
and git hash?

**Comment by Vezzra** [comment]
> Ok, but this one is missing the main version number 0.4.5. It would be easier to recognize if the build number was 0.4.5-2015-08-03.af01c2f

Well, you can stitch that together by parsing the version string, which _does_ include both the version number and the build number. Example for a version string of a FO build for OSX:

`v0.4.5 [build 2015-08-07.7fafac7] Xcode 0511`

> I assume major releases just use the major version number without date and git hash?

The version string of major versions isn't composed any different from that of test builds. The file names for the installer packages (and the custom made source tarballs we'll probably have from now on) however are slightly different for major versions, as they will also contain the version number. Test build packages file names only contain the build number.

**Comment by apoleon** [comment]
Am 07.08.2015 um 18:29 schrieb Vezzra:

> ```
> Ok, but this one is missing the main version number 0.4.5. It would
> be easier to recognize if the build number was 0.4.5-2015-08-03.af01c2f
> ```
> 
> Well, you can stitch that together by parsing the version string, which
> /does/ include both the version number and the build number. Example for
> a version string of a FO build for OSX:
> 
> |v0.4.5 [build 2015-08-07.7fafac7] Xcode 0511|
> 
> ```
> I assume major releases just use the major version number without
> date and git hash?
> ```
> 
> The version string of major versions isn't composed any different than
> that for test builds. The file names for the installer packages (and the
> custom made source tarballs we'll probably have from now on) however are
> slightly different for major versions, as they will also contain the
> version number. Test build packages file names only contain the build
> number.

Sorry for not being specific enough. I was talking about the file name
of the source package. The reason for this is that Debian tracks
upstream packages with an automatic system to remind people of new
releases. If the file name doesn't consist of your usual version
numbers, there is no way for those tools to determine whether you have
released a test release or a new major release. In the end I have to
figure it out manually but it would be a lot easier to parse and more
userfriendly, if your file name was composed of [major version] [build
date] [git hash]

**Comment by Vezzra** [comment]
> it would be a lot easier to parse and more userfriendly, if your file name was composed of [major version] [build date] [git hash]

Ah yes, that certainly can be done, and major releases, as I already said, definitely do include the version number. I can add that for pre-release test builds also.
