### ISSUE TITLE
Pedia entry for concentration camps is incorrect

### ISSUE THREAD

**Issue by swaqvalley** [freeorion/freeorion#2652]
The text for the Concentration Camps building Pedia entry reads: "Decreases the planet's Population at a rate of 3 per turn, increases Target Industry by 5 times the planet's Population and sets the Target Happiness to 0." But the rate of population decrease appears to be based on some formula (not 3 per turn) and the Target Industry is increased by 2 times (not 5 times) the population. In addition, it doesn't mention that the industry is set to the target industry immediately rather having to wait for normal meter growth.

**Comment by swaqvalley** [comment]
It may also be worth adding some explanation of what happens when you try to scrap a concentration camp building. It leaves behind remnants and the population keeps decreasing until (if) the remnants disappear (16.7% chance per turn).

**Comment by geoffthemedio** [comment]
https://github.com/freeorion/freeorion/commit/cb8e1a3b8dec2b0cab7ff2b290f2e60da3f01597#diff-9c40f66d46adcfa760df6228a22c7d48 simplified the population decrease calculation using effect priorities.

https://github.com/freeorion/freeorion/commit/c271f9b059e5e9d6a8f4a8b82abf729fd878e9a2 corrects the description about the amount of industry.

https://github.com/freeorion/freeorion/commit/329d48e3bfeebe9cee1c72990c5de3eebd895e54 mentions the remnants.
