### ISSUE TITLE
Chato slightly OP

### ISSUE THREAD

**Issue by Oberlus** [freeorion/freeorion#2680]
### Environment
* **FreeOrion Version**: v0.4.9 v0.4.9 2019-12-15

### Description
Chato has broad planet tolerance, great research (and average production), plus bad troops (both) and phototrophic.
Any species can have a bad start (little to none good/adequate planets), but this one tends to do pretty well most often. If it is lucky, it's OP; if it is unlucky, it can overcome the problem faster than other thanks to the great research: Exobots are almost on the opposite side of the environment wheel, so once it gets Xenological Genetics (access to poor) it can colonise pretty much everything.

### Suggestion
~~Remove the broad planet tolerance.~~
Add Bad Pilots to Chato.
An species with no production penalty and great research is hard to not be OP, but at least this way it's not that bad.

~~PS: I thought this is pretty much obvious (once I thought of it) and thought it would be good to post it directly as an issue. Should this kind of "issues" be posted first in the forums?~~

**Comment by Vezzra** [comment]
> PS: I thought this is pretty much obvious (once I thought of it) and thought it would be good to post it directly as an issue. Should this kind of "issues" be posted first in the forums?

It should at least be posted together with a corresponding discussion thread on the forum to prevent a design discussion starting in the issue comment section. While a certain issue might be obvious/seem obvious to the creator of the issue, others might think differently, and want to discuss the proposed changes.

In this particular case I'd at least want to hear the opinions of other players, if they perceived it the same way or not, if they think the proposed nerf of the Chato is the way to go or if they think other changes to the Chato would be better etc. But that discussion shouldn't happen here in the comment section.

So, please open a corresponding forum thread and put a link to it here.

**Comment by Oberlus** [comment]
Fair enough!

[Forum thread](https://www.freeorion.org/forum/viewtopic.php?f=6&t=11466).

**Comment by Oberlus** [comment]
As per forum thread's discussion, the best approach seems to be adding Bad Pilots to Chato.

**Comment by Vezzra** [comment]
If that's the general consensus (so to speak), I suggest updating the issue description in the OP accordingly (or close this issue as superseded and open a new one with an updated/adjusted description, although that would be overkill IMO).

**Comment by o01eg** [comment]
@Oberlus @Vezzra Will it be changed in 0.4.9 or only `master` branch?

**Comment by Vezzra** [comment]
I won't block the release for this, but if a proper change is provided in time for RC1, I see no reason not to cherry pick it into the release branch. Adding Bad Pilots to a species isn't a particularly risky adjustment...

**Comment by o01eg** [comment]
I've opened PR.
