### ISSUE TITLE
Incorrect suggestions when there are two invadeable planets in a system

### ISSUE THREAD

**Issue by ghost** [freeorion/freeorion#2684]
### Environment
* **FreeOrion Version**: 0.4.8 (Debian package 0.4.8-3)
* **Operating System**: Debian

### Description
* A system with two independent homeworlds and a third unclaimed planet. Both homeworlds have no defense or shields. They have 13.0 and 12.4 defensive troops.
* In the same turn 6 ships arrive, with 3, 3, 1, 1, 1 and 1 troop pods (i.e. standard-design troop ships and small troop ships), a total of 10. All ships are produced by Ugmors, so they have 150% effectiveness. Meaning, in total I have brought 30 troops, enough to successfully invade both planets. All numbers are shown as expected in the fleet window.
* The game proposes "Invade (+18.0 / 13.1)" and "Invade (18.0 / 12.5)". If I click such a button, I have only 12 troops left for the other planet, which is no longer enough.
* This happens no matter how I group the ships into fleets (they all arrived as one big fleet, but splitting/regrouping afterwards doesn't help).

### Expected Result
Game lets me invade with 15 troops for each of the planets.

### Steps to reproduce
No idea how to reproduce this situation. Perhaps you have some way?

**Comment by o01eg** [comment]
It looks like rounding error.

**Comment by Oberlus** [comment]
Workaround:

1. Make one fleet for the troop ships you want to use for invasion of first (next) planet.
2. Send remaining troop ships (not commanded to invade a previous planet) to another system.
3. Order invasion of the first (next) planet.
4. Cancel de moving order of the remaining troopships.
5. Go to 1 if there are more planets to invade.

The point is ships ordered to move aren't included in the invasion orders, the fleet arrangement does not make a difference.

**Comment by TheSilentOne1** [comment]
On the fleet window, you can manually select which ships to use for invasion.

**Comment by geoffthemedio** [comment]
> ... a total of 10 [troops]. All ships are produced by Ugmors, so they have 150% effectiveness. Meaning, in total I have brought 30 troops, ...

I don't follow... 10 * 150% = 15

Regardless, you don't have to do any fancy move orders and such. If you put the ships into one fleet, then select the ships (in the ships list of the selected fleet) you want to invade with, clicking invade will use just those ships. When no ships are selected, it auto-picks ships, but doesn't do a very careful job of it. This is just a convenience, and you're meant to tell it exactly what ships you want when the automatic picker doesn't do what you want.

**Comment by Oberlus** [comment]
I wasn't aware of this functionality: selecting troops ships affects the invasion mechanic.

I can't find information about this in the Pedia. I'll open an issue.

**Comment by geoffthemedio** [comment]
Not having to select them manually for the automatic selection is the newer option, so the old way perhaps didn't seem necessary to document.

**Comment by Vezzra** [comment]
So, can we close this as invalid? And maybe open an issue for adding a proper description of how assignment of troop ships works to the pedia?

**Comment by Oberlus** [comment]
New issue on this: https://github.com/freeorion/freeorion/issues/2686

**Comment by Vezzra** [comment]
Thanks!
