### ISSUE TITLE
Improve Pedia description of invasion mechanics

### ISSUE THREAD

**Issue by Oberlus** [freeorion/freeorion#2686]
### Environment
* **FreeOrion Version**: 0.4.8

### Description
When using the automatic troops selection (i.e. no manual selection of troop ships, just hitting the invasion button on the planet), the allocation of troopers might be suboptimal, leading to increased invasion costs or the innability to invade all planets on a system (until more troop ships are sent there) if available troop ships were just the exact needed amount.
Players of recent versions that always use the automatic invasion are not aware of the possibility of manual selection of troop ships for greater efficiency.
Current invasion Pedia page does not (and should) document the functionality of manual selection of troop ships to control what troops are used on each planet to invade.

Related issue (closed as invalid): https://github.com/freeorion/freeorion/issues/2684

**Comment by geoffthemedio** [comment]
What should be considered optimal? If the players has a bunch of low-troop ships that could be used up to lower their ship upkeep penalty, that might be better than using a single larger ship. Or maybe the players wants lots of ships to be kept around to be more resiliant to combat losses. And how to allocate arbitrary numbers to sum to another arbitrary number is a difficult problem even if the optimum is well defined.

**Comment by Vezzra** [comment]
Which is exactly why we discarded the idea of trying to "optimize" the automatic troop selection algorithm, and which is why we considered it important to describe manual troop ship selection in the pedia.

If veteran players like @Oberlus didn't realize that there is a manual troop ship selection option, then there is an obvious need for a proper improvement of the pedia, hence this issue...

**Comment by Oberlus** [comment]
> What should be considered optimal?

Yes, that depends on the players objectives at the moment. Hence the need to tell the player that he does not only have the automatic allocation of troops but also the manual one.

**Comment by geoffthemedio** [comment]
Note that ship selection probably also works the same for colonization and bombardment...

**Comment by Oberlus** [comment]
Candidate stringtable entries to include the explanation about manual selection of troop ships:

[PC_TROOPS_DESC](https://github.com/freeorion/freeorion/blob/67e849efe7e80f62b46cc1bc7d5e6762639cd042/default/stringtables/en.txt#L9360)
This is the entry showed in Pedia page "Ground Troops (Ground Troops Ship Part)". 

[METER_TROOPS_VALUES_DESC](https://github.com/freeorion/freeorion/blob/67e849efe7e80f62b46cc1bc7d5e6762639cd042/default/stringtables/en.txt#L5783)
This is also the entry showed in the Pedia page "Troops (Meter Type)".

A new Pedia page for "Invasion" could be advisable, probably within "\*Game Concepts\*", and be referenced from the above entries as well as from other Pedia pages that currently mention "invasion" without linking to any other page.
Or a sentence like the following (that probably needs improvement) could be included directly in the above entries:
"When invading a planet, the troop ships selected in the fleet window will be used for the invasion, unless there are no selected troop ships, in which case enough troop ships will be automatically selected".
It does not explicit anything about optimality but I guess it is enough.

**Comment by geoffthemedio** [comment]
Make a pull request?

**Comment by Oberlus** [comment]
> Make a pull request?

Done: #2804 

I only changed the PC_TROOPS_DESC entry, because it is also referenced from METER_TROOPS_VALUES_DESC.

I'm not very happy with the wording (too many "selected"), but I guess it is good enough.
