### ISSUE TITLE
/zoom does not know about identifiers but always searches by name

### ISSUE THREAD

**Issue by aschuch247** [freeorion/freeorion#2691]
### Environment

* **FreeOrion Version**: 456a9b64510faf81adfc637b9eb5c106f2d0139e, compiled from source
* **Fetched as**: Compiled from source

### Description

The command `/zoom` only searches by object names, but it does not search by object identifiers.

### Expected Result

I expect `/zoom 123` to zoom to object 123.

`ClientUI::ZoomToObject()` needs to understand that the given name is an identifier. The rest is pretty much already implemented.

### Steps to reproduce

* Enable showing of object identifiers.
* Try to use `/zoom` to zoom to any identifier (fleet, ship, system).

**Comment by geoffthemedio** [comment]
Should be resolved by 4195b0c69
