### ISSUE TITLE
Crash randomly while playing game every 2 to 10 minutes.

### ISSUE THREAD

**Issue by Kosakkoz** [freeorion/freeorion#2693]
Crash randomly while playing game every 2 to 10 minutes.

On a Windows 7 Version 6.1.7601 Service Pack 1 Build 7601
8GB ram
With two ATI HD4850 cards with crossfire disabled.
Driver Version	8.970.100.1100

The issue is present with FreeOrion_2019-12-24.fed9060_Test_Win32_Setup.exe
and also with FreeOrion_v0.4.8_2018-08-23.26f16b0_Win32_Setup.exe I tried after by uninstalling and reinstalling game.

Logs
[FreeOrion.zip](https://github.com/freeorion/freeorion/files/4023935/FreeOrion.zip)

**Comment by geoffthemedio** [comment]
Looks like a crash in the human client, but the log doesn't show anything useful and just abruptly ends after a bunch of fleet movement plotting calls. Doubt we can do much about it. Make sure you have fully updated graphics drivers, and maybe try disabling stuff in the options screen galaxy map tab in case it somehow helps...  If you run from the command line, there might also be an error message reported there after a crash that the log doesn't get.

Maybe also try to narrow down the cause... Is it just when a fleet is selected and you're mousing over systems, or when issuing a fleet move order by right clicking, or will it randomly crash even if the window doesn't have focus, or if it has focus but you're not actually doing anything with the mouse or keyboard?

**Comment by Kosakkoz** [comment]
Graphics drivers are the latest (2013)
When it crash I get this.
![image](https://user-images.githubusercontent.com/59540297/71786009-9d7cde80-2fd4-11ea-8181-14495f86c96c.png)

And need to end process.
![image](https://user-images.githubusercontent.com/59540297/71786014-abcafa80-2fd4-11ea-9e66-ed98090efc72.png)

Sometimes it crash when I click, and other times after I click.

I will try what you told me and let you know.
Thank you.

**Comment by Kosakkoz** [comment]
Disabling all checkbox in the options screen galaxy map tab haven't prevented a crash.
Running from command line haven't reported any message after crash.

**Comment by Kosakkoz** [comment]
Can the logs return memory leaks or graphics issues?

**Comment by geoffthemedio** [comment]
> Can the logs return memory leaks or graphics issues?

Not in general.

The crash error message about the display drivers is consistent with my suspicion that the problem could be related to rendering or the graphics drivers. That probably isn't due to a memory leak, which would probably take a lot more than a few minutes to use up enough RAM to cause a crash, and I doubt would lead to a graphics driver error.

Does it matter what other windows you have open in the GUI when crashes happen? Like close the sidepanel, fleets list, sitrep, messages, empires/players list, pedia, etc. vs. having each open alone and waiting or moving the mouse around the screen and scrolling / panning / zooming the map?

**Comment by Kosakkoz** [comment]
"Does it matter what other windows you have open in the GUI when crashes happen?"
I dont think this is related. It's mostly random.
I suspect the crossfire or graphic drivers.
Unfortunatly I dont have enough time nor skills to further narrow down the issue.
So since no one else reported that issue, I think we can close the ticket. It will be there in the case other people search for this issue and want to manifest themselves.
