### ISSUE TITLE
Supply line connection disappears

### ISSUE THREAD

**Issue by kaposvarigellert** [freeorion/freeorion#2719]
### Environment

* **FreeOrion Version**: FreeOrion_v0.4.9-RC1_2020-01-13
* **Operating System**:  Windows 10 Pro 64bit
* **Graphic card used**: AMD Radeon R7 M260
* **Fetched as** 
  * Binary release

### Description

My supply lines collapsed after clicking end turn. I can't produce ships, buildings etc.
Ship refueling does not work either.

I recently used a Black Hole Collapser and the generated map has active Experimentors.

[FreeOrion_Lord_Of_Terra_Terran_0297_20200118_055839.zip](https://github.com/freeorion/freeorion/files/4080783/FreeOrion_Lord_Of_Terra_Terran_0297_20200118_055839.zip)
![bug](https://user-images.githubusercontent.com/20242050/72665414-8db7be00-3a08-11ea-8080-04ad0b9526d1.JPG)

### Steps to reproduce

* First step.
* Second step.
* Another step.
* Issue occurs.

**Comment by Vezzra** [comment]
Confirmed on OSX.

Depending on if this is only a very rare edge case that only occurs under very special circumstances or can happen more frequently, this is potentially a very serious bug.

Shall we consider it as release-blocking?

@kaposvarigellert, do you have a save from one turn earlier? Before the supply lines disappear? That might be helpful for debugging...

**Comment by kaposvarigellert** [comment]
Sure
[FreeOrion_Lord_Of_Terra_Terran_0296_20200118_055738.zip](https://github.com/freeorion/freeorion/files/4083593/FreeOrion_Lord_Of_Terra_Terran_0296_20200118_055738.zip)

I'm not a game dev, but it might have something to do with the Black Hole Collapser.
I think this because my team and the green player is the only one affected.

I play this game since 0.3.2 and this is the first bug I've ever found in any release candidate.
(I only play the game a few times after every major update.)

**Comment by Vezzra** [comment]
I just tried the save of turn 296 on my Mac and my Windows machines. I can reproduce the issue on both. I have no idea what's going on here, though.

The supply meters all show the values you'd expect, but for some strange reason all the systems are not considered connected. The issue also does not go away after advancing a couple of turns.

Declaring the official release is scheduled for coming Sunday (26th). @geoffthemedio, shall I proceed with that? Or should we consider this issue serious enought to be release-blocking? See my comment above:

> Depending on if this is only a very rare edge case that only occurs under very special circumstances or can happen more frequently, this is potentially a very serious bug.
> 
> Shall we consider it as release-blocking?

**Comment by geoffthemedio** [comment]
After some investigation, the issue may be related to the Black Hole Collapser as commented. It appears that two empires have forgotten about all the starlanes they should know about, and thus aren't able to use those lanes to propagate supply. The affect empires are those that have systems being eaten by the collapser.

**Comment by geoffthemedio** [comment]
I think I found the issue... the code that was checking what systems were known to an empire was using the true/false flag for whether a lane is a wormhole where it meant to use the system ID. Starlanes are "false", ie. not a wormhole, which is interpreted as the number 0. In the test game, the system with ID 0 is destroyed by the Black Hole Collapser on the turn cycle between the two saves. Thus both empires that have systems near the collapser, and are thus aware of that system and its lanes, consider all their starlanes as being connected to the now-destroyed system 0, and thus consider them as not visible to themselves, and thus can't be used for supply propagation. Thus all systems can only share production output with themselves, and no systems are connected together in supply sharing groups.

**Comment by geoffthemedio** [comment]
Should probably have that fix in the release... The issue is rare, but rather game breaking.

**Comment by Vezzra** [comment]
> Should probably have that fix in the release... The issue is rare, but rather game breaking.

Agreed. Instead of declaring the stable release tomorrow (Sunday), I'll make RC2.

Fix has been cherry-picked: 925dbc28ea3e9a5ea3c7aeb83ab3ab220f2c4996
