### ISSUE TITLE
AI does not research deuterium tank

### ISSUE THREAD

**Issue by agrrr3** [freeorion/freeorion#2731]
While first time looking at the research AI does I found that deuterium tank does not seem to get researched.

With the fuel efficiency changes I consider fuel tech a must as soon as you have bad fuel efficiency hulls (probably earlier). It should go into the tech lists (not after tech group 3) or fast tracking it if the AI has appropiate hulls researched or fielded.

Not sure about other fuel tech but deuterium tank is so cheap and the change to the tech lists is very easy, so i think a solution should go into 0.4.9 release.

**Comment by Vezzra** [comment]
Hm, the AI not researching the Deuterium Tank tech will probably impair the AI performance quite a bit with the new fuel efficiency mechanic, so I guess you're right, a fix for this should go into 0.4.9.

**Comment by Vezzra** [comment]
Resolved by #2732.
