### ISSUE TITLE
Server crashes when getting incorrect fleet orders

### ISSUE THREAD

**Issue by o01eg** [freeorion/freeorion#2758]
### Environment

* **FreeOrion Version**: https://github.com/o01eg/freeorion/commit/9d02a98e70d79c9c0023f97739f02add3fe2c8fe based on 0.4.9 release +  #2756
* **Operating System**: Linux Ubuntu 18.04.4
* **Fetched as** 
  * Compiled from source

### Description

Seems to be related to #2348. I got following exception twice:

```
terminate called after throwing an instance of 'std::invalid_argument'
  what():  Fleet::SetRoute() : Illegally attempted to change a fleet's direction while it was in transit.
```

Saves before crash (rename to mps):
[FreeOrion_0031_20200213_184554.txt](https://github.com/freeorion/freeorion/files/4202701/FreeOrion_0031_20200213_184554.txt)
[FreeOrion_0049_20200213_202135.txt](https://github.com/freeorion/freeorion/files/4202702/FreeOrion_0049_20200213_202135.txt)

Logs:
[freeoriond.log.2020-02-13T18-51-16.zip](https://github.com/freeorion/freeorion/files/4202707/freeoriond.log.2020-02-13T18-51-16.zip)
[freeoriond.log.2020-02-13T20-26-55.zip](https://github.com/freeorion/freeorion/files/4202708/freeoriond.log.2020-02-13T20-26-55.zip)

I didn't get dumps yet.

### Expected Result
The server or client rejects incorrect order if it is incorrect, or applies it.

**Comment by geoffthemedio** [comment]
I loaded both saves as multiplayer games and ended turn without a crash. Maybe this patch helps, though?

[0001-Safety-try-catch-and-sanitization-when-setting-fleet.patch.txt](https://github.com/freeorion/freeorion/files/4208305/0001-Safety-try-catch-and-sanitization-when-setting-fleet.patch.txt)

**Comment by o01eg** [comment]
@geoffthemedio  Is this patch for `master` branch?

**Comment by geoffthemedio** [comment]
Should work on 0.4.9 or master, I think. Your save probably won't load in master, though

**Comment by o01eg** [comment]
I got error with `git apply` but `patch -p1` successfully applied it.

**Comment by geoffthemedio** [comment]
Does it prevent the crash for you in situations that crash without it, and does it cause any other problems when applied?

**Comment by o01eg** [comment]
@geoffthemedio  Can I check it in logs if there was such situations?

**Comment by geoffthemedio** [comment]
I don't know exactly when such situations happen or would have happened, and couldn't reproduce the issue for myself, so I'm not sure.

You can look for `Caught exception setting fleet route while executing fleet move order` or `FleetMoveOrder::ExecuteImpl given route that starts with fleet` in the server log, but those not being there doesn't prove anything.

What I really wanted to know was if you re-run a turn that crashes with 0.4.9, does it work with those changes, and does it cause any weirdness with fleet move orders not going through that previous would have worked.

**Comment by o01eg** [comment]
I don't even know who did that crashed order.

I didn't find the exception log line in the current logs so I will see if I found it in a actual game.

**Comment by geoffthemedio** [comment]
Based on the end of the log from turn 31:
````
2020-02-13 18:50:54.158128 {0x00007fe071b97740} [debug] server : ServerApp.cpp:3328 : No OrderSet for empire 1
2020-02-13 18:50:54.158155 {0x00007fe071b97740} [debug] server : ServerApp.cpp:3328 : No OrderSet for empire 2
2020-02-13 18:50:54.158174 {0x00007fe071b97740} [debug] server : Order.cpp:989 : ProductionQueueOrder place ProductionItem: BT_BUILDING name: BLD_COL_KOBUNTURA
2020-02-13 18:50:54.158447 {0x00007fe071b97740} [debug] server : Order.cpp:1009 : ProductionQueueOrder moving item in queue
2020-02-13 18:50:54.158622 {0x00007fe071b97740} [debug] server : Order.cpp:346 : FleetMoveOrder::ExecuteImpl Setting route of fleet 2247 to  910 1526 1862
2020-02-13 18:50:54.158688 {0x00007fe071b97740} [debug] server : Order.cpp:1009 : ProductionQueueOrder moving item in queue
2020-02-13 18:50:54.158720 {0x00007fe071b97740} [debug] server : Order.cpp:1009 : ProductionQueueOrder moving item in queue
2020-02-13 18:50:54.158747 {0x00007fe071b97740} [debug] server : Order.cpp:911 : ResearchQueueOrder::ExecuteImpl: adding tech to queue: PRO_MICROGRAV_MAN
2020-02-13 18:50:54.158801 {0x00007fe071b97740} [debug] server : Order.cpp:911 : ResearchQueueOrder::ExecuteImpl: adding tech to queue: PRO_MICROGRAV_MAN
2020-02-13 18:50:54.158990 {0x00007fe071b97740} [debug] server : Order.cpp:346 : FleetMoveOrder::ExecuteImpl Setting route of fleet 2457 to  1582 1505 1645
2020-02-13 18:50:54.159051 {0x00007fe071b97740} [debug] server : Fleet.cpp:370 : Fleet::MovePath for Fleet Colony Fleet 6075 (6075) No starlane connection between systems Kuma β(1288)  and Kuma β(1288). Abandoning the rest of the route. Route was: 1288 1603 1246 
2020-02-13 18:50:54.159097 {0x00007fe071b97740} [debug] server : Order.cpp:346 : FleetMoveOrder::ExecuteImpl Setting route of fleet 6075 to  1288 1603 1246
````
It was empire 3, who owns fleet 6075, which, based on the save header, appears to be you (o01eg).

**Comment by o01eg** [comment]
OK, I'll dig in.

**Comment by o01eg** [comment]
No, it was `Ophiuchus` fleet. Somehow he set route Kuma β (1288) - Beylix α 1603  - Beylix β (1246)
When I change route to Beylix β I got

```
17:16:42.726906 {0x00007f156e5fa500} [debug] server : Order.cpp:346 : FleetMoveOrder::ExecuteImpl Setting route of fleet 6075 to  1603 1246
```
and no crash.

**Comment by o01eg** [comment]
I've tried to use Shift to set fleet back to Kuma β (1288)  and then Beylix α 1603 - Beylix β (1246) but got only:

```
17:24:55.148537 {0x00007f8bfec7b500} [debug] server : Order.cpp:346 : FleetMoveOrder::ExecuteImpl Setting route of fleet 6075 to  1603 1288
17:24:55.148554 {0x00007f8bfec7b500} [debug] server : Order.cpp:346 : FleetMoveOrder::ExecuteImpl Setting route of fleet 6075 to  1603 1288
17:24:55.148566 {0x00007f8bfec7b500} [debug] server : Order.cpp:346 : FleetMoveOrder::ExecuteImpl Setting route of fleet 6075 to  1603 1288
17:24:55.148577 {0x00007f8bfec7b500} [debug] server : Order.cpp:346 : FleetMoveOrder::ExecuteImpl Setting route of fleet 6075 to  1603 1288
17:24:55.148588 {0x00007f8bfec7b500} [debug] server : Order.cpp:346 : FleetMoveOrder::ExecuteImpl Setting route of fleet 6075 to  1603 1246
17:24:55.148599 {0x00007f8bfec7b500} [debug] server : Order.cpp:346 : FleetMoveOrder::ExecuteImpl Setting route of fleet 6075 to  1603 1288
17:24:55.148610 {0x00007f8bfec7b500} [debug] server : Order.cpp:346 : FleetMoveOrder::ExecuteImpl Setting route of fleet 6075 to  1603 1246
17:24:55.148621 {0x00007f8bfec7b500} [debug] server : Order.cpp:346 : FleetMoveOrder::ExecuteImpl Setting route of fleet 6075 to  1603 1288
17:24:55.148631 {0x00007f8bfec7b500} [debug] server : Order.cpp:346 : FleetMoveOrder::ExecuteImpl Setting route of fleet 6075 to  1603 1246
17:24:55.148646 {0x00007f8bfec7b500} [debug] server : Order.cpp:346 : FleetMoveOrder::ExecuteImpl Setting route of fleet 6075 to  1603 1246 1603 1288
17:24:55.148659 {0x00007f8bfec7b500} [debug] server : Order.cpp:346 : FleetMoveOrder::ExecuteImpl Setting route of fleet 6075 to  1603 1246 1897
17:24:55.148670 {0x00007f8bfec7b500} [debug] server : Order.cpp:346 : FleetMoveOrder::ExecuteImpl Setting route of fleet 6075 to  1603 1288
17:24:55.148683 {0x00007f8bfec7b500} [debug] server : Order.cpp:346 : FleetMoveOrder::ExecuteImpl Setting route of fleet 6075 to  1603 1288 1603 1246
```

**Comment by geoffthemedio** [comment]
with 0.4.9 or with the patch?

Did anything break with the patch applied that worked before?

**Comment by o01eg** [comment]
It was with 0.4.9 without patch.

> Did anything break with the patch applied that worked before?

No, I didn't see errors.

**Comment by geoffthemedio** [comment]
OK, I pushed the safety checks: https://github.com/freeorion/freeorion/commit/6f443b43313245598e77b6bfa24dea553e293590

Hopefully resolves the hard-to-reproduce issue...

**Comment by o01eg** [comment]
Should it be backported to 0.4.9 as well?

**Comment by geoffthemedio** [comment]
Hopefully we won't have a bugfix release for v0.4.9 and instead proceed soon to _v0.4.10: The Python Update_
