### ISSUE TITLE
allianced empires do not share planet special discovery

### ISSUE THREAD

**Issue by aschuch247** [freeorion/freeorion#2765]
### Environment

* **FreeOrion Version**: d1e57c8c92a986d7d5e8dfc423a736fbbb3b6869, compiled from source

### Description

When in an alliance with another empire, newly discovered stars/planets are shared. However, specials of planets are not shared. The special is present, and the empires that discovered the planet actually sees the special, just not an allied empire.

### Expected Result

Knowledge of specials known to one empire of the alliance is shared with all members of the alliance.

### Steps to reproduce

* Start a new game, default settings, 1 additional empire (instead of 6).
* Ally with the other empire.
* At some point, the other empire explores system 843.
* The target population of planet 849 shows as 8.50, with -2.00 as unknown.
* Build super testers in your own capital.
* Once super testers are built, the special 'tidally locked rotation' shows up for planet 849.

**Comment by geoffthemedio** [comment]
Does that pull request fix it?

**Comment by aschuch247** [comment]
@geoffthemedio: Yes, planet specials now are seen by shared view. Thanks!
