### ISSUE TITLE
AIs Python error in Japanese

### ISSUE THREAD

**Issue by ganbaranaiyo** [freeorion/freeorion#2798]
### Environment

freeorion 0.4.9 build???
ubuntu19.10
Compiled from source

### Description
python error from AI

### Expected Result
* add ja.txt /stringtables and add ipaexg.ttf /date/fonts/
* change language to ja.txt and change all fonts to ipaexg.ttf
* change AI level to maniacal
* play freeorion 
* AI Python error happen.

### Steps to reproduce

* add ja.txt /stringtables and add ipaexg.ttf /date/fonts/
* change language to ja.txt and change all fonts to ipaexg.ttf
* road save date
* Advance the turn
* Issue occurs.

[ja.txt](https://github.com/freeorion/freeorion/files/4362770/ja.txt)
[https://ipafont.ipa.go.jp/old/ipafont/download.html](url)
[AI_6.log](https://github.com/freeorion/freeorion/files/4362792/AI_6.log)
[freeorion.log](https://github.com/freeorion/freeorion/files/4362796/freeorion.log)
[save-20200321_205423.sav.txt](https://github.com/freeorion/freeorion/files/4362805/save-20200321_205423.sav.txt)

**Comment by geoffthemedio** [comment]
Errors near the end of the log appear to be the same as was fixed by https://github.com/freeorion/freeorion/commit/3eb7770e89f50617027e31580bf92f5460da519a

So please update to the latest master and try again.
