### ISSUE TITLE
AI fleets skip past blockading fleet when that fleet includes domesticated monsters

### ISSUE THREAD

**Issue by Dragget** [freeorion/freeorion#2799]
<<version is 0.4.9 2020-03-02.89280c7>>
I have a fleet parked blockading and AI opponent's home system. It's been there for several turns while I wait for reinforcements to arrive before resuming my offensive:
Before image (attached)
Next turn, the AI decides to pull their fleets back to cover the home system:
After image (attached)
It appears they were able to bypass my defending fleet without combat. Should that be possible? (I verified that my fleet was in aggressive mode, FWIW.)
Advancing two turns, both fleets I marked with arrows in the screenshots skip past my blockade without combat.
Sorry for the poor quality of the images: I was unable to use screen capture, as it just gives me a black screen (game is in fullscreen mode) so I used my phone camera to capture images.

* **FreeOrion Version**: 0.4.9 2020-03-02.89280c7
* **Operating System**: Microsoft Windows 10 (x64)
* **Graphic card used**: Sapphire Pulse 5700XT
* **Fetched as** 
   * Weekly development build
 

### Steps to reproduce
<!--
* First step.
Have a fleet in place with a domesticated space monster in the fleet
![Before screenshot](https://user-images.githubusercontent.com/34214836/77258791-27cef900-6c3a-11ea-8b05-c2cb542fd98e.png)
![After screenshot](https://user-images.githubusercontent.com/34214836/77258798-2dc4da00-6c3a-11ea-8002-c4f143593d88.png)

* Issue occurs.
Enemy AI fleets can route through the system without engaging the fleet (see description above)

**Comment by geoffthemedio** [comment]
Relevant forum thread with screenshot: https://www.freeorion.org/forum/viewtopic.php?f=28&t=11578&p=100367

No save provided to replicate the issue, though...

**Comment by Dragget** [comment]
Here I am attaching the save file for what I believe is another instance of this bug. This time, I have a defending fleet, and the AI opponent enters the system with troopships and captures a planet, which should not be possible without first destroying the defending fleet.


[War 1.zip](https://github.com/freeorion/freeorion/files/4462210/War.1.zip)
Version is 0.4.9 2020-03-23.7b63adf

**Comment by Oberlus** [comment]
Maybe related to this issue:

In current multiplayer game, this happened:

Turn 12:
My 2 frigates arrive to system Alnasl beta, in a single fleet.
I see Magnate's scouts coming from behind Alnasl alpha (that is, there is: enemy scouts en route through a starlane -> Alnasl alpha -> Alnasl beta with frigates).
I split frigates fleet into two, and send one of the frigates to Alnasl alpha just in case they stop there, and leave one frigate in Alnasl beta. It should be stationary. It is indeed aggressive.

Turn 13:
One Magnate's scout stops at Alnasl alpha, and is destroyed by my frig.
The other two scouts just pass freely in spite of my aggressive and stationary frigate in there.

Maybe this has something to do with the fact that the frigate in Alnasl beta was from a split fleet on the turn before.

I can't provide save files until game is over (at least a month from now).

**Comment by geoffthemedio** [comment]
Was the remaining ship in a fleet that was already present in the system, or was it in a new fleet created by the split?

**Comment by Dragget** [comment]
In the original title, I specified "fleets containing domesticated space mosnters". The issue I experienced was resolved when I reloaded a previous turn and separated the monsters (Juggernauts, Snowflakes, Krakens) from my built ships. Unfortunately, the save file I uploaded was removed when I edited the post to correct a typo and add some information. I have been trying to recreate the scenario, and so far have managed only to determine that fleets containing Krakens, at least, are behaving correctly. My suspicion at this point is that Juggernauts are the only units with this issue, but I have not been able to manage a game where I have all three. Without some sort of save file editor, I have to play through and hope I can find what I need in-game to reproduce the issue. :(

**Comment by Oberlus** [comment]
> Was the remaining ship in a fleet that was already present in the system, or was it in a new fleet created by the split?

In a new fleet created by the split.
I dragged one frig out of the fleet and dropped it in empty space, creating a new fleet.
Although I'm not sure which one was send to Alnasl alpha and which one stayed.

[Ophiuchus said](https://www.freeorion.org/forum/viewtopic.php?f=2&t=11580&p=100521&sid=cb5de2a659dfd742fe411abb0c4a63db#p100521) that the stationary state might be reset for new fleets.

**Comment by geoffthemedio** [comment]
I think this issue is partly related to fleets that are in a system and have a move path set to move somewhere else, which are then ordered to move to their current system, setting the move path to nothing, still keep their internal "next system" as it was when they were moving. This marks them as not stationary, even though they don't / won't move.

**Comment by Oberlus** [comment]
> I think this issue is partly related to fleets that are in a system and have a move path set to move somewhere else, which are then ordered to move to their current system, setting the move path to nothing, still keep their internal "next system" as it was when they were moving. This marks them as not stationary, even though they don't / won't move.

That might be the case, yes.
In the multiplayer game, I think I might have ordered the fleet of two frigs to move, then cancel the order, split it into two and order one of the frigs to move.

**Comment by geoffthemedio** [comment]
Perhaps https://github.com/freeorion/freeorion/commit/2f4aa72437fa7e1968cde1f5d2e393c1c9fd42b2 helped?

**Comment by Oberlus** [comment]
> Perhaps [2f4aa72](https://github.com/freeorion/freeorion/commit/2f4aa72437fa7e1968cde1f5d2e393c1c9fd42b2) helped?

I've replicated in a local multiplayer game the scenario I commented above (an incoming enemy arriving to a system, a defending fleet in that system, I command that fleet to move, split an armed ship from that fleet so that it will hold in the system) and the incoming enemies got blocked.
I think you solved it.

**Comment by Dragget** [comment]
Possibly reopen this: I've encountered this again in version 0.4.10+ build 2020-11-16.7964d08. The fleet in question is in the Acubens system. Forum thread is here: https://www.freeorion.org/forum/viewtopic.php?f=28&t=11857
since I was unable to attach the SAVs (zipped) here.
