### ISSUE TITLE
stringtable, music resources not loaded with relative paths

### ISSUE THREAD

**Issue by raptor** [freeorion/freeorion#2800]
### Environment

* **FreeOrion Version**: 0.4.9
* **Operating System**: Multiple (AppImage on Ubuntu, openSUSE)
* **Graphic card used**: N/A
* **Fetched as** 
  * Compiled from source

### Description

With attempting to package FreeOrion as an AppImage, I noticed the following errors in the log file that occur from the 2nd run onwards (because the configuration directories are set up):

> 20:13:11.498743 {0x00007fa93959c780} [error] client : Sound.cpp:462 : PlayMusic: unable to open file /tmp/.mount_freeorQk8yrg/usr/share/freeorion/default/data/sound/artificial_intelligence_v3.ogg I/O Error. Aborting
> 20:13:11.607285 {0x00007fa93959c780} [error] client : StringTable.cpp:62 : StringTable::Load failed to read file at path: /tmp/.mount_freeorQk8yrg/usr/share/freeorion/default/stringtables/en.txt

Note the prefixed path of  `/tmp/.mount_freeorQk8yrg`. A random path like this is set up everytime the AppImage is run and so the resource location changes each time. Other resources do not have this problem

Also, using the command line options like `--resource.path` does not change the path it attempts to load the stringtable/music file from; it still tries to load from the first-run /tmp path

### Expected Result

These resources should be loaded from relative paths like the rest of the game resources. The first run of the game works fine, but not subsequent ones.

### Steps to reproduce

* You can test the AppImage from here, it runs OK on openSUSE 42.3+ and Ubuntu 18.04+, and should run on others with glibc 2.14 and GLIBCXX_3.4.21 or later:
 https://download.opensuse.org/repositories/home:/dbuck/AppImage/
* Quit after first run, and re-run, you notice menu music doesn't work and there are errors about the missing stringtable

**Comment by adrianbroher** [comment]
> Note the prefixed path of /tmp/.mount_freeorQk8yrg. A random path like this is set up everytime the AppImage is run and so the resource location changes each time. Other resources do not have this problem

Wasn't the point of AppImage to isolate the process from the host system?

Probably the ConfigDB writes the path to the file, even if it the default path.

The whole storing configuration pathes in the config file is stupid, but that's the default mode of operation here.

**Comment by geoffthemedio** [comment]
Default-valued options are handled different for the `persistent_config.xml` and the (non-persistent) `config.xml` files. For persistent, it only writes the non-default values. For the non-persistent file, it includes all option values with the intention that this will make it easier to edit the file by hand.

(The persistent file is intended to be persistent over version changes of the game...)

I'm not sure how to deal with this randomized-named app-bundle situation, though...

For default-valued options, it could output a flag-like XML representation, which preserves the nested options in categories structure, but it's still not as easy to manually edit as something written out fully, given the lack of properly formatted opening and closing XML tags, and the lack of indication whether something is a flag or an empty non-flag option in the text file.

**Comment by raptor** [comment]
Portability is AppImage's main focus, not necessarily isolation. User preferences are usually stored on the host system like normal.

It is interesting that the default values do change from run-to-run when listing the command line options:

> freeorion-0-Build0.glibc2.14-x86_64.AppImage --help resource
> [2020-03-23 08:19:32.088895] [0x00007f8cb9f8bd40] [info]    StringTable::Load failed to read file at path: /tmp/.mount_freeorKccH7K/usr/share/freeorion/default/stringtables/en.txt
> Game data resources Options:
> ...
> --resource.stringtable.path
>      Sets the language-specific string table filename. 
>      Default: 
>        /tmp/.mount_freeorVssJzw/usr/share/freeorion/default/stringtables/en.txt

and on next run:

> freeorion-0-Build0.glibc2.14-x86_64.AppImage --help resource
> [2020-03-23 08:24:08.412986] [0x00007f28f70fbd40] [info]    StringTable::Load failed to read file at path: /tmp/.mount_freeorKccH7K/usr/share/freeorion/default/stringtables/en.txt
> Game data resources Options:
> ...
> --resource.stringtable.path
>      Sets the language-specific string table filename. 
>      Default: 
>        /tmp/.mount_freeorSrdeDR/usr/share/freeorion/default/stringtables/en.txt

**Comment by geoffthemedio** [comment]
> It is interesting that the default values do change from run-to-run

The default resources directory would be expected to change depending on the path of the binary being run. There's something fancy going on with binreloc to do this here: https://github.com/freeorion/freeorion/blob/master/util/Directories.cpp#L291

**Comment by adrianbroher** [comment]
What should the binreloc even achieve there?  FreeOrion is not designed to be relocatable.  Having relative pathes to the binary within a prefix would be much easier to handle.

**Comment by geoffthemedio** [comment]
I don't know the details of how different operating systems and distributions handle this issue, or why things were set up that way for the code enabled for Linux builds. My vague recollection is that, in some cases, looking for the resources relative to the binary location wasn't always appropriate. Perhaps some distros put binaries completely different locations from the data files, or people wanted to have multiple binary locations without duplicating all the resource files for each...

**Comment by adrianbroher** [comment]
That's alot of overhead for so many perhaps, some, in some cases and vague recollections…

**Comment by geoffthemedio** [comment]
That I have no idea how something works (clearly) doesn't mean there wasn't a reason for it being implemented as it was.

**Comment by adrianbroher** [comment]
@geoffthemedio do you want to work on this or should I take a stab at it?

**Comment by geoffthemedio** [comment]
I'm looking at by-default outputting only non-default options in config.xml...

Edit: https://github.com/freeorion/freeorion/commit/8a687cbde09c21970aab24c5cbc69026aba5125d seems to work, and would hopefully fix this, since the default resources path for each execution should be left default and thus not output by default to the options file.

**Comment by raptor** [comment]
Verified it works with latest git aa122c8.  AppImage runs fine over multiple runs and sound and stringtable errors are gone.

Thanks!
