### ISSUE TITLE
Unable to create Starlane to close system (Starlane Bore)

### ISSUE THREAD

**Issue by ghost** [freeorion/freeorion#2808]
When I try to create a starlane for the nearest system using Starlane Bore, a connection to the system that is further away is created. The connection can bypass the star system located directly above or next to the one from which the connection is initiated - and it is to those systems that I am trying to create a link to. Incorrect connections can be above 300uu, although other systems are much closer (50uu - 200uu).

FreeOrion version 0.4.9, build 2020-02-02.db53471
run on Windows 10 Home
6 core AMD + 16GB RAM
Radeon RX 580 8GB

**Comment by geoffthemedio** [comment]
Same as https://www.freeorion.org/forum/viewtopic.php?f=28&t=11522 ?

**Comment by geoffthemedio** [comment]
Screenshots and saves to reproduce would be helpful...

**Comment by ghost** [comment]
I'm very sorry - it's simmilar to https://www.freeorion.org/forum/viewtopic.php?f=28&t=11522.
Thread can be closed.
THX and Regards

**Comment by geoffthemedio** [comment]
Having a forum thread doesn't mean there shouldn't be a github issue...
