### ISSUE TITLE
Armed ships not enforcing supply

### ISSUE THREAD

**Issue by Oberlus** [freeorion/freeorion#2813]
### Environment
* **FreeOrion Version**: v0.4.9+ 2020-03-27 8bd22d2
* **Operating System**: Ubuntu 18.04
* **Fetched as** 
  * Compiled from source

Note that this version was compiled from a local branch: master at the time plus the ScapeTrigraph fix, PR#2806

### Description
The armed, aggressive fleet at the centre of the screenshot is not enforcing supply propagation.
![supply_not_enforced](https://user-images.githubusercontent.com/28650914/77862409-83414e00-721b-11ea-9748-4c8b46d1997b.png)
The issue happened first time on turn 124. I attach files for turns 122 and 124.

### Expected Result
Armed, aggressive fleet enforces supply propagation.

### Steps to reproduce
Load save game for turn 124 and check out empty space south of Tork beta system.
[FreeOrion_Human_Player_Terran_122&124.zip](https://github.com/freeorion/freeorion/files/4399929/FreeOrion_Human_Player_Terran_122.124.zip)

**Comment by Oberlus** [comment]
I cannot reproduce with 2020-03-29 05a9f71

Should I close this?

**Comment by geoffthemedio** [comment]
I don't think anything relevant changed in the last few days... so leave it open and perhaps try to figure out the difference between when it happens and when it doesn't...

**Comment by geoffthemedio** [comment]
For some reason, on turn 124, Fleet 11152 has its next system set to Helos (736) even though its travel route is empty. It thus gets treated as moving, so unable to block supply, even though it doesn't actually move. I added some extra resets of the next and prev system to `INVALID_OBJECT_ID` in https://github.com/freeorion/freeorion/commit/cbc6a176416a6721f0040892be6d2d01c7ac4cb1 which appears to resolve the issue and should hopefully prevent it, though I don't know how it appeared... Perhaps a blockade of the system when the ships initially arrived or somesuch...?

**Comment by Oberlus** [comment]
> Perhaps a blockade of the system when the ships initially arrived or somesuch...?

The blue fleets were there since before turn 117. At that turn the red AI attacked (there's a sitrep at turn 116 for incoming enemies to that deep space, which were wiped out and nothing else happened until turn 124 when supply fades off due to AI getting better supply or something). I no longer have the previous save files, but that is also what I recall.
