### ISSUE TITLE
AI does not protect troop ships of failed invasion missions

### ISSUE THREAD

**Issue by Oberlus** [freeorion/freeorion#2814]
* **FreeOrion Version**: 0.4.9+ (also older versions)

### Description
When AI invasion missions (comprising armed and troop ships) fails for whatever reason, AI no longer does anything with those troop ships for the rest of the game. 
It happens in **every** game.
The most common situation for me is when the armed ships of an AI invasion mission attack their target system and lose: the troop ships will remain in the adjacent system until something kills them. 
![AI_never_saves_troopers](https://user-images.githubusercontent.com/28650914/78001483-08b92100-7336-11ea-9f9a-51733301ca02.png)
Those troopers in the screenshot are from a failed invasion mission from tens of turns ago. They remained there since the armed ships were killed. Now they won't flee from the incoming enemy fleet despite having vision and time to retreat (although not retreating to save their asses is not the real issue).

[Forum thread](https://www.freeorion.org/forum/viewtopic.php?f=28&t=11103&p=93871#p93871).

@Morlic-fo prepared a [branch for evasion manoeuvrers](https://github.com/freeorion/freeorion/compare/master...Morlic-fo:BasicEvasiveManeuvers) intended to help with this issue, although it doesn't seem to fix the mission-less situation: keeping the troops alive but not using them to anything else might be worse than just letting them die, since they count for fleet upkeep but serve no useful purpose any more.

### Expected Result
AI reassigns any idle/mission-less troop ships to other missions.

### Steps to reproduce
This is an old issue that might not be urgent, and it happens on every game against AIs, so I'm not attaching save files (that would become incompatible with time).
If someone takes over this, I could provide recent save files on demand.

**Comment by Oberlus** [comment]
@Morlic-fo Would it make sense, as a workaround, to force the AI to keep together the troop ships and the armed ships for a given invasion mission? So that they succeed or fail together.

**Comment by Morlic-fo** [comment]
>  If someone takes over this, I could provide recent save files on demand.

Please do. I am currently working on an invasion rework.

**Comment by Oberlus** [comment]
> Please do. I am currently working on an invasion rework.

Any particular version? Should I use v.4.0.9 or most recent master maybe?

I'll make a small game with a single AI for easier debugging, save every turn, and write down turns in which interesting stuff happens (attacks, absence of retreats, idle troopers, etc.).
Unless you prefer to have more AIs in the game.

**Comment by Morlic-fo** [comment]
Most recent master would be most helpful, a single AI is fine. A final log file would also be great to see where stuff starts going wrong.

**Comment by Oberlus** [comment]
A not-so-small game (30 systems, 1 AI), I'm not sure it will be good for testing.
The AI attacks at turn 130 or so (I wasn't paying attention, sorry, but logs are complete), leaving the troopers behind.
Then I counter-attack thinking I would need 2 turns to arrive but I had something that boosted speed and it only took one turn. I hope logs are enough to know if AI would have reacted properly.

The attached files are .7z, I added .txt to fool github. Tell me if you prefer .zip (but those occupy 2.5x).
[invasion_failed_saves_100-134.7z.txt](https://github.com/freeorion/freeorion/files/4423026/invasion_failed_saves_100-134.7z.txt)
[invasion_failed_saves_60-98.7z.txt](https://github.com/freeorion/freeorion/files/4423028/invasion_failed_saves_60-98.7z.txt)
[invasion_failed_logs.7z.txt](https://github.com/freeorion/freeorion/files/4423029/invasion_failed_logs.7z.txt)

I'll play a smaller game another day, having to wait for 130 turns in a row for the action to start is too much for me to pay proper attention.

**Comment by Morlic-fo** [comment]
What exactly is the issue you experience?

The AI does not forget its invasion fleet. If I load turn 128 and move the military fleet from Troy system into Calafia, destroying the attacking fleets and pass subsequent turns, eventually, once the it has rebuilt sufficient military strength, the AI attacks Calafia again. It then uses the existing invasion ships to capture planets there.

I do agree that the AI should retreat its ships and not park it next to the enemy system but that goes for all ship types...

**Comment by Grummel7** [comment]
I suggest to close this one.
#3754 has fixed a most of it, what remains it covered by #818
