### ISSUE TITLE
Checksum mismatch if the server and the client have diferent language set

### ISSUE THREAD

**Issue by o01eg** [freeorion/freeorion#2817]
### Environment
* **FreeOrion Version**: 025f545
* **Operating System**: Ubuntu 18.04 server + Gentoo AMD64 client
* **Graphic card used**: NVIDIA
* **Fetched as** 
  * Compiled from source

### Description
If both server and client set to same language there no error about mismatched checksum. But if I set client to different language this error appears.

### Expected Result
Checksum is independent from language.

### Steps to reproduce
* Start the server.
* Connect client to it.
* Disconnect.
* Change language in the client.
* Connect client to the server.

**Comment by adrianbroher** [comment]
Smells like bad design, why should the game state contain localized data anyway?  This is part of the representation and responsibility of the client.

**Comment by adrianbroher** [comment]
Which entities have the checksum mismatch?

**Comment by o01eg** [comment]
@adrianbroher 
```
Checksum for PredefinedShipDesignManager on server 879155 != client 948478
```

**Comment by geoffthemedio** [comment]
`PredefinedShipDesignManager::GetCheckSum` probably has localization exposure from this line:

https://github.com/freeorion/freeorion/blob/master/universe/ShipDesign.cpp#L1533

Where the call to `->Name()` doesn't have a `false` parameter, which means the returned name is looked up in the stringtable. Making it `it->second->Name(false)` should instead calculate the checksum from the name stringtable key, which should be stringtable-independent. There might be other exposure, but that's a place to start...

**Comment by o01eg** [comment]
@geoffthemedio Thanks, it was enough to don't catch error.

**Comment by geoffthemedio** [comment]
Presumably fixed by https://github.com/freeorion/freeorion/commit/9ed61d7c9b42d49b8dff4af5776625bd7ccc4632
