### ISSUE TITLE
The server crashed on shutdown

### ISSUE THREAD

**Issue by o01eg** [freeorion/freeorion#2824]
### Environment

* **FreeOrion Version**: https://github.com/o01eg/freeorion/commit/2de79d16190511016280287bb92ee63623a5d072 based on https://github.com/freeorion/freeorion/commit/025f5451ae2df8ea3335de528edcb8cda7e11000
* **Operating System**: Linux Ubuntu Server amd64 18.04.4
* **Fetched as** 
  * Compiled from source

### Description
Happened each time I stopped the server.

Stacktrace from the server:

```
(gdb) bt
#0  0x00007f079d2225cc in PyType_IsSubtype () from /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0
#1  0x00007f079d18a4d8 in PyImport_Cleanup () from /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0
#2  0x00007f079d18a9c8 in Py_FinalizeEx () from /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0
#3  0x000055966e1793f7 in PythonBase::Finalize (this=this@entry=0x7ffc367257b8) at ./python/CommonFramework.cpp:174
#4  0x000055966e179e83 in PythonBase::~PythonBase (this=0x7ffc367257b8, __in_chrg=<optimized out>) at ./python/CommonFramework.cpp:42
#5  0x000055966e293992 in ServerApp::~ServerApp (this=0x7ffc36724bb0, __in_chrg=<optimized out>) at ./server/ServerApp.cpp:129
#6  0x000055966e14a780 in main (argc=<optimized out>, argv=<optimized out>) at ./server/dmain.cpp:94
```

### Expected Result
The server shutdowns without crash

### Steps to reproduce
* Start hostless server.
* Stop hostless server.

**Comment by adrianbroher** [comment]
Cannot reproduce but I also don't know how to start a hostless server. Can you list the exact commands/operations for reproducing this?

**Comment by Oberlus** [comment]
Maybe not the same issue, but whenever I set up a multiplayer game, connecting two clients to it, as soon as one of the clients exits (resign), the other client says "Connection to the server lost".

**Comment by o01eg** [comment]
@adrianbroher The server stopped to produce coredump 7th of April. Maybe when I rebuild it with new weekly test build.
