### ISSUE TITLE
Selection of colony/outposts does not allow to choose what ship to use

### ISSUE THREAD

**Issue by Oberlus** [freeorion/freeorion#2827]
### Environment
* **FreeOrion Version**: v0.4.9+ 2020-04-03.7783255
* **Operating System**: Ubuntu 18.04
* **Fetched as**
  * Compiled from source

### Description
Selecting an outpost/colony ship/base does not allow to use that ship for colonization/outposting.
![CantSelectShipToColonizeOrOutpost](https://user-images.githubusercontent.com/28650914/78451889-6926c600-7688-11ea-8379-de2492c76514.png)

### Expected Result
Selecting an outpost/colony ship/base allows to use that ship for colonization/outposting.

### Steps to reproduce
* Load attached save file.
* Select the outpost base in system Crow beta.
* Click on "Colonize" button next to Crow beta III. It should be an "Outpost" button.
[FreeOrion_Oberlus_Abyss_0078_20200404_151323.zip](https://github.com/freeorion/freeorion/files/4431412/FreeOrion_Oberlus_Abyss_0078_20200404_151323.zip)

**Comment by geoffthemedio** [comment]
You selected the fleet, not the ship.

**Comment by Oberlus** [comment]
Ouch!

Selecting the ship does work. Closing as invalid.
