### ISSUE TITLE
Antimatter tank researched but not available in ship design

### ISSUE THREAD

**Issue by bta-notavailable** [freeorion/freeorion#2829]
Freeorion v0.4.9 [build 2020-02-022.db53471] CMake on ASUS UX430U with Ubuntu 18.04.4 LTS. Single player Fulver species with several natives.

**Comment by bta-notavailable** [comment]
Oh, Titanic Hull with extra fuel tank has 2.7 fuel capacity. Antimatter tank not available for robotic hull either.

**Comment by Oberlus** [comment]
Antimatter tank is not a ship part to mount on your ships, it's just an upgrade to the Extra Fuel Part.

Close this as invalid.
