### ISSUE TITLE
Learning skill branches I did not select.

### ISSUE THREAD

**Issue by bta-notavailable** [freeorion/freeorion#2830]
Freeorion v0.4.9 [build 2020-02-022.db53471] CMake on ASUS UX430U with Ubuntu 18.04.4 LTS. Single player Gysache species with several natives. Recently conquered Trith Citadel (home planet). Wasted research status just started (researched almost everything I want). Turn 270.

I do NOT want fighter bays, mass driver 2, lazer 2, bioterror facilities and bombardment options. Death Rays and troops are much more effective. The rest are a waste of resources to me. But here they are, getting learned in every turn.

**Comment by Oberlus** [comment]
The research points you don't spend on anything are automatically spent on the cheapest available techs.
If you want to put those points on something more expensive you have to add it to the research queue. If there isn't anything else you want to spent points into but you don't want to put them into the remaining cheap techs, you should change focus of some research planets into production or whatever to reduce research points output.

~~Close this as invalid.~~

Or leave it open as a reminder that automatic RP allocation can confuse players, so maybe it should be better documented or the research queue should show (greyed?) the techs that would get automatic RP allocation.

**Comment by Vezzra** [comment]
> Or leave it open as a reminder that automatic RP allocation can confuse players, so maybe it should be better documented or the research queue should show (greyed?) the techs that would get automatic RP allocation.

For that a separate issue should be opened. Closing this as invalid.
