### ISSUE TITLE
[release-0.4.5] missing texts

### ISSUE THREAD

**Issue by aschuch247** [freeorion/freeorion#284]
I am using FreeOrion 2015-08-07.febea19 right now and I noticed some missing texts when running "./freeorion --help" (in reverse order):

--hidden-sitrep-templates
     ERROR: OPTIONS_DB_HIDDEN_SITREP_TEMPLATES_DESC | Default: 

--UI.save-file-dialog.tooltip-delay
     ERROR: OPTIONS_DB_UI_SAVE_DIALOG_TOOLTIP_DELAY | Default: 800

--UI.objects-list-info-col-n (0…9)
     ERROR: OPTIONS_DB_OBJECTS_LIST_COLUMN_INFO | Default: NAME

--UI.objects-list-width-col-n (0…9)
     ERROR: OPTIONS_DB_OBJECTS_LIST_COLUMN_WIDTH | Default: 96

--UI.hotkeys.map.objects
     ERROR: HOTKEY_MAP_OBJECTS | Default: MOD_KEY_LCTRL | MOD_KEY_RCTRL+GGK_o

--UI.fleet-wnd-aggression
     ERROR: OPTIONS_DB_FLEET_WND_AGGRESSION | Default: INVALID_FLEET_AGGRESSION

**Comment by Vezzra** [comment]
Fixed by 1f07e2487cfb497749d5643e348ed8914809c582
