### ISSUE TITLE
Document that Psychogenic Domination cannot take over domesticated space monsters

### ISSUE THREAD

**Issue by petervdmeer** [freeorion/freeorion#2840]
# Environment
* **FreeOrion Version**: v0.4.9 [build 2020-02-02.db53471] CMake
* **Operating System**: Debian Linux
* **Graphic card used**: Not relevant
* **Fetched as**
  * Binary release (packaged for my distribution)

### Description
Psychogenic Domination can only be used to capture regular ships from other players, it cannot be used to capture domesticated space monsters from other players.
This is technically already documented by the text `taking control of enemy ships`, but I would like some text to be added that explicitly states that the focus doesn't work for enemy-player owned space-monsters.

### Expected Result
I would like the documentation to explicitly state that Psychogenic Domination doesn't work for enemy player owned space monsters.

**Comment by urshmost** [comment]
minor editing tweaks to the text for the Pedia entry for Psychogenic Domination, added new sentence at the end relevant to space monsters:



Has a 10% chance of taking control of enemy ships with non-telepathic crews in the same system as a planet with Domination Focus unless the enemy empire also knows the Psychogenic Domination. Domination Focus can only be set on planets colonized by telepathic species.
Reduces the chance that Psionic Snowflakes take over your ships.

It is difficult to force a conscious individual to submit to the total mental control of another entity against its will. By manipulating the timeframes involved however, the mental force exerted by a population over a period of hours may be brought to bear on a single individual in the span of a few seconds, creating an almost irresistible compulsion to join the unified mind.  This ability does not appear to work on Mega Fauna, apparently space monster brains are just too different.
