### ISSUE TITLE
Server fails to start on new game.

### ISSUE THREAD

**Issue by adrianbroher** [freeorion/freeorion#2849]
### Environment

* **FreeOrion Version**: master (2c9b4ba9cc1f44539826a41bc3eda1c563bc03be)
* **Fetched as**: Compiled from source

### Description
When starting a new single player game or continuing an existing game FO reports that the connection to the local game server was lost.

Within freeoriond.log the following errors are displayed:

```
15:25:55.183898 {0x00007fa5d401ff40} [info] log : Logger.cpp:198 : Added logger named "FSM"
15:25:55.184015 {0x00007fa5d401ff40} [info] log : Logger.cpp:330 : Setting "FSM" logger threshold to "debug".
15:25:55.184072 {0x00007fa5d401ff40} [debug] server : ServerApp.cpp:324 : FreeOrion server waiting for network events
15:25:55.227317 {0x00007fa5d1013700} [error] server : Parse.cpp:171 : Exception caught regex parsing script file: basic_string::_M_create
15:25:55.227573 {0x00007fa5d1013700} [error] server : Parse.cpp:171 : Exception caught regex parsing script file: basic_string::_M_create
15:25:55.227694 {0x00007fa5d1013700} [error] server : Parse.cpp:171 : Exception caught regex parsing script file: basic_string::_M_create
15:25:55.227802 {0x00007fa5d1013700} [error] server : Parse.cpp:171 : Exception caught regex parsing script file: basic_string::_M_create
15:25:55.227893 {0x00007fa5d1013700} [error] server : Parse.cpp:171 : Exception caught regex parsing script file: basic_string::_M_create
15:25:55.228061 {0x00007fa5d1013700} [error] server : Parse.cpp:171 : Exception caught regex parsing script file: basic_string::_M_create
```

My guess is that this bug was introduced by fc7c41b27872c9e4d51a6c20f94f568692f86993  as this issue did not occur with 287cf2636b0dab9c4c914d2fb34dea732696899b and this is the only commit that directly or indirectly touches parser code.

**Comment by geoffthemedio** [comment]
As far as I can tell, fc7c41b is just whitespace / linebreak changes. I can't replicate the issue.

**Comment by adrianbroher** [comment]
Seems like this was a hiccup due to a partial compile, when bisecting and rebuilding this bug didn't show up again.

Closing as invalid.
