### ISSUE TITLE
show empire scanning strength in empire report

### ISSUE THREAD

**Issue by aschuch247** [freeorion/freeorion#285]
When designing a stealth scout, it is important to know the enemy empire scanning strength. Right now, I need to check this value manually for each enemy empire by right clicking the empire in the empire report window and then clicking again to open the encyclopedia.

I really like to see this value in the empire report itself to get a quick overview.

**Comment by TheSilentOne1** [comment]
PR: https://github.com/freeorion/freeorion/pull/508

**Comment by TheSilentOne1** [comment]
Added with https://github.com/freeorion/freeorion/commit/6d8e31f94a635a834e3ecfd3d05e43262efdf0a0.
