### ISSUE TITLE
New colonies should be happier than invaded planets

### ISSUE THREAD

**Issue by swaqvalley** [freeorion/freeorion#2862]
PR #2745 causes new colonies to have no industry or research when created because they have less than 5 happiness. This new mechanic handicaps new colonies just as much (or more) than invaded planets.

Oberlus suggests starting a colony with more happiness when the habitability is better for the species. Forum discussion thread:
https://www.freeorion.org/forum/viewtopic.php?f=28&t=11604

**Comment by Vezzra** [comment]
Sounds like a quite serious issue for gameplay. Should be addressed before a new release.

**Comment by Oberlus** [comment]
This can be closed.
Edit: it's been tested and works fine.
