### ISSUE TITLE
Structure scaling rework and four bouts

### ISSUE THREAD

**Issue by agrrr3** [freeorion/freeorion#2901]
I open this for tracking a structure rescaling work. This will broaden the design space for multishot and heighten influence of ship design on combat. When introducing the disruptor arc it was almost impossible to find a design spot which is not either underpowered or overpowered or has other strong drawbacks (even the arc disruptor is restricted for balance reasons - it does not scale with pilot skill).

Forum discussion with benefits/tradeoffs etc: [Four combat bouts as default](https://www.freeorion.org/forum/viewtopic.php?f=6&t=11665)

Game Aim:
* Higher structure values so integer based damages can scale more finely - currently a multishot weapon with four shots has a minimum damage upgrade like the best ship weapon (4 damage for one step)
* Increase default bouts to four from three while keeping current balance (so battles take about the same amount of turns)

Basic implementation idea:
- multiply structure by 6 because we often have 2 and 3 divisions [Re: Base weapon stats for (mostly) integer values](https://www.freeorion.org/forum/viewtopic.php?f=6&t=11563&p=99935&hilit=bouts#p99906) and multiply the weapon damage accordingly
- multiply structure by 4/3 to spread the structure to account for the ship weapon damage done by one extra bout
- the resulting structure multiplier is 8 (== 6 * 4 / 3 )

Implementation Plan (always checking stringtables and AI in each step):
- [x] set default number of bouts to 4
- [x] armor and hull structure scaling by 8 (easy via hip_hulls.macros:STRUCTURE_FACTOR)
- [x] weapon scaling (probably adding SHIP_WEAPON_DAMAGE_FACTOR 6 and FIGHTER_WEAPON_DAMAGE_FACTOR 6 and related rules)
- [x] weapon upgrade techs (scale with SHIP_WEAPON_DAMAGE_FACTOR)
- [x] damage control techs (scale with SHIP_STRUCTURE_FACTOR)
- [x] ship shields, including robotic shields, GOOD_SHIELDS species and ship hulls 2x asteroid swarms (SetMaxShield bonus scale with SHIP_WEAPON_DAMAGE_FACTOR)
- [x] mine effects (SHIP_STRUCTURE_FACTOR)
- [x] planet defense scaling [Changing Number of Bouts - Planetary Defense](https://www.freeorion.org/forum/viewtopic.php?f=6&t=11439&p=98466#p98466) - scale defense with SHIP_WEAPON_DAMAGE_FACTOR, scale shields with SHIP_STRUCTURE_FACTOR
- [x] check game balance for fighters, maybe needs adjustment ("correct" multiplier should be 6*8/9==5.33 instead of six, but that leads to fractions and ignores how easy it is to take down fighters)
- [x] check game balance for flak (upping the bouts makes a 50% buff for flak), this may be ok 
- [x] check game balance for planetary shields, probably needs a buff
- [x] check reinforced hull tech and interaction with base hull and structure scaling
- [x] check reinforced hull, base hull, arc disruptors, mines, tech upgrades,  and structure scaling
- [x] if it still exists: make the base hull still easily destroyed by arc disruptor (i.e. decrease structure)
- [x] check this works for monsters
- [x] check this works for empire ships
- [x] have a look the resulting values are not too weird
- [x] remove line in forum signature

Long Term Followup Plan:
- damage totals in context of CombatBout condition (necessary for better combat UI) 
- fighter damage preview in context of CombatBout condition (necessary for better combat UI) 
- ship weapons use ranges (long range, short range, close range) using CombatBout condition
- upping hull cost/downing weapon cost as anti-chaff [Chaff spam](https://www.freeorion.org/forum/viewtopic.php?f=28&t=11525&p=99427&hilit=bouts#p99422)
- revisit the expendable munitions idea (four bouts context)

Further Reading list:
- [..how chaff scales the bouts](https://www.freeorion.org/forum/viewtopic.php?f=6&t=11421)
- [Multi-turn split fleet combat](https://www.freeorion.org/forum/viewtopic.php?f=6&t=11298&p=96348)

**Comment by magnate** [comment]
Wow, this is very interesting! Will read up and comment in the forum thread.

**Comment by agrrr3** [comment]
> Wow, this is very interesting! Will read up and comment in the forum thread.

Until now only [Changing Number of Bouts - Planetary Defense](https://www.freeorion.org/forum/viewtopic.php?f=6&t=11439&p=98466#p98466) exists.. Hopefully will be able to write up something soon.

**Comment by Vezzra** [comment]
@geoffthemedio, should these proposals really be considered a refactoring rather than a tweak?

**Comment by geoffthemedio** [comment]
@Vezzra debatable, but it seemed like a substantial reworking / rebalancig...

**Comment by Vezzra** [comment]
@geoffthemedio, I always thought of refactoring as somthing that means a purely technical code reorganisation/refactoring (that doesn't change program behaviour), not a rework/rebalancing of content/game mechanics...?

As opposed to a "tweak", something that changes current behaviour/mechanics (but not introducing new things, that would be "feature").

**Comment by agrrr3** [comment]
@Vezzra does the chosen tag have any meaning besides being descriptive?

I am mostly tweaking the use of scaling rules, introducing some new ones in the same manner, and then finally changing default values.

What makes this a kind of refactoring is that if you set the default values back, the same  behavior as currently should arise.

**Comment by Vezzra** [comment]
@agrrr3,

> does the chosen tag have any meaning besides being descriptive?

Filtering. If you want to see e.g. all feature requests, you can do that by filtering for "category:feature".

**Comment by adrianbroher** [comment]
@agrrr3 

> does the chosen tag have any meaning besides being descriptive?

Also in the future there could be workflow automation based on labels, which is where proper usage comes even more important.

**Comment by agrrr3** [comment]
Ok, the tweak part is done. 
Can somebody add testing-requested tag so I can get feedback on the balance?

Next thing would be advance the forum discussion and code review fixes.

There is one particular ugly thing and that is that I now hardcoded the base hull structure as one cant use calculation for structure value and as the value should be the base damage of the Arc Disruptor it needs to be calculated. I could probably script up the correct calculation by adding a effect but that is also ugly.

**Comment by Vezzra** [comment]
Um, as this is an issue, not a PR, adding "testing requested" doesn't make sense here. I assume you're requesting to add that tag to the #2908 pull request?

**Comment by agrrr3** [comment]
Yes, sorry, that comment was rather for implementation PR #2908
