### ISSUE TITLE
Interceptor bays can launch too many interceptors

### ISSUE THREAD

**Issue by magnate** [freeorion/freeorion#2902]
### Environment
* **FreeOrion Version**: b2112fe
* **Operating System**: Win7
* **Graphic card used**: Radeon 5750
* **Fetched as** 
  * Binary release
  * Weekly development build

[FreeOrion_Smeeeg_Smeg_0008_20200428_131950.zip](https://github.com/freeorion/freeorion/files/4545653/FreeOrion_Smeeeg_Smeg_0008_20200428_131950.zip)

[FreeOrion_Smeeeg_Smeg_0010_20200428_132451.zip](https://github.com/freeorion/freeorion/files/4545668/FreeOrion_Smeeeg_Smeg_0010_20200428_132451.zip)

### Description
Interceptor bays launch too many fighters. Five when they should be launching four (turn 8-9, attached). Six when they should be launching five (turn 10-11, attached). 

### Expected Result
Launch bays should launch four interceptors if Laser Fighters is current tech, and five if Plasma Fighters is current tech. 

Note that both save files above have the next fighter tech researched on the turn the combat takes place, but this should not increase the launch capacity until the following turn.

### Steps to reproduce
1. Build a ship with TWO interceptor hangars and ONE launch bay. 
2. Enter combat with it.

You will see one too many interceptors launch on round 2 (and one too few on round 3).

**Comment by agrrr3** [comment]
Could not read the game save. But could recreate it with your description.

TWO hangars and TWO launch bay work as expected (8-0 on Laser Fighters).. 
ONE hangar and TWO launch bays work as expected (4-0 on Laser Fighters).
And in this case TWO hangars and ONE launch bay launches six interceptors (6-2 Laser Fighters)

If I look at the stat dump of the ships, the (max) capacity of all those parts is at six.
I think the AI has already death ray fighters which could indicate that the effect is triggered by a different empire.

**Comment by agrrr3** [comment]
@geoffthemedio could this be a reordering issue in OwnerHasTech traversal like you fixed some? Could it be that OwnerHasTech use in the effect in FT_HANGAR_1 returns true because a different empire has that tech researched? The other option is that the target selection is wrong and applying the effect to the ships of a different empire although demanding OwnedBy empire = Source.Owner .

**Comment by agrrr3** [comment]
This specific instance can be workarounded by moving the effect to the fighter upgrade techs but OwnerHasTech usage is quite heavy so if there is a bug we should squeeze it.

**Comment by geoffthemedio** [comment]
> a reordering issue in OwnerHasTech traversal like you fixed some?

A what?

**Comment by geoffthemedio** [comment]
In:
````
    effectsgroups = [
        EffectsGroup
            scope = And [
                Source
                [[EMPIRE_OWNED_SHIP_WITH_PART(FT_BAY_1)]]
            ]
            activation = Source
            stackinggroup = "INTERCEPTOR_FAST_LAUNCH_EFFECT"
            effects = [
                SetMaxCapacity partname = "FT_BAY_1" value = (
                    3 +
                    Statistic If Condition = OwnerHasTech Name = "SHP_FIGHTERS_2" +
                    Statistic If Condition = OwnerHasTech Name = "SHP_FIGHTERS_3" +
                    Statistic If Condition = OwnerHasTech Name = "SHP_FIGHTERS_4"
                )
            ]
    ]
````
The `Statistic If Condition = OwnerHasTech Name = "SHP_FIGHTERS_2"` checks if there is any object owned by an empire that has that tech. It doesn't restrict to the same empire as the owner of the source object. Extending the `Condition =` to something like `condition = And [Source OwnerHasTech name = "SHP_FIGHTERS_2"]` might help, or perhaps better `condition = And [Target OwnerHasTech name = "SHP_FIGHTERS_2"]`

**Comment by agrrr3** [comment]
> Extending the `Condition =` to something like `condition = And [Source OwnerHasTech name = "SHP_FIGHTERS_2"]` might help, or perhaps better `condition = And [Target OwnerHasTech name = "SHP_FIGHTERS_2"]`

yes, that works, thanks a lot!

**Comment by agrrr3** [comment]
too bad, the merge didnt make it into the weekly build

**Comment by geoffthemedio** [comment]
It's just a FOCS change, so you can apply it easily to your local install or a server without needing a new release package.
