### ISSUE TITLE
Feature request: sitrep message when something is gifted

### ISSUE THREAD

**Issue by magnate** [freeorion/freeorion#2906]
### Environment
* **FreeOrion Version**: b2112fe
* **Operating System**: Win7
* **Graphic card used**: Radeon 5750
* **Fetched as** 
  * Binary release
  * Weekly development build

### Description
Allies can gift you ships or planets, if you have either in the system. At the moment the sitrep tells you nothing about this, so you don't know it's happened until you look. 

### Expected Result
A sitrep message saying `<Empire> gifted you <ship or planet name>`

**Comment by magnate** [comment]
Er something went wrong because I used angle brackets < and > 

I meant a sitrep message saying "EMPIRE_ gifted you SHIP_ or PLANET_"

**Comment by geoffthemedio** [comment]
Implemented by https://github.com/freeorion/freeorion/commit/a136f1635ef04b3e9ed1dcac59c35903cf18e7d5
