### ISSUE TITLE
Same seed on different platforms do not give same map

### ISSUE THREAD

**Issue by Vezzra** [freeorion/freeorion#294]
This issue has been brought up [here](http://www.freeorion.org/forum/viewtopic.php?p=80015#p80015).

Apparently, on Linux we get different maps from those generated on Windows and OSX with the same seed. Below is a screenshot I did of a default quickstart game with the 2015-08-10.2c00daa pre-release test build:

![rel045quickstart](https://cloud.githubusercontent.com/assets/10279417/9293607/e0bf35fa-4431-11e5-9401-cb7d2f2fae76.png)

On Windows I get exactly the same map.

@MatGB: Pls, can you compare this screenshot to the maps you get with a default quickstart game on your Linux and Windows systems when using the above build?

@Dilvish-fo: As you're on Linux too, can you do the same on your system?

Everyone else who's on Linux, if you can test this, please do! I really want to get this issue solved for 0.4.5.

**Comment by Morlic-fo** [comment]
I would expect the following to be the issue:
We pass a string as seed which then is hashed in some way which generally is platform dependent.

The solution in that case would be to use an integer seed instead.

**Comment by Vezzra** [comment]
The code section in question is:

```
// Initialize RNG with provided seed to get reproducible universes
int seed = 0;
try {
    seed = boost::lexical_cast<unsigned int>(GetGalaxySetupData().m_seed);
} catch (...) {
    try {
        boost::hash<std::string> string_hash;
        std::size_t h = string_hash(GetGalaxySetupData().m_seed);
        seed = static_cast<unsigned int>(h);
    } catch (...) {}
}
```

Does that really yield different hashes on different platforms? I thought this code is supposed to provide platform independent results. And even if, apparently the problem already arises with seed 0, which is an integer seed anyway?

**Comment by MatGB** [comment]
I've had a really busy weekend and am exhausted, but I thought I'd just check in and answer the basic question.

As far as I can see, and haven't had time to test on Windows, I get the same layout of systems and placements, but the starting positions for all the empires are completely different.  I need to check and confirm this but the pictures posted by both you and @Deepsloth look to be the same map, but I start near the top (where Enif Alpha is on your pic), and there's an AI (Etty) that starts at Grotto. The systems definitely have different names. Polaris has a toxic world in, and the system on your map that's deep space two jumps to the right towards Cursa Alpha has a Sentinel guarding an Ancient Ruins.

So we're getting the same basic system layout, but different names, placements and similar.

**Comment by raptor** [comment]
32/64 bit differences occur in boost::hash.  See here:

https://stackoverflow.com/questions/17426493/get-32-bit-hash-value-from-boosthash

(Sorry for the drive-by comment)

**Comment by Vezzra** [comment]
Created a PR with an attemped fix, please test: #297

**Comment by Vezzra** [comment]
Created a PR in another attempt to fix the issue: #298. Pls test.

**Comment by Vezzra** [comment]
As mentioned in the discussion on PR #297, apparently some galaxy shapes _do_ give identical maps across platforms, but not all. Elliptical seems to be fine, while spiral gives different maps. I've looked at the code for these two, and the only difference as far as use of rng functions are concerned is that spiral uses a function for gauss distribution, which elliptical does not.

Another shape that uses this function for gauss distribution is ring. Here is a screenshot of seed 0 ring galaxy with all other settings on default (OSX):

![seed0_ring](https://cloud.githubusercontent.com/assets/10279417/9332095/4f552f32-45c3-11e5-86fd-a803f0b9c206.png)

Please compare that to the map you get on your systems (Linux particularly).

**Comment by geoffthemedio** [comment]
With the latest master, MSVC2013:

![ring0_galaxy](https://cloud.githubusercontent.com/assets/11386908/9955984/4504ee1a-5df5-11e5-9446-cbd3934ba9db.jpg)

**Comment by Vezzra** [comment]
Seems to be identical, but IIRC Mac and Win have always been. It's on Linux where we get different results... can someone of our Liinux folks provide a screeshot (seed 0, ring, all other settings on default) for comparison?

**Comment by raptor** [comment]
Linux (openSUSE 13.2 x86_64) screenshot with those settings at commit cb7b5c0b:
![snapshot6](https://cloud.githubusercontent.com/assets/6452412/9966093/f45e10d8-5df7-11e5-93cc-d64b66a31e69.png)

**Comment by Vezzra** [comment]
Yep, that further confirms my suspicion - it's the function for gauss distribution used in the C++ code that apparently yields different results on Linux. Well, I'm going to migrate the other galaxy map generator functions to Python, that should take care of the issue.

**Comment by Vezzra** [comment]
After porting the rest of the galaxy shapes to Python, a seed 0 ring galaxy with all other settings on default looks like this on OSX (commit a1b897376cfc03b5f34b9d1032299e1a0d85b0a1):

![seed0_ring](https://cloud.githubusercontent.com/assets/10279417/9982977/43ce2de0-5fee-11e5-9799-1a627c394d24.png)

Please post screenshots from other platforms (especially Linux) for the same settings.

**Comment by raptor** [comment]
Same Linux system, commit efaf3cfb:

![snapshot7](https://cloud.githubusercontent.com/assets/6452412/9983409/bdb7e240-5fb7-11e5-9e37-f082d4847c70.png)

**Comment by geoffthemedio** [comment]
![ring150](https://cloud.githubusercontent.com/assets/11386908/9988366/35e6efac-6050-11e5-8d09-e706a5cef0ec.png)

**Comment by Vezzra** [comment]
Very good. So, I consider the problem solved so far and will close this issue.
