### ISSUE TITLE
Game crashes when issuing orders to ships

### ISSUE THREAD

**Issue by Oberlus** [freeorion/freeorion#2942]
Bug Report
==========

Environment
-----------
* **FreeOrion Version**: master b7f03df50c3d7648bf47441b1fdb7f08cff65f79
* **Operating System**: Ubuntu 18.04, boost 1.65.
* **Fetched as**
  * Compiled from source

Description
-----------
Game crashes when issuing orders to ships.

Logs report several errors.
Client complains many times about
```
Order.cpp:1199 : Couldn't create ship design.
DesignWnd.cpp:687 : Ship design is invalid
```
Server complains many times about
```
Effects.cpp:3714 : Conditional::Execute has a subcondition that depends on the target object. The subcondition is currently evaluated once to pick the targets, so when evaluating it, there is no defined target object. Instead use RootCandidate.
```
[freeorion_logs.zip](https://github.com/freeorion/freeorion/files/4614934/freeorion_logs.zip)

Steps to reproduce
------------------
* Start FreeOrion and a new game (Quick Start or Single Player -> OK).
* Order ships to move, one by one, until game crashes (order in which you pick the ships or destination doesn't seem to matter). In my case it crashes always at the third ship I command to move.
* Alternatively, pick a single ship and command it to move to several places: it crashes at the second order.

**Comment by Oberlus** [comment]
@l29ah reported in the chat room that it also crashes to him (master, same commit than above) with boost 1.73.

**Comment by geoffthemedio** [comment]
I suspect it's related to the recent switch from `boost::bind` to `std::bind`, maybe interacting with the `boost::signals2::at_front` parameter somehow...?

I can reproduce with master, but after switching several of the `std::bind` back to `boost::bind`, it doesn't happen...

**Comment by geoffthemedio** [comment]
https://github.com/freeorion/freeorion/commit/9eb021f0a2d1b1ba55cff2b7a9825706734b96a3 fixes it for me...

**Comment by Oberlus** [comment]
Tested. Closing as solved.

**Comment by geoffthemedio** [comment]
No idea why `std::bind` has this issue but `boost::bind` doesn't. The list of differences between them that I saw didn't seem to have anything relevant.

**Comment by adrianbroher** [comment]
The problems is probably same as I had with the lambdas. boost signals doesn't know how to handle handle classes, which are not trackable for deletion.  I assume that boost::signals has some special code, which scrapes the boost::bind parameters for trackable subclasses and frees the connection on delection.  This scraping functionality does not exists for the std::bind classes or lambdas.

**Comment by geoffthemedio** [comment]
I don't think any relevant objects are being deleted in this case though... It's just disconnecting and reconnecting signals of fleets after move orders. So what would need to be trackable?

**Comment by adrianbroher** [comment]
The `FleetWnd` instance.

**Comment by geoffthemedio** [comment]
The `FleetWnd` isn't destroyed and recreated when ordering a fleet to move, I think?
