### ISSUE TITLE
Can't scroll research tree past some point

### ISSUE THREAD

**Issue by Voker57** [freeorion/freeorion#2947]
Bug Report
==========

Environment
-----------

* **FreeOrion Version**: d9d4de532d1ef80c71a07e7fa3362
* **Operating System**: debian sid
* **Graphic card used**: gtx 1080
* **Fetched as** 
  * Compiled from source

Description
-----------

Can't scroll research tree vertically fully. Video: https://ipfs.io/ipfs/bafymbzacidiyjvew332cbwzh7v3icul3l4n4v3yylw2eh2q2mnev3ht5wvqcm3uwyvbkpybzk4h7p4hfjua5isgqg56jmxvoskq2hhtmppbibi4z

Expected Result
---------------

can scroll tree normally

Steps to reproduce
------------------

* start game
* open tree
* try to scroll
[freeorion.log](https://github.com/freeorion/freeorion/files/4621445/freeorion.log)

**Comment by Voker57** [comment]
```
8bdc0802ac235e8ec7b39146824264cdaa96a362 is the first bad commit
commit 8bdc0802ac235e8ec7b39146824264cdaa96a362
Author: Marcel Metz <mmetz@adrian-broher.net>
Date:   Fri Jun 8 12:21:34 2018 +0200

    Unfold TechTreeLayout Column::Size function

 UI/TechTreeLayout.cpp | 18 ++++++++----------
 UI/TechTreeLayout.h   |  2 --
 2 files changed, 8 insertions(+), 12 deletions(-)
```

**Comment by Voker57** [comment]
Reverting the commit fixes the bug.

**Comment by adrianbroher** [comment]
The bug is not obvious from the commit diff.  I'm building that commit with a break statement inserted because that's the only difference I could think of.

**Comment by adrianbroher** [comment]
Can you check if the following patch fixes the issue?

```
From 8a6ba93145d6258e993f61f76f61838d986c5b5f Mon Sep 17 00:00:00 2001
From: Marcel Metz <mmetz@adrian-broher.net>
Date: Wed, 13 May 2020 18:38:53 +0200
Subject: [PATCH] Fix #2947

---
 UI/TechTreeLayout.cpp | 1 +
 1 file changed, 1 insertion(+)

diff --git a/UI/TechTreeLayout.cpp b/UI/TechTreeLayout.cpp
index 749cd5d85..85a2ebe80 100644
--- a/UI/TechTreeLayout.cpp
+++ b/UI/TechTreeLayout.cpp
@@ -202,6 +202,7 @@ void TechTreeLayout::DoLayout(double column_width, double row_height, double x_m
         for (unsigned int j = row_index[i].column.size(); j --> 0; ) {
             if (row_index[i].column[j])
                 cur_row_count = j;
+                break;
         }
         row_count = std::max(row_count, cur_row_count);
     }
-- 
2.25.3
```

**Comment by adrianbroher** [comment]
The provided PR fixes the issue for me, feel free to verify.

**Comment by Voker57** [comment]
It works, but you might want to fix the indentation.

**Comment by adrianbroher** [comment]
> It works, but you might want to fix the indentation.

Fixed the code, the first version was actually wrong.
