### ISSUE TITLE
Spatial Distortion Generator description does not match effect

### ISSUE THREAD

**Issue by aschuch247** [freeorion/freeorion#295]
In release-0.4.5 (febea19b90a113567b4e374ef5b980a0aedbdab1) the effect description of the Spatial Distortion Generator reads as:

"Manipulates the dimensional properties of adjacent starlanes. Any enemy ships attempting to reach the system containing this building will be redirected back the way they came, or to a random adjacent star. Only ships fast enough to traverse the starlane in one turn are able to avoid these effects. This is activated with the Spatial Distortion focus."

However, the effect actually happens to fleets either moving to the system or to a directly connected system.

This means that if a fleet moves from somewhere to a system close to an enemy system having a colony with this focus but not to the system itself, and the fleet takes more than one turn to arrive, it still will be "teleported" to one of the neighbouring systems of the one with the Spatial Distortion focus.

It happened in multiplayer. I never noticed that before, but very likely because the AI just does not use this focus (or I never seen it using it).

**Comment by Vezzra** [comment]
Created PR #302 with a fix for the reported issue.

**Comment by Vezzra** [comment]
Fixed in 5c1031798e109d0f081afc73bd9e18c4298487da (master) and d69201f1a58e8edfffe394faaacd2b8458f8468d (release branch).
