### ISSUE TITLE
Cannot Scroll Up in Research Screen

### ISSUE THREAD

**Issue by urshmost** [freeorion/freeorion#2951]
Bug Report
==========
In the Research Screen I cannot drag the tech tree high enough up to see the bottom half of it.  This appears to have started in the 2020-05-12 release.

Environment
-----------
* **FreeOrion Version**: 2020-05-12.9eb021fj
* **Operating System**:  Win 10 Home 64 bit
* **Graphic card used**: Nvidia geforce 670 
running freeorion in Windowed mode, various resolutions
* **Fetched as** :  * Weekly development build

Description
-----------
In the Research Screen I cannot drag the tech tree high enough up to see the bottom half of it.  This appears to have started in the 2020-05-12 release.

it appears to be somehow related to the 'Learning' items.  If I toggle them off in the toolbar the screen seems to work normally?

only affects tree view, list view seems fine.

Steps to reproduce
------------------

install freeorion
start quick game
access tech screen
attempt to drag tech tree upwards

**Comment by adrianbroher** [comment]
Duplicate of #2947

**Comment by urshmost** [comment]
sorry, I only searched on open issues.

**Comment by o01eg** [comment]
@Vezzra What if publish early weekly test build as current one contains multiple fixed bugs?

**Comment by geoffthemedio** [comment]
I think Vezzra should not be expected to do any extra out-of-cycle test builds. If someone really needs a new test build, they can build it themselves...

**Comment by adrianbroher** [comment]
> sorry, I only searched on open issues.

No need to, nobody knows the full issue history.

**Comment by Vezzra** [comment]
> What if publish early weekly test build as current one contains multiple fixed bugs?

I'm usually willing to throw in an extra test build now and then on request, but currently I have too much on my plate, sorry.
