### ISSUE TITLE
freeoriond crashes on malformed player name

### ISSUE THREAD

**Issue by l29ah** [freeorion/freeorion#2966]
Toss the attached file at freeoriond tcp socket and it will abort.
![malformed](https://user-images.githubusercontent.com/31852/82388912-6834d280-9a43-11ea-83e9-9e0b826afefd.gif)

**Comment by geoffthemedio** [comment]
You attached an apparently broken .gif file. What does any file have to do with a player name...?

**Comment by o01eg** [comment]
@geoffthemedio I suppose it's not a git file at all.
```
   ‡  <?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE boost_serialization>
<boost_serialization signature="serialization::archive" version="17">
<player_name>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </player_name>
</boost_serialization>
```

**Comment by l29ah** [comment]
I added .gif to the file name because github has only a few kinds of allowed "extensions" for the attachments.

**Comment by geoffthemedio** [comment]
Attaching a log of such a crash would be helpful. There are numerous places where it might try to extract data from a message and throw an exception and crash if the incoming message isn't properly formatted XML with the expected fields.

#2970 might help...
