### ISSUE TITLE
Regression: AI fighter damage estimation is off

### ISSUE THREAD

**Issue by agrrr3** [freeorion/freeorion#2973]
I'm pretty sure you don't want to increment ```flying_fighters``` in all these lines but actually assign the RHS?

_Originally posted by @Morlic-fo in https://github.com/freeorion/freeorion/pull/2908/files/f7f7ead32ec1b73b7478edda84862bd94f634dac_

this results in the AI estimating fighter strength too high.

Also in the same code review morlic reports:
> .. organic growth effects appear to need corresponding adjustments in AIDependencies as well.

This PR is intended to fix those two bugs.

**Comment by Morlic-fo** [comment]
Fixed by #2974
