### ISSUE TITLE
AI gives up colonizing after some time

### ISSUE THREAD

**Issue by Oberlus** [freeorion/freeorion#2983]
Bug Report
==========

Environment
-----------
* **FreeOrion Version**: v0.4.10+ [build 2020-05-24.cfef763] CMake
  * Compiled from source
* **Operating System**: Ubuntu 18.04

Description
-----------
Check out screenshot:
![AI_gives_up_colonizing](https://user-images.githubusercontent.com/28650914/82807619-6d04e680-9e88-11ea-97c5-2c84a91a6e1d.png)

Light blue is my empire (Human). The continuous increase in colonies is from peaceful colonization, very few planet invasions.
There is no obvious or reasonable reason for the AIs to stop devoting part of their production to occupy more colonies in their safe space.

Expected Result
---------------
AIs do not stop devoting part of their production to occupy more colonies in their safe space.

Steps to reproduce
------------------
This happens in every game if played long enough.
I attach two save files from my current game, turns 92 and 184, and log files from the most recent turns up to 187.
[AI_not_colonizing.zip](https://github.com/freeorion/freeorion/files/4676882/AI_not_colonizing.zip)

**Comment by Oberlus** [comment]
More on this issue:

This Trith AI did well at start but stopped expanding seemingly when it could not find any more planets within its supply. Check out screenshot. Wheeler has two interesting planets to colonize, but it would need using a colony ship. That AI did nothing but produce military for the last 100 turns, although it has not met any of its neighbours (this is a 4 AI 200 system disc galaxy).
@Morlic-fo @Cjkjvfnby Maybe AI is relying only on outpost ships and thus gets stuck?

![TrithExobotsIgnoringRadiatedSpecials](https://user-images.githubusercontent.com/28650914/82880811-34741400-9f3f-11ea-9f5d-7d98d4dfef76.png)

**Comment by Cjkjvfnby** [comment]
Good question. I'll try to find time for the investigation. Feel free to ping me in a week.

**Comment by Oberlus** [comment]
In another similar game I found that an Egassem AI that also stopped colonizing had an Inferno world within its supply, so maybe it is not related to relying only on outposts.

**Comment by Oberlus** [comment]
Update:
After fixing #2993, AIs seems to behave _slightly_ better regarding colonization of available planets. Their graphs for number of colonies no longer becomes flat for hundreds of turns, they might get some more colonies, eventually.
But the issue that at some point (around turn 130-160 on standard galaxy settings) they seemingly focus too much on military and neglect colonization of available planets with nice stats (environment and size) persists. Devoting a small percent of their production (10%) to new colonies when available would improve their performance.

**Comment by geoffthemedio** [comment]
Status of this?

**Comment by Oberlus** [comment]
I think this is solved. @Grummel7, any objection to close it?

**Comment by Grummel7** [comment]
I guess back then this was mostly caused by the Outpost Base bug.
I am not really happy with the way big empires keep spreading, but they do no longer stop dead like this.

**Comment by geoffthemedio** [comment]
with something nearish master...
![colonies](https://user-images.githubusercontent.com/11386908/183244182-0a459ad3-ac66-480b-950b-6afcc0910223.png)
