### ISSUE TITLE
Design window is empty

### ISSUE THREAD

**Issue by Querens** [freeorion/freeorion#2987]
Bug Report
==========

Design window does not contain the result design

Environment
-----------

* **FreeOrion Version**:
* **Operating System**:
* **Graphic card used**:
* **Fetched as** 
  * Binary release
  * Weekly development build
  * Compiled from source

Description
-----------

When I try to create a new design I can see only hulls and mods, but when I choose anything there is no result shown in the window where it has to be

Expected Result
---------------

I expect to see the result of puting parts together
![designBag](https://user-images.githubusercontent.com/55858424/82929258-07018780-9f8c-11ea-9212-f0d89c10c732.png)

Logs
------------------

[freeorion.log](https://github.com/freeorion/freeorion/files/4696102/freeorion.log)

**Comment by Oberlus** [comment]
I don't have this problem with v0.4.10 RC1 (d034b5d)
What version are you playing, in which operating system, and how was it fetched?

**Comment by geoffthemedio** [comment]
In addition to the info @Oberlus requested (which are in the issue template for a reason!) attaching .log files from the human client `freeorion.log` and server `freeoriond.log` from immediately after observing this would also be helpful.

**Comment by Querens** [comment]
Logs are added

**Comment by Querens** [comment]
> In addition to the info @Oberlus requested (which are in the issue template for a reason!) attaching .log files from the human client `freeorion.log` and server `freeoriond.log` from immediately after observing this would also be helpful.

The game g

**Comment by Voker57** [comment]
Saves and server logs can be obtained from @o01eg

**Comment by Oberlus** [comment]
@Querens 
I see from the log that you are playing with v0.4.9+ [build 2020-05-20.73ff009] CMake
If this is from current MP game in o01eg's server, you must upgrade to the server version, which is v0.4.10 [build 2020-05-26.d034b5d].
Your problem might be just that.

**Comment by geoffthemedio** [comment]
from the log:
````
Connected to server at host_name: freeorion-lt.dedyn.io
...
[warn] client : ClientApp.cpp:166 : Checksum received from server does not match client checksum.
...
[error] client : ResearchQueue.cpp:34 : SetTechQueueElementSpending found null tech on research queue?!
````
So a version mismatch might be the issue.

**Comment by Querens** [comment]
> @Querens
> I see from the log that you are playing with v0.4.9+ [build 2020-05-20.73ff009] CMake
> If this is from current MP game in o01eg's server, you must upgrade to the server version, which is v0.4.10 [build 2020-05-26.d034b5d].
> Your problem might be just that.

Didn't help

**Comment by geoffthemedio** [comment]
What if you start a single player game?

**Comment by Querens** [comment]
> What if you start a single player game?

Same

**Comment by geoffthemedio** [comment]
Delete your config.xml maybe?

**Comment by Querens** [comment]
> Delete your config.xml maybe?

Didn't help either

**Comment by Querens** [comment]
Fresh logfile after updating the game

[freeorion.log](https://github.com/freeorion/freeorion/files/4706171/freeorion.log)

**Comment by agrrr3** [comment]
@Querens Are you building that yourself or using something provided?

**Comment by agrrr3** [comment]
The first error is
`20:12:01.082145 {0x00007f67fc34b840} [error] client : DesignWnd.cpp:890 : DisplayedShipDesignManager::Load design with id = 20 has an obsolete_ui_event_count = 40 which does not satisfy 0 < obsolete_ui_event_count < m_obsolete_ui_event_count = 40`

**Comment by Querens** [comment]
> @Querens Are you building that yourself or using something provided?

Myself

**Comment by o01eg** [comment]
Is something happened with "Design Details" windows?

**Comment by geoffthemedio** [comment]
If you have some saved designs, you might need to delete some of them.

**Comment by Querens** [comment]
I've recieved an advice to move windows around( which I did actually long ago), but this time I decided to do that more actively. Under the window "Design starts"( the one with hulls) I've found something which reminds the lost window. But it's screwed and can't be manipulated besides of moving it around

![designFocked](https://user-images.githubusercontent.com/55858424/83337531-e2c3e480-a2c4-11ea-8867-d6dfc29d456b.png)

**Comment by Querens** [comment]
> If you have some saved designs, you might need to delete some of them.

I never save designs

**Comment by Vezzra** [comment]
Can anyone reproduce this issue?

**Comment by agrrr3** [comment]
Hyperant reported this for the windows build.

**Comment by Querens** [comment]
This bug can be kludged by resizing the window manualy in the config.xml

**Comment by geoffthemedio** [comment]
It really is fixed by editing config.xml but not by deleting config.xml even if you don't have a persistent_config.xml ? If so, that's bizzare.

**Comment by Oberlus** [comment]
We might need to open a new issue for the Design Details window getting wrong dimensions and positions when connecting to a server with a somewhat incompatible version and pressing the turn button. At least, this is what seemingly happened here. This issue appears hard to reproduce, if it is dependent on particular characteristics of the server and client code (such as one using std::bin and the other boost::bind calls), and might in fact not happen again.

**Comment by geoffthemedio** [comment]
Does the client even send UI window layout data to the server? I would have thought that would just be stored locally in config.xml.

If there are inconsistencies between the clients and server in the use of `bind` calls, it's not in UI code, which the server doesn't have (most of).

**Comment by Oberlus** [comment]
Yes, but maybe it caused some random memory problem (as the many crashes) that ended up affecting config file. Blind shot.

**Comment by o01eg** [comment]
> Does the client even send UI window layout data to the server?

@geoffthemedio Yes
https://github.com/freeorion/freeorion/blob/599c86c37fbe8e6c093e57e0cedc5be55615dfee/client/ClientApp.cpp#L110-L111

**Comment by geoffthemedio** [comment]
https://github.com/freeorion/freeorion/blob/master/util/MultiplayerCommon.h#L90

nothing about window layout...

**Comment by Vezzra** [comment]
Considering how hard it is to reproduce the issue, and that we have a workaround, I can understand why this has been closed. Nevertheless we need to specify: closed as what? Resolved? Workaround? Invalid? Won't fix?

Or maybe this should be reopened, seeing as the underlying issue hasn't been resolved at all?

**Comment by geoffthemedio** [comment]
The minimum window sizes recently added should probably prevent it now, so probably resolved?
