### ISSUE TITLE
Can't start single player game: Connection to the server has been lost

### ISSUE THREAD

**Issue by Oberlus** [freeorion/freeorion#2994]
Bug Report
==========

Environment
-----------
* **FreeOrion Version**: v0410 d034b5d
* **Operating System**: Windows 8.1
* **Fetched as**
  * Binary release

Description
-----------
Quickstart or Single Player game start gives me a "Connection to the server has been lost".

Could this be a problem with my Firewall configuration? It's the first time I install FO in this Windows machine. Connecting to o01eg's MP server works just fine.

[freeorion.log](https://github.com/freeorion/freeorion/files/4697789/freeorion.log)

[freeoriond.log](https://github.com/freeorion/freeorion/files/4697790/freeoriond.log)

**Comment by geoffthemedio** [comment]
Server log ends with
````
21:26:49.949381 {0x00000da4} [error] network : servernetworking.cpp:186 : PlayerConnection::~PlayerConnection: shutdown error #10009 "El identificador de archivo proporcionado no es válido" for player id 1
21:26:49.949381 {0x00000da4} [error] server : dmain.cpp:105 : main() caught exception(std::runtime_error): Process::Process : Failed to create child process.  Windows error was: "El sistema no puede encontrar el archivo especificado.
````

The server is trying to start AIs at this location:
 `server : serverapp.cpp:257 : starting AIs with C:\Program Files (x86)\FreeOrion\freeorionca.exe`
which seems consistent with the server's location as started by the human client:
`client : humanclientapp.cpp:442 : HumanClientApp::StartServer: C:/Program Files (x86)/FreeOrion/freeoriond.exe`

**Comment by o01eg** [comment]
@Oberlus Could you try launch AI manually or check AI logs?

**Comment by Oberlus** [comment]
When I did the installation and the firewall asked for permissions, I must have clicked something wrong what forbid the creation of FreeOrionCA.exe. Reinstalling the game and telling the firewall that it was a installation/update solved the issue.

Closing it as invalid.
