### ISSUE TITLE
Sly & Gaia special - planet type cycling, colonization weighting

### ISSUE THREAD

**Issue by rrobgill** [freeorion/freeorion#3001]
Description

Prevent planet types cycling when Sly inhabit a planet with Gaia special, and have AI devalue Gaia special when evaluating planets for Colonization

Gain

1. At present the planet cycles through the planet types never stopping. Clearly Sly will never reach good suitability on a non-gaseous planet.

2. When evaluating planets for Colonization, the AI presently treats a Gaia special as favorable for Sly, even though Sly receives no benefit from it.

Exobots also receive no benefit from Gaia specials, a Gaia special does not transform the planet type when inhabited by them, and the AI devalues the Gaia special when evaluating planets for Colonization.

Discussion

https://www.freeorion.org/forum/viewtopic.php?f=6&t=11685

**Comment by agrrr3** [comment]
great catch!

**Comment by Vezzra** [comment]
That isn't a feature request, but a bug report. The current behavior should be considered a bug.

**Comment by Vezzra** [comment]
@rrobgill, with #3002 merged, can this be closed as resolved?

**Comment by rrobgill** [comment]
Yes, resolved by #3002
