### ISSUE TITLE
Xenophobic harassment not working

### ISSUE THREAD

**Issue by rrobgill** [freeorion/freeorion#3009]
Environment

Ubuntu 18.04, https://github.com/freeorion/freeorion/commit/7c259917324bdfa2f452ef976ba0726a2783b639 master compiled from source.
Checked back to distro packaged version 0.4.7.1 and the same problem is seen.

Description

Planets in suitable proximity to xenophobic species are not receiving malus to industry, research or happiness.

![image](https://user-images.githubusercontent.com/35944068/83845119-c9250180-a6f7-11ea-85dc-1014b78067f0.png)
(Herbig a, located one jump from Herbig B is inhabited by Trith. Herbig B I is inhabited by Scylior).

Expected Result
Malus to industry, research, happiness.

Steps to reproduce
Start game, wait for xenophobes to bump up against with anyone else

**Comment by Voker57** [comment]
Are they not in the same empire? Xenophobia only works within one empire.

**Comment by rrobgill** [comment]
My mistake.
