### ISSUE TITLE
Graph Axis Label Float Precision Quirk

### ISSUE THREAD

**Issue by geoffthemedio** [freeorion/freeorion#3016]
![GraphAxisLabelsRounding](https://user-images.githubusercontent.com/11386908/84059288-9f4f3180-a9ba-11ea-8fec-5a3b36beb7c9.png)

The axis labels in the pedia graphs have some buggy displays of non-integer numbers when the range of what's being graphed in small.

**Comment by Vezzra** [comment]
Did #3032 sufficiently address the issue? Can we close this as resolved?
