### ISSUE TITLE
Multiple Sitreps can be reported for Single Black hole creation event

### ISSUE THREAD

**Issue by rrobgill** [freeorion/freeorion#3017]
Bug Report
==========

Environment
Current master compiled from source on Ubuntu 18.04

Description
Events which only occur once can have multiple sitreps  if several objects were able to cause the same event. (For example, create three Artificial Black Hole buildings in the same system and if the complete building on the same turn and activate only a single Black Hole is produced, but the message is displayed three times in that turn).

![2020-06-09_14:03:08!](https://user-images.githubusercontent.com/35944068/84105069-be73b080-aa06-11ea-87e7-145544cae3df.png)

Expected Result

Display a single SitRep message for an event which only occurs once, even if it has multiple potential triggers.

Steps to reproduce
Create > 1 Artificial Black Hole Building in a system

**Comment by agrrr3** [comment]
Can you target it on the system and use a stackinggroup?

As an example why this might be no bug: an event which uses immediate
values can change the same meter multiple times.

**Comment by rrobgill** [comment]
Resolved by #3019
