### ISSUE TITLE
Asteroid Processors remain functional on artificial planets

### ISSUE THREAD

**Issue by rrobgill** [freeorion/freeorion#3023]
Environment
Current master compiled from source on Ubuntu 18.04

Description
If an artificial planet (including via Factory Planet or Paradise World) is created from asteroids containing Asteroid Processor or Reformation processor, these buildings remain on the planet, and continue to function even in the absence of asteroids.

Expected Result
Asteroid processing facilities destroyed if asteroids turned into planet. (Similar to handling of Gas Giant generators).

Steps to reproduce
1 Build Asteroid Processor / Reformation Processor on an asteroid
2 Create artificial planet

![2020-06-11_12:23:55!](https://user-images.githubusercontent.com/35944068/84338084-b2b0f700-ab8a-11ea-8f37-8cc1daeae13f.png)

**Comment by geoffthemedio** [comment]
Resolved by #3024
