### ISSUE TITLE
Connection to the server lost when adding Continuous Scanning policy to slot and pressing Turn

### ISSUE THREAD

**Issue by Oberlus** [freeorion/freeorion#3036]
Bug Report
==========

Environment
-----------
* **FreeOrion Version**: ed213fb
* **Operating System**: Ubuntu 18.04
* **Fetched as** 
  * Compiled from source

Description
-----------
When adding Continuous Scanning (military policy), pressing next turn causes connection to the server lost. Not adding it and removing/adding other policies does not cause the problem.

[FreeOrion_Oberlus_Abyss_0056_20200613_211109.zip](https://github.com/freeorion/freeorion/files/4775469/FreeOrion_Oberlus_Abyss_0056_20200613_211109.zip)
[logs.zip](https://github.com/freeorion/freeorion/files/4775470/logs.zip)

**Comment by rrobgill** [comment]
#3037 will fix this for POPULATION

**Comment by geoffthemedio** [comment]
> #3037 will fix this for POPULATION

Doesn't appear relevant...

**Comment by geoffthemedio** [comment]
Are you sure it's those particular policies and not any second policy or any / any second policy in a category, or only when multiple slots are available or somesuch?

**Comment by Oberlus** [comment]
> Are you sure it's those particular policies and not any second policy or any / any second policy in a category, or only when multiple slots are available or somesuch?

My initial report was wrong. It seems to only happen with the Continuous Scanning policy.
I've tried (from the state of having only Centralization):
- Removing Centralization, next turn -> works.
- Removing Centralization & Adding Population, next turn -> works
- Adding Population, next turn -> works.
- Adding Population & Continuous Scanning, next turn -> fails
- Adding Continuous Scanning, next turn -> fails
- Removing Centralization, next turn, adding Continuous Scanning, next turn -> fails
- Adding Population, next turn, adding Continuous Scanning, next turn -> fails

I also tried other combinations of additions and removals of policies and advancing several turns before trying Continuous Scanning. It always fail with Continuous Scanning.

**Comment by geoffthemedio** [comment]
Is Continuous Scanning the only military policy you tried?

Try with https://github.com/freeorion/freeorion/commit/b62be60428ee0479744b568886b03d32db254e87

**Comment by Oberlus** [comment]
> Is Continuous Scanning the only military policy you tried?
> 
> Try with [b62be60](https://github.com/freeorion/freeorion/commit/b62be60428ee0479744b568886b03d32db254e87)

Yes, that's the only one, but I suspect you are right and TurnPolicyAdopted is the culprit, and Continuous Scanning is the only policy that uses TurnPolicyAdopted.

I'm compiling with b62be60 and report back in an hour, hopefully.

**Comment by Oberlus** [comment]
> Try with [b62be60](https://github.com/freeorion/freeorion/commit/b62be60428ee0479744b568886b03d32db254e87)

That solved the issue. Haven't tried other military policies yet. I'll advance more in the game before closing this.

**Comment by geoffthemedio** [comment]
reopen if still broken
