### ISSUE TITLE
Military Command can be constructed more than once

### ISSUE THREAD

**Issue by Oberlus** [freeorion/freeorion#3040]
Bug Report
==========

Environment
-----------
* **FreeOrion Version**:  ed213fb + b62be60
* **Fetched as** 
  * Compiled from source

Description
-----------
Military Command building, which grants an extra military policy slot, can be constructed in more than one planet.
I haven't tested, but it seems constructing more than one would make no effect (due to the stacking group MILITARY_COMMAND_SLOT_METER_EFFECT)
This is probably a bug in the reference to the building name ("_DESC" is wrong): https://github.com/freeorion/freeorion/blob/28d3d6458d255e039010c967e211cb4961cee86b/default/scripting/buildings/MILITARY_COMMAND.focs.txt#L13

Expected Result
---------------
Since the effect is not supply-bound and the fluff/name is about headquarters, the building should be unique for each empire, as the Imperial Palace.

**Comment by geoffthemedio** [comment]
Fixed the `_DESC`: https://github.com/freeorion/freeorion/commit/6a1035d8f372ff463c056fe9b9fd490a00bbdc84

**Comment by Oberlus** [comment]
Closing as solved (tested)
