### ISSUE TITLE
Removing batch of ships from construction queue removes the wrong one

### ISSUE THREAD

**Issue by Oberlus** [freeorion/freeorion#3042]
Bug Report
==========

Environment
-----------
* **FreeOrion Version**: v0.4.10+ build 2020-06-14 9af9a91 CMake
* **Operating System**: Ubuntu 18.04
* **Fetched as** 
  * Compiled from source

Description
-----------
Having two batches of the same kind in the Production Queue and removing the newest (bottom one) causes instead the removal of the oldest (top one).
Queue before removal:
![before](https://user-images.githubusercontent.com/28650914/84592245-609afa80-ae44-11ea-9185-8ce2adc6be1a.png)
Queue after removal of the last (bottom) item:
![after](https://user-images.githubusercontent.com/28650914/84592247-62fd5480-ae44-11ea-8031-ffb6a45b7fc9.png)
Notice the progress of the outpost ship has been lost, presumably because the one removed was actually the one with some progress instead of the selected one.

This is not necessarily limited to items of the same kind, but I have only seen it happen for that situation.
[logs.zip](https://github.com/freeorion/freeorion/files/4776312/logs.zip)
[FreeOrion_Oberlus_Abyss_0039_20200614_124409.zip](https://github.com/freeorion/freeorion/files/4776313/FreeOrion_Oberlus_Abyss_0039_20200614_124409.zip)

Steps to reproduce
------------------
* Load attached game.
* Go to Production Queue and remove the last item.
* Issue occurs.

**Comment by Oberlus** [comment]
Update:

This does not only affects "Remove from Queue", also "Pause", "Move to Queue Top", etc.

One can drag&drop the top one after (under) the bottom one and it will work, the queue will be reordered, but the bottom one cannot be drag&dropped in a different queue spot: it will be the top one which gets relocated. 

So it seems the item ID is wrong for most operations except for drag&drop the top one to a lower queue position.

If adding more outpost ships to the queue, the new ones won't be affected by the bug: you can place one of the new ones in any queue spot and pause or remove them without interfering with the older outpost ships in the queue. So the ID problem might come from a previous turn.

**Comment by o01eg** [comment]
Could it be reproduced for 0.4.10?

**Comment by Oberlus** [comment]
> Could it be reproduced for 0.4.10?

I don't have a save file, but I have encountered this before in MP games, prior to v0.4.10.

**Comment by Vezzra** [comment]
In that case this bug should be considered release-blocking. While not outright game-breaking, it's certainly serious enough.

**Comment by Oberlus** [comment]
More on this:

This happens after loading a game with batches of the same items (not tested if it happens with buildings, but it certainly happens with any kind of ships).
That is, having several batches of the same ship in the queue won't cause any problem until you save and reload.

So it seems the problem is that all batches of the same ship design get the same ID after reloading?


**Workaround**
To remove any batch of same type that is not the top one, user can move top one to a lower queue position until the one at the top is the desired one, then remove it and reorder the queue again as needed.

**Comment by o01eg** [comment]
Work with production queue uses `m_uuid`. Are those items have same uuid in queue?

**Comment by Oberlus** [comment]
> Work with production queue uses `m_uuid`. Are those items have same uuid in queue?

Probably not, since most of the times this bug does not happen. It seems to be related to save game, although I think one time it happened to me after leaving a game on background for several hours before continuing playing, without reload of a save in between.

**Comment by geoffthemedio** [comment]
> Work with production queue uses `m_uuid`. Are those items have same uuid in queue?

Yes; the queue in the example save contains:
````
ProductionQueue::Element (ProductionItem: BT_SHIP name: Scout id: 112) (1) x1  (remaining: 1)  uuid: edee413e-6f1b-410c-bd03-513841095fba
ProductionQueue::Element (ProductionItem: BT_SHIP name: Outpost Ship id: 56) (1) x1  (remaining: 1)  uuid: b6631e16-94bb-4cb6-9c98-71c24c85c1d5
ProductionQueue::Element (ProductionItem: BT_SHIP name: Outpost Ship id: 56) (1) x1  (remaining: 1)  uuid: b6631e16-94bb-4cb6-9c98-71c24c85c1d5
ProductionQueue::Element (ProductionItem: BT_BUILDING name: BLD_SHIPYARD_BASE) (1) x1  (remaining: 1)  uuid: aae3a706-1f89-403b-b480-f871f98209e3
````

The 2nd and 3rd items have the same UUID, which is why it removes the second when ordered to remove the 3rd; it finds the item to be removed by UUID.

I don't know why the UUIDs are duplicated. As far as I can tell, the order to duplicate or split an item should give it a new unique ID, and this seems to work in my tests.... though possibly I saw this occur once?

Just duplicating (via right-click) an item, saving the game, then reloading, doesn't seem to cause it.

**Comment by o01eg** [comment]
@geoffthemedio What if enforce check if items have unique UUID before inserting them into the queue? Then it will be possible to find how it happened.

**Comment by geoffthemedio** [comment]
That can work, but is the problem that stuff is being inserted twice unintentionally, or that something is being inserted as intend but with the wrong UUID after reloading? If the latter, then it will just be a different bug, not a real fix.

**Comment by Oberlus** [comment]
> is the problem that stuff is being inserted twice unintentionally, or that something is being inserted as intend but with the wrong UUID after reloading? If the latter, then it will just be a different bug, not a real fix.

The problem is that the uuid becomes cloned after reloading (as if same models do not load the right uuid and copy the one from the first model in the queue).
Upon insertion in the queue uuid is not duplicated (AFAIKT from queue manipulation), and you can add and remove what you want without trouble.

**Comment by geoffthemedio** [comment]
> The problem is that the uuid becomes cloned after reloading (as if same models do not load the right uuid and copy the one from the first model in the queue).

What does "the uuid becomes cloned" mean?

Does it duplicate an order, so that two orders are executed with the same newly-generated UUID for a new queue item?

Or does it execute a single order twice, thus trying to add items with the same newly-generated UUID to the queue?

Or does it set the wrong UUID, which duplicates an existing queue item's UUID, in a single new order so that when it executes once, it tries to add something with an already-used UUID to the queue?

> Upon insertion in the queue uuid is not duplicated (AFAIKT from queue manipulation), and you can add and remove what you want without trouble.

Not sure what this means. What is "the queue uuid"?

**Comment by Oberlus** [comment]
@geoffthemedio, I'll try to explain myself with an example, hopefully complete:

Start game, add stuff to queue (for example 10 outpost ships, not important for this example). Add one frigate to queue (call this one batch A), add another frigate (batch B). Change number of ships, repetitions or order of batches A and B, it works just fine. Presumably, each batch has a different uuid. I don't really know what is an uuid, I hope I'm using it correctly here.
Play several turns, batches A and B are not completed yet. You can still do whatever you want with them as expected (again, presumably uuid are different for A and B, no bug).
Save game, load it, issue arises: that is, you no longer can treat batches A and B as expected, as described in OP. Presumably they (the two batches of frigate ships) got the same uuid.
I don't know how or why.

If we had no more than one batch for the same ship design (say one for outpost ships, one for frigates, one for colony ships, etc.) issue will not arise. Issue only happens when there are more than one batch with the same ship design. Probably, not confirmed, in the same planet.

**Comment by geoffthemedio** [comment]
It seems more likely that any inconsistency or problem with queue uuids would happen when issuing orders, particularly if saving after issuing orders on the same turn, then resuming the turn from a loaded file. Have you observed the issue appearing between turns when you didn't duplicate, split, or add something to the queue that turn?

I can't replicate the issue using the steps you describe, but also didn't get any error messages in the logs with #3081 applied, which might have indicated when / how it happens. I have had relevent looking errors in the logs when saving after issuing relevant queue orders and then reloading.

**Comment by geoffthemedio** [comment]
@Oberlus can you tell if https://github.com/freeorion/freeorion/pull/3081 helps?

**Comment by Oberlus** [comment]
> @Oberlus can you tell if #3081 helps?

I've played two games up to turn 150, one with release branch without the fix, one with master with #3081. The issue didn't happen in either one. With master and #3081 I tried to replicate it several times, reloading, and the words "repeated/Repeated" didn't appear once in the logs.

**Comment by geoffthemedio** [comment]
So you can't reproduce the issue with or without the patch, and the patch caused no obvious problems?

**Comment by Oberlus** [comment]
> So you can't reproduce the issue with or without the patch, and the patch caused no obvious problems?

Exactly.

**Comment by Oberlus** [comment]
This keeps happening in 2020-07-01.b4f9ea1 (weekly test build). I found it in two games, late in game (turn 150+).
#3081 isn't in that build.

**Comment by Oberlus** [comment]
I haven't bumped into this problem for a long time. Hopefully it was solved.
Should I close this issue?

**Comment by geoffthemedio** [comment]
> Hopefully it was solved.

I suspect not.

**Comment by Oberlus** [comment]
Update: no occurrences of this bug since 2020. Maybe it was solved. I won't close this for now, but @geoffthemedio , feel free to close it if you think otherwise.

**Comment by geoffthemedio** [comment]
if not reproducible in 2 years then I'll close until it is
