### ISSUE TITLE
Enemy scout arrives to a location and disappears, plus missing arrival and incoming SitReps

### ISSUE THREAD

**Issue by Oberlus** [freeorion/freeorion#3043]
Bug Report
==========

Environment
-----------
* **FreeOrion Version**: v0.4.10+ build 2020-06-14 9af9a91 CMake
* **Operating System**: Ubuntu 18.04
* **Fetched as** 
  * Compiled from source

Description
-----------
Enemy scout without stealth parts gets to a system under detection range and disappears:
![Scout arrives and disappears](https://user-images.githubusercontent.com/28650914/84592852-d7d28d80-ae48-11ea-8948-9b7a9bd8a228.png)

Next turn it appears again:
![Scout re-appears](https://user-images.githubusercontent.com/28650914/84592841-c7221780-ae48-11ea-9696-14d852cc47a5.png)
Also notice there is no "incoming enemy" SitRep.

When it arrives to Perelandra, it does not disappear.

[logs_scout_arrives_disappears.zip](https://github.com/freeorion/freeorion/files/4776366/logs_scout_arrives_disappears.zip)
[save_scout_arrives_disappears_turn_before.zip](https://github.com/freeorion/freeorion/files/4776368/save_scout_arrives_disappears_turn_before.zip)

I attach save game for turn 41 (one before scout arrives to deep space and disappears, when it was visible at Uxmai).

Maybe it has something to do with the Continuous Scanning policy? It is in use in this game.
Or with the fact that Active Radar is completed on turn 42? But that Deep Space spot is under detection range in turn 41, or at least that's what the player infers from the detection areas drawn in the screen (check out save).

Also, the scout arrives Uxmai in turn 41 (it wasn't there in turn 40) but there is no arrival SitRep.

**Comment by Oberlus** [comment]
I wasn't aware that Nebulae (clouds of hydrogen that coalesce to form a new system) do have a -20 speed and +20 stealth effect. Assuming Uxmai system was out of the Nebula and the Deep Space spot was inside, that would explain this issue.

**Comment by Vezzra** [comment]
So can we close this as invalid?

**Comment by Oberlus** [comment]
Yes, I've played more on this game and another one and the behaviour seems consistent.

**Comment by l29ah** [comment]
It's strange it didn't leave a sensor ghost if the arrival was detected as the sitrep suggests.
