### ISSUE TITLE
Wrong Government Policies window dimensions and justification

### ISSUE THREAD

**Issue by Oberlus** [freeorion/freeorion#3045]
Bug Report
==========

Environment
-----------
* **FreeOrion Version**: 9af9a91
* **Operating System**: Ubuntu 18.04 
* **Fetched as** 
  * Compiled from source

Description
-----------
1. The fixed space on top and left of the row of policy slots does not allow to dimension the window small and a lot of space is wasted:
![GovPolicyWindow](https://user-images.githubusercontent.com/28650914/84603749-112eeb80-ae91-11ea-83ed-50e87edc88e5.png)

2. The distribution of space between the available policies and the available slots is biased towards the slots:
![GovPolicyWindow2](https://user-images.githubusercontent.com/28650914/84603891-556ebb80-ae92-11ea-8e99-d48279d5fcc1.png)

Expected Result
---------------
1. Either make the slots justified to top and left without the extra space or centered to the window without the fixed empty  space.
2. Either make the space for available policies and slots proportional to the needed space for each one, or set a minimum space for each part equal to the size of a policy/slot.

**Comment by geoffthemedio** [comment]
This a layout / design issue, not a bug.

**Comment by Oberlus** [comment]
> This a layout / design issue, not a bug.

I agree.
For future layout issues, should I use "Feature request" instead of "Report bug" then?

**Comment by Oberlus** [comment]
The layout of the policies and slots was improved since this issue was open. It ain't perfect yet but this feature request can be closed.
