### ISSUE TITLE
Sly ships don't get Gas Giant extra refuelling

### ISSUE THREAD

**Issue by Oberlus** [freeorion/freeorion#3086]
Bug Report
==========

Environment
-----------
* **FreeOrion Version**: 2020-06-23.a2f5c56
  * Compiled from source

Description
-----------
Sly ships don't get Gas Giant extra refuelling.

Steps to reproduce
------------------
* Start a game as Sly.
* Wander around with a scout and let it spent at least 1 fuel, stop in a system without gas giant and check out refuel per turn: it is +0.1.
* Move the scout to a system with a gas giant, stop in there and check out refuel per turn: it is +0.1.

**Comment by geoffthemedio** [comment]
In release branch or just master?

**Comment by Oberlus** [comment]
> In release branch or just master?

In both. The initial report was for release branch. There, it seemed the Sly GG refuelling didn't work, and the normal refueling of +0.1 per turn worked fine. Now I have to check that again (Edit: confirmed, the behaviour is the same in both branches), because in master branch it seems the problem is that Sly GG refuelling is working inverted:

Sly scout in a system with GGs gets +0.1 per turn:
![WithGG_0 1](https://user-images.githubusercontent.com/28650914/86226575-26439400-bb8c-11ea-9ca3-9d69d8028c0e.png)

Sly scout in a system without GGs gets +0.2 per turn:
![WithoutGG_0 2](https://user-images.githubusercontent.com/28650914/86226603-2e9bcf00-bb8c-11ea-8d5e-e6d0d8cee4b6.png)

It doesn't matter if there are or not non-GG planets.

**Comment by geoffthemedio** [comment]
Does this affect v0.4.10?

**Comment by Oberlus** [comment]
> Does this affect v0.4.10?

Yes

**Comment by geoffthemedio** [comment]
Sorry; just noticed I already asked that...
