### ISSUE TITLE
Messages window does not honour font size settings

### ISSUE THREAD

**Issue by Oberlus** [freeorion/freeorion#3091]
Bug Report
==========

Environment
-----------
* **FreeOrion Version**: v0.4.10, release branch b4f9ea1, master branch 4cc3348

Description
-----------
Messages window does not respect the font size settings from user.
The tittle "Messages" does respect font size, but not the content of the window (chat, errors, etc.).
This is annoying for small screens.

Probable related issue: https://github.com/freeorion/freeorion/issues/2842

Steps to reproduce
------------------
Start a game.
Reduce both font sizes in Options to something small like 8.
Check out how most windows respect the change (at least after resizing the window to force update it) but Messages window keeps its big font size.

**Comment by geoffthemedio** [comment]
You probably need to restart the program to see the change... but it does seem to work for me.

**Comment by Oberlus** [comment]
> You probably need to restart the program to see the change... but it does seem to work for me.

You're right, after restarting the program the window does honour user settings.
Should I close this (as invalid) or change the tittle to "... until client is restarted"?
Other windows update their settings without needing to restart the client.

**Comment by geoffthemedio** [comment]
Some things update immediately. Some update after being closed and reopopened. Some require a program restart... It's just a quirk of how things are set up... Missing feature arguably... kinda buggy. But nothing particularly important about the message window...
