### ISSUE TITLE
Segfault Linux in Objects list

### ISSUE THREAD

**Issue by indywatch** [freeorion/freeorion#3104]
Hi, I don't have many details right now (will try and add more soon) but I am segfaulting with new code on a homebuilt install when I try and sort items in the objects list. The whole game just crashes.

**Comment by indywatch** [comment]
$ ./freeorion --version
FreeOrionCH v0.4.10+ [build 2020-07-04.ca61c04] CMake




$ ./freeorion
[2020-07-14 18:38:13.497224] [0x00007facb6459900] [info]    OptionsDB::Add<>() : Option video.fullscreen.width was given the value "1366" from the command line or a config file but that value couldn't be converted to the correct type, using default value instead.
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
[2020-07-14 18:39:13.513111] [0x00007fe39f2cab80] [info]    ServerApp::~ServerApp
[2020-07-14 18:39:13.513171] [0x00007fe39f2cab80] [info]    Server exited cleanly.
[2020-07-14 18:39:13.531177] [0x00007fe39f2cab80] [info]    Cleaned up FreeOrion Python interface
Segmentation fault
aliasd@aitape:~/freeorion-project/freeorion
$ [2020-07-14 18:39:13.544664] [0x00007fe39f2cab80] [info]    Reset id allocators with highest object id = -1 and highest design id = 69424
$ ./




[freeoriond.log](https://github.com/freeorion/freeorion/files/4917734/freeoriond.log)
[freeorion.log](https://github.com/freeorion/freeorion/files/4917735/freeorion.log)

**Comment by geoffthemedio** [comment]
Maybe fixed by https://github.com/freeorion/freeorion/commit/091ca2bac023b9a9da64ad3c36c1430e67d7ca81 ?

**Comment by Vezzra** [comment]
As #3113, which very much looks like a duplicate of this issue here, has been closed as resolved, I guess it's safe to assume that this issue can be closed too...?

Of course, getting a confirmation from @indywatch would be good, but I don't think we need to wait for that. We can always reopen after all.

Unless this issue is somehow different from #3113?

**Comment by indywatch** [comment]
> Of course, getting a confirmation from @indywatch would be good, but I don't think we need to wait for that. We can always reopen after all.
> 

I agree that the much better bug report probably duplicated my issue. I can go ahead and comment here if I encounter it again on a fresh build, whenever that might be.
