### ISSUE TITLE
segfault when sorting planets

### ISSUE THREAD

**Issue by ghost** [freeorion/freeorion#3113]
Bug Report
==========

Environment
-----------

FreeOrion built from source: 3e68a6b814310e189ec9a843c4ed5448c19b4ee3
Debian 10 buster, amd64
Compiler: clang
C++: libstdc++

Description
-----------

Segfault.
Stack trace
[gdb.txt](https://github.com/freeorion/freeorion/files/4957268/gdb.txt)
 attached.

Steps to reproduce
------------------

* in any game: click on "object" icon
* when you see more than 1 object, click on any header field
* segfault.

**Comment by geoffthemedio** [comment]
Maybe fixed by https://github.com/freeorion/freeorion/commit/091ca2bac023b9a9da64ad3c36c1430e67d7ca81 ?

**Comment by ghost** [comment]
Yes.

**Comment by geoffthemedio** [comment]
Appears to not affect v0.4.10, probably caused by https://github.com/freeorion/freeorion/commit/06293f5879c698ba4ec659ee5afadb280ca7663c#diff-187a00b9133be855a6c4ae4f23caa1e1R2037-R2039
