### ISSUE TITLE
Wrong pilot trait weapon damage scaling

### ISSUE THREAD

**Issue by agrrr3** [freeorion/freeorion#3126]
It seems the pilot trait effect does not damage-scaled for main line weapons.

[forums](https://www.freeorion.org/forum/viewtopic.php?f=28&t=11741&p=102792#p102792)

Also affects 0.4.10, as we test the scaling in the current slow game sever i would like to have this fix in 0.4.10.1 too

**Comment by agrrr3** [comment]
stringtables and AI missing

**Comment by agrrr3** [comment]
stringtables dont seem to need to be adjusted. SHP_FIGHTERS_1_DESC already contain the 6-scaled values
AI does not apply scaling to pilot skill yet, so needs adjustment

**Comment by agrrr3** [comment]
@o01eg should this go into the slow game?
 the implementation is ready - if so it should go there as fast as possible (e.g. before our forces clash). could also have a look at the PR #3127

**Comment by o01eg** [comment]
It will break checksum calculation so I cann't apply it on the server without some release.

**Comment by agrrr3** [comment]
That's why I thought of asking vezzra to include it in 0.4.10.1 .. we would
immediately playtest the change
