### ISSUE TITLE
Loading of save-games broken

### ISSUE THREAD

**Issue by agrrr3** [freeorion/freeorion#3131]
Loading a savegame with a freeorion build on 7d37633 (master) does not work:

```[error] python : FreeOrionAI.py:195 : This client has no empire. Doing nothing to handle chat message.```

edit: before I thought this was about eliminated empires, but simple loading on master triggers this bug

**Comment by geoffthemedio** [comment]
would it affect v0.4.10?

**Comment by agrrr3** [comment]
Probably(?)

**Comment by agrrr3** [comment]
How do i enable super-testers?

**Comment by geoffthemedio** [comment]
> How do i enable super-testers?

checkbox in content tab when setting up a new single player game

**Comment by rgarbacz** [comment]
For me it does not load a saved game at all, neither single nor multiplayer, after load the universe is empty from civilizations:

server : ServerApp.cpp:98 : v0.4.10+ [build 2020-07-28.7d37633] CMake
{0x00007f290509a780} [error] server : SaveLoad.cpp:479 : LoadGame(...) failed!  Error: XML start/end tag mismatch - m_current_value

**Comment by agrrr3** [comment]
> For me it does not load a saved game at all, neither single nor multiplayer, after load the universe is empty from civilizations:
> 
> server : ServerApp.cpp:98 : v0.4.10+ [build 2020-07-28.7d37633] CMake
> {0x00007f290509a780} [error] server : SaveLoad.cpp:479 : LoadGame(...) failed! Error: XML start/end tag mismatch - m_current_value

@rgarbacz that is a completely different issue. open up a new issue (as bug) and state the necessary information there (which version, which operating system, (how) did you build/download...)

**Comment by agrrr3** [comment]
I tried to recreate the error in 0.4.10 - let 6AI play against each others and around turn 930 finally two got eliminated and they seem to have ships left. Reloading the save file worked without the hinch. So either some other situation must also happen or it is possible that this only happens in master

**Comment by Cjkjvfnby** [comment]
I think it is not about the game saves, it is about something else.  

The message you referenced is from the  https://github.com/freeorion/freeorion/blob/master/default/python/AI/FreeOrionAI.py#L193

Probably we have two issues: 
Dead AI talking (begging for peace?). I don't see any code in AI for that. Can you test and send a message to AI yourself?
And for the reproduced case you can add `print(message)`

The second bug maybe that C++ binding return None instead of eliminated empire.

**Comment by agrrr3** [comment]
AFAIUIT it is not dead AI talking to somebody else but the opposite - AI trying to talk to empire-less AI. The question is why sending the message is looping (is it retrying? or working down a queue?). I can try and send a message in the master based save.

**Comment by pidlug** [comment]
Sorry for jumping in but I just tried playing git version (from Arch AUR) and I'm not able to open any saved game. The message "FreeOrionAI.py:195 : This client has no empire. Doing nothing to handle chat message." always shows after loading. I tried to save the game just after one turn and it does not load either.

**Comment by agrrr3** [comment]
On 0.4.10 I the empires with no planets or ships respond as usual to messages, so i guess those are not eliminated

**Comment by agrrr3** [comment]
pidlug is right, this has nothing to do with empires being eliminated it was simply loading savegames on master (compiled with 7d37633fd3989b16b9384fa3c08619e7e8a1d8eb)

i did not get the message rgarbacz got though

**Comment by Cjkjvfnby** [comment]
> AFAIUIT it is not dead AI talking to somebody else but the opposite - AI trying to talk to empire-less AI. The question is why sending the message is looping (is it retrying? or working down a queue?)

I don't understand how AI sends a diplomatic message.  It can respond to a diplomatic messages with a diplomatic messages, but I don't get how the first step is initiated. 

Possible scenario: 
Turn X:      AI_A sends a peace proposal to AI_B. 
Turn X+1:  AI_A is dead, AI_B gets diplomatic messages with peace proposal and send a response.
Turn X+2: AI_A gets the response for the diplomatic message and crashes.

Can someone with C++ background check if diplomatic message queues are cleaned up after AI is dead?  And what does happen if message is not delivered?

**Comment by agrrr3** [comment]
@Cjkjvfnby this is probably not about diplomatic messages at all

**Comment by Cjkjvfnby** [comment]
> @Cjkjvfnby this is probably not about diplomatic messages at all

AI crashes because of some message is sent.  Probably it is diplomatic. This is an end of the chain, the real reason is somewhere in C++ code.


> (compiled with 7d37633)

Do you have time to git bisect?   Or can you just provide commit boundaries?

**Comment by agrrr3** [comment]
> > @Cjkjvfnby this is probably not about diplomatic messages at all
> 
> AI crashes because of some message is sent. Probably it is diplomatic. This is an end of the chain, the real reason is somewhere in C++ code.
> 
> > (compiled with [7d37633](https://github.com/freeorion/freeorion/commit/7d37633fd3989b16b9384fa3c08619e7e8a1d8eb))
> 
> Do you have time to git bisect? Or can you just provide commit boundaries?

Dont think I can bisect for the next two weeks. 

The code you dug up showed that the AI after loading does not have an empire.
@adrianbroher There were changes to serialization recently, so it could be related to that. Maybe also there were changes to AI bindings (?)

**Comment by geoffthemedio** [comment]
I have no similar issue on Windows.

If you think it's serialization related, try reverting those changes?

**Comment by Cjkjvfnby** [comment]
I have installed windows build 2020-08-04 and load save games with date 2020-04-16 and turn 2. (I don't know which build I have used to create it) and got this error.   

After that error both loading or starting new game does not work (black screen).  Need to restart the game.

Savegame created by this build loads without errors.

**Comment by SpikyCaterpillar** [comment]
After much compiling, it appears to me that the bug was introduced in fcf7a53a3a9dd119db45d2e2af6cbb049aef5bf0 (Make serialization of Meter less intrusive). A save made on the first turn with 2be3b4b288e8ce998cfe3ff7f09f7b5ab70f361 loads properly; a save made on the first turn with fcf7a doesn't.

Also, bugged builds seem to load saves made in pre-bug versions of Freeorion okay (though re-saving them creates a save that won't load.) I'm using Debian (64 bit).

**Comment by geoffthemedio** [comment]
@adrianbroher can you investigate?

**Comment by SpikyCaterpillar** [comment]
If a bugged save will help, here are a pair of saves - meter.sav won't load on my machine, beforeintrusion.sav will.
[saves.zip](https://github.com/freeorion/freeorion/files/5035729/saves.zip)

**Comment by Oberlus** [comment]
I've tested https://github.com/freeorion/freeorion/commit/7c0f83fc545eb7b3e2214d94e4517728a8ebb03a and it doesn't work, save files load to an empty galaxy with errors.

**Comment by geoffthemedio** [comment]
> 
> 
> I've tested [7c0f83f](https://github.com/freeorion/freeorion/commit/7c0f83fc545eb7b3e2214d94e4517728a8ebb03a) and it doesn't work, save files load to an empty galaxy with errors.

Need to be more specific. Saves made in what version won't load with what other version?

Are saves made after fcf7a53 broken even after reverting it in 7c0f83f, or can saves made after 7c0f83f also not be loaded?

...

Actually, I think I reverted the wrong commit...  Tried again with https://github.com/freeorion/freeorion/commit/4cc5d4c133a8cc8491dcec181f933ea37a7b5d50

**Comment by Oberlus** [comment]
> Need to be more specific.

Yes: compile 7c0f83f, quickstart a game, advance until turn 3, load auto save from turn 2 -> empty galaxy with errors. 

> Actually, I think I reverted the wrong commit... Tried again with [4cc5d4c](https://github.com/freeorion/freeorion/commit/4cc5d4c133a8cc8491dcec181f933ea37a7b5d50)

Thank you, that one works well:
- For save files made with itself, it loads game correctly.
- For save files made with master (i.e. without the revert), there are errors and galaxy is empty (so the problem in master is about what gets saved and not about how it is loaded).
