### ISSUE TITLE
Splash screen won't cover whole screen anymore

### ISSUE THREAD

**Issue by Oberlus** [freeorion/freeorion#3134]
Bug Report
==========

Environment
-----------
* **FreeOrion Version**: 0.4.10+ 0b407ff
  * Compiled from source
* **Operating System**: Ubuntu 18.04
* **Graphic card used**: GeForce 860M

Description
-----------
With new test version, maybe since the addition of the optional pranky splash screen, splash screen is not rendered to cover the whole screen, in fact it seems to be narrowed horizontally:
![splash_screen](https://user-images.githubusercontent.com/28650914/89759531-aeea1400-daea-11ea-8df6-ea9fa7cec368.png)

Expected Result
---------------
As in v0.4.10 Release (and previous versions):
![splash_screen_release_0 4 10](https://user-images.githubusercontent.com/28650914/89760380-8bc06400-daec-11ea-987b-5cf0eb0db555.png)

**Comment by geoffthemedio** [comment]
I switched to proportional stretch scaling for the texture, which doesn't enlarge it. That's the actual size of the image.

**Comment by Oberlus** [comment]
Then it would be nice to have a larger version of the image. Not a pressing matter indeed, I won't open a feature request for that for now.

**Comment by geoffthemedio** [comment]
Or a new one... or several similarly-themed ones... this has been in place for over 10 years now probably...
