### ISSUE TITLE
Forum broken?

### ISSUE THREAD

**Issue by Vezzra** [freeorion/freeorion#3138]
Do only I experience this, or is our forum kind of broken?

There seems to be something wrong with the layout, things looks somehow different. When I log in, the widgets which used to be in the top right corner are squashed to the left.

I can't post anything, when I try to make a new post, the edit box for the text isn't there.

The last post is from yesterday, Aug 10th, 5:22pm UTC, so it looks like it's not just me...

What's going on?

**Comment by geoffthemedio** [comment]
Not sure... I don't see any error messages.

Maybe the host updated PHP and broke something?

**Comment by geoffthemedio** [comment]
> Maybe the host updated PHP and broke something?

Plausibly it's this. The Admin Control Panel reports PHP version 7.4.6 but [this page](https://www.phpbb.com/community/viewtopic.php?f=556&t=2376856) about phpBB 3.2 says
````
What versions of PHP are supported? #
>= PHP 5.4.7, < PHP 7.3
````

So we probably need to update the forum software version.

I've just run a website database backup.

**Comment by geoffthemedio** [comment]
Attempting to do the update to phpBB 3.3.1 ...

**Comment by geoffthemedio** [comment]
Well... I (think I) followed the instructions, and it seemingly ran successfully, but things are not working correctly.

All page layout is non-functional and it won't let me stay logged in after clicking to another page.

**Comment by geoffthemedio** [comment]
OK, substantial progress... may be functional now?

**Comment by geoffthemedio** [comment]
I've edited the CSS for the forum logo, but it's not updating for me. Might take a while to update, despite multiple purging of the cache...

**Comment by Vezzra** [comment]
@geoffthemedio, thanks for taking care of this so quickly - and for sacrificing your entire evening for it. From what I can see, you apparently have been working on it for at least 3 hours, until midnight.

As far as the logo is concerned, at least for me it works just fine. So I guess it's just the taking some time to update thing, which means you should be able to see the FO logo now too...

Closing this as resolved.
