### ISSUE TITLE
v0.4.10 planetary shields set to lvl 1 if sm arrives

### ISSUE THREAD

**Issue by drkosy** [freeorion/freeorion#3139]
Bugreport
--------------------------
I encounter an issue with space monsters and planetary shields. If a space monster arrives at a system of human player the planetary shield is set to level one, even if level 3 is already invented. That always happening after combat. The shield is set to 41 at the beginning of the new turn even if the monster did low damage. If it kills planetary shields this does happen correctly.
Can't proof it for AI fleets because the are to far away to attack my systems.

Environment
-----------
Playing Version 0.4.10 self compiled from source on fedora linux 32 (kernel 5.7.14 installed)

Description
-----------
Added screenshots bevor the kraken arrives and after arrival. On the second screenshot you see the combat log and shields are down to 41.
Added save game of turn 215 (next turn juggernaut arrives) if you hover over planetary shields in system "Targ alpha" the planet has 191 shield. After arrival the shield is at 41. If you hover over planetary shields it's at level 1. That is the case as long as the juggernaut is in the system. That is as well the case for planetary shield level 2 is invented. Maybe even for level 5 but no proof there...
Unfortunally the savegame dosen't fit with the sceenshots but that isn't availible anymore because it was just an autosave.
[Planetary-Shield-Bug1.zip](https://github.com/freeorion/freeorion/files/5068488/Planetary-Shield-Bug1.zip) -> file contains savegame + log files
![Planetary-Shield-Bug1](https://user-images.githubusercontent.com/69628123/90124648-0a253c00-dd61-11ea-80ff-6af9d2b44a3e.jpg) -> Screenshot before kraken arrives
![Planetary-Shield-Bug2](https://user-images.githubusercontent.com/69628123/90124679-17dac180-dd61-11ea-9683-a746a907bb22.jpg) -> Screenshot after arrival with combat log

Expected Result
---------------
I expect that planetary shields are calculated and treated correctly, even if a space monster is present.

Steps to reproduce
------------------
Just wait till a space monster arrives in a system of the human player.

**Comment by geoffthemedio** [comment]
I'm not sure why, but there are conditions scripted to disable effects from barrier shield techs when combats happen in a system. I'd have probably just disabled the shield meter recovery effect, not the max shield meter effect. Maybe try with this change:
````
 default/scripting/techs/defense/BarrierShield.focs.txt | 6 +++---
 1 file changed, 3 insertions(+), 3 deletions(-)

diff --git a/default/scripting/techs/defense/BarrierShield.focs.txt b/default/scripting/techs/defense/BarrierShield.focs.txt
index 3f52e72ac..20c80ff9e 100644
--- a/default/scripting/techs/defense/BarrierShield.focs.txt
+++ b/default/scripting/techs/defense/BarrierShield.focs.txt
@@ -43,7 +43,7 @@ Tech
             scope = And [
                 Planet
                 OwnedBy empire = Source.Owner
-                (LocalCandidate.LastTurnAttackedByShip < CurrentTurn - 1)
+                //(LocalCandidate.LastTurnAttackedByShip < CurrentTurn - 1)
             ]
             priority = [[DEFAULT_PRIORITY]]
             effects = SetMaxShield value = Value + ( 60 * [[PLANET_SHIELD_FACTOR]] ) accountinglabel = "DEF_PLAN_BARRIER_SHLD_2"
@@ -74,7 +74,7 @@ Tech
             scope = And [
                 Planet
                 OwnedBy empire = Source.Owner
-                (LocalCandidate.LastTurnAttackedByShip < CurrentTurn - 1)
+                //(LocalCandidate.LastTurnAttackedByShip < CurrentTurn - 1)
             ]
             priority = [[DEFAULT_PRIORITY]]
             effects = SetMaxShield value = Value + ( 90 * [[PLANET_SHIELD_FACTOR]] ) accountinglabel = "DEF_PLAN_BARRIER_SHLD_3"
@@ -105,7 +105,7 @@ Tech
             scope = And [
                 Planet
                 OwnedBy empire = Source.Owner
-                (LocalCandidate.LastTurnAttackedByShip < CurrentTurn - 1)
+                //(LocalCandidate.LastTurnAttackedByShip < CurrentTurn - 1)
             ]
             priority = [[DEFAULT_PRIORITY]]
             effects = SetMaxShield value = Value + ( 150 * [[PLANET_SHIELD_FACTOR]] ) accountinglabel = "DEF_PLAN_BARRIER_SHLD_4"
````

@Oberlus @o01eg @Cjkjvfnby @l29ah Any objections to making this change?

**Comment by Oberlus** [comment]
No objections.

**Comment by agrrr3** [comment]
Was introduced in cde9df5ab21ebd3a570d2fb4e94cd7cffaf2f6d0

"Moved shield growth effects into separate effectsgroups with conditions requiring the planet to have not been attacked in the previous turn."

This is simply a regression. The fix looks good.
