### ISSUE TITLE
[AI] Improve TechList technology enque

### ISSUE THREAD

**Issue by Cjkjvfnby** [freeorion/freeorion#3143]
I do an investigation for the AI TechGroups. Tech group might riquire adjustments as we discussed in the https://github.com/freeorion/freeorion/pull/3117.

This is important part of the AI but it is not very transparent how tech are added.

I create this ticket to collect a list of notices I have about it.  It may take some time, and I want to save progress in a persistent place.

**Comment by Cjkjvfnby** [comment]
This function completely breaks an order of the execution, so SHP_WEAPON_1_3 can be added before the SHP_WEAPON_1_2.

```
    def _add_remaining(self):
        """Add all remaining techs in the tech group to self._tech_queue if not already contained."""
        all_needed_techs = set(self.economy + self.weapon + self.armor
                               + self.misc + self.defense + self.hull)
        remaining_techs = list(all_needed_techs - set(self._tech_queue))
        self._tech_queue.extend(remaining_techs)

```

The solution is just rewrite it to preserve order.   This will change AI behavior.

**Comment by Cjkjvfnby** [comment]
Requirements are not listed in the code.  Therefore TechGroup does not list all tech that should be added. 

For example TechGroup1
```
List in TechGroup                       Tech list with respect of requirements
--------------------                       --------------------------------------------
LRN_PHYS_BRAIN                          LRN_PHYS_BRAIN
GRO_PLANET_ECOL                         GRO_PLANET_ECOL
LRN_ALGO_ELEGANCE                       LRN_ALGO_ELEGANCE
GRO_SUBTER_HAB                          GRO_SUBTER_HAB
LRN_NASCENT_AI                          LRN_NASCENT_AI
                                        SHP_ROOT_AGGRESSION
SHP_WEAPON_ARC_DISRUPTOR_1              SHP_WEAPON_ARC_DISRUPTOR_1
                                        DEF_ROOT_DEFENSE
DEF_GARRISON_1                          DEF_GARRISON_1
DEF_DEFENSE_NET_1                       DEF_DEFENSE_NET_1
SHP_FIGHTERS_1                          SHP_FIGHTERS_1
                                        SHP_WEAPON_1_2
SHP_WEAPON_1_3                          SHP_WEAPON_1_3
PRO_ROBOTIC_PROD                        PRO_ROBOTIC_PROD
SHP_WEAPON_1_2                          SHP_WEAPON_1_2
SHP_WEAPON_1_4                          SHP_WEAPON_1_4
SHP_MIL_ROBO_CONT                       SHP_MIL_ROBO_CONT
                                        SHP_DOMESTIC_MONSTER
SHP_ORG_HULL                            SHP_ORG_HULL
```

**Comment by agrrr3** [comment]
> This function completely breaks an order of the execution, so SHP_WEAPON_1_3 can be added before the SHP_WEAPON_1_2.

AFAIK it is not a problem if SHP_WEAPON_1_3 is added before SHP_WEAPON_1_2 . If you add SHP_WEAPON_1_3, all prerequisites are automatically added

see ResearchAI.py#675
```
missing_prereqs = [preReq for preReq in this_tech.recursivePrerequisites(empire_id) if preReq not in tech_base]
```

And _add_remaining techs are added after all manually added techs, so this function cant change the order of research in that group.

**Comment by Grummel7** [comment]
ResearchAI is on my list of things I like to redo, but I don't think it currently has any serious issues that must be fixed for release 0.5.

I suggest closing this issue.

**Comment by Vezzra** [comment]
@Grummel7, see ticket description. @Cjkjvfnby said there:

> I create this ticket to collect a list of notices I have about it. It may take some time, and I want to save progress in a persistent place.

Sounds to me like this issue is more of a place to collect and store infos for that particular topic. As long as @Cjkjvfnby thinks he still needs it... @Cjkjvfnby, any comments? Do you still need this issue, or can it be closed?

**Comment by Cjkjvfnby** [comment]
I think this could be closed.
