### ISSUE TITLE
Arc disruptor art is lower quality (resolution) than the rest of ship parts

### ISSUE THREAD

**Issue by Oberlus** [freeorion/freeorion#3144]
Bug Report
==========

Environment
-----------
* **FreeOrion Version**: v0.4.9, v0.4.10
* **Operating System**: Windows 7 and Windows 8.1, maybe other Windows. Linux does not show the issue.

Description
-----------
![arc_low_quality](https://user-images.githubusercontent.com/28650914/90765145-bc24b100-e2e9-11ea-8866-4c009fb5da56.png)

**Comment by Oberlus** [comment]
> It seems like there's something weird with the encoding / compression of the texture. I loaded it in Paint.net and resaved, and it seems to help... Try replacing with this:
> ![pulse-laser](https://user-images.githubusercontent.com/11386908/90928079-815c6f00-e3f6-11ea-97d6-8113b43324d9.png)

The image you provide is displayed perfectly.
Now we need versions for pulse-laser-1.png, pulse-laser-2.png and pulse-laser-3.png

I edited OP because I was wrong: the issue affects only Windows, not Linux.

**Comment by geoffthemedio** [comment]
Can you try loading and resaving them in the image editor of your preference to see if it works, and if so, submit a pull request?

**Comment by geoffthemedio** [comment]
does this affect v0.4.10?

**Comment by Oberlus** [comment]
> does this affect v0.4.10?

Yes, this was tested with v0.4.10, if affects all versions since the introduction of the Arc Disruptor.
Fix was also tested with v0.4.10, in Windows.

**Comment by Oberlus** [comment]
This isn't solved in v0.4.10.1. Reopen.

**Comment by geoffthemedio** [comment]
Are you sue you're using the new version's files? Maybe the default directory still points to the old version...? The [relevant commit](https://github.com/freeorion/freeorion/commit/734264eaf8422ba582bd31bee8cc54326ee9c1f8) appears to be in the [v0.4.10 commit log](https://github.com/freeorion/freeorion/commits/release-v0.4.10)...

**Comment by Oberlus** [comment]
I only have one default folder. The art was fine until I updated to v0.4.10.1 (because I left the fixed art in the v0.4.10 folder after testing it for this issue).
The files in the folder:

![pulse-laser-1](https://user-images.githubusercontent.com/28650914/93025541-0e15d980-f5ff-11ea-8c85-172b7553d982.png)
![pulse-laser-2](https://user-images.githubusercontent.com/28650914/93025536-0ce4ac80-f5ff-11ea-95ac-05c52d1fb76c.png)
![pulse-laser-3](https://user-images.githubusercontent.com/28650914/93025537-0d7d4300-f5ff-11ea-8d18-9ca02771ff28.png)
![pulse-laser](https://user-images.githubusercontent.com/28650914/93025538-0d7d4300-f5ff-11ea-9335-565e5aefe1b5.png)

I see them just fine with image viewer, but pixeled within FO. No idea what's the problem.

**Comment by geoffthemedio** [comment]
Are they the right updated files, but somehow showing up old-style, or are they somehow reverted to the old ones?

**Comment by Oberlus** [comment]
Their timestamp seem right, they seem the right files.
They are showing old-style.

**Comment by Oberlus** [comment]
I've uploaded the files to and online image edition tool (pixlr) and saved them again. After substituting the original file with the resaved one I see the right image quality in FO.
I guess I should make a new PR and hope that it will work this time.
