### ISSUE TITLE
Crash when clicking on sitrep's link to combat report (combat log)

### ISSUE THREAD

**Issue by Oberlus** [freeorion/freeorion#3153]
Bug Report
==========

Environment
-----------
* **FreeOrion Version**: v0.4.10+ 8119c36
* **Operating System**: Ubuntu 18.04
  * Compiled from source

Steps to reproduce
------------------
* Play a game until you get a combat sitrep.
* Click on the link to the combat report .
* Crash to desktop happens.

Attached a save file with a combat that happened on previous turn.

[freeoriond.log](https://github.com/freeorion/freeorion/files/5125208/freeoriond.log)
[freeorion.log](https://github.com/freeorion/freeorion/files/5125209/freeorion.log)
[FreeOrion_Oberlus_Abyss_0052_20200825_184815.zip](https://github.com/freeorion/freeorion/files/5125211/FreeOrion_Oberlus_Abyss_0052_20200825_184815.zip)

**Comment by geoffthemedio** [comment]
affects v0.4.10?

**Comment by Oberlus** [comment]
> 
> 
> affects v0.4.10?

No, tested. Only recent master version (didn't check when this began to happen, but I'd say I could check combat logs two weeks ago).

**Comment by geoffthemedio** [comment]
should be fixed by https://github.com/freeorion/freeorion/commit/738c2372244aa6eef41543296be321d25a9ccd44
