### ISSUE TITLE
Cannot obtain policy by research

### ISSUE THREAD

**Issue by Phatmented** [freeorion/freeorion#3156]
Bug Report
==========

Environment
-----------

* **FreeOrion Version**: 738c237
* **Operating System**: Arch based
* **Fetched as** 
  * Compiled from source

Description
-----------

Cannot obtain the policy racial purity by research.

Expected Result
---------------

Recieve the policy.

Steps to reproduce
------------------

* First step. Start a game
* Second step. Research Psychological Architecture tech
* Issue occurs. No racial purity policy is unlocked only is unlocked the balance policy

[freeorion.log](https://github.com/freeorion/freeorion/files/5141765/freeorion.log)
[freeoriond.log](https://github.com/freeorion/freeorion/files/5141767/freeoriond.log)

**Comment by geoffthemedio** [comment]
To adopt Racial Purity, you need to first adopt its prerequisite, Checkpoints.

https://github.com/freeorion/freeorion/blob/master/default/scripting/policies/RACIAL_PURITY.focs.txt#L7

**Comment by Phatmented** [comment]
The pedia didn't mention that prerrequisite

**Comment by Phatmented** [comment]
After enabling the policy of border checkpoints now i can enable the racial purity. This prerrequisite should be added to the pedia

**Comment by geoffthemedio** [comment]
> This prerrequisite should be added to the pedia

A lot of things should happen...

**Comment by Phatmented** [comment]
I have played the previous version and they have no policies at all, at least some basic info on how to to do stuff in the pedia is nice. I know is superfluous to the development of the game.

**Comment by geoffthemedio** [comment]
Not superfluous, but competing for time with lots of other stuff and just not yet implemented...

**Comment by Phatmented** [comment]
I didn't know it was still in development. It appears quite functional already
