### ISSUE TITLE
Travis CI Builds Not Shown On GitHub

### ISSUE THREAD

**Issue by geoffthemedio** [freeorion/freeorion#3158]
For seemingly all commits after https://github.com/freeorion/freeorion/commit/4cc5d4c133a8cc8491dcec181f933ea37a7b5d50 the Travis CI builds / tests aren't being run or displayed on GitHub.

On https://travis-ci.org/github/freeorion/freeorion/ it appears that just the Lints are run.

AppVeyor test builds do appear on GitHub.

**Comment by geoffthemedio** [comment]
Perhaps it was because the Lint failed, that all the subsequent test builds weren't run?

After fixing the stringtable, the other builds seem to be running in https://travis-ci.org/github/freeorion/freeorion/builds/722581266

The stringtable Lint failure still wasn't showing up on the GitHub commit lists, though... If it's going to fail and not run the other tests, it should at least show a failure icon.

**Comment by geoffthemedio** [comment]
The test builds for https://github.com/freeorion/freeorion/commit/29762b68b2cbf042036ba95c19124f37edc3700b all ran https://travis-ci.org/github/freeorion/freeorion/builds/722581266 but I see no green checkmarks next to the commit on GitHub.

**Comment by Oberlus** [comment]
You probably are aware of this already, but just in case:

https://travis-ci.community/t/github-pr-is-being-built-but-result-is-not-shown/7025/2


1. Revoke authorization of travis-ci from github:
    Go to https://github.com/settings/applications , find “Travis CI for Open Source” row and click “…” then click the dropdown “Revoke” button.

2. Reset Access of “Travis CI for Open Source” (I’m not sure if this is necessary): Go to github organization home page and click “Settings” - " Third-party access", find the “Travis CI for Open Source” and click the “Edit” button, then it will jump to “Access Review” page, my url like this https://github.com/organizations/hugegraph/settings/oauth_application_policy
    https://github.com/orgs/hugegraph/policies/applications/1508
    click “Deny access” then click “Grant access”.
[Some posted this step wasn't necessary]

3. Re-authorize travis account:
    Go to https://travis-ci.org/, and sign out the account, then click “Sign in with GitHub”, and it will jump to “Authorize Travis CI for Open Source” page, click the green “Authorize travis-ci” button. Well everything is done.


Also
https://travis-ci.community/t/travis-ci-build-no-longer-showing-as-check-on-github-pull-request-page/6955/10

**Comment by adrianbroher** [comment]
That's probably because Travis finally removed support for the GitHub services API, which our integration is still using.

https://docs.travis-ci.com/user/migrate/legacy-services-to-github-apps-migration-guide/

**Comment by geoffthemedio** [comment]
@Oberlus Clicked a bunch as suggested. Couldn't finish 2. but after 3. it seems to be working now.
