### ISSUE TITLE
v0.4.10.1 defaults to three combat bouts, not four

### ISSUE THREAD

**Issue by agrrr3** [freeorion/freeorion#3165]
this is wrong in the release notes as well as in the stringtables

there was a fix to applying scaling also for pilot traits
i think there was also a better rewording for battle, but the stringtables should use three instead of four

https://github.com/freeorion/freeorion/blob/df73fb4c5f5cb59353e4aa225f3ba0e02eeb4243/default/stringtables/en.txt#L6155

**Comment by Vezzra** [comment]
Fixed by db7bd664f98cd2ec83b2880fd19dfe7098822be7
