### ISSUE TITLE
NamedValueLookup referenced unknown ValueRef<d> named 'SHP_REINFORCED_HULL_BONUS'

### ISSUE THREAD

**Issue by Oberlus** [freeorion/freeorion#3186]
Bug Report
==========

Environment
-----------

* **FreeOrion Version**: 1dda8f5
* **Operating System**: Ubuntu 18.04
* **Graphic card used**: GTX 860M
  * Compiled from source

Description
-----------
I'm testing PR #3170, turn 203 in a game that was started using this version. When pressing Turn, connection to server is lost and I get this error:

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  NamedValueLookup referenced unknown ValueRef<d> named 'SHP_REINFORCED_HULL_BONUS'
```

One of the AIs doesn't finish its turn, for what I can see in the GUI, but that's probably because server crashes before updating status in the client. All AI logs say clean exit after `Client connection disconnected by EOF from server.`

Attached logs and a save game from turn 202, press Turn twice to hit the crash.

[logs_1dda8f5.zip](https://github.com/freeorion/freeorion/files/5358999/logs_1dda8f5.zip)
[FreeOrion_Oberlus_Abyss_0202_20201010_145402.zip](https://github.com/freeorion/freeorion/files/5358992/FreeOrion_Oberlus_Abyss_0202_20201010_145402.zip)

I don't know how to get a stack trace of the server. Tried `gbd ./freeoriond` but when running the client it says another server is running.

**Comment by agrrr3** [comment]
> Can you add a screenshot of the "[Test] Name Value Refs" pedia entry?

forget that - you got a syntax error in your named_values.txt file

**Comment by Oberlus** [comment]
Ouch. I saw it. Thank you.
Closing as invalid.

Edit: on turn 204 one AI got the tech and triggers the crash. Removing the lingering parenthesis solves the problem.
