### ISSUE TITLE
NamedReal/NamedInteger value declaration precedence is odd

### ISSUE THREAD

**Issue by Oberlus** [freeorion/freeorion#3188]
Bug Report
==========

Environment
-----------

* **FreeOrion Version**: e8b1d40
* **Operating System**: All

Description
-----------

When writing this:
(NamedReal name = "GARRISON_2_MAXTROOPS_EFFECT" value = 2 * [[TROOPS_PER_POP]]) 

This is intended:
(NamedReal name = "GARRISON_2_MAXTROOPS_EFFECT" value = (2 * [[TROOPS_PER_POP]])) 

But this is what we get:
((NamedReal name = "GARRISON_2_MAXTROOPS_EFFECT" value = 2) * [[TROOPS_PER_POP]]) 

[Forum thread.](https://www.freeorion.org/forum/viewtopic.php?p=103678#p103678)

**Comment by agrrr3** [comment]
It seems precedence is working for integer, but not for floats:

`(NamedReal name = "TWO_BY_THREE" value = 2 * 3)` registers 2.0

`(NamedReal name = "TWO_BY_THREE" value = 2.0 * 3.0)` registers 2.0

`(NamedInteger name = "TWO_BY_THREE" value = 2 * 3)` registers 6

Also it seems this precedence is working for top level named value refs, so the only thing known to be broken is name-in-the-middle Real value refs.

**Comment by agrrr3** [comment]
I made a PR which seems to fix the issue for NamedReal
