### ISSUE TITLE
Manual saves don't load (black screen) when all automatic save options are disabled

### ISSUE THREAD

**Issue by Ouaz** [freeorion/freeorion#3190]
Bug Report
==========

Environment
-----------

* **FreeOrion Version**:  Build 2020-10-13.cd7ecf3
* **Operating System**: Windows 7
* **Graphic card used**: Intel HD graphics 3000
* **Fetched as** 
  * Weekly development build

Description
-----------

If all autosave options are disabled, save files created manually don't load (black screen, only the music plays)

Steps to reproduce
------------------

* Start Freeorion with the default config.xml
* In autosave options, disable everything (`Enable single-player autosaves at turn start`, `Enable multi-player autosaves at turn start`, `Enable autosave after the galaxy creation`, `Enable autosave when resigning or closing game`)
* Start a new single player game.
* Advance to turn 2 then save manually.
* Quit the game, then try to load the manual save.

Here's two save files: 
[test_saves.zip](https://github.com/freeorion/freeorion/files/5378755/test_saves.zip)

_test_automatic.sav_ = All autosave options are enabled (default settings), game is saved manually at turn 2. The save file loads correctly.
_test_manual.sav_ = All autosave options are disabled, game is saved manually at turn 2. The save file doesn't load, only black screen with music playing.

**Comment by agrrr3** [comment]
Might be a different issue, but i had here once autosaves not working with the current weekly build (fedora32, snap, 2020-10-13.cd7edf3). Couldnt recreate on a different machine though. On the first machine i was switching between different freeorion versions via snap.

On the original issue - cant recreate on debian, snap, 2020-10-13.cd7edf3

**Comment by agrrr3** [comment]
oh, and i can load both saves fine. maybe one of the previous processes was still running?

**Comment by geoffthemedio** [comment]
@Ouaz can you check / replicate this again?

**Comment by Ouaz** [comment]
I started FO (with all autosave options disabled) and loaded _test_manual.sav_... and it worked?!

Here's the log:
[freeorion_manual_save_OK.log](https://github.com/freeorion/freeorion/files/5433107/freeorion_manual_save_OK.log)

But I'm still able to reproduce the bug. I restart FO, create a new game, advance to turn 2, then save the game as _manual_2.sav_.

I exit to main menu, then try to load the save file: black screen.

Here's the log:
[freeorion_not_OK.log](https://github.com/freeorion/freeorion/files/5433113/freeorion_not_OK.log)

But if I try to load it from a fresh start (close totally FO then restart), sometimes it works... but sometimes not! (no old process running)

When it does not load, the log stops here:

`[debug] network : clientnetworking.cpp:456 : ClientNetworking::SetPlayerID: player id set to: -1
`

When it loads:

```
[debug] network : clientnetworking.cpp:456 : ClientNetworking::SetPlayerID: player id set to: -1
[debug] client : humanclientapp.cpp:1034 : New roles: 10101
[debug] network : clientnetworking.cpp:456 : ClientNetworking::SetPlayerID: player id set to: 1
Etc.
```

EDIT: each time the save file does not load and I close FO (with close button), it generates a crash report in Windows.

**Comment by Ouaz** [comment]
I installed the `build 2020-11-09.fa112c8`, and the problem seems to have disappeared. Manual saves load correctly, in each case. 

EDIT: Except one: the bug still occurs when the autosave options are disabled **prior** to start a new game, and trying to load the manual save in the same FO session (but the save loads correctly if FO is closed then restarted, but not each time). If the autosave options are disabled after a new game have been started, the manual save loads correctly every time (same session or another one). 

This issue can be safely closed.
