### ISSUE TITLE
Default fleet standing should be Aggressive, not Obstructive.

### ISSUE THREAD

**Issue by Oberlus** [freeorion/freeorion#3203]
Bug Report
==========

Environment
-----------

* **FreeOrion Version**: dc9cf2e
* **Operating System**: Ubuntu 18.04
  * Compiled from source

Description
-----------
AI scout arrives at system Herculis where human player armed ship was awaiting.
However no combat triggers.
That's because of the new fleet standing that defaults to Obstructive.

![No_combat](https://user-images.githubusercontent.com/28650914/97079596-b30bd500-15f5-11eb-8f64-39f379350c44.png)

Expected Result
---------------
Combat triggers upon scout arrival unless player expressly sets the armed fleet to Obstructive/Passive.

Steps to reproduce
------------------
Load attached game save turn 38, press next turn twice, check out SitReps and system Herculis.

[No_combat_save_turns_38_and_40.zip](https://github.com/freeorion/freeorion/files/5432721/No_combat_save_turns_38_and_40.zip)
[No_combat_freeorion_logs.zip](https://github.com/freeorion/freeorion/files/5432722/No_combat_freeorion_logs.zip)
[No_combat_AI_logs.zip](https://github.com/freeorion/freeorion/files/5432723/No_combat_AI_logs.zip)

**Comment by geoffthemedio** [comment]
The fleet is set to obstruct passage but not start combats. Switch it to "initiate combat".

**Comment by Oberlus** [comment]
Oh, I see, the new fleet standing.

The default fleet standing should be aggressive, IMO, because that is what all not-new players will expect, and because there is no obvious reason to not shoot by default at an enemy ship (empires at war).

Should I open a new issue for that, or could this one be repurposed?

**Comment by geoffthemedio** [comment]
Probably this one.

It's actually been implemented for a week or so, but not yet committed to master, as I've been working on something else on the same branch. I've just pushed the relevant commits to https://github.com/freeorion/freeorion/commits/refactor_test though, and will push to master after test builds are OK.

**Comment by geoffthemedio** [comment]
See also: https://www.freeorion.org/forum/viewtopic.php?f=28&t=11799

**Comment by Oberlus** [comment]
New subject of this issue has been solved in master with e283084.
Closing as solved.

**Comment by Vezzra** [comment]
Ok, @geoffthemedio tagged this as invalid, @Oberlus closed this as solved - what is it?

**Comment by Oberlus** [comment]
It was tagged as invalid before I repurposed the opening comment.
I don't mind keeping tags as they are now. Issue is solved anyways.
