### ISSUE TITLE
Provide long descriptions for Nymnmn and Trenchers

### ISSUE THREAD

**Issue by Oberlus** [freeorion/freeorion#3207]
Feature request
===============

Nymnmn and Trenchers are the only species apart from Super Testers that do not have a description:
```
SP_NYMNMN
Nymnmn

SP_NYMNMN_GAMEPLAY_DESC
'''Planet-wide sapient magnetic waveforms.
Prefer [[PT_DESERT]] planets.
[[encyclopedia SELF_SUSTAINING_SPECIES_TITLE]]
'''

SP_NYMNMN_DESC
''''''

SP_TRENCHERS
Trenchers

SP_TRENCHERS_GAMEPLAY_DESC
'''<img src="species/preview/trenchers.png"></img>
Enigmatic wheeled robots devoted to carving up their planet into the most elaborate curves and spirals.
Prefer [[PT_BARREN]] planets.
[[encyclopedia ROBOTIC_SPECIES_TITLE]]
'''

SP_TRENCHERS_DESC
<img src="species/trenchers.png"></img>
```

It would be good to get nice fluffy descriptions for them. I could not find any piece of text for them lost in the forum.

**Comment by agrrr3** [comment]
@oberlus maybe ask on the forums for fluff?

**Comment by st-pa-fo** [comment]
i made something up for the Nymnmn … 't was fun to do, but took really a lot longer than expected

**Comment by geoffthemedio** [comment]
Is this resolved?

**Comment by Oberlus** [comment]
Well, almost done. Trenchers still pending (text now is "coming soon" xD)

**Comment by Oberlus** [comment]
Closed as resolved.
