### ISSUE TITLE
NamedValueRefManager doesn't generate same checksum

### ISSUE THREAD

**Issue by o01eg** [freeorion/freeorion#3220]
Bug Report
==========

Environment
-----------
* **FreeOrion Version**: 2999af27e6dbef5b6a2c64cf48e11a2de06d51e5
* **Operating System**: Linux Devuan Testing AMD64
* **Graphic card used**: Intel
* **Fetched as** 
  * Compiled from source

Description
-----------
When I launch unittests I sometimes got checksum error:

```
[warn] ai : ClientApp.cpp:173 : Checksum for NamedValueRefManager on server 215410 != client 2208271

[warn] ai : ClientApp.cpp:173 : Checksum for NamedValueRefManager on server 215410 != client 6123322

[warn] test : ClientApp.cpp:173 : Checksum for NamedValueRefManager on server 2208271 != client 215410
```

Looks like checksum calculation for `NamedValueRefManager` isn't stable and could provide different results.

Expected Result
---------------
Tests are passed.

Steps to reproduce
------------------
* Build freeorion with unittests
* Launch `fo_systemtest_game --run_test=SmokeTestGame` some times (near 20% or launches catch this error).
* Issue occurs.

**Comment by agrrr3** [comment]
I got here a test run where  the last four double named refs are missing on the AI client.
```
server : NamedValueRefManager.cpp:115 : NamedValueRefManager current checksum: 2863741 at XENOPHOBIC_OTHER_TARGET_INDUSTRY_PERPOP
 server : NamedValueRefManager.cpp:115 : NamedValueRefManager current checksum: 864180 at XENOPHOBIC_SELF_TARGET_HAPPINESS_COUNT
 server : NamedValueRefManager.cpp:115 : NamedValueRefManager current checksum: 4868948 at XENOPHOBIC_SELF_TARGET_INDUSTRY_SCALING
 server : NamedValueRefManager.cpp:115 : NamedValueRefManager current checksum: 8873338 at XENOPHOBIC_SELF_TARGET_RESEARCH_SCALING
```
"Last four" means in alphabetic order. I cant think of a reason why that should matter and also of no reason why the XENOPHOBIC value refs should not be present. Maybe this is just a conincidence. I will rerun this

Ran this three times, always with the same result

**Comment by agrrr3** [comment]
Removing the missing value refs "worked" for me.  SmokeTestGame via fo_systemtest_game fails but not for checksum
```
20:14:19.250737 {0x00007f6953a6d780} [info] test : ClientAppFixture.cpp:137 : Handle message SAVE_GAME_COMPLETE
20:14:20.251088 {0x00007f6953a6d780} [debug] test : Process.cpp:87 : Process::Terminate
20:14:20.251201 {0x00007f6953a6d780} [debug] test : Process.cpp:89 : Process::Terminate calling m_impl->Terminate()
20:14:20.251258 {0x00007f6953a6d780} [debug] test : Process.cpp:253 : Process::Impl::Terminate calling kill(m_process_id, SIGINT)
20:14:20.251328 {0x00007f6953a6d780} [debug] test : Process.cpp:255 : Process::Impl::Terminate calling waitpid(m_process_id, &status, 0)
20:14:20.711036 {0x00007f6953a69700} [debug] network : ClientNetworking.cpp:508 : Client connection disconnected by EOF from server.20:1
4:20.711044 {0x00007f6953a6d780} [debug] test : Process.cpp:257 : Process::Impl::Terminate done
20:14:20.711036 {0x00007f6953a69700} [debug] network : ClientNetworking.cpp:508 : Client connection disconnected by EOF from server.20:1
4:20.711044 {0x00007f6953a6d780} [debug] test : Process.cpp:257 : Process::Impl::Terminate done
20:14:20.711094 {0x00007f6953a6d780} [warn] test : Process.cpp:259 : Process::Impl::Terminate got failure status 139
20:14:20.711107 {0x00007f6953a6d780} [debug] test : Process.cpp:94 : Process::Terminate calling RequestTermination()
20:14:20.711121 {0x00007f6953a6d780} [debug] test : Process.cpp:271 : Process::Impl::Kill calling kill(m_process_id, SIGKILL)
20:14:20.711130 {0x00007f6953a6d780} [debug] test : Process.cpp:273 : Process::Impl::Kill calling waitpid(m_process_id, &status, 0)
20:14:20.711138 {0x00007f6953a6d780} [debug] test : Process.cpp:275 : Process::Impl::Kill done
```

log looks different if run via make tests (e.g. SmokeTestHostless)
```
Waiting AI for turns...ESC[0;39;49m
19:32:14.697344 {0x00007f5a57d7e780} [debug] FSM : ServerFSM.cpp:305 : ServerFSM::HandleNonLobbyDisconnection : Lost connection to playe
r #1, named "TestPlayer".
19:32:14.697441 {0x00007f5a57d7e780} [warn] FSM : ServerFSM.cpp:322 : Player #1, named "TestPlayer"quit before empire was eliminated.
19:32:14.697469 {0x00007fb707d39700} [debug] network : ClientNetworking.cpp:508 : Client connection disconnected by EOF from server.
19:32:14.697852 {0x00007f5a57d7e780} [debug] python : <string>:3 : Python current directory set to /home/user/freeorion/freeorion/default/python/chat
19:32:14.698240 {0x00007f5a57d7e780} [info] python : chat.py:41 : Chat : [[PLAYER_LEFT_GAME,TestPlayer]] (255, 255, 255, 255)
19:32:14.698509 {0x00007f5a57d7e780} [error] FSM : ServerFSM.cpp:380 : Too high unconnected human player 1 expected 1; server terminating.
```

**Comment by agrrr3** [comment]
So it looks like the observed behavior (some named refs missing in the registries) could come from concurrently parsing and handling messages.
E.g. if the server sends a checksum after parsing and the AI wants to calculate that, it accesses all managers to calculate their contents' checksum, which using the Pending mechanism to block execution if parsing did not return a result (i.e. parsing finished). 
The NamedValueRefManager does not use the Pending mechanism, so if that is still parsing, some of the named values are not registered yet. 
Also as other parsers register named values, the NamedValueRefManager calculation of checksum must start after all other parsing of content with valuerefs is finished or block until those parsing threads are finished.

Also this might be related to a deterministic solution to correctly initialise invariants, because the initialisation may only happen after parsing is finished. See #3225

**Comment by o01eg** [comment]
I suppose it was fixed in #3221 ?

**Comment by agrrr3** [comment]
Yes, should be fixed

**Comment by agrrr3** [comment]
> Also this might be related to a deterministic solution to correctly initialise invariants, because the initialisation may only happen after parsing is finished. See #3225

Just as note: as the invariants are not part of the checksum calculations, so the checksums on client/server can never differ because of differently calculated invariants
