### ISSUE TITLE
TestEnumParser started to fail

### ISSUE THREAD

**Issue by o01eg** [freeorion/freeorion#3224]
Bug Report
==========

Environment
-----------
* **FreeOrion Version**: 4550078
* **Operating System**: Ubuntu Bionic 18.04 (Travis CI)
* **Fetched as** 
  * Compiled from source

Description
-----------
Enum parser test started to fail with errors:

```
    Start 1: TestEnumParser

1/4 Test #1: TestEnumParser ...................***Failed    0.06 sec

Running 13 test cases...

/home/travis/build/freeorion/freeorion/test/parse/TestEnumParser.cpp:141: error: error: in "TestEnumParser/EmpireAffiliationTypeParser": check pass has failed

/home/travis/build/freeorion/freeorion/test/parse/TestEnumParser.cpp:141: error: error: in "TestEnumParser/EmpireAffiliationTypeParser": check result == EmpireAffiliationType::AFFIL_HUMAN has failed

/home/travis/build/freeorion/freeorion/test/parse/TestEnumParser.cpp:308: error: error: in "TestEnumParser/StatisticTypeParser": check pass has failed

/home/travis/build/freeorion/freeorion/test/parse/TestEnumParser.cpp:308: error: error: in "TestEnumParser/StatisticTypeParser": check result == ValueRef::StatisticType::RMS has failed

*** 4 failures are detected in the test module "FreeOrion unit/coverage tests parser"
```

Looks like it happened after #3210

Expected Result
---------------
CI unittests are passed.

Steps to reproduce
------------------
* Build and run parser unit tests.

**Comment by geoffthemedio** [comment]
https://github.com/freeorion/freeorion/blob/master/test/parse/TestEnumParser.cpp#L141 should probably pass Human not HUMAN

https://github.com/freeorion/freeorion/blob/master/test/parse/TestEnumParser.cpp#L308 should probably pass RMS not Rms


Trying https://github.com/freeorion/freeorion/commit/2972b568d95ff008d30b38d0a06713f2e61f9e17

**Comment by o01eg** [comment]
@geoffthemedio Yes, it works for me.

**Comment by geoffthemedio** [comment]
Should be fixed by https://github.com/freeorion/freeorion/commit/6b359c3e90393e3778de9f0847974e5ea192ed3b
