### ISSUE TITLE
Turn advance is broken - freeze

### ISSUE THREAD

**Issue by agrrr3** [freeorion/freeorion#3246]
Bug Report
==========
Turn advance is broken - I checked single player with 6 AI and single player with zero AI.

Environment
-----------
current master build locally, and weekly build snap on fedora 32/33

Description
-----------

Turn advance on turn 1 freezes.

Expected Result
---------------

Turn two is ready for orders.

Steps to reproduce
------------------
* Start a single player game (with zero or more AI)
* Click turn advance

**Comment by agrrr3** [comment]
@o01eg auto-turn is the culprit
```
commit 82c69f3951d302456133337a01ce4f51f3851440
Merge: 94ab2f2e0 c876e9d02
```

**Comment by o01eg** [comment]
Yes, I've already opened PR to fix it.
