### ISSUE TITLE
Crash to desktop when trying to launch FO on macOS

### ISSUE THREAD

**Issue by Vezzra** [freeorion/freeorion#3252]
Bug Report
==========

Environment
-----------

* **FreeOrion Version**: 0.4.10+, build 81807c6a864d51fefdd8433d821609cbc4008da8
* **Operating System**: macOS 10.14.6
* **Fetched as** 
  * Compiled from source

Description
-----------

﻿﻿When I try to launch FO on macOS, the app immediately crashes. On the terminal I get this output:
```
Assertion failed: (e == 0), function ~recursive_mutex, file /BuildRoot/Library/Caches/com.apple.xbs/Sources/libcxx/libcxx-400.9.4/src/mutex.cpp, line 64.
Abort trap: 6
```
freeorion.log: [freeorion.log.zip](https://github.com/freeorion/freeorion/files/5625216/freeorion.log.zip)

**Comment by Vezzra** [comment]
@o01eg pointed to a possible cause in the comment section of #3243, see [here](https://github.com/freeorion/freeorion/pull/3243#issuecomment-735430472).

**Comment by agrrr3** [comment]
Googling for similar problems, error message seems only to exist for MacOS / iOS. Not sure if those handle threads/mutexes in a different way - they shouldnt or if that problem also exists on win32/linux.

I just build 81807c6 on linux and i can start and play and quit without problems.

@Vezzra is that always happening on start for you?

**Comment by Vezzra** [comment]
@agrrr3,

> is that always happening on start for you?

Yes. I can't start FO on Mac at all with current master. Crashes every time.
