### ISSUE TITLE
Exception float division by zero occurred during generateOrders

### ISSUE THREAD

**Issue by a2geek** [freeorion/freeorion#3257]
Bug Report
==========
Am seeing divide by zero errors in logs. Uncertain conditions required. Game is random setting, 50 planets, 3 AI's at Turtle mode (yeah, I'm still stinky at this game!).

```
[19 Dec 15:27:11] AI_3: AI_Error: AI script error : FreeOrionAI.py:_error_handler():73  - Exception float division by zero occurred during generateOrders
Traceback (most recent call last):
  File "/snap/freeorion/128/share/freeorion/default/python/AI/FreeOrionAI.py", line 70, in _error_handler
    res = func(*args, **kwargs)
  File "/snap/freeorion/128/share/freeorion/default/python/common/listeners.py", line 42, in wrapper
    res = funct(*args)
  File "/snap/freeorion/128/share/freeorion/default/python/AI/FreeOrionAI.py", line 336, in generateOrders
    aistate.prepare_for_new_turn()
  File "/snap/freeorion/128/share/freeorion/default/python/AI/AIstate.py", line 998, in prepare_for_new_turn
    self.__report_last_turn_fleet_missions()
  File "/snap/freeorion/128/share/freeorion/default/python/AI/AIstate.py", line 952, in __report_last_turn_fleet_missions
    CombatRatingsAI.get_fleet_rating(fleet_id),
  File "/snap/freeorion/128/share/freeorion/default/python/AI/CombatRatingsAI.py", line 395, in get_fleet_rating
    return FleetCombatStats(fleet_id, consider_refuel=False).get_rating(enemy_stats)
  File "/snap/freeorion/128/share/freeorion/default/python/AI/CombatRatingsAI.py", line 370, in get_rating
    return combine_ratings_list([x.get_rating(enemy_stats, ignore_fighters) for x in self.__ship_stats])
  File "/snap/freeorion/128/share/freeorion/default/python/AI/CombatRatingsAI.py", line 370, in <listcomp>
    return combine_ratings_list([x.get_rating(enemy_stats, ignore_fighters) for x in self.__ship_stats])
  File "/snap/freeorion/128/share/freeorion/default/python/AI/CombatRatingsAI.py", line 284, in get_rating
    shield_factor = e_total_attack / e_net_attack
ZeroDivisionError: float division by zero
```

Environment
-----------

* **FreeOrion Version**: v0.4.10.1
* **Operating System**: Ubuntu 20.04, installed via snap
* **Graphic card used**: Radeon RX 580
* **Fetched as** 
  * Binary release

```
$ snap list freeorion
Name       Version    Rev  Tracking       Publisher  Notes
freeorion  v0.4.10.1  128  0.4.10/stable  agrrr3     -
```

Description
-----------

Expected Result
---------------

Steps to reproduce
------------------

Uncertain. But I will upload the game save state.

**Comment by a2geek** [comment]
[save-20201219_153743.sav.gz](https://github.com/freeorion/freeorion/files/5720181/save-20201219_153743.sav.gz)

**Comment by Vezzra** [comment]
@freeorion/ai-team? @Morlic-fo?

**Comment by Cjkjvfnby** [comment]
I dig code a little and find out the problem might be present at this point:

https://github.com/freeorion/freeorion/blob/master/default/python/AI/CombatRatingsAI.py#L200
```python
shots = ship.currentPartMeterValue(fo.meterType.secondaryStat, partname)
```
If happens when `shots` is 0. 

We haven't hit this before because it was hardcoded.
https://github.com/freeorion/freeorion/commit/b67efe89e5877e08dff2ab18a43d15b7e4b9b4d0

Looks like some part has 0 shots.  @Vezzra is 0 shots considered to be a bug and should be fixed in content or it is a normal situation and we should fix it in the code?  

Fix in code might look like:
```python
shots = max(ship.currentPartMeterValue(fo.meterType.secondaryStat, partname), 1)
```

Ps. I have not had a game installed.

**Comment by Vezzra** [comment]
> is 0 shots considered to be a bug and should be fixed in content or it is a normal situation and we should fix it in the code?

Good question, I'd say it's a bug (what sense does a 0 shot weapon make?), but I'm not sure - @geoffthemedio? @Oberlus? @agrrr3? Any input on this?

@Cjkjvfnby: In any case, the fix you suggest makes sense. Maybe write a warning/error into the log about encountering a weapon part with 0 shots, but make sure to continue without throwing.

**Comment by geoffthemedio** [comment]
Probably there are cases with a species or other reduction of shots to zero on what would otherwise be a 1+ shot weapon.

**Comment by Vezzra** [comment]
Ok, makes sense. Meaning, that case can legitimately happen.

 So the fix @Cjkjvfnby suggested should go in - if assuming 1 shots in case there are actually 0 in the context of that code section is ok, that is. @freeorion/ai-team?

**Comment by Oberlus** [comment]
I can't find where the division by zero (by shots==0) happens.

**Comment by geoffthemedio** [comment]
> I can't find where the division by zero (by shots==0) happens.

Based on the provided stack trace, [here](https://github.com/freeorion/freeorion/blob/master/default/python/AI/CombatRatingsAI.py#L278):
````
            if e_attacks:
                # e_num_attacks = sum(n for n in e_attacks.values())
                e_total_attack = sum(n*dmg for dmg, n in e_attacks.items())
                # e_avg_attack = e_total_attack / e_num_attacks
                e_net_attack = sum(n*max(dmg - my_shields, .001) for dmg, n in e_attacks.items())
                e_net_attack = max(e_net_attack, .1*e_total_attack)
                shield_factor = e_total_attack / e_net_attack
                my_structure *= max(1, shield_factor)
            my_total_attack = sum(n*max(dmg - e_shields, .001) for dmg, n in my_attacks.items())
````
Presumably `e_net_attack` is 0 if there are no shots, so replace on line 284 with something like `max(1.0, e_net_attack)` or `max(.001, e_net_attack)`

**Comment by Cjkjvfnby** [comment]
Hi, I am back from vacation and plan to investigate this issue. 

> Probably there are cases with a species or other reduction of shots to zero on what would otherwise be a 1+ shot weapon.

Looks like an issue: either having a weapon with 0 damage on a ship or getting incorrect stats.   

@geoffthemedio, which empire bonus will be applied to parts in this code? 

```python
ship.currentPartMeterValue(fo.meterType.secondaryStat, partname)
```

Will it be the shipowner (enemy) or AI which calculates it?

**Comment by geoffthemedio** [comment]
> @geoffthemedio, which empire bonus will be applied to parts in this code?

Do you mean what effects will have been applied when this code runs, or which effects will be calculated by this code itself? I don't really know how all the AI code works, but it doesn't immediately appear to be calculating effects, so I'll assume that you mean what effects will have been applied when this code runs. As I don't really know how the AI code works, I'm still not sure... but I assume all effects / meter updates will have been run when this code is called. 

> Will it be the shipowner (enemy) or AI which calculates it?

All I can say is that there is a parameter to the function named `enemy_stats`, which suggests that it may calculate information about enemy empire ships...
