### ISSUE TITLE
0.4.10.1 build fails with "error: 'ShipPartMeters' function with trailing return type has 'const auto&' as its type rather than plain 'auto'"

### ISSUE THREAD

**Issue by daniel-santos** [freeorion/freeorion#3258]
[emerge-info.txt](https://github.com/freeorion/freeorion/files/5720341/emerge-info.txt)
I'm building on Gentoo Linux x86_64.  Attached is my emerge --info games-strategy/freeorion (after I commented out the offending line and a dependency).

```
FAILED: CMakeFiles/freeorionca.dir/python/UniverseWrapper.cpp.o 
/usr/bin/ccache /usr/bin/x86_64-pc-linux-gnu-g++ -DBINPATH=\"/usr/bin\" -DBOOST_ALL_DYN_LINK -DENABLE_BINRELOC -DFREEORION_BUILD_AI -DFREEORION_LINUX -DSHAREPATH=\"/usr/share\" -I/tmp/portage/games-strategy/freeorion-0.4.10.1-r1/work/freeorion-0.4.10.1/GG/Boost::boost -I/tmp/portage/games-strategy/freeorion-0.4.10.1-r1/work/freeorion-0.4.10.1/GG -isystem /usr/include/python3.7m  -march=native -O2 -ggdb3 -pipe -fvisibility=hidden   -Wall -std=c++14 -MD -MT CMakeFiles/freeorionca.dir/python/UniverseWrapper.cpp.o -MF CMakeFiles/freeorionca.dir/python/UniverseWrapper.cpp.o.d -o CMakeFiles/freeorionca.dir/python/UniverseWrapper.cpp.o -c /tmp/portage/games-strategy/freeorion-0.4.10.1-r1/work/freeorion-0.4.10.1/python/UniverseWrapper.cpp
/tmp/portage/games-strategy/freeorion-0.4.10.1-r1/work/freeorion-0.4.10.1/python/UniverseWrapper.cpp:193:5: error: 'ShipPartMeters' function with trailing return type has 'const auto&' as its type rather than plain 'auto'
  193 |     const auto&             (Ship::*ShipPartMeters)(void) const =                               &Ship::PartMeters;
      |     ^~~~~
/tmp/portage/games-strategy/freeorion-0.4.10.1-r1/work/freeorion-0.4.10.1/python/UniverseWrapper.cpp: In function 'void FreeOrionPython::WrapUniverseClasses()':
/tmp/portage/games-strategy/freeorion-0.4.10.1-r1/work/freeorion-0.4.10.1/python/UniverseWrapper.cpp:607:67: error: 'ShipPartMeters' was not declared in this scope; did you mean 'ShipPartManager'?
  607 |             .add_property("partMeters",             make_function(ShipPartMeters,           return_internal_reference<>()))
      |                                                                   ^~~~~~~~~~~~~~
      |                                                                   ShipPartManager
```

**Comment by daniel-santos** [comment]
This is my build log.  Unfortunately, it's been appended to a few times as I tweaked the code and rebuilt.
[freeorion-0.4.10.1-r1:20201219-231816.log.gz](https://github.com/freeorion/freeorion/files/5720343/freeorion-0.4.10.1-r1.20201219-231816.log.gz)

**Comment by geoffthemedio** [comment]
> `UniverseWrapper.cpp:193:5: error: 'ShipPartMeters' function with trailing return type has 'const auto&' as its type rather than plain 'auto'`

[That line](https://github.com/freeorion/freeorion/blob/release-v0.4.10/python/UniverseWrapper.cpp#L193) isn't declaring a function with a trailing return type, but rather a function pointer. Not sure what the problem is.

Maybe try replacing `const auto&` with `const Ship::PartMeterMap&` ?

**Comment by daniel-santos** [comment]
Wow, I had forgotten how much TMP can increase compile time and memory!  That change builds.

I haven't used trailing return types or come across them yet (that I can remember) and I don't see why it was parse it that way.  I guess this is a gcc bug?  Version is:

gcc (Gentoo 10.2.0-r2 p3) 10.2.0

BTW, do you know if gcc can build this `-flto` yet? :)  I suppose I could give it a try, I have 64G of ram on this workstation.

**Comment by geoffthemedio** [comment]
> do you know if gcc can build this `-flto` yet?

If you're asking me, no idea. I develop and build on Windows with MSVC. That has some link time optimization that seems to run successfully, if that indicates anything...

**Comment by daniel-santos** [comment]
Oh, I see!  Well it seems to build and run fine with -flto.  Yes, msvc has had whole program optimizations for some time, I'm not sure how the two compare though.  In GCC, it has only become "mostly stable" in the last two years, by which I mean there are some cases where it still fails to compile, although I suspect that every case of "compiling but building bad code" is now fixed.

I'm going to close this an open an upstream report.  It built on GCC 9 w/o problems, so it looks like a regression.  Thanks!

**Comment by daniel-santos** [comment]
[Upstream GCC bug report](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=98441) has been opened.
