### ISSUE TITLE
initial Resonant Moon and Artificial Moon

### ISSUE THREAD

**Issue by aschuch247** [freeorion/freeorion#326]
I have a colony with Resonant Moon since the initial turn. Still, I can build an Artificial Moon there. Does that make sense? A requirement for Artificial Moon already is that the colony does not have an Artifical Moon building yet. Maybe add that a Resonant Moon must not be present either?

master (9c7444728d139b4c53b4ddde22918597a5318d8a)

**Comment by Vezzra** [comment]
Being able to build an Artifical Moon if one is already present does not make much sense, the proposed fix sounds reasonable IMO.
