### ISSUE TITLE
AIs Should Adopt Policies and Manage Influence and Planet Stability

### ISSUE THREAD

**Issue by geoffthemedio** [freeorion/freeorion#3272]
Recent versions of master have an influence resource which can be used to adopt policies, as well as various effects that modify planet stability (previously and still internally the "HAPPINESS" meter). Several techs, primarily for production bonuses, as well as meter growth on planets, depend on planets' stability level to function.

AIs should be upated to be aware of the features and mechanics, and to play accordingly.

Notably important are various useful effects that can be acquired by adopting policies.

As well, number of colonies / outposts owned, supply connection or lack thereof or distance to the capital or a regional adiminstration building have effects on planet stability.

Some planets should generally be set to influence focus to generat more of it for the empire.

These features and content are still works in progress and subject to changes and balancing, but some mechanisms for the AI to be aware of and make use of them are needed.

**Comment by geoffthemedio** [comment]
@Cjkjvfnby obviously your support would be highly appreciated...

**Comment by Cjkjvfnby** [comment]
Looks like this feature affects all aspects of the AI.

**Comment by Oberlus** [comment]
Current implementation of policies and influence (as of 60a10c5) is far from definitive. Balance is off by far, some stuff doesn't make sense fluff-wise or gameplay-wise and people will want it changed, and whatnot.
Implementation of AI using policies should be conservative and minimalistic for now. Maybe the general functions to de/adopt policies, and some hard-scripted adoption of a few policies, while ignoring most of them.
In any case, AIs ignoring policies and influence are still competitive (specially as long as having negative influence stockpile does not imply any negative effects).

**Comment by geoffthemedio** [comment]
@Cjkjvfnby @Grummel7 Can this be considered resolved?

**Comment by Grummel7** [comment]
I guess we can say yes. It does use influence focus, several policies and IRAs. Of course the AI does not consider all policies, but then there are much older features it does not use, like terraforming and gaia transformation.

**Comment by Vezzra** [comment]
@Cjkjvfnby? Want to add anything? Can we close this as resolved?

**Comment by Cjkjvfnby** [comment]
@Vezzra , I totally agree with @Grummel7.
