### ISSUE TITLE
Divine Authority is not unlocked by any tech

### ISSUE THREAD

**Issue by Oberlus** [freeorion/freeorion#3284]
Bug Report
==========

* **FreeOrion Version**: 60a10c5

No tech unlocks PLC_DIVINE_AUTHORITY:
```
freeorion$ grep -rl DIVINE default/scripting/*
default/scripting/policies/DIVINE_AUTHORITY.focs.txt
freeorion$
``` 

Maybe, fluff wise, it could be done in TRANSCEND_ARCH. It is not a perfect match, and has no reasoning behind about if that's the right place balance-wise, but I don't see anything better than that.
Alternatively, place it at PSIONICS, but that one is already overloaded of policies (I would relocate some of those, but that's another issue), and you don't need fantastical mind powers to hold divine authority among your people.

**Comment by geoffthemedio** [comment]
Make a pull request?
