### ISSUE TITLE
stealth and detection range descriptions inconsistent

### ISSUE THREAD

**Issue by aschuch247** [freeorion/freeorion#329]
Sentient Hull:

The descriptions says "Stealth is good" and "Detection Range is good"; stealth is 45 and detection range is 100.

Bio-Adaptive Hull:

"Stealth is high" and "Detection Range is excellent"; stealth is 35 and detection range is 75.

Protoplasmic Hull:

"Stealth is high" and "Detection Range is good"; stealth is 35 and detection range is 50.

Endosymbiotic Hull:

"Stealth is good" and "Detection Range is high"; stealth is 25 and detection range is 50.

---

What is the intended order - good, high, excellent? I haven't checked further descriptions, so there might be more inconsistencies.

I am using master (de699b506aeee3bd24385f169ebb0c22a731069b).

**Comment by MatGB** [comment]
The intended order and what actually ended up being written were, it appears, very inconsistent, I added and updated all those descriptors as a temporary measure this time last year before the auto generated numbers were displayable, I think that's now working properly so it should be taken out.

Stealth is High is meant to be better than Stealth is Good, I suspect I forgot that the Sentient gives itself a +20 bonus on top of the basic stealth 25, which is of course lower than the 35 for Bi-Ad and Proto. No idea why I messed up Good and High for detection. Thanks for letting us know, I'll get that fixed at some point this week (probably when I upload the new art for the Endosymbiotic, that's lovely).

**Comment by Vezzra** [comment]
@MatGB, any progress on that? Or maybe already fixed, and just forgot to close this issue?

**Comment by MatGB** [comment]
I had forgotten it completely, at one point someone else was going to do some work on it, possibly @vincele , not sure if anything got done, I know I didn't.  I think it's more than just scriptable work though, IIRC you can't pull out some stats into the Pedia and I forgot to get someone to look into it. 

Ideally, any info in the Pedia should be generated whenever possible, the paragraphs in question were added by me in an attempt to standardise a previous mess but some are already out of date and/or had a generated stat display added.

**Comment by vincele** [comment]
Nope, I don't think I ever noticed that bug myself...

**Comment by Vezzra** [comment]
Ok, I see. Anyway, I think we should fix this for 0.4.6 - @MatGB, as the one still assigned to this issue, do you think you can squeeze that in somewhere within the next few weeks?

**Comment by LGM-Doyle** [comment]
@MatGB I posted PR #695.  I hope it frees you up for other balancing.

**Comment by Vezzra** [comment]
Should be fixed by #695, so closing this issue.
