### ISSUE TITLE
OLONY_ADMIN_COSTS_PER_PLANET in default/scripting/species/common/influence.macros line 12

### ISSUE THREAD

**Issue by jinlan** [freeorion/freeorion#3312]
I don't know whether it actually caused a bug, it seems like miss spelling.

version: 2021-02-09.cb4b741

-------------------------------------------------------------------------------------------

One more thing. Could you tell me how to modify this file to make "OLONY_ADMIN_COSTS_PER_PLANET" don't count outpost? I really don't want wait for a week.

I tried added a new line after line 15:
Not Population high = 0

Is that OK?

**Comment by geoffthemedio** [comment]
> I don't know whether it actually caused a bug, it seems like miss spelling.

Probably not an issue; the name of the reference isn't used elsewhere as far as I can tell.

> Could you tell me how to modify this file to make "OLONY_ADMIN_COSTS_PER_PLANET" don't count outpost? I really don't want wait for a week.
> 
> I tried added a new line after line 15:
> Not Population high = 0
> 
> Is that OK?

Should work. Also could check for if it has any species with `Species`.
