### ISSUE TITLE
Build error with 0.4.10.1: cmake cannot find boost_python library from boost 1.61.0

### ISSUE THREAD

**Issue by GvMariani** [freeorion/freeorion#3334]
Bug Report
==========
Trying to do a local build of freeorion 0.4.10.1, from the sources from github.
The build fails at cmake configure stage with the error message: "CMake Error at cmake/FindBoost.cmake:2161 (message):
Unable to find the requested Boost libraries. Boost version: 1.61.0 Boost include path: /usr/include 
Could not find the following Boost libraries: boost_python35
No Boost libraries were found."

Environment
-----------
* **FreeOrion Version**: 0.4.10.1
* **Operating System**: Rosa Linux Fresh 2016.1 (a Mandriva derivative) x86_64
* **Graphic card used**:  Radeon RX460
* **Fetched as**: Compiled from source
* **Compiler**: gcc 5.5.0
* **Boost release installed**: 1.61.0
* **Python releases installed**: 3.5.9 and 2.7.14
* **CMake release installed**: 3.16.2

Description
-----------
Cmake command line used:
*********************************
/usr/bin/cmake .. -DCMAKE_INSTALL_PREFIX:PATH=/usr -DCMAKE_INSTALL_LIBDIR:PATH=/usr/lib64 -DINCLUDE_INSTALL_DIR:PATH=/usr/include -DLIB_INSTALL_DIR:PATH=/usr/lib64 -DSYSCONF_INSTALL_DIR:PATH=/etc -DSHARE_INSTALL_PREFIX:PATH=/usr/share -DLIB_SUFFIX=64 -DCMAKE_SKIP_RPATH:BOOL=ON -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DBUILD_SHARED_LIBS:BOOL=ON -DBUILD_STATIC_LIBS:BOOL=OFF '-DCMAKE_MODULE_LINKER_FLAGS= -Wl,--as-needed -Wl,--no-undefined -Wl,-z,now -Wl,-z,relro -Wl,-O1 -Wl,--build-id -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,--unresolved-symbols=ignore-all' -DCMAKE_BUILD_TYPE=Release -DLIB_SUFFIX=64 -DBUILD_SHARED_LIBS=OFF -DENABLE_TIFF_TEXTURES=ON
*********************************

In my system Boost 1.61.0 libraries are in /usr/lib64 and header files in /usr/include/boost; the installed python3 libraries in /usr/lib64 are: lib64boost_python3_1.61.0 and libboost_python3.so (there are also lib64boost_python1_1.61.0 and libboost_python1.so, supporting python2).

Cmake searches for and finds various boost libraries (filesystem, iostreams, locale, log, log_setup, serialization, system, thread, regex, date_time, chrono and  atomic), but fails to find the libboost_python3 ones with this error message:
***********************************
CMake Error at cmake/FindBoost.cmake:2161 (message):
Unable to find the requested Boost libraries.
Boost version: 1.61.0
Boost include path: /usr/include
Could not find the following Boost libraries:
         boost_python35
No Boost libraries were found.  You may need to set BOOST_LIBRARYDIR to the directory containing Boost libraries or BOOST_ROOT to the location of Boost.
Call Stack (most recent call first):
CMakeLists.txt:240 (find_package)
***********************************

The culprit is at the lines 240-241 of the main CMakeLists.txt file:
*********************
find_package(Boost COMPONENTS python${PYTHON_VERSION_MAJOR}${PYTHON_VERSION_MINOR} REQUIRED)
set(Boost_PYTHON_SUFFIX "${PYTHON_VERSION_MAJOR}${PYTHON_VERSION_MINOR}")
*********************
AFAICT the last line instructs cmake to search for a library called libboost_python35, while the installed one is name libboost_pyhton3.
Since the minimum boost version supported is set to "1.58.0" (see in the line 223 of the main CMakelists.txt file), that statement looks wrong to me: as stated in the initial comment of the provided FindBoost.cmake file (lines 44-51), the boost python libraries have a version suffix in the form of major.minor only in boost release 1.67.0 and above... In boost <= 1.66.0 the version suffix is distribution specific: in my case they are "1" for python2 and "3" for python3.

The issue can be easily worked around by patching the main CMakeLists.txt file and cmake/make_versioncpp.py to remove the mention of the minor version number (see attached patch), but this in turn will cause trouble for any boost >= 1.67 and cannot be the proper solution... As an alternative, the minimum boost version required should be bumped to "1.67.0".
[freeorion-0.4.10.1-fix-boost_python-detection.txt](https://github.com/freeorion/freeorion/files/6054460/freeorion-0.4.10.1-fix-boost_python-detection.txt)

Expected Result
---------------
The build continues.

Steps to reproduce
------------------
* Install the 0.4.10.1 sources.
* Run cmake with the command line reported above.
* Look at the error message.

**Comment by geoffthemedio** [comment]
> Since the minimum boost version supported is set to "1.58.0" (see in the line 223 of the main CMakelists.txt file), that statement looks wrong to me: as stated in the initial comment of the provided FindBoost.cmake file (lines 44-51), the boost python libraries have a version suffix in the form of major.minor only in boost release 1.67.0 and above... In boost <= 1.66.0 the version suffix is distribution specific: in my case they are "1" for python2 and "3" for python3.

[TravisCI builds](https://travis-ci.org/github/freeorion/freeorion/jobs/732703727#L300) succeed on Ubuntu 18.04 with Boost 1.62 installed, so the minimum shouldn't need to be Boost 1.67 just to fix a library naming inconsistency problem. What about something like (untested, problably malformed, but the idea should be clear, [based on this](https://stackoverflow.com/questions/50978724/how-can-i-make-find-package-search-with-config-mode-and-fallback-on-module-mode)):
````
find_package(Boost COMPONENTS python${PYTHON_VERSION_MAJOR}${PYTHON_VERSION_MINOR} CONFIG QUIET)
if(python${PYTHON_VERSION_MAJOR}${PYTHON_VERSION_MINOR}_FOUND)
    set(Boost_PYTHON_SUFFIX "${PYTHON_VERSION_MAJOR}${PYTHON_VERSION_MINOR}")
else()
    find_package(Boost COMPONENTS python${PYTHON_VERSION_MAJOR} REQUIRED)
    set(Boost_PYTHON_SUFFIX "${PYTHON_VERSION_MAJOR}")
endif()
````

**Comment by GvMariani** [comment]
> find_package(Boost COMPONENTS python${PYTHON_VERSION_MAJOR}${PYTHON_VERSION_MINOR} CONFIG QUIET)
> if(python${PYTHON_VERSION_MAJOR}${PYTHON_VERSION_MINOR}_FOUND)
>     set(Boost_PYTHON_SUFFIX "${PYTHON_VERSION_MAJOR}${PYTHON_VERSION_MINOR}")
> else()
>     find_package(Boost COMPONENTS python${PYTHON_VERSION_MAJOR} REQUIRED)
>     set(Boost_PYTHON_SUFFIX "${PYTHON_VERSION_MAJOR}")
> endif()

Yeah this works for me (tested locally)...
However I wonder if you need to modify also cmake/make_versioncpp.py, because  at line 24 it has:
************
"boost_python%d%d" % (sys.version_info.major, sys.version_info.minor),
************
If I'm not wrong also this one should evaluate to "boost_python35" as in the CMakeLists.txt case: don't know what it happens if you don't change it though (judging by my local test of the above change: nothing...).

**Comment by geoffthemedio** [comment]
> "boost_python%d%d" % (sys.version_info.major, sys.version_info.minor),

The `required_boost_libraries` list that that is used to populate appears to only be used to [generate a Windows install script](https://github.com/freeorion/freeorion/blob/master/cmake/make_versioncpp.py#L78).

**Comment by GvMariani** [comment]
> > "boost_python%d%d" % (sys.version_info.major, sys.version_info.minor),
> 
> The `required_boost_libraries` list that that is used to populate appears to only be used to generate a Windows install script

OK. Then your proposed change is enough to fix the issue...

**Comment by geoffthemedio** [comment]
Except that it's broken when the forrmat does include the minor revision, but that should be fixable.

**Comment by hifron** [comment]
Languages and libraries develops, even Python or could in future, introduce backward incompatibilities or future incompatibility which could be undetected. Ubuntu 18.04 is last Ubuntu(unofficially, 16.04 is proper) which supports x86 architecture.

Cmake is full of bugs some unresolved some ways a lot of days... Maybe not in this case, but... Linuxes evolve currently faster and respecting its architecture is proper way to fix things... POSIX, UNIXes and such things are in backward... Even MacOS has UNIX history...

**Comment by GvMariani** [comment]
> Languages and libraries develops, even Python or could in future, introduce backward incompatibilities or future incompatibility which could be undetected. Ubuntu 18.04 is last Ubuntu(unofficially, 16.04 is proper) which supports x86 architecture.
> 
> Cmake is full of bugs some unresolved some ways a lot of days... Maybe not in this case, but... Linuxes evolve currently faster and respecting its architecture is proper way to fix things... POSIX, UNIXes and such things are in backward... Even MacOS has UNIX history...

To me your reasoning seems to go in the line of requesting boost 1.67.0 or later even if freeorion would also build with older boost releases... this is fine, since on your software you have the last word.
From my POV, though, when you don't need some specific feature from a given library release, it is better to request the lower working release, rather than the higher one only because it happened to be the one used when developing a new release.

**Comment by hifron** [comment]
If there would be more Python libraries in system(when developing for some obscure problem), app should set which to use or be bundled with it and simply call find python for boost and cmake should not fail even with such versioning used in common in Linux distributions(but there should be maybe strict policy to enforce error). But problem is that project even with that may not compile with such boost and python or have additional problems.

Problem is that developing such functionality in old cmake when there are new versions mean problems for project cmake which they MAYBE would not want to have in this case.

But even when fix is in place for cmake or linking versions of libraries in distribution(may be there even be more proper solution)(it could be distribution specific, but Ubuntu fails in this practice for various reasons(even with failing projects), but may be solution), there may be some (maybe hidden, maybe not) incompatibilities or problems with the way that libraries expects something or be compiled against(python-c++ problem). This happens sometimes during upgrades when something fails or when tweaking with libraries.

Distribution may also propose Debian solution for this problem, but also support for such distribution may decide what to do and do it after Ubuntu solution or custom development. But this could introduce problems in other projects in distribution and is distribution problem and solution.

Problem is that FreeOrion expects something from future in your distribution. It could be maybe delivered, but that is also problem in its own way as proper solution for this.

**Comment by hifron** [comment]
If there would be more Python libraries in system(when developing for some obscure problem), app should set which to use or be bundled with it and simply call find python for boost and cmake should not fail even with such versioning used in common in Linux distributions(but there should be maybe strict policy to enforce error as is currently warning with OpenGL libraries in FreeOrion project or C++ standard policy). But problem is that project even with that may not compile with such boost and python or have additional problems.

Problem is that developing such functionality in old cmake when there are new versions mean problems for project cmake which they MAYBE would not want to have in this case.

But even when fix is in place for cmake or linking versions of libraries in distribution(may be there even be more proper solution)(it could be distribution specific, but Ubuntu fails in this practice for various reasons(even with failing projects), but may be solution), there may be some (maybe hidden, maybe not) incompatibilities or problems with the way that libraries expects something or be compiled against(python-c++ inter). This happens sometimes during upgrades when something fails or when tweaking with libraries.

Distribution may also propose Debian solution for this problem, but also support for such distribution may decide what to do and do it after Ubuntu solution or custom development. But this could introduce problems in other projects in distribution and is distribution problem and solution.

Problem is that FreeOrion expects something from future in your distribution. It could be maybe delivered, but that is also problem in its own way as proper solution for this.

**Comment by Vezzra** [comment]
Has a fix been committed to master? Can this be closed? Or is a better fix than the one suggested needed?

**Comment by geoffthemedio** [comment]
> Has a fix been committed to master? Can this be closed? Or is a better fix than the one suggested needed?

no, no, and yes but I don't know the magic CMake

**Comment by Vezzra** [comment]
Okay... but it was you who suggested the fix - can't you just copy it to the proper location in our `CMakeLists.txt`...?

**Comment by geoffthemedio** [comment]
> Except that it's broken when the forrmat does include the minor revision, but that should be fixable.

**Comment by Vezzra** [comment]
Ah, ok, so the fix *does* need improvement before this issue can be considered adequately addressed...

**Comment by geoffthemedio** [comment]
@GvMariani does #3375 work for you?

**Comment by GvMariani** [comment]
> @GvMariani does #3375 work for you?

The commit won't apply cleanly to 0.4.10.1 sources, so I cannot test it directly. However it looks good to me...
I would only point out that this change is needed not "for some strange boost installations", but for compatibility with boost older than 1.67...

**Comment by o01eg** [comment]
CI uses boost 1.62 and we didn't run into this issue.

**Comment by o01eg** [comment]
@geoffthemedio I could open another PR for stable branch.

**Comment by geoffthemedio** [comment]
> @geoffthemedio I could open another PR for stable branch.

if it helps test, sure...

**Comment by o01eg** [comment]
@geoffthemedio @GvMariani  Opened https://github.com/freeorion/freeorion/pull/3376

**Comment by GvMariani** [comment]
> @geoffthemedio @GvMariani Opened #3376

This one applies and works for me...
