### ISSUE TITLE
Unexplored systems shows star type insread of unknown

### ISSUE THREAD

**Issue by o01eg** [freeorion/freeorion#3377]
Bug Report
==========

Environment
-----------

* **FreeOrion Version**: 02bef43037347a9c4624616be4a122231dc83db6
* **Operating System**: Gentoo Linux AMD64
* **Graphic card used**: NVIDIA
* **Fetched as** 
  * Compiled from source

Description
-----------

Currently unexplored systems shows star type and it becames harder to differentiate them from known but out of vision fields systems.

![fo-bug-unexplored](https://user-images.githubusercontent.com/397177/113354763-5224bd80-9348-11eb-9209-c8942f6138d8.png)

Expected Result
---------------

Server hides info of unexplored systems and they shows without known star type.

Steps to reproduce
------------------

* Start the game.

**Comment by geoffthemedio** [comment]
This is a design issue... Reason to show the star type is to guide player choice about where to explore first.

Could also be a game rule.

**Comment by o01eg** [comment]
I think it should not be some option. Currently it looks like known system without other starlines.

**Comment by o01eg** [comment]
As I understand the server sends full info about those systems even names?

**Comment by geoffthemedio** [comment]
> As I understand the server sends full info about those systems even names?

Depends what you mean by "full info about those systems".

Names are sent, and can be seen in the objects list. Contents of the system aren't sent, unless they are visible on their own. Starlanes are sent only if the other end is or has been visible.

**Comment by o01eg** [comment]
But starlanes themselves aren't universe object so server have to send `System` so client could draw starlane? What if introduce new universe object `Position` which will contain `System`, If empire don't see `System` it doesn't get it but get `Position` to draw starlanes?

**Comment by geoffthemedio** [comment]
Presumably resolved by 3afbdca450ecee64695dfab705c8659f8fb817a8
