### ISSUE TITLE
Application freeze at turn change -- "Cannot connect to server"

### ISSUE THREAD

**Issue by Thinker55** [freeorion/freeorion#3390]
Bug Report
==========

Environment
-----------

* **FreeOrion Version**:04.10+ Build 2021-03-30.02bef43
* **Operating System**:OpenSuSE LEAP 15.2 current patches.
* **Graphic card used**: ATI Radeon
* **Fetched as** 
  * Compiled from source

Description
-----------

Started on 4/4/21 in the midst of a game at over 300 turns, but on a new game after a reboot, failure also occurs
Application appears fine at screen, but upon selecting button to change turn, nothing happens.  

Following error occurs in underlying terminal session:
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
[AI_1.log](https://github.com/freeorion/freeorion/files/6259191/AI_1.log)
[AI_2.log](https://github.com/freeorion/freeorion/files/6259192/AI_2.log)
[AI_3.log](https://github.com/freeorion/freeorion/files/6259193/AI_3.log)
[AI_4.log](https://github.com/freeorion/freeorion/files/6259194/AI_4.log)
[AI_5.log](https://github.com/freeorion/freeorion/files/6259195/AI_5.log)
[AI_6.log](https://github.com/freeorion/freeorion/files/6259196/AI_6.log)
[freeorion.log](https://github.com/freeorion/freeorion/files/6259197/freeorion.log)
[freeoriond.log](https://github.com/freeorion/freeorion/files/6259198/freeoriond.log)

Expected Result
---------------

Game continues to next turn.

Steps to reproduce
------------------

* First step.  Press button to advance turn.  Everything appears fine until this is done.  As indicated, it initially occurred in the midst of a long-running game, but new games cannot move beyond Turn 1.  
* Issue occurs.

**Comment by geoffthemedio** [comment]
Guessing, but perhaps you ran once as root and it created some files which are not not writable?

I don't see anything useful in the logs you posted. Perhaps logs from an attempt to start a new game? String that it would start the game, get you into the map screen, and only then have connection problems...

**Comment by Thinker55** [comment]
I built it, I started a game, I did over 300 turns, then suddenly, I get the error.  After a reboot, the game starts, but there is no connection, so you can't move forward.  Obviously, I have network connectivity (this is the system).  It's just weird.  Suddenly, I get the server connection error, and it is there even for new games.  You start Turn 1, everything works until you hit the button, then it hangs.

**Comment by Thinker55** [comment]
If I start a game, the server error is the very first thing to show up.

annot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock

**Comment by Thinker55** [comment]
No, I never ran as root.

**Comment by geoffthemedio** [comment]
As far as I know the "jack" errors are related to some audio software or system that doesn't have anything to do with interprocess or network connectivity, despite the "server" in the error messages. See eg: the comment in [this](https://stackoverflow.com/questions/4672457/pyaudio-trying-to-use-jack).

Maybe something on your system decided to block the ports FreeOrion uses?

Defaults are 12345 and 12346 as [here](https://github.com/freeorion/freeorion/blob/master/network/Networking.cpp#L7).

Can you start freeorion, go into the options logs tab and set networking to trace, then try to start a single player game, get the error, then exit and post the resulting freeorion.log file?
![trace networking logs](https://user-images.githubusercontent.com/11386908/114100933-52333900-98c5-11eb-9041-2a301e6107c5.png)

**Comment by Thinker55** [comment]
Okay.  I don't know where to go with this.  The jack server error appears upon initialization, before the main screen even appears.  I set up the network trace and got nothing -- no log., even after doing the settings, then re-starting the game.  There is a directory there, with config files in it, but that's it.  Logging doesn't seem to work.  I went through and patched my system, put the ports in the firewall, shut down the firewall, and played with things.  I thought maybe the issue was that I had no audio set up, but I did that and audio works.   Now, however, I CAN advance turns in a game, so that piece appears to be an OS glitch on my machine.  So, to review:

Having thoroughly patched my machine (I was relying upon the online patch manager, which apparently doesn't cover EVERYTHING.) I can now advance turns in a game -- but the jack server error continues to manifest upon game initialization.
Firewall settings appear to be irrelevant.  I turned it off, I added and removed the ports -- no effect.
Sound settings also appear to be irrelevant.
Network tracing failed.  No file created.  I'm attaching the logs to see if there is anything in there that might help.  You may want to re-categorize, since the more serious issue is handled.
[freeorion.log](https://github.com/freeorion/freeorion/files/6287465/freeorion.log)
[freeoriond.log](https://github.com/freeorion/freeorion/files/6287466/freeoriond.log)

**Comment by geoffthemedio** [comment]
Setting the network log level to trace is not expected to create another file. Rather, it adds more detail to the client and server logs that are already generated.

As far as I am aware, the jack server error can be ignored, unless it has some impact on audio that particularly bothers you.

The logs you posted in the last comment appear to be from separate runs of the program, with the server after you set the network logging to trace, and then a separate later execution of the client in which you didn't start a game (nor thus the server).

If neither ther server nor client log you posted was from when there was a problem, then there's not much to look for in them.

Seems like you fixed the turn change problem by updating your system...
