### ISSUE TITLE
Option to turn off auto-centre galaxy map

### ISSUE THREAD

**Issue by magnate** [freeorion/freeorion#3398]
Feature request
===============

Idea
----
I would like to be able to click on a system or ship in the sitrep and not have the galaxy map centre on it. It can still be selected, but without moving the galaxy map. (For more sophistication you could check whether the selected object is offscreen, and move the map only if so, but I'd prefer not even that.)

Gain
----
Every game I carefully arrange my galaxy map and subwindows so I can see everything I need to see without anything important covered up or offscreen. So every time the map auto centres on something I have to move it back to my 'strategic view'.

Discussion
----------
https://www.freeorion.org/forum/viewtopic.php?f=28&t=11675

**Comment by geoffthemedio** [comment]
hopefully resolved by https://github.com/freeorion/freeorion/commit/b4250dcb81fca0171b04001ea349efcc59e3a18f
