### ISSUE TITLE
Not really okay: Translation error in fr.txt

### ISSUE THREAD

**Issue by Felecarpp** [freeorion/freeorion#3400]
Bug Report
==========
fr.txt, PRO_MICROGRAV_MAN_DESC
"Augmente la [[metertype METER_TARGET_INDUSTRY]] de [[value PRO_MICROGRAV_MAN_TARGET_INDUSTRY_FLAT]] sur toutes les colonies en Focus Recherche situées dans des systèmes abritant des colonies ou avant-postes sur une Ceinture d'Astéroïdes."
This is not the research focus but the industry focus which is improved. The correct sentence is:
"Augmente la [[metertype METER_TARGET_INDUSTRY]] de [[value PRO_MICROGRAV_MAN_TARGET_INDUSTRY_FLAT]] sur toutes les colonies en Focus Industrie situées dans des systèmes abritant des colonies ou avant-postes sur une Ceinture d'Astéroïdes."

**Comment by geoffthemedio** [comment]
Can you make a pull request to fix it?

Or @Ouaz could you check?

**Comment by Felecarpp** [comment]
Sorry I was accustomed to writes issues but if I know how to fix it, it is better to make a pull request.

**Comment by geoffthemedio** [comment]
Noting the issue withouy a pull request is still appreciated, though a pull request is better.
