### ISSUE TITLE
Precognitive Detection leads AI colony ships to reckless behavior

### ISSUE THREAD

**Issue by Morlic-fo** [freeorion/freeorion#3424]
The species effect Precognitive Detection gives basic visibility of planets even in unexplored systems.
If such a planet is found and it is suitable, the AI will attempt to colonize it. 

The issue is that the good planets are often guarded by some stationary space monster. Detecting the planet via Precognitive Detection means that the guard is not scouted, often resulting in the loss of the outpost/colony ship.

A sane behaviour would be to prioritize an exploration mission to the system of interest to check for any guards before sending in some much more expensive colony ship.

For reference:
https://github.com/freeorion/freeorion/blob/8a995e1585ef6ea410b2d4c3dcf37a438729daa8/default/scripting/species/common/telepathic.macros#L1-L13

**Comment by agrrr3** [comment]
> A sane behaviour would be to prioritize an exploration mission to the system of interest to check for any guards before sending in some much more expensive colony ship.

@Morlic-fo In-system scouting before sending a colony ship in any unexplored system is probably a good rule of thump. Not sure if that "unexplored" info is available in this case. Is that hard to do?

**Comment by Cjkjvfnby** [comment]
> The species effect Precognitive Detection 

SP_FULVER is our candidate for that.

Do we have any way to set species for AI at the game start?   

Or need to add hack into https://github.com/freeorion/freeorion/blob/2d97fa0a4e1995446db98ac48ff100f14cf7f9f9/default/python/universe_generation/empires.py#L463?

**Comment by Morlic-fo** [comment]
Probably need to hack there, yes.

Following save is a test case:
[test-fulver-suicide.zip](https://github.com/freeorion/freeorion/files/6374611/test-fulver-suicide.zip)
Relevant AI is the Zone empire in the bottom right of the map. The AI will suicide its colony ship into the Trophy Alpha system.

**Comment by geoffthemedio** [comment]
> Do we have any way to set species for AI at the game start?

Can be done when setting up a "multiplayer" game, in which you can have no human-controlled empires if desired.
