### ISSUE TITLE
Selected categories not highlighted when entering research window.

### ISSUE THREAD

**Issue by Oberlus** [freeorion/freeorion#3427]
Bug Report
==========

Environment
-----------
* **FreeOrion Version**: v0.4.10+ 6d40336
* **Operating System**: Ubuntu 18.04
* **Graphic card used**: GTX 860m
  * Compiled from source

Description
-----------
When you enter the Research Window, the buttons of the categories that are selected to be shown are not highlighted.
![after](https://user-images.githubusercontent.com/28650914/116805998-931c1780-ab2a-11eb-9092-32dd8fc0fde1.png)
If you deselect a category (to hide its techs) the button stays greyed out (as expected), and selecting it again (to show its techs) highlights the button (as expected):
![before](https://user-images.githubusercontent.com/28650914/116806055-ca8ac400-ab2a-11eb-9715-50398e443a34.png)

Expected Result
---------------
When you enter the Research Window the selected/shown categories have their button highlighted.

**Comment by Oberlus** [comment]
It is not that the button is not highlighted (i.e. just a UI issue) but that the selected categories are somehow considered not selected, and so the first time the greyed button of a selected category is pressed, the button gets highlighted and nothing else happens (there are no changes in the shown techs), and the second time you press it, the button is greyed out again and the corresponding techs are hidden.

**Comment by Vezzra** [comment]
That sounds serious and should be fixed for 0.5...

**Comment by Oberlus** [comment]
In current test build (768af09), when you click on a tech to add it to the research queue, the corresponding category button gets greyed out, and so to hide those techs before showing another category you need to click on the button twice. I didn't notice this on previous test version.

**Comment by geoffthemedio** [comment]
Fixed some time ago...
