### ISSUE TITLE
Focus selector appears on non-colonized planet

### ISSUE THREAD

**Issue by o01eg** [freeorion/freeorion#3450]
Bug Report
==========

Environment
-----------

* **FreeOrion Version**: 2021-05-10.4f04bdc
* **Operating System**: Gentoo Linux AMD64
* **Graphic card used**: NVIDIA
* **Fetched as** 
  * Compiled from source

Description
-----------

![Снимок экрана_2021-05-14_23-52-25](https://user-images.githubusercontent.com/397177/118355558-3e8c8980-b579-11eb-9928-edee9f224dbb.png)

Expected Result
---------------

No focus selector shown on non-colonized planet.

Steps to reproduce
------------------

* Place colony ship over planet.

**Comment by geoffthemedio** [comment]
There is something more specific required, or I can't reproduce...
![no_focus_colonization](https://user-images.githubusercontent.com/11386908/118394622-1028b000-b646-11eb-9f2c-f4f9fbac1b1b.png)

**Comment by o01eg** [comment]
Could not reproduce and it forgot to pinpoint turn when it happened.
