### ISSUE TITLE
game does not recognise extinction as a failure state

### ISSUE THREAD

**Issue by Moth-Tolias** [freeorion/freeorion#3452]
* **FreeOrion Version**: v0.4.10.1
* **Operating System**: ubuntu 20.10

Expected Result
---------------
having no population and no ships ends the game, and/or notifies the player they are now a spectator.

Steps to reproduce
------------------
* build an evacuation system on your homeworld
* scrap all of your ships
* set to automatically advance turns
* upon extinction, dialog boxes stating "Orders were sent for an empire this client does not control." start to appear every turn. also, it becomes impossible to turn auto-advance off.

**Comment by o01eg** [comment]
I've tried to look into it and even if I turn off auto-advance off server still advance turn for leftover AI players until host disconnect.
