### ISSUE TITLE
Propaganda Broadcast policy affects all empires' capitals.

### ISSUE THREAD

**Issue by Oberlus** [freeorion/freeorion#3456]
Bug Report
==========

Environment
-----------

* **FreeOrion Version**: 0.4.10+ 4f04bdc
  * Weekly development build

Description
-----------
The effect from policy Propaganda Broadcast from one empire does apply to the capital of all empires.
Maybe it also stacks.

Expected Result
---------------
It only affects the capital of the owner of the policy.

Steps to reproduce
------------------
I don't have a game to replicate (we spot it in current MP game).

**Comment by geoffthemedio** [comment]
fixed by https://github.com/freeorion/freeorion/commit/5f05b2b55cef5a9cbe5148ce4514bac766c2db86 more or less

**Comment by Oberlus** [comment]
> 
> 
> fixed by [5f05b2b](https://github.com/freeorion/freeorion/commit/5f05b2b55cef5a9cbe5148ce4514bac766c2db86) more or less

I love it: allies get +1, enemies get -1.
