### ISSUE TITLE
Build FreeOrion on Windows action failing

### ISSUE THREAD

**Issue by geoffthemedio** [freeorion/freeorion#3473]
As of the last day or so, the [Add msbuild to PATH step](https://github.com/freeorion/freeorion/runs/2712780401#step:4:1) of the **Build FreeOrion on Windows** GitHub action is failing: 
````
Run microsoft/setup-msbuild@v1.0.2
  with:
    vs-version: [16.0,16.10)
C:\ProgramData\Chocolatey\bin\vswhere.exe -products * -requires Microsoft.Component.MSBuild -property installationPath -latest -version [16.0,16.10)
Error: Unable to find MSBuild.
````
It [worked OK yesterday](https://github.com/freeorion/freeorion/runs/2706005398#step:4:1) and I don't think anything in the [latest master commit](https://github.com/freeorion/freeorion/commit/1c079a7f06ff94d1d62000d888f3b138211443e6) (changing stringtable) would be relevant.

**Comment by o01eg** [comment]
Should be fixed in #3472 but we get same compilation issue as g++ 11 on Windows too.
