### ISSUE TITLE
Crash when clicking on "Planet Suitability"

### ISSUE THREAD

**Issue by sevu** [freeorion/freeorion#3482]
Built from 2424a12.

Stdout / stderr displays `corrupted size vs. prev_size`.

I see two possible reasons:
* something broke recently
* compiler flag `-Ofast`

Can someone reproduce it?

**Comment by geoffthemedio** [comment]
I tried just now and got no crash. Can you elaborate / be specific about how you (re)produce the issue?

**Comment by sevu** [comment]
Can you try it with the [gamesave.sav.gz](https://github.com/freeorion/freeorion/files/6607971/gamesave.sav.gz) too? I'll make a debug build.

**Comment by geoffthemedio** [comment]
Problem is you have researched `GRO_CYBORG` but that tech was removed, and some code in the suitability generation is assuming all researched techs exist... Will [add a safety check](https://github.com/freeorion/freeorion/commit/8f9d916a4402ae8269df87f39acd7c7e3a9678f6).

**Comment by sevu** [comment]
I see … I started on my branch, then compiled master to get the fix from recently, and along that these changes. The safety check works.

**Comment by geoffthemedio** [comment]
https://github.com/freeorion/freeorion/commit/df37443ea66aafdcb59ac82806aca587cd4d52a8
