### ISSUE TITLE
Support different font directories on Linux systems

### ISSUE THREAD

**Issue by raptor** [freeorion/freeorion#349]
Many Linux distros (Fedora, Debian, openSUSE) forbid or discourage including fonts within a package and instead force or encourage you to load them from the system dir `/usr/share/fonts` and its subdirectories.  

Removing fonts from a package will introduce a problem:  the greek letters on star names disappear and it looks like there are repeated star names everywhere.

Here is a hard-coded fix that I just employed in a package:
https://build.opensuse.org/package/view_file/games/freeorion/freeorion-fontdir.diff?expand=1

**Comment by geoffthemedio** [comment]
You can already change the font file options to point to anywhere on the system, so using other font directories is already supported.

What you're proposing is to use an distro-specific file path as the default font file. That's not going to happen, and can't even be done for all Linux builds, as not all distros will use the same location or provide the same font files.

Can you remove the font files from the package and replace them with symlinks to the desired location?

Alternatively, you can put a persistent_config.xml file into ~/.freeorion/ which specifies the desired font files.

**Comment by raptor** [comment]
When you say "I can already change the font file options" do you mean in the build system?  I couldn't find a setting.  Each user will not want to do that by hand if it isn't already set up.

`/usr/share/fonts` is not very distro-specific as it's the same in all distros I've tested (so far).  However the `truetype` part may be...  I haven't checked that bit yet.

Symlinks are a good idea but are likely discouraged on some distros.  I will try and see what happens with the lint reports on mine.

A CMake option would be ideal.

**Comment by geoffthemedio** [comment]
You can create a config.xml or persistent_config.xml that specifies the font file locations.

**Comment by raptor** [comment]
Editing a config.xml seems like it is also not end-user friendly - everything should just work on first run when people install the game.

How do I do this persistent_config.xml you speak of, and how does it behave with system and end-user settings?

Thanks!

**Comment by Dilvish-fo** [comment]
> Many Linux distros (Fedora, Debian, openSUSE) forbid or discourage including fonts within a package...

I note that our Debian and Ubuntu maintainers have made no objection/request regarding this (to my recollection at least).   As for the basic 'rule', all I find for Debian is [the following](https://www.debian.org/doc/debian-policy/ch-customized-programs.html#s11.8.5) : 

> Packages that provide fonts for the X Window System[107] must do a number of things to ensure that they are both available without modification of the X or font server configuration, and that they do not corrupt files used by other font packages...[list of requirements follows].

I think that since we are not trying to insert our fonts for general use by the X Windows System, those guidelines/restrictions don't really apply to FreeOrion.

> How do I do this persistent_config.xml you speak of, and how does it behave with system and end-user settings?

persistent_config.xml is simply an optionally-present config file, which if present in your FreeOrion config folder (the same one that contains config.xml) will override any settings in config.xml.  Its xml structure is the same as for config.xml; typically you would just copy a subset of entries over, setting their values to whatever you want them to persist at.   The various situations that cause config.xml to be overwritten do not apply to persistent_config.xml; it is only changed via explicitly editing it.

**Comment by raptor** [comment]
Debian does make an objection in lintian, and I've had a package declined sponsorship because of it (and others):
https://lintian.debian.org/tags/font-in-non-font-package.html

Although that warning is lower severity than I remember a few years ago (but I may be wrong).  The non-objection in practice for Debian is probably due to the authority level of the maintainer or the popularity of the game (or both).  But it is still discouraged when packaging any piece of software.

Fedora:
https://fedoraproject.org/wiki/Packaging:FontsPolicy#Package_layout_for_fonts

openSUSE:
https://en.opensuse.org/openSUSE:Packaging_guidelines#Fonts

For the persistent_config.xml:  when you say "override", does that mean it will always be what I set it to be for end users?  Is there a way to default to a different config just on first-run and let the user keep any setting change if they so wish?

**Comment by Dilvish-fo** [comment]
> For the persistent_config.xml: when you say "override", does that mean it will always be what I set it to be for end users?

Yes, it would.  The ingame options page only modifies config.xml.

> Is there a way to default to a different config just on first-run and let the user keep any setting change if they so wish?

I would think that your the package you build could provide a version of config.xml with whatever initial-default setting you wanted, and then the user would have no trouble over-riding that.

**Comment by raptor** [comment]
In theory, upon package installation, I could iterate through all users and set-up a `config.xml` in a `$HOME/.freeorion/` folder, but that is quite cumbersome and incurs significant package maintenance overhead as the file can change from release-to-release.  It would also clutter non-players home directories.  This type of set-up is typically left to upstream.

I just tested the soft-links on openSUSE.  RPMLint didn't give any warnings, the fonts work on first install, and an end-user still can change the paths.   So this is the best workaround yet.  Thanks!

**Comment by Vezzra** [comment]
As a usable workaraound has been found, I'm closing this issue.
