### ISSUE TITLE
Document how to get policy slots

### ISSUE THREAD

**Issue by Grummel7** [freeorion/freeorion#3528]
There is no way (within the game) to quickly find out how to get additional policy slots.

**Comment by geoffthemedio** [comment]
If you'd like to write a pedia article about it, it could be added...

**Comment by Vezzra** [comment]
Would be good to have in the release...

**Comment by phocasbyz** [comment]
hello
i was going to ask for this, it will be very usefull

we are flouding with various many new policies
but is is very hazardous to get new slots to use them

**Comment by MichaelCourtney** [comment]
I can create a page with manual links for now.

What would be nice to have longer term is for EncyclopediaDetailPanel.cpp to find tags, similar to how species traits work.

Current ways to open a slot: buildings, policies, ship hull(sentient), techs

**Comment by Grummel7** [comment]
The page new page can be found under game concepts, I think that does it...
