### ISSUE TITLE
Out of sight "planet was attacked" sitrep

### ISSUE THREAD

**Issue by Oberlus** [freeorion/freeorion#3536]
Bug Report
==========

Environment
-----------
* **FreeOrion Version**: 51e34bd
* **Operating System**: Ubuntu 18.04
* **Fetched as**
  * Compiled from source

Description
-----------
Player empire is getting a "planet was attacked" sitrep for a currently out of sight planet.

![OutOfSightSitrep](https://user-images.githubusercontent.com/28650914/127983695-2df76678-1585-43bf-b1d1-6e75a81999c4.png)

Expected Result
---------------
Player only gets sitreps for visible events.

Steps to reproduce
------------------
Load attached save and press turn.

[FreeOrion_Oberlus_Abyss_0045_20210803_100022.zip](https://github.com/freeorion/freeorion/files/6922503/FreeOrion_Oberlus_Abyss_0045_20210803_100022.zip)

**Comment by geoffthemedio** [comment]
Tested with master on Windows. No such sitrep was generated...
![WFM](https://user-images.githubusercontent.com/11386908/129446858-c4f11d52-baef-4f6b-ac26-3aea519bf257.png)

**Comment by Oberlus** [comment]
I got this again.
Playing Trith with current master (8f700e9).

On turn 23 I get a planet was attacked sitrep for a far flung planet I once saw many turns ago:
![out-of-sight-planet-attack-23](https://user-images.githubusercontent.com/28650914/149139307-49db8217-b04a-4a41-a61b-7cd634d7a728.png)
Check out how it says "last seen on turn 22" (previous turn).

I reload previous turn 22:
![out-of-sight-planet-attack-22](https://user-images.githubusercontent.com/28650914/149139481-5cdeea4a-a61d-4c2a-90ab-376903b59a42.png)
There was no allied vision nearby that planet, plus notice that UI now says "last scanned on turn 13"

I reload turn 21:
![out-of-sight-planet-attack-21](https://user-images.githubusercontent.com/28650914/149139765-f0ee0d3b-f497-434e-a27f-0755d44f0ff2.png)
Still nothing mine nearby that planet, plus now UI says "last seen on turn 20". But it will say "turn 13" next turn, which appears incoherent.
No sitreps of combat for that planet before turn 23.

Maybe this has something to do with Trith having Telepathic Detection and is not a bug?

I attach saves for turns 21-23 and logs for 23.
[out-of-sight-planet-attack-sitrep.zip](https://github.com/freeorion/freeorion/files/7854522/out-of-sight-planet-attack-sitrep.zip)

**Comment by agrrr3** [comment]
I think telepathic vision makes sense. VIS_BASIC_VISIBILITY is enough for the combat report sitrep.
So my guess is that you had a trith ship in 5-jump range on turn 22. 

The confusing messages I would interpret as: you have been to the system in turn 13. you had basic visibility in turns 20 and 22, but not in 21 and 23(?)

@geoffthemedio Maybe we should at least require partial visibility?

**Comment by Oberlus** [comment]
If this is just about Telepathic Detection (and Precognitive Detection I guess), I think it's OK to leave it with VIS_BASIC_VISIBLITY. It makes a lot of sense that TelePathic beings are able to sense people's distress under attack.
We would just need to improve some documentation to avoid player's confusion.
The only documentation for this two species traits are the oneliners shown in the species descriptions. I don't know what would be better: replace "Telepathic Detection: can sense nearby populated planets." by something like "Telepathic Detection: can sense nearby populated planets (including when they are attacked)", or maybe better add a Pedia page about Visibility where visibility levels are explained and these two species traits are mentioned.

**Comment by MichaelCourtney** [comment]
![unexplored](https://user-images.githubusercontent.com/43386669/186692774-95457523-18aa-449e-b4de-e66a4bcff9b5.png)

Fulver

**Comment by geoffthemedio** [comment]
try with https://github.com/freeorion/freeorion/pull/4188/commits/106a5ffa64d17af831e9a0134b02c3e5b77f05e9 ?

**Comment by geoffthemedio** [comment]
hopefully fixed by https://github.com/freeorion/freeorion/commit/df536aa9c6c6606f280e7bd09e024c57731e6a6f
