### ISSUE TITLE
V 0.5 Policy Metropoles (ECO)

### ISSUE THREAD

**Issue by phocasbyz** [freeorion/freeorion#3539]
i've only 4 planets and 1 outpost on a fresh game (turn 50)
i selected 3 policies
-planetary infrastructure
-colonial bootstrapping
-metropoles

and get a -5 stability on all the 3 colony planets (except capital)

the pedia says he 6 high-pop planets  get several bonus and that the others planets get -5 stability

i understand the 6 first planets should be the 6 high-pop and then should have all the bonus and no stability malus

i can see several bonus on the capital
-research
-industry
-infrastucture
- supply   (!! +2 bonus and no -2 malus as showed in the pedia)

the 3 colony planets have no bonus at all
- no malus -2 on supply
- -5 malus on stability

Environment
-----------
Xubuntu 21.04

 » Thu Aug 05, 2021 4:08 pm
Uploaded version 2021-08-02.51e34bd to ppa:o01eg/freeorion.

Description
-----------
from freeorion.log
>>>
22:47:36.637765 {0x00007fd29328c800} [debug] timer : ScopedTimer.cpp:258 : Effect TargetSets Evaluation - reordering      time:      173 µs
22:47:36.637774 {0x00007fd29328c800} [debug] timer : ScopedTimer.cpp:268 : Effect TargetSets Evaluation                   time:     3553 µs
22:47:54.327904 {0x00007fd29328c800} [warn] client : NamedValueRefManager.h:265 : NamedValueRefManager::GetValueRef found no registered double valueref for "METROPOLES_PLANET_LIMIT". This should not happen once "#3225 Refactor initialisation of invariants in value refs to happen after parsing" is implemented
22:47:54.329105 {0x00007fd29328c800} [warn] client : NamedValueRefManager.h:265 : NamedValueRefManager::GetValueRef found no registered double valueref for "METROPOLES_PLANET_LIMIT". This should not happen once "#3225 Refactor initialisation of invariants in value refs to happen after parsing" is implemented
22:47:54.330258 {0x00007fd29328c800} [warn] client : NamedValueRefManager.h:265 : NamedValueRefManager::GetValueRef found no registered double valueref for "METROPOLES_PLANET_LIMIT". This should not happen once "#3225 Refactor initialisation of invariants in value refs to happen after parsing" is implemented
22:47:54.331636 {0x00007fd29328c800} [warn] client : NamedValueRefManager.h:265 : NamedValueRefManager::GetValueRef found no registered double valueref for "METROPOLES_PLANET_LIMIT". This should not happen once "#3225 Refactor initialisation of invariants in value refs to happen after parsing" is implemented
22:47:54.332906 {0x00007fd29328c800} [warn] client : NamedValueRefManager.h:265 : NamedValueRefManager::GetValueRef found no registered double valueref for "METROPOLES_PLANET_LIMIT". This should not happen once "#3225 Refactor initialisation of invariants in value refs to happen after parsing" is implemented
22:47:54.334383 {0x00007fd29328c800} [warn] client : NamedValueRefManager.h:265 : NamedValueRefManager::GetValueRef found no registered double valueref for "METROPOLES_PLANET_LIMIT". This should not happen once "#3225 Refactor initialisation of invariants in value refs to happen after parsing" is implemented
22:47:54.335673 {0x00007fd29328c800} [warn] client : NamedValueRefManager.h:265 : NamedValueRefManager::GetValueRef found no registered double valueref for "METROPOLES_PLANET_LIMIT". This should not happen once "#3225 Refactor initialisation of invariants in value refs to happen after parsing" is implemented
22:47:54.948980 {0x00007fd29328c800} [warn] client : NamedValueRefManager.h:265 : NamedValueRefManager::GetValueRef found no registered double valueref for "METROPOLES_PLANET_LIMIT". This should not happen once "#3225 Refactor initialisation of invariants in value refs to happen after parsing" is implemented
22:47:54.965482 {0x00007fd29328c800} [warn] client : NamedValueRefManager.h:265 : NamedValueRefManager::GetValueRef found no registered double valueref for "METROPOLES_PLANET_LIMIT". This should not happen once "#3225 Refactor initialisation of invariants in value refs to happen after parsing" is implemented
22:47:54.981934 {0x00007fd29328c800} [warn] client : NamedValueRefManager.h:265 : NamedValueRefManager::GetValueRef found no registered double valueref for "METROPOLES_PLANET_LIMIT". This should not happen once "#3225 Refactor initialisation of invariants in value refs to happen after parsing" is implemented
22:47:54.999241 {0x00007fd29328c800} [warn] client : NamedValueRefManager.h:265 : NamedValueRefManager::GetValueRef found no registered double valueref for "METROPOLES_PLANET_LIMIT". This should not happen once "#3225 Refactor initialisation of invariants in value refs to happen after parsing" is implemented
22:47:55.048667 {0x00007fd29328c800} [warn] client : NamedValueRefManager.h:265 : NamedValueRefManager::GetValueRef found no registered double valueref for "METROPOLES_PLANET_LIMIT". This should not happen once "#3225 Refactor initialisation of invariants in value refs to happen after parsing" is implemented
22:48:00.698194 {0x00007fd29328c800} [warn] client : NamedValueRefManager.h:265 : NamedValueRefManager::GetValueRef found no registered double valueref for "METROPOLES_PLANET_LIMIT". This should not happen once "#3225 Refactor initialisation of invariants in value refs to happen after parsing" is implemented
22:48:00.714674 {0x00007fd29328c800} [warn] client : NamedValueRefManager.h:265 : NamedValueRefManager::GetValueRef found no registered double valueref for "METROPOLES_PLANET_LIMIT". This should not happen once "#3225 Refactor initialisation of invariants in value refs to happen after parsing" is implemented
22:48:03.029161 {0x00007fd29328c800} [warn] client : NamedValueRefManager.h:265 : NamedValueRefManager::GetValueRef found no registered double valueref for "METROPOLES_PLANET_LIMIT". This should not happen once "#3225 Refactor initialisation of invariants in value refs to happen after parsing" is implemented
22:48:23.170285 {0x00007fd29328c800} [debug] client : GGHumanClientApp.cpp:1114 : GGHumanClientApp::HandleFocusChange(Lost Focus)
22:48:35.565999 {0x00007fd29328c800} [debug] client : GGHumanClientApp.cpp:1114 : GGHumanClientApp::HandleFocusChange(Gained Focus)
22:48:37.011366 {0x00007fd29328c800} [warn] client : NamedValueRefManager.h:265 : NamedValueRefManager::GetValueRef found no registered double valueref for "METROPOLES_PLANET_LIMIT". This should not happen once "#3225 Refactor initialisation of invariants in value refs to happen after parsing" is implemented
22:48:42.970741 {0x00007fd29328c800} [debug] client : GGHumanClientApp.cpp:1114 : GGHumanClientApp::HandleFocusChange(Lost Focus)
22:49:24.044401 {0x00007fd29328c800} [debug] client : GGHumanClientApp.cpp:1114 : GGHumanClientApp::HandleFocusChange(Gained Focus)
22:49:37.884970 {0x00007fd29328c800} [debug] client : Universe.cpp:850 : UpdateMeterEstimatesImpl on 8 objects
22:49:37.891087 {0x00007fd29328c800} [debug] timer : ScopedTimer.cpp:258 : Effect TargetSets Evaluation - species         time:     1658 µs

Expected Result
---------------
according to pedia

should have bonus on 5 colony planets
-research
-industry
-infrastucture
- supply   (!! +2 bonus and no -2 malus as showed in the pedia)

Steps to reproduce
------------------
always

**Comment by geoffthemedio** [comment]
There's also a requirement that the planets that get the bonus need to have at least 20 population, which isn't mentioned in the description. It's meant for "tall" empires, not just small ones.

The -2 would actually apply to stockpiling, not supply.

**Comment by phocasbyz** [comment]
thanks
yes my capital is above 20 pop and raised the bonus
ok, i can understand no bonus if low population  and missing some text in the pedia

if i understand from your comments it seems working like
- if < 20 pop then malus -5
- if >=20 pop 
-       if  number <= 6  then bonus
-       else malus -5

 -5 malus on all other planets when you have not raised the 6x  bonus on the big planets, it's a heavy cost



from the pedia i understand it worked like
>>>
if planet.pop.20[1-6] then bonus+1

if 6 bonus raided then malus on others
(so no malus il less than 6 bonus raised)

**Comment by geoffthemedio** [comment]
> -5 malus on all other planets when you have not raised the 6x bonus on the big planets, it's a heavy cost

If you don't have a few planets with 20+ population, it doesn't make much sense to adopt the policy.

**Comment by geoffthemedio** [comment]
Hopefully fixed by https://github.com/freeorion/freeorion/commit/2fbb8f0171f304b3131f1bd998d49523bcf1ede5
