### ISSUE TITLE
Mention Flathub for new release announcements on the website

### ISSUE THREAD

**Issue by travier** [freeorion/freeorion#3547]
Could you mention the Flathub package in new release announcements on the website alongside the snap package for Linux users?

Thanks!

**Comment by geoffthemedio** [comment]
@Vezzra is that something you'd deal with?

**Comment by Vezzra** [comment]
@travier: I see no problem with that, as long as someone provides a link I can post in the news section.

**Comment by travier** [comment]
Thanks! Here is the link to FreeOrion on Flathub: https://flathub.org/apps/details/org.freeorion.FreeOrion (same as the one in the README). I usually update a couple of days after each release.

**Comment by Vezzra** [comment]
[Done](https://freeorion.org/index.php/Main_Page)

**Comment by travier** [comment]
Thanks!
