### ISSUE TITLE
Crash to desktop when checking planet suitability ("Invalid UTF-8")

### ISSUE THREAD

**Issue by Oberlus** [freeorion/freeorion#3557]
Bug Report
==========

Environment
-----------
* **FreeOrion Version**: 2021-09-06.32fed9e_Test_Win32
* **Operating System**: Windows 8.1
  * Weekly development build

Description
-----------
Right-clicking on a planet and then clicking on planet suitability sometimes crashes client to desktop.
I tried four games, in two of those the crash happened on first try to check a planet suitability (other than capital, which didn't trigger the crash for me), on the other two games I needed to check out more planets. It always took less than five turns of game.

Steps to reproduce
------------------
* Start a game and explore the galaxy.
* Try to check out planet suitability of uncolonized planets until bug happens.

[freeorion.log](https://github.com/freeorion/freeorion/files/7135164/freeorion.log)
[freeoriond.log](https://github.com/freeorion/freeorion/files/7135165/freeoriond.log)

**Comment by geoffthemedio** [comment]
Is it a particular planet you can reproduce the issue with in a test save, or any planet randomly?

Can you reproduce it with trace level logging enabled (just set in the client right before producing the crash)?

**Comment by Oberlus** [comment]
It's is somewhat random. When a crash happens and I restart FO and reload last save, the same planet that caused the crash might not do it again.
Let's see if this logs are enough (I didn't set everything to trace, e.g. I left combat, ai, server, and some others as debug).
In this case the crash happened in turn 1 after checking planet suitability of capital world before doing anything else (lucky).


[freeorion.log](https://github.com/freeorion/freeorion/files/7135671/freeorion.log)
[freeoriond.zip](https://github.com/freeorion/freeorion/files/7135672/freeoriond.zip)

**Comment by geoffthemedio** [comment]
The log helps narrow down the location of the exception a bit, after `Suitability report env image` appears in the `TraceLogger()` call, but I can't tell exactly where beyond that.

Maybe it's related to https://github.com/freeorion/freeorion/commit/fcc7df34be212cec6e95824a1a2b2c7570f53df2 ?

**Comment by geoffthemedio** [comment]
Can you compile to test changes or debug stuff?

**Comment by Oberlus** [comment]
> Can you compile to test changes or debug stuff?

Not in windows. And in Linux I don't have the trouble. If convenient, I have no trouble waiting until next test release.

**Comment by geoffthemedio** [comment]
Linux strings are already UTF8, unlike Windows that uses UTF-16 when interacting with the OS filesystem, which can lead to problems when constucting a string with bit of pathes from the filesystem library, particularly if you have any characters in the pathes the game accesses that have characters in them that don't fit in a single-byte UTF-8 representation.

**Comment by Oberlus** [comment]
> Maybe it's related to [fcc7df3](https://github.com/freeorion/freeorion/commit/fcc7df34be212cec6e95824a1a2b2c7570f53df2) ?

Maybe. The previous test version (that doesn't have that commit) runs OK and I can check out planet suitability in every planet with no problems.

> particularly if you have any characters in the pathes the game accesses that have characters in them that don't fit in a single-byte UTF-8 representation.

I don't know if I have such characters in the pathes. All pathes are the ones set by default during installation. Program is installed in "C:\Archivos de Programa (x86)\FreeOrion", and saves and whatnot are in "C:\Usuarios\L\AppData\Roaming\FreeOrion".

**Comment by geoffthemedio** [comment]
> Program is installed in "C:\Archivos de Programa (x86)\FreeOrion", and saves and whatnot are in "C:\Usuarios\L\AppData\Roaming\FreeOrion"

Looks like only single byte characters to me.

**Comment by Oberlus** [comment]
With latest test version (d918658) I no longer get crash to desktop when checking planet suitability, but the window no longer gives me info on target population of empire species. See the attached screenshot.
![NoSuitabilityInfo](https://user-images.githubusercontent.com/28650914/133455778-06bcee2a-f424-4458-b61e-d090377ef28f.png)

**Comment by geoffthemedio** [comment]
I wrapped the code that generates the report in a try-catch block. There's probably a line in the client log containing `"Caught exception generating planet suitability info:` and then some stuff about invalid UTF-8

**Comment by Oberlus** [comment]
Log for starting a new game and checking planet suitability of a planet in home system. All log sets to trace.
[freeorion.log](https://github.com/freeorion/freeorion/files/7173587/freeorion.log)

If the log for the server is needed, please let me know what debug options can be set to debug instead of trace because it is huge.

**Comment by Oberlus** [comment]
Attached logs for current test version. Now client crashes (again), and last line of client log is this:

> encyclopediadetailpanel.cpp:2966 : Caught exception in HairSpaceExtext parsing or determining lines: Invalid UTF-8

[freeorion.log](https://github.com/freeorion/freeorion/files/7205646/freeorion.log)
[freeoriond.zip](https://github.com/freeorion/freeorion/files/7205647/freeoriond.zip)

**Comment by Oberlus** [comment]
With current test version f3abe16 I no longer get crashes when clicking on planet suitability and the info is displayed properly.
I guess I can close this?

**Comment by geoffthemedio** [comment]
some logs from right after displaying planet suitability would still be helpful...

**Comment by Oberlus** [comment]
Sure. Logs from quickstarting a game and checking homeworld suitability:

[freeorion.log](https://github.com/freeorion/freeorion/files/7257847/freeorion.log)
[freeoriond.zip](https://github.com/freeorion/freeorion/files/7257849/freeoriond.zip)

**Comment by geoffthemedio** [comment]
Guess it's OK then...
