### ISSUE TITLE
Snap Build CI Fails

### ISSUE THREAD

**Issue by geoffthemedio** [freeorion/freeorion#3562]
https://github.com/freeorion/freeorion/runs/3628886285

There's nothing in the logs, just several steps with "Error:".

It doesn't appear to be related to any change in the FreeOrion repository itself...

@o01eg any ideas?

**Comment by hifron** [comment]
According to https://github.com/snapcore/action-build/commits/master and e8af0bdc2112285c263cca7f03526b20f74dbff3 tools: do not fail if LXD snap cannot be refreshed
and next commits from 17.9.2021 seems as infrastructure upgrade.

**Comment by o01eg** [comment]
@geoffthemedio Looks like it was fixed. https://github.com/freeorion/freeorion/runs/3698075344
