### ISSUE TITLE
Wrong fleet icons in fleet list and on map [build 2021-09-12.d918658] (snap 237)

### ISSUE THREAD

**Issue by NickDToth** [freeorion/freeorion#3563]
Environment
-----------
* **FreeOrion Version**: 4.10+ [build 2021-09-12.d918658]
* **Operating System**: Ubuntu 16.04 (not that it matters for this bug)
* **Fetched as**
  * Weekly development build (Snap 237)

Description
-----------

Every non-monster fleet type except a pure colony fleet shows the outpost fleet icon. Scouts do not show the scout icon ever.

Some screenshots showing scout, troop, battle, and colony fleets, all with outpost fleet icons except the colony fleet:

https://drive.google.com/file/d/1oFDyNFKituraTVM0v67wAtnqMVUQN4Gd/view?usp=sharing
https://drive.google.com/file/d/1cKDkEChH2KvJHRx1xi-bZ8ZsOPa0GypW/view?usp=sharing

I first noticed this when re-opening a saved game from before the snap upgrade, but it happens in new games and is consistent across zooming and restarting, etc.

Cause
-----------

I went for a hunt in the C code and I think I know why this is happening, so please enjoy the prospect of a bug report with a possible solution?

In https://github.com/freeorion/freeorion/blob/weekly-test-builds/universe/Fleet.cpp , HasOutpostShips() returns true for every ship that is not a colony ship because the test on line 703 returns true for every ship with zero colonising capacity:

```
700 bool Fleet::HasOutpostShips(const Universe& universe) const {
.       auto isX = [&universe](const std::shared_ptr<const Ship>& ship) {
.           if (const auto design = universe.GetShipDesign(ship->DesignID()))
703             if (design->ColonyCapacity() == 0.0f)
.                   return true;
.           return false;
.       };
.       return HasXShips(isX, m_ships, universe.Objects());
708 }
```

I note that you changed the source of your information from ShipDesign:: to universe:: in this update. Could it be that ColonyCapacity() or its previous equivalent used to return NUL or <0 for ships with no colony parts, but now returns 0.0 and thus requires an explicit extra check for colony parts with zero colonists?

This explains why colony fleets don't get outpost ship icons: with ColonyCapacity()>0.0, they are the only type to fail the HasOutPostShips() current criteria.

For bonus points, the scout ships don't show the scout icon at all because the scout icon is only displayed if a fleet has absolutely no other kinds of ships in it, and since all fleets are at the minimum reported to be either colony or outpost fleets, all fleets fail this fallback test, which occurs in https://github.com/freeorion/freeorion/blob/weekly-test-builds/UI/FleetButton.cpp, in FleetHeadIcons(), lines 458-467

```
458     if (hasMonsters) {
.           if (canDamageShips)   { main_filenames.emplace_back(size_prefix + "head-monster.png"); }
.           else                 { main_filenames.emplace_back(size_prefix + "head-monster-harmless.png"); }
.       } else {
.           if (canDamageShips)   { main_filenames.emplace_back(size_prefix + "head-warship.png"); }
.           if (hasColonyShips)  { main_filenames.emplace_back(size_prefix + "head-colony.png");  }
.           if (hasOutpostShips) { main_filenames.emplace_back(size_prefix + "head-outpost.png"); }
.           if (hasTroopShips)   { main_filenames.emplace_back(size_prefix + "head-lander.png");  }
.       }
467     if (main_filenames.empty()) { main_filenames.emplace_back(size_prefix + "head-scout.png"); }
```

I hope this is an easy fix for whoever and that I can get back to seeing my scouts and battle fleets rendered in their gloriously aggressive pointiness!

**Comment by geoffthemedio** [comment]
hopefully fixed... https://github.com/freeorion/freeorion/commit/f44373819bbcf84830c10a538df288f8a0da5e28#diff-e962bd93eb7005ac25812d6d0c4ded3cd2be4e2fe4b0a0e60f5e67078eebd55b
