### ISSUE TITLE
Outpost Base ship crash client when enqueued

### ISSUE THREAD

**Issue by o01eg** [freeorion/freeorion#3566]
Bug Report
==========

Environment
-----------

* **FreeOrion Version**: 2021-09-27.f3abe16
* **Operating System**: Linux
* **Graphic card used**: NVIDIA
* **Fetched as** 
  * Compiled from source

Description
-----------

When I try to enqueue Outpost Base client crashes with 
```
terminate called after throwing an instance of 'std::invalid_argument'
  what():  Attempted to construct a Ship with an invalid design id
```

Expected Result
---------------
Outpost Base enqueued in Production Queue

Steps to reproduce
------------------

* Start the game
* Open production on home planet.
* Enqueue Outpost Base.

**Comment by geoffthemedio** [comment]
probly due to https://github.com/freeorion/freeorion/commit/1063350b6216d95a830afd6e559f75ba693d3b47#r56321718

**Comment by geoffthemedio** [comment]
https://github.com/freeorion/freeorion/commit/a7bcaec4fea4fe59c95f1802f7ba65713751edb5
