### ISSUE TITLE
Check if mine techs are applied correctly/consistently to space monsters 

### ISSUE THREAD

**Issue by Vezzra** [freeorion/freeorion#360]
Brought up here: http://www.freeorion.org/forum/viewtopic.php?p=80779#p80779

Created an issue so we do not forget to do that check eventually.

**Comment by aschuch247** [comment]
I am running master (79d169fd21ca02bdb780557c5da9c18055fcae71).

A Small Krill Swarm is wandering around in my empire. I already have Mines 2. The structure is down to 0 already, but it still does not die. I've seen a Medium Krill Swarm dying from Mines.

My guess is that there is something special for the condition that a monster has zero attack, like the Small Krill Swarm does?

**Comment by Dilvish-fo** [comment]
The clause that destroys ships from mines is distinct from the one that damages; I expect the former is probably not covering monsters at all, and that the Medium Krill you say die was actually killed off in the combat process (even if mines had already reduced its structure to zero)
