### ISSUE TITLE
Incorrect effect string

### ISSUE THREAD

**Issue by o01eg** [freeorion/freeorion#3603]
Bug Report
==========

Environment
-----------

* **FreeOrion Version**: 2021-11-16.6c3d9f1
* **Operating System**: Linux
* **Graphic card used**: Intel
* **Fetched as** 
  * Compiled from source

Description
-----------

Effects related to policies incorrectly displays in effects windows.
![Снимок экрана_2021-11-18_21-23-57](https://user-images.githubusercontent.com/397177/142476674-cf9d5031-6d6f-4b27-a7be-8a32403e990b.png)

Expected Result
---------------

Correct string

Steps to reproduce
------------------

* Load save as `Ophiuchus`
[FreeOrion_0009_20211118_180937.mps.zip](https://github.com/freeorion/freeorion/files/7565258/FreeOrion_0009_20211118_180937.mps.zip)
 * Set all other players as AI
 * Start the game
 * Check `Troika δ I` Research and Industry

**Comment by geoffthemedio** [comment]
Presumably related to https://github.com/freeorion/freeorion/commit/be6da52bfb5fa7f4ff0a53ebde5dd38169480a59 
@agrrr3

maybe https://github.com/freeorion/freeorion/commit/2834459e83f62131639a296c56ac26e7321edc9c helps?

**Comment by agrrr3** [comment]
@geoffthemedio I rather guess the issue main issue is of effect strings - and maybe related to switching from strings to string_views?

regarding the AI issue, 2834459 looks good to me. the lance has no upgrades. and policies are not yet supported
(probably i should check if the AI needs tech and hull support as well)

**Comment by geoffthemedio** [comment]
Ah, there are two issues? I'm was confused by the description, but thought the point was the AI error.

**Comment by geoffthemedio** [comment]
I can't reproduce the tooltip truncated building name issue.

**Comment by o01eg** [comment]
AI errors was because I loaded game locally and replace players with AI.

**Comment by agrrr3** [comment]
I see that error also in single player games quite often. Just checking the mouseovers of stability, industry, research. This comes and goes, so does not seem persistent. Maybe only on linux?

**Comment by o01eg** [comment]
Save opens correctly on 0da0365d976d4abe6a948ae77b4ce290c4e6acab

**Comment by geoffthemedio** [comment]
after looking into it a bit more, it seems likely related to https://github.com/freeorion/freeorion/commit/6c3d9f171438dde5a55fa7ae760595baaf231ea9#r60454299 and thus https://github.com/freeorion/freeorion/commit/bca4d0da23a0bbbbee53a2b279a2222892110f74#diff-cf095cbb164a7dd95b9160ae6f70ea483c1ffb7fa5230c1bb104ce12e1e1b6a9
