### ISSUE TITLE
Experience

### ISSUE THREAD

**Issue by neko259** [freeorion/freeorion#361]
This is a feature request.
I think ship crew experience and/or planet population experience can be added. Crew expecience can influence attack and defence chance (e.g. take some random % less damage which grown with experience). Planet experience (raised by the colony age and defending from enemies) can increase production time or other things. This can be turned on/off before game creation.
There is a similar feature in Sins of a Solar Empire game, but there it only applies to large ships (no such concept in freeorion yet).

**Comment by geoffthemedio** [comment]
This is a combination of several very complicated and design-heavy ideas, which really need to be discussed on the forums first.
