### ISSUE TITLE
Crash when adding column to list of planets window

### ISSUE THREAD

**Issue by DarthGandalf** [freeorion/freeorion#3626]
Bug Report
==========

Segfault when adding column "supply distance"

Environment
-----------

* **FreeOrion Version**: FreeOrion Human Client v0.4.10+ HEAD [build 2021-12-26.a7e5d21] CMake
* **Operating System**: Gentoo Linux amd64
* **Graphic card used**: GeForce RTX 2070 S, with nouveau driver
* **Fetched as** 
  * Compiled from source (via `games-strategy/freeorion-9999` gentoo package)

Description
-----------

![Выделение_395](https://user-images.githubusercontent.com/325092/147411425-f4a23878-07a6-4e62-996b-023b803e61ef.png)

[freeorion.log](https://github.com/freeorion/freeorion/files/7777104/freeorion.log)

stacktrace: [gdb.txt](https://github.com/freeorion/freeorion/files/7777103/gdb.txt)

Expected Result
---------------

It should add the new column and not crash

Steps to reproduce
------------------

* Launch the game
* Open list of planets
* Increase size of window to see the empty columns on the right
* Right-click an empty column header
* Add "supply distance" column

**Comment by hifron** [comment]
On Gentoo there is a lot of crashes due to various flags options during compiling system... Maybe unrelated to this problem...

**Comment by DarthGandalf** [comment]
Sorry, but using Gentoo doesn't automatically mean using crazy compiler flags.

`-O2 -pipe -march=znver2 -ggdb3 -frecord-gcc-switches`

**Comment by hifron** [comment]
FreeOrion also uses OpenGL 2.1 and there are some policies and warnings with that with cmake compilation and maybe nouveau open source nVidia driver is some hidden problem(such new graphic may not be tested such well as official nVidia driver with older OpenGL versions and OpenGL has also strict and compatible modes)... A lot of another problems possible... But maybe bug is elsewhere...

**Comment by geoffthemedio** [comment]
Investigating this lead me to [fix a use-after-move issue](https://github.com/freeorion/freeorion/commit/ada13db48a783addcd3e44f8a9e385e08a6a1984), but I don't think that was related to your issue. Would you be able to edit the source and recompile to test, since I can't replicate it myself?

**Comment by DarthGandalf** [comment]
By editing the source you mean just updating to latest master? Sure, updated to 4ca1eca

But it still crashes when I try to add that column

**Comment by geoffthemedio** [comment]
I mean changing the source by hand to add some additional debug output as I will suggest, or checking out a branch that does so.

**Comment by DarthGandalf** [comment]
Yes, of course, I can do that

I thought you meant replicating the fix you did to test whether it works with it (by editing the source and applying that patch)

**Comment by DarthGandalf** [comment]
A custom branch in a custom repo will probably be easier than telling "add this line to this line at this file"

**Comment by geoffthemedio** [comment]
> I thought you meant replicating the fix you did to test whether it works

I don't know how to fix it, as I can't tell from the (otherwise quite nice) stack trace you posted or the log what the cause is. So I would start with a bunch of debugging logging to see if I can figure out what's going wrong.

**Comment by geoffthemedio** [comment]
Can you check with https://github.com/freeorion/freeorion/commit/ee5067ef660cfe588cf84651d4a434a9d638535e applied?

https://github.com/freeorion/freeorion/commits/testfix_complexVariable_double_eval

**Comment by DarthGandalf** [comment]
That branch doesn't crash!
