### ISSUE TITLE
Blank space after pages in pedia (can hide text too)

### ISSUE THREAD

**Issue by Szunti** [freeorion/freeorion#366]
I see it on every page.

![freeorion-pedia](https://cloud.githubusercontent.com/assets/1443881/10218722/462980a0-6839-11e5-9be4-75a246be53c0.png)

**Comment by geoffthemedio** [comment]
As noted here: http://www.freeorion.org/forum/viewtopic.php?p=81010#p81010

**Comment by Szunti** [comment]
Read that, but thought it's better to have an issue. (I don't know if you meant this too with the might be fixed. It isn't, I have the master)

**Comment by geoffthemedio** [comment]
No, I was just referring to the UI-wide flickers and cursor issues.

**Comment by Szunti** [comment]
SitRep can have similar things at some sizes too.

![freeorion-sitrep-blank](https://cloud.githubusercontent.com/assets/1443881/10220704/b7b9367e-6849-11e5-8479-8c1848d00d47.png)

**Comment by geoffthemedio** [comment]
Tweaked the sitrep list layout a bit more.

If you dislike the space existing for the scroll bars, that's a design issue. The current behaviour is consistent with, for example, the fleets / ships lists.
