### ISSUE TITLE
Integer number shown with scientific notation in sitrep

### ISSUE THREAD

**Issue by Oberlus** [freeorion/freeorion#3662]
Bug Report
==========

Environment
-----------
* **FreeOrion Version**: 8f700e9
* **Operating System**: Ubuntu 18.04
* **Fetched as**
  * Compiled from source

Description
-----------
Sitrep for foreign empire detection strength upgraded shows "30" as "3e+01":
![scientific-notation-for-integer-sitrep](https://user-images.githubusercontent.com/28650914/149181155-ee9cd1bf-cb23-4302-9664-4a06f2188eea.png)

Expected Result
---------------
Numbers are shown as integer or fractional when appropriate.

Steps to reproduce
------------------
Quickstart a game, advance turn until an AI player researches Active Radar and the sitrep is generated.

**Comment by geoffthemedio** [comment]
should be fixed by https://github.com/freeorion/freeorion/commit/3a5ea465dd20c6e8163869c3d7e5b379053c3bbe
