### ISSUE TITLE
Huge memory usage while playing FO (not about compilation)

### ISSUE THREAD

**Issue by Oberlus** [freeorion/freeorion#3663]
Bug Report
==========

Environment
-----------
* **FreeOrion Version**: 8f700e9
* **Operating System**: Ubuntu 18.04
* **Graphic card used**: GeForce GTX 860 M
* **Fetched as**
  * Compiled from source

Description
-----------
After playing some 30 turns (but a couple of hours counting AFK time) in a game against 6 AIs, the UI began to be sluggish, mouse pointer refreshing every now and then (less than 5 times per second), and getting worse with more turns.
I opened system monitor and saw nearly 100% RAM usage (of available 8.2 GB) plus 0.7 GB or disc swap. Exited and RAM usage went down to 22% (swap down to 570 MB). FO was taking more than 6 GB in a game at turn 40, and increasing.
Notice the steep reduction in memory usage at -15 sec (I exited FO at -22, but took some time to save game): 
![HugeMemUsageFO](https://user-images.githubusercontent.com/28650914/149191905-a6dc0316-0bee-47f3-ab78-6c524e54ae61.png)

Maybe this is related to the crashes in Windows, if both are about leaking memory.

Expected Result
---------------
I can't remember what was typical memory usage with older versions, but I never had this problem before, playing in this same machine.

Steps to reproduce
------------------
Quickstart a game, check out memory usage. Advance a few tens of turns and check out memory usage. Maybe wait an hour with the window minimized and check out memory usage.

**Comment by geoffthemedio** [comment]
Can you find a version when it started happening? Perhaps looking around the same time as the versions mentioned here: https://freeorion.org/forum/viewtopic.php?p=109160#p109160

**Comment by Oberlus** [comment]
I have compiled and playtested fb38731 and ff62820. In both cases I quickstarted a game and let it auto turn for more than an hour and more than 350 turns, and memory usage was always under 3.3 GB (so FO was taking ~1.4 GB). I'll try a bisect.

**Comment by MichaelCourtney** [comment]
When I was trying to find which commit was giving me trouble there was a huge slow down in loadtime somewhere after ee412229 and before 0a71f9c

**Comment by Oberlus** [comment]
I did a git bisect between ff62820 and 8f700e9. All were good. I recompiled master (8f700e9) and I got no memory problems for a quickstart game for 30' and 200+ turns (sometimes I stopped it to open and close windows randomly, but did little actual playing). Memory usage was below 37% after an hour of autoturning and 400 turns. I don't know what was wrong for me first time, but I cannot reproduce. I'll keep an eye on this, but this can be closed.

**Comment by freddyhayward** [comment]
How much did you 'play' vs autoturn in each test case? I have found that without establishing any colonies, memory won't exceed ~2GB, whereas if I continually found colonies, I consume over 9GB.

**Comment by freddyhayward** [comment]
By turn 13 of a super-testers game (no AIs, no natives, cheap & fast everything) with 90+ colonies, memory usage reaches 11GB. After restarting the game and reloading the save, usage is 108MB. With no actions or turns, memory usage increases by about 1MB/sec, so that 5 minutes later memory usage exeeds 300MB.

**Comment by geoffthemedio** [comment]
> Can you find a version when it started happening? Perhaps looking around the same time as the versions mentioned here: https://freeorion.org/forum/viewtopic.php?p=109160#p109160

**Comment by freddyhayward** [comment]
> Can you find a version when it started happening? Perhaps looking around the same time as the versions mentioned here: https://freeorion.org/forum/viewtopic.php?p=109160#p109160

It starts happening at https://github.com/freeorion/freeorion/commit/fb38731469610571e01bbda674bad396be797bc5 for sure. https://github.com/freeorion/freeorion/commit/ff62820ae17d425b7e9fabd25981333f500b3db5 does not have the problem — in my testing with nearly 300 colonies, memory only reached 550MB.

**Comment by Oberlus** [comment]
I got the same results as @freddyhayward : fb38731 is the culprit.

**Comment by geoffthemedio** [comment]
Can you separately try each of:
https://github.com/freeorion/freeorion/commit/9fe122a4f360f673c5b9daaca3a735ea39ded008
https://github.com/freeorion/freeorion/commit/bd15ff0f87f60ee372188e3d5d76dd48da48c149
https://github.com/freeorion/freeorion/commit/0f4272d9ff448ac78e80f85ab20e19eb7671f286
to check if they resolve the issue?

**Comment by Oberlus** [comment]
> bd15ff0

I tested this one. Memory still leaks, but it feels slower. I think interacting with the UI accelerates memory consumption (I guess because it forces more renders).

Edit: 9fe122a is also bad.

**Comment by Oberlus** [comment]
0f4272d seems to be free of this problem. In all other cases, loading this game of mine (turn 55) was enough to see how memory usage increases by the minutes, without advancing turn. I've had 0f4272d idle for 3 hours and it's still at the same value than just loaded.

**Comment by MichaelCourtney** [comment]
0f4272d runs for me though I only briefly tested it. I'll do a proper test later. I've got some visible lag compared to ff62820 a slight pause when I click on a ship icon

Edit: The lag was possibly not FO. There was a process attached to Visual Studios that wasn't shutting down on exit, I've worked out how to turn it off completely.

**Comment by geoffthemedio** [comment]
I've pushed https://github.com/freeorion/freeorion/commit/b553bcc3b6fae3cfad6217ccba65367b4fac16ab to master. I don't understand why those changes caused memory leaks.

**Comment by geoffthemedio** [comment]
Could you also check https://github.com/freeorion/freeorion/commit/52277694b73471b109b5ad150a41e4f7eb179c51 ?

**Comment by Oberlus** [comment]
> Could you also check [5227769](https://github.com/freeorion/freeorion/commit/52277694b73471b109b5ad150a41e4f7eb179c51) ?

This one seems OK regarding memory growing while doing nothing.
It stills does that thing (that I don't know if it's a bug) about having much less memory usage upon reload:
My current playtest game is turn 95, played continuously from turn 55, used mem was 5.9%. After exiting FO and restarting it to continue game, memory usage goes down to 3.6%. Then playing a turn rises it up to 3.8%, then playing a few more turns doesn't increase it.

I didn't notice longer lags when using the UI.

**Comment by ghost** [comment]
I seem have same problem.
I tried "stable version" (0.4.10.2-2) from ArchLinux repository:
https://archlinux.org/packages/community/x86_64/freeorion/
https://github.com/archlinux/svntogit-community/tree/packages/freeorion/trunk
is... f663dad6379658b539bd28c95229218eb4333ef2 ? [[1]](https://github.com/archlinux/svntogit-community/blob/1a7160f8b33690ae38a04b3782875fe9684a677e/trunk/PKGBUILD#L27).

Then I tried compile "*-git version" 93069bb43f9145feb6f7a0fbd54701326a0ad34d `(v0.4.10+ build.2022-01-21.93069bb. CMake)` And FreeOrion still leak RAM (4GB and SWAP). After closed the game (when have 99% occupied RAM) I still have ~30% unknown occupied RAM (without SWAP).

How to reproduce it... Just play, need some time. If I playing slowly, then (+99% RAM) happen after 10 turns (per session), usually this ~25 turns (per session, for me), if I skipping turn over and over - then can skip so many turns (per session).

**Comment by Vezzra** [comment]
Hm... @Oberlus, you said with the fixes applied @geoffthemedio provided, the issue had been solved for you. Is that still true for 93069bb43f9145feb6f7a0fbd54701326a0ad34d?

**Comment by geoffthemedio** [comment]
If there are still memory leak issues, then it's not likely related to the issue @Oberlus was having. @0x159BABA11227B902 it would be helpful if you can identify a commit where it starts happening, somewhere between a v0.4.10 release an master...
