### ISSUE TITLE
SmokeTestHostless Randomly Fails

### ISSUE THREAD

**Issue by geoffthemedio** [freeorion/freeorion#3684]
The SmokeTestHostless test is presently less than useless, in that it seems to randomly fail for no reason, or no reason related to whatever the most recent commits are about, leading to reported CI failures that make it difficult to tell if a change actually broke something.

An example: https://github.com/freeorion/freeorion/runs/4896276619?check_suite_focus=true#step:13:8907
Or: https://github.com/freeorion/freeorion/runs/4873208942?check_suite_focus=true#step:13:5587
Or: https://github.com/freeorion/freeorion/pull/3681#issuecomment-1022550569

Re-running the tests several times will often result in a different one of the 4 Ubuntu tests failing, with the others then being cancelled. Eventually it usually manages to run them all. Other times they all work on the first try.

**Comment by geoffthemedio** [comment]
@o01eg you might have a look...

**Comment by o01eg** [comment]
Not sure why but it looks it has issues when reconnect to server. We can set `FO_TEST_HOSTLESS_GAMES=1` so CI won't catch it.

**Comment by geoffthemedio** [comment]
Can you make a pull request that does that?
