### ISSUE TITLE
Empire kills by fighters are not recorded

### ISSUE THREAD

**Issue by Oberlus** [freeorion/freeorion#3694]
Bug Report
==========

Environment
-----------
* **FreeOrion Version**: 580d50d

Description
-----------
@MichaelCourtney found that kills made by fighters are not counting towards unlocking a military slot and are not shown in the statistics Empire info page. 

Discusion: https://freeorion.org/forum/viewtopic.php?p=109811#p109811 and the posts above

Expected Result
---------------
All kills regardless of type of weapon used are recorded in the Empire statistics.

Steps to reproduce
------------------
I don't have a save for this.

**Comment by agrrr3** [comment]
I dont know how the event system works, but AttackFighterShip registers in attacks_event, AttackShipShip/PlanetShipShip in platform_event.

**Comment by agrrr3** [comment]
still only reading code: hm maybe server/ServerApp.cpp FlattenEvents is not working correctly? 
i guess the structure should be combat_info.combat_events (on toplevel) has BoutEvent.s (level 1) which have also one attacks_event (level 2).
The attacks_event has AttacksEvent.s and PlatformEvent.s (for ship attacks) (level 3).  The PlatformEvent.s again have AttacksEvent.s and should be on the fourth inner level.
FlattenEvents should flatten all those and its not very likely that flattening the fourth level works if flattening the third doesnot.

**Comment by agrrr3** [comment]
wont be able to investigate more in the next weeks i guess, somebody else please take over

**Comment by MichaelCourtney** [comment]
https://www.freeorion.org/forum/viewtopic.php?f=28&t=12299

**Comment by geoffthemedio** [comment]
Does https://github.com/freeorion/freeorion/commits/combat_info_rework fix it?

**Comment by geoffthemedio** [comment]
https://github.com/freeorion/freeorion/commit/c7b26addf3b4d321dd5685da28eda0b0ab342b0b
