### ISSUE TITLE
Start of game shows "AI_FIRST_TURN_GREETING_MSG202" instead of the actual message

### ISSUE THREAD

**Issue by psypherium** [freeorion/freeorion#3713]
![Screenshot from 2022-02-22 00-07-53](https://user-images.githubusercontent.com/12213882/154962060-8150baeb-f91f-4c51-b078-e5b0d536b0a5.png)

This is only a very minor thing, but I thought I would mention it in case it hasn't been noticed yet.

This happens in the release version and in a build made from git code today. Arch Linux.

**Comment by MichaelCourtney** [comment]
AI_FIRST_TURN_GREETING_MSG201
Stay the hell away from us!

AI_FIRST_TURN_GREETING_MSG203
Stay away from us, and we will stay away from you!

AI_FIRST_TURN_GREETING_LIST_TURTLE
'''AI_FIRST_TURN_GREETING_MSG201
AI_FIRST_TURN_GREETING_MSG202'''

looks like a typo: MSG203 instead of MSG202

**Comment by Cjkjvfnby** [comment]
Great catch!  It was there for 6 years :)
