### ISSUE TITLE
Planetary drive not reducing population

### ISSUE THREAD

**Issue by MichaelCourtney** [freeorion/freeorion#3715]
I have just tested moving planets in single-player and it seems that there is no population reduction happening (even though it is announced when you switch to starlane drive focus). - Thinksome

(https://www.freeorion.org/forum/viewtopic.php?p=110269#p110269)

Either this is broken or the message and description are wrong.

19th Multiplayer game

**Comment by Oberlus** [comment]
When the focus effect is activated, there should be no mistake, this should apply (with Scope = Source):
https://github.com/freeorion/freeorion/blob/694a408a29a784fd83094022125960f3eecd5578/default/scripting/species/common/advanced_focus.macros#L107
We have the MoveTo effect, the SitRep effect, and the SetPopulation effect. No idea why would not work the last effect.


While we are at it, I think we should increase cost and turns to complete of [planet beacon building](https://github.com/freeorion/freeorion/blob/06684c90468f186b9c94e4c6518dcee982decb8d/default/scripting/buildings/PLANET_BEACON.focs.txt#L4), and increase a lot cost of [planet beacon ship part](https://github.com/freeorion/freeorion/blob/06684c90468f186b9c94e4c6518dcee982decb8d/default/scripting/ship_parts/General/SP_PLANET_BEACON.focs.txt#L6) (that doesn't get destroyed), and add an IP cost to moving planets (in the focus effect, decreasing the IP meter of the moved planet).

**Comment by geoffthemedio** [comment]
Check the effect priorities?

**Comment by Oberlus** [comment]
It shares priority with the following:
- LIFECYCLE_MANIP_POPULATION_EFFECTS (creation of population in just settled colonies).
- Bombard weapons killing effect.
- Evacuation.

The only priority after that, OVERRIDE is used in
- Ancient Guardians.
- Conc. Camps.
- Art. Factory World.
- Gateaway to the Void.
- Experimentors Outpost Hull.
- Lembalalam.

It doesn't seem that anything is undoing the /2 effect of the focus.

**Comment by MichaelCourtney** [comment]
I might double check this tomorrow in game, see if I can reproduce. Just going on TS's comment that its happening. See if I can spot anything.

**Comment by MichaelCourtney** [comment]
Before focus change:
![1](https://user-images.githubusercontent.com/43386669/155354861-c82c171f-e200-4bf0-8e38-9a4c215aee87.png)
After focus change:
![2](https://user-images.githubusercontent.com/43386669/155354922-b1f30212-756a-4dbe-bf90-866c13f8a8ce.png)
Arrival in new system:
![3](https://user-images.githubusercontent.com/43386669/155354951-84fc7d13-77e6-481b-bed5-8561e02a15a6.png)

**Comment by MichaelCourtney** [comment]
Tested without a lighthouse - planet was successfully destroyed.
Tested without a lighthouse, destroy replaced with halve population - destroy sitrep gens, planet pop is not halved

**Comment by geoffthemedio** [comment]
I suspect the issue is that meter updates are run a few times during turn processing, with resets to the initial values between the updates, and after the effect moves the planet during a full effect processing (including meter and non-meter effects), the condition to fire the population-changing effect is no longer met, so it doesn't re-execute that effect for the later post-move meter updates.

A workaround might be to also apply a special that removes itself and also re-applies the same population effect. It could be a highly stealthy special, so the player never sees it, and set to only fire on the same turn it was applied. Not sure, but might be workable.

**Comment by Grummel7** [comment]
Yes, using a special does the job, I just used the time of the postponed dev-meeting implementing it. Only minor issue: I can hide it using stealth, but is there a way stop it from being listed in the Pedia list of specials?

**Comment by Grummel7** [comment]
Actually I was too quick. I special fails when a planet does consecutive jumps. I guess I cannot add a special twice, or else the effect removes both.

A building does the job, but I cannot hide it. Well, who cares, just give it a proper name and description...

**Comment by Grummel7** [comment]
It occurred to me that a special could work, if I remove before the population effects. So I've added another PR.

Neither of them has a correct forecast. I wonder whether we could implement a condition "ClientOnly", so we could have the original reduction in advanced_focus.macros, but move it to an extra EffectGroup that is only used by the client to provide a correct forecast.

**Comment by Grummel7** [comment]
Now I've found a way to fix the forecast: Keep the original effect and only apply the special's effect when the original effect's condition is not met after the move.
