### ISSUE TITLE
Tamed monsters created at owned monster nests are unowned

### ISSUE THREAD

**Issue by Oberlus** [freeorion/freeorion#3726]
Bug Report
==========

Environment
-----------
* **FreeOrion Version**: 4c7cf35
* **Operating System**: Ubuntu 18.04
* **Fetched as** 
  * Compiled from source

Description
-----------
Owned monster nests are creating unowned monsters, although the sitrep says they are tamed.
This is happening recently, probably from a commit in the last two weeks.

Expected Result
---------------
Tamed monsters are owned.

Steps to reproduce
------------------
Check out [discussion thread in the forum](https://www.freeorion.org/forum/viewtopic.php?f=28&t=12327).

**Comment by geoffthemedio** [comment]
should be fixed by https://github.com/freeorion/freeorion/commit/496928cda880ab5c2fe652f6b75f85a6a5b8989d

**Comment by Oberlus** [comment]
Yes, playtested. I assume you'll merge 496928c soon so I'm closing this now.
