### ISSUE TITLE
Can't start or resume single player games

### ISSUE THREAD

**Issue by Oberlus** [freeorion/freeorion#3743]
Bug Report
==========

Environment
-----------

* **FreeOrion Version**: 4d7cbe3
* **Operating System**: Ubuntu 20.04.4
* **Fetched as** 
  * Compiled from source

Description
-----------
I pulled and compiled current master, and started freeorion.
When I clicked on Single Player to start a game, the window freezed (mouse pointer only updates outside of FO window).
Waited several minutes, then killed it.
I started freeorion again and I was able to start a game with no delay.
Then my Sly scout run into another Sly scout and I remembered I hadn't changed some python line to avoid that (hence #3742).
I exited FO, did that PR, and tried to start anew game but window freezed.
I restarted several times, but I didn't wait more than 30 seconds before killing it.
Then I tried with master version again (without the mentioned PR) and could not start a game after several tries.
I can not "Continue", "Single Player" nor "Quick Start".
Then I switched to multiplayer game branch and had no trouble starting several games. Switched back to master and cannot start games.

No idea if this is reproducible. I can't attach a log or anything. I set logs to debug in Options and the only thing that is written (in freeorion.log) is that the logger has been initialized.

**Comment by Oberlus** [comment]
Playtested in another rig, Ubuntu 18.04.4

b3df307 (because I had it compiled): works

4d7cbe3: works!

I'll see what's the problem in the new rig, won't close this for now.

**Comment by Morlic-fo** [comment]
Can you check if reverting [5e59e34](https://github.com/freeorion/freeorion/pull/3620/commits/5e59e34f56d3d15e57573c7f0a89b221c916edea) fixes your issue?

**Comment by Oberlus** [comment]
> [5e59e34](https://github.com/freeorion/freeorion/pull/3620/commits/5e59e34f56d3d15e57573c7f0a89b221c916edea)

I was confused by the commit hash (I realize now it has different hash in the PR and once merged). Found the right one, 32ea75d, by searching for the commit description. I guess there is a better way?
This was my first git revert :dancers: 

I playtested it with the revert. With and without the change of PR #3742. It works like a charm.

**Comment by Morlic-fo** [comment]
Could you build #3746, set the logging level of the *network* logger to trace, reproduce the problem and post the resulting freeorion.log?

**Comment by Oberlus** [comment]
Done

[3746_set_trace_try_SP.log](https://github.com/freeorion/freeorion/files/8261134/3746_set_trace_try_SP.log)

**Comment by Morlic-fo** [comment]
Thanks, that was very helpful.

I added another commit to that PR which should fix the issue: [5328b92](https://github.com/freeorion/freeorion/pull/3746/commits/5328b927dd81eddcccc607e4dda13c6996d46d7b)
Can you confirm if this works?

**Comment by Oberlus** [comment]
It works.

[freeorion.log](https://github.com/freeorion/freeorion/files/8271110/freeorion.log)
[freeoriond.log](https://github.com/freeorion/freeorion/files/8271112/freeoriond.log)

Thank you very much.
