### ISSUE TITLE
Researching Electromagnetic Dampening doesn't cheapen Planetary Cloud Cover

### ISSUE THREAD

**Issue by Oberlus** [freeorion/freeorion#3753]
Bug Report
==========

Environment
-----------

* **FreeOrion Version**: 5328b92 (PR #3746)
  * Compiled from source
* **Operating System**: Ubuntu 20.04

Description
-----------
RP cost of tech Planetary Cloud Cover (SPY_STEALTH_1) is 100 minus 50 if Electromagnetic Dampening (SPY_STEALTH_PART_1) is researched, both multiplied by TECH_COST_MULTIPLIER (default 2).
In my current test game, default values, I got SPY_STEALTH_PART_1 several turns ago but SPY_STEALTH_1 still costs 200 RP (100*2). SPY_STEALTH_PART_1 costed 100.

![planet_stealth_tech_not_reduced](https://user-images.githubusercontent.com/28650914/158698714-cc39f9c8-9079-4ba2-9c9e-55cffbc3bb40.png)

FOCS seems right:
https://github.com/freeorion/freeorion/blob/cf18c18728aa67d3c8126c85b361961c450d9545/default/scripting/techs/spy/STEALTH_1.focs.txt#L6

I attach save and logs.

[logs.zip](https://github.com/freeorion/freeorion/files/8274743/logs.zip)
[FreeOrion_Oberlus_Abyss_0065_20220316_225533.zip](https://github.com/freeorion/freeorion/files/8274745/FreeOrion_Oberlus_Abyss_0065_20220316_225533.zip)

**Comment by Morlic-fo** [comment]
Possibly related to / fixed by #3750 ?

**Comment by Morlic-fo** [comment]
Loaded save with #3750 and seems to be fixed...
![image](https://user-images.githubusercontent.com/11706951/158702530-f3e989a2-796f-4a33-a096-034f4ba59d12.png)
