### ISSUE TITLE
Each unseen empire with Propaganda causes a -1 IP

### ISSUE THREAD

**Issue by Oberlus** [freeorion/freeorion#3758]
Bug Report
==========

Environment
-----------

* **FreeOrion Version**: 7058bfc
* **Operating System**: Ubuntu 20.04
  * Compiled from source

Description
-----------
HW has an Unknown -9 IP at start and Unknown -9 IP the rest of the game. See screenshot.
Edit 9 AIs with Propaganda, nice!

![IPminus9](https://user-images.githubusercontent.com/28650914/159347275-a47d2c1b-573b-4bbe-baee-36c8ad19d621.png)

It is not limited to Sly, I also tried Scylior.

[unknownIPminus9_logs.zip](https://github.com/freeorion/freeorion/files/8318626/unknownIPminus9_logs.zip)

**Comment by Grummel7** [comment]
It's 9 evil AIs now enabling propaganda broadcasts in turn 1.
Are you playing with master? It should have been fixed by now, see history of https://github.com/freeorion/freeorion/commits/master/default/scripting/policies/PROPAGANDA.focs.txt

**Comment by Oberlus** [comment]
> Are you playing with master?

Yes, see version reported, latest master's commit as of today.

**Comment by geoffthemedio** [comment]
Try `RootCandidate.Owner` in this line: https://github.com/freeorion/freeorion/commit/82560a62e54b5d879f467ef33e29edd6e85d2b9f

**Comment by Grummel7** [comment]
Yes, `RootCandidate.Owner` finally does the job.

Btw: Is it intended that ships count as well?
