### ISSUE TITLE
get_colony_builders, etc.

### ISSUE THREAD

**Issue by Grummel7** [freeorion/freeorion#3760]
The new InitializerLock has done its job and identified another premature usage of get_colony_builders. While analysing it, I found a can of worms.

The problem was caused by this [commit](https://github.com/freeorion/freeorion/commit/63e8a2fdf0cc5cb0a6b0c39ca98dd52816721deb). A couple of dicts in ColonizationAI.py have been moved to extra files. Before this commit, the variables have simply been recalculated in `ColonizationAI.survey_universe`. This meant that before survey_universe they had their old values, but they were usually not empty. Accessing those variable before `survey_universe` was always wrong, but it became worse since the values are now cached_for_turn, meaning they are cleared at the beginning of each turn and completely empty before `survey_universe`. 

But they are used before. E.g. `PlanetUtils.get_capital` uses both get_colony_builders and get_ship_builders when the AI has lost its capital and it is called several times before survey_universe, starting right in `FreeOrionAI.generate_orders`. So once an AI has lost its capital, it will throw an exception every turn.

I tried to move `survey_universe` to the top of `generateOrder`, after the following lines and it seems to work. Does anyone see a problem with that move?
```
    if empire.eliminated:
        info("This empire has been eliminated. Aborting order generation.")
        return
```

**Comment by Grummel7** [comment]
Actually there is yet another problem: survey_universe calls set_colony_builders 0 - N times. If an empire has no big enough planet at all, we get yet another exception. But that should be easy to fix.

**Comment by Cjkjvfnby** [comment]
Great catch!

The main idea of that lock is to find such places.  

If we will get something that is hard to fix, feel free to disable the lock.  So we could fix it without time pressure.
