### ISSUE TITLE
Game doesn't start due to python error

### ISSUE THREAD

**Issue by drkosy** [freeorion/freeorion#3765]
Bug Report
==========
After a new clean build on fedora linux 35 the game doesn't start. I just get the message:
"terminate called after throwing an instance of 'boost::python::error_already_set' "

Python Version 3.9.10
Boost Version 1.76.0

Git clone done on 22-03-19 build branch: master

Link to FO-Forum: https://www.freeorion.org/forum/viewtopic.php?f=25&t=12343&p=110958#p110958

**Comment by Grummel7** [comment]
Does this problem still exist with current builds?

This is surely not an AI problem.

According to the forum post, the last line in the log (freeorion.log, as far as I can tell) is:

```
08:46:48.769251 {0x00007f7c6bb4f640} [debug] client : PythonCommon.cpp:46 : Python module search path: /usr/lib64/python39.zip:/usr/lib64/python3.9:/usr/lib64/python3.9/lib-dynload
```

When I start freeorion, I find this in the freeorion.log before even starting a game:
```
09:24:05.054570 {0x00007fcbeac85700} [debug] client : PythonCommon.cpp:46 : Python module search path: /usr/lib/python39.zip:/usr/lib/python3.9:/usr/lib/python3.9/lib-dynload
09:24:05.055138 {0x00007fcbeac85700} [info] client : NamedValueRefManager.cpp:45 : NamedValueRefManager::NameValueRefManager constructs singleton 0x7fcc011ceb60
```
So my best guess is that the crash happens during some python interface preparations for FOCS parsing.

**Comment by o01eg** [comment]
Maybe someone could prepare Dockerfile for Fedora 35 like we did for Ubuntu 21.04:

https://github.com/freeorion/freeorion/blob/master/.github/ubuntu-21.04/Dockerfile
https://github.com/freeorion/freeorion/blob/master/.github/workflows/build-ubuntu-docker.yml

**Comment by o01eg** [comment]
I've tried to use CI to catch it but tests are passed: https://github.com/o01eg/freeorion/runs/5757586562?check_suite_focus=true

**Comment by o01eg** [comment]
Could you add some logging to check where it happens? Or may be better to catch it in debugger to see stacktrace of exception.

**Comment by o01eg** [comment]
Could you check if it reaches parsers? https://github.com/o01eg/freeorion/tree/fix-fedora-35-python-crash

**Comment by drkosy** [comment]
> Does this problem still exist with current builds?

Yes, it does. Got the latest files from master, built it and during start the discribed error occured again. It seems the window pops up for just 2 seconds, before the error is shown.

>Could you add some logging to check where it happens? Or may be better to catch it in debugger to see stacktrace of exception.

Which kind of logging do you need? FreeOrion Log or System Log? I'll gladly provide more information.

**Comment by o01eg** [comment]
> Which kind of logging do you need? FreeOrion Log or System Log? I'll gladly provide more information.

I need detailed FreeOrion log. Could you add line to try to catch, where it throws?

```diff
diff --git a/util/AppInterface.cpp b/util/AppInterface.cpp
index c7532ab97..2c377948a 100644
--- a/util/AppInterface.cpp
+++ b/util/AppInterface.cpp
@@ -60,6 +60,8 @@ void IApp::StartBackgroundParsing(const PythonParser& python, std::promise<void>
         return;
     }
 
+    DebugLogger() << "Start background parsing...";
+
     // named value ref parsing can be done in parallel as the referencing happens after parsing
     if (IsExistingDir(rdir / "scripting/common"))
         GetNamedValueRefManager().SetNamedValueRefParse(Pending::ParseSynchronously(parse::named_value_refs, rdir / "scripting/common"));
```

**Comment by drkosy** [comment]
The whole log file is attached.
[freeorion.log](https://github.com/freeorion/freeorion/files/8391016/freeorion.log)

>Could you add line to try to catch, where it throws?

Could you please tell me where to add this line. Sorry, I'm really new to this kind of stuff...

**Comment by o01eg** [comment]
Could you clone my repository and branch `fix-fedora-35-python-crash`?

**Comment by drkosy** [comment]
>Could you clone my repository and branch fix-fedora-35-python-crash?

I tried "git clone https://github.com/freeorion/fix-fedora-35-python-crash.git" and I tried "git clone https://github.com/o01eg/fix-fedora-35-python-crash.git" both time it prompted for user and password just to tell me that I need a token??

Next try was an update on freeorion git files followed by "git checkout fix-fedora-35-python-crash"  with told me that this reference doesn't exist.

So I wonder how to reach your repository.

**Comment by o01eg** [comment]
My repository has address https://github.com/o01eg/freeorion.git

You could add it as remote `git remote add o01eg https://github.com/o01eg/freeorion.git`, get commit from it `git fetch o01eg`, then run `git checkout fix-fedora-35-python-crash`

**Comment by drkosy** [comment]
Thanks for your help. I managed to clone your repository, change to fix-fedora-35-python-crash and build it. Sadly the error still occurs. I attached freeorion.log
[freeorion.log](https://github.com/freeorion/freeorion/files/8404696/freeorion.log)

**Comment by o01eg** [comment]
I've updated logs. Could you again build from my branch?

```bash
git fetch o01eg
git checkout -f 603289b3c
```

I use commit to ensure which code you use.

**Comment by drkosy** [comment]
It works! I tested Singleplayer and everything seems to went well :-)

**Comment by o01eg** [comment]
Not sure how it was fixed. Could you show logs?

**Comment by drkosy** [comment]
The logs are attached.
Maybe I changed something. Cmake never gets the path to libboost_python, so I add that manually. As I use python 3.10 it's libboost_python310.so
Yesterday I recognized by chance that the python library was set to python 3.9 so I changed that manually to:
>//Path to a library.
PYTHON_LIBRARY:FILEPATH=/usr/lib64/libpython3.10.so.1.0

Maybe that have done the trick?

[freeorion.log](https://github.com/freeorion/freeorion/files/8419871/freeorion.log)
[freeoriond.log](https://github.com/freeorion/freeorion/files/8419873/freeoriond.log)

**Comment by o01eg** [comment]
I suppose so. You should have same boost_python and python libraries.
