### ISSUE TITLE
Obsolete policies not removed from Empire::available_policies

### ISSUE THREAD

**Issue by Grummel7** [freeorion/freeorion#3774]
When I load a slightly older game now, the AI runs into an exception every turn trying to get the information about PLC_RESERVE_TANKS. The problem is obsolete policies are never removed from Empire::available_policies.

I've tried adding this to Empire::UpdatePolicies:
```
    auto policies_temp2 = m_available_policies;
    for (auto& policy_name : policies_temp2) {
        const auto* policy = GetPolicy(policy_name);
        if (!policy) {
            ErrorLogger() << "UpdatePolicies couldn't find policy with name: " << policy_name;
            m_available_policies.erase(policy_name);
        }
    }
```
It does solve the issue after one turn. But there should be a way to fix it right after loading the game.

Can anyone point me to the right place for this cleanup code?

**Comment by geoffthemedio** [comment]
This will only arise if using different content scripts before and after loading a save, so a one turn error just in that case isn't a major problem. Handling just policies for this case is also a bit arbitrary, as lots of other content could appear in similar lists with various consequences.

That said, something in LoadGame in SaveLoad.cpp would probably make sense, after deserializing empires.

**Comment by Grummel7** [comment]
Well, let's start with this case, we can always extend it when we encounter similar problems.
