### ISSUE TITLE
Include python and boost versions to version string of client and server log

### ISSUE THREAD

**Issue by o01eg** [freeorion/freeorion#3782]
Feature request
===============

Idea
----

To get available important dependencies versions and possible updates we could gather it on the servers.

Gain
----

It will allow to update game dependencies while consider if players didn't get issues with getting new version.

Discussion
----------

https://www.freeorion.org/forum/viewtopic.php?f=4&t=12356 (discussed by voice).

**Comment by geoffthemedio** [comment]
I wouldn't add this info to the version string, but rather have a separate client-to-server message that is sent after connecting, similar to checksum, but in the other direction.

**Comment by o01eg** [comment]
@geoffthemedio Why not add it to JOIN_GAME message alongside with version string?

**Comment by geoffthemedio** [comment]
https://github.com/freeorion/freeorion/tree/message_deps

**Comment by o01eg** [comment]
I think instead of new argument it possible get it same way as `FreeOrionVersionString()` because both defined in `Version.h`.

**Comment by geoffthemedio** [comment]
How do you want to handle the info on the server once received? Just append to the server log as in https://github.com/freeorion/freeorion/commit/ed230aad5471fa9c724f9f1120e2b10c2a81c20a#diff-fadad80f5d7d4080c2f7cdcfcf5e0e6568ba5db112ca51723ccc9181bf34b116R1152-R1153 ?

**Comment by o01eg** [comment]
Yes, I don't have other idea what to do with it yet so info logs will be fine.

**Comment by o01eg** [comment]
It looks like linker couldn't link `DependencyVersions()` because it defined in freeorioncommon and used in freeorioncommon but implemented in executables.

Could we extend IApp to solve it with virtual functions?

**Comment by o01eg** [comment]
Or maybe add it as parameter to `JoinGameMessage`.

**Comment by geoffthemedio** [comment]
[Latest version](https://github.com/freeorion/freeorion/commit/8263f55f994f6e1729b020a2bdc9af31ebc76a1f) builds. Does it also do what you wanted?

**Comment by o01eg** [comment]
Yes

**Comment by geoffthemedio** [comment]
https://github.com/freeorion/freeorion/commit/8263f55f994f6e1729b020a2bdc9af31ebc76a1f
