### ISSUE TITLE
Half of last line is missing on lots of the pedia pages

### ISSUE THREAD

**Issue by Szunti** [freeorion/freeorion#379]
Just compiled, (@Vezzra yes it compiles on my linux) (522fe977)
Like this:

![fo-halfline](https://cloud.githubusercontent.com/assets/1443881/10522297/c0b66aea-7374-11e5-82be-7451f1561023.png)

**Comment by geoffthemedio** [comment]
Was supposedly fixed...

https://github.com/freeorion/freeorion/pull/375

**Comment by MatGB** [comment]
It's not, it is in some places but not all, and it's also completely obscuring the list of places where the special or building is visible.
