### ISSUE TITLE
Autosave python error at turn 1 load - AI reset to aggressive

### ISSUE THREAD

**Issue by abmpicoli2** [freeorion/freeorion#3800]
* **FreeOrion Version**: 0.4.10.2 and master
* **Operating System**: Windows

Description
-----------
When reloading a single player autosave game, the AI, that was originally set to typical, is reset to aggressive. 

In the logs, the error messages that appear are:

```
17 abr 14:26:24] AI_11: AI_Error: AI script error : FreeOrionAI.py:resumeLoadedGame():133  - AI given empty state-string to resume from; this is expected if the AI is assigned to an empire previously run by a human, but is otherwise an error. AI will be set to Aggressive.
```

Expected Result
---------------
The expected result from an autosave is that the AI selected should be roughly the same. And not show the python errors in the logs.

[FreeOrion-logs.zip](https://github.com/freeorion/freeorion/files/8502158/FreeOrion-logs.zip)

Steps to reproduce
------------------
During single player creation, choose "Typical" in the AI level.
Then reload the autosave from turn 1.

**Comment by geoffthemedio** [comment]
This also seems to still affect master.

As far as I can tell, this only affects the turn 1 start of turn autosave. Autosaves from later turns and manual saves appear to work correctly for me.

Also seemingly working is the autosave from the end of the first turn, which can be enabled in the options.

**Comment by geoffthemedio** [comment]
Problem internally is that the autosave runs without polling the players for their state information. Normally this is fine, as the server has previous state info from players to put into the save, but on the first turn after galaxy generation, AIs haven't yet sent any state info. The server thus saves an empty state string for th AIs. When that save is later loaded, the AIs receive an empty state string, and thus don't know that they were previously set to some other aggression.

@Cjkjvfnby @Morlic-fo @Grummel7 I'm not sure how to get the right save state info. I'd have to get it from the AIs themselves, and can't generate it on the server. The AIs could perhaps send that info back to the server immediately upon starting up, with the initial post-galaxy-creation autosave deferred until that info is received. Or there could be (agin) a message from the server to the AIs that requests a state string...

**Comment by Morlic-fo** [comment]
How about setting save string server side to some special value and if that is passed, just let the AI behave as if it is a new game, i.e. regenerate the aggression.

At least in the current implementation, RNG is seeded by galaxy seed and empire name so it should yield same results when loading the game.

I.e. change
https://github.com/freeorion/freeorion/blob/6d50cf134245ef8f9fb3939d31fb15fe4c140069/client/AI/AIClientApp.cpp#L264
to ```if (loaded_game_data && save_state_string != "MyMagicValue")```?

**Comment by geoffthemedio** [comment]
> some special value

perhaps an empty string?

**Comment by Morlic-fo** [comment]
> perhaps an empty string?

Sure. Unless there is some other reason to have an empty string, e.g. the AI failing to build a proper savestring and thus sending an empty one. When loading such a savegame, we would probably want to raise an error message on load (as is done now). Of course, that failure state string could instead be a non-empty string.

**Comment by geoffthemedio** [comment]
You can decide how you want to use the AI state string...

**Comment by hifron** [comment]
In JavaScript(and TypeScript) world, there are transitions of state, which could be modified, but not the current version, only the next(and theoretically and practically replayed)...

During setup there could already be present initial setup save turn 0 in which AI should do nothing... And in future of programming AI should behave according some situation predefined like slow start scenarios and similar(settings at turn 0 setup)...

**Comment by Morlic-fo** [comment]
> You can decide how you want to use the AI state string...

All up to @Grummel7 who is clearly the most active and motivated AI dev right now as far as changes other than refactoring are concerned. But starting with the empty string is probably the simplest.

**Comment by Grummel7** [comment]
Hm, now we have two parallel discussion. I'll close the PR since we all seem to agree that the original idea to fix this was too complicated.

**Comment by Grummel7** [comment]
An empty string is what the AI gets at the moment. Of course it could interpret it differently, but there is a small problem is that it does not get the aggression level.
I just tried a very simple fix, and it seems to work very well: 
AIClientApp.cpp
```
            if (save_state_string.empty())
                m_AI->StartNewGame();
            else
                m_AI->ResumeLoadedGame(save_state_string);
```
The old AIs have not done anything in turn 1 and the new AIs will be as random as before, but using the correct max aggression.

**Comment by geoffthemedio** [comment]
Can that redirect be done in the AI scripts if it receives an empty state string?

**Comment by hifron** [comment]
If there is for example very slow computer(or phone not accelerated by AI) and AI would be more advanced, there would be problems...

**Comment by Grummel7** [comment]
> Can that redirect be done in the AI scripts if it receives an empty state string?

No, because only StartNewGame send m_aggression to the AI.

**Comment by Morlic-fo** [comment]
> No, because only StartNewGame send m_aggression to the AI.

Currently, the AI aggression is chosen in the C++ code, but I don't really see why that would be necessary or even desirable from a design point of view.

We can move the aggression selection logic to python, and the respective function can be called from either `startNewGame` or `resumeLoadedGame` as necessary.

**Comment by Grummel7** [comment]
> Currently, the AI aggression is chosen in the C++ code, but I don't really see why that would be necessary or even desirable from a design point of view.
> 
> We can move the aggression selection logic to python, and the respective function can be called from either `startNewGame` or `resumeLoadedGame` as necessary.

I may be the most active AI developer at the moment, but that doesn't mean I now all its ins and outs yet. If the AI can determine the configured aggression, the issue can indeed be fixed without changing anything in C++.

Could you prepare a PR?
