### ISSUE TITLE
Regression: Ship values in ship design view is broken (including Estimated combat strength)

### ISSUE THREAD

**Issue by agrrr3** [freeorion/freeorion#3809]
Pedia view for a human frigate object; Both for species  Generic and species human:
```
Estimated combat strength   (ignoring shields):  239   (5.11 per PP)
            (enemy with attack 3.1 and shields 0.0):  239   (5.11 per PP)
```

In design view estimation is zero; Both for species  Generic and species human:
```
Estimated combat strength   (ignoring shields):  0   (0.00 per PP)
            (enemy with attack 3.1 and shields 0.0):  0   (0.00 per PP)
```

**Comment by agrrr3** [comment]
related from the log; 

`
[error] client : CombatDamage.cpp:168 : Combat::WeaponDamageImpl passed source ship without a valid design ID: OBJ_SHIP -2:   at: (-100000.000000, -100000.000000) nearest (System 897) owner: Erdimperium created on turn: 1 specials:   Meters: TargetIndustry: Cur: 0.00 Init: 0.00  TargetResearch: Cur: 0.00 Init: 0.00  TargetInfluence: Cur: 0.00 Init: 0.00  MaxFuel: Cur: 0.00 Init: 0.00  MaxShield: Cur: 0.00 Init: 0.00  MaxStructure: Cur: 0.00 Init: 0.00  Industry: Cur: 0.00 Init: 0.00  Research: Cur: 0.00 Init: 0.00  Influence: Cur: 0.00 Init: 0.00  Fuel: Cur: 0.00 Init: 0.00  Shield: Cur: 0.00 Init: 0.00  Structure: Cur: 0.00 Init: 0.00  Stealth: Cur: 0.00 Init: 0.00  Detection: Cur: 0.00 Init: 0.00  Speed: Cur: 0.00 Init: 0.00   design id: -1 fleet id: -1 species name: SP_HUMAN produced by empire id: 1 arrived on turn: 1 last resupplied on turn: 1
`
a) that is a temporary object (ID -2) and the code returns because there is no valid design ID (either we should not return for the temporary or set a temporary design id)
b) the values are basically unusable

**Comment by agrrr3** [comment]
also those zero values are shown in the UI, only PP cost seems to do the right thing

@geoffthemedio as far as analyzed it looks the UI adds a temporary ship and registers/recalls it using the design ID. so the lookup (using the INVALID design id) seems to work as there actually is a ship object. I am not sure if the PP is calculated using a ship or simply by summing up hull and parts' cost. If it is done via a ship, we have two different objects

**Comment by geoffthemedio** [comment]
`GetDetailedDescriptionStats` is called with a temporary ship with design ID set to -1 (invalid design) and a pointer to a temporary ship design created from what's set up in the design GUI.

`GetDetailedDescriptionStats` then calls `ship->TotalWeaponsFighterDamage(...)` on the ship, without passing the design.

`ship->TotalWeaponsFighterDamate` does a series of calls, passing along a pointer to itself, until it reaches `Combat::WeaponDamageImpl`, which checks the design of the ship and outputs that error message because it's still -1.

The temporary ship design doesn't have a valid design ID to look up, so would need to be passed along.

Probably this needs some reworking regardless, as the ship's part meters, which are set up based on the ship's design, are also involved in the calculation, and would need to be added and then updated first.

**Comment by agrrr3** [comment]
yeah, the weapon total damage is the minor issue here (one can simply accept a design ID -1 iff ship ID -2). the meters should be righted. this was working once (for damage calculation and showing in the meters in the UI). dunno where to change that

**Comment by agrrr3** [comment]
the normal meters do not get updated because of a similar issue - `Universe::InsertShipDesignID` initially fails because of UpdateIDAndCheckIfOwned return false for invalid design id.
and then i had a followup issue  - it seems the pocket universe context seems to be reused in some way and  InsertShipDesignID stop registering the ship design because the design ID was already registered

the main preparation work gets done in RefreshDetailPanelIncomplDesignTag (in  EncyclopediaDetailPanel.cpp)

note the ID for incomplete design gets set in DesignWnd::MainPanel::RefreshIncompleteDesign()  and the IdAllocator also has to agree.

**Comment by agrrr3** [comment]
I am not completely sure how to proceed with the IDs. Locally I added an INCOMPLETE_SHIP_DESIGN constant -4 for identifying the ship design shown in the design UI and recognize that ID in the relevant places as not invalid. 

Buut maybe that is only a special case of a more general one. We might in other cases want to add multiple temporary objects and designs and those having the same ID will probably create issues (e.g. we use the design ID to look it up, so we cant have multiple of those). In those cases it might be enough branch of a pocket universe and add designs and objects to that one, counting up the IDs and scrapping the universe when we are done with it. So there might be multiple universes which have different ship designs with the same ID and that would be ok. 
Use case would be for example a battle simulator for use in AI (and UI).

Buut as the error of multi-registration suggests, there might be some unintentional/half intended overlapping of universes; e.g. if we would use pocket universes e.g. to restrict the scope of nested conditions we probably want to inherit the ship designs.
Also there might be leaking from pocket universe data to another/the real universe (e.g. trying to show a ship design with a certain ID, but with actually meaning a different design)

**Comment by hifron** [comment]
Maybe `boost::uuids::uuid uuid` ,which is already in some places... And in Changelog.md there are lines:

- If parsing a ship design fails, just fail that design, not the whole directory.
- Added UUIDs to ship designs.

But in ShipDesign::ProductionCost there is TODO to do it with context and maybe without it it is something broken...

**Comment by agrrr3** [comment]
@Oberlus
@MichaelCourtney can (one of) you guys confirm that the ship design view working?

**Comment by MichaelCourtney** [comment]
I'll try and take a look when I can. Currently getting compile errors trying to compile master. Oberlus might get to it 1st

**Comment by Oberlus** [comment]
I started a new design with an unavailable (locked) hull, added an MD and a SP, and combat estimations and other values seemed OK.

GJ.
