### ISSUE TITLE
Asteroid coating adding 10% multiple times

### ISSUE THREAD

**Issue by Grummel7** [freeorion/freeorion#3820]
I doubt that this was intended, was it?
![asteroid_coating](https://user-images.githubusercontent.com/20499830/166416882-6d3b9c16-f6eb-492a-b3be-7eb5d56e8ea4.png)
See also https://www.freeorion.org/forum/viewtopic.php?p=111365#p111365

**Comment by agrrr3** [comment]
does this scale with the number of plates, or do you maybe have two specials in your empire?
