### ISSUE TITLE
Fighter launch capacity set to 0 for unknown reasons

### ISSUE THREAD

**Issue by Oberlus** [freeorion/freeorion#3830]
Bug Report
==========

Environment
-----------
* **FreeOrion Version**: 5c9b2de (saves from 9783ded)
* **Operating System**: Ubuntu 20.04 (saves from another system using snap)
  * Compiled from source

Description
-----------
Fighter launch capacity set to 0 for unknown reasons, despite hangars having some fighters in it.

Steps to reproduce
------------------
Load save file 51 from LienRag's report at the forum: https://www.freeorion.org/forum/viewtopic.php?p=111600&sid=c99d79f975129e9d3c7fb704faad38ac#p111600
Check out the ship "Manet" going from Taladas to empty system Rov. It has launch capacity 2 (correct).
Press turn and check out that same ship at Rov: it now has launch capacity 0.

**Comment by MichaelCourtney** [comment]
To produce bug, adopt Flanking.

**Comment by agrrr3** [comment]
there might be multiple issues with (the FOCS stuff used) in PLC_FLANKING.

one is this issue and while e.g. arc disruptor effect works `SetMaxSecondaryStat partname = "SR_ARC_DISRUPTOR" value = Value + NamedReal name = "PLC_FLANKING_ARC_DISRUPTOR_SHOT_BONUS" value = 1.0`, the launch bay effect intendended for interceptors in the same effectsgroup does seem to cause the issue: 
```
                SetMaxCapacity partname = "FT_BAY_1" value = Value
                + (  (Statistic If condition = And [ Object id = Target.ID  DesignHasPart low = 1 high = 999 name = "FT_HANGAR_1" ] )
                   * (NamedReal name = "PLC_FLANKING_BAY_LAUNCH_BONUS" value = 2.0 ) )
```

Also in the same EffectsGroup, SetMaxSecondaryStat is used for hangar capacity of the other fighters and SetMaxDamage for MD,Laser,Plasma and DR. I did not check if those effects work.

also i had the feeling that the effectsgroup gets triggered too often (a ship in flight not eligible for pincer bonus gets its launch bay set to zero).

Also note these bad effects are all regressions

@geoffthemedio is this possible in principle(?): an error occurs when the value ref for SetMaxCapacity is evaluated in SetShipPartMeter::Execute so the whole thing evaluates to zero?

**Comment by geoffthemedio** [comment]
If there is an error, some valuerefs will default to returning 0, so perhaps, depending what qualifies as an "error"...

**Comment by agrrr3** [comment]
it fails to find the meter? after the following in NewMeterValue m is nullptr and it `return {Meter::INVALID_VALUE, m};`
```
if constexpr (std::is_same_v<M, MeterType>) {
    m = target ? target->GetMeter(meter) : nullptr;
}else if constexpr (std::is_same_v<M, Meter*>) {
    m = meter;}
```
... think i found the bug...
