### ISSUE TITLE
AI fleet not atacking an enemy scout for more than one turn

### ISSUE THREAD

**Issue by Oberlus** [freeorion/freeorion#3833]
Bug Report
==========

Environment
-----------
* **FreeOrion Version**: 37b4b97
* **Operating System**: Ubuntu 20.04
  * Compiled from source

Description
-----------
A basic small hull scout arrives at a system at turn 56, finding a lot of enemy ships including one robotic hull warship capable of combat.
No combat ensues despite mutual visibility. Maybe the robotic warship was built this same turn and could not enter combat yet.
After another turn, with the scout idle among the enemy ships, still no combat ensues.

Problem with AI setting their fleet to non-aggressive or something else?

Steps to reproduce
------------------
Load attached save game, turn 56, check out northwest system Xiddig Delta, and press turn.

[37b4b97_no_combat.zip](https://github.com/freeorion/freeorion/files/8650869/37b4b97_no_combat.zip)

**Comment by Grummel7** [comment]
> After another turn, with the scout idle among the enemy ships, still no combat ensues.

Well, when you load turn 57, you'll find that your scout is still there, but there is no battleship. I can see in the AI logs that it was indeed built in the same turn that your scout arrived and flew off immediately.

As I player I would have changed on of the troop ships to aggressive, so the planet defense would have killed your scout. But the AI doesn't know that trick yet. Perhaps one day I'll change that ;-)

I suggest closing this issue.
