### ISSUE TITLE
Searching the Pedia freezes the client

### ISSUE THREAD

**Issue by Oberlus** [freeorion/freeorion#3835]
Bug Report
==========

Environment
-----------
* **FreeOrion Version**: 3abfde4
* **Operating System**: Windows 10
  * Weekly development build

Steps to reproduce
------------------
Start FO, click on Pedia, write down anything in the search text box and hit enter.
It also happens when searching the Pedia within a game.

**Comment by geoffthemedio** [comment]
Did this change recently?

**Comment by Oberlus** [comment]
> Did this change recently?

I'll try to pinpoint it, but don't have time now.
I did use Pedia OK in the past month, not sure when, I'll start looking at the weekly test build of two weeks ago.

**Comment by geoffthemedio** [comment]
Just tried now and e6b4f942f8caaa56144dcdc9e59d6c51319600f7 seems to work fine for me.

**Comment by geoffthemedio** [comment]
Can you post your client log from immediately after searching for "test" or similar? Also look in it for errors about missing strings, in particular I see **Missing string: FLUX_HULL_TECHS_DESC**. It shouldn't cause a huge delay in that case, but it's possible there's a problem with the multithreading access guards that affects your system different from mine in the case it has to create a new ERROR string while searching...  So if you have some missing string log lines, maybe check if adding them to the stringtable fixes the issue?

**Comment by o01eg** [comment]
> Just tried now and [e6b4f94](https://github.com/freeorion/freeorion/commit/e6b4f942f8caaa56144dcdc9e59d6c51319600f7) seems to work fine for me.

If it also fixes Pedia freeze maybe ask for early weekly test build?

**Comment by geoffthemedio** [comment]
There's nothing special about that commit other than being the one I had on my machine. Nothing relevant changed recently that I know of.

**Comment by geoffthemedio** [comment]
@Oberlus poke

**Comment by Oberlus** [comment]
With latest master version this no longer happens. Closing.

**Comment by geoffthemedio** [comment]
I also don't get any hang when searching in the pedia from the intro splash screen in 3abfde43 but if you could revert to that and reproduce the freeze and post the client .log file from immediately after it happens, that might be helpful...

**Comment by Oberlus** [comment]
I recompiled 3abfde4 and tried OP's steps but got not freeze this time.
No idea what was going on then.
