### ISSUE TITLE
Compile error on Windows:  error C2039: '_copysign': is not a member of 'boost::core'

### ISSUE THREAD

**Issue by Vezzra** [freeorion/freeorion#3902]
Bug Report
==========

Environment
-----------

* **FreeOrion Version**: eb6a7d214cc74e3fdfe2b16d31ab3c011e59b0b9
* **Operating System**: Windows 10
* **Fetched as** 
  * Compiled from source

Description
-----------

Trying to build FO on Windows fails with this error message:
```
1>C:\Users\User\SoftwareProjekte\FO\main\include\boost\lexical_cast\detail\inf_nan.hpp(80,43): error C2039: '_copysign': is not a member of 'boost::core'
1>C:\Users\User\SoftwareProjekte\FO\main\include\boost\core\is_same.hpp(23): message : see declaration of 'boost::core'
```
As required, I'm using v13 of the SDK to build master at this commit.

**Comment by o01eg** [comment]
It should be fixed with https://github.com/freeorion/freeorion-sdk/pull/97#issuecomment-1133411408. Does MSVS show which *.cpp file failed to build?

**Comment by o01eg** [comment]
Also, what version of MS VS and which project is used?

**Comment by o01eg** [comment]
Looks like it somehow caused by c++20 enabled in MS VS 2022 project while CMake generates projects with c++17 standard.

**Comment by Vezzra** [comment]
> It should be fixed with [freeorion/freeorion-sdk#97 (comment)](https://github.com/freeorion/freeorion-sdk/pull/97#issuecomment-1133411408).

That's what I thought, too. Which is why I was surprised when I got that error - I thought "Hadn't you guys fixed exactly that just some days ago...?" 🤷‍♂️ 

> Does MSVS show which *.cpp file failed to build?

Not really, unfortunately. The output in the VS IDE is not conclusive. It happens when building the parser lib, it *looks* like it is `StdAfx.cpp`, but as I said, the output is not conclusive. And I wonder what that cpp file has to do with the parser lib...?

> Also, what version of MS VS and which project is used?

I use MSVS 2022, and the MSVS2022 project files to build FO on Windows.

**Comment by Vezzra** [comment]
> Looks like it somehow caused by c++20 enabled in MS VS 2022 project while CMake generates projects with c++17 standard.

Ok, I see - can that be fixed?

**Comment by o01eg** [comment]
I'm experimenting with it in https://github.com/freeorion/freeorion/pull/3905 If CI passed I'll apply that solution.

**Comment by geoffthemedio** [comment]
Probably relevant workaround code: https://github.com/freeorion/freeorion/blob/master/util/OptionValidators.h#L13-L19

**Comment by o01eg** [comment]
@geoffthemedio Issues happens in Parser library so I suppose it should be included somewhere else. CMake still uses c++17 although.

**Comment by Vezzra** [comment]
Everything works fine now.

**Comment by geoffthemedio** [comment]
https://github.com/freeorion/freeorion/commit/97151184c4d6494439e098428d43865e337a973a
https://github.com/freeorion/freeorion/pull/3907

> Everything works fine now.

Except building the Parsers in C++20 mode

**Comment by o01eg** [comment]
I've set up CI to check it so we could try to return c++20 in MS VS 2022.

**Comment by Vezzra** [comment]
> Except building the Parsers in C++20 mode

Point taken 😉
