### ISSUE TITLE
Pedia Update: Stealth/Detection

### ISSUE THREAD

**Issue by MichaelCourtney** [freeorion/freeorion#3959]
The New mechanics for star type/fleet size aren't listed in the pedia (unless you count the mouse over)

**Comment by MichaelCourtney** [comment]
I can add the stealth/detection modifiers for star type as a linked page or I can tack the modifier list onto the end of both stealth and detection pages. I'm inclined towards the 2nd option

**Comment by Grummel7** [comment]
> I can add the stealth/detection modifiers for star type as a linked page or I can tack the modifier list onto the end of both stealth and detection pages. I'm inclined towards the 2nd option

Option 2 would be okay for me, as long as you define the text in one place.
