### ISSUE TITLE
crash when moving ships between fleets

### ISSUE THREAD

**Issue by aschuch247** [freeorion/freeorion#397]
I am using master (b05074c131bc56651613952dce0071b0460f3365) and the game crashed when moving ships from one fleet to another. A coredump file (438M) has been created. A backtrace is attached to this issue.

[gdb.txt](https://github.com/freeorion/freeorion/files/34808/gdb.txt)

**Comment by geoffthemedio** [comment]
Looks to be the same as discussed here:

http://www.freeorion.org/forum/viewtopic.php?p=81431#p81431

**Comment by geoffthemedio** [comment]
I looked into this a couple months ago, but can't find any comments specifically about it, but do have a related comment here: http://www.freeorion.org/forum/viewtopic.php?p=81368#p81368

Give the crashes are occurring with top of the stack like

GG::Wnd::UpperLeft
GG::Wnd::Top
GG::ListBox::RowPtrIteratorLess::operator()

I think it's the same issue, with an iterator being invalid after the corresponding Wnd is deleted, and the list is attempting to resort its row iterators in an std::set, which involves calling their custom comparison function, which attempts to dereference them, which crashes when the dereferenced iterator points to a deleted Wnd.

**Comment by geoffthemedio** [comment]
As mentioned here,

http://www.freeorion.org/forum/viewtopic.php?p=82029#p82029

more testing is requested.

**Comment by Vezzra** [comment]
Did some testing on OSX with a lot of splitting, merging, drag-and-dropping (that usually should have triggered a crash after some time), no crash so far. Only time will tell if this legendary issue is finally gone, but the first impression is that things seem stable now.

**Comment by Vezzra** [comment]
Some more of the same testing on Linux, same result, no chrashes so far.
