### ISSUE TITLE
Artifical Moon building does not remove itself when it creates Resonant Moon

### ISSUE THREAD

**Issue by Casteele72** [freeorion/freeorion#3973]
Bug Report
==========

Artifical Moon building does not remove itself when it creates Resonant Moon.

Environment
-----------

* **FreeOrion Version**:* 

v0.4.10.1 HEAD [build 2020-09-25 39cfe10] CMake
 
* **Operating System**:
Debian Linux 10:
$ uname --all
Linux cas-deb64 5.4.0-0.bpo.4-amd64 1 SMP Debian 5.4.19-1~bpo10+1 (2020-03-09) x86_64 GNU/Linux

* **Fetched as** *

Binary release (I think? I do not remember if I fetched the current installation from the Debian Linux APT repository, from GitHub, or if I built it from GitHub sources...)

Description
-----------

After an Artificial Moon building is constructed, it creates the Resonant Moon special as expected. However, the building remains on the planet. It would seem that it should behave similar to Gaia Transformation, and destroy itself when it activates. Manually scrapping the building works as expected, with no observed side effects.

I copied the few lines from Gaia Transformation (and adding square brackets around the AffectsGroups entries) that make Gaia remove itself. So far, that appears to fix the issue. Additionally, making the change also triggers all previously unremoved buildings to remove themselves during the next turn/update cycle.

Expected Result
---------------

As stated in the Description, above.

Steps to reproduce
------------------

Construct an Artificial Moon and wait a few turns after it completes. The planet gets the Resonant Moon special added properly, but the building remains on the planet's building list.

If you do the same steps for the Gaia Transformation, the Gaia Transformation building destroys itself after creating the Gaia planet special (as expected).

**Comment by crazymerlyn** [comment]
should this be closed? #4041 fixes it
