### ISSUE TITLE
Category mismatch in Interstellar Logistics

### ISSUE THREAD

**Issue by MichaelCourtney** [freeorion/freeorion#3974]
Bug Report
==========
using [[tech SHP_INTSTEL_LOG]] in the stringtables does not create a link in the pedia. This appears to be due to a category mismatch.

name="SHP_INTSTEL_LOG" ( should be name="CON_INTSTEL_LOG")
category="CONSTRUCTION_CATEGORY"

https://www.freeorion.org/forum/viewtopic.php?f=15&t=11432&p=112618#p112618

**Comment by geoffthemedio** [comment]
> [[tech SHP_INTSTEL_LOG]] in the stringtables does not create a link in the pedia

works for me...
![pedia_link](https://user-images.githubusercontent.com/11386908/178360398-4d59c3cf-0775-4307-b6ad-dae452e39775.png)

**Comment by MichaelCourtney** [comment]
Ok I have no idea what was going on as its working for me now, and I'm using an exact copy of what was not working for me before...
