### ISSUE TITLE
unable to load save game

### ISSUE THREAD

**Issue by aschuch247** [freeorion/freeorion#398]
I am using master (b05074c131bc56651613952dce0071b0460f3365). I am using automatic save and I tried to load such a save game. But nothing happens. I see the star field background, and the mouse cursor. I can move the mouse cursor around, but nothing more happens.

I attached the client and server log files.

[freeorion.log.txt](https://github.com/freeorion/freeorion/files/34809/freeorion.log.txt)
[freeoriond.log.txt](https://github.com/freeorion/freeorion/files/34810/freeoriond.log.txt)

**Comment by geoffthemedio** [comment]
Should be fixed, at least for new save gmes.

**Comment by aschuch247** [comment]
It's been some time, but just for reference, the fix likely is 7f21abb91170574920ceecbe76563d277b9c62ce.
