### ISSUE TITLE
Autogenerated Effects Descriptions Break Some Pedia Articles

### ISSUE THREAD

**Issue by geoffthemedio** [freeorion/freeorion#3996]
With Options / UI / Auto-generated effects descriptions checked, going to some pedia articles, such as the colony buildings or Gaia Transformation, just gives an error message:
`Error parsing rich text tags: expected end tag:int got end of string.`

@o01eg Possibly related to recent changes to parsers and dumping?

**Comment by o01eg** [comment]
@geoffthemedio Not sure if it about dumps or parser. Is it possible to find where it happens?

Colony buildings wasn't changed yet.

**Comment by geoffthemedio** [comment]
Probably is an issue with dumps, as parsing seems fine.

**Comment by o01eg** [comment]
Yes, looks like `// StringCast<i>` not escaped and was treated as starting tag.

**Comment by o01eg** [comment]
I can change angle brackets to other one in Dump or add XML escaping of those symbols.
