### ISSUE TITLE
Frame limiter not working

### ISSUE THREAD

**Issue by MagaTailor** [freeorion/freeorion#401]
Hi, 

I finally got FO 0.4.5 working on my old Slackware box and it's doing great (you might be interested to hear the game works perfectly well on a [Geforce FX 5200](http://www.nvidia.com/page/pg_20040109440047.html) using the 173 series NVIDIA driver, i.e OpenGL 1.5).

The problem is, after setting the FPS limiter to 24, I'm still getting around 40 FPS. It's not a problem at all cause FO is merely using about 30% CPU but still not the expected behaviour. 

Thx.

**Comment by geoffthemedio** [comment]
It's a known issue. The actual FPS does increase or decrease with the requested FPS, though they have never matched. Vsync also seems to affect it; when I use the my NVIDIA adapter, it's limited to 60 FPS, presumably due to some vsync setting, but the integrated adapter can go over 150 FPS with the limit set to max.

**Comment by MagaTailor** [comment]
Ok, I'll close then. Any use opening another about the following? 

The default for the `Fake resolution change` option is `on` which causes FO to become unusable in fullscreen (100% cpu, fps down to 1) - turning this option off immediately fixes it.

Oh, one more thing - could you direct me to the place in the source responsible for the spinning star system selector rendering?

Thanks

**Comment by geoffthemedio** [comment]
No need to close because it's known...

Sure, open issues for, well, issues.

https://github.com/freeorion/freeorion/blob/master/UI/CUIControls.cpp#L1829

**Comment by MagaTailor** [comment]
Ok, thanks. I thought you meant it was being tracked elsewhere.
