### ISSUE TITLE
"Fullscreen + Fake resolution" combo problem

### ISSUE THREAD

**Issue by MagaTailor** [freeorion/freeorion#402]
As long as the `fake resolution change` option is active FO becomes unusable in fullscreen (100% cpu usage, fps down to 1) 

FO 0.4.5 on 32-bit linux (slackware), [Geforce FX 5200](http://www.nvidia.com/page/pg_20040109440047.html), X 1.14, NVIDIA binary driver ver. 173, OpenGL 1.5

**Comment by geoffthemedio** [comment]
I suppose the solution in your case is to not use that option. Apparently it has uses, though I'm not sure when / on what system that is...

**Comment by MagaTailor** [comment]
Yeah, that's how I got it working correctly in fullscreen - so does it have to be on by default?

**Comment by Vezzra** [comment]
IIRC that option was implemented to work around issues with switching between fullscreen/windowed mode on some systems. On most systems enabling that option seems to be to more compatible mode, that's why it defaults to on.

At least that's how I remember it. @Mitten-O is the guy who implemented the thing, so he probably knows best. Unfortunately he hasn't been around much lately.

**Comment by Mitten-O** [comment]
You remember it quite correctly, I myself had to refresh the details to my mind from the original thread. Here: http://www.freeorion.org/forum/viewtopic.php?f=9&t=8989&hilit=full+screen+sdl&start=15#p71338. And some source material: https://forums.libsdl.org/viewtopic.php?t=9231&sid=4e7ebe3df4be87f0ee65a18a7a944738

To put it simply, resolution changes can be very temperamental on linux, so it's generally better to just fake it by drawing onto a framebuffer of the desired resolution and scaling that on the screen. I do not believe there is reason to change the default, but it is good to know it can cause a problem like this.

Frame buffer shenanigans are not (well?) supported on old video cards. The option should be disabled when they are entirely unsupported, but maybe the driver has some slow emulation of it or something. What GPU are you using?

**Comment by petevine** [comment]
[Geforce FX 5200](http://www.nvidia.com/page/pg_20040109440047.html)

**Comment by Mitten-O** [comment]
As far as I can tell from [NVIDIAs specs](http://www.nvidia.ru/object/nvidia_opengl_specs.html), the FX 5200 is indeed too old (2003-ish) to properly support the shenanigans. Well, at least you apparently can live well without them and we can now point people to turning the option off if they run into the same issue.

**Comment by Vezzra** [comment]
Ok, I'm tagging this as wontfix and close the issue, as we can't really do anything about it.
