### ISSUE TITLE
Ghost fighters?

### ISSUE THREAD

**Issue by Grummel7** [freeorion/freeorion#4040]
With current master I got a strange battle log.

I wonder what my flak was firing at in turns 3 and 4:
![ghostfighter](https://user-images.githubusercontent.com/20499830/183258013-c5935354-bed0-4522-b6c9-503e8c2c3d25.png)

To reproduce: load the game, advance turn.
[ghostfighter.sav.gz](https://github.com/freeorion/freeorion/files/9275434/ghostfighter.sav.gz)

Note that I originally played with a build based on https://github.com/freeorion/freeorion/commit/17fbb82cd1ce2170196278a949074f35abe6ca26. After updating I now also get a AI exception. I'll look into that myself.

**Comment by geoffthemedio** [comment]
possibly related to [62e6edc17f2](https://github.com/freeorion/freeorion/commit/62e6edc17f2#diff-85d057a3b1f5be4f02b74c50befe42216a56f4d4bb939d317dfc3f18d03df424R1091-R1093) which is adding fighters twice. No idea why I did that... possibly debug code that slipped into the final commit?

**Comment by Oberlus** [comment]
Is this fixed?

**Comment by geoffthemedio** [comment]
I think 6a95a8d27d fixed it, but confirmation would be good...

**Comment by Grummel7** [comment]
With current master I do not see any fighter ghosts.
