### ISSUE TITLE
System.SystemID

### ISSUE THREAD

**Issue by Grummel7** [freeorion/freeorion#4042]
Since https://github.com/freeorion/freeorion/commit/053257e1259eb71bf26324e937a35a3cb820ed65, system.systemID always gives -1, at least for the AI:
`planet=P_512<Subra α II> systemID=496, system=S_-1<Subra α>, systemID=-1 id=496`

**Comment by geoffthemedio** [comment]
Always, or just for loaded saves?

**Comment by geoffthemedio** [comment]
Can you try with https://github.com/freeorion/freeorion/commit/7d82eed493ff3aefd5ea82ed332fb628a9d2994f applied?

**Comment by Grummel7** [comment]
You are right, it happened only when loading a game saved before that change.
And your fix seems to work, at least I can load the save file again without getting an exception.

**Comment by geoffthemedio** [comment]
presumably fixed https://github.com/freeorion/freeorion/commit/7d82eed493ff3aefd5ea82ed332fb628a9d2994f
