### ISSUE TITLE
Confused Likes

### ISSUE THREAD

**Issue by Grummel7** [freeorion/freeorion#4043]
Build: 5da81ffc5f775bfe70c396104753b712a31750c6 plus 7d82eed493ff3aefd5ea82ed332fb628a9d2994f patched in.

I already observed it yesterday after the ghost fighter issue, but somehow this game was completely broken. Since I've played it with different versions, I suspected some more save file issue. This morning I started a new game, which looked okay up to now.

I just adopted diversity and moderation, then looked at my capital and was surprised about the stability (knowing that liberty + diversion should give -4 to Trith). Now this is how it looks like:
![confusedLikes](https://user-images.githubusercontent.com/20499830/183284079-f2126cd6-47e5-45f9-8074-1fb7ecce4cc4.png)

No dislike for diversion, but like and dislike for Scanning facilities? And I don't even own three scanning facilities. They should not like Bureaucracy neither.

Save file:
[ConfusedLikes.sav.gz](https://github.com/freeorion/freeorion/files/9276527/ConfusedLikes.sav.gz)

**Comment by Grummel7** [comment]
I just compiled various code bases and I can now say the issue has been caused by 8b1d7c3dd9ee9b58d160980613a1a6caa5162eea.

**Comment by geoffthemedio** [comment]
probably related to https://github.com/freeorion/freeorion/commit/f5d5f28675cee9fe3b2780b197ac94404d06b03e

**Comment by Grummel7** [comment]
> probably related to [f5d5f28](https://github.com/freeorion/freeorion/commit/f5d5f28675cee9fe3b2780b197ac94404d06b03e)

No, I can reproduce it when using 8b1d7c3dd9ee9b58d160980613a1a6caa5162eea "rework ValueTest::Eval to avoid repeated evaluations of valuerefs whe…" (which is older than f5d5f28675cee9fe3b2780b197ac94404d06b03e), but not with 17fbb82cd1ce2170196278a949074f35abe6ca26.

**Comment by geoffthemedio** [comment]
hopefully fixed in master

**Comment by Grummel7** [comment]
Indeed I cannot reproduce it with master anymore
