### ISSUE TITLE
Use `boost::format` to format strings

### ISSUE THREAD

**Issue by AndyMender** [freeorion/freeorion#4047]
---
name: Refactoring request
about: Use `boost::format` to format string templates
labels: "category:refactoring"
---
Feature request
===============

Idea
----
Several languages use string formatters to generate string templates, which are easier to reason about and easier to type. Since FreeOrion makes heavy use of Boost, it could be possible to utilize `boost::format` in a couple of places:
https://www.boost.org/doc/libs/1_69_0/libs/format/doc/format.html

Refactoring could be done in small batches to make PRs easier to read and test.

Gain
----
Easier to write and populate string templates with values.

Discussion
----------
Should I create a separate forum thread for this? The suggestion is a rather sizeable refactoring effort in the long-run and definitely up for discussion.

**Comment by geoffthemedio** [comment]
boost::format already is used in various places in the code, so I'm not sure what this issue is really about...

**Comment by AndyMender** [comment]
> boost::format already is used in various places in the code, so I'm not sure what this issue is really about...

I found quite some places where it's still not used, hence I opened an issue. If there is an ongoing effort to cover most of the code base, we can close the ticket.

If it's okay to proceed, I can open PRs to cover the bits of code that still don't use it.

**Comment by geoffthemedio** [comment]
Can you give some specific examples where you think boost::format should be used instead of what's done now?

**Comment by AndyMender** [comment]
> Can you give some specific examples where you think boost::format should be used instead of what's done now?

I think in the `DebugLogger` calls like [here](https://github.com/freeorion/freeorion/blob/master/combat/CombatSystem.cpp#L244) where readability suffers a bit. In places where the variable value is fed via `<<` at the end of a string it probably wouldn't help much.

**Comment by geoffthemedio** [comment]
````
DebugLogger() << "Planet " << obj->Name() << " visible empire stealth check: " << empire_detection
              << " >= " << obj->GetMeter(MeterType::METER_STEALTH)->Current();
````
seems fine / readable to me... I write lots of logger stream lines like that, though, so I'm used to it. 

Alternative would be something like:
````
DebugLogger() << boost::format("Planet %1% visible empire stealth check: %2% >= %3%")
    % obj->Name() % empire_detection % obj->GetMeter(MeterType::METER_STEALTH)->Current();
````
which is a bit easier to read in terms of what the overall layout of the result will be, but which I find a bit harder to follow in terms of what value goes in what spot, as I've got to keep track of where the substituted values are in the chained `%` list and relate that to the numbers in the `%X%` placeholders. So... I dunno.

**Comment by AndyMender** [comment]
Alright, if you say it wouldn't be much of an improvement, I can try working on something else :).

There is also another project called [inja](https://github.com/pantor/inja) which could be used instead, but that would require pulling in an extra dependency.

**Comment by geoffthemedio** [comment]
For that specific example, I don't see much benefit for a big refactor. If there's a broad consensus that most people find it much better, and you're really motivated, then I'm not super opposed, though. But if you're not really motivated for that specific issue, then I suspect there's other stuff that would be more useful to focus on...

**Comment by AndyMender** [comment]
> But if you're not really motivated for that specific issue, then I suspect there's other stuff that would be more useful to focus on...

I wanted to start with something like minor fixes / refactoring to get more familiar with the code base and saw `boost::format` as a fairly low hanging fruit. Since I'm new to this project, feel free to redirect me to a different ticket/issue and I can start a discussion on the forums to see if people are in general more widely interested in using `boost::format`.

**Comment by geoffthemedio** [comment]
> feel free to redirect me to a different ticket/issue

That's a bit difficult to do without knowing what you're capable of and interested in.
Something things that come to mind are:
-refactor GetMeterNameMap, NameToMeter, and MeterToName in ValueRef.cpp to use a constexpr array of pair, or two constexpr arrays to hold the strings (as string_view) and the MeterTypes, or a single constexpr array indexed by MeterTypes converted to suitable values (accounting for INVALID_METER_TYPE = -1), rather than the current use of a static map<string, MeterType>
-set up an A* search in the Pathfinder for fleet movement, with a cost function based on distance to the destination system. I briefly looked into it but decided to not bother due to all the boost over-engineered template code I'd need to wade through
-make MIN_RECOLONIZING_SIZE and MIN_RECOLONIZING_HAPPINESS into GameRules

Or for something more game-mechanicsy, make multi-ally supply network merging work, as discussed here: https://freeorion.org/forum/viewtopic.php?f=28&t=12322

**Comment by AndyMender** [comment]
> That's a bit difficult to do without knowing what you're capable of and interested in.
> Something things that come to mind are:
> -refactor GetMeterNameMap, NameToMeter, and MeterToName in ValueRef.cpp to use a constexpr array of pair, or two constexpr arrays to hold the strings (as string_view) and the MeterTypes, or a single constexpr array indexed by MeterTypes converted to suitable values (accounting for INVALID_METER_TYPE = -1), rather than the current use of a static map<string, MeterType>

Big thanks for the patience and advice. I will have a look at this task then. Meanwhile, I opened a forum thread here: https://freeorion.org/forum/viewtopic.php?f=9&t=12525

**Comment by Vezzra** [comment]
> For that specific example, I don't see much benefit for a big refactor.

@geoffthemedio, considering this, should this refactoring request be closed or do you want to keep it open?

**Comment by AndyMender** [comment]
Since the poll has no responses after around a month, I would say it's not exactly a burning issue. If there are specific sections of the code which would benefit from using `boost::format`, that could be discussed on individual PRs perhaps?

Feel free to close this ticket :)
