### ISSUE TITLE
`messages` window does not cleaned on game start

### ISSUE THREAD

**Issue by Cjkjvfnby** [freeorion/freeorion#405]
Steps to reproduce:
- run game
- start new game
- scroll message on top
- exit to main menu
- start new game
- check messages

Observed result:
- messages from previous game shown, scroll position same as previous game

Expected result: 
- clean messages window at start of game

`windows 7x64`
`v0.4.5+ [build 2015-11-22.dd23058] MSVC 2013`

**Comment by Vezzra** [comment]
Hm, clearing the message window on game start sounds reasonable...

**Comment by geoffthemedio** [comment]
Fixed? https://github.com/freeorion/freeorion/commit/64fbc2146e427aad59dc5e025f03638c83320fa3
