### ISSUE TITLE
Messages window up and down keys does not set cursor to the end of text

### ISSUE THREAD

**Issue by Cjkjvfnby** [freeorion/freeorion#406]
Steps to reproduce:
- type `hello` in Messages window and press `Enter`
- press `up key`

Observed Result:
- cursor at the beginning of line 

Expected result:
- cursor at the end of line

`windows 7x64`
`v0.4.5+ [build 2015-11-22.dd23058] MSVC 2013`

**Comment by Vezzra** [comment]
Oh, you mean, when cycling through the history you'd expect the cursor to be positioned at the end of the line instead of the beginning. Yep, sounds reasonable.

**Comment by geoffthemedio** [comment]
should be fixed

https://github.com/freeorion/freeorion/commit/3835c46b863ada0855326271ba9c21a3ba7fe8f8
