### ISSUE TITLE
Refactor Meter to Map code in ValueRefs.cpp

### ISSUE THREAD

**Issue by AndyMender** [freeorion/freeorion#4060]
Follow-up to a side discussion started in: https://github.com/freeorion/freeorion/issues/4047

Originally suggested by @geoffthemedio 
> -refactor GetMeterNameMap, NameToMeter, and MeterToName in ValueRef.cpp to use a constexpr array of pair, or two constexpr arrays to hold the strings (as string_view) and the MeterTypes, or a single constexpr array indexed by MeterTypes converted to suitable values (accounting for INVALID_METER_TYPE = -1), rather than the current use of a static map<string, MeterType>

I'm creating an issue ticket for this so it's clear someone's working on it. if it's preferable to simply open a draft PR instead, I will close this ticket and open a PR.

**Comment by Vezzra** [comment]
> I'm creating an issue ticket for this so it's clear someone's working on it. if it's preferable to simply open a draft PR instead, I will close this ticket and open a PR.

I guess opening a draft PR should be sufficient usually. However, you can of course also create an issue, but for the purpose of indicating that someone is working on it that someone should be assigned to the issue. I just did that now, I assigned you (@AndyMender) to this issue.

**Comment by AndyMender** [comment]
> > I'm creating an issue ticket for this so it's clear someone's working on it. if it's preferable to simply open a draft PR instead, I will close this ticket and open a PR.
> 
> I guess opening a draft PR should be sufficient usually. However, you can of course also create an issue, but for the purpose of indicating that someone is working on it that someone should be assigned to the issue. I just did that now, I assigned you (@AndyMender) to this issue.

Thanks! I was unable to assign myself previously, hence the initial confusion. I will remember about draft PRs for the future.
