### ISSUE TITLE
Game shows a lot of "Unkown" factors and that colonies are disconnected

### ISSUE THREAD

**Issue by Blue-Award** [freeorion/freeorion#4066]
Bug Report
==========

Environment
-----------

* **FreeOrion Version**: 2022-08-09.1d2ba57
* **Operating System**: Windows 10
* **Fetched as** 
  * Weekly development build

Description
-----------

I've downloaded recent official (windows) test build, 2022-08-09.1d2ba57

Something looks to be fundamentally off. Chiefly, colonies think they are disconnected from capital, even capital itself. So for example -10 to stability. But then there's "Unkown" factor that offsets that, and then some (I think the capital does not know it is capital so also no stability bonus for being the capital, except factored into the "Unkown").

Those "Unknowns" also show up in production, research, supply for example after adopting "Centralization". And game actually thinks I should not get those bonuses, so it projects the meters will fall down

So it's like client thinks I have no capital, but in the end things get tallied up correctly by the server, but client is confused and shows that stuff as "Unkown"

Expected Result
---------------
Well... That colonies show as connected to the capital, and effects from something like Centralization show up tagged as such rather than "Unkown"

Steps to reproduce
------------------
Just start the game and look at your capital. Perhaps adopt Centralization and advance turn to see some "Unkowns" (assuming your species cares about connection to capital, and otherwise has enough stability to have benefit from Centralization right away)

**Comment by geoffthemedio** [comment]
probably / mostly fixed by https://github.com/freeorion/freeorion/commit/fb2ebbfa80b3d1ca9be484717a07a3557f4ebe8e

**Comment by Vezzra** [comment]
> probably / mostly fixed by [fb2ebbf](https://github.com/freeorion/freeorion/commit/fb2ebbfa80b3d1ca9be484717a07a3557f4ebe8e)

@geoffthemedio: Sufficiently fixed so this can be closed as resolved, or should it stay open?

**Comment by geoffthemedio** [comment]
> Sufficiently fixed

someone else should check

**Comment by agrrr3** [comment]
i did yesterday a build based on current master and the display of capital bonus are fixed/have the expected values
