### ISSUE TITLE
ValueRef::Operation(OpType::NEGATE) looks the same in dump like ValueRef::Constant

### ISSUE THREAD

**Issue by o01eg** [freeorion/freeorion#4072]
Bug Report
==========

Environment
-----------

* **FreeOrion Version**: d94d75670fd1ecb46e454ceec5fb5e5f2520f67e
* **Operating System**: Devuan Linux
* **Fetched as** 
  * Compiled from source

Description
-----------
When I tried to understand what Python parser changed in produced structures in #4071 first I tried to use Dump and I didn't found anything because both produces same result -5.0 and -5.0. Maybe use same approach as https://github.com/freeorion/freeorion/pull/3911 so difference will be seen.

Expected Result
---------------
Dump for ValueRef::Operation(OpType::NEGATE) should look differently allowing to understand where which is used.

**Comment by geoffthemedio** [comment]
Negate prepends a `-`, which I guess would look the same as a negative constant if negate is applied to a positive constant. Not sure how better to represent it, though. Could maybe always have the inner expression within brackets?

https://github.com/freeorion/freeorion/blob/master/universe/ValueRefs.h#L2235

**Comment by o01eg** [comment]
@geoffthemedio Yes, I think it will be better.
