### ISSUE TITLE
Nascent Artificial Intelligence produce Unknown component in Research meter

### ISSUE THREAD

**Issue by o01eg** [freeorion/freeorion#4110]
Bug Report
==========

Environment
-----------

* **FreeOrion Version**: 2022-08-30.000f16b (also was in 2022-08-23.9b1afe0, but good in 2022-07-26.9439c8d)
* **Operating System**: Linux
* **Graphic card used**: Intel
* **Fetched as** 
  * Compiled from source

Description
-----------

After researching Nascent Artificial Intelligence Research meter doesn't change and show additional Unknown component with -1 value. It doesn't get solved even if connect as Observer:
![FO_2022-08-30_22-55-47](https://user-images.githubusercontent.com/397177/187532615-4eb78fcb-061c-44b4-8046-38bffbe038af.png)

Expected Result
---------------

No Unknown meter components.

Steps to reproduce
------------------

* Load MP game 
[FreeOrion_0016_20220830_194543.mps.zip](https://github.com/freeorion/freeorion/files/9456262/FreeOrion_0016_20220830_194543.mps.zip)
* Check Mesa β Research meter.

**Comment by MichaelCourtney** [comment]
I can produce both bug and not bug.

I get the unbugged version by saving and quitting to desktop, then reloading

**Comment by o01eg** [comment]
As I understand reloading is not enough, it still present same turn after reload but gone next turn.

**Comment by MichaelCourtney** [comment]
yes. that's what I get. If the unknown malus is already there, it'll take a turn. If I save and quit to desktop on turn 1 the bug never shows up.

**Comment by o01eg** [comment]
I'm bisecting it now and it looks like it was broken between 3ef85c1ba3ac8707b88ee956170a0142701fb539 and a5d10e42f0f57822b67530e97f8029a2e05de76d commit @geoffthemedio

**Comment by o01eg** [comment]
Looks like 9c317f7492877ebbc3cde7639f8712fb672be2b3 broke it.

**Comment by geoffthemedio** [comment]
should be fixed by https://github.com/freeorion/freeorion/commit/6807e0bb17a1ecc031b241d92121299057c123b6

**Comment by o01eg** [comment]
Yes, it's fixed in `master`
