### ISSUE TITLE
Formatting copied from text window

### ISSUE THREAD

**Issue by Cjkjvfnby** [freeorion/freeorion#412]
Steps to reproduce:
-  type `hello` in chat
- select colored message and press `Copy To Buffer` shortcut (`CTRL+c` for windows)
- paste result somethere

Observed result:
  `Human_Player: hello</rgba>`

Expected result:
  `Human_Player: hello`

In debug mode some special chars copied too (caret return for example). Cursor moves to the start of line after paste of text in that case.

`windows 7x64`
`v0.4.5+ [build 2015-11-22.dd23058] MSVC 2013`

**Comment by Cjkjvfnby** [comment]
Maybe this ticket have same cause as https://github.com/freeorion/freeorion/issues/406

**Comment by geoffthemedio** [comment]
How should this work? As now, it leaves in any formatting text that appears, which is advantageous as it allows formatted text to be copied with the formatting... as long as the opening tags for the relevant formatting are included, and with potentially quirky results if the closing tags are not included in the selected region of text.

An alternative is to strip all the formatting tags when pasting, which avoids quirks, but that doesn't limit functionality somewhat.

**Comment by Cjkjvfnby** [comment]
This tags are relevant only for game. I don't have any use-case for copy-pasting tags. Solution with fix of the paste suits me too.

**Comment by geoffthemedio** [comment]
should be fixed, by stripping tags from copied text before passing to the clipboard.
