### ISSUE TITLE
AI-Client is does not get modified game rules

### ISSUE THREAD

**Issue by Grummel7** [freeorion/freeorion#4124]
The costs for buildings and ships that the AI gets do not include cost factors configured at game start.

To reproduce, start a game with AI-debugging and a building cost factor of 0.5.
Check that the cost for a Military Command in your client is shown as 40.
Use the chat window and enter:
```
start 2
fo.getBuildingType("BLD_MILITARY_COMMAND").productionCost(2, e.capitalID)
fo.getGameRules().getDouble("RULE_BUILDING_COST_FACTOR")
```
The replies show that the AI thinks it costs 80 and the factor is 1.0

See also [this forum thread](https://www.freeorion.org/forum/viewtopic.php?p=114062#p114062)

After a little testing it seems to me the AI simply gets the default value of all game rules.

**Comment by geoffthemedio** [comment]
try with https://github.com/freeorion/freeorion/pull/4188/commits/d281e8728ade0e44161b456532ac0cee5d175d16 ?

**Comment by Grummel7** [comment]
> try with [d281e87](https://github.com/freeorion/freeorion/commit/d281e8728ade0e44161b456532ac0cee5d175d16) ?

```
[05 Oct 20:26:20] Human_Player: fo.getGameRules().getDouble("RULE_BUILDING_COST_FACTOR")
[05 Oct 20:26:20] AI_1: 1.7
```
Looks good.

**Comment by geoffthemedio** [comment]
should be fixed by https://github.com/freeorion/freeorion/commit/555b38021412c49dde95839a043846e55d0931c6
