### ISSUE TITLE
Client crash when click Options UI Automatically reposition windows

### ISSUE THREAD

**Issue by mishavee** [freeorion/freeorion#4155]
Bug Report
==========

Environment
-----------
* **FreeOrion Version**: v0.4.10+ [build 2022-09-21.b9809e4] CMake
* **Operating System**: Manjaro 21.3 XFCE 
* **Graphic card used**: i5 3rd gen integrated graphics
* **Fetched as** 
  * Compiled from source
From AUR repository: freeorion-git 0.4.10.with.FreeOrionSDK.v12.1255.g6a9b32fec-1

Description
-----------
Clicking the UI option "Automatically reposition windows" cause the game to exit with the following text to console 

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  OptionsDB::Get<>() : Attempted to get nonexistent option "".
Aborted (core dumped)
```

The log files don't show any change.
The same crash happens if there is or isn't a game running.

Steps to reproduce
------------------
* First step.
Click Options > UI > Automatically reposition windows
* Issue occurs.

**Comment by geoffthemedio** [comment]
should be fixed by https://github.com/freeorion/freeorion/commit/d4f8cff2e5ec34593aaa0534815284d1edfac0cf
