### ISSUE TITLE
Refuel Bug

### ISSUE THREAD

**Issue by MichaelCourtney** [freeorion/freeorion#4190]
Weekly test build version is 2022-08-30.000f16b. 21st Multi-player

Ship fails to move on turn it refuel to 1.0 fuel

https://www.freeorion.org/forum/viewtopic.php?f=28&t=12610

**Comment by MichaelCourtney** [comment]
[fuelbug.zip](https://github.com/freeorion/freeorion/files/9716703/fuelbug.zip)

bugged scout

test build (build 2022-10-04.f92cec7)

**Comment by Grummel7** [comment]
That's odd. I've added some debugging to see the actual values. Here is what I got:
```
freeorion.log:18:22:27.683334 {0x00007fd82ec95e80} [info] client : FleetWnd.cpp:1640 : min_fuel = 0.899
freeorion.log:18:22:27.814622 {0x00007fd82ec95e80} [info] client : FleetWnd.cpp:1640 : min_fuel = 0.999
```
When I changed the increase in from 0.1001 to 0.101, it worked as expected. Does the FOCS parser truncate number to 3 decimal places?

I guess we could change the value to 0.101, players have to rely this small increase for 50 turns to actually see the extra.
Or we change the parser to accept a 4th place.

**Comment by o01eg** [comment]
> Does the FOCS parser truncate number to 3 decimal places?

Could it be related to those changes in meters? https://github.com/freeorion/freeorion/commit/c35dfd02f5a166b2838d608be98a66ab5d248364

Maybe we should calculate other thing with fixed point arithmetic too?

**Comment by Grummel7** [comment]
> Could it be related to those changes in meters? [c35dfd0](https://github.com/freeorion/freeorion/commit/c35dfd02f5a166b2838d608be98a66ab5d248364)

Ah, meters are actually fixed point values. Well, that explains why the extra 0.0001 is lost. But then it does not explain where the rounding error occurs. Obviously not when adding 0.1001 to it.

Well, here it is:
```
client : FleetWnd.cpp:1640 : min_fuel = 1.099
client : FleetWnd.cpp:1640 : min_fuel = 0.098
```
Flying a starlane costs 1.001 fuel!?

> Maybe we should calculate other thing with fixed point arithmetic too?

Which other do you have in mind? Meters use only + and -, which makes fixed point arithmetic trivial, general calculation would be more complicated and possibly even increase rounding error due to lack of precision.

**Comment by Grummel7** [comment]
Got it: Calculations were still done using floats and then conversion to fixed points truncated the result, that why adding -1 could decrease the value by 1.001.
