### ISSUE TITLE
Invalid ship design entry in logs

### ISSUE THREAD

**Issue by Cjkjvfnby** [freeorion/freeorion#4205]
Some ship designs are invalid but fixed automatically.

I have reproduced this with `v0.4.10+ [build 2022-10-04.f92cec7] MSVC 2022`

`freeorion.log` contains 6 entries related to the `SP_SOLAR_CONCENTRATOR`

```
ShipDesign.cpp:527 : Invalid ShipDesign part "SP_SOLAR_CONCENTRATOR" can't be mounted in SL_EXTERNAL slot. Removing "SP_SOLAR_CONCENTRATOR"
ShipDesign.cpp:564 : ShipDesign was made valid as:
```

**Comment by geoffthemedio** [comment]
should be fixed by https://github.com/freeorion/freeorion/commit/c6858fd5b0fe2b2f45244d64e6d678a97586b258
