### ISSUE TITLE
FTBFS trunk 0086924b4951d85df6cd5a452f4e56d7f3c81cf7 Hopefully fix part drag over top of other part not working issue.

### ISSUE THREAD

**Issue by ghost** [freeorion/freeorion#422]
UI/DesignWnd.cpp:91:18: error: ‘PC_FIGHTER_BAY’ was not declared in this scope
UI/DesignWnd.cpp:92:18: error: ‘PC_FIGHTER_WEAPON’ was not declared in this scope

These symbols are added in that commit, but never defined.

**Comment by geoffthemedio** [comment]
hopefully fixed

https://github.com/freeorion/freeorion/commit/f6f1bec94d023614cc99ed25e77d494ff7677e83
