### ISSUE TITLE
AI API method is hard to call

### ISSUE THREAD

**Issue by Cjkjvfnby** [freeorion/freeorion#4228]
validShipDesign accepts a vector as an argument, and it's a bit hard to create this vector, and using a list is not possible.  
The first argument design is also a bit confusing since you don't actually need it.  

Here is a sample how this code could be called
```python
d = fo.getShipDesign(list(e.availableShipDesigns)[0])
fo.validShipDesign(d, d.hull, d.parts)
```

I'd recommend removing this binding (we do not use it right now and could add it later).
Or allow call it like:

````python
fo.validShipDesign(d,  'SH_COLONY_BASE', ['CO_OUTPOST_POD', '', ''])
````

```cpp
py::def("validShipDesign",
                +[](const ShipDesign& design, const std::string& hull, const std::vector<std::string>& parts) -> bool
```

Error when trying to use list.
```
  File "J:\games\FreeOrion\python37.zip\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
Boost.Python.ArgumentError: Python argument types in
    freeOrionAIInterface.validShipDesign(shipDesign, str, list)
did not match C++ signature:
    validShipDesign(class ShipDesign, class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >, class std::vector<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::allocator<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > >)
```

**Comment by geoffthemedio** [comment]
something like https://github.com/freeorion/freeorion/commit/49e1ae593d3fb86f4eb9c577dac12b3bea2f9bc6 ?

**Comment by Cjkjvfnby** [comment]
Yes.

**Comment by Cjkjvfnby** [comment]
Totally unrelated, what does method `count(val)` of the Set does?
Does `size` and `__len__` return the same result?  If yes, I'd prefer to remove the size and keep only `__len__`.

```
class IntSet:
    def count(self, number: int) -> int: ...

    def __len__(self) -> int: ...
    def size(self) -> int: ...

**Comment by geoffthemedio** [comment]
> what does method `count(val)` of the Set does?

Returns 1 if the set contains `val` and 0 otherwise. Can be removed.

> Does `size` and `__len__` return the same result?

Yes.

> If yes, I'd prefer to remove the size and keep only `__len__`.

OK.

https://github.com/freeorion/freeorion/commits/grooming_mostly

**Comment by geoffthemedio** [comment]
validShipDesign parameter: https://github.com/freeorion/freeorion/commit/19625f2a702389a7742be22d286c8b9d0bf018e4
set wrapper: https://github.com/freeorion/freeorion/commit/b07f32ca1cad0394db5540eeb35613ed4632c139
