### ISSUE TITLE
Independent Population special does not work

### ISSUE THREAD

**Issue by Blue-Award** [freeorion/freeorion#4265]
Bug Report
==========

Environment
-----------

I can see it still happening on 2022-10-17.7060115 but it is visible in current MP21 as well, where I set two planets to independence

Description
-----------
There's this Independent Population special created after granting planet independence, that is supposed to keep the population max from before independence, where the original empire could have a bunch of population boosting techs. Alas, the special simply does not work and population instead goes to whatever it would be without the special. This still includes some things like species population boost, phototropic, self-sustaining, gaia... But for example exobots on asteroids would die off because without population boosting techs (including boosting on 'poor' environment) they can't sustain population on asteroids

Expected Result
---------------
The population of planet that was granted independence trends towards the population max which would include the Independent Population Special

Steps to reproduce
------------------

Can be set up easily in test mode with cheap techs and buildings

* research some population boosting techs like subterranean habitation
* settle some planet, for best effect some very bad environment that would be inhospitable without the growth techs
* grant the planet independence
* see that the independent population special is not taken into account, for example species die off without it in unsuitable environments, like independent exobots on asteroids, or the max simply stabilizes at a value that excludes the special

**Comment by agrrr3** [comment]
oops seems i forgot to make a PR... wait a sec
