### ISSUE TITLE
Luxury resources pedia pages should inform about relation to "Capital Markets" policy.

### ISSUE THREAD

**Issue by gendalv** [freeorion/freeorion#4282]

**Comment by MichaelCourtney** [comment]
Note, Missing:

Links to capital markets and black markets on luxury resources page.
List of luxury resources.
Bonus for influence focus on luxury special.

**Comment by Vezzra** [comment]
Has this been completely addressed by #4303 and can be closed, or is there still work to do?

**Comment by MichaelCourtney** [comment]
> Has this been completely addressed by #4303 and can be closed, or is there still work to do?

As far as I'm aware yes. I don't plan to add anything without further comment from gendalv

**Comment by Vezzra** [comment]
Alright, @gendalv hasn't commented, so I assume the issue has been resolved. I'm closing this ticket. Should there be any work left to do, we can reopen.
