### ISSUE TITLE
Exobot Productivity malus isn't working.

### ISSUE THREAD

**Issue by gendalv** [freeorion/freeorion#4288]
"Decreases the stability and production output of non-exobot populated planets in the empire by 1.00."

2022-10-17.7060115

**Comment by MichaelCourtney** [comment]
The scripting is specific to industry-focused planets, the pedia entry is not. Is this just a pedia problem? Is the penalty correctly there on non-exobot industry planets?

**Comment by Vezzra** [comment]
Fixed by #4290
