### ISSUE TITLE
Star type tab isn't working

### ISSUE THREAD

**Issue by gendalv** [freeorion/freeorion#4291]
![321](https://user-images.githubusercontent.com/10047774/198392427-7885a3bf-14e5-4de2-bf78-069d14f3a9cf.jpg)
 2022-10-17.7060115

**Comment by geoffthemedio** [comment]
works for me
![objects](https://user-images.githubusercontent.com/11386908/198410162-1c1a81c5-9d2b-4a0d-83fc-f21fa9c26857.png)

**Comment by gendalv** [comment]
I thought star type implies the planet is part of *.
How do you even get stars to be shown? I'm only seeing planets list.

**Comment by geoffthemedio** [comment]
use the filters button at the bottom left
