### ISSUE TITLE
English Pedia entries show incorrect values for weapon bonuses

### ISSUE THREAD

**Issue by rl-starbound** [freeorion/freeorion#4296]
When looking at the direct weapon ship parts (mass drivers, lasers, plasma beams, death rays) in the builder or pedia, the descriptions show incorrect weapon bonus values. For example, in `en.txt` the variable `SR_WEAPON_4_1_DESC` says, "Each death ray on a ship built by a species with the piloting trait will do an additional 30 damage per piloting level (-30 for Bad Pilots)", but the actual modifier in `scripting/species/common/weapons.macros` for death rays is 5.

I'm using Flathub v0.4.10.2 but I've checked the English stringtables in master and the issue is there as well. The French string tables appear to be correct (I don't speak French, but I can read the numbers in the entry).

I'll make a PR to fix this, but I wanted to check to make sure that it's not some intended future feature.

**Comment by MichaelCourtney** [comment]
> For example, in `en.txt` the variable `SR_WEAPON_4_1_DESC` says, "Each death ray on a ship built by a species with the piloting trait will do an additional 30 damage per piloting level (-30 for Bad Pilots)", but the actual modifier in `scripting/species/common/weapons.macros` for death rays is 5.

It's actually: ([[SHIP_WEAPON_DAMAGE_FACTOR]] * 5) where the default value of ship_weapon_damage_factor is 6

**Comment by rl-starbound** [comment]
Where do you see that the default is 6? On my 0.4.10.2 installation, the default is 1.

Actually, I can't find a default value in the source code, so that's the default value I see in the UI (New Game `Balance` option `Ship Weapon Damage Scaling`) after I start a new game (and have deleted my config and prior saves, just in case). I see the other scaling factors have defaults set in `scripting/game_rules.focs.txt`, but not `RULE_SHIP_WEAPON_DAMAGE_FACTOR`.

**Comment by Grummel7** [comment]
30 is correct in trunk, although it would be better if Pedia could be reflect the game rules instead of hard-coding the defaults.

The issue mentions 0.4.10.2. Indeed, e024daae0572e20d41dab039be91b381bf720798 looks suspicious. Why was this merged into 0.4.10? That branch does not have a game rule for damage scaling, does it?

**Comment by rl-starbound** [comment]
> if Pedia could be reflect the game rules instead of hard-coding the defaults

:+1:

**Comment by MichaelCourtney** [comment]
> Where do you see that the default is 6? On my 0.4.10.2 installation, the default is 1.
> 
> Actually, I can't find a default value in the source code, so that's the default value I see in the UI (New Game `Balance` option `Ship Weapon Damage Scaling`) after I start a new game (and have deleted my config and prior saves, just in case). I see the other scaling factors have defaults set in `scripting/game_rules.focs.txt`, but not `RULE_SHIP_WEAPON_DAMAGE_FACTOR`.

In master it's defined in ShipHull.cpp, I assume its the same place in 0.4.10.2, I don't have a copy of that on my PC

I'll fix up the pedia in master to reflect the game rules for weapons today.

**Comment by rl-starbound** [comment]
I see it, thanks. Yes, it's 6.0 on `master`, but 1.0 on `v0.4.10.2`.

**Comment by MichaelCourtney** [comment]
> I'll fix up the pedia in master to reflect the game rules for weapons today.

Well I would if it was actually simple. I'm running into an issue that the in game values are generated by summing multiple values generated by a bunch of macros. The stringtables aren't set up to handle that

**Comment by agrrr3** [comment]
> Well I would if it was actually simple. I'm running into an issue that the in game values are generated by summing multiple
> values generated by a bunch of macros. The stringtables aren't set up to handle that

@MichaelCourtney not sure where the discussion was/is, but there are multiple possibilities - but i guess they need backend support/implementation - could you point me to a forum thread? i could give input

**Comment by MichaelCourtney** [comment]
> > Well I would if it was actually simple. I'm running into an issue that the in game values are generated by summing multiple
> > values generated by a bunch of macros. The stringtables aren't set up to handle that
> 
> @MichaelCourtney not sure where the discussion was/is, but there are multiple possibilities - but i guess they need backend support/implementation - could you point me to a forum thread? i could give input

Looks like you found it, but reference it's:

https://www.freeorion.org/forum/viewtopic.php?f=2&t=12638

**Comment by agrrr3** [comment]
Can we close this, as whatever the result is, as it applies to 0.4 ?

**Comment by Vezzra** [comment]
> Can we close this, as whatever the result is, as it applies to 0.4 ?

Meaning, it has been fixed in 0.5, correct?

**Comment by rl-starbound** [comment]
I haven't been following development for a while. I guess it's okay to close this if it only applies to an EOL branch.

There was a question in the middle of the thread about whether to have the pedia entries hard-coded for default values or dynamically generated based on the user's prefs. Did that question get resolved, and if not, should it keep this issue open? I won't close the issue now, pending an answer to that question, but I'm okay with closing it if the maintainers want to.

**Comment by Vezzra** [comment]
> I guess it's okay to close this if it only applies to an EOL branch.

Hence my question if this issue has been fixed in 0.5, or if it is still present there. If the former, this will be closed, as we won't backport any fixes to the 0.4.10 release. We only ever maintain the current release branch (which is 0.5 now).

If the latter, this should stay open. So - is the issue as reported here present in 0.5?

**Comment by agrrr3** [comment]
> So - is the issue as reported here present in 0.5?

could reproduce in 0.4.10, but is fixed in 0.5

it is "broken" (it is ok for the default value but does not show the correct values if you change the rule) in master though and #4437 should fix that

**Comment by Vezzra** [comment]
> it is "broken" (it is ok for the default value but does not show the correct values if you change the rule) in master though and #4437 should fix that

Well, in this case I think this issue should only be considered completely fixed once #4437 has been merged. So, I'm leaving this open and linked it to that PR, so it gets closed once #4437 gets merged.
