### ISSUE TITLE
Game crash to menu on end of turn.

### ISSUE THREAD

**Issue by gendalv** [freeorion/freeorion#4297]
And why is it saying "The connection to the server has been lost" when it does it? It also gives the same message, when clicking "single player"->"Cancel".
[save.zip](https://github.com/freeorion/freeorion/files/9894606/save.zip)
`pass: ase[vofnjwqeofih{FGUEbw`
 2022-10-17.7060115

**Comment by geoffthemedio** [comment]
What version?

The server process is separately launched and runs on the same system for single player games. If the server crashes, then the client loses the connection to it.

Zip seems to be broken.

**Comment by gendalv** [comment]
It's not broken you need 7z

**Comment by geoffthemedio** [comment]
should be fixed by 5304127ac8d7ab06b966991a321c5f0eea0c4763

**Comment by geoffthemedio** [comment]
https://github.com/freeorion/freeorion/commit/181fe668e49a90f7ea64a41f24da3b55b9d09c8a

**Comment by gendalv** [comment]
That save might not be crashing in the new version, but still is unplayable it seems, the message window spams errors it seems.

**Comment by geoffthemedio** [comment]
Make a new issue about whatever errors you're seeing.
