### ISSUE TITLE
AI lag in mid/end game

### ISSUE THREAD

**Issue by andresmrm** [freeorion/freeorion#430]
It seems the AI is lagging to finish it's turn after ~150 turns.

It happened in a map of about 20 systems and 5 AI. Even after I killed all of them, around turn 300, they still took +30s to finish turn (checked the green icon in Empire list; save button was locked until they finished too). Closing the game and loading again helped, reduced time to about 10s.

Tested in a bigger map (50 systems) with only monsters, no AI, and turns finished fast (~1s) even around turn 300. That's why I think it's an AI problem.

version: 0.4.5+ 
OS: Arch Linux

**Comment by andresmrm** [comment]
Played a map with 120 systems, 3 AI. Started to lag a little (~3s per turn) around turn 300.
Maybe it's related to the number of AIs?

**Comment by geoffthemedio** [comment]
Depending how many processor cores you have and how long it takes each to process turn updates, turn processing time would make sense to depend roughly linearly on the number of AIs, with a large contribution from other stuff as well.

**Comment by andresmrm** [comment]
I have 8 cores here, didn't notice if the game was using all of them.

But the strange part to me is to use +30s to process dead AIs.
I have no idea about how this AI works, but maybe it would help to check if the AI still has any systems/ships before wasting time processing it.

**Comment by MatGB** [comment]
I've long thought we should kill the AI processes when they're eliminated, and now we actually have a 'player eliminated' criteria for the victory conditions I do think that ought to be implemented, in the event that gifts/diplomacy/whatever end up needing to resurrect or create new AIs that could be done at the time, but frankly I've never seen the point of allowing that, defeated is defeated. Not my call and way beyond my ability either way.

**Comment by Vezzra** [comment]
Hm, that sounds more like as if the AI processes are hanging somewhere, maybe a timeout? Especially dead AIs taking 30s to complete a turn sounds strange. Never encountered something like that, for me the lag in later game is always UI responsiveness going down due to many game objects choking effects processing.

@andresmrm, what exactly are your system specs?

**Comment by andresmrm** [comment]
Specs:
Intel(R) Core(TM) i7-3610QM CPU @ 2.30GHz
8Gb of RAM
Intel Corporation 3rd Gen Core processor Graphics Controller
NVIDIA Corporation GF108M GeForce GT 630M
(using one or the other graphic card seems to have no impact on game performance)

---

I started a new game: 200 systems, 10 AI, I'm at turn 400 (1 AI is dead by now).
If I wait AI to finish processing to pass turn, it takes ~6s to start the new turn.
If I pass the turn just when it starts (AI just started to process its turn), it takes ~20s for the AI to finish process (I'm looking at Empires window) and then more ~6s to start the new turn.
This time I used a chronometer to measure the times and they seem to have low variation.
Times measured after a game restart.

I'm watching processor core use with **top**. It seems to use all the 8 cores, at 100%, when l pass the turn. Then, when the **Turn** button is enabled again, it still uses ~4 cores for ~5s. But after that, for ~15s, it seems to use only 1 core, at 100%, to finish processing AI, not all cores.

**Comment by geoffthemedio** [comment]
Does this help?

https://github.com/freeorion/freeorion/pull/431

**Comment by karlexceed** [comment]
Just wanted to chime in that I've noticed this too; from a fresh compile of 0.4.5 on Ubuntu 15.04, using all defaults for Quick Play. First several dozen turns are fast, around 100 turns they start becoming noticeably slower. On my dual core laptop, it becomes excruciating. On my quad core desktop, just takes a bit longer.

**Comment by geoffthemedio** [comment]
Check if merging https://github.com/freeorion/freeorion/pull/431 made any difference.

Probably should also to disable anything complicated (eg. pickling the AI state data) in the response to a save game info request.

**Comment by andresmrm** [comment]
I tested the EliminatedEmpiresPythonAI branch in a map with ~200 systems, 10 AIs.
They started to lag around turn 100.
Now I'm at turn ~400, just killed all AIs, but it's taking ~14s for AI to finish processing, and ~7s to change turn. So a "quick turn" (when I pass turn just after it starts) is taking ~21s.

I noticed that 2 eliminated AI stopped playing (in the beginning of the turn they quickly change from '>' to '...'), but the other 8 still stay in '>' for ~14s.

**Comment by geoffthemedio** [comment]
Since there are 10 of them, some of the AIs may have to wait for the others to finish playing before getting any CPU time, depending how the threads / processes are being scheduled.

**Comment by Vezzra** [comment]
Well, he said he had _all_ AIs eliminated, so all AIs should abort any calculations immediately. Why 8 of them still take ~14s to do their turn is weird...

**Comment by Vezzra** [comment]
@karlexceed, #431 has been merged (commit 16e3922dec027bb2baeeeea094dede83f0ae9052), can you check if that makes any difference for you?

**Comment by geoffthemedio** [comment]
It doesn't help much for the AIs to abort calculations if the AI client spends a bunch of time just serializing / deserializing the gamestate updates. His tests were also probably done before the early aborts were added for save game state requests.

**Comment by Vezzra** [comment]
Well, he mentioned the AIs displaying the ">" indicating they were actually in the "thinking" phase. I assumed the ">" wouldn't be shown during serializing/deserializing, but I'm probably wrong about that.

But it would certainly be interesting the hear how it works for him now, with the additional aborts for save game state requests. @andresmrm?

**Comment by Vezzra** [comment]
@andresmrm, are you still there? Need further feedback from you, see above...

**Comment by andresmrm** [comment]
Hi, @Vezzra! Sorry for the long delay. Had a problem with my previous HD and had to find a new one.
Still didn't installed FreeOrion again. Do you want me to try it? Git version?

**Comment by Vezzra** [comment]
Hi @andresmrm, good to see you again :wink:

Yeah, if you could rerun your tests with current master and report back, that would be great. We are currently trying to prepare for the next release, and need to clean up all those old issues lying around...

**Comment by andresmrm** [comment]
Just did a test, map with 50 systems, 6 AI. I'm the last surviving at turn 300. When passing turn some AIs stay about 2s in the ">" green icon and then go to "...". So for me it's great! Feel free to close the issue.

**Comment by Vezzra** [comment]
Thanks!
