### ISSUE TITLE
LGTM.com will be shut down in December 2022

### ISSUE THREAD

**Issue by o01eg** [freeorion/freeorion#4313]
Bug Report
==========

Environment
-----------

* **FreeOrion Version**: any

Description
-----------

As it noted in LGTM site, it will be shut down soon: https://lgtm.com/ 
They propose to move to GitHub tools https://github.blog/2022-08-15-the-next-step-for-lgtm-com-github-code-scanning/

Expected Result
---------------

Use GitHub code scanning

**Comment by Cjkjvfnby** [comment]
I'd say check the reports.  Fix things that we can and let it go.  

Personally, I don't find it very useful for Python code.   We already have a bunch of linters. 


Not sure about our GitHub action resources.  @geoffthemedio ?

> https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/about-code-scanning#about-billing-for-code-scanning
Code scanning uses GitHub Actions, and each run of a code scanning workflow consumes minutes for GitHub Actions. For more information, see "[About billing for GitHub Actions](https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions)."

**Comment by geoffthemedio** [comment]
> Not sure about our GitHub action resources. @geoffthemedio ?
> 
> > [](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/about-code-scanning#about-billing-for-code-scanning)

I'm not sure what you want to know / are asking, but CodeQL already runs and produces reports, eg. https://github.com/freeorion/freeorion/security/code-scanning (requires project-associated log in to see)

**Comment by Cjkjvfnby** [comment]
I can see some warnings, but Python code is not covered.  I won't miss it, since I rarely watch LGTM reports.

Do you care about CodeQL reports for C++ code?

**Comment by geoffthemedio** [comment]
Occasionally it reports something useful.

**Comment by hifron** [comment]
Some open source projects have on their README.md file message(seen to user as image, but probably is text plugin) saying grade quality of project code(from LGTM)...

**Comment by geoffthemedio** [comment]
I uninstalled LGTM from the repository and will delete the .yml d76f3e0652048771bb223436534452246204c40b
