### ISSUE TITLE
Ship Design window is broken in master (d5582f7 ... 42ad0e1)

### ISSUE THREAD

**Issue by Oberlus** [freeorion/freeorion#4319]
Bug Report
==========

Edited for better context and removed the already fixed AI issue.

Environment
-----------

* **FreeOrion Version**: d5582f7 ... 42ad0e1
* **Operating System**: Ubuntu 20.04
  * Compiled from source

Description
-----------

The ship design window is broken, the buttons for Available and Unavailable hulls and ship designs don't work as expected.
Enabling or disabling Available or Unavailable just clears the list of hulls and ship designs.
Double clicking on a basic hull (the ones showed at start) makes visible all hulls and ship designs, regardless of the state of the available/unavailable buttons.

Steps to reproduce
------------------
Start a quick game and try to design ships with available and unavailable hulls.

[freeoriond.log](https://github.com/freeorion/freeorion/files/9980197/freeoriond.log)
[freeorion.log](https://github.com/freeorion/freeorion/files/9980198/freeorion.log)

**Comment by geoffthemedio** [comment]
`availableFoci` should be fixed by https://github.com/freeorion/freeorion/pull/4318

**Comment by Vezzra** [comment]
@geoffthemedio, I'm confused - has the issue been fixed or not? Or only partially?

The reported issues seem quite serious and game breaking. If this can't be completely fixed until Sunday, shall I proceed with the creation of the release branch nonetheless, or postpone?

**Comment by geoffthemedio** [comment]
there are two issues. one was fixed.

**Comment by Oberlus** [comment]
Checked with latest master, the AI issue is solved, the ship design window problem remains.

**Comment by Oberlus** [comment]
> The reported issues seem quite serious and game breaking.

It is gamebreaking. Not to the point of making the game impossible to play, but designing ships becomes quite cumbersome and unaware players could not find the way to design the ships they want.

**Comment by geoffthemedio** [comment]
> the buttons for Available and Unavailable hulls and ship designs don't work as expected.

hopefully fixed by 6af34c7c18fdddc709916f0b6ed0d6e9efb55efd

**Comment by Vezzra** [comment]
Excellent 😃
