### ISSUE TITLE
Gateway to the Void isn't working for Monsters

### ISSUE THREAD

**Issue by magnusviri** [freeorion/freeorion#4328]
Bug Report
==========
Gateway to the Void isn't working for Black Kraken.

Environment
-----------

* [FreeOrion_2022-11-14.22c61c1_Test_MacOSX_10.12.dmg](https://sourceforge.net/projects/freeorion/files/FreeOrion/Test/FreeOrion_2022-11-14.22c61c1_Test_MacOSX_10.12.dmg/download)
* Mac OS X 12.6

Description
-----------
The Black Krakens can go through Gateway to the Voids. Other fleets can't.

Expected Result
---------------
Black Krakens should not appear at Pinatha because they should've died at Gacrux.

Steps to reproduce
------------------
It's turn 265 in the save game. There's 2 Black Krakens at Gion. They go to Gacrux, which has a gateway to the void. **It looks like they die there** in turn 266, but then in turn 267 they show up at Pinatha. There might be other Black Krakens but it doesn't make sense that they just suddenly appear at Pinatha.

There are Gateway to the Voids all over the map. If you click "next turn" over and over you can watch them just go all over the place.

[save-20221119_144011.sav.zip](https://github.com/freeorion/freeorion/files/10050842/save-20221119_144011.sav.zip)

**Comment by magnusviri** [comment]
Actually, I played another game and it isn't stopping any monsters. It looks like it kills AI ships though. And now I'm wondering if maybe it is stopping some monsters, but not all. Either way, the monsters disappear when they land on the star. But then they reappear the next turn travelling from the star system with the GttV.

**Comment by geoffthemedio** [comment]
https://www.freeorion.org/forum/viewtopic.php?p=115227#p115227
