### ISSUE TITLE
Android Builds Failing

### ISSUE THREAD

**Issue by geoffthemedio** [freeorion/freeorion#4336]
https://github.com/freeorion/freeorion/actions/runs/3613945375/jobs/6090282988

Probably not related to that banch's changes...

**Comment by bend-n** [comment]
Sorry about this, the setup-python action just randomly started failing. I thought it wouldnt affect you though, as o01eg has his own containers. It seems its a [upstream setup-python bug](https://github.com/actions/setup-python/issues/556), not related to my container changes. You should be able to
```diff
   - name: Setup
-    uses: bend-n/godot-actions/.github/actions/setup-godot@main
+    uses: bend-n/godot-actions/.github/actions/setup-godot@0bf36a3
```

**Comment by bend-n** [comment]
this is fixed

**Comment by geoffthemedio** [comment]
re-running a recent test build...

**Comment by bend-n** [comment]
The glibc error is because https://github.com/o01eg/godot-builds/commit/5c2addaf272f2388f6d9ea889af862109fadde25 your containers arent running on ubuntu:jammy

**Comment by geoffthemedio** [comment]
so just partly fixed, then...

**Comment by o01eg** [comment]
I've tried to switch back to upstream container in PR.
