### ISSUE TITLE
Cancel gifting of newly conquered planet by former owner (or cancel invasion)

### ISSUE THREAD

**Issue by Blue-Award** [freeorion/freeorion#4345]
Bug Report
==========

Environment
-----------

* **FreeOrion Version**: MP22 one, 2022-11-01.6387e2e, presumably others too
* **Fetched as** 
  * Weekly development build

Description
-----------
In current slow multiplayer game, MP22, there is this specific setup of who is allied and at peace to whom. I am at peace with Daybreak, at war with Endhu, Endhu is allied to Daybreak. I have anticipated that they want to gift Endhu's planet at Duna a to Daybreak, so I am not able to capture it later, and moved on with a troop ship. 

So turn 46, I am there with troop ship and ordering invasion of Duna a II. Same turn, Endhu orders gifting of the planet

Come turn 47, I get the usual sitrep about invasion - ground battle with Endhu, Duna a II was captured by BlueAward. However, the gifting order "stuck" and the planet ended up with Daybreak after all, so I lost the troop ship for nothing

Expected Result
---------------
Either I should keep the planet (gift order cancelled after successful invasion), or the invasion should not happen (as if gifting happened first, and then invasion gets cancelled as I can't invade at-peace planet)

Steps to reproduce
------------------

As described, this happend on the break of turn 47 in multiplayer game 22, so you should have relevant save game.

But set up is Empires A and B at peace, A and C at war, B and C allies. On the same turn empire A invades a planet of empire C, while the empire C gifts that planet to empire B. Troop ship is lost, and invasion seemingly successful, but the planet ends up with empire B (gifted-to) not with empire A (the aggressor)

**Comment by Blue-Award** [comment]
NB talking with Daybreak, it shows as the planet was gifted by me - so I successfully conquered the planet, but the gifting order stuck around, and it was executed as me gifting the planet to Daybreak

**Comment by Vezzra** [comment]
Did #4349 properly fix this bug? Can this issue be closed as resolved? @Blue-Award?

**Comment by Blue-Award** [comment]
> Did #4349 properly fix this bug? Can this issue be closed as resolved? @Blue-Award?

yea, tested with setting up multiplayer game locally between three players and with new binaries it works as I would expect, that is the captured planet stays with the invader instead of getting gifted to the other empire
