### ISSUE TITLE
resurrectable species in suitability

### ISSUE THREAD

**Issue by vincent-legoll** [freeorion/freeorion#435]
They don't appear in suitability report until you build the first colony whereas they should appear when you build the xenoresurrection center at their discovery site.

**Comment by dbenage-cx** [comment]
Should be fixed by cebf07a

**Comment by Vezzra** [comment]
Can anyone confirm that cebf07a5cdc9a158e312af872c8739514c1144ed fixed this issue? Don't have the time to test that myself right now.

**Comment by vincent-legoll** [comment]
Bug is fixed, tested with today's cb44cafde562faa86fa2765ae59ee3cf28597742

**Comment by Vezzra** [comment]
Thanks!
