### ISSUE TITLE
Segmentation fault at ./freeorion startup. Debug with gdb.

### ISSUE THREAD

**Issue by asm64** [freeorion/freeorion#4356]
Bug Report
==========

  * Horrible: "Segmentation fault at ./freeorion startup"

> Reading symbols from ./freeorion...
> (gdb) run
> Starting program: /home/pvv/Games/git/freeorion/freeorion 
> 
> [Thread debugging using libthread_db enabled]
> Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
> [New Thread 0x7fffeea7c700 (LWP 29682)]
> [Thread 0x7fffeea7c700 (LWP 29682) exited]
> [New Thread 0x7fffee9fb700 (LWP 29683)]
> [Thread 0x7fffee9fb700 (LWP 29683) exited]
> [New Thread 0x7fffee9fb700 (LWP 29684)]
> [New Thread 0x7fffee1fa700 (LWP 29685)]
> [New Thread 0x7fffed7d2700 (LWP 29686)]
> 
> Thread 1 "freeorion" received signal SIGSEGV, Segmentation fault.
> GG::Edit::Edit (this=0x55555663b020, str="", font=..., color=..., text_color=..., interior=...) at /home/pvv/Games/git/freeorion/GG/src/Edit.cpp:48
> 48	    m_int_color(interior)
> (gdb) 

Environment
-----------

* **FreeOrion Version**: main
* **Operating System**: linux
* **Graphic card used**: nvidia-driver-470
* **Fetched as** 
  * Compiled from source

Description
-----------

Expected Result
---------------

* run

Steps to reproduce
------------------

* build
```
FOPT="-march=amdfam10 -O2"

if [ ! -d "./freeorion" ] ; then
    git clone https://github.com/freeorion/freeorion
    cd ./freeorion
else
    cd ./freeorion
    git pull
fi

if [ -f "./CMakeCache.txt" ]; then rm -f CMakeCache.txt; fi
make clean

#cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="$FOPT" .
cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="$FOPT" .
make -j7 CFLAGS="$FOPT"
```
* run
`./freeorion`
* got "Segmentation fault"

**Comment by geoffthemedio** [comment]
What specific release or commit? I don't know what "FreeOrion Version: main" means.

Regardless, can you try:
````
diff --git a/GG/src/Edit.cpp b/GG/src/Edit.cpp
index 81d546303..4edaa0d07 100644
--- a/GG/src/Edit.cpp
+++ b/GG/src/Edit.cpp
@@ -43,7 +43,7 @@ namespace {
 
 Edit::Edit(std::string str, std::shared_ptr<Font> font,
            Clr color, Clr text_color, Clr interior) :
-    TextControl(X0, Y0, X1, HeightFromFont(font, PIXEL_MARGIN), std::move(str), std::move(font),
+    TextControl(X0, Y0, X1, HeightFromFont(font, PIXEL_MARGIN), std::move(str), font,
                 text_color, FORMAT_LEFT | FORMAT_IGNORETAGS, INTERACTIVE | REPEAT_KEY_PRESS),
     m_int_color(interior)
 {
````

**Comment by asm64** [comment]
> What specific release or commit? I don't know what "FreeOrion Version: main" means.

Hi. I mean master of course. Now i checked out your patch.

```
pvv@homeserver:~/Games/git/freeorion$ LANG=C git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   GG/src/Edit.cpp

```
Now works fine. Thanks.
