### ISSUE TITLE
Fix boost deprecation messages

### ISSUE THREAD

**Issue by grawlinson** [freeorion/freeorion#4366]
Feature request
===============

Idea
----
When compiling for Arch Linux, the build script spits out a significant amount of deprecation messages from Boost:

```sh
/usr/include/boost/spirit/include/phoenix.hpp:12:1: note: ‘#pragma message: This header is deprecated. Use <boost/phoenix.hpp> instead.’
# BOOST_HEADER_DEPRECATED("<boost/phoenix.hpp>")
```

Gain
----

No unexpected failure to build from source when boost eventually removes the specified header.

**Comment by geoffthemedio** [comment]
As far as I'm aware, that comes from within Boost itself, so not something we can fix, other than by using a newer version of Boost that fixes it. All the instances of `phoenix.hpp` in FreeOrion code that I found when searching just now are `#include <boost/phoenix.hpp>`.

There is one case of `#include <boost/spirit/include/phoenix_core.hpp>` that can probably be fixed, though.

**Comment by grawlinson** [comment]
Thanks for the quick reply. Would you like me to file a PR fixing that particular instance?

**Comment by geoffthemedio** [comment]
No I will [change it](https://github.com/freeorion/freeorion/commit/d5f79535ce629cb2e9a273c8daf3c86cc5de95f7).
