### ISSUE TITLE
Structural Damage by Fleet in a fleets window not calculated properly

### ISSUE THREAD

**Issue by o01eg** [freeorion/freeorion#4374]
Bug Report
==========

Environment
-----------

* **FreeOrion Version**: 2022-11-01.6387e2e i.e. the MP22 version
* **Fetched as** 
  * Weekly development build

Description
-----------
Summary Structural Damage by Fleet in a fleet is not sum of Structural Damage by Fleet of each ship:

![Interestingmaths](https://user-images.githubusercontent.com/397177/215252164-6e17bd2c-bbcf-4523-b243-d9817bc3b306.png)

Expected Result
---------------
Structural Damage by Fleet of fleet in system is a sum of Structural Damage by Fleet of each ship.

Steps to reproduce
------------------

**Comment by geoffthemedio** [comment]
I'm not able to reproduce this in the v0.5 release version, and the server won't let me join the MP game.

**Comment by o01eg** [comment]
@geoffthemedio Granted you Observer access to the game.

**Comment by geoffthemedio** [comment]
I think it's an issue of destroyed ships / fleets being shown but not counted in the totals...  I can remove those checks if you prefer.

**Comment by o01eg** [comment]
Is it server-side or client-side? Also if it calculates destroyed ship should total Structural Damage by Fleet be bigger that sum of each ship?

**Comment by geoffthemedio** [comment]
Those numbers are calculated client side: https://github.com/freeorion/freeorion/blob/master/UI/FleetWnd.cpp#L2949-L2960

> Also if it calculates destroyed ship should total Structural Damage by Fleet be bigger that sum of each ship?

I don't understand the question.

**Comment by o01eg** [comment]
There is example screenshot where total is 408 while single ship have 597 Structural Damage by Fleet

**Comment by MichaelCourtney** [comment]
I'll produce a save sometime. It happens when you fleets mixing direct fire and carrier. The Total for "fleets at blah" will be the total direct fire damage, it'll be missing the carrier damage.

**Comment by geoffthemedio** [comment]
I don't know how the fleet total and individual ships in the fleet values for structure damage or fighter destruction numbers are calculated... I didn't write them as far as I recall.

**Comment by o01eg** [comment]
I see, there some desync in 3rd argument of `TotalWeaponsShipDamage`:

`true`:
https://github.com/freeorion/freeorion/blob/5e87d795469e723e84e02d8e37d9f657b909d06e/UI/FleetWnd.cpp#L871

and

https://github.com/freeorion/freeorion/blob/5e87d795469e723e84e02d8e37d9f657b909d06e/UI/FleetWnd.cpp#L1557

`false`:
https://github.com/freeorion/freeorion/blob/5e87d795469e723e84e02d8e37d9f657b909d06e/UI/FleetWnd.cpp#L2964

**Comment by geoffthemedio** [comment]
The third parameter is a `bool` called `include_fighters` so that would make sense...

I have no preference so whatever makes more sense to you is fine.
