### ISSUE TITLE
[Patch] Never move the iterator outside of its begin-end range.

### ISSUE THREAD

**Issue by Hacklin** [freeorion/freeorion#440]
[bug_outOfRange-20160107.zip](https://github.com/freeorion/freeorion/files/87223/bug_outOfRange-20160107.zip)

If the first prerequisite tech is complete,
the tech iterator is set before begin() and
the prerequisite tech at begin() is removed.
This can cause an AI to hang with the error:
"Player AI_? no longer has a connection to the server."

Patch: NeverMoveAnIteratorOutsideOfItsBeginEndRange.diff

**Comment by geoffthemedio** [comment]
Can you submit the patch as a pull request?

**Comment by Vezzra** [comment]
As @Hacklin apparently missed the request to make a PR, I went ahead and did it myself, see PR #448. @geoffthemedio, can you check if that fix is ok?

Seems to work fine on OSX.
