### ISSUE TITLE
FreeOrion 0.5-rc1 fails to build on armhf debian

### ISSUE THREAD

**Issue by o01eg** [freeorion/freeorion#4407]
Bug Report
==========

Environment
-----------

* **FreeOrion Version**: 0.5-rc1
* **Operating System**: Linux Ubuntu armhf
* **Fetched as** 
  * Compiled from source

Description
-----------

When building 0.5-rc1 on PPA armhf architecture fails to build.

Build logs: https://launchpadlibrarian.net/653456440/buildlog_ubuntu-jammy-armhf.freeorion_0.5rc1+ppa1~jammy_BUILDING.txt.gz

Suppose it related to https://github.com/gazebosim/gazebo-classic/issues/3208

Expected Result
---------------

Successful compilation.

**Comment by geoffthemedio** [comment]
Can we test with CI builds? Maybe just removing the `template struct` declarations is sufficient?

https://github.com/freeorion/freeorion/commit/c5367c6eedcef95ad5c935457d4f1d2cf656b197

**Comment by o01eg** [comment]
Github Actions doesn't support it directly https://github.com/orgs/community/discussions/25319

**Comment by geoffthemedio** [comment]
Can you test some other way? I have no idea how to do so...

**Comment by o01eg** [comment]
I could try to use Debian tutorial about qemu https://wiki.debian.org/QemuUserEmulation but it will be expected to be more slow.

> Maybe just removing the `template struct` declarations is sufficient?
> 
> [c5367c6](https://github.com/freeorion/freeorion/commit/c5367c6eedcef95ad5c935457d4f1d2cf656b197)

Looks like it at least didn't break code. I'll try to use it on PPA.

**Comment by o01eg** [comment]
@geoffthemedio Yes. https://github.com/freeorion/freeorion/commit/c5367c6eedcef95ad5c935457d4f1d2cf656b197 fixed it in 0.5 branch. I've also enabled `armhf` for weekly test build PPA so same issue could be catch earlier.

**Comment by o01eg** [comment]
Fixed with https://github.com/freeorion/freeorion/commit/c5367c6eedcef95ad5c935457d4f1d2cf656b197
