### ISSUE TITLE
No Troops ... v0.5+ HEAD [build 2023-02-24.cc2e7b1]

### ISSUE THREAD

**Issue by wiloyee** [freeorion/freeorion#4409]
Bug Report
==========
Troopships don't have any troops. 
Tryed it with different games.

Environment
-----------
* **FreeOrion Version**:  v0.5+ HEAD [build 2023-02-24.cc2e7b1]
* **Operating System**:  Linux 6.1.8-gentoo #1 SMP PREEMPT_DYNAMIC Sun Jan 29 10:35:54 CET 2023 x86_64 Intel(R) Core(TM) i5-3340M CPU @ 2.70GHz GenuineIntel GNU/Linux
* **Graphic card used**: 
  * Compiled from source

Expected Result
---------------
Troopships should have troops

Steps to reproduce
------------------
build a troopship ... 
No troops.

**Comment by wiloyee** [comment]
[freeorion.log.gz](https://github.com/freeorion/freeorion/files/10848734/freeorion.log.gz)
trace level log file

**Comment by wiloyee** [comment]
Build enviroment:

Python 3.11.2
ninja 1.11.1
cmake version 3.25.2

**Comment by agrrr3** [comment]
made a build for your revision, i can reproduce your issue; also the colony ship has no colonists
```
$ snapcraft release freeorion 342 latest/edge/issue-4409
Released 'freeorion' revision 342 to channels: 'latest/edge/issue-4409' 
$ snapcraft status freeorion
Track    Arch    Channel             Version                   Revision    Progress    Expires at
latest   amd64   stable              v0.4.10.2                 231         -           -
                 candidate           v0.5-rc1-2-g2b503c71e     338         -           -
                 beta                v0.5-rc1-2-g2b503c71e     338         -           -
                 edge                2023-02-24.cc2e7b157      342         -           -
                 edge/issue-4409     2023-02-24.cc2e7b157      342         -           2023-03-31T00:00:00Z
```

**Comment by Vezzra** [comment]
@wiloyee, @agrrr3, is that only an issue with current master, or does it also show up on the release branch?

**Comment by agrrr3** [comment]
only on master as far as i am aware of

**Comment by o01eg** [comment]
Yes, MP game on 0.5 RC 1 doesn't have that issue.

**Comment by wiloyee** [comment]
I have found this: 
Version 7bade227d97572b57b2e743faffc27bb6a3fd52e OK
Version 87b4646f3610dd322f5f244d16f8f1a5de36e3c3 Error 

there are many changes in: 
universe/ShipPart.cpp

It may be that one of these changes is causing the issue.

I hope that this will help to find out the error

Thanks
    Bernd

**Comment by o01eg** [comment]
@geoffthemedio Could you look into it?

**Comment by agrrr3** [comment]
looking at the commit, ShipPart.cpp#205
`for (auto& effect : effects) {` seems fishy.

If all the effects get copied into retval, why are the original effects updated?
but cant imagine that this could lead to the observed behavior

**Comment by geoffthemedio** [comment]
> If all the effects get copied into retval, why are the original effects updated?

They aren't copied; they are moved:
````
        for (auto& effect : effects) {
            effect->SetTopLevelContent(name);
            retval.push_back(std::move(*effect));
        }
````

**Comment by geoffthemedio** [comment]
Appears to have been fixed by or before 581c9cb

probably by [not moving from the name](https://github.com/freeorion/freeorion/commit/581c9cbef4b72cfac9ddf1dcce1f606a78eb605a#diff-2d25322dd303c9d3b5aaf647f94ba57a1effd0bb80ea54ee00112d5b81d2d723R223) parameter before using it to [initialize part effects](https://github.com/freeorion/freeorion/commit/581c9cbef4b72cfac9ddf1dcce1f606a78eb605a#diff-2d25322dd303c9d3b5aaf647f94ba57a1effd0bb80ea54ee00112d5b81d2d723R299).

**Comment by Vezzra** [comment]
@wiloyee, @geoffthemedio, has the issue been fixed? Can this be closed as resolved?

**Comment by Blue-Award** [comment]
I think it's fixed, I am playing on aa45874 weekly build and had successfully deployed colonies and troop ships

**Comment by Vezzra** [comment]
It would be good to have a confirmation from @wiloyee or @geoffthemedio...

**Comment by geoffthemedio** [comment]
Someone other than me should test a potential fix written by me.

**Comment by Vezzra** [comment]
Well, we've a confirmation from @Blue-Award, but maybe @wiloyee can also check if this has been fixed - @wiloyee?

**Comment by geoffthemedio** [comment]
seemingly has been fixed
