### ISSUE TITLE
v0.5 default window size hides save/load/exit/options Menu

### ISSUE THREAD

**Issue by agrrr3** [freeorion/freeorion#4428]
Bug Report
==========

Environment
-----------
linux; v0.5, master; this is actually an issue since adding the influence marker to the top of the main window. I just got used to it so much that i totally forget about it.

Description
-----------
If I open a fresh freeorion game in windowed mode, the main window does not show the 'Menu' menu at the top right of the main window. 
I need to drag the right border a bit to the right in order to be able to see it. New players probably won't guess that there is a 'Menu' hidden. That 'Menu' contains the important options: Save Game/Load Game/Exit to Main Menu/Options. 

So I guess we should fix this even for 0.5

Expected Result
---------------
If I open a fresh freeorion game in windowed mode, the main window  shows the 'Menu' menu so I can click it and e.g. 'Save Game'

**Comment by Vezzra** [comment]
That should probably fixed for the release. @agrrr3, how quick do you think can a fix be provided? Looks like we need another release candidate...

**Comment by agrrr3** [comment]
Don't know how long it takes. I always struggle with our GUI
Probably easy to fix it you know what you are doing

**Comment by o01eg** [comment]
I suppose that menu appears on `Esc` key.

**Comment by o01eg** [comment]
Maybe just increase default window size for Menu to be shown?

**Comment by Vezzra** [comment]
#4436 fixed this, correct? So this can be closed as resolved?
