### ISSUE TITLE
No damage for bad pilots

### ISSUE THREAD

**Issue by drkosy** [freeorion/freeorion#4463]
Bug Report
==========
Used v0.5+ build 2023-03-27.f3e17e5.

Played gysache as bad pilots. Fregatte MS don't have any combat strengh. Even with Massdriver 4 there is no combat strength shown in the UI.

Environment
-----------
Self built FO on Fedora-Linux 37

Description
-----------
See [https://www.freeorion.org/forum/posting.php?mode=reply&t=12758](url) for more information and discussion.

Steps to reproduce
------------------
Start a new game with bad pilot race and invent all Massdriver techs.

**Comment by geoffthemedio** [comment]
I get 0 damage at the start of the game with Gysache, but after upgrading to mass driver 2 or 3, and a turn to upgrade while in supply, they have damage.
![gyscahe mass driver level 2 damage](https://user-images.githubusercontent.com/11386908/228948499-a768ae01-6ab3-4162-b6fa-2717c291b3ee.png)

**Comment by geoffthemedio** [comment]
This is probably related to the check for whether a part uses the standard capacity effect [that was added](https://github.com/freeorion/freeorion/commit/509683a4f84ee7155d9f7b62479b45f8d0d70c55#diff-2d25322dd303c9d3b5aaf647f94ba57a1effd0bb80ea54ee00112d5b81d2d723R415) to the getter for the Capacity value:
https://github.com/freeorion/freeorion/blob/release-v0.5/universe/ShipPart.cpp#L408-L416
`return m_capacity * GetGameRules().Get<double>("RULE_SHIP_WEAPON_DAMAGE_FACTOR");`

https://github.com/freeorion/freeorion/blob/master/universe/ShipPart.cpp#L392-L400
`return m_capacity * (m_add_standard_capacity_effect ? GetGameRules().Get<double>("RULE_SHIP_WEAPON_DAMAGE_FACTOR") : 1.0f);`

So perhaps the `SetMaxCapacity` effect needs to be explicitly scaled up by the ship weapon damage factor when the part doesn't use default capacity effects. I feel like this is overly complicated and there should rather be no checks for m_add_standard_capacity_effect or scaling by the rule within the ship part capacity and similar getters...

**Comment by agrrr3** [comment]
this is working in #4437

**Comment by Vezzra** [comment]
> this is working in #4437

@agrrr3, by that you mean #4437 will solve this, correct?

**Comment by agrrr3** [comment]
> > this is working in #4437
> 
> @agrrr3, by that you mean #4437 will solve this, correct?

yes
