### ISSUE TITLE
include Android Godot client in readme

### ISSUE THREAD

**Issue by johndh** [freeorion/freeorion#4467]
Feature request
===============

Idea
----

Please update the readme build instructions to include the Android version, where to get the most current apk, and how to build it from source.

Gain
----

I had to search on the forum to find that there even was an Android client. This would make it more obvious for people looking for FOSS mobile games.

Discussion
----------

https://www.freeorion.org/forum/viewtopic.php?p=115995&hilit=android#p115995

**Comment by o01eg** [comment]
Android client is in such incomplete and experimental state so It's hard to even call it a game.

`BUILD.md` contains Android section if needed.

**Comment by johndh** [comment]
Ah, I didn't realize that the instructions were elsewhere. That's probably fine, because anyone interested in finding it for testing and development purposes would be more likely to find it, and anyone interested in actually playing it would be disappointed.

**Comment by Vezzra** [comment]
In that case I suggest to close this as "works for me". Is that ok? @o01eg, @johndh?

**Comment by o01eg** [comment]
@Vezzra Yes.
