### ISSUE TITLE
packaging/ missing from source

### ISSUE THREAD

**Issue by DarthGandalf** [freeorion/freeorion#4470]
Bug Report
==========

CMake Error at cmake_install.cmake:152 (file):
  file INSTALL cannot find
  "/mnt/portagetmp/portage/games-strategy/freeorion-0.5/work/src-tarball/packaging/org.freeorion.FreeOrion.desktop":
  No such file or directory.

Because the whole packaging/ dir is missing from the published FreeOrion_v0.5_Source.tar.gz 

Environment
-----------

* **FreeOrion Version**: 0.5
* **Operating System**: Gentoo Linux amd64
* **Graphic card used**: irrelevant
* **Fetched as** 
  * Compiled from source

Description
-----------

[build.log](https://github.com/freeorion/freeorion/files/11154358/build.log)

Expected Result
---------------

It should build and install successfully

Steps to reproduce
------------------

* Downoad FreeOrion_v0.5_Source.tar.gz 
* cmake ...
* make
* make install
* Issue occurs.

**Comment by Vezzra** [comment]
@DarthGandalf, yes, you're correct, that's an oversight on my part. The `packaging` folder has always been excluded from the source tarball, as it originally only contained the bits and parts required to build the installer packages and app bundles for Windows and macOS, which is stuff that usually does not belong in source tarballs.

The `org.freeorion.FreeOrion.desktop` for Linux has been added later, but this file of course needs to be shipped with the source tarball.

As a solution for now I've included the `packaging` folder and am currently uploading the updated source tarball to SourceForge and Github.

Please retry with the updated tarballs and report back - thanks!

**Comment by DarthGandalf** [comment]
Yep, now it works, thanks
