### ISSUE TITLE
Charge/Flanking policies need supply to upgrade damage

### ISSUE THREAD

**Issue by MichaelCourtney** [freeorion/freeorion#4517]
Bug Report
==========
v0.5 Release

https://freeorion.org/forum/viewtopic.php?t=12778&sid=543cf0256e11cd5c604c55d4e093f769

**Comment by Blue-Award** [comment]
This is especially relevant for Flanking, because the bonus is situational and you may lose it outside supply and then do not regain it even if the situational parameters are met

**Comment by agrrr3** [comment]
#4557 fixes this in master; maybe we should consider backporting (after playtesting a bit) to 0.5 if we do a maintenance release. 

Note though that might be involved as the structure change quite a bit.

**Comment by Vezzra** [comment]
> maybe we should consider backporting

That consideration notwithstanding, this issue can be closed as resolved (*edit: once #4557 has been merged*).

If I understand correctly, a backport of this fix to the 0.5 release branch would be a more involved thing anyway, so if that's done, create a separate PR for the release branch.

**Comment by Vezzra** [comment]
Sorry, overlooked that #4557 hasn't been merged yet...
