### ISSUE TITLE
Part exclusions not working for identical parts

### ISSUE THREAD

**Issue by MichaelCourtney** [freeorion/freeorion#4519]
Bug Report
==========
v0.5 Release

You can build ships with 2 flux lance or 2 defense grids (but not a ship with a defense grid and deflector shield). This is not meant to be possible (and was not in previous versions)

https://freeorion.org/forum/viewtopic.php?t=12777&sid=d4fa13e7ec542e3ed79b3955d4dabf46

**Comment by MichaelCourtney** [comment]
Can also reproduce in master 2023-05-16.182dfe7

**Comment by geoffthemedio** [comment]
If you can narrow the window of builds from when it worked to when it stopped working, that would be helpful.

**Comment by MichaelCourtney** [comment]
> If you can narrow the window of builds from when it worked to when it stopped working, that would be helpful.

It works in 2022-11-01-01.6387e2e
It doesn't work in 2022-11-14-22c61c1

**Comment by Cjkjvfnby** [comment]
I think the cause of this bug might be in the same code, but not sure if they are actually related.
https://github.com/freeorion/freeorion/issues/4521

**Comment by MichaelCourtney** [comment]
I see changes to ShipDesign:: on Nov 10

**Comment by geoffthemedio** [comment]
probably due to 6d1a1098

**Comment by geoffthemedio** [comment]
Do #4530 and #4531 fix it?

**Comment by MichaelCourtney** [comment]
> Do #4530 and #4531 fix it?

my copy of visual studios is playing up. Will try and test when I can, but hopefully someone gets to it 1st

**Comment by o01eg** [comment]
I've tested #4531 with Base Hull and Defense Grid and it prevents to save design with two Defense Grid on it.
