### ISSUE TITLE
Many design errors in AI logs

### ISSUE THREAD

**Issue by Cjkjvfnby** [freeorion/freeorion#4521]
Description
-----------

Looks like validation for `exclusions` exclude the item itself.
```
[warn] ai : ShipDesign.cpp:510 : Invalid ShipDesign part SH_DEFENSE_GRID conflicts with "SH_DEFENSE_GRID". Removing "SH_DEFENSE_GRID"
[warn] ai : ShipDesign.cpp:560 : ShipDesign was made valid as:
ShipDesign
    name = "SM_JUGGERNAUT_1"
```

Expected Result
---------------
No error in log.

Steps to reproduce
------------------
Steps to reproduce:
- start game
- exit to the main menu
- check logs

v0.5+ [build 2023-05-18.375ed06] CMake

**Comment by geoffthemedio** [comment]
Does #4531 fix it?

**Comment by Cjkjvfnby** [comment]
Yes, this error is gone.
