### ISSUE TITLE
Bug in Species Stealth

### ISSUE THREAD

**Issue by MichaelCourtney** [freeorion/freeorion#4532]
Bug Report
==========
Build: 2023-05-22.3bafe8f
Something is up with planet stealth, you can see in the screenshot I'm Sly. Researching cloud cover also doesn't work.

![Sly](https://github.com/freeorion/freeorion/assets/43386669/687dbca3-c540-4e0a-b1fc-33a4120076c3)

**Comment by MichaelCourtney** [comment]
seems to be working fine in release v0.5

**Comment by MichaelCourtney** [comment]
Not working in build 2023-04-03.3e2a786

**Comment by geoffthemedio** [comment]
Are you reproducing this from a fresh game start? Commit 3e2a786 is in v0.5 as e54e27b9

**Comment by MichaelCourtney** [comment]
> Are you reproducing this from a fresh game start? Commit [3e2a786](https://github.com/freeorion/freeorion/commit/3e2a786493f6840540ae47d3e66b61bcd0c0f305) is in v0.5 as [e54e27b](https://github.com/freeorion/freeorion/commit/e54e27b9ab328006582cfa556d02faf479662061)

I'm producing from a new game with a fresh install and an uninstall in between. Using Vezzra's builds for windows.

I get the bug with both: FreeOrion_2023-04-03.3e2a786_Test_Win32_Setup
and FreeOrion_2023-05-22.3bafe8f_Test_Win32_Setup

but not with FreeOrion_v0.5_Win32_Setup

**Comment by geoffthemedio** [comment]
10d9d9fb125 doesn't work
5700c340ef9 doesn't work
fe83a83eed doesn't work
1e48801a5 doesn't work
bae8eac85 doesn't work
e3c91dd5 breaks it, but adding `NoOp` in the `GREAT_STEALTH` macro scope after `Source` appears to work... (!?)
11133d00 works
90c4eded3 works
1cf0d73bbd works
cbc6eab17fd works

**Comment by geoffthemedio** [comment]
Could you check if this is fixed by #4534 ?

**Comment by geoffthemedio** [comment]
@MichaelCourtney ?

**Comment by MichaelCourtney** [comment]
> @MichaelCourtney ?

I'm running into issues compiling in VS (master in general, not the commit). Which makes it very hard to test anything.

**Comment by MichaelCourtney** [comment]
Is there a way for me to produce a build direct from github, if I can't compile on my laptop?

**Comment by geoffthemedio** [comment]
@Cjkjvfnby @o01eg Is there a way to get test build artifacts for pull requests without merging into master?

**Comment by Cjkjvfnby** [comment]
> @Cjkjvfnby @o01eg Is there a way to get test build artifacts for pull requests without merging into master?

No, but we could do it. 

- Option one is always to build artifacts for all branches. 
- Create a separate job that could be run manually,  and you will need to specify the commit to build things. (this might be complicated with forks)

**Comment by MichaelCourtney** [comment]
> @MichaelCourtney ?

Fixed by (https://github.com/freeorion/freeorion/pull/4534)
