### ISSUE TITLE
flak seems broken

### ISSUE THREAD

**Issue by agrrr3** [freeorion/freeorion#4555]
Bug Report
==========

flak seems broken/does not help shooting down enemy fighters

Environment
-----------
snap install latest/beta aka 2023-06-06.09820928d

Description
-----------
when opening the ship designer, adding a flak should increase the amount of total fighter destruction .
other fighter killing parts (Flux Lance, Arc Disruptor, ) do work correctly (add 3 / 9 total fighter destruction).
to make sure it is not only an UI issue i send a medium hull with two flak against a dyson forrest; the flak had the chance but did not shoot down any fighters

Expected Result
---------------
flak increases maximum total fighter destruction by 9

Steps to reproduce
------------------
* start a game 
* go to the ship designer
* add a ship hull with a flak part

**Comment by agrrr3** [comment]
datapoint: 
flak in ship designer ui was working in 2023-04-18.66a5bd726 (snap rev 353) OK
and broken in 2023-04-25.9514ea384                (358) NOK
probably a victim of 3bc2018a0e8141c897656017e4f0cbefdfbde7df

**Comment by agrrr3** [comment]
@vezzra this is a problem in master, not in 0.5 (i just checked to be sure). or would a maintenance release be 0.5.0.1 ?

**Comment by agrrr3** [comment]
the problem was an overenthusiastic cleanup in 98d164e5437f30f7c8ca77b0c7a5c501ae669db2
which by mistake removed setting of parts' MaxCap/2ndary which do not have WEAPON_UPGRADE_CAPACITY_EFFECTS (so it got unnoticed when testing)

**Comment by Vezzra** [comment]
> @Vezzra this is a problem in master, not in 0.5 (i just checked to be sure). or would a maintenance release be 0.5.0.1 ?

Correct. v0.5.1 is the next major release, the maintenance release for 0.5 is 0.5.0.1.
