### ISSUE TITLE
Divide by zero and overflow bugs

### ISSUE THREAD

**Issue by MXB2001** [freeorion/freeorion#4569]
Environment
-----------
* **FreeOrion Version**:
0.5 (latest flatpak)

* **Operating System**:
Debian 10 Linux

* **Fetched as** 
flatpak from flathub (current as of 2-3 days ago)

Description
-----------
After gaining some policies and choosing them (unknown which sorry) started getting a message in red about Influence, divide by zero and square root of something. It does not crash the game but likely is messing up the influence stat. The error comes and goes, pattern hard to detect.

Also, in the cassini system (see in the attached save game) the stealth of the asteroid belt is 65535.36 or around there. Obvious overflow bug. The asteroid has 2 specials: Minerals (or gems, I've only been playing this game for a few hours - all nite like when I was young :) plus the ash cloud which is supposed to add a small amount of stealth.

Save and log (wasn't sure which but I think this is the main one) attached below:

[freeorion.zip](https://github.com/freeorion/freeorion/files/11836859/freeorion.zip)
[save-20230622_070944.zip](https://github.com/freeorion/freeorion/files/11836790/save-20230622_070944.zip)

**Comment by geoffthemedio** [comment]
> in the cassini system (see in the attached save game) the stealth of the asteroid belt is 65535.36 or around there. Obvious overflow bug. 

This is not an overflow, but rather a [large placeholder value](https://github.com/freeorion/freeorion/blob/master/universe/Meter.h#L96) that is indicated for stealth when the value isn't known due to [an object not being sufficiently visible](https://github.com/freeorion/freeorion/blob/master/universe/UniverseObject.cpp#L352-L355).

> started getting a message in red about Influence, divide by zero and square root of something

If you can repdroduce it, please follow up about that. However, if you're getting these messages in the chat log window, then it's something in the AI, which would not itself affect your or another empire's influence output calculation.

**Comment by Blue-Award** [comment]
OK reading this second time I've probably just duplicated it with #4570 but attached the message box there... seems AI is trying to set influence focus on a planet that has zero population?

**Comment by Blue-Award** [comment]
File "c:\Program Files (x86)\FreeOrion\default\python\AI\ResourcesAI.py", line 121, in evaluate
    return self.rating_below_best(focus) / sqrt_population

**Comment by Blue-Award** [comment]
<code>
sqrt_population = min(1.0, self.planet.currentMeterValue(fo.meterType.population)) ** 0.5
</code>

perhaps it should be `max` not `min`

**Comment by geoffthemedio** [comment]
so I guess this can be closed?

**Comment by Blue-Award** [comment]
Haven't actually checked but it indeed seems to be duplicate of the other, so ye

**Comment by Vezzra** [comment]
Duplicate of #4570, correct?

**Comment by Blue-Award** [comment]
> Duplicate of #4570, correct?

Yes. 

Or the other way around but I perhaps gave more context to it

**Comment by Vezzra** [comment]
> Or the other way around but I perhaps gave more context to it

Since it is this PR that got closed as duplicate, it makes sense to put a reference here to the issue it is a duplicate of. I just wanted to know if I got the right issue, that's all... :wink:

**Comment by geoffthemedio** [comment]
read the previous two comments?

**Comment by geoffthemedio** [comment]
there are / were comments earlier about it...
