### ISSUE TITLE
division by zero while trying to generate_resources_orders

### ISSUE THREAD

**Issue by Blue-Award** [freeorion/freeorion#4570]
Bug Report
==========

Maybe https://github.com/freeorion/freeorion/issues/4569 encompasses this issue but it is singular ZeroDivisionError: float division by zero error while the aforementioned issue lists a few things

Environment
-----------

* **FreeOrion Version**: aa45874 with manual patch of serialization issue that I saw 
https://github.com/freeorion/freeorion/pull/4567
* **Operating System**: windows 10

* **Fetched as** 
  * Weekly development build

Description
-----------
After ending turn, message window shows AI log:

<pre>AI_22: AI_Error: AI script error : FreeOrionAI.py:generateOrders():345  - Exception float division by zero while trying to generate_resources_orders
Traceback (most recent call last):
  File "c:\Program Files (x86)\FreeOrion\default\python\AI\FreeOrionAI.py", line 342, in generateOrders
    action()
  File "c:\Program Files (x86)\FreeOrion\default\python\AI\ResourcesAI.py", line 750, in generate_resources_orders
    focus_manager.set_planetary_foci(reporter)
  File "c:\Program Files (x86)\FreeOrion\default\python\AI\ResourcesAI.py", line 149, in set_planetary_foci
    self.set_influence_focus()
  File "c:\Program Files (x86)\FreeOrion\default\python\AI\ResourcesAI.py", line 440, in set_influence_focus
    [
  File "c:\Program Files (x86)\FreeOrion\default\python\AI\ResourcesAI.py", line 441, in <listcomp>
    (pinfo.evaluate(INFLUENCE), pinfo)
  File "c:\Program Files (x86)\FreeOrion\default\python\AI\ResourcesAI.py", line 121, in evaluate
    return self.rating_below_best(focus) / sqrt_population
ZeroDivisionError: float division by zero
Local context: {'self': PlanetFocusInfo(P_364056<Piazzi ε II>), 'focus': 'FOCUS_INFLUENCE', 'sqrt_population': 0.0}</pre>

Expected Result
---------------
No error in log? And presumably correct workings of the AI whatever it was trying to do

Steps to reproduce
------------------
I've attached save games for turn 40 when everything is fine and then turn 41 when the error shows up (next turn, 42, also shows the error)

**Comment by Blue-Award** [comment]
Eyeballing it https://github.com/freeorion/freeorion/blame/39498c8623baa1de4c865e6cc2bbc1293592425b/default/python/AI/ResourcesAI.py#L117 has `min` rather than `max` and it seems like that would fix it. 

I tried it locally and indeed the error goes away though perhaps it is still a question why something with zero population got considered (I did not follow that). After all the line about `min` seems to be there for 7 months now

**Comment by Blue-Award** [comment]
Granted changing min to max would rather drastically change whatever the AI is doing there, as most of the time the sqrt would be 1.0, and weird stuff if population would fall below 1.0, but without following the grand logic it seems that would indeed be the idea to max population at 1.0 if it is below, rather than capping it at 1.0 (though no idea why population lower than 1.0 would need not to be considered)

**Comment by Cjkjvfnby** [comment]
Sorry missed this. 

I did not find the save attached, but this should be fixed here: https://github.com/freeorion/freeorion/pull/4579

PS. There was a bug with savegames, so some old savegames might not work https://github.com/freeorion/freeorion/issues/4566.

**Comment by Blue-Award** [comment]
> Sorry missed this.
> 
> I did not find the save attached


Apologies looks like I forgot to attach. The other issue has one https://github.com/freeorion/freeorion/issues/4569 but I am attaching just now (sorry wrong zip lemme find it)

**Comment by Blue-Award** [comment]
sorry I can't find the zip, probably I removed it when I thought I have attached it... and the savegames are gone now too

**Comment by Cjkjvfnby** [comment]
Should we port this zero division to 0.5?

**Comment by Vezzra** [comment]
> Should we port this zero division to 0.5?

If that bug is present in 0.5, then probably yes.

Create a separate PR for the release branch.

**Comment by Cjkjvfnby** [comment]
New PR for release:

https://github.com/freeorion/freeorion/pull/4596
