### ISSUE TITLE
Crashes editing description

### ISSUE THREAD

**Issue by MXB2001** [freeorion/freeorion#4575]
* **FreeOrion Version**:
0.5
* **Operating System**:
Debian 10
* **Graphic card used**:
Unknown
* **Fetched as**
Flatpak

Description
-----------
Editing a premade unit description and moving cursor left at start of line crashes program.

[freeorion.zip](https://github.com/freeorion/freeorion/files/11857888/freeorion.zip)

Steps to reproduce
------------------
* First step.
Select Cruiser Ms
* Second step.
replace fuel tank with flux lance
* Another step.
click description box and default text appears, click anywhere and then cursor to the start of the line
* Problem occurs.

[FreeOrion_Maximilian_My_0023_20230624_141858.zip](https://github.com/freeorion/freeorion/files/11857896/FreeOrion_Maximilian_My_0023_20230624_141858.zip)

**Comment by geoffthemedio** [comment]
Could someone else check / verify that #4576 fixes this?

**Comment by o01eg** [comment]
Actually I cannot even reproduce issue with or without PR applied.

**Comment by geoffthemedio** [comment]
> cannot even reproduce issue

Nor could I.

Thogh when testing, I noticed a rendering issue for the text entry carat at the start of multi-line edit boxes, which appeared to be connected to a possible index underflow that could have caused a crash. I guess testing that would also be useful...

**Comment by geoffthemedio** [comment]
presumably fixed. update if testing indicates otherwise.
