### ISSUE TITLE
No automatic GUI description of species traits after py conversion?

### ISSUE THREAD

**Issue by Blue-Award** [freeorion/freeorion#4587]
Bug Report
==========

During a game on build aa45874 I saw Acirema homeworld and when examining the Acirema species in pedia, I saw there is nothing about their traits, while I was sure there used to be plenty listed (like better industry, research, ship shields etc.).

Tried to see what has changed and I see Acirema have been moved to focs.py from focs.txt. I've noticed Abaddoni also have been moved, and sure enough, they lack those descriptions as well in GUI, including the pop up that you get when starting new game and selecting species you want to play. Starting the game with Abaddoni however shows bad research and great influence in action as expected, even if those are not listed. So seems to only be GUI issue.

Also Banforo and Ancient Guardians have this issue, also being python-ported

Expected Result
---------------

Species like Acirema or Abaddoni have their traits ++, -- listed in the GUI in their entry, or in case in Abaddoni, in the pop up when hovering over them in initial species selection drop down

Steps to reproduce
------------------

You don't even have to start game, you can launch Pedia from main menu, search for e.g. Banforo, and see no traits listed that show stuff like Good Industry. Additionally this also applies for Abaddoni and the drop down where you select starting species

**Comment by o01eg** [comment]
It looks like `Species::GameplayDescription` miss it. `Species::m_effect` returns empty `GetDescription`.

**Comment by o01eg** [comment]
I suppose it broken both in `master` and `v0.5`?
