### ISSUE TITLE
Species' like/dislike of policies have no effect on stability

### ISSUE THREAD

**Issue by freddyhayward** [freeorion/freeorion#4595]
Liking or disliking an adopted policy used to provide a base +2/-2 bonus/malus to stability, and now it doesn't.

Unfortunately I don't know the exact commit that causes this, but it doesn't work on [1b21f9b](https://github.com/freeorion/freeorion/commit/1b21f9b988d0745e84f9af80cf492de54ef7e0a7), and worked normally on [182dfe7](https://github.com/freeorion/freeorion/commit/182dfe751d368aa58f217c42b54e9e8bef514df6).

**Comment by geoffthemedio** [comment]
LIkes/dislikes for policies now affect species empire opinions instead of directly affecting planet stability aad7000c

**Comment by freddyhayward** [comment]
> LIkes/dislikes for policies now affect species empire opinions instead of directly affecting planet stability [aad7000](https://github.com/freeorion/freeorion/commit/aad7000c5bfdacd3ec3bd6cf4cb29b8116fc3203)

Thanks, does species empire opinion currently have any consequences?

**Comment by geoffthemedio** [comment]
Currently, species opinions of empires just affects the annexation costs for that species' planets by the corresponding empire.

More is planned https://freeorion.org/forum/viewtopic.php?p=116560&sid=3fea6ff08b7090d416b9b1e874e623ca#p116560

**Comment by freddyhayward** [comment]
Interesting, thanks.
