### ISSUE TITLE
Stability is not affected by opinion on adopted policies 

### ISSUE THREAD

**Issue by Blue-Award** [freeorion/freeorion#4602]
Bug Report
==========

Environment
-----------

* **FreeOrion Version**: 2023-07-04.d2b1f58
* **Fetched as** 
  * Weekly development build

Description
-----------

Stability is not affected by policy likes/dislikes.

Perhaps broken with merge of other opinion stuff?

Steps to reproduce
------------------

Perhaps easiest with Egassem that can adopt Centralisation from the get go but supposedly dislike it. The stability is not affected by this

**Comment by Blue-Award** [comment]
Looks like it is working for planetary focus, specials and buildings (haven't tested for other species in same system)

**Comment by Blue-Award** [comment]
d2b1f58

**Comment by MichaelCourtney** [comment]
https://github.com/freeorion/freeorion/commit/aad7000c5bfdacd3ec3bd6cf4cb29b8116fc3203

Not sure if the lack of stability is change is a bug (or partially complete change), or the intended new behaviour

**Comment by Blue-Award** [comment]
Yeah I don't know how the new "opinion" feature is supposed to work. Looks like it has no effect in game as of now, though?

Maybe stability was supposed to be affected by opinion, so could make sense to roll policy effects into opinion, kind of pot-ay-to, pot-ah-to. So for our test game, assuming the opinion doesn't actually work yet, we could temporarily revert the changes to policy likes/dislikes handling in the script, presumably?

**Comment by Blue-Award** [comment]
so yeah maybe the actual bug is that the "opinion" stuff doesn't work for some reason but it should.. we're just not sure if it supposed to work yet

**Comment by Blue-Award** [comment]
Main thing is that I/we don't know how the new "opinion and annexation" feature should be working/works/to what extent it is complete. No pedia entry for that, though I can see some opinion score at least about empires on individual species' tabs and on empire info tab in pedia. Presumably that score is linked to some new ability to annex .. planets? Empires? without troops... but not clear upfront how that should work

Perhaps opinion indeed does not affect stability, though that policy likes and dislikes are rolled into opinion now, and that is not affecting stability - it changes the game quite a bit, its balance, but not saying it's bad or good, just quite different now. Policy likes and dislikes were quite big part of balancing your stability around critical points. In our test slow game we decided to set +5 base stability, except that doesn't actually work too, so as a workaround we put +5 on every environment for the same effect,

**Comment by geoffthemedio** [comment]
probably resolved by e2ef6f039f
