### ISSUE TITLE
Annexation doesn't actually cost anything

### ISSUE THREAD

**Issue by Blue-Award** [freeorion/freeorion#4624]
Bug Report
==========

Environment
-----------

* **FreeOrion Version**: 2023-07-10 c17e43d

* **Fetched as** 
  * Weekly development build

Description
-----------

Currently GUI suggests 5 IP cost per population to annex natives. You need as much stockpiled to have "Annex" button show up, and when you click it (and refresh the GUI by switching some planet's focus etc because GUI doesn't update but that's another story) it suggests you will pay that amount next turn. 

Next turn comes, natives are annexed, but turns out you haven't actually paid anything (you tend to get less IP than expected without annexation but that seems to be just be function of higher IP costs due to having new colony)

Expected Result
---------------
I would expect to actually pay the specified IP amount to annex.

Separate issue may worth filling is that opinion doesn't seem to affect the 5 IP/pop cost, never mind that the cost is not paid anyway

Steps to reproduce
------------------

Didn't o01eg annex Happybirthdays already in MP25? I should be able to annex VolpUglush soon and you'd have a save game

However, one can start test game, no AIs, plenty of natives, 1 IP/PP/RP costs to everything and there's surely going to be some natives to annex quickly once you get orbital construction, space elevator.. And maybe worth starting with Etty to have higher supply to begin with

**Comment by geoffthemedio** [comment]
Should be fixed after c136cc7f9
