### ISSUE TITLE
Baseline stability setting doesn't set baseline stability for imperial planets

### ISSUE THREAD

**Issue by Blue-Award** [freeorion/freeorion#4625]
Bug Report
==========

Environment
-----------

* **FreeOrion Version**: 2023-07-10 c17e43d

* **Fetched as** 
  * Weekly development build

Description
-----------

There's this Game Rule "Planet Stability Baseline" but it only affects stability for natives now. It doesn't bump stability for planets in an empire.

Instead it looks like it counts as "opinion baseline" between species and empires.

Expected Result
---------------

I believe the setting should still affect baseline stability, not only for natives, but for empires too, and if there's a need to set baseline species opinion about empires, it should be a different game setting/rule

**Comment by Blue-Award** [comment]
I suppose if opinion impacted stability, then both policy likes/dislikes and base stability setting would indeed impact stability through opinion, but as stands, they do not, and while policy bit might be ok (just different), the 'base stability' still sounds like it should do what it was

**Comment by geoffthemedio** [comment]
probably fixed by e36258faf4
