### ISSUE TITLE
Gamerule "RULE_ENABLE_ALLIED_REPAIR" does nothing

### ISSUE THREAD

**Issue by MichaelCourtney** [freeorion/freeorion#4629]
It lost its function over here:

https://github.com/freeorion/freeorion/commit/606c19e1f22f0cfbb98b61975c7ab9be22546def

**Comment by o01eg** [comment]
Should we just remove that rule?

**Comment by MichaelCourtney** [comment]
> Should we just remove that rule?

Probably. The only places I see it are game rules.focs, game rules.py, the stringtables and \test\parse

**Comment by geoffthemedio** [comment]
> Should we just remove that rule?

I think so.
