### ISSUE TITLE
Flak cannons not working on monsters

### ISSUE THREAD

**Issue by MichaelCourtney** [freeorion/freeorion#4636]
https://freeorion.org/forum/viewtopic.php?t=12785&start=173

seems to work fine on a player ship

**Comment by geoffthemedio** [comment]
d9015ec2682a didn't remove `NoDefaultCapacityEffect` for `SR_WEAPON_0_1` as it did for the others, so maybe that's the problem?

Try with #4637 ?

**Comment by geoffthemedio** [comment]
resolved by #4638
