### ISSUE TITLE
Effect evaluation broken in master

### ISSUE THREAD

**Issue by agrrr3** [freeorion/freeorion#4639]
Bug Report
==========
effect evaluation (at least for ships) seems to be completely borked in master;

* starting fleet turn 0 - 0 damage
* starting fleet turn 1 - 1G damage
* the structure calculation seems to have been applied twice in client (expected 256 structure with a -128 unknown effect)

currently bisecting; was good in last  weekly build

broken: 2c7adc10466ead6bf1e7d58c68bbd22e913a366b
first broken: dbe6246b209ab926b1adde0fe67b163f2322e2f1
good: e202871720bda9ea65f59e5507501f5d5f5dba97
good: a5bbc08367edbc6ea14a09f6c08280ae7935d192
good: 5da62e179d3fe4f0169f2caba0781351e33ed11a

**Comment by agrrr3** [comment]
my compile is sooo slow

**Comment by geoffthemedio** [comment]
Seemingly fixed by https://github.com/freeorion/freeorion/commits/existing_insert
