### ISSUE TITLE
Destroyed fleet still selected by "Next idle fleet"

### ISSUE THREAD

**Issue by crazymerlyn** [freeorion/freeorion#4668]
Bug Report
==========

Environment
-----------

* **FreeOrion Version**: v0.5 HEAD [build 2023-03-21.50eff8b] CMake
* **Operating System**: Gentoo
* **Graphic card used**: Intel Corporation Alder Lake-P Integrated Graphics Controller (rev 0c)
* **Fetched as**
  * Compiled from source ([games-strategy/freeorion 0.5 package](https://packages.gentoo.org/packages/games-strategy/freeorion))

Description
-----------

When cycling though idle fleets using \<Alt-g\>, the game brings me to the last location where my scout was destroyed.
The same happens when cycling through all fleets using \<Ctrl-g\>.

[freeorion.log.gz](https://github.com/freeorion/freeorion/files/12273234/freeorion.log.gz)

I noticed the phantom fleet while cycling in my previous game too but in that one i didn't realize about the shortcut until well into the game. In this new game, the cycling option worked fine for the first few turns, even after using up colony ships. It was only after a scout was destroyed that the glitch appeared again.

It also seems the effect is limited to just one regardless of how many fleets have been destroyed. 

Expected Result
---------------
The game should only cycle through ships that still exist

Steps to reproduce
------------------
[phantom_fleet.sav.gz](https://github.com/freeorion/freeorion/files/12272991/phantom_fleet.sav.gz)

* Send a fleet to be destroyed
* Try to cycle through your fleets using \<Alt-g\> or \<Ctrl-g\>

In the save file above a scout was destroyed in Furud B a few turns ago

**Comment by Vezzra** [comment]
@o01eg, do you really think a fix for this should be backported to 0.5? Doesn't look like such a serious issue to me...
