### ISSUE TITLE
Megalith doesn't increase Infrastructure by 30, it sets it to 30

### ISSUE THREAD

**Issue by MXB2001** [freeorion/freeorion#4669]
* **FreeOrion Version**:
0.5
* **Operating System**:
Linux
* **Fetched as** 
Flatpak

Description
-----------
Well the title pretty much sums it up. I built a megalith on my capital and the infra started dropping from 46 to 30.

**Comment by geoffthemedio** [comment]
Strange... https://github.com/freeorion/freeorion/blob/release-v0.5/default/scripting/buildings/MEGALITH.focs.txt#L25 appears to add, not set the target infrastructure.

Can you add a screenshot with the cursor hovering over the planet's infrastructure meter, showing the accounting breakdown?

**Comment by MXB2001** [comment]
Agreed it is strange. I looked at the file first and although I don't know this scripting syntax it looked all right. Yet here is the screenshot:

![Screenshot_20230808_200133](https://github.com/freeorion/freeorion/assets/65250870/bfeab8f4-8e32-4fc2-bcc9-7b20d23fcedf)

N.B. This is after several turns when it has dropped down from the initial 46. Sorry didn't take a screenshot, but the accounting was identical then.

**Comment by geoffthemedio** [comment]
Can you make a similar screenshot from a turn before the Megalith production completes? Or attach a save, I suppose.

**Comment by MichaelCourtney** [comment]
Note the palace is +20 "if you don't have a megalith", which would put you at 50 before (and 60 afterwards)

**Comment by MichaelCourtney** [comment]
Not sure why it's happening, but screenshot 1 is with scripting unchanged, and screenshot 2 is with the priority line removed.

![megalith1](https://github.com/freeorion/freeorion/assets/43386669/236842c0-6e3a-4ff3-ba23-12ba1d364e81)
![megalith2](https://github.com/freeorion/freeorion/assets/43386669/2800d36d-aa7a-40dc-a4ea-85dacc70f0b1)

**Comment by MichaelCourtney** [comment]
its because the 3 different effects have the same stackinggroup name (construction, supply and setmeters), only the earliest gets applied.

Its also why this is happening:
https://freeorion.org/forum/viewtopic.php?p=111613&hilit=megalith#p111613

though I still see a 1 turn delay, when I change the stackinggroup name

**Comment by geoffthemedio** [comment]
feedback re: #4676 would be useful
