### ISSUE TITLE
NumberOf number scripting broken

### ISSUE THREAD

**Issue by MichaelCourtney** [freeorion/freeorion#4674]
Experimentors aren't spawning and monster nest placement is broken (probably some other things)

https://freeorion.org/forum/viewtopic.php?t=12817&sid=98342984d12ce3aac7a03def37f8209a

> [quote=BlueAward post_id=117181 time=1691755833 user_id=73644]
> 
>> [quote=wobbly post_id=117173 time=1691732058 user_id=33730]
> > Don't know, I can see changes to that part of the parser on 24th Jun. Maybe try a version from just before and just after?
> > [/quote]
> 
> I have tried 2023-06-19.aa45874 and yes, experimentors spawned successfully at that build (and removed starlanes on second turn)
> 
> Then I tried 2023-06-27.1b21f9b aaand... experimentors DID NOT successfully spawn (experiment zero was left alone in a connected system, as there was no outpost building to remove the starlanes)
> 
> So there ya go.
> [/quote]

This was the commit I suspected: https://github.com/freeorion/freeorion/commit/e3b2d3ff754400379ba8e56e4bfabbb11a11976c
though there is also a ton of other commits in that same week

**Comment by geoffthemedio** [comment]
confirming / narrowing down to a particular commit would be helpful...

edit: nevermind, I think I see the problem...
