### ISSUE TITLE
Solar Concentrator not giving advertised multiplier

### ISSUE THREAD

**Issue by MXB2001** [freeorion/freeorion#4678]
The pedia (and the script which I studied) say that at a Orange star the multiplier should be 2.25. I'm seeing 1.25 as shown on this screenshot:

![Screenshot_20230812_192259](https://github.com/freeorion/freeorion/assets/65250870/a04beaae-29dd-43e8-afc9-ae1353485df4)

(Charge policy is also in effect and if it is included then it's worse at 1.16 not 1.25)

**Comment by MichaelCourtney** [comment]
Assuming no solar web, I'm seeing +2.25 (x6 for weapon scaling), not x2.25 in the scripting. e.g. Value + 3 * 0.75

https://github.com/freeorion/freeorion/blob/master/default/scripting/ship_parts/General/SP_SOLAR_CONCENTRATOR.focs.txt#L30

As far as what is actually intended the pedia entry is so vague I'm not sure what it's meant to mean:

![Concentrator](https://github.com/freeorion/freeorion/assets/43386669/9c3310b2-6504-4161-a9ad-b01f3eb9ee3c)

**Comment by MXB2001** [comment]
Holy mackerel! You are right the Pedia does not say whether it is + or *. I had not expected such a microscopic increase (addition) for such an expensive item.

Looks like it is not a bug but rather a balance problem.

**Comment by Zireael07** [comment]
multiplication would indeed make more sense imho
