### ISSUE TITLE
Weapon Tier Update

### ISSUE THREAD

**Issue by Scara83** [freeorion/freeorion#469]
Playing build.5f8c27f.
I noticed changes in the weapon tier update on ships, upon researching new tiers.
First they seemed to update when connected to a supplyline. It certainly did work before.
This build it seems they won't update, even having the ships parked on an orbital drydock.
As I click next turn they shortly appear with the actual researched tier, but are then set back again to the original values!

**Comment by geoffthemedio** [comment]
When is "First"?

**Comment by Vezzra** [comment]
I guess builds prior to 5f8c27f... @Scara83?

**Comment by Scara83** [comment]
Ah sorry, I'm not sure if this bug did maybe came up earlier. I checked a savegame from a git pull dating 4-2-16, I quit the game earlier so it went unnoticed, at that point they weren't updating already...

**Comment by geoffthemedio** [comment]
Hopefully fixed...

https://github.com/freeorion/freeorion/commit/ceb8a6d2473747837a7ec0ccc45e0597116ec248

**Comment by geoffthemedio** [comment]
anybody still having this issue...?

**Comment by Scara83** [comment]
No, it looks like it's working good now
