### ISSUE TITLE
FreeOrion (0.5 and Git master) fails to build from source on 32 bit architectures e.g. i386

### ISSUE THREAD

**Issue by apoleon** [freeorion/freeorion#4699]
Bug Report
==========

Hi,

Debian maintainer of FreeOrion here. Version 0.5 and latest Git master fail to build from source on i386 and other 32 bit architectures.

https://buildd.debian.org/status/package.php?p=freeorion

I thought this issue was related to https://github.com/freeorion/freeorion/issues/4583

The problem appears to be in Meter.cpp.

https://buildd.debian.org/status/fetch.php?pkg=freeorion&arch=i386&ver=0.5%2Bgit20230820-1&stamp=1692559465&raw=0

````
[ 15%] Building CXX object CMakeFiles/freeorioncommon.dir/universe/Meter.cpp.o
/usr/bin/c++ -DBINPATH=\"/usr/bin\" -DBOOST_ALL_DYN_LINK -DBOOST_ALL_NO_LIB -DENABLE_BINRELOC -DFREEORION_BUILD_COMMON -DFREEORION_LINUX -DSHAREPATH=\"/usr/share\" -Dfreeorioncommon_EXPORTS -isystem /usr/include/python3.11 -g -O2 -ffile-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -O2 -g -DNDEBUG -std=c++20 -fPIC -fvisibility=hidden -Wall -MD -MT CMakeFiles/freeorioncommon.dir/universe/Meter.cpp.o -MF CMakeFiles/freeorioncommon.dir/universe/Meter.cpp.o.d -o CMakeFiles/freeorioncommon.dir/universe/Meter.cpp.o -c /<<PKGBUILDDIR>>/universe/Meter.cpp
/<<PKGBUILDDIR>>/universe/Meter.cpp:20:32: error: static assertion failed
   20 |     static_assert(r2.Current() == 64999.001f);
      |                   ~~~~~~~~~~~~~^~~~~~~~~~~~~
/<<PKGBUILDDIR>>/universe/Meter.cpp:20:32: note: the comparison reduces to ‘(6.4999e+4l == 6.49990010000000000012e+4l)’
/<<PKGBUILDDIR>>/universe/Meter.cpp:26:32: error: static assertion failed
   26 |     static_assert(r3.Current() == 64998.991f);
      |                   ~~~~~~~~~~~~~^~~~~~~~~~~~~
/<<PKGBUILDDIR>>/universe/Meter.cpp:26:32: note: the comparison reduces to ‘(6.499898828125e+4l == 6.49989909999999999997e+4l)’
/<<PKGBUILDDIR>>/universe/Meter.cpp:40:32: error: static assertion failed
   40 |     static_assert(q2.Current() == 1.01f);
      |                   ~~~~~~~~~~~~~^~~~~~~~
/<<PKGBUILDDIR>>/universe/Meter.cpp:40:32: note: the comparison reduces to ‘(1.00999999046325683594e+0l == 1.00999999999999999999e+0l)’
/<<PKGBUILDDIR>>/universe/Meter.cpp:46:32: error: static assertion failed
   46 |     static_assert(q3.Current() == 0.01f);
      |                   ~~~~~~~~~~~~~^~~~~~~~
/<<PKGBUILDDIR>>/universe/Meter.cpp:46:32: note: the comparison reduces to ‘(9.99999977648258209229e-3l == 9.9999999999999999998e-3l)’
make[3]: *** [CMakeFiles/freeorioncommon.dir/build.make:499: CMakeFiles/freeorioncommon.dir/universe/Meter.cpp.o] Error 1
make[3]: Leaving directory '/<<PKGBUILDDIR>>/obj-i686-linux-gnu'
make[2]: *** [CMakeFiles/Makefile2:496: CMakeFiles/freeorioncommon.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
````

Environment
-----------

Debian Sid
FreeOrion 0.5 and Git master

**Comment by geoffthemedio** [comment]
I can't find a compiler setup [on Compiler Explorer](https://godbolt.org/z/a8T8WxWcb) that reproduces this, so apparently just setting the compiler to work in 32-bit mode doesn't do it.

As such, I have no way to test fixes or workaround like `#ifdef`ing out the failing rounding tests. I think that'd be the easiest workaround, as the tests aren't essential to run at compile time and if they fail, it just indicates there could probably-negligible rounding differences that probably wouldn't even be noticeable.

So, some input on what `#define` I can use to turn off these tests on the affected systems would be helpful...

**Comment by o01eg** [comment]
At least it wasn't brokn on Debian stable https://github.com/o01eg/freeorion/actions/runs/5921692617/job/16054581360 but it breaks on sid https://github.com/o01eg/freeorion/actions/runs/5922180678/job/16055799221

**Comment by o01eg** [comment]
@geoffthemedio Could you try s390x arch?

**Comment by geoffthemedio** [comment]
OK, with that test build I can tweak the `static_assert`s to check "close enough" instead of quality for the `float` results.

**Comment by geoffthemedio** [comment]
https://github.com/freeorion/freeorion/commit/b83a9d56d3a8ea2e8518c32e2e700e453aaf27fe

**Comment by apoleon** [comment]
I just did a rebuild on i386 with commit b83a9d5 applied. It looks better now but it still fails at one point with the same static assertion error.

````
[ 15%] Building CXX object CMakeFiles/freeorioncommon.dir/universe/Meter.cpp.o
/usr/bin/c++ -DBINPATH=\"/usr/bin\" -DBOOST_ALL_DYN_LINK -DBOOST_ALL_NO_LIB -DENABLE_BINRELOC -DFREEORION_BUILD_COMMON -DFREEORION_LINUX -DSHAREPATH=\"/usr/share\" -Dfreeorioncommon_EXPORTS -isystem /usr/include/python3.11 -g -O2 -ffile-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -O2 -g -DNDEBUG -std=c++20 -fPIC -fvisibility=hidden -Wall -MD -MT CMakeFiles/freeorioncommon.dir/universe/Meter.cpp.o -MF CMakeFiles/freeorioncommon.dir/universe/Meter.cpp.o.d -o CMakeFiles/freeorioncommon.dir/universe/Meter.cpp.o -c /<<PKGBUILDDIR>>/universe/Meter.cpp
/<<PKGBUILDDIR>>/universe/Meter.cpp:32:36: error: static assertion failed
   32 |     static_assert(fabs_close_enough(r3.Current(), 64998.991f));
      |                   ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
/<<PKGBUILDDIR>>/universe/Meter.cpp:46:32: error: static assertion failed
   46 |     static_assert(q2.Current() == 1.01f);
      |                   ~~~~~~~~~~~~~^~~~~~~~
/<<PKGBUILDDIR>>/universe/Meter.cpp:46:32: note: the comparison reduces to ‘(1.00999999046325683594e+0l == 1.00999999999999999999e+0l)’
make[3]: *** [CMakeFiles/freeorioncommon.dir/build.make:499: CMakeFiles/freeorioncommon.dir/universe/Meter.cpp.o] Error 1
make[3]: Leaving directory '/<<PKGBUILDDIR>>/obj-i686-linux-gnu'
make[2]: *** [CMakeFiles/Makefile2:496: CMakeFiles/freeorioncommon.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
````

**Comment by geoffthemedio** [comment]
Added the extra assert and force pushed and made a pull request #4702

@apoleon note that you can wrap code and logs with 4 ` before and after to format it better

**Comment by apoleon** [comment]
I merged the pull request locally but I still get one static assertion failed error:

````
[ 15%] Building CXX object CMakeFiles/freeorioncommon.dir/universe/Meter.cpp.o
/usr/bin/c++ -DBINPATH=\"/usr/bin\" -DBOOST_ALL_DYN_LINK -DBOOST_ALL_NO_LIB -DENABLE_BINRELOC -DFREEORION_BUILD_COMMON -DFREEORION_LINUX -DSHAREPATH=\"/usr/share\" -Dfreeorioncommon_EXPORTS -isystem /usr/include/python3.11 -g -O2 -ffile-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -O2 -g -DNDEBUG -std=c++20 -fPIC -fvisibility=hidden -Wall -MD -MT CMakeFiles/freeorioncommon.dir/universe/Meter.cpp.o -MF CMakeFiles/freeorioncommon.dir/universe/Meter.cpp.o.d -o CMakeFiles/freeorioncommon.dir/universe/Meter.cpp.o -c /<<PKGBUILDDIR>>/universe/Meter.cpp
/<<PKGBUILDDIR>>/universe/Meter.cpp:32:36: error: static assertion failed
   32 |     static_assert(fabs_close_enough(r3.Current(), 64998.991f));
      |                   ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
make[3]: *** [CMakeFiles/freeorioncommon.dir/build.make:499: CMakeFiles/freeorioncommon.dir/universe/Meter.cpp.o] Error 1
make[3]: Leaving directory '/<<PKGBUILDDIR>>/obj-s390x-linux-gnu'
make[2]: *** [CMakeFiles/Makefile2:496: CMakeFiles/freeorioncommon.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs.... 
````

Strangely enough the error only happens on Debian's build server but not on my local computer. For now I will just remove the test.

**Comment by geoffthemedio** [comment]
The 4x` need to be on their own lines.

**Comment by hifron** [comment]
> 32-bit PC (i386) no longer covers any i586 processor; the new minimum processor requirement is i686. If your machine is not compatible with this requirement, it is recommended that you stay with bullseye for the remainder of its support cycle.

**Comment by apoleon** [comment]
> > 32-bit PC (i386) no longer covers any i586 processor; the new minimum processor requirement is i686. If your machine is not compatible with this requirement, it is recommended that you stay with bullseye for the remainder of its support cycle.

That's not the problem here. i386 implies i686. The remaining problem for me is that freeorion cannot be built from source because some of Debian's build servers just run out of memory at some point (i386 (i686) and mipsel). I had this issue before and I worked around it by tuning some compiler options. Not sure what needs to be done this time because the official 0.5 version builds fine but Git master fails. I guess I just wait for the next release.

**Comment by geoffthemedio** [comment]
> freeorion cannot be built from source because some of Debian's build servers just run out of memory at some point

Could you elaborate? Are particular source files affects (eg. parsers)? Possibly this can be resolved by splitting up problematic source files.

> I guess I just wait for the next release.

The problem doen't seem likely to incidentally fix itself...

**Comment by apoleon** [comment]
[last freeorion log i386 Debian builder ](https://buildd.debian.org/status/fetch.php?pkg=freeorion&arch=i386&ver=0.5%2Bgit20230820-3&stamp=1692713513&raw=1)
This is the last log file for our i386 (i686) builder. FreeOrion fails at [ 64%] Linking CXX shared library libfreeorionparse.so. AFAICS the build system also overrides Debian's defaults and passes -03 instead of -02 and in version 0.5 -std=c++17 was used and now the standard version is c++20 (don't know if this is important though). The optimization flag -03 is more likely relevant here but I'm not sure. Hence why I assumed it just may be a temporary development setting and when you cut a new release it all will be fine TM.

The current debian/rules file for freeorion looks like that: [debian/rules](https://sources.debian.org/src/freeorion/0.5%2Bgit20230820-3/debian/rules/)

For instance I don't use parallel builds for 32 bit architectures and less debug information to reduce the memory consumption.

**Comment by o01eg** [comment]
I suppose additions to parsers make them harder to link compared to 0.5 release, maybe opinions changes.

**Comment by geoffthemedio** [comment]
Can you try with `-O2` ?

> now the standard version is c++20 (don't know if this is important though)

It's important in that the code uses C++20 features now, so that version is likely required for it to build.

**Comment by hifron** [comment]
Swap file? (it was sometime recommended that swap file should be max twice the size of memory, but 10GB should be maybe necessary if in DEFAULT parallel build)

Compiling on only 1 processor(but probably requires clean cmake .. cache or when with other parameters like RelWithDebInfo instead of Debug)
`cmake --build /home/.../freeorion/build --config Debug --target all -j 1 --`

**Comment by o01eg** [comment]
Is it possible to use bisect to found out when memory usage was raised on Debian build servers?

**Comment by apoleon** [comment]
> Can you try with -O2 ?

In CMakeLists.txt there is this line

````
$<$<AND:$<NOT:$<BOOL:${BUILD_TESTING}>>,$<CXX_COMPILER_ID:GNU>>:-O3>
````

If I change -O3 to -O2 then FreeOrion builds fine on our build servers and this solves my problem. I don't have access to the build infrastructure, so I can't give you more details or change swap size etc. 

I see three options:

1. Change -O3 to -O2 permanently
2. Add a conditional to only use -O2 when a 32 bit architecture is detected
3. Allow overriding this value

Normally the optimization flag is part of CXXFLAGS and I can override this variable with Debian's tools. However in this case -O3 is always appended after CXXFLAGS and thus has precedence. I simply can't override it without patching CMakeLists.txt

I guess the only thing that is left now is the failing test in universe/Meter.cpp.

````
static_assert(fabs_close_enough(r3.Current(), 64998.991f));
````
This still fails on some architectures and I had to disable it. Either the test should be even more "flexible" or maybe there is an overall better non-flaky way to test here.
 
By the way FreeOrion compiles on almost 20 different processor architectures now, I find this quite impressive for a game this size.

[buildd status for freeorion](https://buildd.debian.org/status/package.php?p=freeorion)

**Comment by geoffthemedio** [comment]
@apoleon does #4758 work?

**Comment by apoleon** [comment]
#4758 should work, not tested yet, but I trust Adrian, who is also a Debian developer.
