### ISSUE TITLE
Launch bay don't get increased launch rate with tech

### ISSUE THREAD

**Issue by l29ah** [freeorion/freeorion#4708]
Bug Report
==========

Environment
-----------

* **FreeOrion Version**: ae870ac7b0ed5dbe0b27116126c83680f4b121f5
* **Fetched as** 
  * Compiled from source

Description
-----------
Technologies like `Fighters and Launch Bays 2` tell that they increase launch rates of launch bays, but they don't, as seen in a battle and in fighter mouseover.

Expected Result
---------------

No discrepancy.

**Comment by Cjkjvfnby** [comment]
This is a bug in the text description. Lunch rate is definitely not updated. 

Also, I don't see that  `Upgrades the fighters of all carriers within [[metertype METER_SUPPLY]] to have plasma weaponry.`  is implemented as well.

**Comment by l29ah** [comment]
Such a description was added in 500debe7c4853dccbdbfd32a8d984951d0999a7b

**Comment by Cjkjvfnby** [comment]
> Such a description was added in https://github.com/freeorion/freeorion/commit/500debe7c4853dccbdbfd32a8d984951d0999a7b

Thank you, so it's not in tech files, it's in the part itself.

I see that FT_HANGAR_1 benefits from improvement, but hungar2,3,4 does have any mention of it.  I'm not experienced enough to understand if it's how FOCS works, or if this is just missed.

**Comment by agrrr3** [comment]
The english description tells that launch rate and capacity gets increased for interceptor fighters.
For the other fighter types damage gets increased. So this is consistent.

**Comment by l29ah** [comment]
Oops, my bad.

**Comment by agrrr3** [comment]
> I don't see that `Upgrades the fighters of all carriers within [[metertype METER_SUPPLY]] to have plasma weaponry.` is implemented as well.

this seems legit, though
