### ISSUE TITLE
[AI]  Unused method from AI interface is broken

### ISSUE THREAD

**Issue by Cjkjvfnby** [freeorion/freeorion#4709]
If you try to execute this code inside the AI you will get an error: `fo.getEmpire().exploredSystemIDs`

```
TypeError: No to_python (by-value) converter found for C++ type: class boost::container::flat_set<int,struct std::less<int>,void>
```

This method is unused, so maybe just remove it. It was working some time ago and was returning set of ints. 

Latest master, build on CI: `v0.5+ [build 2023-08-23.5a34f35] CMake`

![изображение](https://github.com/freeorion/freeorion/assets/171597/c616ef4e-5b12-4e75-99aa-e339e4f9c313)

**Comment by geoffthemedio** [comment]
hopefully fixed by 1960f4cc
