### ISSUE TITLE
Probably wrong operator precedence in SidePanel code

### ISSUE THREAD

**Issue by adrianbroher** [freeorion/freeorion#471]
When compiling `UI/Sidepanel.cpp` g++ reports the following warning:

```
<project dir>/UI/SidePanel.cpp: In Elementfunktion »void SidePanel::PlanetPanel::ClickColonize()«:
<project dir>/UI/SidePanel.cpp:2086:65: Warnung: logical not is only applied to the left hand side of comparison [-Wlogical-not-parentheses]
     if (!planet || !planet->CurrentMeterValue(METER_POPULATION) == 0.0 || !m_order_issuing_enabled)
```

I haven't yet the time to check what is the right statement by means of gameplay logic, but `!value == 0.0` probably doesn't reflect what the author actually had in mind.

**Comment by geoffthemedio** [comment]
planet->CurrentMeterValue(METER_POPULATION) != 0.0f would make more sense.

**Comment by Vezzra** [comment]
Yep, definitely. Although apparently that case gets caught somewhere else (otherwise a "Colonize" button should show up for already colonized planets), I guess it's reasonable to fix this little glitch.

Done, d3a6fa2692a7e35a9d959ca43d723ab461cfd443.
