### ISSUE TITLE
crash on turn end

### ISSUE THREAD

**Issue by Voker57** [freeorion/freeorion#4714]
Bug Report
==========

The game crashes on ending the turn

Environment
-----------

* **FreeOrion Version**: ae870ac7b0ed5dbe0b27116126c83680f4b121f5
* **Operating System**: Debian GNU/Linux
* **Graphic card used**: nVidia geForce GTX 1080
* **Fetched as** 
  * Compiled from source

Description
-----------
backtrace: [trace.txt](https://github.com/freeorion/freeorion/files/12443198/trace.txt)
save file: 
[zabagovano.zip](https://github.com/freeorion/freeorion/files/12443203/zabagovano.zip)

Expected Result
---------------

Steps to reproduce
------------------

* load the game
* end turn
* crash

**Comment by geoffthemedio** [comment]
already fixed by #4655
