### ISSUE TITLE
Annexation doesn't update ownership of buildings

### ISSUE THREAD

**Issue by Blue-Award** [freeorion/freeorion#4721]
Bug Report
==========

Annexing planet that has a building like Cultural Library doesn't make you the owner of the building, unlike invasion or gifting

You may gift the planet and the Cultural Library becomes owned, and in this particular case you get +5 science anyway from the building even if it is not owned, but that's besides the point, there are some other cases like Acirema's energy compressor or, you know, some species made independent - scripting doesn't check for ownership every time but still sounds like those buildings should be owned.. for example shipbuilding seems to check if you actually own the shipyard and annexing a planet that had shipyard doesn't make you the owner and you can't build ships

Environment
-----------

* **FreeOrion Version**: 2023-08-22 3803224
* **Fetched as** 
  * Weekly development build
 

Description
-----------

When annexing a planet with some building like Cultural Library, you don't become owner of the building

Expected Result
---------------
I am the owner of the building(s) after annexation

Steps to reproduce
------------------

Probably easiest is to start a test game with colonizable planet close (or cheap techs and resarch growth techs etc), colonize something with your initial colonizer, build a shipyard there, grant independence, annex. The shipyard is not owned by you and you can't build ships!

That's what I've done in the savegame below (turn 50 pre-annexation, turn 51 post-annexation)

[re-annexing_with_a_building.zip](https://github.com/freeorion/freeorion/files/12476296/re-annexing_with_a_building.zip)

**Comment by geoffthemedio** [comment]
I wonder if and how annexation cost should depend on the presence of buildings on a planet...

**Comment by geoffthemedio** [comment]
should be fixed by c375bb610f03d8
