### ISSUE TITLE
Targeted terraform not working as advertised

### ISSUE THREAD

**Issue by MXB2001** [freeorion/freeorion#4727]
Description
-----------
The Pedia states that targeted terraforms can be build (typo) at an outpost while popular requires pop 1 min. This is not working. The targeted terraform requires 1 pop min also (tried it an outpost).

Of course this may be an error in the Pedia instead but I report as a bug since I don't know which it is supposed to be.

**Comment by agrrr3** [comment]
Targeted terraforming is (at least it was once) intended to be buildable on
outposts. This is one of the reasons it got introduced.
