### ISSUE TITLE
Scrap unowned Scrying Spheres (minor bug)

### ISSUE THREAD

**Issue by MXB2001** [freeorion/freeorion#4746]
Bug Report
==========
Environment
-----------
* **FreeOrion Version**:
0.5
* **Operating System**:
Debian Linux
* **Fetched as** 
Flatpak

Description
-----------
Right click on unowned Scrying Sphere presents option to Scrap Building.

Expected Result
---------------
Only allowed options should appear. One can not scrap the unowned sphere if you try but it should not appear in the first place.

**Comment by geoffthemedio** [comment]
should be fixed by #4756
