### ISSUE TITLE
Design slots aren't shown

### ISSUE THREAD

**Issue by o01eg** [freeorion/freeorion#4797]
Bug Report
==========

Environment
-----------

* **FreeOrion Version**: 2023-11-24.4dfbe68 and 99dfd571abcd9edf4f65256a3a4d028c9be2be28, previous weekly test build and 972a22789ce6b80c9cd83444ca4a759e015a4a93 were fine.
* **Operating System**: Linux
* **Graphic card used**: Intel
* **Fetched as** 
  * Compiled from source

Description
-----------

Slots aren't shown in Design window and cannot be used.

![fo_2023-12-02_09-35-10](https://github.com/freeorion/freeorion/assets/397177/60e1340a-bfec-4afd-bb1e-a85d3d410813)

Expected Result
---------------

Slots are working correctly.

Steps to reproduce
------------------

* Start the game.
* Switch to Design window.
* Open existing design or hull.

**Comment by o01eg** [comment]
Bisect shows ff70c560aaf5909e06535581a2054e09a0f080a5 as culprit.

**Comment by geoffthemedio** [comment]
should be fixed by 260dd8591
