### ISSUE TITLE
Influence Int overflow

### ISSUE THREAD

**Issue by magnusviri** [freeorion/freeorion#4801]
Bug Report
==========

Large influence (69k) causes Influence Debt.

Environment
-----------

* FreeOrion 0.5 build 2023-03-21-50eff8b
* macOS 13
* M1
* Binary release

Description
-----------

I let it run forever and I started noticing revolts. When I looked at why, I see there's influence debt! It looks to me like the code that calculates influence debt is is using a signed int or something.

<img width="864" alt="Screenshot 2023-12-09 at 20 34 19" src="https://github.com/freeorion/freeorion/assets/711269/ec969a78-8801-45ab-9eba-dd303d6a6ec4">

Expected Result
---------------

Massive influence amount shouldn't produce debt.

Steps to reproduce
------------------

Win the game let it run forever.

**Comment by Grummel7** [comment]
I looked into this and found that the approach of this fix is totally wrong.
The empire stockpiles are implemented as ResourcePools, not a Meters.

I analysed this in master and could fix the issue by applying a limit in ResourcePool::SetStockpile, but looks rather hacky. 

What puzzles me is why the overflow happens at all. ResourcePool as well as scripting uses floats, there should be no problem with numbers bigger then 64k. The limit  is wrong for integers, too, 16-bit integers would overflow at 32k and 32-bit integers could handle bigger numbers, even with a meter scaling of 1/1000.

**Comment by Grummel7** [comment]
I found it: The actual problem is in EmpireStockpileValue::Match.

This function uses Meter::LARGE_VALUE for the upper limit, if no maximum is given by the condition.
So when the empire's overall influence exceed LARGE_VALUE, the condition HasEmpireStockpile(empire=Source.Owner, resource=Influence, low=0) no longer matches.

**Comment by Vezzra** [comment]
So, a proper fix is in the works? :wink:
