### ISSUE TITLE
datetime.utcfromtimestamp for version string is deprecated in Python3.12

### ISSUE THREAD

**Issue by o01eg** [freeorion/freeorion#4804]
Bug Report
==========

Environment
-----------

* **FreeOrion Version**: master
* **Operating System**: Linux
* **Fetched as** 
  * Compiled from source

Description
-----------

```
freeorion/cmake/make_versioncpp.py:151: DeprecationWarning: datetime.datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version. Use
 timezone-aware objects to represent datetimes in UTC: datetime.datetime.fromtimestamp(timestamp, datetime.UTC).
   build_no = ".".join([datetime.utcfromtimestamp(timestamp).strftime("%Y-%m-%d"), commit])
```

Expected Result
---------------

Configuration without warnings.

Steps to reproduce
------------------

* Install python3.12
* Run `python cmake\make_versioncpp.py . XXX YYY`

**Comment by Cjkjvfnby** [comment]
It's just a python script, you could run it directly from the repo root. 

```shell
python cmake\make_versioncpp.py . XXX YYY
```
