### ISSUE TITLE
Duplicate module named "multiplier" in mypy check

### ISSUE THREAD

**Issue by o01eg** [freeorion/freeorion#4810]
Bug Report
==========

Environment
-----------

* **FreeOrion Version**: [master](https://github.com/freeorion/freeorion/tree/master)
* **Operating System**: Linux
* **Fetched as** 
  * Compiled from source

Description
-----------

When I launch `mypy` I got error:

```
default/scripting/species/common/multiplier.py: error: Duplicate module named "multiplier" (also at "default/scripting/common/multiplier.py")
default/scripting/species/common/multiplier.py: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#mapping-file-paths-to-modules for more info
default/scripting/species/common/multiplier.py: note: Common resolutions include: a) using `--exclude` to avoid checking one of them, b) adding `__init__.py` somewhere, c) using `--explicit-package-bases` or adjusting MYPYPATH
```

Expected Result
---------------

`mypy` check passes.

Steps to reproduce
------------------

* Clone the repo.
* Install `mypy==1.5.0`
* Launch `mypy default/scripting/` from root.

**Comment by Cjkjvfnby** [comment]
This should solve it. 
https://github.com/freeorion/freeorion/pull/4792

**Comment by Vezzra** [comment]
> This should solve it. #4792

Did it? Can we close this issue?

**Comment by o01eg** [comment]
@Vezzra Not yet as we still have two "multiplier" modules.

**Comment by Vezzra** [comment]
Ok

**Comment by o01eg** [comment]
Next is `default/scripting/species/species_macros/stealth.py: error: Duplicate module named "stealth" (also at "default/scripting/macros/stealth.py")`. Should I reopen this issue or open new one?

**Comment by Cjkjvfnby** [comment]
Feel free to repopen

**Comment by Cjkjvfnby** [comment]
By the way, how do you run the mypy?  

If I run it in the repository (where pyproject.toml is located) with the command `mypy .`  I don't see an issue.   I use `mypy 1.8.0 ` as mentioned in the requirements.

**Comment by o01eg** [comment]
May be issue because I run it from build folder where default/ got linked. When I run it from source root folder as `mypy default/scripting/` I don't get issues.

**Comment by Cjkjvfnby** [comment]
If you don't use mypy for other projects,

I can convert pyproject.toml to the ini file and you could create a link from your home folder to it.  
In that case, all mypy runs will be with that settings. 

Mypy settings file discovery:
https://mypy.readthedocs.io/en/stable/config_file.html#the-mypy-configuration-file
