### ISSUE TITLE
Set minimum detection range of 1 for all monsters/ships/planets

### ISSUE THREAD

**Issue by Oberlus** [freeorion/freeorion#4823]
Feature request
===============

Idea
----
Set minimum detection range of 1 for all monsters/ships/planets.
Thus, all ships can always see the system in which they are, and the only undetected in-system objects must have higher stealth than the observer's detection strength.

Gain
----
Players, experienced and not, often find themselves wondering why they can't settle a planet or attack a fleet they can see. Players don't know what's happening and they believe it to be a bug (that includes me, Wobbly, LienRag, newcomers...).

Discussion
----------
The first posts in this thread deal with this:
https://www.freeorion.org/forum/viewtopic.php?p=117031

Alternative
-----------
Allow zero visibility range but make it more easily detectable. Maybe use a different ship/fleet icon for "blinded" fleets, or add a Sitrep, or highlight somehow the ships with lower than 1 detection range.

**Comment by geoffthemedio** [comment]
could you test #4917 ?

**Comment by Oberlus** [comment]
I'm sorry, I can't compile, my Ubuntu 20.04 is too old.

**Comment by geoffthemedio** [comment]
probably resolved, comment again if not
