### ISSUE TITLE
Starlane Nexus failed to open new starlane

### ISSUE THREAD

**Issue by Piwoslaw** [freeorion/freeorion#4828]
Bug Report
==========

Environment
-----------

* **FreeOrion Version**: v0.5+ [build 2023-12-2.15a17e]
* **Operating System**: Windows 11
* **Graphic card used**:
* **Fetched as** 
  * Binary release
  * Weekly development build : FreeOrion_2023-12-26.185a17e_Test_Win32_Setup
  * Compiled from source

Description
-----------
Starlane Bore/Nexus does not create any new starlanes. The building can be selected and built, but then the SitRep gives:
"At Bragi: a Starlane Nexus failed to open new starlanes."
No additional info given, for example what conditions were not met, etc.

Tried multiple times on different systems, and different weekly test builds for the last 1-2 months, now using most recent.

**Comment by MichaelCourtney** [comment]
It's very likely to have happen here:

https://github.com/freeorion/freeorion/commit/b8f864bc7e3a347ac30fbb6c307bdf9050eb2b9a

**Comment by MichaelCourtney** [comment]
Ok its working in this build:
FreeOrion_2023-10-03.de34f58_Test_Win32_Setup
but not this build:
FreeOrion_2023-10-09.540253f_Test_Win32_Setup

and that commit is 2023-10-04

**Comment by geoffthemedio** [comment]
test save?

**Comment by MichaelCourtney** [comment]
[auto.zip](https://github.com/freeorion/freeorion/files/14394085/auto.zip)

The building is finished on turn 4 and failing turn 5

**Comment by MichaelCourtney** [comment]
Commented out the checks 1 by 1, it's failing this:
https://github.com/freeorion/freeorion/blob/master/default/scripting/buildings/buildings.macros#L122-L133

![before](https://github.com/freeorion/freeorion/assets/43386669/f6d3f52d-5550-4da2-a4b9-c0d5d73a9e46)

![after](https://github.com/freeorion/freeorion/assets/43386669/700b0f73-5877-46a5-9d41-93f6b8bd1c8f)

**Comment by geoffthemedio** [comment]
How far apart are those systems? You can check in the objects window, which has a column for how far objects are from the selected system.

**Comment by MichaelCourtney** [comment]
There is? Because I can't seem to find that column. Anyway its almost dead on 90uu. Here's a 90uu circle:
![90uu](https://github.com/freeorion/freeorion/assets/43386669/278040c8-0242-46cd-bfd2-50148ca6e062)

**Comment by Blue-Award** [comment]
> There is? Because I can't seem to find that column. Anyway its almost dead on 90uu. Here's a 90uu circle: 

If you right click on column header on "Objects" list, you can change/select what column to view under that header. "Dist. to Sel. Fleet" and "Dist. to Sel. System" are some of the many columns you can choose there

It lets you to judge how far enemy can move for example, when distance circle would just be some eyeballing (like if there's a sharp turn on starlanes or something)
