### ISSUE TITLE
Forum is not working

### ISSUE THREAD

**Issue by Oberlus** [freeorion/freeorion#4829]
Bug Report
==========

https://www.freeorion.org/forum/ has been down for several hours.

**Comment by geoffthemedio** [comment]
Cloudflare error page says it's an issue with the host/server.

Hosting provider says it's an issue with Cloudflare, or at least nothing is wrong that they can see with their system.

Relevant person for Cloudflare setup is probably asleep now, so it will likely be some hours at least.

Edit: Person was awake. Is fixed. Needed an updated IP on Cloudflare's side apparently.
