### ISSUE TITLE
cmake problem with V0.5

### ISSUE THREAD

**Issue by Grummel7** [freeorion/freeorion#4830]
For testing Geoff's Meter fix I tried to compile V0.5 on my system and failed with an error in a boost/python header.
Suspecting a cmake problem I reran cmake without success. Then I copied CMakeLists.txt from master and this time running cmake fixed the problem.

I guess the problem has been fixed with dbecd7b4b5ea1fab713005061f7916844afa72f7, but trying to merge it caused some conflicts.

@o01eg Can you please have a look at this. I guess all cmake fixes not related to new code in master should be merged into V0.5

**Comment by o01eg** [comment]
I got warnings but code compiles fine.

**Comment by Vezzra** [comment]
Ok, can this issue be addressed by some kind of fix, or only by a workaround? Or, in other words: Will there be a PR which addresses this issue, or should it be closed as "wont fix"/"workaround"?

If it can only be addressed by a workaround, a description of that workaround should probably be posted here.

**Comment by o01eg** [comment]
@Grummel7 Did you fix issue locally?

**Comment by Grummel7** [comment]
I did reply in the PR saying the fix worked for me, but I can repeat it here...

**Comment by Grummel7** [comment]
Seems must add another one to close it...

**Comment by Grummel7** [comment]
argh
