### ISSUE TITLE
Xenophobic frenzy 

### ISSUE THREAD

**Issue by jeberger** [freeorion/freeorion#4836]
Xenophobic frenzy removes the self-sustaining population bonus when there are nearby populated planets. With FreeOrion 0.5 self-sustaining metabolism grants the population bonus only on planets with good environment. But xenophobic frenzy removes the bonus on all planets, not only on good ones. As a consequence, "adequate" planets become inhabitable since the bonus is removed although it was never granted in the first place.

**Comment by agrrr3** [comment]
Hi, welcome! This is not really a bug but a balancing issue. 

The self-sustainable bonus was too powerful so we restricted it to good planets. But the game changed a lot since then so maybe Trith could need a buff. If that is so, it might make sense to e.g. give half the self-sustaining bonus on adequate planets.

Anyway, balance/design discussion is supposed to happen in the forums, not on github. 
Feel free to open a topic there https://www.freeorion.org/forum/

**Comment by Vezzra** [comment]
To be fair, if a balance issue is so serious that it actually breaks some things (which seems to be the case here), classifying it as a bug is justified.

It's one thing if a balance issue just makes some things unbalanced, it's another if it outright breaks things.

Nevertheless, the discussion about how to address the issue, which usually involves doing rebalancing, should happen on the forum, not here. So, please open a thread on the forum and post a link to that thread here.

**Comment by jeberger** [comment]
Note that I'm not objecting to the fact that the bonus is now limited to good planets. My issue is that xenophobic frenzy removes the bonus _even on planets where the bonus was never granted,_ despite the fact that the Pedia states that: "_the reduction is never higher than the population bonus for Self-Sustaining Metabolism_".

**Comment by jeberger** [comment]
I've opened a thread in the forum. It's awaiting moderator approval, will post the link here when it gets through.

EDIT: Here's the forum link: https://www.freeorion.org/forum/viewtopic.php?t=12910

**Comment by Oberlus** [comment]
This is indeed a bug.

This
https://github.com/freeorion/freeorion/blob/a3605a0b2997e4b3373554a9ed6ba01859d57018/default/scripting/species/species_macros/xenophobic.py#L101C1-L104C1

Should be like this:
```
        activation=Planet(environment=[Good])
        & HasTag(name="SELF_SUSTAINING")
        & (0 < _xenophobic_selfsustaining_qualifying_planet_count()),
```

I can't make Pull Requests at the time (no dev. machine). If anyone is willing to make it...

**Comment by agrrr3** [comment]
> My issue is that xenophobic frenzy removes the bonus _even on planets where the bonus was never granted,_ despite the fact that the Pedia states that: "_the reduction is never higher than the population bonus for Self-Sustaining Metabolism_".

sorry, my bad. I thought self-sustaining and xenophobic frenzy was not intended to be connected, but separate issues. mea culpa

**Comment by agrrr3** [comment]
Added PRs for master and 0.5
