### ISSUE TITLE
With 30-01 build GUI shows zeroes as values for ships and fleets

### ISSUE THREAD

**Issue by Blue-Award** [freeorion/freeorion#4861]
Bug Report
==========

Environment
-----------
* **FreeOrion Version**: 2024-01-30 0dd6806

* **Fetched as** 
  * Weekly development build

Description
-----------

GUI shows ship/fleet values as zero in the fleet window (like structure, damage, shields, fuel etc - all of them)

Expected Result
---------------

Values showing properly for fleets, individual ships, and entire fleet summary

Steps to reproduce
------------------

You can just start single player game and see this right away with starting frigate

**Comment by geoffthemedio** [comment]
should be fixed by #4860
