### ISSUE TITLE
Neutral forces can see your stealthy ships on first bout already

### ISSUE THREAD

**Issue by Blue-Award** [freeorion/freeorion#4862]
Bug Report
==========

Neutral planets and ships see your supposedly stealthy forces right away, I mean even if the neutral's detection is lower than stealth of your ships.

Curiously wanted to reproduce this with vacuum dragon, but vacuum dragon didn't see me. So the first save I'm attaching will have a fight with vaccum dragon at nash, after new turn, where the dragon actually can't see my ships on the first bout. 

But there's still second fight about to happen, with planets, at Ruchba delta, and those do see me on the first bout despite detection 60 while the ships have effective 85 stealth (95 without starless system penalty on the turn before attack)

Even more curiously, subsequent fights, the planets at Ruchba delta can't see me on first bout the next turn. But if I jump out of the system, and come back, they see me on first bout again.

Since the fight with ship (the vacuum dragon) actually didn't show the error - dunno why, maybe it's about parts and their targetting) I went to a drone factory and a drone, and also attaching save for that. But again for the inconsistency of things, the drone and drone factory can't see me on first bout for the following fight... but one turn more, and the drone factory can see me.

In MP26 I had similar situation with drone and drone factory, and they saw my both ships on the first bout, first fight (though was bit different scenario as one ship would be steatlhy and another not)

My expectations is all those cases the ships would have not been seen for the first bout, and the fact that sometimes they actually aren't is even more surprising.

[save.zip](https://github.com/freeorion/freeorion/files/14130839/save.zip)

**Comment by geoffthemedio** [comment]
As far as I recall, the combat system doesn't distinguish between different ships on the same "team" for what is visible. For monsters/neutrals, that means that they all start being able to detect anything that any of them has sufficient detection strength to see.

Possibly the one turn differences could be related to stealth being a meter that's determined before movement, and the new location value not taking effect until the subsequent turn?

**Comment by Blue-Award** [comment]
In my repro, there's a fight with two planets. one has 60 detection, the other has 20 detection. When ships have 85 stealth, coming from starless system, they are seen. When they have 95 stealth, after they stayed around for a turn, or jumped from a system that had a star not giving penalty, they are not seen.

Similary drone factory, supposedly 10 vision, doesn't see the ships if they come in with 95 stealth, but sees them once they stay around its empty system, having 85 stealth.

It's almost as if neutrals had 90 detection strength

**Comment by Blue-Award** [comment]
Also generally, fighting other players, I am used to if there's mixed fleet with stealthy and not stealthy ships, the not stealthy ones are seen, but the stealthy are unseed on first bout. Like also happened in mp25 for example fight with 9 of my ships, 7 stealthy enough are mentioned as not detected until they launch their fighters,

**Comment by Blue-Award** [comment]
I think I found the issue, CombatInfo::GetMonsterDetection looks like monsters are getting detection strenght equal to MY detection (range), instead of monsters' detection. So when I am at empty system, I have 85 range, so that's the strength monsters get, which happens to coincide with me having 85 stealth then. Cause empty system is both bonus to range and malus to stealth. Should be able to prepare a PR fix myself
