### ISSUE TITLE
Error: Could not symlink bin/openssl

### ISSUE THREAD

**Issue by geoffthemedio** [freeorion/freeorion#4869]
Previously-successful GitHub Action build is now failing: https://github.com/freeorion/freeorion/actions/runs/7854298075/job/21441788705

````
==> Pouring openssl@3--3.2.1.ventura.bottle.tar.gz
Error: Could not symlink bin/openssl
Target /usr/local/bin/openssl
is a symlink belonging to openssl@1.1. You can unlink it:
  brew unlink openssl@1.1

To force the link and overwrite all conflicting files:
  brew link --overwrite openssl@3

To list all files that would be deleted:
  brew link --overwrite --dry-run openssl@3
Error: Process completed with exit code 1.
````

Doesn't seem to affect pull request builds, eg: https://github.com/freeorion/freeorion/actions/runs/7857658436/job/21441808812?pr=4868
Edit: Or it does affect pull request builds: https://github.com/freeorion/freeorion/actions/runs/7857792783/job/21442056074?pr=4868

**Comment by o01eg** [comment]
Looks like if had openssl-1 in cache which was restored over openssl-3, I've just removed `build-macos-13` and that step passed successfully.

**Comment by geoffthemedio** [comment]
re-running an affected action builds seems to not have the issue.

https://github.com/freeorion/freeorion/actions/runs/7854298075/job/21455242523

**Comment by geoffthemedio** [comment]
Still gaving the issue on a branch... 

https://github.com/freeorion/freeorion/actions/runs/7865047054/job/21475111531?pr=4765#step:8:32

Does something need to be done separately for that?

Edit: now it's working...
