### ISSUE TITLE
Inconsistant species modifiers to policies depending on focus

### ISSUE THREAD

**Issue by MichaelCourtney** [freeorion/freeorion#4870]
Bug Report
==========
Cray receive the research bonus to centralisation when research focused, but not when industry focused.
Cray receive the industry penalty to centralisation when industry focused, but  not when research focused
Presumably this happens to other policies/techs/specials, centralisation was just the 1 I noticed.

![Cray1](https://github.com/freeorion/freeorion/assets/43386669/8cc11b3d-af54-4cc2-95dc-a75d982b5fd8)
![Cray2](https://github.com/freeorion/freeorion/assets/43386669/01a38fa6-e751-4013-85b1-fa048acd68f2)
![Cray3](https://github.com/freeorion/freeorion/assets/43386669/16366203-7603-45f6-ad03-93164a8a7372)
![Cray4](https://github.com/freeorion/freeorion/assets/43386669/f2996d1a-a258-41f8-9a73-fc9454a00137)

Environment
-----------
build 2024-01-22.373998f

Expected Result
---------------
Either no species modifiers to centralisation or the same species modifiers to centralisation independent of focus.

Steps to reproduce
------------------
Start game with player Cray. Adopt centralisation policy. Switch Focuses.

**Comment by MichaelCourtney** [comment]
Apparently happens with metropoles too. Simplest fix is to move anything that doesn't require a focus to after the species bonus/penalty. Otherwise you have to deal with species like Cynos (no industry focus) and Phinnert (no research focus)

**Comment by MichaelCourtney** [comment]
Part 1(of 2):
https://github.com/freeorion/freeorion/pull/4886
Part 2(of 2):
https://github.com/freeorion/freeorion/pull/4887

**Comment by Vezzra** [comment]
@MichaelCourtney, both of these PRs have been merged, can we close this issue as resolved?
