### ISSUE TITLE
Nearuniversal Translator Bonus Calculation ignores planets

### ISSUE THREAD

**Issue by JoschHH** [freeorion/freeorion#4874]
Bug Report
==========
The "Nearuniversal Translator" bonus is only calculated from population. The "square root of number of races with a planet on influence focus with a translator built" seems to be ignored.

Environment
-----------
* Windows 10 Pro
* V0.5 Build 2023-03-21eff8b
* **Fetched as** 
  * Binary release

Description
-----------
According to explanation text, it is supposed to increase influence generation by a factor depending the number of races, that have one operational. 

In my game, the factor stayed the same regardless of the number of translators I built with different races. Deleting the translators on other planets also did not decrease the effect again. 

Expected Result
---------------
The bonus figure should vary depending on the no of races with an active translators built 

Steps to reproduce
------------------
<contact me for hints, which logfiles might help you evaluate this behaviour>

**Comment by MichaelCourtney** [comment]
> # Bug Report
> The "Nearuniversal Translator" bonus is only calculated from population. The "square root of number of races with a planet on influence focus with a translator built" seems to be ignored.
> ## Description
> 
> According to explanation text, it is supposed to increase influence generation by a factor depending the number of races, that have one operational.
> In my game, the factor stayed the same regardless of the number of translators I built with different races. Deleting the translators on other planets also did not decrease the effect again.
> The bonus figure should vary depending on the no of races with an active translators built
> ## Steps to reproduce

![translator](https://github.com/freeorion/freeorion/assets/43386669/5ad755a0-fe6e-44d0-881f-b6d7564b6d8d)

it's "number of unique species on planets controlled by the _empire that owns this building_" not
"_number of unique species_ on planets controlled by the empire that _owns this building_"

e.g. "how many species does the empire have" not
"how many species have the building"

**Comment by JoschHH** [comment]
Argh- I read that wrong. Thx, Case dismissed
