### ISSUE TITLE
Border Checkpoints Policy

### ISSUE THREAD

**Issue by 101Wanderer101** [freeorion/freeorion#4885]
An unowned planet with stealth 45 on my supply line and even with my own planet in the system is still invisible with my detection strength 30 but with Border checkpoints policy ON for 20 moves. Sorry, if it's not a bug,

**Comment by MichaelCourtney** [comment]
There is a mismatch between the scripting and the pedia. The scripting specifically only effects ships:

https://github.com/freeorion/freeorion/blob/master/default/scripting/policies/CHECKPOINTS.focs.txt#L22-L29

The pedia specifies ships _and planets_, also the top line about hindering supply is outdated. That was removed here:

https://github.com/freeorion/freeorion/commit/7060115b099914793388b46cb0d94ad1c4cd8343


![BC](https://github.com/freeorion/freeorion/assets/43386669/fce74bc4-1878-490b-a189-3a9fb812b162)

Old discussion occured here and here:

https://freeorion.org/forum/viewtopic.php?f=15&t=12618
https://freeorion.org/forum/viewtopic.php?f=15&t=12593

**Comment by MichaelCourtney** [comment]
https://github.com/freeorion/freeorion/pull/4889

Forum discussion suggests its a documentation error, rather then a bug.

**Comment by MichaelCourtney** [comment]
Found a 2nd bug here. It effects outposts, though the meter never actually changes because its an outpost.
![checkpoints](https://github.com/freeorion/freeorion/assets/43386669/c87e5daa-1d28-44a4-9ca6-8ab567d8a5ce)

**Comment by MichaelCourtney** [comment]
Probably the best way to fix the 2nd bug is not to charge for outposts? That's more consistent with other policies.

**Comment by agrrr3** [comment]
Agreed, outposts should not cost influence

**Comment by crazymerlyn** [comment]
This seems to have been fixed by #4889. Is there still something left to do here?

**Comment by geoffthemedio** [comment]
If not, please comment about what's missing...
