### ISSUE TITLE
Incorect Annex Sitrep

### ISSUE THREAD

**Issue by MichaelCourtney** [freeorion/freeorion#4902]
![drkosy](https://github.com/freeorion/freeorion/assets/43386669/fbe438a4-e86c-4698-8207-5019a73d92b9)

Should have been "by wobbly"

**Comment by geoffthemedio** [comment]
Can you test with #4904 ? Seems to work for me...

![annexed sitrep](https://github.com/freeorion/freeorion/assets/11386908/d283628d-a95e-49aa-8e51-f3f032bcaa78)

**Comment by MichaelCourtney** [comment]
> Can you test with #4904 ? Seems to work for me...

Tested in multiplayer. Also works for me.
