### ISSUE TITLE
Turn 1 Influence Malus

### ISSUE THREAD

**Issue by MichaelCourtney** [freeorion/freeorion#4903]
On turn 1 there is -1 IP on the capital influence malus marked "unknown". Trial and error shows its the Capital disconnect penalty scripted here:

https://github.com/freeorion/freeorion/blob/master/default/scripting/species/species_macros/influence.py#L136

**Comment by MichaelCourtney** [comment]
Fix:

https://github.com/freeorion/freeorion/pull/4901

**Comment by Blue-Award** [comment]
Are you able to link your issue with my PR "officially" so it shows on the "development" side bar? I can't seem to be able to add from PR's side that "successfully merging this PR would close this issue" but maybe that's reserved for people with more editing power

**Comment by geoffthemedio** [comment]
usually putting "fix #XXXX" or similar in the pull request description will auto close the issue when the pull request is merged, at least when I do it.
