### ISSUE TITLE
(multiplayer 26th) Conceeding Empire's assets disapear

### ISSUE THREAD

**Issue by MichaelCourtney** [freeorion/freeorion#4906]
This behaviour didn't exist in earlier MPs and is likely unintended.

https://freeorion.org/forum/viewtopic.php?t=12878&start=312

**Comment by geoffthemedio** [comment]
There is and has been code to delete stuff of eliminated empires for quite a while... not sure why it didn't work previously.

**Comment by MichaelCourtney** [comment]
Conceding empires planets have remained in every game since I started playing MP, which would be somewhere around 14th MP. My understanding is the empire colonies disappeared in older MP games, and this was considered unfair.

The attacking empire spends resources building attack fleets and troop ships, in return for conquered planets, but then the losing side concedes, leaving the attacker in a position where they've already spent the resources but don't get the returns.

Maybe ideal is for a conceding empire's planets to become independant, similar to what happens after building independence decree.

https://github.com/freeorion/freeorion/blob/master/default/scripting/buildings/COLONY_INDEPENDENCE_DECREE.focs.txt

Not sure what to do about ships, previously they have remained, but lacked the empire techs on the weapons.

**Comment by geoffthemedio** [comment]
The `INDEPENDENT_COLONY_X_SPECIAL` adding effects are problematic for a core game mechanic, since it can't rely on particular specials being defined.

**Comment by MichaelCourtney** [comment]
I'll take your word on that. I'm not sure what's actually best, I'll just name some issues that occur when an empire planet or ship becomes simply "unowned"

- Planets reliant on growth techs to be habitable die out
- Planets lose defense and troop techs making them much easier to invade then if the player played on
- Ships lose their empire weapon techs

You can probably find old discussions about it on the forum, but the short of the long is no-one seems to actually come up with a fully satisfactory solution.

**Comment by geoffthemedio** [comment]
Despite those issues, presumably #4909 would be better than it is now and make it possible to go back to how it was previously, with stuff just becoming unowned? A test report would be helpful...

**Comment by MichaelCourtney** [comment]
Agreed. I'll test later in the week when I have spare time. My computer is a little slow, so compiling requires a large block of free time.

**Comment by MichaelCourtney** [comment]
Not sure if the confusion is me not speaking clearly. With code changes, I have to re-compile and compiling causes my computer to hang for potentially a few hours.

Basically I agree the change, it'll just take me a bit of a time to check it actually works.

**Comment by MichaelCourtney** [comment]
ok I'd test if I could actually work out how to change the game settings in multi-player mode

**Comment by geoffthemedio** [comment]
guess I'll just merge and it can be tested in MP later...
