### ISSUE TITLE
freeorion.org inaccessible

### ISSUE THREAD

**Issue by geoffthemedio** [freeorion/freeorion#4929]
Attempting to access freeorion.org gives a 403 Forbidden error, saying:

You don't have permission to access this resource.Server unable to read htaccess file, denying access to be safe

**Comment by geoffthemedio** [comment]
Apparently some script running on the site was using too many server resources and they disabled the whole website directory. The site has been running nothing but phpBB and MediaWiki for years, so I'm not sure what the issue was. I am currently waiting for more info...

**Comment by geoffthemedio** [comment]
The hosting provider says a bot was attempting to crawl the site to train a language model. Since we use Cloudflare to protect against traffic spikes (after one took down the site and lead to a $1000 hosting bill in 2019) the host couldn't block the bot by IP, and thus took down the whole site to prevent it from affecting anything else hosted on the same server. We apparently need to do something in the Cloudflare account to prevent this. The appropriate person has been informed.

**Comment by o01eg** [comment]
Good thing it wasn't some security breach.

**Comment by Oberlus** [comment]
Maybe related, if not already done: robot.txt to disallow the scrapping bots
https://neil-clarke.com/block-the-bots-that-feed-ai-models-by-scraping-your-website/

**Comment by Vezzra** [comment]
Since the website and forums are still down, a brief notification here: this weeks test builds are available at sourceforge:

https://sourceforge.net/projects/freeorion/files/FreeOrion/Test/

**Comment by geoffthemedio** [comment]
A rule to block "ClaudeBot" has been added to CloudFlare. I've replied to the issue on the site host informing them of this.

**Comment by geoffthemedio** [comment]
The site appears to be back up again...
