### ISSUE TITLE
Universe generator doesn't work with boost 1.85 and python 3.12

### ISSUE THREAD

**Issue by o01eg** [freeorion/freeorion#4949]
Bug Report
==========

Environment
-----------

* **FreeOrion Version**: 0.5.0.1 and 092ea03
* **Operating System**: Gentoo Linux AMD64
* **Fetched as** 
  * Compiled from source

Description
-----------

Bug was reported here: https://bugs.gentoo.org/932780

There was error in the server logs:

```
08:18:20.723186 {0x00007ffff3e6cc00} [error] python : util.py:45 : Python create_universe: couldn't get any home systems, ABORTING!
08:18:20.725162 {0x00007ffff3e6cc00} [error] server : PythonCommon.cpp:101 : Traceback (most recent call last):
08:18:20.725177 {0x00007ffff3e6cc00} [error] server : PythonCommon.cpp:101 :   File "/usr/share/freeorion/default/python/common/listeners.py", line 42, in wrapper
    res = funct(*args)
          ^^^^^^^^^^^^
08:18:20.725182 {0x00007ffff3e6cc00} [error] server : PythonCommon.cpp:101 :   File "/usr/share/freeorion/default/python/universe_generation/universe_generator.py", line 121, in create_universe
    raise Exception(err_msg)
08:18:20.725185 {0x00007ffff3e6cc00} [error] server : PythonCommon.cpp:101 : Exception: Python create_universe: couldn't get any home systems, ABORTING!
```

[freeorion-logs.zip](https://github.com/freeorion/freeorion/files/15455964/freeorion-logs.zip)

Expected Result
---------------

The game is started.

Steps to reproduce
------------------

* Install boost 1.85 and python 3.12
* Build freeorion.
* Start the game.
* Issue occurs.

**Comment by ionenwks** [comment]
As noted in the Gentoo bug, I was able to workaround this by adding `-fno-strict-aliasing` when building freeorion, so I assume there's some aliasing issue somewhere *possibly* specific to gcc14+boost-1.85. Haven't tried to debug this further.

Unsure if will manage to reproduce, but we'll just pass -fno-sa downstream and not worry about it further for now.

**Edit:** been told it happens with gcc13 too, so maybe just boost-1.85 and maybe some condition

**Comment by ionenwks** [comment]
For the record, recent findings in the downstream https://bugs.gentoo.org/932780 point to this most likely being an issue in boost headers themselves:

https://github.com/boostorg/container/issues/281
https://github.com/boostorg/container/issues/252

**Edit:** see also the new downstream bug for boost at https://bugs.gentoo.org/933289
