### ISSUE TITLE
Stealth ships sucked into combat despite passive fleet stance

### ISSUE THREAD

**Issue by Blue-Award** [freeorion/freeorion#4955]
Probably was there for a loong time. If a combat is triggered in a system, then fleets set to Passive stance actually participate in the fight despite the stance's description of "not firing in combat at all"

I've set up a repro where a monster engages player's planet and there is highly stealthed ship in the system, too. The ship is in passive stance, so should not engage and thus remain stealthed. Meanwhile, it decloacks and engages in combat.

[PassiveCombat.zip](https://github.com/user-attachments/files/15828106/PassiveCombat.zip)

I've tracked it down to CombatSystem.cpp::ObjectCanAttack wanting to retrieve ship's fleet stance, but the place it takes fleets from, CombatInfo object, doesn't hold the fleets. So every object is considered to be able to attack at that point, despite of what code tries to achieve (return false for passive hide fleet)

So it should take the fleet's stance from elsewhere.

I initially tried to fix it by copying fleets into CombatInfo's objects, and it works, however combat message now shows fleets as "cannot initially detect". So probably it should be fixed differently, or exclude the fleets explicitly from that message, too.

On the latter, philosophical note is if invisible ships that never fired should even be mentioned in the combat log!

**Comment by agrrr3** [comment]
I think we have two issues here: the important one:  passive hide ships should never shoot or launch fighters, no matter what happens

the other issue is what is written into the combat log.

for the combat log it would be okayish not to log ships which were not detected at all.
it think the right solution here is to give info about hidden ships to A) empires which had full vision of it at the beginning of the combat and B) to empires which detected it later; which currently means to all empires if and only if the ship actually shot/launched fighters.

i also think it is ok to quickfix the first problem first and then have a good look at the combat log.
the quickfix which i would prefer is to use the universe passed in into the combatinfo to lookup the fleet stance.

note that the scripting in principle allows to target unseen objects and that might make sense for something e.g. like a system-wide bomb which does not care about visibility or ownership.

**Comment by agrrr3** [comment]
@Blue-Award do you want to implement or should I implement something and you review/test ?

**Comment by Blue-Award** [comment]
I've tested that change that it indeed fixes the main issue (and fleets aren't in the combat info now, so don't show up in messages, unlike my first go)

**Comment by Blue-Award** [comment]
per discussion on the PR, I went back to my original attempt i.e. actually copying fleets to combat info, just edited the combat log not to show them as "initially unable to detect", as I think that's redundant and confusing
