### ISSUE TITLE
Sitrep not reporting some enemy ship arrival warnings or the resulting combat

### ISSUE THREAD

**Issue by MXB2001** [freeorion/freeorion#4963]
Environment
-----------
* **FreeOrion Version**:
0.5.0.1
* **Operating System**:
Linux
* **Fetched as** 
Snap

Description
-----------
The situation report (news) failed to warn of enemy ships arriving next turn at Tombstone. The following turn it only reported the arrival of enemy ships (singly, not as a fleet for some reason) and no combat. There was combat which destroyed the defending fleet however.
The attacking ships had no stealth and were visible on the map. The defending ships did have stealth sufficient to make them invisible to the attacking fleet. They were set to aggressive stance (intentionally) so as to defend the system.

Save file & log (a couple of turns (2?) after the bug happened, the older news can of course still be seen:

[save-20240615_005116.sav.gz](https://github.com/user-attachments/files/16018149/save-20240615_005116.sav.gz)

[freeorion.log](https://github.com/user-attachments/files/16018153/freeorion.log)

Expected Result
---------------
Obviously the news is supposed to report these things.

**Comment by agrrr3** [comment]
Loaded the save game; everything looks good to me

> The situation report (news) failed to warn of enemy ships arriving next turn at Tombstone.

Neighboring system Antilia is closer than the 75uu speed of the enemy ships.
If you had turn 352 savegame you could look if the enemy shis are in or even beyond Antilia. In that case one would not get a sitrep, as the destination is not clear.

> The following turn it only reported the arrival of enemy ships (singly, not as a fleet for some reason)

AI did put the ships in one ship fleets. dunno

> and no combat. There was combat which destroyed the defending fleet however.

sitreps sais `At Tombstone: there was Combat with Entente.`

**Comment by MXB2001** [comment]
I don't recall seeing a combat report on the turn the ships vanished but who knows. I think I may also have sent the wrong save from a turn before the events. In any case due to all the confusion I'll consider this my mistake (as is anyways for the warning) and just keep an eye out in the future (as I'm pretty sure I've seen missed combat reports before).
