### ISSUE TITLE
inline images in pedia are broken

### ISSUE THREAD

**Issue by Grummel7** [freeorion/freeorion#4964]
Playing with current master I noticed that images within the Pedia text are not rendered, although the icons in upper right is shown as expected. The images exists and it is not only this, but all inline images are displayed like that.

![img_src](https://github.com/freeorion/freeorion/assets/20499830/a8e3f1a9-6d7b-4b75-976d-fd8805d07ad6)

**Comment by geoffthemedio** [comment]
looks OK for me...

![image](https://github.com/freeorion/freeorion/assets/11386908/29c258cf-3745-4f44-ad8f-6d7a4e0f6659)

**Comment by geoffthemedio** [comment]
Can you add some debug code and reply with what it outputs when viewing the Scylior pedia page?:

````
diff --git a/GG/src/RichText/ImageBlock.cpp b/GG/src/RichText/ImageBlock.cpp
index 63b8a34f8..c64be1cba 100644
--- a/GG/src/RichText/ImageBlock.cpp
+++ b/GG/src/RichText/ImageBlock.cpp
@@ -16,6 +16,7 @@
 #include <GG/TextControl.h>
 #include <GG/Texture.h>
 #include <GG/utf8/checked.h>
+#include <boost/stacktrace.hpp>
 
 
 using namespace GG;
@@ -26,6 +27,8 @@ ImageBlock::ImageBlock(const fs::path& path, X x, Y y, X w,
                         GG::Flags<GG::WndFlag> flags) :
     BlockControl(x, y, w, flags)
 {
+    std::cout << "ImageBlock path: " << path << "  stack: " << boost::stacktrace::stacktrace() << std::endl;
+
     try {
         m_graphic = Wnd::Create<StaticGraphic>(
             GetTextureManager().GetTexture(path),
diff --git a/GG/src/RichText/RichText.cpp b/GG/src/RichText/RichText.cpp
index edb1889ab..8579b3929 100644
--- a/GG/src/RichText/RichText.cpp
+++ b/GG/src/RichText/RichText.cpp
@@ -265,8 +265,10 @@ void RichTextPrivate::CreateBlocks(std::vector<RichTextTag> tags)
         const auto it = std::find_if(m_block_factory_map.begin(), m_block_factory_map.end(),
                                      [tag = std::string_view{tag.tag}](const auto& key_fac)
                                      { return key_fac.first == tag; });
-        if (it == m_block_factory_map.end())
+        if (it == m_block_factory_map.end()) {
+            std::cout << "CreateBlock no factory for tag: " << tag.tag << "  params: " << tag.tag_params << "  content: " << tag.content << std::endl;
             continue;
+        }
         const auto* fac = it->second.get();
         if (!fac)
             continue;
diff --git a/GG/src/RichText/TextBlock.cpp b/GG/src/RichText/TextBlock.cpp
index ffa44225e..e586b4ef2 100644
--- a/GG/src/RichText/TextBlock.cpp
+++ b/GG/src/RichText/TextBlock.cpp
@@ -22,6 +22,8 @@ TextBlock::TextBlock(X x, Y y, X w, std::string str,
 {
     SetName("TextBlock: " + str.substr(0, 16));
 
+    std::cout << "TextBlock str: " << str << std::endl;
+
     // Construct the text control. Activate full text wrapping features,
     // and make it stick to the top.
     // With these setting the height is largely ignored, so we set it to one.
````

**Comment by Grummel7** [comment]
Its actually a linker issue, but it's puzzling me.
https://github.com/freeorion/freeorion/blob/367dbe1ef3d3237f7c621a824b49e8e4e0a991f0/GG/src/RichText/ImageBlock.cpp#L140
ImageBlock registers itself to block factory, but this code is stripped away by the linker. Which is strange, because there is a call from to it from ClientUI.
https://github.com/freeorion/freeorion/blob/367dbe1ef3d3237f7c621a824b49e8e4e0a991f0/UI/ClientUI.cpp#L629

The linker only includes this function, but removes all the rest of ImageBlock:
```
$ nm -C freeorion | grep ImageBlock
                 U GG::ImageBlock::SetDefaultImagePath(boost::filesystem::path)
```

But GG::ImageBlock::SetDefaultImagePath calls GG::ImageBlock::SetImagePath. I even tried to print dummy, and I got a 0, but still the rest of ImageBlock was stripped away.

I could fix the issue by explicitly linking ImageBlock.o outsides libGG, though.

I am using g++-12, btw.

**Comment by Grummel7** [comment]
I was too tired yesterday, I should have known this bug pattern. I am still surprised by the linker result, but that was not the problem.

The actual problem is that both dummy in ImageBlock and default_block_factories in RichText are created during static initialisation, so there is no guarantee which one is created first. In my case ImageBlock registered itself to an uninitialised vector, which by chance did not crash, but the vector initialisation then removed the entry.
