### ISSUE TITLE
Right click "Rename Design" doesn't work

### ISSUE THREAD

**Issue by MXB2001** [freeorion/freeorion#4969]
Environment
-----------
* **FreeOrion Version**:
0.5.0.1
* **Operating System**:
Linux
* **Fetched as** 
Snap

Description
-----------
The right click menu on start designs in the design screen has an option named rename design. It pops up a little field where you can rename the ship but when you do and click OK nothing happens other than the field closing.
The ship design can be selected and renamed successfully on the window where the graphic image is shown which also has a rename design button.

Recommendation
--------------
Since it seems superfluous, delete the non working menu option, it just wastes time and space.

**Comment by geoffthemedio** [comment]
> start designs

Do you mean saved designs or finished designs?

Regardless, it's supposed to work, but I think there are bug(s) in the functions that [check if a rename order is valid](https://github.com/freeorion/freeorion/blob/master/util/Order.cpp#L1771).

**Comment by MXB2001** [comment]
> > start designs
> 
> Do you mean saved designs or finished designs?

I didn't pay attention to that.

OK, checked.

It was in Design Starts window and the Finished Designs "Tab", right click on a finished design and a menu pops up. The rename option there is the one that doesn't work.
