### ISSUE TITLE
Error in build: CMakeFiles/freeorion.dir/__/__/UI/TechTreeWnd.cpp.o:

### ISSUE THREAD

**Issue by mtdew365** [freeorion/freeorion#497]
This happens with the latest build.... (8281b9d)
Fedora 23 x64 bit

CMakeFiles/freeorion.dir/**/**/UI/TechTreeWnd.cpp.o: In function `TechTreeWnd::LayoutPanel::TechPanel::Update()':
TechTreeWnd.cpp:(.text+0x56b8): undefined reference to`typeinfo for Effect::EffectBase'
TechTreeWnd.cpp:(.text+0x56d1): undefined reference to `typeinfo for Effect::EffectBase'
collect2: error: ld returned 1 exit status
client/human/CMakeFiles/freeorion.dir/build.make:1849: recipe for target 'freeorion' failed
make[2]: **\* [freeorion] Error 1
CMakeFiles/Makefile2:454: recipe for target 'client/human/CMakeFiles/freeorion.dir/all' failed
make[1]: **\* [client/human/CMakeFiles/freeorion.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: **\* [all] Error 2

Thanks

**Comment by geoffthemedio** [comment]
Can you try to narrow it down to a particular line that causes that error, by commenting out other stuff?

**Comment by mtdew365** [comment]
I will try....

```
[74%] Built target freeoriond
CMakeFiles/freeorion.dir/__/__/UI/TechTreeWnd.cpp.o: In function `TechTreeWnd::LayoutPanel::TechPanel::Update()':
TechTreeWnd.cpp:(.text+0x56b8): undefined reference to `typeinfo for Effect::EffectBase'
TechTreeWnd.cpp:(.text+0x56d1): undefined reference to `typeinfo for Effect::EffectBase'
collect2: error: ld returned 1 exit status
client/human/CMakeFiles/freeorion.dir/build.make:1849: recipe for target 'freeorion' failed
```

This was all one line.

edited: fix formatting. Cjkjvfnby

**Comment by Cjkjvfnby** [comment]
You can use markdown to show logs as code. It will escape single backticks. You can find reference to markdown near comment button: `Styling with Markdown is supported`

**Comment by mtdew365** [comment]
Confirmed working.  Thanks.
