### ISSUE TITLE
kraken-1.png incorrect sRGB profile

### ISSUE THREAD

**Issue by dbenage-cx** [freeorion/freeorion#499]
On first load(pedia or map selection) of a larval kraken, libpng 1.6+ reports
"libpng warning: iCCP: known incorrect sRGB profile"

http://www.libpng.org/pub/png/libpng-manual.txt (next to last mention of 'iCCP')

Could be ignored in source or I took liberty to convert via gimp if it is helpful: https://github.com/dbenage-cx/freeorion/tree/iCCP-kraken-1

**Comment by Vezzra** [comment]
Sounds reasonable.

Can you make a pull request? Easier to merge...

**Comment by Vezzra** [comment]
Should be fixed by #500.
