### ISSUE TITLE
Local server and AI client not starting up in Windows when under path with out-of-codepage unicode

### ISSUE THREAD

**Issue by Blue-Award** [freeorion/freeorion#4991]
If the game is placed under a path that has unicode characters that don't translate to current codepage under Windows, and Windows is not set to default to utf8 for "non unicode" apps, bunch of things don't work.

Maybe the app could use setting to utf8 codepage after all, at least on recent Windows, and require workarounds for older Windows if someone has issues? 

But, I can keep fixing, too! 

After application of all other fixes so far, the game starts, sounds work, textures work, fonts work. But, you still can't play, single player at least, because the local server won't start (and slightly getting ahead, AI clients won't start, either)

Initial investigation (with the other fixes applied) puts first instance of failure on 
https://github.com/freeorion/freeorion/blob/6c6a58bbed647f56490c9b3728bdc540d052077d/server/ServerApp.cpp#L185

Using boost::filesystem::path.string() in our scenario makes the narrow string end up with ???? in path, which doesn't actually lead to proper ai client executable. So, local server fails to spin up local AI clients, and fails.

When that's fixed, then AI clients have their own issue to boot, too.

Need to comprehensively review remaining usages of path.string() and path.generic_string() to avoid such issues. Most of those should likely be replaced with PathToString. This is even relevant for debug logging of generic_string in case we ever want to move to std::filesystem instead of boost::filesystem, as my exploration in that area shows that MSVC is perfectly happy to throw exception if it can't convert file name to narrow string, as opposed to boost calmly putting question marks ???? in output string. Though might leave those logging cases until such time we actually move to std::filesystem

I'll try to make a local game finally actually work, at least with Continue/New Game/Quickstart, which may still leave some things out around options dialog and file save/load dialog.

**Comment by o01eg** [comment]
Maybe we need to use boost::process instead of `Process` so we can handle boost file names there.

**Comment by Blue-Award** [comment]
At places boost::filesystem::path is created out of std::string via implicit constructor and that bypasses the `FilenameToString` conversion silently. I've fixed some things like that in https://github.com/freeorion/freeorion/pull/4990 but I see more. 

An example is string table loading. For example `RequiredCharsets()`

https://github.com/freeorion/freeorion/blob/c10a310b93bafb1282c7d59ebd0f646910016fe0/UI/ClientUI.cpp#L432-L434

This will fail to load the charsets if `file_name` has actual utf8 encoded codepoints, cause the path implicit constructor will just take that string as is without conversion (or rather, with locale conversion, where relevant, which is not by default utf8), so there will be no such file path on Windows. We need to convert that path to wide ourselves, or rather use `FilenameToPath` and it is a subtle and silent way for things to go wrong.

I wonder if setting default conversion / locale to UTF-8 in wmain would solve that (but is it desired to begin with?). Or just imbuing the boost::filesystem with utf8 locale, for example just calling `boost::nowide::nowide_filesystem()` - but seems @geoffthemedio didn't like that (and it wouldn't work with std::filesystem anyway... so using `boost::nowide` in more targetted ways seemed ok)

I've just temporarily marked the problematic implicit constructor in boost's path.hpp as explicit and see what fails during compilation and will roll on those fixes here too for relevant places

I think another place things could go similarly wrong is operator/ for appending to paths, if input is not a fixed narrow string but something we took from settings and is narrow string encoded to utf8. Perhaps operator= too

So yeah I'll go looking for those places tho it's bit going against the tide which would presumably be dealt with if entire windows app was set to utf-8 in a few ways but maybe programmatically with `setlocale()` https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/setlocale-wsetlocale?view=msvc-160#utf-8-support

perhaps worth to leave people using Windows older than Windows 10 1803 (April 2018) behind on this issue, and set FreeOrion.exe to utf-8 locale (not like people complained about this in past, right?) But I'm still game to fix this stuff where I see it, to make the utf8-utf16 and utf16-utf8 conversions more explicit/actually present where relevant on Windows

**Comment by Blue-Award** [comment]
Hmm looking at PythonBase.cpp, seems at least there Python is initialized to use UTF-8 encoding, which perhaps already makes the FreeOrion.exe app reliant on the aforementioned UTF-8 support in Windows (April 2018 onwards)

https://github.com/freeorion/freeorion/commit/aa9689855cdf5e7e05a0ee73ba48ba6aac410028

I was looking there since there are those implicit fs::path conversions not going via utf8 and walked onto the above

so maaaybe it's not that bad to set that encoding for entire app on start

**Comment by geoffthemedio** [comment]
`Py_SetStandardStreamEncoding` claims to affect how the Python interpreter handles scripts, not how pathes are handled (unless written out explicitly in the scripts, I suppose)

**Comment by Blue-Award** [comment]
> `Py_SetStandardStreamEncoding` claims to affect how the Python interpreter handles scripts, not how pathes are handled (unless written out explicitly in the scripts, I suppose)

Yes. I was wondering if this is some bespoke handling by Python internals here, or is it more of a pass through to Windows handling given locale. In the latter case it would mean it depends on Windows being able to handle UTF-8 locale


BTW I tried to imbue logger file stream with utf8 locale which would handle logging wide strings properly (main issue behind python init failing currently) and it's eluding me a bit, but maybe I need to do something about severity levels per boost tutorial https://live.boost.org/doc/libs/master/libs/log/doc/html/log/tutorial/wide_char.html (but Freeorion has this logging setup more convoluted than in this example). I think setting UTF-8 locale on startup could solve that too but meanwhile my PR there does explicit utf8 encoding of the logging message

**Comment by Blue-Award** [comment]
TBH I am not sure what that `Py_SetStandardStreamEncoding` was meant to fix, when would python init return false so that this bit is called and saves the day?

https://docs.python.org/3/howto/unicode.html suggests utf8 is the default encoding for python anyway, if you have source file with different encoding you can put into the source file something like
<pre>
# -*- coding: latin-1 -*-
</pre>

but it doesn't seem to be a problem for Freeorion directly, perhaps for modders who add python scripts and encode differently for some reason?

Or maybe when some system settings are gobbled in for Python instead of embedded settings? (probably could use explicit isolated config)

Just a note from inquisitive mind, presumably no need to worry about it. Though  `Py_SetStandardStreamEncoding`  is Deprecated since version 3.11

More relevantly, I checked `boost::python::exec` works with utf8 encoded `char*` though in the end opted to use `boost::python::str` and let it handle `path.native()` whatever way it wants (rather than using `PathToString(path)` in the bit like `PythonBase::AddToSysPath`)
