### ISSUE TITLE
Submenu for Meters in Object window disappears too fast to select anything

### ISSUE THREAD

**Issue by petervdmeer** [freeorion/freeorion#5027]
Bug Report
==========

Environment
-----------
* **FreeOrion Version**: fd02446ad0bf344b0d7dee059d40e0c2db3975ab
* **Operating System**: Debian Linux
* **Graphic card used**: Intel Corporation Skylake GT2 [HD Graphics 520] 
* **Fetched as**
  * Compiled from source

Description
-----------
Changing a column in the objects window to one of the Meters (Target Stability for example) is not possible because the submenu under meters disappears before I can select it.

This is a screenshot from the Meters submenu, just before it disappears:
![objects_meters](https://github.com/user-attachments/assets/2e539a8a-a3bd-4fec-91fe-68c1f120a1d4)

Logfiles don't seem relevant (the game doesn't crash).

Expected Result
---------------
When the submenu opens, then it stays open until I move my mouse out of the boundaries of the submenu. This would allow me to select any of the Meters from the submenu (I was looking for Target Stability and Target Influence when I encountered the bug).

Steps to reproduce
------------------
Just start the game and try to change the Columns in the Objects menu to one of the Meters. Notice that the submenu disappears immediately (instead of staying open long enough to select one of the Meters.

**Comment by geoffthemedio** [comment]
Possibly fixed in #5026

**Comment by petervdmeer** [comment]
#5026 indeed seems to fix the issue.

**Comment by o01eg** [comment]
@geoffthemedio Can we extract fix to separate small PR so we can fix it in upcoming release?
