### ISSUE TITLE
Build fail - Empire/Empire.cpp - Linux

### ISSUE THREAD

**Issue by dbenage-cx** [freeorion/freeorion#511]
4.4.3-300.fc23.x86_64 GNU/Linux (Fedora)

Assuming related to new CommonParams (sorry for format, github errored on log upload)

../freeorion/build> make -j3
[  0%] Building CXX object parse/CMakeFiles/freeorionparse.dir/EncyclopediaParser.cpp.o
Writing file: util/Version.cpp
Building v0.4.5+ build 2016-03-06.9bbf680
[ 16%] Built target GiGi
[ 16%] Built target freeorionversion
[ 17%] Built target GiGiSDL
[ 17%] Building CXX object parse/CMakeFiles/freeorionparse.dir/FieldsParser.cpp.o
Scanning dependencies of target freeorioncommon
[ 17%] Building CXX object CMakeFiles/freeorioncommon.dir/Empire/Empire.cpp.o
In file included from ../freeorion/Empire/ResourcePool.h:9:0,
                 from ../freeorion/Empire/Empire.h:5,
                 from ../freeorion/Empire/Empire.cpp:1:
../freeorion/Empire/../universe/ShipDesign.h: In member function ‘void PartType::serialize(Archive&, unsigned int)’:
../freeorion/Empire/../universe/ShipDesign.h:682:35: error: ‘production_meter_consumption’ was not declared in this scope
         & BOOST_SERIALIZATION_NVP(production_meter_consumption)
                                   ^
../freeorion/Empire/../universe/ShipDesign.h:683:35: error: ‘production_special_consumption’ was not declared in this scope
         & BOOST_SERIALIZATION_NVP(production_special_consumption);
                                   ^
../freeorion/Empire/../universe/ShipDesign.h: In member function ‘void HullType::serialize(Archive&, unsigned int)’:
../freeorion/Empire/../universe/ShipDesign.h:703:35: error: ‘production_meter_consumption’ was not declared in this scope
         & BOOST_SERIALIZATION_NVP(production_meter_consumption)
                                   ^
../freeorion/Empire/../universe/ShipDesign.h:704:35: error: ‘production_special_consumption’ was not declared in this scope
         & BOOST_SERIALIZATION_NVP(production_special_consumption);

**Comment by geoffthemedio** [comment]
should be fixed

**Comment by Vezzra** [comment]
Had those errors on OSX too, fix works.
