### ISSUE TITLE
Small UI "bug" (or misbehavior)

### ISSUE THREAD

**Issue by cpeosphoros** [freeorion/freeorion#513]
I'm playing in a Linux Mint box, with FO compiled from trunk 2 days ago.

The thing is, when I close the Production UI by hitting "ESC" the SitRep window resets to the first topic. When closing it by clicking the cog icon in the top of the screen the SitRep doesn't change its state (which I think is the desirable behavior).

---

All contributions are released under GPL or LGPL v2 or later, or under appropriate Creative Commons licence, consistent with project guidelines.

**Comment by Vezzra** [comment]
Can you specify the exact build (or any other build with which you can reproduce the issue)?

**Comment by cpeosphoros** [comment]
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.

**Comment by Vezzra** [comment]
Confirmed on OSX (build a0f6702ad9e22edcda7ad69d7d9509d6511be8e5).
