### ISSUE TITLE
Ship parts and predefined ship designs missing

### ISSUE THREAD

**Issue by Vezzra** [freeorion/freeorion#515]
Commit 56ceb121e324eb7306aed793b0f479c522b9c45c seems to have introduced an issue that affects parsing of ship parts. When you launch a default quickstart game, lots of ship parts are missing, as do all the predefined ship designs that depend on them (as expected). However, _all_ the starting fleets/ships are there, even those which use ship parts that seem to be missing.

No error messages in the log files though.

**Comment by geoffthemedio** [comment]
I'm wondering if the recent splitting of scripts into many files has affected parse error reporting somehow.. But possibly not; all the content is listed in the pedia, but is apparently being treated as not producible by the UI.

**Comment by dbenage-cx** [comment]
Adding an effectsgroup to the affected entries reintroduces them into the game.

**Comment by geoffthemedio** [comment]
I think I know the problem... the CommonParams constructor isn't always being called, so it passes default initialized common parameters, which are not producible.

Edit: probably fixed...

**Comment by dbenage-cx** [comment]
good here

**Comment by Vezzra** [comment]
> I'm wondering if the recent splitting of scripts into many files has affected parse error reporting somehow..

Nope, just ran a test, parse errors still show up in the log.

**Comment by geoffthemedio** [comment]
Didn't think it stopped all error messages, but just some.

**Comment by Vezzra** [comment]
Hm, if that's the case, it will be hard to track down.

**Comment by geoffthemedio** [comment]
indeed. probably not the case, though.
