### ISSUE TITLE
Research UI not remebering "Display" window position and settings between game sessions

### ISSUE THREAD

**Issue by cpeosphoros** [freeorion/freeorion#529]
Build from latest git pull, but it has been happening for quite a time, both on Windows 10 and now on Linux Mint.

When exiting the game and coming back again, Research UI's "Display" window gets reset to original settings. Just refer to the print screens.

Pre save:
![pre save](https://cloud.githubusercontent.com/assets/748982/13864857/02b812ee-ec84-11e5-9830-a6ac52a476c6.png)

Post save:
![post save](https://cloud.githubusercontent.com/assets/748982/13864858/049a0b8a-ec84-11e5-9dd1-10e0313f48c8.png)

**Comment by dbenage-cx** [comment]
Attempted to look into this.  The window options are saved and loaded but being reset after/during game launch.

e.g. TechTreeControls resets during the second(recursive) pass through [SetMinSize()](https://github.com/freeorion/freeorion/blob/master/UI/TechTreeWnd.cpp#L373)

Edit: And suddenly I can no longer reproduce :/

**Comment by dbenage-cx** [comment]
@cpeosphoros are you still able to reproduce?

**Comment by Vezzra** [comment]
@cpeosphoros & @dbenage-cx, any status update on this issue? Can any of you reproduce this, any hope of fixing this, or shall we just close this issue for the time being?

**Comment by dbenage-cx** [comment]
resolved here after c86b157

**Comment by cpeosphoros** [comment]
Not happening anymore

**Comment by Vezzra** [comment]
Good :smiley:
