### ISSUE TITLE
Fatal exceptions when loading old saves not crashing FO

### ISSUE THREAD

**Issue by cpeosphoros** [freeorion/freeorion#534]
I just did a "git pull", recompiled, etc.

When trying to load a recent save from my latest build, hoping it would still work, it didn't (as expected, it happens most of the time.)

What didn't happen was the expected FO crash.

The client UI's Messages window says:

```
Creating AI clients
Loading
```

And stays there forever.

The terminal from which I launched FO says:

```
$ ./freeorion
FreeOrion server waiting for network events
main() caught exception(std::runtime_error): Invalid empire ID specified for order.
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::lock_error> >'
  what():  boost: mutex lock failed in pthread_mutex_lock: Invalid argument
main() caught exception(std::runtime_error): Invalid empire ID specified for order.
main() caught exception(std::runtime_error): Invalid empire ID specified for order.
main() caught exception(std::runtime_error): Invalid empire ID specified for order.
```

And also stays there forever.

Shouldn't those exceptions just crash everything and throw me back to the terminal prompt?

Possibly related to: https://github.com/freeorion/freeorion/issues/524

Comment from Geoff on the forum post:

> It already happens in some cases, that if the server crashes, the client notices and aborts back to the intro screen. Sometimes the servers ends up hung waiting for some message that will never come, though, leading to this situation. It would be good to add some periodic ping messages between clients and server, to verify everything's still connected, but that hasn't been implemented.

---

All contributions are released under GPL or LGPL v2 or later, or under appropriate Creative Commons licence, consistent with project guidelines.

**Comment by Vezzra** [comment]
Ok, I boldly assume that #642 fixed this issue and therefore close it. Should it turn out that it isn't fixed, please report and we can reopen.
