### ISSUE TITLE
Monstrous weapons need updating

### ISSUE THREAD

**Issue by cpeosphoros** [freeorion/freeorion#536]
Refer to: http://www.freeorion.org/forum/viewtopic.php?f=15&t=10006&view=unread&sid=96ccf93875079e58510e2de75d3978b7#unread

MatGB said:

> since we changed the refinement system, multiple monsters got downgraded in some ways unless owned, where they regularly got a power increase, we need to create monstrous weapons for the various guardians and wondering monsters so that they can be properly balanced (plus, you get eaten by Kraken, not shot by lasers)

Unnamed said:

> I would like to do that. I noticed that most monsters have just one weapon, but I think it will be better to use multiple weapons as it will be slightly more effective against fighters.
> I allready made graphics for krill swarms and kraken. For the other monsters I will create graphics, too.
> Should I make icons for the monstrous weapons as well?

Geoff the Medio said:

> Yes.
> 
> Also, Krill Swam might be a good case to give a monster a special fighter bay part that has very high capacity, but very low damage, and remove the direct fire weapons. The swarm would then fight by launching a swarm of fighters, which seems suitable for its name.

**Comment by Vezzra** [comment]
I'm a bit unsure, but hasn't this already been taken care of? I _think_ I recall that some commits with new monster weapons (scritping and graphics) have gone in... but maybe that was only a start...?

Anyone?

**Comment by MatGB** [comment]
@V-ktor did some excellent work on it, I'm doing some balancing tweaks so while it's nearly finished it's not fully complete yet (one of the things added was different hulls for the different guardians, so you can script them to have better guns, etc, which I've done for the Warden and the Sentinel but not yet the others).

Plus, when Fighters are ready to go in then the Krill Swarms need to have the correct parts uncommented and the stopgaps removed.

**Comment by Vezzra** [comment]
> Plus, when Fighters are ready to go in then the Krill Swarms need to have the correct parts uncommented and the stopgaps removed.

Ok, I see. That means this issue can't be finished for 0.4.6, as fighters/carriers have been postponed. Because of that I will change the milestone to post 0.4.6 (but you can still put in for 0.4.6 what actually can be finished of course).

**Comment by l29ah** [comment]
Isn't it done already?

**Comment by MatGB** [comment]
There are probably some tweaks that ought to happen for some of the critters but I did essentially forget to close this one when we merged Fighters and sorted the Krill out, so basically, yes, at some point they'll get another pass, thanks for the reminder.
