### ISSUE TITLE
Guardian hulls need sensor parts

### ISSUE THREAD

**Issue by cpeosphoros** [freeorion/freeorion#537]
Refer to: http://www.freeorion.org/forum/viewtopic.php?f=15&t=10006&view=unread&sid=96ccf93875079e58510e2de75d3978b7#unread

MatGB said:

> Stealthed scoutships should be able to sneak relatively easily passed Sentries and Maintenance ships, but not Wardens, all currently get the same detection (based on vision range for unowned stuff). I recently set it to 50, but ideally it should start at 10 and go up for different things, so individual parts are needed.

**Comment by Vezzra** [comment]
Implemented by #650.
