### ISSUE TITLE
Orbital Drydocks need to be toned down

### ISSUE THREAD

**Issue by cpeosphoros** [freeorion/freeorion#539]
Refer to: http://www.freeorion.org/forum/viewtopic.php?f=15&t=10006&view=unread&sid=96ccf93875079e58510e2de75d3978b7#unread

MatGB said:

> Exact details to be decided but they definitely shouldn't work on the turn you conquer the planet they're on (perhaps a Happiness threshold), and probably ought to require a ship spend a turn there stationary not simply turn up. They also need to lose the Infrastructure penalty.

dbenage-cx said:

> Would like to tackle this.
> 
> My proposal is to repair the ship a percentage of its current structure each turn.
> The percentage would be adjusted based on the happiness of the planet (which has a lower threshold within the scope). e.g.:
> `SetStructure value = min(Target.MaxStructure, Value * (1 + ((Source.Planet.Happiness / 20.0) * 0.25)))`
> Increases the ships structure by 25% if the planet has 20 happiness. Higher/lower happiness adjusts the rate of repair.
> 
> Within scope, set a minimum of 5 happiness:
> `(Source.Planet.Happiness >= 5)`

MatGB said:

> Hmm, thing is, we still want drydocks to be the most powerful repair, but we want them at strategic points and ideally require you to withdraw ships to use.
> 
> My main balance problem with them is they complete a full repair immediately you arrive and they repair immediately on conquest, both of which are too much. I want to tone down fleet repair/damage control techs to be fairly low repair per turn, but drydocks should, if they work, repair in a turn or two, just not immediately and on conquest, make sense?
> 
> Having said that, I do like the basic idea that happier planets will repair stuff faster, but the basic repair rate needs to be higher, probably 50% if at 20 (given that it'll take time to get there, etc). And it'll need sitreps distinguishing between partial repair and full repair in some way.
> 
> It's partially as the idea is they're going to be increased in cost quite a lot at some point, but only when the AI team feels they'll be able to improve the AI production planning so they're not wasting points building them anywhere, if we nerf them too much it's a) annoying to players and b) makes the cost increase less justified.

**Comment by dbenage-cx** [comment]
Adjusted to hopefully be more inline with MatGB's vision.

Gave a minimum repair rate of +5, mainly to help repair nearly destroyed and small ships faster.
On a planet with 5 happiness, the repair rate is +20% of the current structure.
For 25 happiness, +100%

The idea was for large ships with a lot of damage to take a long time to repair on unhappy worlds.

While I like the happiness scale, I think it probably needs to be withdrawn for a target repair rate of 1-2 turns.  A ship with 21 max structure and 3 current structure will take 4 turns on a planet with 25 happiness.

**Comment by Vezzra** [comment]
Please, guys, use the forum for the more detailed discussions (especially if there is already a relevant discussion going on on the forums, so discussions don't get scattered over several completely separate platforms like the forum and github).

I've opened a dedicated thread for the Orbital Drydock item, please continue the discussion there:

http://www.freeorion.org/forum/viewtopic.php?f=15&t=10007

@dbenage-cx: I've copied your last comment and posted it in that thread.

**Comment by Vezzra** [comment]
Implemented by #549
