### ISSUE TITLE
Allowing expansion shipyards to be buildable if prereq building is enqueued

### ISSUE THREAD

**Issue by cpeosphoros** [freeorion/freeorion#545]
Refer to: http://www.freeorion.org/forum/viewtopic.php?f=15&t=10006&view=unread&sid=96ccf93875079e58510e2de75d3978b7#unread

MatGB said:

> As for me, I'm currently working on:
> This was basically done but not tested before the recent changes to the Default folder strucutre, as I need to test it further anyway I now need to split the work up, not a major problem but a delay

**Comment by Vezzra** [comment]
Same question as in #547 & #546...

**Comment by MatGB** [comment]
I'd like it in, the work is done but needs splitting up into the new directories, plus it might need some AI tweaks (not much, at a guess).

**Comment by Vezzra** [comment]
Ok, milestone set to 0.4.6.

**Comment by MatGB** [comment]
Done with [9e062b7](https://github.com/freeorion/freeorion/commit/9e062b71055a8335ae8a1b490a4594f3bd8321e7)
