### ISSUE TITLE
Star systems sometimes too far apart

### ISSUE THREAD

**Issue by Vezzra** [freeorion/freeorion#563]
Reportedly, with certain settings (mostly spiral or cluster layouts), excessively long starlanes get generated, which surpass the max starlane length limit by far. This can cause issues with the Experimentors, as well as other game mechanics/elements which are balanced with a certain starlane length limit in mind.

EDIT: This is caused by star systems which are placed too far away from any other system during universe generation, which is what needs to be fixed to prevent the excessively long starlanes /EDIT

http://www.freeorion.org/forum/viewtopic.php?p=83137#p83137

**Comment by geoffthemedio** [comment]
I don't consider this a bug... The limit is intentionally not enforced if it would disconnect a system from the rest of the galaxy, and sometimes a long lane will be needed.

**Comment by Vezzra** [comment]
Yes, I know. The issue is not that the limit isn't _strictly_ enforced, and that you can get the occasional extra long starlane. The problem I see is that apparantly sometimes these extra long starlanes can get really _excessively_ long, like twice the max length limit or even more.

I assumed that's not within the tolerances you had in mind when not enforcing the limit in the starlane generation code (correct me if I'm wrong), which is why I consider this an issue that should be addressed. I don't know how to classify this other than as a bug... we can, of course, introduce some kind of label for things which are issues we want to address, but are not bugs in the strict sense of the word - any ideas?

**Comment by geoffthemedio** [comment]
I didn't have any particular tolerances in mind... Sometimes a lane is needed.

This might be better described as an issue with the system location generation, rather than the lane itself being too long, as the latter in a consequence of the former.

**Comment by MatGB** [comment]
> This might be better described as an issue with the system location generation,

Agreed, but it is still an issue—I've commented on similar before in Clusters where it's possible to have a system or cluster so far away there's a stupidly restrictive chokepoint that can create very unfun games, extremely long starlanes are part of that problem

**Comment by Vezzra** [comment]
> This might be better described as an issue with the system location generation

Yep, you're right of course. Edited the issue title and OP accordingly.

**Comment by Vezzra** [comment]
Fixed by #651.
