### ISSUE TITLE
Autosaving at end of turn

### ISSUE THREAD

**Issue by cpeosphoros** [freeorion/freeorion#572]
Could an option be given that autosaving would occur at the end of a turn, instead or in addition of its beginning?

Mild dislexy sometimes makes me mistakenly hit end-turn instead of production, with a lot of orders already issued, and late in the game having to reload an autosave at the start of the turn and reissueing everything may be a pain.

**Comment by geoffthemedio** [comment]
@LGM-Doyle You might consider this since you've been working on related features: https://github.com/freeorion/freeorion/pull/1670

**Comment by Vezzra** [comment]
Implemented by #1696.
