### ISSUE TITLE
Option to switch off experimenters outpost

### ISSUE THREAD

**Issue by alexsl** [freeorion/freeorion#581]
Please add an option to switch off experimenters outpost. 
Maybe some players like to play with this outpost, but not all. It generate hordes of monsters which destroying my colonies. This is not fun playing for me. 
Thank you.

**Comment by tkinias** [comment]
I’d second that.  For me, the experimenters totally ruin the game – I just quit now when I see the first Black Kraken.

**Comment by vincele** [comment]
Maybe keep them in sync with total AI-strength, so that they scale with the player wanted difficulty setting

**Comment by geoffthemedio** [comment]
I think this is implemented with https://github.com/freeorion/freeorion/commit/346f3f0430450230b0dbde5f85a835d1871619b2
