### ISSUE TITLE
Show system totals for Shields, Defense and Supply

### ISSUE THREAD

**Issue by cpeosphoros** [freeorion/freeorion#596]
Right up at a system's panel, where it's shown the Total Industry and Research for that system, I suggest that it should also be shown the total Shields and Defense values, along with the best planet's Supply value in that system.

Also, those values should be also displayed for systems not owned by the player.

**Comment by dbenage-cx** [comment]
Because it took me a minute to understand:
![system_summary](https://cloud.githubusercontent.com/assets/17205519/14335380/4933b092-fc20-11e5-8846-243e243f0c6c.png)

**Comment by geoffthemedio** [comment]
Shields and defense don't make much sense to show, particularly for not-the-human-player systems, as if this is done, it would become very unclear what is meant if there are multiple empires with planets in the same system.

**Comment by cpeosphoros** [comment]
> Shields and defense don't make much sense to show, particularly for not-the-human-player systems, as if this is done, it would become very unclear what is meant if there are multiple empires with planets in the same system.

They do make sense, if you are calculating fleet strength to invade that system. If the many empires involved don't include the human-player empire, then they make as much sense as any other system, as the invading fleet will have to deal with all planets at the same time.

As for multi-empire systems including the human-player, I think they are not that common, and also very transient when they do happen. Being a limit case, I think they merit an exception treatment, which can be either just sum all them up - being treated as any other system - or just sum up the human values, or just ignore them and show no values in those specific systems, whatever is easier to code.

**Comment by MatGB** [comment]
Agree, 95%+ of systems will be one empire only most of the game and if there's a partial change of hands it indicates a full change of hands is happening very soon.

On the other hand right at this moment I have to look at a fleet of ships then count up the values for each planet in system to work out if I have enough guns to take their shields down before they kill me, and that's a calculation most players are going to have to make 100s of times per game. This is a really good idea and I'm amazed I didn't think to ask for it years ago.

**Comment by geoffthemedio** [comment]
That 95% is partly because there's presently no functional diplomacy system. In future it will probably be more of an issue...

**Comment by Vezzra** [comment]
> That 95% is partly because there's presently no functional diplomacy system. In future it will probably be more of an issue...

Even in that case it could still be very helpful if totals for planetary shields and defences are shown at least for systems where all colonies belong to the same (or allied) empires.
