### ISSUE TITLE
Full screen client prevents screensaver to activate

### ISSUE THREAD

**Issue by cpeosphoros** [freeorion/freeorion#613]
Built from 228a5e, but already present for a while.

When the client is set to full screen, Linux Mint screensaver will not activate, even if the game is minimized.

**Comment by geoffthemedio** [comment]
Sounds like a issue better filed with with Linux Mint maintainers...

**Comment by MatGB** [comment]
It does the same on Kubuntu, I had assumed it was meant to, never thought to check

**Comment by adrianbroher** [comment]
I don't see why the screensaver should kick in for a game.

For a workaround see the SDL 2 FAQ entry: [Why does SDL disable my screensaver by default?](https://wiki.libsdl.org/FAQUsingSDL#Why_does_SDL_disable_my_screensaver_by_default.3F)

Voting for a WONTFIX.

**Comment by cpeosphoros** [comment]
> I don't see why the screensaver should kick in for a game.

It should, IMHO, if the game is minimized. But I have no problems with WONTFIX, it's a very minor nuisance, that can be worked around.

**Comment by adrianbroher** [comment]
I guess that checking for the [SDL_WindowEventID](https://wiki.libsdl.org/SDL_WindowEventID)s  values `SDL_WINDOWEVENT_MINIMIZED`, `SDL_WINDOWEVENT_MAXIMIZED` and  `SDL_WINDOWEVENT_RESTORED` and either calling [SDL_DisableScreenSaver](https://wiki.libsdl.org/SDL_DisableScreenSaver) or [SDL_EnableScreenSaver](https://wiki.libsdl.org/SDL_EnableScreenSaver) should should enable the behaviour that @cpeosphoros  is asking for.

**Comment by Vezzra** [comment]
Having the screen saver kick in only when the game is minimized sounds reasonable.

**Comment by l29ah** [comment]
Same in Gentoo even if it is windowed and in the main menu.

**Comment by l29ah** [comment]
Quick hack to stop freeorion from messing with a screen saver: https://dump.bitcheese.net/files/kudylib/0001-stop-disabling-xscreensaver.patch

**Comment by Vezzra** [comment]
Any status updates on this? Shall we close this as wontfix, keep it open in case someone feels like addressing this at some distant point in the future, are there concrete plans for a fix (e.g. incorporating the patch @l29ah provided)?

**Comment by adrianbroher** [comment]
> Any status updates on this?

No progress so far.  Didn't invest any time into this issue.

> Shall we close this as wontfix, keep it open in case someone feels like addressing this at some distant point in the future, are there concrete plans for a fix (e.g. incorporating the patch @l29ah provided)?

I would keep it open until someone feels like providing a complete patch, which includes en-/disabling the screensaver when the game has lost/regained focus.  The patch created by @l29ah doesn't satisfy this.

**Comment by Vezzra** [comment]
Ok, thanks for the update!

**Comment by l29ah** [comment]
I wonder if it will work when i'm on another workspace.

**Comment by Voker57** [comment]
> I don't see why the screensaver should kick in for a game.

I don't see why it shouldn't, care to elaborate?
Maybe for a game that doesn't use keyboard or mouse, but otherwise it's not game's business IMO.
At least make it configurable

**Comment by Vezzra** [comment]
@Voker57, the issue has actually been addressed and closed as resolved, so the screensavers on the affected platforms should work now.

**Comment by adrianbroher** [comment]
> I don't see why it shouldn't, care to elaborate?

I consider games to be the class of applications that has the highest continuous response/feedback rate.  When you're playing a game you're continuously interacting with it until the end of the game session.

**Comment by Voker57** [comment]
@Vezzra I see that screensavers are still disabled with window not minimized, that's not desirable for me. Also not sure if window is considered minimized when it's on different desktop.

**Comment by Vezzra** [comment]
I don't understand - this issue has been about FO *preventing* the screensaver from activating when in full screen mode. That has been fixed if I understand correctly.

Inhowfar is screensavers being *enabled* when the window is not minimized a problem, and what has that to do with this particular issue here anyway...?

**Comment by Voker57** [comment]
@Vezzra sorry, I meant "disabled". Edited my comment.

**Comment by Vezzra** [comment]
Ah, ok, that makes more sense.

**Comment by MatGB** [comment]
@adrianbroher 
> I consider games to be the class of applications that has the highest continuous response/feedback rate. When you're playing a game you're continuously interacting with it until the end of the game session.

I'm don't, at all, for turn based games I'm constantly switching between the game app and other things, I don't think I've ever played FO without switching to other tasks repeatedly: there are some games I just play, but they won't be turn based or roguelikes.

**Comment by Voker57** [comment]
Issue is important for me, can't play without patching screensaver-disabler out.

**Comment by l29ah** [comment]
YEAH THIS SUCKS

**Comment by geoffthemedio** [comment]
@l29ah could you elaborate? What is the (new / reappearing) problem...?

**Comment by Voker57** [comment]
@geoffthemedio problem is freeorion prevents screensaver from activating when focused, with no option to disable this functionality.

**Comment by geoffthemedio** [comment]
I'd be fine with just always having the screensaver be active... Is the really a need to disable it? Presumably that can be configured in the OS anyway, per-program.

**Comment by Vezzra** [comment]
Sure, having the screensaver active just be active is a reasonable approach. However, if this is something we can address on our side, it needs to be done, and therefore a separate feature request issue should be opened.

**Comment by geoffthemedio** [comment]
@Voker57  @l29ah Try with that pull request?
