### ISSUE TITLE
Cumulative bug for Python AI Interface

### ISSUE THREAD

**Issue by Cjkjvfnby** [freeorion/freeorion#614]
This is cumulative bug for Python AI interface issues. This bugs are not critical and present in code for a long time. If someone want to fix them and this fix is not 'remove', think twice. Fixing code that is not used is waste of time. 
- [ ] `planet.meters` returns `freeOrionAIInterface.MeterTypeMeterMap` which is unusable:
  
  ```
  Chat Message to human: Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "f:\projects\FreeOrion\default\AI\freeorion_tools.py", line 18, in dict_from_map
  return {el.key(): el.data() for el in thismap}
  File "f:\projects\FreeOrion\default\AI\freeorion_tools.py", line 18, in <dictcomp>
  return {el.key(): el.data() for el in thismap}
  TypeError: No to_python (by-value) converter found for C++ type: class Meter
  ```
- [x] `planet.type` does not match `planet.originalType` -> `freeOrionAIInterface.planetType.swamp` != `freeOrionAIInterface.planetType.barren`.  Checked once on single planet.   `planet.originalType` is not used in AI code
- [ ] message text does not match enum variable:  Passing `meterType.maxCapacity` to `planet.initialMeterValue` produce next error:
  
  ```
  ValueError: UniverseObject::InitialMeterValue was passed a MeterType that this UniverseObject does not have: METER_MAX_CAPACITY 
  ```
  
  I expect that variable in message will have exactly same name as it have. In my case I try to check value of all 66 meters, it is not normal usecase.
- [ ] `planet.getMeter` is not used and duplicate behavior of `planet.currentMeterValue` and `planet.initialMeterValue`(unused) 
- [ ] ShipPartMeterMap' is returned by `ship.partMeters` and have only one method to access inner values: **iter**. which returns empty list.
- [ ] `planet.InitialOrbitalPosition`: No to_python (by-value) converter found for C++ type: class Radian
- [ ] `planet.OrbitalPeriod`: No to_python (by-value) converter found for C++ type: class Year
- [ ] `planet.RotationalPeriod`: No to_python (by-value) converter found for C++ type: class Day
- [ ] `sitrep.getTags`: Python argument types in None.None(sitrep) did not match C++ signature: None(class VarText {lvalue})
- [ ] `sitrep.typeString`: Python argument types in None.None(sitrep) did not match C++ signature: None(class VarText {lvalue}

**Comment by geoffthemedio** [comment]
planet.type would only be expected to be the same as planet.originalType if the type hasn't changed.

**Comment by Cjkjvfnby** [comment]
I don't think that AI have changed this planet type (at turn 4), I think that this were done by `universe generator` when adding capitals.

**Comment by geoffthemedio** [comment]
then it's not a python interface bug

**Comment by Vezzra** [comment]
But still a bug, if I understand the issue correctly. So, just to be sure: when the Python universe generation scripts change the type of the starting planet of an empire (to match the PE preference of the starting species), just the "current" type gets changed, but not the "original" type? That's not how it's intended to work...

**Comment by Vezzra** [comment]
Ok, investigated this and indeed, when setting the planet type of an empire homeworld to the preferred type of the starting species during universe generation, only the current type is set, but not the original type. Obviously we want the original type of an empire homeworld to be the preferred type of the starting species too, so I went ahead and fixed this: 0546c4804ff37468d57f3dcd0a11e2f2fbf91e33.

So the second item on the list above should now be fixed.

**Comment by MatGB** [comment]
Ah, good, that'll also stop terraform reversion turning up on homeworlds, which has been a minor annoyance for ages, good call.

**Comment by adrianbroher** [comment]
@Cjkjvfnby 
This bug is old, smells and is probably stale as hell.  Please give me a good reason to reopen it.

**Comment by Cjkjvfnby** [comment]
@adrianbroher,
Boost python interface is still smells. But this nonworking entries is very important and cannot be deleted, because it might be needed in next decades. 

Status of the issue will not stop me from updating description and adding comments. Let it be closed.

**Comment by adrianbroher** [comment]
@Cjkjvfnby If you need the OP content feel free to open a project.  But a long running issue is not the right place to track the refactoring. It only distracts other devs from small and concrete working packages.

**Comment by Vezzra** [comment]
Managing the items listed in the OP as separate cards in a project sounds like a very good idea to me. Especially since you can easily convert cards into issues. So, @Cjkjvfnby, I'd really recommend doing that...

**Comment by Cjkjvfnby** [comment]
>  If you need the OP content feel free to open a project.
What is `OP`?

> But a long running issue is not the right place to track the refactoring.

It is not refactoring.  This is dead entries in API, they are broken and unused.   

>  It only distracts other devs from small and concrete working packages.

I am ok with closing this issue.   

> Managing the items listed in the OP as separate cards in a project sounds like a very good idea to me. Especially since you can easily convert cards into issues. So, @Cjkjvfnby, I'd really recommend doing that...

Looks like I miss some github features.

I am not planning to work on something big right now, study take to much free time :(.  Lets stop this distraction.

**Comment by adrianbroher** [comment]
> What is OP?

Opening Post.
