### ISSUE TITLE
Unnecessary writes to config folder?

### ISSUE THREAD

**Issue by andresmrm** [freeorion/freeorion#618]
I just got an SSD disk so I'm trying to reduce unnecessary writes to it.
So I set "saves" folder to an extenal HDD (since I knew autosave would do many writes).
After that, Freeorion was still writing ~2MB/turn on my SSD (where my main system is).

Using `find -mmin -1` I saw some files (logs?) in `~/.local/share/freeorion` were changing every turn, and they have a few MB. So I linked that folder to a folder on `/tmp` (my /tmp stays on RAM). Even after that it was still writing ~2MB/turn.

Then I tried to start Freeorion with `HOME=<path to a folder on external HDD> ./freeorion`.
It started to write the log files to this new "fake home", but was still writing ~2MB/turn to the SSD.

The last file that was still changing in my true home folder was `.config/freeorion/config.xml`. It has only a few KB, so I didn't think it was the cause of the 2MB/turn. But I tried to transfer `.config/freeorion` to RAM (`/tmp`) and it worked. No more writes to my SSD every turn.

I see two _possible_ bugs there:
- Starting Freeorion with a modified $HOME var changed the path to the `.local` folder, but not to the config folder.
- I can't see why it's writing ~2MB/turn to the config folder, if there is no file that big there. Maybe the autosave is first been saved there and than moved to the right folder?

Well, maybe this is a specific problem that will only affect me... Anyway, it seemed a strange behavior, so I thought it would be better to report. =P

**Comment by dbenage-cx** [comment]
Hi @andresmrm, not a dev, but just a quick checklist:
- Assuming you do not have a `.config/freeorion/persistent_config.xml` file
- `$XDG_CONFIG_HOME` is set to your desired external directory, or is unset
- Temporarily rename or mv `.config/freeorion/config.xml`

**Comment by andresmrm** [comment]
> - Assuming you do not have a .config/freeorion/persistent_config.xml file

No.

> - $XDG_CONFIG_HOME is set to your desired external directory, or is unset

Good point! Changing this var Freeorion started using the `.config` in the "fake home". Thanks!

> - Temporarily rename or mv .config/freeorion/config.xml

Not sure about what do you mean with this point...

So the remaining question is: why is it writing about 2MB/turn in the config folder?

**Comment by Vezzra** [comment]
I've to admit I have no idea what's going on here... @andresmrm, I'm a bit confused: how can you see that 2MB get written to a certain folder without seeing which file(s) those 2MB get written to?

Leaving the milestone undecided for now, until we can determine if we're actually dealing with a bug here.

**Comment by andresmrm** [comment]
Using `iotop` I can see which process are writing to disks.
Than, using a [small script](https://gist.github.com/andresmrm/7a58b5efe9d7a008d974ad4604323dc0), I print the accumulated values and changes to `/sys/fs/ext4/<HD>/lifetime_write_kbytes`.
To make sure, this time I also checked `Total_LBAs_Written` with `smartctl`.

I tried to disable autosave to do the test, but it seems it was still writing to the config folder every turn. So maybe it's not related to the autosave process...

**Comment by Vezzra** [comment]
I'm afraid I'm a bit lost... can someone of our Linux folks take a look at this?

**Comment by dbenage-cx** [comment]
config.xml is updated pretty frequently, mostly for UI changes 
(e.g. [./watch_diff.sh](https://gist.github.com/dbenage-cx/4057d995ce0cd8ca0e1b7b676232c3e8) `$XDG_CONFIG_HOME/freeorion/config.xml`)

Are you seeing this traffic if you only click 'next turn'?

**Comment by andresmrm** [comment]
I used your script, @dbenage-cx. Even **only** clicking in 'next turn', sometimes the diff acused the contents of the file being duplicated or erased, but not every turn. Any way, there is something being written to HD every turn. Maybe the `config.xml` is been rewritten every turn, but most of the time `watch_diff.sh` can't catch it?

**Comment by matthoppe** [comment]
Run strace -e trace=open,write -p pid_of_freeorion ... I was seeing ~8039 bytes being written when changing back and forth from menus. It was opening and closing the file for each write too.

**Comment by andresmrm** [comment]
Tested with `strace`. Passing turn makes it write many lines. Not sure about how many bytes it says are written.
I noticed that just changing focus to/from Freeorion window makes `strace` print a line like this:

```
write(9, "2016-04-24 15:03:12.238217 [debu"..., 90) = 90
```

**Comment by andresmrm** [comment]
Starting game with `--log-level FATAL` avoids the writes on window change focus, but I'm still getting this output in `strace` each turn end:

```
open("/freeorion_build/../home/.local/share/freeorion/save/auto", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 16
open("/freeorion_build/../home/.config/freeorion/config.xml", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 16
write(16, ">\n          <left>-2147483648</l"..., 7790) = 7790
open("/freeorion_build/../home/.config/freeorion/config.xml", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 16
write(16, ">\n          <left>-2147483648</l"..., 7790) = 7790
open("/freeorion_build/../home/.config/freeorion/config.xml", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 16
write(16, ">\n          <left>-2147483648</l"..., 7790) = 7790
open("/freeorion_build/../home/.config/freeorion/config.xml", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 16
write(16, ">\n          <left>-2147483648</l"..., 7790) = 7790
open("/freeorion_build/../home/.config/freeorion/config.xml", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 16
write(16, ">\n          <left>-2147483648</l"..., 7790) = 7790
open("/freeorion_build/../home/.config/freeorion/config.xml", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 16
write(16, ">\n          <left>-2147483648</l"..., 7790) = 7790
open("/freeorion_build/../home/.config/freeorion/config.xml", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 16
write(16, ">\n          <left>-2147483648</l"..., 7790) = 7790
open("/freeorion_build/../home/.config/freeorion/config.xml", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 16
write(16, ">\n          <left>-2147483648</l"..., 7790) = 7790
open("/freeorion_build/../home/.config/freeorion/config.xml", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 16
write(16, ">\n          <left>-2147483648</l"..., 7790) = 7790
open("/freeorion_build/../home/.config/freeorion/config.xml", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 16
write(16, ">\n          <left>-2147483648</l"..., 7790) = 7790
open("/freeorion_build/../home/.config/freeorion/config.xml", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 16
write(16, ">\n          <left>-2147483648</l"..., 7790) = 7790
open("/freeorion_build/../home/.config/freeorion/config.xml", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 16
write(16, ">\n          <left>-2147483648</l"..., 7790) = 7790
open("/freeorion_build/../home/.config/freeorion/config.xml", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 16
write(16, ">\n          <left>-2147483648</l"..., 7790) = 7790
open("/freeorion_build/../home/.config/freeorion/config.xml", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 16
write(16, ">\n          <left>-2147483648</l"..., 7790) = 7790
open("/freeorion_build/../home/.config/freeorion/config.xml", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 16
write(16, ">\n          <left>-2147483648</l"..., 7790) = 7790
open("/freeorion_build/../home/.config/freeorion/config.xml", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 16
write(16, ">\n          <left>-2147483648</l"..., 7790) = 7790
```

**Comment by mmoderau** [comment]
Is it possible that window geometry and UI position is stored each turn?

**Comment by dbenage-cx** [comment]
Not just each turn, but generally on each change of the object.

If the 2MB is a total from normal gameplay each turn (not just clicking 'next'), I could see it as expected behavior.

I should have clarified the simple script was just to give a glimpse at content.  inotify-tools is likely a better option for this task, but may be a moot point ;)

FWIW: The only files in $XDG_CONFIG_HOME/freeorion that should be modified by the game is config.xml and AI/default/config.ini.  All other file writes should be in $XDG_DATA_HOME/freeorion (or a sub-directory of) by default.

**Comment by LGM-Doyle** [comment]
@andresmrm I've posted PR #639.  It should only write to the config file when something has changed.  If you want you could pull it and verify that it works.

**Comment by andresmrm** [comment]
Thanks, @LGM-Doyle! Just tested it and seems to work.
No more writes to disk when just passing turns and autosave is disabled.
And when autosave is enabled, `./watch_diff.sh` shows no changes to `config.xml` when just passing turns.
So, for me, feel free to close this issue.
