### ISSUE TITLE
FO spamming terminal window

### ISSUE THREAD

**Issue by cpeosphoros** [freeorion/freeorion#620]
In the terminal from which I launch FO, there are lots of messages like this:

`ImageBlockFactory param path: encyclopedia/planet_environments/pt_desert.png
ImageBlockFactory combined path: /home/chronos/git/freeorion.build/default/data/art/encyclopedia/planet_environments/pt_desert.png  exists?: 1
ImageBlockFactory param path: encyclopedia/EP_wheel.png
ImageBlockFactory combined path: /home/chronos/git/freeorion.build/default/data/art/encyclopedia/EP_wheel.png  exists?: 1
ImageBlockFactory param path: encyclopedia/planet_environments/pt_desert.png
ImageBlockFactory combined path: /home/chronos/git/freeorion.build/default/data/art/encyclopedia/planet_environments/pt_desert.png  exists?: 1
ImageBlockFactory param path: encyclopedia/EP_wheel.png
ImageBlockFactory combined path: /home/chronos/git/freeorion.build/default/data/art/encyclopedia/EP_wheel.png  exists?: 1
`

**Comment by geoffthemedio** [comment]
Why is this labelled as "Server" doing something?

**Comment by cpeosphoros** [comment]
Because I imagine it's "Server" which writes to the terminal window. If it's not, just we can just change the title.

**Comment by geoffthemedio** [comment]
It's not. (Unless you run freeoriond separately from the command line)

**Comment by cpeosphoros** [comment]
Edited.

**Comment by Vezzra** [comment]
Probably low priority, but still want to see that fixed if possible, so set milestone to 0.4.6.

**Comment by Vezzra** [comment]
Fixed by #624
