### ISSUE TITLE
Add Editable Save File Format Option

### ISSUE THREAD

**Issue by geoffthemedio** [freeorion/freeorion#622]
Recently someone asked in the forums how to edit save files, and in a reply it was noted that in v0.4.5, one could set the save file format to XML, to get a semi-human-editable save format.

In the latest builds, however, the non-binary-mode save is a readable-text header followed by compressed, and thus unreadable or editable, text.

It shouldn't be too difficult to add another option, for "uncompressed XML" saves, in which the main bulk of the gamestate is still semi-readable serialized text.

**Comment by adrianbroher** [comment]
It's complete an utter nonsense to introduce another option for something that should not be configurable in the first place.  Just save the files as xml, but compress the whole file with the standard algorithm when saving and uncompress when loading.  Also get rid of the binary save files options.  It's not platform transparent and therefor garbage.

**Comment by geoffthemedio** [comment]
The whole file being compressed means the whole file has or would have to be loaded before any info in it can be used. This creates a bunch of problems, most notably substantial delays when populating save file lists in the UI. I added an uncompressed header to the format in part to avoid that.

Binary saves might still be faster than loading and uncompressing the XML, and can likely work with less memory requirements. In order to handle the compressed XML, the whole compressed string and the whole uncompressed string need to be stored continguously in memory buffers. This could potentially cause problems when attempting to reserve that large of a memory block (~500 MB); at least it did before I reworked things to attempt to reserve enough space in the decompressed text buffer before doing the decompression filtering, and a particularly large save file might still have issues, due the the verbosity of tagged XML serialization.

**Comment by LGM-Doyle** [comment]
Is it possible to change from a save file to a save directory?

Each section of the save can be a separate compressed XML file.  
The simplest partition is a header file and an everything else file.  Other partitions might minimize the amount of data that needs to be loaded for different executables.  Perhaps header, current turn and historical to prevent loading historical data until the human client requests it.  Perhaps even break up current turn and historical into per-client save files to minimize client loading.

XML does allow file inclusion, so the header could just include all of the other stuff, if the XML parser is lazy enough to not expanded tags until requested.

Is  a directory with two compressed XML files header and everything else and way to have small file size, fast loading header information and transparent data?

**Comment by geoffthemedio** [comment]
Possible, yes, but I wouldn't do anything more complicated to deal with than a single save file.

**Comment by geoffthemedio** [comment]
https://github.com/freeorion/freeorion/pull/1427

**Comment by geoffthemedio** [comment]
I think this was more or less resolved with https://github.com/freeorion/freeorion/pull/1427
