### ISSUE TITLE
AI colonization logic needs improvements

### ISSUE THREAD

**Issue by Morlic-fo** [freeorion/freeorion#634]
The AI makes some seemingly weird decisions on which planets to colonize (see e.g. http://freeorion.org/forum/viewtopic.php?f=2&t=10053). 

Furthermore, the AI is very slow to get going. A more aggressive / greedy approach in the early game seems needed.

**Comment by Morlic-fo** [comment]
Related PRs:
#1007  -  should fix AI going for too small planets
#1008  -  fixes critical bug for Orbital colonization

Still needs more work.

**Comment by MatGB** [comment]
[AI-colony-plan.zip](https://github.com/freeorion/freeorion/files/641576/AI-colony-plan.zip)
[AI-colony-plan-sav.zip](https://github.com/freeorion/freeorion/files/641577/AI-colony-plan-sav.zip)
![screenshot_20161209_081849](https://cloud.githubusercontent.com/assets/11533206/21042451/3ab922c8-bde9-11e6-8e38-492436db1bee.png)
Noticed recently a strong reticence in using the initial colony ship, previous game and this one found at least one AI with it unused despite very local strong target, screenshot, log and savegame attached.

I've very rarely if ever regretted placing my initial colony on the first habitable planet I can find, having it sat there at turn 35 when there's a Good planet in the neighbouring system slows them down far too much.

**Comment by Morlic-fo** [comment]
> Noticed recently a strong reticence in using the initial colony ship, previous game and this one found at least one AI with it unused despite very local strong target, screenshot, log and savegame attached.

Was introduced by #1079.
Was fixed by #1313.

**Comment by Morlic-fo** [comment]
I think most critical bugs are resolved by now and the colonization pattern seems at least coherent.

* Bug that put outposts for resurrected species not in the empire:
87da6a4e48c49037dc3c1e9e74f569ca8694900c

* Wrong calculation of target population
ab25d21ff1e0c4d55f5ca0801165e8a3ced4cc7e
85776ff14885e93262fdf8e07e5154ab6c829a57
254947df56b28c2601616b0da11283227fa31be6

New specific problems should get their own issue.
