### ISSUE TITLE
AI fleet movement / pathfinding issues

### ISSUE THREAD

**Issue by Morlic-fo** [freeorion/freeorion#636]
~~1. The AI stops at every system on its path when moving fleets thus wasting a lot of valuable time.~~
2. The AI often makes bad decisions if the path is obstructed or threatened. Some easy-to-use framework to detect and then deal with these situations would be really nice to have.

**Comment by Morlic-fo** [comment]
> The AI stops at every system on its path when moving fleets thus wasting a lot of valuable time.

Possibly resolved by https://github.com/freeorion/freeorion/commit/853af0ea037ff01e0a63645984cebf0228f81a5a

**Comment by Dilvish-fo** [comment]
The path obstruction thing has also nagged me for a long while.  Although it would be *possible* for the AI to deal with this purely in python, my intent is to someday put up a PR which would enable both human and AI players to flag systems as dangerous (and have some be automatically designated as dangerous, such as if an armed aggressive enemy is visibly present) and then also make an alternate version of the boost pathing code, which would exclude all the flagged systems (except that the ultimate destination would still be included no matter what) from the network it uses to determine pathing.  

For the player UI I would propose having passive fleets use this "safe-move" pathing.  For the AI we might do the same or have a somewhat move complex decision for which pathing algorithm it would use, so it could use this pathing mode to have its warships go around Sentinels, for example, when it doesn't really want to take them on.

I had started on this a long while back but my first partial implementation had too many problems (and I think it was before we revamped blockades), I think I understand the problem much better now and I will probably start over mostly from scratch; I hope to get to it some time this year, perhaps in the next few months.

**Comment by LGM-Doyle** [comment]
I had this in mind when I made the changes to split the pathfinding code from the universe code.

For the UI I was considering a right-click context menu for systems in the MapWnd with the option "Avoid traveling through System".  Selecting that option would then not create paths through that system unless the player/AI directly selected that system as the endpoint in a path.  

I do not think that using the alternate pathing only for passive fleets  makes sense.  In the early game, many monsters are too challenging for your military fleets.  Being able to directly select the system as an endpoint and ignore the avoid instructions means that fleets of any type will only go to the avoided system intentionally, which allows military fleets to deal with the monsters.

Once a system is being avoided the context menu option would change to "Stop avoiding traveling through system".

The same pathfinder interface made available to the player via the UI, would also be available to the AI via the python interface.

**Comment by geoffthemedio** [comment]
> "Stop avoiding traveling through system".

Perhaps "Allow fleet pathing though system" ?

**Comment by Morlic-fo** [comment]
The remaining point was mostly addressed by #1772. For further issues, more specific issues should be opened.
