### ISSUE TITLE
Save files become inaccessible if renamed

### ISSUE THREAD

**Issue by Cjkjvfnby** [freeorion/freeorion#660]
Steps to reproduce:
- start game
- rename saves form `*.sav` to `xxx` or anything without .`sav` at the end
- try to load game

Observed result:
- there is no save game with this name
- file present in saves directory

Expected result:
- if `.sav` is absent it should be added before saving

```
Windows 7x64
v0.4.5+ [build 2016-05-10.2a6b7b4] MSVC 2013
```

**Comment by dbenage-cx** [comment]
PR addresses correctly appending the extension when saving

> rename saves form *.sav to xxx or anything without .sav at the end

Assuming these are renamed outside of the game, the observed result is expected.

**Comment by Vezzra** [comment]
Ok, thanks. Closing this issue.
