### ISSUE TITLE
Add documentation for "Update Old Design" in Design Window

### ISSUE THREAD

**Issue by LGM-Doyle** [freeorion/freeorion#671]
PRs #506 and #552 added the ability to persistently sort designs in the design window and to update old designs.

These new features need documentation in the UI section of the pedia and also tooltips explaining the usage.

See the discussion in [http://freeorion.org/forum/viewtopic.php?f=25&t=10090&sid=d961978af4ed03a5c22e0d7bcad1a375](url) for details.

**Comment by Vezzra** [comment]
Has been addressed by #690, closing.
