### ISSUE TITLE
Pointer hidden and windows flicker on Win10/Intel Core i5-2430M

### ISSUE THREAD

**Issue by MatGB** [freeorion/freeorion#676]
As detailed here:
http://www.freeorion.org/forum/viewtopic.php?f=25&t=9768

Stepdaughters Win laptop is:
Acer Aspire 5750 15.6 inch Laptop (Intel Core i5-2430M Processor, RAM 8GB, HDD 500GB, DVD-Super Multi DL Drive, Windows 7 Home Premium 64-bit) 
https://www.amazon.co.uk/Acer-i5-2430M-Processor-DVD-Super-Windows/dp/B005WOELCM

that's been upgraded to Win10. Still an issue in FreeOrion_2016-05-19.4781a80_Test_Win32_Setup

**Comment by MatGB** [comment]
Haven't tagged this as blocking release, but given there was another report it would be good to look into it.

**Comment by adrianbroher** [comment]
@MatGB quote from the thread:

> Getting into the game proper and the entire display is flickering, especially the menu at the top, and the mouse isn't visible making UI elements rather problematic...
> When running quickstart, the mouse is visible while the screen is black and it's running the "generating" effects in messages, but when the map actually appears the mouse disappears.

This generally sounds like the depth buffer check is still enable/read.

Would you identify the 'flickering' as [Z-Fighting](https://www.youtube.com/watch?v=9AcCrF_nX-I)?

**Comment by MatGB** [comment]
Possibly. Unfortunately the laptop on which I was getting this problem has now died and not been repaired yet, so am unable to test any potential fixes, it doesn't happen on my Linux box or on my newer laptop. 

But the symptoms described in the vid and the explanation would make the most sense given the way the problem wasn't always there.

**Comment by Vezzra** [comment]
IIRC I observed that issue (slight flickering, especially of the top bar) on my Linux box. Haven't run FO there for some time, need to check if I remember correctly and if it still happens. If yes, I should be able to test fixes.

**Comment by adrianbroher** [comment]
@Vezzra could you check out if the patch proposed fixes the issue?

**Comment by Vezzra** [comment]
Nope, doesn't make a difference. Get the same kind/amount of flickering with and without the patch (observation based on comparison between builds of 313f92f9dec464a21a9137b7d3df8258d42319cd and dabf4d42bea5e80b7294da033efc9affb7e2138d).

**Comment by adrianbroher** [comment]
@Vezzra 
Can you create a short screencast showing the problem (Quicktime player should be able to do that)?

**Comment by adrianbroher** [comment]
A second attempt to fix this issue.

**Comment by Vezzra** [comment]
Second fix also didn't change anything.

Regarding screencast: I had to do that by filming my monitor, as running FO and trying to capture the screen brought the ancient box my Linux system runs on to its knees. The result should be sufficient, though.

Here is the video file: [Flickering.m4v.zip](https://github.com/freeorion/freeorion/files/453883/Flickering.m4v.zip)

**Comment by adrianbroher** [comment]
This doesn't look like a depth issue so it's probably a different error than @MatGB experiences.

@Vezzra Do you happen to run a desktop were the taskbar is placed on the upper edge of the desktop and does that taskbar dimensions match the size of the flickering area?

**Comment by Vezzra** [comment]
@adrianbroher : If by "task bar" you mean Ubuntu Unity's "dash", no (I'm not on KDE or Gnome desktop). That is on the left edge of my desktop. At the top is just the menu bar, but that does not overlap with the flickering part of the FO window. However, the height of the flickering area seems to be roughly the same as the height of the menu bar above.

**Comment by geoffthemedio** [comment]
https://github.com/freeorion/freeorion/pull/1500 is just speculatively intended to help with the mouse cursor disappearing issue.

**Comment by Vezzra** [comment]
We got a [report on the forum](http://freeorion.org/forum/viewtopic.php?p=90873#p90873) that the issue doesn't turn up anymore with recent test builds.

Can anyone else who had that problem confirm this? @MatGB?

**Comment by zllj** [comment]
Still have the issue on Windows 7 64bit SP1 with intel 2000. Cursor hidden.

**Comment by geoffthemedio** [comment]
@zllj please specify what FreeOrion version you tested, otherwise the report is of little use.

**Comment by zllj** [comment]
0.4.7.1 stable
Hidden cursor and flickering graphics

**Comment by zllj** [comment]
Sorry, it's my bad, I confirm the most recent test build works fine here 2018-02-12.c8e8372

**Comment by adrianbroher** [comment]
Closing this as fixed according to reports with (build 2017-11-20.e6848d8) and later. In case this issue reappears please open a new issue.
