### ISSUE TITLE
Mine damage in system with no mines

### ISSUE THREAD

**Issue by Piwoslaw** [freeorion/freeorion#703]
Build 2016-05-30.fc49608
On turn 68 an AI troopship wandered to one of my planets (Horst α) and was destroyed. SitRep reported that the enemy troopship was destroyed by mines, but I had not researched ANY defense techs yet (no Planetary Defense, Mines, etc., only Force Filed Harmonics), and the only ship in the system was an outpost ship. The system had no hidden natives, nor Fortress special.

The same situation happened again in a different system a few turns later.

Attached are screenshot for beginning of turn 68 and savegame of turn 69 (save of turn 68 not available).

![mines](https://cloud.githubusercontent.com/assets/19825312/15907672/56776ba2-2dbe-11e6-8196-3a039e645c2a.jpg)
[save-20160607_093444.zip](https://github.com/freeorion/freeorion/files/305530/save-20160607_093444.zip)

**Comment by dbenage-cx** [comment]
@Piwoslaw Ty, testing a potential fix (alot of possibilities to verify)

**Comment by Piwoslaw** [comment]
Same problem, this time a newer build - 2016-06-06.4187172

AI scout arrived at Tombstone on Turn 35 and lost 3 hitpoints to mines, on Turn 36 was destroyed by them.

The only defense I researched are Force Field Harmonics and Planetary Bunker Complex, no Planetary Defense nor Mines researched yet. No other ships in the system. No Fortress nor hidden natives visible.

![mines2](https://cloud.githubusercontent.com/assets/19825312/15960875/356e9e40-2f02-11e6-9305-5845d27e528c.jpg)
[save-20160610_114011.zip](https://github.com/freeorion/freeorion/files/308769/save-20160610_114011.zip)

**Comment by Vezzra** [comment]
@Piwoslaw: The fix proposed by @dbenage-cx addresses a bug which causes the mine damage of an owned Fortress special to be applied to all empire owned systems. Which means, if that's the bug that causes what you've observed in your games, you must have captured or colonized a planet with the Fortress special (anywhere, not in the system where the enemy ships got damaged) - can you confirm that?

**Comment by dbenage-cx** [comment]
@Vezzra Per the second savegame, one is owned at Hamal III.  The first has one at Lystena I (not in screenshot).

**Comment by Piwoslaw** [comment]
Hi All,
Sorry for the delay. As @dbenage-cx wrote - I confirm that in both games I already had a planet with a Fortress in my empire, in a different system, captured prior to the issue.

**Comment by Vezzra** [comment]
Ok, that means #706 is indeed a fix for this issue. Thanks for reporting back!
