### ISSUE TITLE
Spurious bug (was: Spontaneous revelation of whole map)

### ISSUE THREAD

**Issue by tkinias** [freeorion/freeorion#704]
I just witnessed the oddest bug I’ve ever seen in Freeorion:  On the turn 15–16 turn change of a new game, the entire map was revealed to me, and my sitrep was full of the ship movements of empires I had yet to encounter.  I’m attaching a screencap of the game at that point.

![screenshot_2016-06-08_21-07-05](https://cloud.githubusercontent.com/assets/17457465/15916170/d8f612fa-2dbd-11e6-96f4-d3196286880d.png)

**Comment by geoffthemedio** [comment]
Is it reproducible from a save the turn before?
My guess is it's another case of xenophobe telepathic detection getting quirky...

**Comment by ghost** [comment]
Pretty.  Do you have a savegame you could attach?  Both 15 and 16 (just before and just after) would be best.
Also, please attach the server log.

**Comment by TheSilentOne1** [comment]
Could you accidentally have built the supertester takeover building?

**Comment by Vezzra** [comment]
Nifty 😋 

And what @TheSilentOne1 said - because that buidling would do exactly what you've witnessed...

**Comment by geoffthemedio** [comment]
Looks like all empires on the map have visible detection range circles, which I think would not be visible if it was due to a super tester building. A screenshot in which the player's homeworld and the messages and empires windows are visible would be helpful.

**Comment by matt474** [comment]
The planet on the lower right of the purple empire has no vision circle, yet the core supply lines are connected to it. This suggests that the planet has a detection range larger than the galaxy, and most likely has a super tester on it. The other two would still have the default species and thus would still have a visible circle.

**Comment by tkinias** [comment]
It was indeed a super-tester takeover – I’m not used to that being enabled in the game and I’ve never intentionally built one before...

Please close (I don’t think I can do that myself).
