### ISSUE TITLE
Fleet window looks corrupted if scrollbar is hidden

### ISSUE THREAD

**Issue by Cjkjvfnby** [freeorion/freeorion#722]
Steps to reproduce:
- click on fleet to open fleet window
- enlarge window till scroll disappear

Observed result:
- scroll is absent, deep black hole at right border
  ![no_scroll_bar](https://cloud.githubusercontent.com/assets/171597/16180446/84ab97dc-368d-11e6-8f26-644cf35e76eb.png)

Expected result:
- scroll always present or content fill all window

`v0.4.5+ [build 2016-06-13.daadebe] MSVC 2013`
`Win 7x64`

**Comment by geoffthemedio** [comment]
Looks how it's supposed to, and works the same as most / all other variable-sized lists with scrollbars sometimes visible and sometimes hidden (planets list, sitrep, etc...)

**Comment by Cjkjvfnby** [comment]
I changed milestone o post release.

It looks like broken for me.

If it hard to fix lets close.

**Comment by TheSilentOne1** [comment]
adressed here: https://github.com/freeorion/freeorion/pull/757

**Comment by Vezzra** [comment]
#757 has been merged, so closing this issue.
