### ISSUE TITLE
Save file does not complete when immediately exiting game

### ISSUE THREAD

**Issue by dbenage-cx** [freeorion/freeorion#766]
With a sufficiently large enough game:
- `Menu` -> `Save Game` -> `OK`
- Immediately exit the game (`X` in top corner or `alt`+`f4`)

The save file is created as an empty file.

Waiting a brief period before exiting will successfully complete the save file.

"Sufficiently large" will likely be dependant on system specs and the users response time.
The following save consistently works for me if exiting within ~2 seconds after `OK`: [moderate_size_save.zip](https://github.com/freeorion/freeorion/files/362360/moderate_size_save.zip)

[Likely related forum post](http://www.freeorion.org/forum/viewtopic.php?f=28&t=9896#p84602)

**Comment by MatGB** [comment]
This does indeed sound exactly like what I'm experiencing, yes. Thanks for replicating, any ideas to solve?

**Comment by dbenage-cx** [comment]
Possibly some sort of progress indicator without a user interaction.  e.g. a self closing pop-up

This would not prevent a user from closing too soon, but it does give an indicator that the save is not finished.

**Comment by geoffthemedio** [comment]
I finished some partly implemented code, so now there is a line in the messages window after every save.

**Comment by dbenage-cx** [comment]
Very nice.  Would a `Saving...` message prior to serialization/processing be acceptable?  During an exceedingly long operation, the user is not aware the save is incomplete.

**Comment by geoffthemedio** [comment]
Probably, unless it gets spammy, though that's doubtful given the volume of messages already output each turn...
