### ISSUE TITLE
Add config string support to universe generation and turn events python code

### ISSUE THREAD

**Issue by Cjkjvfnby** [freeorion/freeorion#773]
Need to provide `fo.getAIConfigStr()`, `fo.getUserConfigDir()` to `universe generation` and `turn events` C++ API.

**Comment by Vezzra** [comment]
I understand that `getUserConfigDir` could be useful for the server Python interface, but why `getAIConfigStr`? What use case can you think of for this?

**Comment by Cjkjvfnby** [comment]
`getAIConfigStr` is used to change python script behavior without changing existing code.

At current time I want to trigger interface inspector for all interface in single run.

Other use case is generate special maps for testing purposes.

**Comment by Cjkjvfnby** [comment]
yes, yes

**Comment by Cjkjvfnby** [comment]
It is done.  https://github.com/freeorion/freeorion/pull/2271/files#diff-058ed30f9c557ea7d8387a675bb3ce01R35

**Comment by Vezzra** [comment]
Implemented by #2271.
