### ISSUE TITLE
The combat report should show structure as integer numbers

### ISSUE THREAD

**Issue by Deepsloth** [freeorion/freeorion#778]
The combat report shows structure as a decimal number, which looks messy in this example:
![combat report](https://cloud.githubusercontent.com/assets/11727275/17033901/96223122-4f80-11e6-9db6-e69c6e8a53d9.jpg)

**Comment by Vezzra** [comment]
@geoffthemedio, I assume you fixed this in 9dbaf8f27f0fd686812c2829c4e0f3d983cb472c? Just to sure...

**Comment by geoffthemedio** [comment]
hopefully.

likely they are other instances of similar number display issues, though.
