### ISSUE TITLE
Cannot paste anything into "Internet game at:" box

### ISSUE THREAD

**Issue by l29ah** [freeorion/freeorion#779]
Neither with middle mouse click nor with ^V. Having fun typing an ipv6 address there.

**Comment by geoffthemedio** [comment]
Not indicated what build you're using, but in the latest test builds, standard in-game cut-copy-paste hotkeys work, and you can right-click for a popup menu with similar commands.

But I doubt FreeOrion supports IPV6 anyway...

**Comment by l29ah** [comment]
On Fri, Jul 22, 2016 at 08:27:50AM -0700, Geoff wrote:

> Not indicated what build you're using, but in the latest test builds, standard in-game cut-copy-paste hotkeys work, and you can right-click for a popup menu with similar commands.

0.4.5. Building master now.

## 

()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments

**Comment by l29ah** [comment]
Yes indeed it works in master. Sorry for the noise.
