### ISSUE TITLE
Label Fleets Window as "near System X"

### ISSUE THREAD

**Issue by geoffthemedio** [freeorion/freeorion#786]
If a fleets window is showing fleets not at a system, indicate that the fleets are "near SystemName" instead of just saying "Fleets".

**Comment by Cjkjvfnby** [comment]
May be "on way to SystemName" for fleet with known destination?

**Comment by geoffthemedio** [comment]
This is about the whole window, not individual fleets. Also, fleets already are labelled with their destination.

**Comment by Vezzra** [comment]
Implemented by #1115
