### ISSUE TITLE
Server-side option to disable graphs

### ISSUE THREAD

**Issue by l29ah** [freeorion/freeorion#790]
They give one's intentions away in multiplayer games and make scouting and stealth not very useful.

**Comment by geoffthemedio** [comment]
You should be able to delete whichever you don't want from the relevant script files in 

https://github.com/freeorion/freeorion/tree/master/default/scripting/empire_statistics

(Or just delete all the files therein)

**Comment by l29ah** [comment]
Thanks, it did the job.

**Comment by Voker57** [comment]
Still having option to disable those per-game (and w/o altering game files) would be nice.

**Comment by geoffthemedio** [comment]
A complicated game-rules setup interface is vaguely planned, eventually...
