### ISSUE TITLE
Missing support for alternate planet landscapes

### ISSUE THREAD

**Issue by Deepsloth** [freeorion/freeorion#792]
The commit https://github.com/freeorion/freeorion/commit/2b3c363139f95df7e66fe89ea7af2e82dc5e201e added alternate planet landscapes to be used in the planet suitability pedia entries. Support for alternate images hasen't been implemented yet.

Discussion: http://www.freeorion.org/forum/viewtopic.php?f=10&t=9730&start=21

**Comment by wheals** [comment]
Can be closed now.

**Comment by Vezzra** [comment]
Implemented by #1835.
