### ISSUE TITLE
Beginning of the turn sound

### ISSUE THREAD

**Issue by l29ah** [freeorion/freeorion#800]
It would be nice if the game would play a sound when a next turn begins. This would solve a problem of missing it while going away doing other things while other people are finishing their turns in a multiplayer game. This is partially solved by the sound of the spawning messages window, but some turns don't produce any messages and the window won't open.

**Comment by MatGB** [comment]
Falls under the "why didn't we think of this before" feature requests, I definitely concur.

**Comment by l29ah** [comment]
Actually it may even make sense to call `notify-send` ;)

**Comment by dbenage-cx** [comment]
@l29ah What does `notify-send` refer to?

**Comment by l29ah** [comment]
I don't get your question.
`notify-send` is a program that asks DE/WM to pop up a notification in GNU/unixes.

**Comment by dbenage-cx** [comment]
Ok, thank you.  I will look into it this weekend.
