### ISSUE TITLE
Cannot bomb a planet

### ISSUE THREAD

**Issue by l29ah** [freeorion/freeorion#801]
I've come to an uncloaked native-robotic-inhabited planet, shut down its shields and defenses and brought an EMP-armed ship, yet i still can't bomb it.
Saved game: http://anonymous.lv/save-20160726_235959.mps
Pick L29Ah, then go to Gienah alpha.

**Comment by l29ah** [comment]
Ok, it turned out i need to pick an individual ship for bombing: just clicking on the fleet name won't do the job. I guess it would be cumbersome when i start bringing several bombers tho.

**Comment by l29ah** [comment]
And sometimes it just ceases bombing it and dealing no damage to the population, requiring re-ordering the bombing run.

**Comment by l29ah** [comment]
If i select the planet w/o selecting the ship and press "Cancel Bombarding", nothing happens.

**Comment by geoffthemedio** [comment]
Probably duplicates https://github.com/freeorion/freeorion/issues/672

**Comment by Vezzra** [comment]
Looks like it - @MatGB, can you confirm that #672 (you opened that one) covers everything mentioned here? If yes, we can close this one as duplicate.

**Comment by l29ah** [comment]
Yep, he hit the same thing. I could add that it needs two clicks on the cancel button when the ship is selected to cancel the bombing.
