### ISSUE TITLE
Tech tree labels are slow

### ISSUE THREAD

**Issue by l29ah** [freeorion/freeorion#811]
When i enable rendering of all technologies, fps drops to 5 on Intel(R) Core(TM) i7 CPU L 620 @ 2.00GHz, regardless the actual amount of visible labels. When i zoom out enough the labels vanish, fps grows to 30.

**Comment by Vezzra** [comment]
Been noticing that for a long time too, but never got around to open an issue about it. Thx.

Not sure how complicated it is to fix this, so I didn't assign a milestone yet.

**Comment by l29ah** [comment]
This reproduces better on debug builds btw: it becomes multiple times slower, like 0,7fps with full tech tree enabled.

**Comment by Vezzra** [comment]
Fixed by #936
