### ISSUE TITLE
Enable TCP keep-alives plz

### ISSUE THREAD

**Issue by l29ah** [freeorion/freeorion#819]
ISP NATs tend to forget about connections that doesn't have any data moving thru them for a while. That's why there's SO_KEEPALIVE sockopt. It should be enabled in the connections to freeoriond to avoid spurious disconnects.
// i'll try poing it in the meantime

**Comment by Vezzra** [comment]
I'm not familiar with the networking code at all, but this doesn't sound too complicated, and would fix a rather nasty issue in multiplayer... anyone pls correct me if I'm wrong.

Will tag it for the release for now.

**Comment by LordMike** [comment]
That, or send a form of heartbeat messages back and forth between peers. If no messages have been received within a timeframe, then the other peer has likely gone away.
