### ISSUE TITLE
Allow Energy shipyards to be built at systems where artifical black hole queued

### ISSUE THREAD

**Issue by MatGB** [freeorion/freeorion#820]
[FreeOrion • View topic - Energy Compressor requirements tweak](http://www.freeorion.org/forum/viewtopic.php?f=28&t=10142&p=84575#p84575)

The Energy Compressor and Solar Containment Unit shipyards can be built if an artificial black hole in enqueued on the same planet, ideally it should be any planet in the same system.

**Comment by dbenage-cx** [comment]
For some reason, I thought this was already done by someone else.

**Comment by MatGB** [comment]
I'd done a partial on it and someone suggested it be improved a bit, I never got around to opening the issue before going away and still had the tab open, I'm trying to clear up outstanding stuff, thanks.
