### ISSUE TITLE
Psionics doesn't seem to work

### ISSUE THREAD

**Issue by l29ah** [freeorion/freeorion#822]
The description suggests that by researching psionics and capturing telepatic species i'll have reduced tech costs, but nope, death rays are as expensive as usual.

**Comment by MatGB** [comment]
By having a telepathic species the cost to research psionics is reduced (from 600 to 100), and also telepathic species are the only ones able to use some abilities/immune to some abilities.

It's an area that needs more work at some point but for now it definitely works as intended for me, the issue might be the description (or translation?) isn't clear, point us at where you read it and we can try to imrpvoe it.

**Comment by l29ah** [comment]
Yes, i've misunderstood the description in the pedia, combined with the fact that telepathic species usually have a penalty to research and never a bonus.
