### ISSUE TITLE
Asteroid hull is too costly

### ISSUE THREAD

**Issue by l29ah** [freeorion/freeorion#827]
It is said it is inexpensive, yet it's twice as expensive compared to the robotic hull that has comparable features, repairs itself and also requires less research and facilities.

**Comment by MatGB** [comment]
Not sure what version you're playing but the base cost before upkeep and parts of an asteroid Hull is 20, the base cost of a robotic Hull is 40, those numbers haven't changed for some time.

**Comment by l29ah** [comment]
It seems like i've stumbled upon some place where the hull price will not account for upkeep, but now i fail to find the actual place where i've seen this. Otherwise you're right.

**Comment by MatGB** [comment]
If you find it again do please post it as displays are meant to be consistent and while we're hoping to replace the current upkeep system soon this would definitely count as a bug.
