### ISSUE TITLE
Remove upkeep/maintenance mechanic

### ISSUE THREAD

**Issue by afwbkbc** [freeorion/freeorion#831]
This makes no sense. It worsens empire scaling, so even if your empire is 4 times larger and your fleet 4 times larger - you won't have 4x advantage, but something closer to 2x. This is unfair, especially in 1x2 games, where team of two players will suffer 2 times less from upkeep issue and will be able to keep more fleet. I don't see why must there be soft restrictions to number of ships - why not just let pump it linearly? It will make gameplay more rough, but more fair.

**Comment by Deepsloth** [comment]
I think this topic belongs into the forum. This is not an issue, but a conscious design decission.

**Comment by adrianbroher** [comment]
What @Deepsloth said.

We use the issue tracker as issue tracker and not as a discussion forum. Feel free to open a thread in the [FreeOrion forum](http://freeorion.org/forum/index.php) for your request.

**Comment by TheSilentOne1** [comment]
Let me add that this is something we have been discussing about, and which may be adressed if or when the influence mechanic is implemented: http://www.freeorion.org/forum/viewtopic.php?f=5&t=9998
