### ISSUE TITLE
Refueling a ship with fuel < 1 to >= 1 should generate a sitrep

### ISSUE THREAD

**Issue by l29ah** [freeorion/freeorion#835]
I have to poll all this horde of scouting ships stuck in the galaxy every turn otherwise.

**Comment by Cjkjvfnby** [comment]
Do you contol them manually or use auto explore?

**Comment by l29ah** [comment]
On Sat, Aug 06, 2016 at 01:48:01AM -0700, Andrey wrote:

> Do you contol them manually or use auto explore?

Manually. They tend to get eaten by known monsters on auto.

## 

()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments
