### ISSUE TITLE
Gateway to the Void can be used to block defeat

### ISSUE THREAD

**Issue by MatGB** [freeorion/freeorion#838]
[FreeOrion • View topic - gateway to the void](http://www.freeorion.org/forum/viewtopic.php?f=28&t=10169&p=84903#p84903)

It still refers to Outposts as having 0.1 population and is generally unclear, needs checking against the actual scripted effects and describing more clearly/accurately

**Comment by MatGB** [comment]
Effects and description updated with [Update Gateway to the Void description and code](https://github.com/freeorion/freeorion/commit/49f112123403b63956e46d2af3956163b4677ce5)

**Comment by MatGB** [comment]
The initial Issue is now dealt with but it's revealed a bigger problem, with the new victory conditions/sitreps the gateway as scripted both before and now can be used to prevent defeat as it's basically unconquerable. The ability to force a stalemate is something we could choose to introduce but this isn't/shouldn't be it.

[gateway to the void](http://www.freeorion.org/forum/viewtopic.php?f=28&t=10169)

(keeping the current milestone for now but it could be left for post Release as it is a very edge case problem)

**Comment by Vezzra** [comment]
Too rare an edge case to block the release for it, so I'm removing the "Release 0.4.6" milestone.

**Comment by rrobgill** [comment]
I believe this has been resolved by #3068
