### ISSUE TITLE
Scanline display differs between fleets and systems

### ISSUE THREAD

**Issue by dbenage-cx** [freeorion/freeorion#841]
Scan lines for a fleet/ship map icon are rendered below/under the icon.
For systems, they are rendered on top/above the icon.
![stealth_planet](https://cloud.githubusercontent.com/assets/17205519/17450805/106d475c-5b28-11e6-8cb1-0ec7f33bf9f9.png)![stealth_planet2](https://cloud.githubusercontent.com/assets/17205519/17451330/96a5579e-5b2b-11e6-876c-f92ccd5f06fe.png)

Pointed out by l29ah in #826

**Comment by geoffthemedio** [comment]
planets -> stars or systems

**Comment by Vezzra** [comment]
See, I never noticed that there have been scanlines on fleet icons at all... that visual indicator definitely needs improvement.

**Comment by Vezzra** [comment]
Hopefully not too hard to fix, so tagged it for the release.
