### ISSUE TITLE
Avoiding resetting the config file?

### ISSUE THREAD

**Issue by l29ah** [freeorion/freeorion#842]
When i switch between different builds of freeorion, every time the config file is being reset to defaults, forcing me to reconfigure the game, even though there aren't seem to be any format incompatibilities. Is this an intended behaviour? How do i avoid this?

**Comment by TheSilentOne1** [comment]
The behaviour is intended, as in the past config files from different builds caused a variety of bugs. However, you can create a persistent config file that will not be deleted:
http://www.freeorion.org/index.php/Config.xml
