### ISSUE TITLE
Implement 'Graviton Disruptor' ship component

### ISSUE THREAD

**Issue by afwbkbc** [freeorion/freeorion#848]
Ship with such component must be stationed near target star system (e.g. range 50 or 100). It can then start deployment, which will take several turns. On successful deployment, star of target star system is immediately transformed into black hole, all its planets with population and infrastructure are destroyed, as is any fleet stationed there. In addition, shockwave is released to nearby systems. Its power is proportional to size and number of planets that were destroyed by black hole, and depends on how far this system is. Effects can include turning small planets into asteroids, medium to small+asteroids, reducing or eliminating population, destroying some infrastructure, damaging/destroying ships, turning planets into irradiated or barren or inferno, etc. Gas giants can be ignited, making this system a two-star system and eliminating all life except for inferno planets.
This new mechanic will prevent players from going into infinite fortifications of planets in late game, they will now also have to have a fleet to destroy deploying graviton disruptors near their systems.

**Comment by afwbkbc** [comment]
Will you accept pull request for this?

**Comment by MatGB** [comment]
Not immediately, we're not putting any new features in at the moment that would require the AI team to do more work as they're catching up with existing stuff pending the next Release.

However, it is an interesting idea, I have some fairly strong balance concerns (as I always do with new strong features)—I'd basically want to see a proper spec for it and then it would almost certainly need tweaking, etc.

But if you want to get the basics setup, as long as you understand it can't go into the game without the AI agreeing to it and putting in their own changes, we're good.

**Comment by Vezzra** [comment]
This one is more specific, so probably sort of an edge case. But still, I think the forum is the better place for the kind of discussion an addition like that requires. So I recommend the same as for #849, although this one here should probably go into the [Scripting & Balancing forum](http://freeorion.org/forum/viewforum.php?f=15). Please open an appropriate thread there.

**Comment by Vezzra** [comment]
As this is more specific feature request than the other issues, I will let that one here stay for the time being. Nevertheless, please use our forum for relevant design/balancing discussions, and once a satisfying consensus has been reached, you can provide an implementation via PR.
