### ISSUE TITLE
Feature request: Missile hulls and payloads

### ISSUE THREAD

**Issue by afwbkbc** [freeorion/freeorion#849]
A new tech branch can be added. Missile hulls have no HP (or 1hp), high stealth and starlane speed, very low cost (most of cost comes from payloads). Stealth (do-not-attack) behavior by default. Upon entering fight they detonate, damaging one or several ships. Depends on payload. Some have point damage, some are weaker but have area-of-effect damage like mines, some also reduce planet population if attacking planet.
This mechanic would help battling really tough ships/fleets.

**Comment by Vezzra** [comment]
That's actually more an idea for a game element/mechanic, not really a feature per se, and as such should be subject to design discussion on the [game design forum](http://freeorion.org/forum/viewforum.php?f=6) first. So I recommend closing this issue, open a thread on the forum and presenting your idea there.

Objections anyone?

**Comment by Vezzra** [comment]
Going ahead and closing this now as invalid, please open a thread describing these ideas on our forums as suggested above.
