### ISSUE TITLE
Feature request: add border and supply sharing between allies

### ISSUE THREAD

**Issue by afwbkbc** [freeorion/freeorion#852]
Often there is a need to defend ally from attack, but ships just can't get anywhere.
Also its inconvenient that ally must tell where enemies are, how many of them.
Both border and supply sharing can be disabled by default, but enablable through right-click menu in empires panel.

**Comment by afwbkbc** [comment]
Sry, by "border: I mean vision.

**Comment by Vezzra** [comment]
Things like that are planned - this belongs to the whole diplomacy/empire relations field. There has been some preliminary work done at best, aside from that we haven't even entered the design phase on this entire thing. Just a lot of ideas floating around.

Anyway, like your other requests, #848 & #849, this doesn't really belong here on the issue tracker, but on our [forum](http://freeorion.org/forum/). So once again, please, you're very welcome to present your ideas there, but don't use our issue tracker for ideas/design discussions.

**Comment by Vezzra** [comment]
Closing as invalid, please open forum thread to discuss these ideas.
