### ISSUE TITLE
Multiplayer lobby window is tiny

### ISSUE THREAD

**Issue by l29ah** [freeorion/freeorion#858]
![screenshot](https://dump.bitcheese.net/files/boxinel/screenshot-window.png)
The players don't fit the list and it's impossible to use all those huge bezels.

**Comment by Vezzra** [comment]
A result of the bigger default font size. Definitely needs to be fixed.

**Comment by geoffthemedio** [comment]
https://github.com/freeorion/freeorion/commit/1a90cd26f74ec8a1e08239c2e478dd20c8863d8e
