### ISSUE TITLE
Folder default/readme.txt needs updating

### ISSUE THREAD

**Issue by MatGB** [freeorion/freeorion#860]
> buildings.txt, fields.txt, ship_hulls.txt, ship_parts.txt, specials.txt, species.txt, techs.txt: These define the basic content types referred to in their names. 

Many of these files either no longer exist or have been substantially reduced, the subfolder system needs explaining.

> Note that species.txt often contains the effects of techs/buildings, for technical reasons.

All of this has either been moved to a .macro file or put into the tech or building location.

**Comment by dbenage-cx** [comment]
Should this be changed to a markdown, or the other README.md files changed to basic text?
I prefer the former, any issues with Windows not associating the extension by default?

**Comment by MatGB** [comment]
Beyond me I'm afraid, I was looking something else up and github displayed it for me, as the first paragraph was obviously wrong I thought best to open the issue. 

However, I'm instinctively drawn to saying that, even if it's normal to use a different type, having it in simple plain text might be preferred as it's the instructions for the _default_ folder which is meant to be all the simple-to-customise stuff is kept for non-coders.

**Comment by Vezzra** [comment]
Markdown is still pretty well readable even if viewed only as plain text, and we've converted the other readme files from plain text to markdown some time ago (IIRC @adrianbroher did this). So I'd say change to markdown.

Other comments/opinions on that?

**Comment by Vezzra** [comment]
Oh, nevermind, just saw in #861 that you decided to switch to markdown anyway. Agree with all the reasons cited (just for the records :wink:).
