### ISSUE TITLE
SetSpecialCapacity seems to reset the initial time of the special

### ISSUE THREAD

**Issue by agrrr3** [freeorion/freeorion#865]
### Environment
- **FreeOrion Version**:  v4.0.5+ freeorion build from june (2016-06-06.4187172)
- **Operating System**: windows 8.1 pro ,
- **Graphic card used**:
- **Fetched as**
  - Binary release
### Description

i scripted an effect which uses SetSpecialCapacity on a planet and it seems that the initial turn gets reset. It gets set to the turn in which SetSpecialCapacity is happening (i can see it in the user interface "Present since turn:" and also HasSpecialSinceTurn reacts on it).

I tried to check if that is intended, googled and found the code for the method in UniverseObject.cpp and it looks like it is not intended. Actually the cpp code looks like it shouldn't change, but it changes.
### Expected Result

SetSpecialCapacity should not change the turn since which the special exists. 
#### Steps to reproduce
- Script a special to be added to a planet and have its capacity set each turn using SetSpecialCapacity
- Watch the special in freeorion and its "Present since turn:"  field

**Comment by geoffthemedio** [comment]
If you found the relevant line(s), it would be convenient to link to them...

https://github.com/freeorion/freeorion/blob/master/universe/UniverseObject.cpp#L378
https://github.com/freeorion/freeorion/blob/master/universe/Effect.cpp#L2167

**Comment by agrrr3** [comment]
Sorry, forgot about linking the file and didnt know about the line anchor. Thanks geoff, will do next time

**Comment by agrrr3** [comment]
And in the Effect.cpp i didnt find a reference to setting the specials capacity. Where is the mapping from the parse token (https://github.com/freeorion/freeorion/blob/master/parse/Tokens.h#L375) happening?

**Comment by geoffthemedio** [comment]
https://github.com/freeorion/freeorion/blob/master/parse/EffectParser3.cpp#L84

**Comment by agrrr3** [comment]
@geoffthemedio  thanks! ok, that explains it. AddSpecial and SetSpecialCapacity both use Effect::AddSpecial. 
If I get it right I would have to add a SetSpecialCapacity to Effect.\* using the UniverseObject method, and change the EffectParser to use it for tok.SetSpecialCapacity_ (?). I dont have a freeorion c++ development environment, so I'm not really able to fix and verify. Can I help in some way?

**Comment by geoffthemedio** [comment]
Or modify what AddSpecial does in the case a special is already present on an object.

**Comment by agrrr3** [comment]
What is the intended behavior for adding an already existing special? Should that reset the "present since" turn or not?

**Comment by geoffthemedio** [comment]
No particular design decision was likely ever made about it... Just me adding a feature and implementing something. If it doesn't work as is, likely nothing else depends on it, so it can be changed.

**Comment by Vezzra** [comment]
I'd say in case a special is added to an object that already has that special attached, the code should treat that as an "update" to the existing special (not as a replacement of the old special by a new one), so no resetting of the "present since turn" value.

**Comment by geoffthemedio** [comment]
Hopefully fixed. Please check.

https://github.com/freeorion/freeorion/commit/8ebf00cfd33c75384a31d1b9b69e5999450fe3c3

**Comment by Vezzra** [comment]
While waiting for @agrrr3 to report back to decide if we can close this issue, I'm going to remove the "Release v0.4.6" milestone. Fixed or not, this isn't game-breaking or critical in any way, so should not hold up the release.

**Comment by agrrr3** [comment]
Sorry, on not responding earlier. I'm trying to set up a build environment in a virtual machine.

**Comment by Vezzra** [comment]
No problem, take your time...

**Comment by geoffthemedio** [comment]
@agrrr3 status?

**Comment by agrrr3** [comment]
Finally starting testing.

Was busy with creating a reproducible build environment using docker. 
Have the current setup running and its slow as hell (8fps best), will probably have to change in future:
Windows 8.1 Host  - VirtualBox - Lubuntu VM - freeorion git sources
Windows 8.1 Host  - VirtualBox - Lubuntu VM - Docker - docker image building freeorion 0.4.5+ based on debian squeeze (mounting the sources as volume)
Windows 8.1 Host  - VirtualBox - Lubuntu VM - Docker - docker image building freeorion 0.4.5+ based on debian squeeze
(Windows 8.1 Host  - xpra) connecting via ssh to (... Lubuntu VM - Docker - docker container running xpra and freeorion)

**Comment by agrrr3** [comment]
Ok, its looking good, SetSpecialCapacity and AddSpecial work. 
Code analysis shows no use which should cause troubles.
Thank you for your patience :)
