### ISSUE TITLE
FreeOrion version string should be more accessible

### ISSUE THREAD

**Issue by adrianbroher** [freeorion/freeorion#875]
### Environment

- **FreeOrion Version**: master
- **Operating System**: any
- **Graphic card used**: -
- **Fetched as**
  - Compiled from source
### Description

Split of from #872.

When reporting issues on github, users are asked to give the version number of the version they experience the bug/issue.  However the user is forced to manually copy the version string because there is no way to select or output the version string easily.
### Expected Result

The user should be able to select and <Ctrl+C> the version string into the clipboard. Also when right clicking the version string there should be a context menu containing a `copy to clipboard` entry.
Additionally the user should be able to execute `./freeorion --version` on command line. This should print out the version string on the standard output and terminate the application immediately with exit=0.
#### Steps to reproduce

- Start freeorion.
- Select or right click version string
- Nothing happens

Alternative
- Start `freeorion` on command line with `freeorion --version`
- `freeorion` does start regularly without printing a version string

**Comment by adrianbroher** [comment]
Milestone: I suggest this should be part of release 0.4.6

It's an easy to fix bug and would give us better quality issue reports.

@Vezzra any opinion on that?

**Comment by Vezzra** [comment]
@adrianbroher, assuming it's as easy as you expect it to be (an expectation I share), I guess we can flag this for the release.

However, if it can't be addressed in time, I won't block the release for it.

**Comment by adrianbroher** [comment]
@Vezzra's response got lose somewhere in the interwebs:

> @adrianbroher, assuming it's as easy as you expect it to be (an expectation I share), I guess we can flag this for the release.
>
> However, if it can't be addressed in time, I won't block the release for it.
