### ISSUE TITLE
Scanlined fleets/ships within detection range

### ISSUE THREAD

**Issue by Vezzra** [freeorion/freeorion#876]
### Environment
- **FreeOrion Version**: v0.4.5+ [build 2016-08-16.6a394b5]
- **Operating System**: Mac OS X 10.10.5
- **Graphic card used**: AMD Radeon HD 6490M 256 MB
- **Fetched as**
  - Compiled from source
### Description

As can be seen on the screenshot below, there are two fleets of enemy troop ships at Trobia Beta that are scanlined - the fleet and ship icons in the fleet window as well as the fleet icon on the map.

However, these fleets are within my detection range (I'm the blue player), so this shouldn't be possible.

These troop fleets at Trobia Beta are the only ones that show this strange behaviour, all other enemy ships I encountered in this game (so far) are displayed as expected.

![scanlinedfleets](https://cloud.githubusercontent.com/assets/10279417/17731855/8537a302-646f-11e6-985e-6469991824ec.png)

Savegame: 
[savegame.zip](https://github.com/freeorion/freeorion/files/422234/savegame.zip)
### Expected Result

There should be no "sensor ghosts" within detection range.

Either these ships are really there and have a stealth below my empires detection strength, in which case they should be displayed without the scanlines.

Or they have been detected previously, and then moved while not in detection range, or had their stealth raised and became undetectable, thus creating sensor ghosts. In which case those sensor ghosts should have been cleared once they came back into my detection range.
### Steps to reproduce

I haven't found a way to reproduce the issue reliably.

**Comment by dbenage-cx** [comment]
Wrong save file?  Not seeing any of the systems in the screenshot.

**Comment by Vezzra** [comment]
@dbenage-cx, just downloaded the save and checked it - everything is there. The Grail, Thäti and Trobia star system groups are located in the botton right area of the (visible) map. If you can't find them after you loaded the save, can you post a screenshot of the map as it's displayed on your system?

**Comment by Vezzra** [comment]
Ok, something I noticed only now (when looking at that save again): these troop ships have stealth 15, which is above my empire detection strength of 10. However, in this case, the question is, why can I see them at all?

Something doesn't add up here.

**Comment by dbenage-cx** [comment]
My fault, loaded from wrong dir :/
Spatial Flux Hull has a lower stealth while moving, in this case you will see it move but lose track of it shortly after it arrives. At turn 61, I saw another couple of these arrive in system, they disappear (scanlines) shortly after the turn starts.

**Comment by MatGB** [comment]
Aye, it's one of those "why" effects added ages ago I haven't gotten around to reviewing, but flux hulls are regularly appearing and disappearing until you've researched AR.

**Comment by Vezzra** [comment]
Ah, I see, now that explains a few things. Well, I still consider that a glitch we need to do something about, probably not for the release, but long term. It's somewhat confusing if you see them coming, and on arrival they turn into sensor ghosts that don't go away.

And I still wonder why they sensor ghosts won't go away. I mean, don't sensor ghosts get cleared if the area where they are displayed gets within your detection range? Well, apparently not...

**Comment by MatGB** [comment]
In theory, they do get cleared, I've certainly seen it happen, but they don't clear if the stealth at the time they were ghosted remains above your detection (eg ion storms that've moved on).

The most common reason a ghost clears is if you sight the actual ship somewhere else, that doesn't happen if it dies out of your vision or merges/matures.

Basically, you're supposed to know that there is/was something there when you last surveyed the area (which is good), but it lasts a long time and even with the new ability to clear the ghosts it can be annoying at times.

**Comment by Vezzra** [comment]
Hm, I see... I admit that's tricky. If those sensor ghosts vanished immediately (because they are in my detection range), a player might miss that there have been ships incoming which just became undetectable upon arrival.

But if sensor ghosts get not cleared in this case, they can potentially stay for the rest of eternity, which can be annoying. I suppose the ability to clear them manually now is probably the best compromise, so I'm going to close this as wontfix.
