### ISSUE TITLE
Bonus/malus details tooltip box does not fit contained text properly

### ISSUE THREAD

**Issue by Vezzra** [freeorion/freeorion#877]
### Environment
- **FreeOrion Version**: v0.4.5+ [build 2016-08-16.6a394b5]
- **Operating System**: Mac OS X 10.10.5
- **Graphic card used**: AMD Radeon HD 6490M 256 MB
- **Fetched as**
  - Compiled from source
### Description

As can bee seen on the screenshot below, the tooltip box displaying the breakdown of the boni/mali applied to the research meter does not entirely fit the text lines:

![tooltipvisualglitch](https://cloud.githubusercontent.com/assets/10279417/17732305/64b6757a-6471-11e6-8984-0e1843502ce9.png)

This also happens with other meters (I checked the industry meter too).

Savegame: 
[savegame.zip](https://github.com/freeorion/freeorion/files/422234/savegame.zip) (this is the same file as for #876)
### Expected Result

The tooltip box should be wide enough to properly contain all text lines.
### Steps to reproduce
- Start new game
- Research several techs that give boni to research and/or industry
- After having gained some boni, hover the mouse over the industry or research icon of one of your colonies on the planets sidebar

**Comment by adrianbroher** [comment]
This is a general issue with almost all GG UI elements. Most of them don't honor their content dimensions.

**Comment by Vezzra** [comment]
Ok, I thought that worked before the change to the default font size... well, I'll downgrade the milestone to "none", meaning if someone gets around to fix it in time for the release, fine, otherwise we'll live with these glitches (as far as the release is concerned, not forever of course 😉).

**Comment by Vezzra** [comment]
@adrianbroher is right, this is a general issue. Here is another example of a tooltip box (this time the breakdown for the structure stat of a ship):

![tooltipvisualglitch2](https://cloud.githubusercontent.com/assets/10279417/17747217/1033e0bc-64b4-11e6-8a1a-619fda5f31e1.png)

I _do_ believe however that these glitches were introduced when the default font size has been increased (can't remember having seen them before). So the question remains if we shouldn't try to fix this for the release, or just live with it for the time being - @geoffthemedio?

**Comment by geoffthemedio** [comment]
https://github.com/freeorion/freeorion/commit/68b91cc861ce2ec98da2d9cd94bb8c7c69ca8fcb

Would be better if it adjusted to just fit the text, but that's more effort.
