### ISSUE TITLE
Default size of PP breakdown window on production screen too small

### ISSUE THREAD

**Issue by Vezzra** [freeorion/freeorion#881]
### Environment
- **FreeOrion Version**: v0.4.5+ [build 2016-08-16.6a394b5]
- **Operating System**: Mac OS X 10.10.5
- **Graphic card used**: AMD Radeon HD 6490M 256 MB
- **Fetched as**
  - Compiled from source
### Description

Another glitch most likely introduced by the change of the default font size, this time it's the PP summary on the production screen:

![pp_summary](https://cloud.githubusercontent.com/assets/10279417/17747380/e139386a-64b4-11e6-8be1-54b175cfe99d.png)
### Expected Result

The default size of the PP summary window should be sufficient to show the entire contents without them being clipped.
### Steps to reproduce

Start new game and go to the production screen.

**Comment by geoffthemedio** [comment]
Somewhat better, not great:

https://github.com/freeorion/freeorion/commit/f95628816719ea41e8b0e1d04175856a8a2759f1
