### ISSUE TITLE
Incorrect display of circular fleet movement orders

### ISSUE THREAD

**Issue by l29ah** [freeorion/freeorion#885]
If you use Shift-clicks and make the fleet go in a circle, it will display "Holding at X" in the status, but will execute the order properly. // 0cab3265af9777a0f5fb90e2680e235dadeeae17

**Comment by geoffthemedio** [comment]
https://github.com/freeorion/freeorion/commit/4e3969fa15ecf3b617e64beb55009462e3e7c0e8
