### ISSUE TITLE
Fails to build with boost 1.61

### ISSUE THREAD

**Issue by Voker57** [freeorion/freeorion#887]
Latest git, debian unstable

Build log: http://dump.bitcheese.net/files/lutaryw/build.log.gz

**Comment by geoffthemedio** [comment]
Probably duplicates https://github.com/freeorion/freeorion/issues/777

**Comment by Vezzra** [comment]
I'd say yes, that's a duplicate, but just to be sure I'd like another opinion - @adrianbroher, you're on Linux, can you confirm the problem reported here is the same as in #777?

**Comment by Vezzra** [comment]
Ok, in this case we need to keep this open as a separate issue.

**Comment by Vezzra** [comment]
As decided in the discussion of #851 ([see these comments](https://github.com/freeorion/freeorion/issues/851#issuecomment-241255590)), setting milestone to "Release v0.4.6" again for now.

**Comment by adrianbroher** [comment]
Note:

Reverting https://github.com/boostorg/serialization/commit/69ecae6919b417be2b2558aefffea97fbe50d4a8 in the debian test chroot makes the issue go away.  It's not a viable solution for us however.

**Comment by LGM-Doyle** [comment]
@adrianbroher I have some guesses.

The commit that you referenced (2 hours ago), suggests that adding delete operators to the serialized classes may fix the problem.

The log file linked above suggests a simpler solution may be to make the destructors public.

If you are not already on it (I assume that you are), I could try posting PRs with those solutions implemented.

**Comment by adrianbroher** [comment]
@LGM-Doyle 

> The commit that you referenced (2 hours ago), suggests that adding delete operators to the serialized classes may fix the problem.

Well, I don't have much experience with overwriting new/delete and making the destructors public is just a cheap workaround as it doesn't convey the fact that `UniverseObject`s are not supposed to be managed  by the `Universe` instance itself.

What do you think would be the best way to fix this?

**Comment by LGM-Doyle** [comment]
@adrianbroher I think the better fix is to make the destructors public, for the following reasons:
- `UniverseObject` implies it is associated with `Universe`
- the only place that `UniverseObject` can get a valid ID is from the `Universe`
- overwriting delete will probably lead to complicated bugs.

**Comment by l29ah** [comment]
Still an issue for 1.62.0, correct the ifdefs plz.

**Comment by Vezzra** [comment]
I thought 5a3c309cd4025f207e3a77fe57021934e80de703 fixed the issue... so did it turn up with 1.62 again so we need another fix, or didn't 5a3c309cd4025f207e3a77fe57021934e80de703 fix the issue for you in the first place?

**Comment by geoffthemedio** [comment]
https://github.com/freeorion/freeorion/commit/5a3c309cd4025f207e3a77fe57021934e80de703 makes a change specifically for Boost 1.61, and would have no effect with any other boost version.

**Comment by Vezzra** [comment]
Uh, stupid me, should have looked at the commit 😳 

Well, looks like the fix needs to be extended to apply to 1.62 too... rename and reopen this issue, or open a separate one?

**Comment by geoffthemedio** [comment]
I made the version number checks >= instead of ==

https://github.com/freeorion/freeorion/commit/6b971f65dbef4614cd0c9020bcc6670d3f11b961

**Comment by Vezzra** [comment]
@l29ah, just to be sure, everything now works for you?

**Comment by l29ah** [comment]
On Fri, Oct 28, 2016 at 03:17:29AM -0700, Vezzra wrote:

> @l29ah, just to be sure, everything now works for you?

/usr/include/boost/spirit/home/qi/detail/alternative_function.hpp:30:46: error: no type named ‘types’ in ‘boost::spirit::qi::detail::find_substituteboost::optional<boost::variant<boost::fusion::vector2<boost::optional<EmpireAffiliationType, ValueRef::ValueRefBase<int>_>, EmpireAffiliationType, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> >, EmpireAffiliationType>::variant_type {aka class boost::optionalboost::variant<boost::fusion::vector2<boost::optional<EmpireAffiliationType, ValueRef::ValueRefBase<int>_>, EmpireAffiliationType, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> >}’
         typedef typename variant_type::types types;
                                              ^

## 

()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments

**Comment by Vezzra** [comment]
Can you build with boost 1.61? If yes, that's probably a new issue specifically with 1.62, for which a separate issue should be opened.

**Comment by l29ah** [comment]
On Fri, Oct 28, 2016 at 04:56:36AM -0700, Vezzra wrote:

> Can you build with boost 1.61? If yes, that's probably a new issue specifically with 1.62, for which a separate issue should be opened.

https://github.com/freeorion/freeorion/issues/777

## 

()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments

**Comment by Vezzra** [comment]
Ok, I'm a bit confused... #777 has been closed because, if I understand correctly, solutions had been found to deal with the issues introduced by boost 1.61. So, assuming I read your response correctly, you _can_ build with boost 1.61, but when using 1.62 the issues of #777 turn up again (as do the compile errors you posted above).

Which is confusing, because if these are still the same issues as with 1.61, why don't the fixes work anymore? Unless we're dealing with almost identical, but still new issues here introduced by 1.62 - in which case a separate issue should be opened (where of course #777 and this issue here should be referenced).

**Comment by l29ah** [comment]
On Fri, Oct 28, 2016 at 05:17:06AM -0700, Vezzra wrote:

> Ok, I'm a bit confused... #777 has been closed because, if I understand correctly, solutions had been found to deal with the issues introduced by boost 1.61. So, assuming I read your response correctly, you _can_ build with boost 1.61, but when using 1.62 the issues of #777 turn up again (as do the compile errors you posted above).
> 
> Which is confusing, because if these are still the same issues as with 1.61, why don't the fixes work anymore? Unless we're dealing with almost identical, but still new issues here introduced by 1.62 - in which case a separate issue should be opened (where of course #777 and this issue here should be referenced).

Because they check for exact version match, i suppose.

## 

()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments

**Comment by geoffthemedio** [comment]
> Because they check for exact version match, i suppose.

Not anymore...

https://github.com/freeorion/freeorion/commit/6b971f65dbef4614cd0c9020bcc6670d3f11b961

**Comment by l29ah** [comment]
On Fri, Oct 28, 2016 at 06:01:09AM -0700, Geoff wrote:

> > Because they check for exact version match, i suppose.
> 
> Not anymore...
> 
> https://github.com/freeorion/freeorion/commit/6b971f65dbef4614cd0c9020bcc6670d3f11b961

You can't into context (#777).

> CMakeLists.txt:if(${Boost_VERSION} EQUAL "106100")

## 

()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments

**Comment by geoffthemedio** [comment]
If there are more places that need adjusting, can you make a pull request?

**Comment by Vezzra** [comment]
> You can't into context (#777).
> 
> > CMakeLists.txt:if(${Boost_VERSION} EQUAL "106100")

Ah, here is the culprit. I knew @geoffthemedio had adjusted a fix to apply not only for 1.61, but also for later versions, which is why I've been confused - I thought the fixes weren't for 1.61 only anymore.

Well, that of course needs to be fixed.
