### ISSUE TITLE
AI chats during debug mode

### ISSUE THREAD

**Issue by Morlic-fo** [freeorion/freeorion#894]
### Description

The AI will chat its "banter" lines while the debug mode is active.
Example:

> Human_Player: start 2
> AI_3: Entering debug mode
> Print 'stop' to exit.
> Local variables:
>   ai  aistate
>   u   universe
>   e   empire
> Human_Player: import SupplyAI
> **AI_4: Didn't Stephen Hawking warn you not to talk to us?**
> Human_Player: print SupplyAI.supply_manager
> AI_3: <SupplyAI.SupplyManager object at 0x031E2D30>
> **AI_2: Don't bother me, I'm eating... aliens!**
### Expected Result

No irrelevant chatting in debug mode.

**Comment by Cjkjvfnby** [comment]
And other issue with debug mode.   End of the turn should turn it off or reset game variables (`universe`, `AIState`)

**Comment by Morlic-fo** [comment]
Don't turn it off. I often use it over several turns. You just have to call stuff like `universe = fo.geetUniverse()` each turn...

Updating the preset variables like `u` seems reasonable.
