### ISSUE TITLE
Server port changed

### ISSUE THREAD

**Issue by Voker57** [freeorion/freeorion#900]
6ad3342ee512b1e1bbff61655046fa3a, while allowing server ports to be changed from settings, changed them from 12345, 12346 to 12545, 12546. Not sure if it's intended.

**Comment by geoffthemedio** [comment]
not intentional, but probably irrelevant...

**Comment by geoffthemedio** [comment]
https://github.com/freeorion/freeorion/commit/1849a4b26c31732a0b0940b1103f7819077b5390
