### ISSUE TITLE
Situation report font size does not obey UI options

### ISSUE THREAD

**Issue by raptor** [freeorion/freeorion#901]
- **FreeOrion Version**:  0.4.5+ [build 2016-08-21.68b91cc]
- **Operating System**:  openSUSE 13.2 x86_64
- **Graphic card used**:  Both Intel (using i915 module) and NVidia Quadro NVS 4200M (using nvidia binary blobs)
- **Fetched as**
  - Compiled from source
### Description

Adjusting the font size for 'text' in the UI options does not adjust the font size for the yearly situation reports.  This occurs even after restarting the game, and in different screen modes (full screen/ windowed and with different resolutions).

**Comment by geoffthemedio** [comment]
There is a separate option for the sitrep font size, which is not reflected in the options screen. Why this was added, I'm not sure, but it's certainly intentional.

**Comment by geoffthemedio** [comment]
https://github.com/freeorion/freeorion/commit/5f94fee8ef139abd2a11cbf0ce942a0241b3ee9c
http://www.freeorion.org/forum/viewtopic.php?p=79699#p79699
http://www.freeorion.org/forum/viewtopic.php?f=9&t=9589

**Comment by Vezzra** [comment]
Hm, it's nevertheless far from ideal that the font size you can specify in the options dialog has no effect on the sitrep text, without being able to change the font size for it too via the options dialog. That you can do so by hacking config.xml isn't really helping.

@TheSilentOne1, 5f94fee8ef139abd2a11cbf0ce942a0241b3ee9c was your commit, what was the idea again? Why didn't you add sitrep font size to the options dialog?

**Comment by TheSilentOne1** [comment]
No specific reason. If there's no objections, I'll do so.

**Comment by adrianbroher** [comment]
From http://www.freeorion.org/forum/viewtopic.php?p=79699#p79699

Please keep the response order in mind: 3 1 2.

> and there is a forum thread with more information on the rationale.

There is no obvious link to the rationale. It's not clear if this means that there should be two font size settings (I don't believe this is intentional) or if the icon size should be configurable and not depend on the font size (sound much more reasonable to me).

**Comment by TheSilentOne1** [comment]
Firstly, the option-db entry currently (also) has no effect on the sitrep font size. My bad - first contact with FreeOrion's code. However, I agree with @adrianbroher that we don't need an individual font size for the sitrep entries. So I second to remove the sitrep font size options-db entry.
If we agree on this I'll put up a fix.

**Comment by TheSilentOne1** [comment]
(Actually, I see now it used either the std font size or sitrep font size, whichever was larger.)

**Comment by Vezzra** [comment]
> However, I agree with @adrianbroher that we don't need an individual font size for the sitrep entries. So I second to remove the sitrep font size options-db entry.

I second that too.
