### ISSUE TITLE
Supply doesn't propagate into newly conquered systems correctly

### ISSUE THREAD

**Issue by MatGB** [freeorion/freeorion#902]
### Environment
- **FreeOrion Version**: [49f1121](https://github.com/freeorion/freeorion/commit/49f112123403b63956e46d2af3956163b4677ce5)
- **Fetched as**
  - Compiled from source
### Description

A newly conquered planet/system has zero supply (this is good), but if you move the conquering fleet out on the turn you land the troops, the next turn the planet will be out of supply _even if another planet has enough supply to propagate in_.

I believe this is introduced by #896 as I've not noticed it before, and if supply propagation is calculated before invasions that would make sense.
### Expected Result

If a friendly system is within supply of a newly conquered system, the newly conquered system should display and be in supply assuming no enemy forces/planets block it.
### Steps to reproduce

Invade all planets in a system that is in supply range of a friendly system
Move warships away so system is empty
End turn
![supply-blocking](https://cloud.githubusercontent.com/assets/11533206/17848821/824ef118-684d-11e6-9e52-c71af759b7d5.png)

Attached picture shows newly conquered Bhanu is within supply of Menkalinan but it hasn't propagated in, thus lost production is displayed by the UI.

**Comment by MatGB** [comment]
Not sure if this should block release so not put in a milestone, @geoffthemedio, fairly sure that it's your most recent change, easily fixable?

**Comment by geoffthemedio** [comment]
The last supply update is after combat, but invasions are handled before combat. Unobstructed systems and empire system supply ranges are also updated immediately before the supply update.

https://github.com/freeorion/freeorion/blob/master/server/ServerApp.cpp#L3045

**Comment by geoffthemedio** [comment]
I can't tell from the image and text what empire you are and what system you're concerned about. Bhanu γ I guess? Looks like it's in a separate supply group from the other systems that it appears like it should be connected to..

Is it just a display bug, or does at actually affect production on the subsequent turn?

**Comment by Vezzra** [comment]
He is the violet empire and apparently had just conquered Bhanu Gamma (that's the system showing the wasted production resource supply lines). If I understand correctly, he gave his troop ships the invasion order and his warships a move order, which is why there are no fleets at Bhanu Gamma left.

His colony Menkalinan I has a supply of 4, so should propagate into Bhanu Gamma, but apparently it doesn't.

Seems as if during the last supply propagation update the colonies in Bhanu Gamma were still considered occupied by the green player and thus blocking supply propagation. Although that should not be possible given the order of events (invasion - combat - supply update), this is what it looks like...

@MatGB: Just to be sure: this problem persists only for the turn immediately after the invasion, right? After another turn, your supply does propagate into Bhanu Gamma as expected?

**Comment by MatGB** [comment]
Yeah, it's only for the turn of conquest but production isn't applied to stuff the AI had queued, it is applied correctly so nothing is actually lost (I tested this after posting the bug), but it's annoying for an experienced player and is going to really confuse players that already have problems understanding supply.

I have both turns autosaves zipped if it's needed but it's 4meg so not uploading it unless asked.

Now, possibly related: when giving orders to ships, they can't fly past enemy held systems regardless of what's in them, at first I thought it was stealthed stuff but it's happening for every single AI system. Not fully tested the problem yet but it's an issue for fast low armour stealth scouts vs mines amongst other things. I'll happily post it as a separate bug when I've tested/confirmed it more but it came in at the same time as this and might be from the same source.

**Comment by Vezzra** [comment]
>  I'll happily post it as a separate bug when I've tested/confirmed it more but it came in at the same time as this and might be from the same source.

Yes, please, even if it is actually related, but we can't be sure of that. And while the original bug is just a minor annoyance (which means I won't tag it for the release), this second one is far more serious (which means it probably should be tagged for the release).

**Comment by MatGB** [comment]
OK, related.
![supply-blocking-2](https://cloud.githubusercontent.com/assets/11533206/17858370/5c9a4460-687d-11e6-96a6-15d57d65c099.png)

I've just captured Nexus alpha. In the previous turn I had a fleet there and supply went through the system and up to Iru alpha, where it displayed as competing to supply the deep space node with my scout in. Nexus alpha is blocked as above (but has queued production), but it's blocking the further propagation of supply, preventing my scout from being refueled (as I've now got a fleet in orbit around the system I was competing with).

**Comment by geoffthemedio** [comment]
Try:

https://github.com/freeorion/freeorion/pull/911

**Comment by Vezzra** [comment]
Assuming #911 fixed this issue here too, it can be closed, right?

**Comment by MatGB** [comment]
Yup, appears to now work properly
