### ISSUE TITLE
AI controlled systems block movement with no ships

### ISSUE THREAD

**Issue by MatGB** [freeorion/freeorion#904]
### Environment
- **FreeOrion Version**: [49f1121](https://github.com/freeorion/freeorion/commit/49f112123403b63956e46d2af3956163b4677ce5)
- **Fetched as**
  - [x] Compiled from source
### Description

See attached picture. As discussed in #902 and possibly related, ships can't move past enemy systems without stopping even if the system is empty.

Have confirmed this isn't a display issue, the pictured scout stops in the next turn and takes mine damage which isn't what you want for a fast stealth scout designed to get past obstacles.
### Expected Result

A ship should be able to move through a system that has no blocking enemy presence regardless of ownership of system—this isn't affecting neutral/native systems nor deep space/unowned systems.
### Steps to reproduce
- Order scout ship to move multiple systems at once through enemy held empty systems.
  ![empty-controlled-systems-blocking-move](https://cloud.githubusercontent.com/assets/11533206/17855338/2aefe774-6870-11e6-9297-6d62702fa635.png)

**Comment by Vezzra** [comment]
I assume, "empty systems" meaning systems without enemy armed ships in this case.

**Comment by geoffthemedio** [comment]
Probably due to the fleet code (seemingly inappropriately) using the empire's (supply) unobstructed systems to determine where it can move through...

https://github.com/freeorion/freeorion/blob/master/universe/Fleet.cpp#L251

**Comment by Vezzra** [comment]
Any estimates how hard that might be to fix?

**Comment by MatGB** [comment]
> I assume, "empty systems" meaning systems without enemy armed ships in this case. 

Yes, sorry, thought I'd removed all uses of that unclear term on copyedit.

**Comment by geoffthemedio** [comment]
reverting the change that caused the issue would fix it immediately
otherwise, need to write separate functions for separate purposes, or implement the previous change differently...

**Comment by Vezzra** [comment]
> reverting the change that caused the issue would fix it immediately

Which would in turn require the AI adjustment to the un-fixed supply propagation, which is most likely even more complicated (and the AI team not able to pull it off in time), so not really an option.

> otherwise, need to write separate functions for separate purposes

Well, as you said yourself, the fleet code using the empire's supply unobstructed systems to determine where it can move through is probably inappropriate, so a real fix needs to address that anyway. That however sounds potentially quite complicated/far from trivial, but maybe it's not as bad as it looks... your assessment is probably the best, do you think that can be done until our Sept 4th deadline?

**Comment by geoffthemedio** [comment]
Reportedly fixed by https://github.com/freeorion/freeorion/pull/911

**Comment by Vezzra** [comment]
Thanks!
