### ISSUE TITLE
Remove inactive release branches

### ISSUE THREAD

**Issue by adrianbroher** [freeorion/freeorion#905]
### Description

When using git, gitk or any other repository viewer the inactive _release-0.4.4_ and _release-0.4.5_ branches are listed when showing all branches or when using autocomplete with those tools.  This just adds unnecessary noise into my workflow.  Neither of those branches is required to exist because those release are tagged properly and we're not planning to develop on top of those releases.

So I ask you to delete these branches.

**Comment by Cjkjvfnby** [comment]
Looks OK for me.

Can we invent some workflow so releases will be just tags in our straight master branch?

**Comment by Vezzra** [comment]
> Can we invent some workflow so releases will be just tags in our straight master branch?

That would require some fundamental changes to our workflow. Currently master is our main dev branch, all ongoing development work is committed there. If you use master for the releases, you need a separate dedicated dev branch, and only merge stuff approved for release into master.

AFAIK there are many projects which use that model, but we don't, and I can't see the advantage doing so for FO.

**Comment by Vezzra** [comment]
Done.

**Comment by adrianbroher** [comment]
Thanks.
