### ISSUE TITLE
Game updates break old saves.

### ISSUE THREAD

**Issue by afwbkbc** [freeorion/freeorion#913]
Several times we were unable to finish game because everybody updated game client and didn't want to roll it back. So old savefile didn't work anymore.
Client executable and libraries should be saved into every savefile, so that if its version differs from current - it will be extracted and executed, replacing current running client seamlessly.
In multiplayer games, client for every player will be saved because they can run different OS or have some other differences. Then on game initialisation clients will be sent to them by host and executed on their machines, replacing current client.
Also we can go further and make every savefile self-executable, it seems very convenient - you can then just send savefile to friend and play.

**Comment by Voker57** [comment]
Would you kindly, as it have been pointed out numerous times, bless fine forums at http://www.freeorion.org/forum/ with your innovative suggestions?
