### ISSUE TITLE
Palace Supply Boost Description Wrong?

### ISSUE THREAD

**Issue by geoffthemedio** [freeorion/freeorion#916]
The script for imperial palace seems to give +2 to supply, and I see that in-game in the effect accounting, but the stringtable description says it gives a bonus of 1.

https://github.com/freeorion/freeorion/blob/master/default/scripting/buildings/IMPERIAL_PALACE.focs.txt#L55
https://github.com/freeorion/freeorion/blob/master/default/stringtables/en.txt#L10385

Not sure if I'm missing something...

**Comment by adrianbroher** [comment]
The last time the MaxSupply value was change is commit fc31467c5e3185837f246325bbb5dd35ce763553 (2014-06-02).

The part of the string table that referrers to the MaxSupply is way older 560225cf3d4a20edcc42dfa3c874351ef21de2df (at least 2012-12-02).

I would say the stringtable entry wasn't updated properly.

**Comment by MatGB** [comment]
Agreed, it wap changed I think when we gave planets size dependent supply bonuses but we tried so many variables not surprised we missed an update.

**Comment by Vezzra** [comment]
Yep, pretty much.
