### ISSUE TITLE
Confusing sitrep if Planetary Starlane Drive fails

### ISSUE THREAD

**Issue by Vezzra** [freeorion/freeorion#917]
### Environment
- **FreeOrion Version**: master
- **Operating System**: any
- **Fetched as**
  - Compiled from source
### Description
#869 fixed issues with planetary orbits in conjunction with the planets sidepanel, however, a side effect of these fixes is that moving a planet via the Planetary Starlane Drive will now fail if there are no free orbits in the destination system.

A bug in `System::Insert` prevented this from happening until now, instead planets just got added to the destination system beyond capacity.

Now when trying to move a planet into an already full system will simply result in the planet staying in the original system, but the player still gets a sitrep telling him that his planet arrived at system A, with A being the system the planet is already in. No further explanation is given, which certainly isn't very helpful.

A fix could maybe check if the system actually changed, and if not, give a different sitrep telling the player something along the lines "Moving planet X to system Y failed due to Y already containing too much planets".

**Comment by Vezzra** [comment]
After looking a bit into this I got the impression that there will be no easy/quick fix to this. I certainly am not going to block the release for that, so I'm removing the "Release v0.4.6" milestone.

**Comment by l29ah** [comment]
Also the pedia article should specify the planet limit.

**Comment by Vezzra** [comment]
Yep, absolutely.

**Comment by geoffthemedio** [comment]
@Vezzra Is this resolved?

**Comment by Vezzra** [comment]
Sorry, I don't have the time to test this, but the patch (PR #3028) looks good. I think we can just assume the issue fixed and close this.

Should there still be something wrong, someone will sooner or later stumble over it, and we can open a new issue.

**Comment by Vezzra** [comment]
Fixed by #3028.
