### ISSUE TITLE
Xenophobic frenzy sometimes gives bonus to population

### ISSUE THREAD

**Issue by Voker57** [freeorion/freeorion#924]
Example here: http://dump.bitcheese.net/files/livyvun/xenofun.mps

Empire NBL, planet Yoyo 3 I

**Comment by Vezzra** [comment]
Confirmed on OSX.

@MatGB, IIRC you've been the last one to tinker with the whole xenophobic stuff, any idea what's going on?

**Comment by MatGB** [comment]
It's something related to the Trith self sustaining malus, I've encountered it but not for awhile and had forgotten about it to be honest. Self sustaining and the related malus have had weird issues in edge cases for ages. 

To see it, play trith and look at poor or hostile worlds before you've got the growth techs. I don't think it's release stopping but I'll have another look at it.

**Comment by Vezzra** [comment]
Ok, so it's an edge case. Well, that xenophobic stuff has had these quirks quite a while, and it has been worse. So definitely not release stopping.

If you can figure out the problem and fix it, good, but it's not a priority (for the release).

**Comment by Morlic-fo** [comment]
Should be fixed by #944
