### ISSUE TITLE
Clicking on monster crashes game

### ISSUE THREAD

**Issue by Voker57** [freeorion/freeorion#927]
How to reproduce:

load this save http://dump.bitcheese.net/files/raxocil/kraken.mps
Choose Cynothoglys (can skip adding AIs)
There's a monster icon down from Obaca 3, click it and game will crash.

**Comment by geoffthemedio** [comment]
https://github.com/freeorion/freeorion/commit/510b1650f42a9a4979b668b8e91ddbdfe26a4799
