### ISSUE TITLE
The game crash while it's opening

### ISSUE THREAD

**Issue by LawrenceJGD** [freeorion/freeorion#929]
When I try to run the game a blank windows appears and then Windows say that it's unresponsive.

**Operating System**: Windows 10, version 1607.
**FreeOrion Version**: 0.4.5.
**Build**: 2015-09-01.f203162.
**Downloaded From**: Github releases.
**Graphic Card**: GMA 3150.

PD: Maybe the problem is my GPU. I read somewhere in the wiki that I could disable parts of the game that use OpenGL 2.0 for use an older version, if that's possible, can you help me do that, please?

PD2: Sorry for my bad English.

PD3: I attached a file with the log and configuration in a [.zip file](https://github.com/freeorion/freeorion/files/441545/FreeOrion.zip).

**Comment by geoffthemedio** [comment]
Could you try the latest test build?

**Comment by geoffthemedio** [comment]
Crash appears to happen almost immediately at startup; there are only two lines in the log:

```
2016-08-28 19:42:26.883741 [debug] Client : Logger initialized
2016-08-28 19:42:26.883741 [debug] Client : v0.4.5 [build 2015-09-01.f203162] MSVC 2013
```

There's no way to disable anything that could get it to start on this system, I think, and I'd be surprised if  a newer build would even help.
