### ISSUE TITLE
Make Pedia Accessible From Intro Menu Screen

### ISSUE THREAD

**Issue by geoffthemedio** [freeorion/freeorion#933]
Add a button the the main splash screen menu, perhaps near the one to open freeorion.org, that opens the pedia, so that it is accessible without starting an actual game.

**Comment by Deepsloth** [comment]
That would be a nice feature. I often have to start or load a game just to check something in the pedia.

**Comment by geoffthemedio** [comment]
Implemented by https://github.com/freeorion/freeorion/commit/0000f395e3e8b2872812fff41a190b9edd7e78cd
