### ISSUE TITLE
Long hull type names get clipped in hull list on ship design screen

### ISSUE THREAD

**Issue by Vezzra** [freeorion/freeorion#951]
### Environment
- **FreeOrion Version**: master
- **Fetched as**
  - Compiled from source
### Description

What the title says:

![hulllist](https://cloud.githubusercontent.com/assets/10279417/18310663/0af0c212-7500-11e6-8f96-b610bd318bd8.png)
### Expected Result

If the name is too long to fit, wrap it to more lines instead of clipping it.

**Comment by LGM-Doyle** [comment]
@Vezzra, if you try this and it looks OK, then I'll merge it.

**Comment by Vezzra** [comment]
Looks like @geoffthemedio beat us to it 😉 

Probably a good thing, as my ability to test things is currently, well, hampered.

**Comment by Vezzra** [comment]
Fixed by #1118
