### ISSUE TITLE
Tech list display glitch in other languages than english

### ISSUE THREAD

**Issue by Ouaz** [freeorion/freeorion#958]
### Environment

- **FreeOrion Version**: v0.4.6 pre-release [build 2016-09-04.22b124c]
- **Operating System**: Windows 7
### Description

Due to longer words, the text in the tech list display columns may overlap in languages other than english:

English:
![tech_list_en](https://cloud.githubusercontent.com/assets/11946570/18329906/10ef1b04-7556-11e6-92b8-2a910ed5e979.PNG)

French:
![tech_list_fr](https://cloud.githubusercontent.com/assets/11946570/18329910/17c402be-7556-11e6-97ae-d0ae4ed68d6e.PNG)

Deutsch:
![tech_list_de](https://cloud.githubusercontent.com/assets/11946570/18329915/1c7cf64e-7556-11e6-970c-979a3a46aa2f.PNG)
### Expected Result

Make the tech list columns resizeable.

**Comment by Vezzra** [comment]
Or at least clip the text at the edge of the column.

**Comment by Ouaz** [comment]
Related #758
