### ISSUE TITLE
Add Part Secondary Stat ComplexDoubleValueRef 

### ISSUE THREAD

**Issue by geoffthemedio** [freeorion/freeorion#960]
There is a ValueRef for a part's scripted Capacity stat, and an associated DoubleComplexValueRef parser 

https://github.com/freeorion/freeorion/blob/master/universe/ValueRef.cpp#L1190
https://github.com/freeorion/freeorion/blob/master/parse/DoubleComplexValueRefParser.cpp#L21

For weapons, these are the damage.

There should also be a ValueRef and parser added for a part's secondary stat, which for weapons is the shots per combat round.

**Comment by geoffthemedio** [comment]
https://github.com/freeorion/freeorion/commit/050473c8426bc2607317aeb1f8abdd1f9762cccb

**Comment by adrianbroher** [comment]
@geoffthemedio You know about [Fixes and Closes #N](https://help.github.com/articles/closing-issues-via-commit-messages/)?

**Comment by geoffthemedio** [comment]
No, I just clicked comment and close issue below this box. Does both in one click. Doing it in the commit message would require remembering that there was an issue specifically for something, and then looking it up to get the issue number, possibly when I don't have net access, which was the case for these commits.
