### ISSUE TITLE
Focus dropdown list box gets clipped when it doesn't fit in the window

### ISSUE THREAD

**Issue by Vezzra** [freeorion/freeorion#969]
### Environment
- **FreeOrion Version**: 0.4.6 RC1
- **Operating System**: OSX
- **Fetched as**
  - Binary release
### Description

![clippedfocuslist](https://cloud.githubusercontent.com/assets/10279417/18446516/e96f0b90-7922-11e6-9660-c28fc02504c4.png)

Hopefully the screenshot shows the problem sufficiently well.

If a system has enough planets to fill up the sidepanel down to the bottom, then it's sometimes impossible to access all focus settings of the bottommost planet. The sidepanel scrollbar doesn't allow to scroll down far enough and thus get the bottom planet up far enough so that the entire focus dropdown list box fits within the window.

Also, the box does not get expanded upwards, if it does not fit within the window when expanded, there appears no scrollbar and you can't move the selection with the cursor keys.

The only way to set the focus for such a planet is either by the object window, or if you resize the sidepanel so that the bottom planet is forced to move sufficiently far away from the bottom window border that the dropdown list box fits into the window.
### Expected Result

If the focus dropdown list box extends past the bottom window border, one or more of those should happen:
- Add some extra space below the bottommost planet so you can scroll that planet up high enough for the box to fit within the window when expanded.
- Expand the dropdown list box upward.
- Provide a vertical scrollbar.
- Enable the cursor keys so that a selection can be made using them (+space or enter to confirm the selection).
### Steps to reproduce
- Start new game.
- Resize the FO window so that the focus dropdown list box of your starting colony does not fit within the window when expanded (at least one focus should be entirely in the clipped part of the box).
- Try to select the focus that is in the clipped part of the box.
- You won't succeed... 😉

**Comment by Vezzra** [comment]
As this is a quite annoying bug, I'll tag it for the release, which means there _should_ be a RC2.

However, if no one gets around to fix that suffciently quickly, I won't really block the release for this, and if no actually critical issue turns up, there will also be no RC2. I'll just try to give it some priority by tagging it for the release.

**Comment by geoffthemedio** [comment]
I don't understand the problem... Just expand the buildings, population, or resources panel, then scroll a bit more down.

**Comment by Vezzra** [comment]
Right. I can officially claim the "dumbest assumable user" crown from @Morlic-fo now. 😳 😉

Why I didn't think of that will remain a mystery forever, of course that works. However, it just makes that issue much less annoying, so instead of very annoying it's just very mildly annoying - but it's still not quite right that I need to expand some other UI elements to create enough room for the box to fit.

That's a workaround. A quick and easy one, but still a workaround. I still think the box should open in a way that all it's items are accessible, without having to resort to some kind of trick like this.

So, I think the issue should remain open, and addressed eventually, but of course it's low priority, and I'll remove the "Release v0.4.6" milestone.

**Comment by geoffthemedio** [comment]
Droplists and right-click popup menus sometimes open up instead of down when there's not enough space below, but I find this at least as annoying as having the bottom cut off, as muscle memory expects things to be a particular place relative to the last click.

**Comment by Vezzra** [comment]
No problem, expanding upwards is just one possible solution. Give me a scrollbar, let me use the cursor keys, provide enough extra space below the bottommost planet so I can scroll up high enough without having to expand one of the panels - any of those would be sufficient for me.

**Comment by MatGB** [comment]
This is almost certainly related to, and more annoying than the multiplier dropdowns not being accessible properly if the bottom entry on the production list is just above the scrollbar cutoff. Not release blocking but I'd love for both to be fixed.

**Comment by LGM-Doyle** [comment]
PR #1114 lets you use the cursor keys with the drop down list.  The drop down list is still clipped, so this is not a complete solution.

**Comment by Vezzra** [comment]
Resolved by #1307.
