### ISSUE TITLE
Save game operation fails silently if user resigns and quits the game quickly enough

### ISSUE THREAD

**Issue by Vezzra** [freeorion/freeorion#971]
### Environment
- **FreeOrion Version**: 0.4.6 RC1
- **Operating System**: OSX
- **Fetched as**
  - Binary release
### Description

Something I never noticed before, probably because I very rarely play games that get so big that the save game process takes long enough:

When you initiate a save, the operation returns immediately, but as you can observe by the messages in the message window, the save game operation actually takes some time to complete. However, you are already able to resign and quit the game, in which case the save game operation gets silently aborted.

If you're like me and hide the message window, you don't realize that the save hasn't completed yet - you play your game, want to take a break and resume later, so you save, resign, quit. When you get back, your savegame isn't there, because you quit too quickly.
### Expected Result

If you save a game, one of the following should prevent quitting the game too quickly for the operation to finish:
- Simply don't return control to the user until the save operation has finished.
- Disable all buttons in the game menu that would quit the current game ("Resign", "Load") until the operation has finished, also block all other operations that could quit the application (closing the window etc.).
### Steps to reproduce

Huh, tedious:
- Play a big game long enough to get a save that takes long to finish.
- Initiate a save.
- Resign and quit as quickly as possible.
- The save should not have been created.

**Comment by Vezzra** [comment]
I tagged that for the release for now, because IMO that's a serious bug, but I want to put that decision up for a vote: do you guys agree, or should I remove the "Release v0.4.6" milestone and leave that as a "known issue" for 0.4.6?

**Comment by geoffthemedio** [comment]
This is not a new observation, and is not appropriate to implement fixes for before a release. The save-related messages were added in part to resolve this (and if you're hiding the messages window, its your own fault for not seeing them...)

**Comment by Vezzra** [comment]
Ok, I see. Sorry, didn't want to cause unnecessary fuss, but somehow I missed that the issue existed and the save game message is an attempt to address that.

If that's too complicated to address for the release I'll of course remove the milestone (will set it to "post 0.4.6"). 

> if you're hiding the messages window, its your own fault for not seeing them.

While that is true, the save game message solution is not really sufficient. Saving the game is a too important and essential operation to rely on the user paying attention to a message appearing in a small window in the corner of the screen. It should not be _possible_ to interrupt the operation like that, so I think the issue should remain open (unless there is already another issue about this which I overlooked?).

**Comment by MatGB** [comment]
I forgot to say in last discussion that it would be better if the save window doesn't shut until the operation is done, that's fairly standard in apps. 

It still annoys me and I still sometimes forget to watch messages which, frankly, is am utterly pointless window in single player, we need to either use it for more stuff or not use it for important stuff.
