### ISSUE TITLE
Provide a "noop" effect

### ISSUE THREAD

**Issue by Vezzra** [freeorion/freeorion#973]
There are a few edge cases when an effectsgroup is needed which doesn't actually execute any effects. Currently these are implemented by using constructs like `effects = RemoveSpecial name = ""`.

While that does the trick it's not very pretty. A "noop" effect for that specific purpose would be nice.

**Comment by geoffthemedio** [comment]
https://github.com/freeorion/freeorion/commit/b25a5c1578474d90c8b7462bbcfe5ab855d0800e

**Comment by geoffthemedio** [comment]
Not sure where else to use it...

https://github.com/freeorion/freeorion/commit/8b6a6a340a6c34e0a9c539abdcbcc1f4c8e73d7a
