### ISSUE TITLE
Add a sub-category level in Pedia

### ISSUE THREAD

**Issue by Ouaz** [freeorion/freeorion#976]
### Description

Currently, there are 3 levels in Pedia:

I. Category (key CATEGORY_SOMETHING)
II. Article Title (key STUFF_TITLE)
III. Article Content (key STUFF_TEXT)

Ex: 

I. Category "Game Concepts" (GATEGORY_GAME_CONCEPTS)
II. Article "Fuel" (FUEL_TITLE)
III. Content "Fuel" (FUEL_TEXT)
### Expected Result

A new SUBCATEGORY key would be useful, in order to better sort articles by subject, and avoid huge lists of +50 articles in Pedia (moreover only sorted by alphabetical order):

---

Ex 1:
-> In stringtables:

```
Category > "Game Concepts" (GATEGORY_GAME_CONCEPTS)
Sub-Category > "Meters and Stats" (SUBCATEGORY_METERS_STATS)
Article Title > "Fuel" (FUEL_TITLE)
Fuel Article Content (FUEL_TEXT)
```

In FUEL.focs :

```
Article
    name = "FUEL_TITLE"
    category = "CATEGORY_GAME_CONCEPTS"
    subcategory = "SUBCATEGORY_METERS_STATS"
    short_description = "SHIPS_ARTICLE_SHORT_DESC"
    description = "FUEL_TEXT"
    icon = "icons/meter/fuel.png"
```

Possible sub-categories: 
"Species Traits" (Metabolisms, Telepathy, Xenophoby, etc),
"Focus Types" (Growth Focus, Protection Focus, etc.)
"Diplomacy" (AI agression levels, Peace, etc.)
and so on...

---

Ex 2:
Category > "Ship Design"
Sub-Category > "Cryonic Types", "Endomorphic Types", "Organic Types", "Exploration Types", etc.
Ship designs sorted by hull types and/or functions (Exploration, Colonization, Combat, etc.).

etc.

**Comment by dbenage-cx** [comment]
Related #755 

An alternative approach might be to change categories to support/expect using a different Article.
Currently, doing so will result in the article used as a category to display as top level content (and not list the defining article).
Instead, the UI could support expanding such an article for a list of sub-pages.
This would then allow a descriptive entry to the existing categories.
