### ISSUE TITLE
Numbers in planet suitability report are wrong on the turn right after a planet has been depopulated

### ISSUE THREAD

**Issue by Vezzra** [freeorion/freeorion#979]
### Environment
- **FreeOrion Version**: master
- **Operating System**: any
- **Fetched as**
  - Compiled from source
### Description

If a planet gets depopulated (regardless of the reason), on the turn right after the pop dropped to 0 and the colony has been turned into an outpost, the suitability report for that planet displays wrong numbers. One turn later the numbers are displayed correct again.
### Expected Result

The numbers displayed in the suitability report on the turn right after a planet has been depopulated should not be different from the numbers shown before or after that turn.
### Steps to reproduce
- Check the suitability report of a colony that is about to be depopulated (and write down the numbers).
- Wait until the colony has been depopulated and turned into an outpost.
- On the turn that happened check the suitability report again (and write down the numbers).
- Advance one turn.
- Check the suitability report again (and write down the numbers).
- Compare the numbers from all three checks: the numbers from the first and last check should be the same, but the numbers from the 2nd check should be different.

**Comment by raptor** [comment]
Thanks for starting this.  For reference, here is the topic I started when I noticed it:

http://www.freeorion.org/forum/viewtopic.php?f=28&t=10219

**Comment by MatGB** [comment]
This also applies to the turn you capture ancient guardians as per #837 , so while they're not merged in yet as/when we do merge them in it'll be more important as you're likely to be deciding what to colonise a newly depopulated world a lot more regularly once they are (it's thrown me out more than once and I'm only on my first testgame using them)

**Comment by dbenage-cx** [comment]
I need to test this further, so far it appears to solve the case with Ancient Guardians

``` diff
diff --git a/universe/Planet.cpp b/universe/Planet.cpp
index b11808d..bffabcf 100644
--- a/universe/Planet.cpp
+++ b/universe/Planet.cpp
@@ -867,7 +867,7 @@ void Planet::PopGrowthProductionResearchPhase() {
                 species_it->second++;
         }
         // remove species
-        SetSpecies("");
+        PopCenter::Reset();
     }

     if (!just_conquered) {
```

(Edit: "Appears" as the current/initial pop varies between 10, 2 or 0.0 on my tests without this patch)
