### ISSUE TITLE
Overview of ListBox related improvements.

### ISSUE THREAD

**Issue by LGM-Doyle** [freeorion/freeorion#994]
This issue provides an overview to PRs (#987, #988, #989, #990, #991, #992, #993) 
all related to improving `ListBox` performance.  I will explain the expected 
performance improvements, and how the PRs are partitioned.

The collection of PRs all provide performance improvements to `ListBox`
elements.  They fall into two broad categories:
- improve XML parsing performance in `Font::DetermineLines()`.
- use `PreRender()` to make layout run once per render frame and only when
  the window is visible.

I worked on `DetermineLines()` and `PreRender()` together and they are
interleaved because they were equal contributors to the
performance problems with lists and one would mask the other.
# Testing

I've played about 600 turns of freeorion with the improve_listbox branch.
One game before and one after @adrianbroher's recent `CMakeList` changes.

All of the individual commits compile and I've played turns with some of them.
# Performance improvements

The most dramatic performance improvement I measured was the case mention
in the forums by @MatGB of splitting a fleet in `FleetWnd` with the
`SidePanel` open.  With 200 ships in system and about 20 displayed this case
improved from ~60000 ms to 50 ms.  With the `SidePanel` closed the same case
improves from 3000 ms to 50 ms.

Similarly, a `SaveFileDialog` of 35 files with 6 visible improved from 510 ms
to 21 ms.

The numbers are similar for the production and research queues.
# Breakup of PRs

I've tried to breakup the PRs so there is a first independent set of PRs
that create the new functionality (or fix bugs) and then the dependent PRs
that use the features in the first set of PRs.

Consequently the PRs need to be merged in this order.
## Independent setup/fix PRs

These PRs add the described features, but do not use them.
They are independent of each other.
- #987 remove_MarkupBox  
- #988 fix_SaveFileDialog_focus_change_reset  
- #989 improve_Font_DetermineLines
- #990 add_GG_Wnd_PreRender
- #1001 Convert GG::EventPump time logging to boost::chrono.
## Dependent PRs
- #991 add_GG_DeferredLayout   --   a Layout class that does the layout in `PreRender()`
- #992 use_Wnd_PreRender_various_files   --   use new `DetermineLines()` and `PreRender()` in non `ListBox` classes.
- #993 improve_listbox   --    use all of the above to improve list boxes
- #1002 Implement request #986 rename systems.

The <num> improve_listbox PR contains changes to the ListBox class mixed in
with changes to ListBox derived classes in order to maintain a testable level of
functionality.  Some commits in the middle of this PR have noticeable
artifacts in the ListBoxes.

**Comment by LGM-Doyle** [comment]
I added #1001 which I forgot to break out originally.  I updated the lists of PRs.

**Comment by adrianbroher** [comment]
With the exception of #988 all of the related PR are merged up to this point and the majority of this issue is addressed.  The goal of the leftover PR can be considered without this accumulative issue being open. If someone objects feel free to reopen this.
