### ISSUE TITLE
Hull tags and tech lines need better documentation

### ISSUE THREAD

**Issue by MatGB** [freeorion/freeorion#995]
### Description

Various effects can work on all hulls of a given type, eg: the Solar Concentrator and Robotic Interface Shields. What hulls are affected is unclear or undocumented in game and some players believe they only work on the basic Organic or Robotic hulls. As we hope to expand these effects, the hull tags and similar need better explanations
### Expected Result

Hull tags probably ought to be displayed in hull descriptions and part descriptions, Pedia articles should exist explaining the concept.

**Comment by dbenage-cx** [comment]
Outside of PR #1344 (pedia categories), what other improvements are needed to address this?
I'm not certain about exposing content tags in-game as it may require the player to know the underlying game structure/break immersion. (I realize the object list has them currently)

**Comment by Vezzra** [comment]
Everyone, status report? How far have things proceeded with this? Already done, or at least close to finishing up? If not, I intend to reassign this to the "optional for 0.4.7" milestone. As important and as nice as it is to have better documentation, I don't want to hold up the release for this.

**Comment by dbenage-cx** [comment]
While the documentation can certainly be improved further, hull lines are at least no longer undocumented.  Unless @MatGB objects, and as it is not related to fighters, optional seems ok to me.

**Comment by Vezzra** [comment]
Alright, no objections so far, changing milestone.
