### ISSUE TITLE
Weapon refinement explanations and species effects unclear

### ISSUE THREAD

**Issue by MatGB** [freeorion/freeorion#996]
### Description

Weapon refinement techs need to be clearer about the expected results and mention further modifiers from effect such as species.

Hull design Pedia articles need to clearly say stats are based on your current empire tech and may be further modified by species, etc.
### Expected Result

Improved explanations to prevent confusion for new players and allow further modifiers to be explained and integrated clearly. Discussion here: [Post](http://www.freeorion.org/forum/viewtopic.php?p=85701#p85701)

**Comment by Vezzra** [comment]
Everyone, but especially @MatGB: status report? Any progress on this? Unless already done or close to be done I intend to reassign this to the "optional for 0.4.7" milestone, as I don't want to hold up the release for it.

**Comment by Vezzra** [comment]
No objections so far, so I'm going to reassign.

**Comment by memem359** [comment]
Started a [new discussion thread](http://www.freeorion.org/forum/viewtopic.php?f=28&t=10484) about altering the Pedia weapon text.

I didn't touch the Hull entries, because it wasn't clear to me what needed adjustment.
