### ISSUE TITLE
Pausing production doesn't prevent completion if fleet upkeep changes

### ISSUE THREAD

**Issue by MatGB** [freeorion/freeorion#997]
- **FreeOrion Version**: [1e8c148](https://github.com/freeorion/freeorion/commit/1e8c148343a3538eba5259573eb3a7e3503ceb0b)
  Linux, compiled from source.
### Description

If a nearly-complete ship/group of ships are paused for production and a large change occurs in fleet upkeep (eg: large invasion using many troop ships) then paused ships that now have more pp than needed to complete will complete.

If you've paused ships like this for a reason: eg they're not needed for some time and you want to avoid the upkeep, this is sub optimal, paused should mean paused.
### Expected Result

If something is paused it should be fully paused, not complete if upkeep numbers change.

(NB: we hope to get rid of the current upkeep mechanics but it's not going to happen in the immediate future, pausing is a good new feature and should work as expected)
### Steps to reproduce

Load attached save
[FreeOrion_Mat_Rumpole_0078_20160927_050547.sav.zip](https://github.com/freeorion/freeorion/files/494567/FreeOrion_Mat_Rumpole_0078_20160927_050547.sav.zip)
Order troop ships to invade Imperial Lystena ii
Check production queue has troop ships paused
End turn

**Comment by Dilvish-fo** [comment]
It appears to me that as part of the production queue shift to percentage completion, this issue has been fixed and should be closed.

**Comment by MatGB** [comment]
Yup, good point, had forgotten it, thanks.

**Comment by Vezzra** [comment]
@Dilvish-fo, it definitely has its benefits that you dig through all that open bug reports now... this way some cleanup gets done 😉
