### ISSUE TITLE
Parts and hulls requiring a strategic resource should require supply

### ISSUE THREAD

**Issue by MatGB** [freeorion/freeorion#999]
### Description

Currently, Neutronium and Asteroid parts/hulls only require the building player owns a building for the correct resource, meaning building of these parts cannot be prevented by blocking supply, etc.
### Expected Result

If something requires a strategic resource, another player should be able to block supply and deny that resource, so neutronium and asteroid parts should require an active supply connection not just ownership.

This will probably require an AI update, especially for the Asteroid parts and hulls.

**Comment by Vezzra** [comment]
Hrm, that's actually something we should have taken care of this release cycle, but as this requires AI updates it's a bit late for that now. But we should make sure to address this after 0.4.7.

**Comment by Morlic-fo** [comment]
The proposed changes should be fine without an AI update.

I don't think there is any part of the code that assumes that strategic resources are spread globally. It is just assumed to be some normal shipyard for now.

The checks whether or not a part can be built somewhere are fully queried from the server so no issue on that front either.

**Comment by Vezzra** [comment]
That's good to hear, in that case I set this to be required for 0.4.7.

**Comment by Vezzra** [comment]
Fixed by #1324.
